INFILE &datafid PAD LRECL = 1452;
INPUT
    @    1   VERDATE                              $     8.      
    @    9   REFPER                               $    13.      
    @   22   SAMPLEID                             $    20.      
    @   42   PERSONID                                   2.      
    @   44   GEO_PRV                                    2.      
    @   46   GEODCMAA                                   3.      
    @   49   GEODDA11                                   8.      
    @   57   GEODPC                               $     6.      
    @   63   GEODHR4                                    4.      
    @   67   GEODDHA                                    4.      
    @   71   GEODBCHA                                   4.      
    @   75   GEODLHN                                    4.      
    @   79   GEODDA06                                   8.      
    @   87   GEODFED                                    5.      
    @   92   GEODCSD                                    7.      
    @   99   GEODCD                                     4.      
    @  103   GEODSAT                                    1.      
    @  104   GEODPG11                                   2.      
    @  106   GEODUR                                     1.      
    @  107   GEODUR2                                    1.      
    @  108   GEODSUBZ                                   6.      
    @  114   SAM_CP                               $     6.      
    @  120   SAM_TYP                                    1.      
    @  121   CASETYPE                                   1.      
    @  122   SAMDSHR                                    1.      
    @  123   SAMDLNK                                    1.      
    @  124   ADM_STA                                    2.      
    @  126   ADM_PRX                                    1.      
    @  127   ADM_YOI                                    4.      
    @  131   ADM_MOI                                    2.      
    @  133   ADM_DOI                                    2.      
    @  135   ADM_N09                                    1.      
    @  136   ADM_N10                                    1.      
    @  137   ADM_N11                                    1.      
    @  138   ADM_N12                                    2.      
    @  140   ADM_LHH                                    1.      
    @  141   DHH_AGE                                    3.      
    @  144   DHH_YOB                                    4.      
    @  148   DHH_MOB                                    2.      
    @  150   DHH_DOB                                    2.      
    @  152   DHH_SEX                                    1.      
    @  153   DHH_MS                                     2.      
    @  155   DHHDSAGE                                   3.      
    @  158   DHHDYKD                                    2.      
    @  160   DHHDOKD                                    2.      
    @  162   DHHDLE5                                    2.      
    @  164   DHHD611                                    2.      
    @  166   DHHDL12                                    2.      
    @  168   DHHDL18                                    2.      
    @  170   DHHDLVG                                    2.      
    @  172   DHHDECF                                    2.      
    @  174   DHHDHSZ                                    2.      
    @  176   GEN_01                                     1.      
    @  177   GEN_02                                     1.      
    @  178   GEN_02A2                                   2.      
    @  180   GEN_02B                                    1.      
    @  181   GEN_07                                     1.      
    @  182   GEN_08                                     1.      
    @  183   GEN_09                                     1.      
    @  184   GEN_10                                     1.      
    @  185   GENDHDI                                    1.      
    @  186   GENDMHI                                    1.      
    @  187   GENGSWL                                    1.      
    @  188   MAM_037                                    1.      
    @  189   HWT_2                                      2.      
    @  191   HWT_2A                                     2.      
    @  193   HWT_2B                                     2.      
    @  195   HWT_2C                                     2.      
    @  197   HWT_2D                                     2.      
    @  199   HWT_2E                                     2.      
    @  201   HWT_2F                                     2.      
    @  203   HWT_3                                      3.      
    @  206   HWT_N4                                     1.      
    @  207   HWT_4                                      1.      
    @  208   HWTDHTM                                    5.3     
    @  213   HWTDWTK                                    6.2     
    @  219   HWTDBMI                                    6.2     
    @  225   HWTDISW                                    2.      
    @  227   HWTDCOL                                    1.      
    @  228   HWTDWHO                                    1.      
    @  229   CCC_031                                    1.      
    @  230   CCC_035                                    1.      
    @  231   CCC_036                                    1.      
    @  232   CCC_051                                    1.      
    @  233   CCC_061                                    1.      
    @  234   CCC_071                                    1.      
    @  235   CCC_072                                    1.      
    @  236   CCC_073                                    1.      
    @  237   CCC_073A                                   1.      
    @  238   CCC_073B                                   1.      
    @  239   CCC_081                                    1.      
    @  240   CCC_091                                    1.      
    @  241   CCC_101                                    1.      
    @  242   CCC_102                                    3.      
    @  245   CCC_10A                                    1.      
    @  246   CCC_10B                                    1.      
    @  247   CCC_10C                                    2.      
    @  249   CCC_105                                    1.      
    @  250   CCC_106                                    1.      
    @  251   CCC_121                                    1.      
    @  252   CCC_131                                    1.      
    @  253   CCC_31A                                    1.      
    @  254   CCC_141                                    1.      
    @  255   CCC_151                                    1.      
    @  256   CCC_161                                    1.      
    @  257   CCC_171                                    1.      
    @  258   CCC_17A                                    1.      
    @  259   CCC_173                                    1.      
    @  260   CCC_181                                    1.      
    @  261   CCC_280                                    1.      
    @  262   CCC_290                                    1.      
    @  263   CCCDDIA                                    1.      
    @  264   DOHUI                                      1.      
    @  265   HUI_01                                     1.      
    @  266   HUI_02                                     1.      
    @  267   HUI_03                                     1.      
    @  268   HUI_04                                     1.      
    @  269   HUI_05                                     1.      
    @  270   HUI_06                                     1.      
    @  271   HUI_07                                     1.      
    @  272   HUI_07A                                    1.      
    @  273   HUI_08                                     1.      
    @  274   HUI_09                                     1.      
    @  275   HUI_10                                     1.      
    @  276   HUI_11                                     1.      
    @  277   HUI_12                                     1.      
    @  278   HUI_13                                     1.      
    @  279   HUI_14                                     1.      
    @  280   HUI_15                                     1.      
    @  281   HUI_16                                     1.      
    @  282   HUI_17                                     1.      
    @  283   HUI_18                                     1.      
    @  284   HUI_19                                     1.      
    @  285   HUI_20                                     1.      
    @  286   HUI_21                                     1.      
    @  287   HUI_22                                     1.      
    @  288   HUI_23                                     1.      
    @  289   HUI_24                                     1.      
    @  290   HUI_25                                     1.      
    @  291   HUI_26                                     1.      
    @  292   HUI_27                                     1.      
    @  293   HUIDVIS                                    2.      
    @  295   HUIDHER                                    2.      
    @  297   HUIDSPE                                    1.      
    @  298   HUIDMOB                                    2.      
    @  300   HUIDDEX                                    2.      
    @  302   HUIDEMO                                    1.      
    @  303   HUIDCOG                                    2.      
    @  305   HUIDHSI                                    6.3     
    @  311   HUP_01                                     1.      
    @  312   HUP_02                                     1.      
    @  313   HUP_03                                     1.      
    @  314   HUPDPAD                                    1.      
    @  315   HCU_1AA                                    1.      
    @  316   HCU_1BA                                    1.      
    @  317   HCU_1BB                                    1.      
    @  318   HCU_1BC                                    1.      
    @  319   HCU_1BD                                    1.      
    @  320   HCU_1BE                                    1.      
    @  321   HCU_1A1                                    1.      
    @  322   HCU_1A2                                    2.      
    @  324   HCU_1AC                                    2.      
    @  326   CHP_01                                     1.      
    @  327   CHP_02                                     3.      
    @  330   CHP_03                                     1.      
    @  331   CHP_04                                     3.      
    @  334   CHP_05                                     2.      
    @  336   CHP_06                                     1.      
    @  337   CHP_07                                     2.      
    @  339   CHP_08                                     1.      
    @  340   CHP_09                                     3.      
    @  343   CHP_10                                     2.      
    @  345   CHP_11                                     1.      
    @  346   CHP_12                                     3.      
    @  349   CHP_13                                     2.      
    @  351   CHP_14                                     1.      
    @  352   CHP_15                                     3.      
    @  355   CHPDMDC                                    3.      
    @  358   RAC_1                                      1.      
    @  359   RAC_2A                                     1.      
    @  360   RAC_2B1                                    1.      
    @  361   RAC_2B2                                    1.      
    @  362   RAC_2C                                     1.      
    @  363   RAC_5                                      2.      
    @  365   RACDIMP                                    1.      
    @  366   RACDPAL                                    1.      
    @  367   DOADL                                      1.      
    @  368   ADL_01                                     1.      
    @  369   ADL_02                                     1.      
    @  370   ADL_03                                     1.      
    @  371   ADL_04                                     1.      
    @  372   ADL_05                                     1.      
    @  373   ADL_06                                     1.      
    @  374   ADLF6R                                     1.      
    @  375   FLU_160                                    1.      
    @  376   FLU_162                                    1.      
    @  377   FLU_164                                    2.      
    @  379   FLU_165                                    1.      
    @  380   FLU_66A                                    1.      
    @  381   FLU_66B                                    1.      
    @  382   FLU_66C                                    1.      
    @  383   FLU_66D                                    1.      
    @  384   FLU_66E                                    1.      
    @  385   FLU_66F                                    1.      
    @  386   FLU_66G                                    1.      
    @  387   FLU_66H                                    1.      
    @  388   FLU_66I                                    1.      
    @  389   FLU_66J                                    1.      
    @  390   FLU_66K                                    1.      
    @  391   FLU_66L                                    1.      
    @  392   FLU_66M                                    1.      
    @  393   FLU_66O                                    1.      
    @  394   FLU_66N                                    1.      
    @  395   FVC_1A                                     1.      
    @  396   FVC_1B                                     2.      
    @  398   FVC_1C                                     2.      
    @  400   FVC_1D                                     3.      
    @  403   FVC_1E                                     3.      
    @  406   FVC_2A                                     1.      
    @  407   FVC_2B                                     2.      
    @  409   FVC_2C                                     2.      
    @  411   FVC_2D                                     3.      
    @  414   FVC_2E                                     3.      
    @  417   FVC_3A                                     1.      
    @  418   FVC_3B                                     2.      
    @  420   FVC_3C                                     2.      
    @  422   FVC_3D                                     3.      
    @  425   FVC_3E                                     3.      
    @  428   FVC_4A                                     1.      
    @  429   FVC_4B                                     2.      
    @  431   FVC_4C                                     2.      
    @  433   FVC_4D                                     3.      
    @  436   FVC_4E                                     3.      
    @  439   FVC_5A                                     1.      
    @  440   FVC_5B                                     2.      
    @  442   FVC_5C                                     2.      
    @  444   FVC_5D                                     3.      
    @  447   FVC_5E                                     3.      
    @  450   FVC_6A                                     1.      
    @  451   FVC_6B                                     2.      
    @  453   FVC_6C                                     2.      
    @  455   FVC_6D                                     3.      
    @  458   FVC_6E                                     3.      
    @  461   FVCDJUI                                    5.1     
    @  466   FVCDFRU                                    5.1     
    @  471   FVCDSAL                                    5.1     
    @  476   FVCDPOT                                    5.1     
    @  481   FVCDCAR                                    5.1     
    @  486   FVCDVEG                                    5.1     
    @  491   FVCDTOT                                    5.1     
    @  496   FVCGTOT                                    1.      
    @  497   PAC_1A                                     1.      
    @  498   PAC_1B                                     1.      
    @  499   PAC_1C                                     1.      
    @  500   PAC_1D                                     1.      
    @  501   PAC_1E                                     1.      
    @  502   PAC_1F                                     1.      
    @  503   PAC_1G                                     1.      
    @  504   PAC_1H                                     1.      
    @  505   PAC_1I                                     1.      
    @  506   PAC_1J                                     1.      
    @  507   PAC_1K                                     1.      
    @  508   PAC_1L                                     1.      
    @  509   PAC_1M                                     1.      
    @  510   PAC_1N                                     1.      
    @  511   PAC_1O                                     1.      
    @  512   PAC_1P                                     1.      
    @  513   PAC_1Q                                     1.      
    @  514   PAC_1R                                     1.      
    @  515   PAC_1S                                     1.      
    @  516   PAC_1T                                     1.      
    @  517   PAC_1Z                                     1.      
    @  518   PAC_1U                                     1.      
    @  519   PAC_1V                                     1.      
    @  520   PAC_1W                                     1.      
    @  521   PAC_1X                                     1.      
    @  522   PAC_2A                                     3.      
    @  525   PAC_3A                                     1.      
    @  526   PAC_2B                                     3.      
    @  529   PAC_3B                                     1.      
    @  530   PAC_2C                                     3.      
    @  533   PAC_3C                                     1.      
    @  534   PAC_2D                                     3.      
    @  537   PAC_3D                                     1.      
    @  538   PAC_2E                                     3.      
    @  541   PAC_3E                                     1.      
    @  542   PAC_2F                                     3.      
    @  545   PAC_3F                                     1.      
    @  546   PAC_2G                                     3.      
    @  549   PAC_3G                                     1.      
    @  550   PAC_2H                                     3.      
    @  553   PAC_3H                                     1.      
    @  554   PAC_2I                                     3.      
    @  557   PAC_3I                                     1.      
    @  558   PAC_2J                                     3.      
    @  561   PAC_3J                                     1.      
    @  562   PAC_2K                                     3.      
    @  565   PAC_3K                                     1.      
    @  566   PAC_2L                                     3.      
    @  569   PAC_3L                                     1.      
    @  570   PAC_2M                                     3.      
    @  573   PAC_3M                                     1.      
    @  574   PAC_2N                                     3.      
    @  577   PAC_3N                                     1.      
    @  578   PAC_2O                                     3.      
    @  581   PAC_3O                                     1.      
    @  582   PAC_2P                                     3.      
    @  585   PAC_3P                                     1.      
    @  586   PAC_2Q                                     3.      
    @  589   PAC_3Q                                     1.      
    @  590   PAC_2R                                     3.      
    @  593   PAC_3R                                     1.      
    @  594   PAC_2S                                     3.      
    @  597   PAC_3S                                     1.      
    @  598   PAC_2T                                     3.      
    @  601   PAC_3T                                     1.      
    @  602   PAC_2Z                                     3.      
    @  605   PAC_3Z                                     1.      
    @  606   PAC_2U                                     3.      
    @  609   PAC_3U                                     1.      
    @  610   PAC_2W                                     3.      
    @  613   PAC_3W                                     1.      
    @  614   PAC_2X                                     3.      
    @  617   PAC_3X                                     1.      
    @  618   PAC_7                                      1.      
    @  619   PAC_7A                                     3.      
    @  622   PAC_7B                                     1.      
    @  623   PAC_8                                      1.      
    @  624   PAC_8A                                     3.      
    @  627   PAC_8B                                     1.      
    @  628   PACDEE                                     4.1     
    @  632   PACFLEI                                    1.      
    @  633   PACDFM                                     3.      
    @  636   PACDFR                                     1.      
    @  637   PACFD                                      1.      
    @  638   PACDPAI                                    1.      
    @  639   PACDLTI                                    1.      
    @  640   PACDTLE                                    4.1     
    @  644   PACFLTI                                    1.      
    @  645   DOUPE                                      1.      
    @  646   UPE_01A                                    1.      
    @  647   UPE_01                                     1.      
    @  648   UPE_02                                     1.      
    @  649   UPE_02A                                    1.      
    @  650   UPE_02B                                    1.      
    @  651   UPE_02C                                    1.      
    @  652   UPE_02D                                    1.      
    @  653   UPE_03A                                    1.      
    @  654   UPE_03B                                    1.      
    @  655   UPE_04A                                    1.      
    @  656   UPE_05A                                    1.      
    @  657   UPE_05B                                    1.      
    @  658   UPE_06                                     1.      
    @  659   UPE_06A                                    1.      
    @  660   UPE_06B                                    1.      
    @  661   UPE_06C                                    1.      
    @  662   UPE_07                                     1.      
    @  663   UPE_07A                                    1.      
    @  664   UPEFILS                                    1.      
    @  665   UPEFSKB                                    1.      
    @  666   UPEFSNB                                    1.      
    @  667   DOINJ                                      1.      
    @  668   REP_1A                                     1.      
    @  669   REP_2                                      1.      
    @  670   REP_3                                      2.      
    @  672   REP_3A                                     1.      
    @  673   REP_4                                      1.      
    @  674   REP_5A                                     1.      
    @  675   REP_5B                                     1.      
    @  676   REP_5C                                     1.      
    @  677   REP_5D                                     1.      
    @  678   REP_5F                                     1.      
    @  679   REP_5G                                     1.      
    @  680   REP_5H                                     1.      
    @  681   REP_5I                                     1.      
    @  682   INJ_01                                     1.      
    @  683   INJ_02                                     2.      
    @  685   INJ_03                                     2.      
    @  687   INJ_04                                     1.      
    @  688   INJ_05                                     2.      
    @  690   INJ_06                                     2.      
    @  692   INJ_07                                     1.      
    @  693   INJ_08                                     2.      
    @  695   INJ_09                                     2.      
    @  697   INW_01                                     1.      
    @  698   INWF02                                     1.      
    @  699   INWF03                                     1.      
    @  700   INWCSIC                              $     6.      
    @  706   INWCSOC                              $     6.      
    @  712   INWF04                                     1.      
    @  713   INWDOCG                              $     2.      
    @  715   INWDING                              $     2.      
    @  717   INJ_10                                     1.      
    @  718   INJ_11A                                    2.      
    @  720   INJ_12                                     2.      
    @  722   INJ_12A                                    1.      
    @  723   INJ_13                                     1.      
    @  724   INJ_14A                                    1.      
    @  725   INJ_14B                                    1.      
    @  726   INJ_14C                                    1.      
    @  727   INJ_14L                                    1.      
    @  728   INJ_14M                                    1.      
    @  729   INJ_14F                                    1.      
    @  730   INJ_14N                                    1.      
    @  731   INJ_14O                                    1.      
    @  732   INJ_14K                                    1.      
    @  733   INJ_15                                     1.      
    @  734   INJ_15A                                    1.      
    @  735   INJ_16                                     1.      
    @  736   INJ_17                                     2.      
    @  738   INJDTBS                                    4.      
    @  742   INJDCAU                                    2.      
    @  744   INJDCBP                                    4.      
    @  748   INJDSTT                                    1.      
    @  749   SMK_01A                                    1.      
    @  750   SMK_01B                                    1.      
    @  751   SMK_01C                                    3.      
    @  754   SMK_202                                    1.      
    @  755   SMK_203                                    3.      
    @  758   SMK_204                                    3.      
    @  761   SMK_05B                                    3.      
    @  764   SMK_05C                                    2.      
    @  766   SMK_05D                                    1.      
    @  767   SMK_06A                                    1.      
    @  768   SMK_06B                                    2.      
    @  770   SMK_06C                                    3.      
    @  773   SMK_207                                    3.      
    @  776   SMK_208                                    3.      
    @  779   SMK_09A                                    1.      
    @  780   SMK_09B                                    2.      
    @  782   SMK_09C                                    3.      
    @  785   SMK_10                                     1.      
    @  786   SMK_10A                                    1.      
    @  787   SMK_10B                                    2.      
    @  789   SMK_10C                                    3.      
    @  792   SMKDSTY                                    2.      
    @  794   SMKDSTP                                    3.      
    @  797   SMKDYCS                                    3.      
    @  800   ETS_10                                     1.      
    @  801   ETS_11                                     2.      
    @  803   ETS_20                                     1.      
    @  804   ETS_20B                                    1.      
    @  805   ETS_35                                     1.      
    @  806   ETS_36                                     1.      
    @  807   ETS_37A                                    1.      
    @  808   ETS_37B                                    1.      
    @  809   ETS_37C                                    1.      
    @  810   ETS_37D                                    1.      
    @  811   ALC_1                                      1.      
    @  812   ALC_2                                      2.      
    @  814   ALC_3                                      2.      
    @  816   ALCDTTM                                    1.      
    @  817   DOSXB                                      1.      
    @  818   SXB_1                                      1.      
    @  819   SXB_2                                      3.      
    @  822   SXB_3                                      1.      
    @  823   SXB_4                                      1.      
    @  824   SXB_07                                     1.      
    @  825   SXB_7A                                     1.      
    @  826   SXB_09                                     1.      
    @  827   SXB_10                                     2.      
    @  829   SXB_11                                     1.      
    @  830   SXB_12A                                    1.      
    @  831   SXB_12B                                    1.      
    @  832   SXB_12C                                    1.      
    @  833   SXB_12D                                    1.      
    @  834   SXB_12F                                    1.      
    @  835   SXB_12E                                    1.      
    @  836   SXB_13A                                    1.      
    @  837   SXB_13B                                    1.      
    @  838   SXB_13C                                    1.      
    @  839   SXB_13D                                    1.      
    @  840   SXB_13F                                    1.      
    @  841   SXB_13G                                    1.      
    @  842   SXB_13E                                    1.      
    @  843   DOACC                                      1.      
    @  844   ACC_10                                     1.      
    @  845   ACC_11                                     1.      
    @  846   ACC_12A                                    1.      
    @  847   ACC_12B                                    1.      
    @  848   ACC_12C                                    1.      
    @  849   ACC_12D                                    1.      
    @  850   ACC_12E                                    1.      
    @  851   ACC_12F                                    1.      
    @  852   ACC_12G                                    1.      
    @  853   ACC_12H                                    1.      
    @  854   ACC_12I                                    1.      
    @  855   ACC_12J                                    1.      
    @  856   ACC_12K                                    1.      
    @  857   ACC_12L                                    1.      
    @  858   ACC_12M                                    1.      
    @  859   ACC_12N                                    1.      
    @  860   ACC_20                                     1.      
    @  861   ACC_21                                     1.      
    @  862   ACC_22A                                    1.      
    @  863   ACC_22B                                    1.      
    @  864   ACC_22C                                    1.      
    @  865   ACC_22D                                    1.      
    @  866   ACC_22E                                    1.      
    @  867   ACC_22F                                    1.      
    @  868   ACC_22G                                    1.      
    @  869   ACC_22H                                    1.      
    @  870   ACC_22I                                    1.      
    @  871   ACC_22J                                    1.      
    @  872   ACC_22K                                    1.      
    @  873   ACC_22L                                    1.      
    @  874   ACC_22M                                    1.      
    @  875   ACC_22N                                    1.      
    @  876   ACC_22O                                    1.      
    @  877   ACC_30                                     1.      
    @  878   ACC_31                                     1.      
    @  879   ACC_32A                                    1.      
    @  880   ACC_32B                                    1.      
    @  881   ACC_32C                                    1.      
    @  882   ACC_32D                                    1.      
    @  883   ACC_32E                                    1.      
    @  884   ACC_32F                                    1.      
    @  885   ACC_32G                                    1.      
    @  886   ACC_32H                                    1.      
    @  887   ACC_32I                                    1.      
    @  888   ACC_32J                                    1.      
    @  889   ACC_32K                                    1.      
    @  890   ACC_32L                                    1.      
    @  891   ACC_32M                                    1.      
    @  892   ACC_32N                                    1.      
    @  893   ACC_40                                     1.      
    @  894   ACC_40A                                    1.      
    @  895   ACC_40B                                    1.      
    @  896   ACC_40C                                    1.      
    @  897   ACC_40D                                    1.      
    @  898   ACC_40E                                    1.      
    @  899   ACC_40F                                    1.      
    @  900   ACC_40G                                    1.      
    @  901   ACC_41                                     1.      
    @  902   ACC_42                                     1.      
    @  903   ACC_43A                                    1.      
    @  904   ACC_43B                                    1.      
    @  905   ACC_43C                                    1.      
    @  906   ACC_43D                                    1.      
    @  907   ACC_43E                                    1.      
    @  908   ACC_43F                                    1.      
    @  909   ACC_43G                                    1.      
    @  910   ACC_43H                                    1.      
    @  911   ACC_43I                                    1.      
    @  912   ACC_44                                     1.      
    @  913   ACC_45A                                    1.      
    @  914   ACC_45B                                    1.      
    @  915   ACC_45C                                    1.      
    @  916   ACC_45D                                    1.      
    @  917   ACC_45E                                    1.      
    @  918   ACC_45F                                    1.      
    @  919   ACC_45G                                    1.      
    @  920   ACC_45H                                    1.      
    @  921   ACC_45I                                    1.      
    @  922   ACC_46                                     1.      
    @  923   ACC_47A                                    1.      
    @  924   ACC_47B                                    1.      
    @  925   ACC_47C                                    1.      
    @  926   ACC_47D                                    1.      
    @  927   ACC_47E                                    1.      
    @  928   ACC_47F                                    1.      
    @  929   ACC_47G                                    1.      
    @  930   ACC_47H                                    1.      
    @  931   ACC_47I                                    1.      
    @  932   ACC_50A                                    1.      
    @  933   ACC_50                                     1.      
    @  934   ACC_51                                     1.      
    @  935   ACC_52                                     1.      
    @  936   ACC_53A                                    1.      
    @  937   ACC_53B                                    1.      
    @  938   ACC_53C                                    1.      
    @  939   ACC_53D                                    1.      
    @  940   ACC_53E                                    1.      
    @  941   ACC_53F                                    1.      
    @  942   ACC_53G                                    1.      
    @  943   ACC_53H                                    1.      
    @  944   ACC_53I                                    1.      
    @  945   ACC_53J                                    1.      
    @  946   ACC_53K                                    1.      
    @  947   ACC_53L                                    1.      
    @  948   ACC_53M                                    1.      
    @  949   ACC_54                                     1.      
    @  950   ACC_55A                                    1.      
    @  951   ACC_55B                                    1.      
    @  952   ACC_55C                                    1.      
    @  953   ACC_55D                                    1.      
    @  954   ACC_55E                                    1.      
    @  955   ACC_55F                                    1.      
    @  956   ACC_55G                                    1.      
    @  957   ACC_55H                                    1.      
    @  958   ACC_55I                                    1.      
    @  959   ACC_55J                                    1.      
    @  960   ACC_55K                                    1.      
    @  961   ACC_55L                                    1.      
    @  962   ACC_55M                                    1.      
    @  963   ACC_60                                     1.      
    @  964   ACC_61                                     1.      
    @  965   ACC_62                                     1.      
    @  966   ACC_63A                                    1.      
    @  967   ACC_63B                                    1.      
    @  968   ACC_63C                                    1.      
    @  969   ACC_63D                                    1.      
    @  970   ACC_63E                                    1.      
    @  971   ACC_63F                                    1.      
    @  972   ACC_63G                                    1.      
    @  973   ACC_63H                                    1.      
    @  974   ACC_63I                                    1.      
    @  975   ACC_63J                                    1.      
    @  976   ACC_63K                                    1.      
    @  977   ACC_63L                                    1.      
    @  978   ACC_63M                                    1.      
    @  979   ACC_64                                     1.      
    @  980   ACC_65A                                    1.      
    @  981   ACC_65B                                    1.      
    @  982   ACC_65C                                    1.      
    @  983   ACC_65D                                    1.      
    @  984   ACC_65E                                    1.      
    @  985   ACC_65F                                    1.      
    @  986   ACC_65G                                    1.      
    @  987   ACC_65H                                    1.      
    @  988   ACC_65I                                    1.      
    @  989   ACC_65J                                    1.      
    @  990   ACC_65K                                    1.      
    @  991   ACC_65L                                    1.      
    @  992   ACC_65M                                    1.      
    @  993   ACC_66                                     1.      
    @  994   ACC_67A                                    1.      
    @  995   ACC_67B                                    1.      
    @  996   ACC_67C                                    1.      
    @  997   ACC_67D                                    1.      
    @  998   ACC_67E                                    1.      
    @  999   ACC_67F                                    1.      
    @ 1000   ACC_67G                                    1.      
    @ 1001   ACC_67H                                    1.      
    @ 1002   ACC_67I                                    1.      
    @ 1003   ACC_67J                                    1.      
    @ 1004   ACC_67K                                    1.      
    @ 1005   ACC_67L                                    1.      
    @ 1006   ACC_67M                                    1.      
    @ 1007   DOWTM                                      1.      
    @ 1008   WTM_01                                     1.      
    @ 1009   WTM_02                                     2.      
    @ 1011   WTM_03                                     1.      
    @ 1012   WTM_04                                     1.      
    @ 1013   WTM_05                                     1.      
    @ 1014   WTM_06A                                    1.      
    @ 1015   WTM_06B                                    1.      
    @ 1016   WTM_06C                                    1.      
    @ 1017   WTM_06D                                    1.      
    @ 1018   WTM_06E                                    1.      
    @ 1019   WTM_06F                                    1.      
    @ 1020   WTM_06G                                    1.      
    @ 1021   WTM_06H                                    1.      
    @ 1022   WTM_06I                                    1.      
    @ 1023   WTM_06J                                    1.      
    @ 1024   WTM_06K                                    1.      
    @ 1025   WTM_06L                                    1.      
    @ 1026   WTM_06M                                    1.      
    @ 1027   WTM_07A                                    3.      
    @ 1030   WTM_07B                                    1.      
    @ 1031   WTM_08A                                    3.      
    @ 1034   WTM_08B                                    1.      
    @ 1035   WTM_10                                     1.      
    @ 1036   WTM_11A                                    3.      
    @ 1039   WTM_11B                                    1.      
    @ 1040   WTM_12                                     1.      
    @ 1041   WTM_13A                                    1.      
    @ 1042   WTM_13B                                    1.      
    @ 1043   WTM_13C                                    1.      
    @ 1044   WTM_14                                     1.      
    @ 1045   WTM_15A                                    1.      
    @ 1046   WTM_15B                                    1.      
    @ 1047   WTM_15C                                    1.      
    @ 1048   WTM_15D                                    1.      
    @ 1049   WTM_15E                                    1.      
    @ 1050   WTM_15F                                    1.      
    @ 1051   WTM_15G                                    1.      
    @ 1052   WTM_15H                                    1.      
    @ 1053   WTM_15I                                    1.      
    @ 1054   WTM_15J                                    1.      
    @ 1055   WTM_15K                                    1.      
    @ 1056   WTM_15L                                    1.      
    @ 1057   WTM_16                                     2.      
    @ 1059   WTM_17                                     1.      
    @ 1060   WTM_18                                     1.      
    @ 1061   WTM_19                                     1.      
    @ 1062   WTM_20A                                    1.      
    @ 1063   WTM_20B                                    1.      
    @ 1064   WTM_20C                                    1.      
    @ 1065   WTM_20D                                    1.      
    @ 1066   WTM_20E                                    1.      
    @ 1067   WTM_20F                                    1.      
    @ 1068   WTM_20G                                    1.      
    @ 1069   WTM_20H                                    1.      
    @ 1070   WTM_20I                                    1.      
    @ 1071   WTM_20J                                    1.      
    @ 1072   WTM_20K                                    1.      
    @ 1073   WTM_20L                                    1.      
    @ 1074   WTM_20M                                    1.      
    @ 1075   WTM_20N                                    1.      
    @ 1076   WTM_21A                                    3.      
    @ 1079   WTM_21B                                    1.      
    @ 1080   WTM_22                                     1.      
    @ 1081   WTM_23A                                    3.      
    @ 1084   WTM_23B                                    1.      
    @ 1085   WTM_24                                     1.      
    @ 1086   WTM_25A                                    3.      
    @ 1089   WTM_25B                                    1.      
    @ 1090   WTM_26                                     1.      
    @ 1091   WTM_27A                                    1.      
    @ 1092   WTM_27B                                    1.      
    @ 1093   WTM_27C                                    1.      
    @ 1094   WTM_27D                                    1.      
    @ 1095   WTM_28                                     1.      
    @ 1096   WTM_29A                                    1.      
    @ 1097   WTM_29B                                    1.      
    @ 1098   WTM_29C                                    1.      
    @ 1099   WTM_29D                                    1.      
    @ 1100   WTM_29E                                    1.      
    @ 1101   WTM_29F                                    1.      
    @ 1102   WTM_29G                                    1.      
    @ 1103   WTM_29H                                    1.      
    @ 1104   WTM_29I                                    1.      
    @ 1105   WTM_29J                                    1.      
    @ 1106   WTM_29K                                    1.      
    @ 1107   WTM_29L                                    1.      
    @ 1108   WTM_30                                     1.      
    @ 1109   WTM_31                                     1.      
    @ 1110   WTM_32                                     1.      
    @ 1111   WTM_33                                     1.      
    @ 1112   WTM_34                                     1.      
    @ 1113   WTM_35                                     1.      
    @ 1114   WTM_36                                     1.      
    @ 1115   WTM_37A                                    1.      
    @ 1116   WTM_37B                                    1.      
    @ 1117   WTM_37C                                    1.      
    @ 1118   WTM_37D                                    1.      
    @ 1119   WTM_37E                                    1.      
    @ 1120   WTM_37F                                    1.      
    @ 1121   WTM_37G                                    1.      
    @ 1122   WTM_37H                                    1.      
    @ 1123   WTM_37I                                    1.      
    @ 1124   WTM_37J                                    1.      
    @ 1125   WTM_37K                                    1.      
    @ 1126   WTM_37L                                    1.      
    @ 1127   WTM_37M                                    1.      
    @ 1128   WTM_38A                                    3.      
    @ 1131   WTM_38B                                    1.      
    @ 1132   WTM_39A                                    3.      
    @ 1135   WTM_39B                                    1.      
    @ 1136   WTM_40                                     1.      
    @ 1137   WTM_41A                                    3.      
    @ 1140   WTM_41B                                    1.      
    @ 1141   WTM_42                                     1.      
    @ 1142   WTM_43                                     1.      
    @ 1143   WTM_44                                     1.      
    @ 1144   WTM_45A                                    1.      
    @ 1145   WTM_45B                                    1.      
    @ 1146   WTM_45C                                    1.      
    @ 1147   WTM_45D                                    1.      
    @ 1148   WTM_45E                                    1.      
    @ 1149   WTM_45F                                    1.      
    @ 1150   WTM_45G                                    1.      
    @ 1151   WTM_45H                                    1.      
    @ 1152   WTM_45I                                    1.      
    @ 1153   WTM_45J                                    1.      
    @ 1154   WTM_45K                                    1.      
    @ 1155   WTM_45L                                    1.      
    @ 1156   WTMDSO                                     4.      
    @ 1160   WTMDSN                                     4.      
    @ 1164   WTMDSA                                     4.      
    @ 1168   WTMDCO                                     4.      
    @ 1172   WTMDCN                                     4.      
    @ 1176   WTMDCA                                     4.      
    @ 1180   WTMDTO                                     4.      
    @ 1184   WTMDTN                                     4.      
    @ 1188   WTMDTA                                     4.      
    @ 1192   LBS_01                                     1.      
    @ 1193   LBS_02                                     1.      
    @ 1194   LBS_03                                     1.      
    @ 1195   LBS_11                                     1.      
    @ 1196   LBS_31                                     1.      
    @ 1197   LBSF32                                     1.      
    @ 1198   LBSF33                                     1.      
    @ 1199   LBSF34                                     1.      
    @ 1200   LBSF35                                     1.      
    @ 1201   LBSCSIC                              $     6.      
    @ 1207   LBSCSOC                              $     6.      
    @ 1213   LBSF36                                     1.      
    @ 1214   LBS_42                                     3.      
    @ 1217   LBS_53                                     3.      
    @ 1220   LBSDHPW                                    3.      
    @ 1223   LBSDPFT                                    1.      
    @ 1224   LBSDWSS                                    1.      
    @ 1225   LBSDING                              $     2.      
    @ 1227   LBSDOCG                              $     2.      
    @ 1229   SDC_8                                      1.      
    @ 1230   SDC_9                                      1.      
    @ 1231   SDCCCB13                                   5.      
    @ 1236   SDCGCB10                                   2.      
    @ 1238   SDC_2                                      1.      
    @ 1239   SDC_3                                      4.      
    @ 1243   SDC_4A                                     1.      
    @ 1244   SDC_4B                                     1.      
    @ 1245   SDC_4C                                     1.      
    @ 1246   SDC_4D                                     1.      
    @ 1247   SDC_4E                                     1.      
    @ 1248   SDC_4F                                     1.      
    @ 1249   SDC_4G                                     1.      
    @ 1250   SDC_4H                                     1.      
    @ 1251   SDC_4I                                     1.      
    @ 1252   SDC_4J                                     1.      
    @ 1253   SDC_4K                                     1.      
    @ 1254   SDC_4L                                     1.      
    @ 1255   SDC_4M                                     1.      
    @ 1256   SDC_4N                                     1.      
    @ 1257   SDC_4T                                     1.      
    @ 1258   SDC_4U                                     1.      
    @ 1259   SDC_4V                                     1.      
    @ 1260   SDC_4P                                     1.      
    @ 1261   SDC_4Q                                     1.      
    @ 1262   SDC_4R                                     1.      
    @ 1263   SDC_4S                                     1.      
    @ 1264   SDC_41                                     1.      
    @ 1265   SDC_42A                                    1.      
    @ 1266   SDC_42B                                    1.      
    @ 1267   SDC_42C                                    1.      
    @ 1268   SDC_43A                                    1.      
    @ 1269   SDC_43C                                    1.      
    @ 1270   SDC_43B                                    1.      
    @ 1271   SDC_43D                                    1.      
    @ 1272   SDC_43E                                    1.      
    @ 1273   SDC_43F                                    1.      
    @ 1274   SDC_43H                                    1.      
    @ 1275   SDC_43G                                    1.      
    @ 1276   SDC_43I                                    1.      
    @ 1277   SDC_43K                                    1.      
    @ 1278   SDC_43J                                    1.      
    @ 1279   SDC_43M                                    1.      
    @ 1280   SDC_5A_1                                   1.      
    @ 1281   SDCC5B1                                    8.      
    @ 1289   SDCC5B2                                    8.      
    @ 1297   SDCC5B3                                    8.      
    @ 1305   SDCC61                                     8.      
    @ 1313   SDCC62                                     8.      
    @ 1321   SDCC63                                     8.      
    @ 1329   SDCDFOLS                                   1.      
    @ 1330   DHH_OWN                                    1.      
    @ 1331   SDC_7AA                                    1.      
    @ 1332   SDCDLHM                                    2.      
    @ 1334   SDCDAIM                                    3.      
    @ 1337   SDCFIMM                                    1.      
    @ 1338   SDCDRES                                    3.      
    @ 1341   SDCDFL1                                    2.      
    @ 1343   SDCDABT                                    1.      
    @ 1344   SDCDCGT                                    2.      
    @ 1346   PMKPROXY                                   1.      
    @ 1347   EDU_1                                      1.      
    @ 1348   EDU_2                                      1.      
    @ 1349   EDU_3                                      1.      
    @ 1350   EDU_4A                                     2.      
    @ 1352   EDUDH04                                    1.      
    @ 1353   EDUDH10                                    2.      
    @ 1355   EDUDR04                                    1.      
    @ 1356   EDUDR10                                    2.      
    @ 1358   INC_1A                                     1.      
    @ 1359   INC_1B                                     1.      
    @ 1360   INC_1C                                     1.      
    @ 1361   INC_1D                                     1.      
    @ 1362   INC_1E                                     1.      
    @ 1363   INC_1F                                     1.      
    @ 1364   INC_1G                                     1.      
    @ 1365   INC_1O                                     1.      
    @ 1366   INC_1H                                     1.      
    @ 1367   INC_1J                                     1.      
    @ 1368   INC_1I                                     1.      
    @ 1369   INC_1K                                     1.      
    @ 1370   INC_1L                                     1.      
    @ 1371   INC_1M                                     1.      
    @ 1372   INC_1N                                     1.      
    @ 1373   INC_2                                      2.      
    @ 1375   INC_3                                      8.      
    @ 1383   INC_6A                                     1.      
    @ 1384   INC_6B                                     1.      
    @ 1385   INC_6C                                     1.      
    @ 1386   INC_6D                                     1.      
    @ 1387   INC_6E                                     1.      
    @ 1388   INC_6F                                     1.      
    @ 1389   INC_6G                                     1.      
    @ 1390   INC_6H                                     1.      
    @ 1391   INC_6I                                     1.      
    @ 1392   INC_6J                                     1.      
    @ 1393   INC_6K                                     1.      
    @ 1394   INC_6L                                     1.      
    @ 1395   INC_6M                                     1.      
    @ 1396   INC_6N                                     1.      
    @ 1397   INC_6O                                     1.      
    @ 1398   INC_7                                      2.      
    @ 1400   INC_8A                                     8.      
    @ 1408   INC_8B                                     1.      
    @ 1409   INC_8C                                     2.      
    @ 1411   INC_8D                                     2.      
    @ 1413   INCFIMP4                                   1.      
    @ 1414   INCDHH                                     2.      
    @ 1416   INCDPER                                    2.      
    @ 1418   INCDADR                                   11.9     
    @ 1429   INCDRCA                                    2.      
    @ 1431   INCDRPR                                    2.      
    @ 1433   INCDRRS                                    2.      
    @ 1435   WTSFSS1                                    1.      
    @ 1436   WTS_F13                                    1.      
    @ 1437   WTS_S1M                                    8.2     
    @ 1445   WTS_S1S                                    8.2     
         ;
