VARIABLE LABELS                                                                 
    VERDATE  'Date de création du fichier'                                      
    REFPER   'Période de référence'                                             
    SAMPLEID 'Identificateur du ménage'                                         
    PERSONID 'Identificateur de la personne'                                    
    GEO_PRV  'Province de résidence du répondant'                               
    GEODCMAA 'Région métropolitaine du Recensement de'                          
    GEODDA11 '2011 AD - (D)'                                                    
    GEODPC   'Code postal - (D)'                                                
    GEODHR4  'Région sociosanitaire de résidence - (D)'                         
    GEODDHA  'District Health Authority Nouv. -Écosse'                          
    GEODBCHA 'C.B. Health Authority (HABC) - (D)'                               
    GEODLHN  'Rés.loc.intégrés santé - (LHIN)-On. -(D)'                         
    GEODDA06 'Aire de diffusion du Recensement de 2006'                         
    GEODFED  'Circonscription électorale fédérale -(D)'                         
    GEODCSD  'Subdivision de recensement - (D)'                                 
    GEODCD   'Division de recensement - (D)'                                    
    GEODSAT  'Genre de class. secteurs stat. - (D)'                             
    GEODPG11 'Grp. Régions socio-sanitaires homologues'                         
    GEODUR   'Région urbaine et rurale'                                         
    GEODUR2  'Région urbaine et rurale - 2 niveaux-(D)'                         
    GEODSUBZ 'Sous-zones - Alberta'                                             
    SAM_CP   'Période de collecte de l''échantillon'                            
    SAM_TYP  'Type d''échantillon'                                              
    CASETYPE 'Type de cas'                                                      
    SAMDSHR  'Permission de partager les données - (D)'                         
    SAMDLNK  'Permission de jumeler les données - (D)'                          
    ADM_STA  'État de réponse après traitement données'                         
    ADM_PRX  'Composante santé compl. par procuration'                          
    ADM_YOI  'Année de l''interview'                                            
    ADM_MOI  'Mois de l''interview'                                             
    ADM_DOI  'Jour de l''interview'                                             
    ADM_N09  'Interview au téléphone/en face à face'                            
    ADM_N10  'Répondant seul durant l''interview'                               
    ADM_N11  'Réponses biais./présence autre personne'                          
    ADM_N12  'Langue de l''interview'                                           
    ADM_LHH  'Langue /préf. - interview ménage'                                 
    DHH_AGE  'Âge'                                                              
    DHH_YOB  'Année de naissance'                                               
    DHH_MOB  'Mois de naissance'                                                
    DHH_DOB  'Jour de naissance'                                                
    DHH_SEX  'Sexe'                                                             
    DHH_MS   'État matrimonial'                                                 
    DHHDSAGE 'Âge du conjoint'                                                  
    DHHDYKD  'Nbre pers <= 15 ans dans le ménage - (D)'                         
    DHHDOKD  'Nbre pers 16-17 ans dans le ménage - (D)'                         
    DHHDLE5  'Nbre pers. <= 5 ans dans le ménage - (D)'                         
    DHHD611  'Nbre pers. 6-11 ans/dans le mén. - (D)'                           
    DHHDL12  'Nbre pers. < 12 ans dans le ménage - (D)'                         
    DHHDL18  'Nbre pers. < 18 ans dans le ménage - (D)'                         
    DHHDLVG  'Dispositions de vie/rép. sélect. - (D)'                           
    DHHDECF  'Type de ménage - (D)'                                             
    DHHDHSZ  'Taille de ménage - (D)'                                           
    GEN_01   'Évaluation personnelle de la santé'                               
    GEN_02   'Éval. pers. de santé - comparer à 1 an'                           
    GEN_02A2 'Satisfaction de vie en général'                                   
    GEN_02B  'Évaluation personnelle de santé mentale'                          
    GEN_07   'Stress perçu dans la vie'                                         
    GEN_08   'A travaillé à un emploi'                                          
    GEN_09   'Éval. personnelle du stress au travail'                           
    GEN_10   'Sentiment d''appartenance - comm. locale'                         
    GENDHDI  'Santé perçue - (D)'                                               
    GENDMHI  'Santé mentale perçue -(D)'                                        
    GENGSWL  'Satisfaction de vie en général'                                   
    MAM_037  'Enceinte actuellement'                                            
    HWT_2    'Taille / autodéclarée'                                            
    HWT_2A   'Taille - de 1''0" à 1''11" / autodéclarée'                        
    HWT_2B   'Taille - de 2''0" à 2''11" / autodéclarée'                        
    HWT_2C   'Taille - de 3''0" à 3''11" / autodéclarée'                        
    HWT_2D   'Taille - de 4''0" à 4''11" / autodéclarée'                        
    HWT_2E   'Taille - de 5''0" à 5''11" / autodéclarée'                        
    HWT_2F   'Taille - de 6''0" à 6''11" / autodéclarée'                        
    HWT_3    'Poids / autodéclaré'                                              
    HWT_N4   'Poids unité de mesure lb/kg /autodéclaré'                         
    HWT_4    'Opinion propos de son poids-autodéclaré'                          
    HWTDHTM  'Taille (mètres) / autodéclarée - (D)'                             
    HWTDWTK  'Poids (kilogrammes) / autodéclaré - (D)'                          
    HWTDBMI  'IMC / autodéclaration - (D)'                                      
    HWTDISW  'Class. IMC (18 +) / autodéclar. - (D)'                            
    HWTDCOL  'Class. IMC (12-17) / autodéclar. - (D)'                           
    HWTDWHO  'IMC pour les jeunes / autodéclaré – (D)'                          
    CCC_031  'Fait de l''asthme'                                                
    CCC_035  'Asthme - a eu des symptômes/des crises'                           
    CCC_036  'Asthme - a pris des médicaments'                                  
    CCC_051  'Souffre d''arthrite'                                              
    CCC_061  'Maux de dos autres que fibro./arthrite'                           
    CCC_071  'Fait de l''hypertension'                                          
    CCC_072  'Déjà diagnostique pour l''hypertension'                           
    CCC_073  'Médicaments - l''hypertension'                                    
    CCC_073A 'Enceinte - diagn. avec hypert. 1ère fois'                         
    CCC_073B 'Non enceinte - diagno. avec hypertension'                         
    CCC_081  'A des migraines'                                                  
    CCC_091  'Atteint d''une MPOC'                                              
    CCC_101  'Est atteint du diabète'                                           
    CCC_102  'Diabète - âge au premier diagnostique'                            
    CCC_10A  'Diabète - diagnostique durant grossesse'                          
    CCC_10B  'Diabète - diag.-autre que grossesse'                              
    CCC_10C  'Diabète - diag./après commencé insuline'                          
    CCC_105  'Diabète - prend insuline actuellement'                            
    CCC_106  'Diabète -pilules pour contrôler le sucre'                         
    CCC_121  'Souffre d''une maladie cardiaque'                                 
    CCC_131  'Souffre d''un cancer'                                             
    CCC_31A  'Déjà souffre d''un cancer'                                        
    CCC_141  'Souffre d''ulcères à l''estomac/intestin'                         
    CCC_151  'Atteint troubles-acc. vasculaire cérébr.'                         
    CCC_161  'Atteint d''incontinence urinaire'                                 
    CCC_171  'Atteint de troubles intestinaux'                                  
    CCC_17A  'Genre de trouble intestinaux'                                     
    CCC_173  'Diagnostiqué avec une scoliose'                                   
    CCC_181  'Atteint Alzheimer/démence cérébrale'                              
    CCC_280  'Est atteint d''un trouble de l''humeur'                           
    CCC_290  'Est atteint d''un trouble d''anxiété'                             
    CCCDDIA  'Type de diabète'                                                  
    DOHUI    'Module: HUI - (F)'                                                
    HUI_01   'Vision - lire journal sans lunettes'                              
    HUI_02   'Vision - lire journal avec lunettes'                              
    HUI_03   'Vision - capable de voir'                                         
    HUI_04   'Vision - reconnaître ami sans lunettes'                           
    HUI_05   'Vision - reconnaître ami avec lunettes'                           
    HUI_06   'Ouïe - dans groupe sans prothèse audit.'                          
    HUI_07   'Ouïe - dans groupe avec prothèse audit.'                          
    HUI_07A  'Ouïe - capable d''entendre'                                       
    HUI_08   'Ouïe - ds pièce sil. sans prothèse aud.'                          
    HUI_09   'Ouïe - ds pièce sil. avec prothèse aud.'                          
    HUI_10   'Élocution - parfait. compris - inconnus'                          
    HUI_11   'Élocution - partiel. compris - inconnus'                          
    HUI_12   'Élocution - parfait. compris - non-inc.'                          
    HUI_13   'Élocution - partiel. compris - non-inc.'                          
    HUI_14   'Mobilité - marche sans diff./sans supp.'                          
    HUI_15   'Mobilité - capable de marcher'                                    
    HUI_16   'Mobilité - besoin appareil pr marcher'                            
    HUI_17   'Mobilité - besoin aide pers. pr marcher'                          
    HUI_18   'Mobilité - besoin d''un fauteuil roulant'                         
    HUI_19   'Mobilité - fréq. util. fauteuil roulant'                          
    HUI_20   'Mobilité - besoin aide déplacer faut.'                            
    HUI_21   'Dext. - capable saisir/manip. pts objet'                          
    HUI_22   'Dext. - a besoin aide/limitations mains'                          
    HUI_23   'Dext. - a besoin aide avec des tâches'                            
    HUI_24   'Dext. - a besoin équip. sp./limit. mains'                         
    HUI_25   'Émotion - évaluation personnelle'                                 
    HUI_26   'Cognition - capacité se souvenir choses'                          
    HUI_27   'Cognition - cap. à penser/résoudre prob.'                         
    HUIDVIS  'Vision (code fonctionnel)'                                        
    HUIDHER  'L’ouïe (code fonctionnel)'                                        
    HUIDSPE  'Élocution (code fonctionnel)'                                     
    HUIDMOB  'Marche (mobilité) (code fonctionnel)'                             
    HUIDDEX  'Dextérité (code fonctionnel)'                                     
    HUIDEMO  'Émotion (code fonctionnel)'                                       
    HUIDCOG  'Code fonct. - troubles cognition - (D)'                           
    HUIDHSI  'Indice de l''état de la santé(HUI3) - (D)'                        
    HUP_01   'Habituellement sans douleurs/malaises'                            
    HUP_02   'Douleurs/malaises - intensité habituelle'                         
    HUP_03   'Douleurs/malaises - nbre act. empêchées'                          
    HUPDPAD  'Douleur (code fonctionnel)'                                       
    HCU_1AA  'A un médecin régulier'                                            
    HCU_1BA  'Raison pas méd. - pas dans la région'                             
    HCU_1BB  'Raison pas méd. - aucun nouveau patient'                          
    HCU_1BC  'Raison pas méd. - pas essayé avoir un'                            
    HCU_1BD  'Raison pas méd. - est parti / retraité'                           
    HCU_1BE  'Raison pas méd. - autre'                                          
    HCU_1A1  'Médecin régulier'                                                 
    HCU_1A2  'Genre d''''endroit fréquenté'                                     
    HCU_1AC  'Langue parlée avec médecin'                                       
    CHP_01   'A passé la nuit comme patient'                                    
    CHP_02   'Nbre de nuits comme patient'                                      
    CHP_03   'Consulté méd. de famille/omnipraticien'                           
    CHP_04   'Nbre de consult. - médecin de famille'                            
    CHP_05   'Lieu de la plus récente consultation'                             
    CHP_06   'Consulté un spécialiste de la vue'                                
    CHP_07   'Nbre de consult. - spécialiste de la vue'                         
    CHP_08   'Consulté un autre médecin'                                        
    CHP_09   'Nbre de consult. - autre médecin'                                 
    CHP_10   'Lieu de la plus récente consultation'                             
    CHP_11   'Consulté une infirmière'                                          
    CHP_12   'Nbre de consult. - infirmière'                                    
    CHP_13   'Lieu de la plus récente consultation'                             
    CHP_14   'Consulté un dentiste ou orthodontiste'                            
    CHP_15   'Nbre de consult. - dentiste/ortho.'                               
    CHPDMDC  'Nbre de consultations avec des médecins'                          
    RAC_1    'A de la difficulté à faire des activités'                         
    RAC_2A   'Réduit genre/quantité activités - maison'                         
    RAC_2B1  'Réduit genre/quantité activités - école'                          
    RAC_2B2  'Réduit genre/quantité act. - travail'                             
    RAC_2C   'Réduit genre/quantité act. - autres'                              
    RAC_5    'Cause du problème de santé'                                       
    RACDIMP  'Répercussion des probl. de santé - (D)'                           
    RACDPAL  'Participation et activité limitée - (D)'                          
    DOADL    'Module de contenu commun - ADL (F)'                               
    ADL_01   'Besoin aide - préparer les repas'                                 
    ADL_02   'Besoin aide - rendre à des rendez-vs'                             
    ADL_03   'Besoin aide - accomplir tâches ménagères'                         
    ADL_04   'Besoin aide - pour les soins personnels'                          
    ADL_05   'Besoin aide - pour se déplacer ds maison'                         
    ADL_06   'Besoin aide - occuper finances pers.'                             
    ADLF6R   'Besoin d''aide pour des tâches - (F)'                             
    FLU_160  'A déjà reçu un vaccin contre la grippe'                           
    FLU_162  'A reçu vaccin contre grippe - dern. fois'                         
    FLU_164  'A reçu vaccin contre la grippe - mois'                            
    FLU_165  'Reçu vaccin grippe - année cour./dern.'                           
    FLU_66A  'Aucun vaccin - n''a pu s''en occuper'                             
    FLU_66B  'Aucun vaccin - pas néc. selon répondant'                          
    FLU_66C  'Aucun vaccin - pas néc. selon médecin'                            
    FLU_66D  'Aucun vaccin - resp. pers./familiales'                            
    FLU_66E  'Aucun vaccin - non disp. lorsque requis'                          
    FLU_66F  'Aucun vaccin - non disp. dans la région'                          
    FLU_66G  'Aucun vaccin - délai d''attente trop long'                        
    FLU_66H  'Aucun vaccin - problèmes de transport'                            
    FLU_66I  'Aucun vaccin - problème de langue'                                
    FLU_66J  'Aucun vaccin - coût'                                              
    FLU_66K  'Aucun vaccin - ne savait pas où aller'                            
    FLU_66L  'Aucun vaccin - peur'                                              
    FLU_66M  'Aucun vaccin - mauvaise réaction'                                 
    FLU_66O  'Pas vaccin - inc.sortir dom./prob santé'                          
    FLU_66N  'Aucun vaccin - autre'                                             
    FVC_1A   'Boit jus de fruits-unité de déclaration'                          
    FVC_1B   'Boit jus de fruits - nbre de fois/jour'                           
    FVC_1C   'Boit jus de fruits - nbre de fois/sem.'                           
    FVC_1D   'Boit jus de fruits - nbre de fois/mois'                           
    FVC_1E   'Boit jus de fruits - nbre de fois/année'                          
    FVC_2A   'Mange des fruits - unité de déclaration'                          
    FVC_2B   'Mange des fruits - nbre de fois/jour'                             
    FVC_2C   'Mange des fruits - nbre de fois/sem.'                             
    FVC_2D   'Mange des fruits - nbre de fois/mois'                             
    FVC_2E   'Mange des fruits - nbre de fois/année'                            
    FVC_3A   'Mange salade verte-unité de déclaration'                          
    FVC_3B   'Mange salade verte - nbre de fois/jour'                           
    FVC_3C   'Mange salade verte - nbre de fois/sem.'                           
    FVC_3D   'Mange salade verte - nbre de fois/mois'                           
    FVC_3E   'Mange salade verte - nbre de fois/année'                          
    FVC_4A   'Mange pom. de terre - unité de déclar.'                           
    FVC_4B   'Mange pom. de terre - nbre de fois/jour'                          
    FVC_4C   'Mange pom. de terre - nbre de fois/sem.'                          
    FVC_4D   'Mange pom. de terre - nbre de fois/mois'                          
    FVC_4E   'Mange pom. de terre - nbre de fois/année'                         
    FVC_5A   'Mange des carottes-unité de déclaration'                          
    FVC_5B   'Mange des carottes - nbre de fois/jour'                           
    FVC_5C   'Mange des carottes - nbre de fois/sem.'                           
    FVC_5D   'Mange des carottes - nbre de fois/mois'                           
    FVC_5E   'Mange des carottes - nbre de fois/année'                          
    FVC_6A   'Mange autres légumes-unité déclaration'                           
    FVC_6B   'Mange autres légumes - portions/jour'                             
    FVC_6C   'Mange autres légumes - portions/sem.'                             
    FVC_6D   'Mange autres légumes - portions/mois'                             
    FVC_6E   'Mange autres légumes - portions/année'                            
    FVCDJUI  'Cons. quotidienne - jus de fruits - (D)'                          
    FVCDFRU  'Cons. quotidienne - fruits - (D)'                                 
    FVCDSAL  'Cons. quotidienne - salade verte - D)'                            
    FVCDPOT  'Cons. quotid. - pommes de terre - (D)'                            
    FVCDCAR  'Cons. quotidienne - carottes - (D)'                               
    FVCDVEG  'Cons. quotidienne - autres légumes - (D)'                         
    FVCDTOT  'Cons. quoti. - tot. fruits et lég. - (D)'                         
    FVCGTOT  'Cons. quoti. - tot. fruits/lég. - (D, G)'                         
    PAC_1A   'Act./3 dern. m. - marche pour exercice'                           
    PAC_1B   'Act./3 dern. m. - jardinage/trav. ext.'                           
    PAC_1C   'Act./3 dern. m. - natation'                                       
    PAC_1D   'Act./3 dern. m. - bicyclette'                                     
    PAC_1E   'Act./3 dern. m. - danse moderne/sociale'                          
    PAC_1F   'Act./3 dern. m. - exercises à la maison'                          
    PAC_1G   'Act./3 dern. m. - hockey sur glace'                               
    PAC_1H   'Act./3 dern. m. - patinage sur glace'                             
    PAC_1I   'Act./3 dern. m. - patin à roues align.'                           
    PAC_1J   'Act./3 dern. m. - jogging ou course'                              
    PAC_1K   'Act./3 dern. m. - golf'                                           
    PAC_1L   'Act./3 dern. m. - classe d''exercices'                            
    PAC_1M   'Act./3 dern. m. - ski/planche à neige'                            
    PAC_1N   'Act./3 dern. m. - quilles'                                        
    PAC_1O   'Act./3 dern. m.- baseball ou balle molle'                         
    PAC_1P   'Act./3 dern. m. - tennis'                                         
    PAC_1Q   'Act./3 dern. m. - poids et haltères'                              
    PAC_1R   'Act./3 dern. m. - pêche'                                          
    PAC_1S   'Act./3 dern. m. - volley-ball'                                    
    PAC_1T   'Act./3 dern. m. - basketball'                                     
    PAC_1Z   'Act./3 dern. m. - Soccer'                                         
    PAC_1U   'Act./3 dern. m. - pêche - Autre'                                  
    PAC_1V   'Act./3 dern. m. - Aucune activité phy.'                           
    PAC_1W   'Act./3 dern. m. - autre (#2)'                                     
    PAC_1X   'Act./3 dern. m. - autre (#3)'                                     
    PAC_2A   'Nbre de fois - marche pour l''exercice'                           
    PAC_3A   'Temps consacré - marche pour l''exercice'                         
    PAC_2B   'Nbre de fois - jardinage/travaux ext.'                            
    PAC_3B   'Temps consacré - jardinage/travaux ext.'                          
    PAC_2C   'Nbre de fois - natation'                                          
    PAC_3C   'Temps consacré - natation'                                        
    PAC_2D   'Nbre de fois - bicyclette'                                        
    PAC_3D   'Temps consacré - bicyclette'                                      
    PAC_2E   'Nbre de fois - danse moderne/sociale'                             
    PAC_3E   'Temps consacré - danse moderne/sociale'                           
    PAC_2F   'Nbre de fois - exercices à la maison'                             
    PAC_3F   'Temps consacré - exercices à la maison'                           
    PAC_2G   'Nbre de fois - hockey sur glace'                                  
    PAC_3G   'Temps consacré - hockey sur glace'                                
    PAC_2H   'Nbre de fois - patinage sur glace'                                
    PAC_3H   'Temps consacré - patinage sur glace'                              
    PAC_2I   'Nbre de fois - patin à roues alignées'                            
    PAC_3I   'Temps consacré - patin à roues alignées'                          
    PAC_2J   'Nbre de fois - jogging ou course'                                 
    PAC_3J   'Temps consacré - jogging ou course'                               
    PAC_2K   'Nbre de fois - golf'                                              
    PAC_3K   'Temps consacré - golf'                                            
    PAC_2L   'Nbre de fois - classe d''exercices'                               
    PAC_3L   'Temps consacré - classe d''exercices'                             
    PAC_2M   'Nbre de fois - ski/planche à neige'                               
    PAC_3M   'Temps consacré - ski/planche à neige'                             
    PAC_2N   'Nbre de fois - quilles'                                           
    PAC_3N   'Temps consacré - quilles'                                         
    PAC_2O   'Nbre fois partic. - baseball/balle molle'                         
    PAC_3O   'Temps consacré - baseball/balle molle'                            
    PAC_2P   'Nbre de fois - tennis'                                            
    PAC_3P   'Temps consacré - tennis'                                          
    PAC_2Q   'Nbre de fois - poids et haltères'                                 
    PAC_3Q   'Temps consacré - poids et haltères'                               
    PAC_2R   'Nbre de fois - pêche'                                             
    PAC_3R   'Temps consacré - pêche'                                           
    PAC_2S   'Nbre de fois - volley-ball'                                       
    PAC_3S   'Temps consacré - volley-ball'                                     
    PAC_2T   'Nbre de fois - basketball'                                        
    PAC_3T   'Temps consacré - basketball'                                      
    PAC_2Z   'Nbre de fois - soccer'                                            
    PAC_3Z   'Temps consacré - soccer'                                          
    PAC_2U   'Nbre de fois - autre activité (#1)'                               
    PAC_3U   'Temps consacré - autre activité (#1)'                             
    PAC_2W   'Nbre de fois - autre activité (#2)'                               
    PAC_3W   'Temps consacré - autre activité (#2)'                             
    PAC_2X   'Nbre de fois - autre activité (#3)'                               
    PAC_3X   'Temps consacré - autre activité (#3)'                             
    PAC_7    'Travail ou école en marchant / 3 mois'                            
    PAC_7A   'Nbre fois/3 m./marcher travail ou école'                          
    PAC_7B   'Temps marcher aller/retour travail/école'                         
    PAC_8    'Travail ou école en bicyclette / 3 mois'                          
    PAC_8A   'Nbre fois/3 m./bicycle travail ou école'                          
    PAC_8B   'Temps consacré - bicycle travail/école'                           
    PACDEE   'Dépense d''énergie quotidienne - (D)'                             
    PACFLEI  'Participation - activités de loisirs-(F)'                         
    PACDFM   'Fréq. mens./act. phys. > 15 min. - (D)'                           
    PACDFR   'Fréq. - toutes activités physiques - (D)'                         
    PACFD    'Partic. activité phys. > 15 min. - (F)'                           
    PACDPAI  'Indice de l''activité physique - (D)'                             
    PACDLTI  'Ind. de l''act. phys. - Loisirs et trans.'                        
    PACDTLE  'Dép. éner. quo. - Act. trans. et loisirs'                         
    PACFLTI  'Particip. - Act. phys. loisirs ou trans.'                         
    DOUPE    'Module : UPE - (F)'                                               
    UPE_01A  'Fait bicyclette dans 12 derniers mois'                            
    UPE_01   'Fréq. - porte un casque - vélo'                                   
    UPE_02   'Patin roues alignées 12 derniers mois'                            
    UPE_02A  'Fréq. - casque - patin à roues'                                   
    UPE_02B  'Fréq. - protège-poignets - patin à roues'                         
    UPE_02C  'Fréq. - protège coudes - patin à roues'                           
    UPE_02D  'Porte des protège-genoux'                                         
    UPE_03A  'Ski alpin/planche à neige - 3 dern. m.'                           
    UPE_03B  'Ski alpin/planche à neige - 12 dern. m.'                          
    UPE_04A  'Fréq. - porte casque - ski alpin'                                 
    UPE_05A  'Fréq. - porte casque - planche à neige'                           
    UPE_05B  'Fréq. - protège-poignets-pl. à neige'                             
    UPE_06   'A fait du skateboard - 12 dern. m.'                               
    UPE_06A  'Fréq. - porte casque - skateboard'                                
    UPE_06B  'Fréq. - protège-poignets - skateb.'                               
    UPE_06C  'Fréq. - protège coudes - skateb.'                                 
    UPE_07   'Joué hockey sur glace 12 derniers mois'                           
    UPE_07A  'Porte un protecteur buccal'                                       
    UPEFILS  'Porte tout équip. prot. - roues alignées'                         
    UPEFSKB  'Porte t. équip. protect. - skateb. - (F)'                         
    UPEFSNB  'P.t. équip. protect. - pl. à neige - (F)'                         
    DOINJ    'Module: INJ - (F)'                                                
    REP_1A   'Blessure de mouvements répétitifs'                                
    REP_2    'Limiter vos activités normales'                                   
    REP_3    'Activité qui a causé cette lésion'                                
    REP_3A   'Activité qui a causé cette lésion'                                
    REP_4    'Mouv. Rep.-activ. à un emploi/entreprise'                         
    REP_5A   'Activité - Marcher'                                               
    REP_5B   'Activité - Sports'                                                
    REP_5C   'Activité - Loisirs'                                               
    REP_5D   'Activité - Tâches ménagères'                                      
    REP_5F   'Activité - Ordinateur'                                            
    REP_5G   'Activité - Conduire un véhicule'                                  
    REP_5H   'Activité - Transporter ou soulever'                               
    REP_5I   'Activité - Autre'                                                 
    INJ_01   'Blessé au cours des 12 dern. m.'                                  
    INJ_02   'Nbre de blessures - 12 dern. m.'                                  
    INJ_03   'Blessure la plus grave - mois'                                    
    INJ_04   'Blessure la plus grave - année'                                   
    INJ_05   'Blessure la plus grave - genre'                                   
    INJ_06   'Bles. la + grave - partie corps atteinte'                         
    INJ_07   'Organes internes - partie du corps'                               
    INJ_08   'Blessure la plus grave - lieu'                                    
    INJ_09   'Bless. la + grave - activité lors bless.'                         
    INW_01   'Blessure produite à emploi actuel'                                
    INWF02   'Réponse inscrite - genre d''entreprise'                           
    INWF03   'Réponse inscrite - genre de travail'                              
    INWCSIC  'SCIAN 2007'                                                       
    INWCSOC  'CNP-S 2006'                                                       
    INWF04   'Réponse inscrite - fonctions plus imp.'                           
    INWDOCG  'Groupe professionnel'                                             
    INWDING  'Groupe d''industrie'                                              
    INJ_10   'Blessure la plus grave - chute'                                   
    INJ_11A  'Comment êtes-vous tombé'                                          
    INJ_12   'Heure de la blessure'                                             
    INJ_12A  'Heure de la blessure'                                             
    INJ_13   'Bless. la + grave - soins/48 hres après'                          
    INJ_14A  'Soignez dans le 48 heures'                                        
    INJ_14B  'Soignez dans le 48 heures'                                        
    INJ_14C  'Soignez dans le 48 heures'                                        
    INJ_14L  'Soignez dans le 48 heures'                                        
    INJ_14M  'Soignez dans le 48 heures'                                        
    INJ_14F  'Soignez dans le 48 heures'                                        
    INJ_14N  'Soignez dans le 48 heures'                                        
    INJ_14O  'Soignez dans le 48 heures'                                        
    INJ_14K  'Soignez dans le 48 heures'                                        
    INJ_15   'Suivi en raison de la blessure'                                   
    INJ_15A  'Suivi en raison de la blessure'                                   
    INJ_16   'Autres blessures - pas limité activités'                          
    INJ_17   'Autres blessures - nombre'                                        
    INJDTBS  'Genre de blessure/partie du corps - (D)'                          
    INJDCAU  'Cause de la blessure - (D)'                                       
    INJDCBP  'Cause blessure selon lieu de l''incident'                         
    INJDSTT  'État de la blessure - (D)'                                        
    SMK_01A  'A fumé 100 cigarettes ou plus - vie'                              
    SMK_01B  'A déjà fumé toute une cigarette entière'                          
    SMK_01C  'Âge - a fumé première cigarette entière'                          
    SMK_202  'Genre de fumeur'                                                  
    SMK_203  'Âge comm. fumer tous les jours (f.quot.)'                         
    SMK_204  'Nbre cig. par jour (fumeur quotidien)'                            
    SMK_05B  'Nbre cig. par jour (fumeur occasionnel)'                          
    SMK_05C  'Nbre jours-1 cig. ou plus (fumeur occ.)'                          
    SMK_05D  'A déjà fumé cigarettes tous les jours'                            
    SMK_06A  'Cessé fumer-quand (jamais fumeur quot.)'                          
    SMK_06B  'Cessé fumer - mois (jamais fumeur quot.)'                         
    SMK_06C  'Nbre d''années depuis cessé de fumer'                             
    SMK_207  'Âge - commencé à fumer tous les jours'                            
    SMK_208  'Nbre cig. par jour (ancien fumeur quot.)'                         
    SMK_09A  'Cessé de fumer quotidiennement - quand'                           
    SMK_09B  'Cessé de fumer quotidiennement - mois'                            
    SMK_09C  'Nbre d''années depuis cessé fumer quot.'                          
    SMK_10   'A complètement cessé de fumer'                                    
    SMK_10A  'Cessé de fumer complètement - quand'                              
    SMK_10B  'Cessé de fumer complètement - mois'                               
    SMK_10C  'Nbre d''années depuis cessé de fumer'                             
    SMKDSTY  'Genre de fumeur - (D)'                                            
    SMKDSTP  'Nbre années depuis cessé fumer compl.(D)'                         
    SMKDYCS  'Nbre d''années que répondant a fumé - (D)'                        
    ETS_10   'Quelqu''un fume à l''intérieur la maison'                         
    ETS_11   'Nbre pers. qui fument intérieur maison'                           
    ETS_20   'Exposé/fumée des autres - véh. privé'                             
    ETS_20B  'Exposé/fumée des autres - lieux publics'                          
    ETS_35   'Permis de fumer - Maison'                                         
    ETS_36   'Restrictions de fumer'                                            
    ETS_37A  'Type de restrictions -certaines pièces'                           
    ETS_37B  'Type de restrictions - jeunes enfants'                            
    ETS_37C  'Type de restrictions - fenêtres ouvertes'                         
    ETS_37D  'Type de restrictions - Autres'                                    
    ALC_1    'A bu alcool - 12 derniers mois'                                   
    ALC_2    'Fréquence de consommation d''alcool'                              
    ALC_3    'Fréq. Conso. 4 (femmes)/5(hommes) verres'                         
    ALCDTTM  'Genre de buveur (12 mois)'                                        
    DOSXB    'Module: SXB - (F)'                                                
    SXB_1    'A déjà eu des relations sexuelles'                                
    SXB_2    'Âge - première relation sexuelle'                                 
    SXB_3    'A eu des relat. sexuelles - 12 m.'                                
    SXB_4    'Nombre de partenaires différents - 12 m.'                         
    SXB_07   'Déjà diagnostiqué d''une MTS'                                     
    SXB_7A   'A utilisé un condom la dernière fois'                             
    SXB_09   'Important d''éviter de tomber enceinte'                           
    SXB_10   'Important éviter / blonde tombe enceinte'                         
    SXB_11   'Utilise hab. méth. de contraception-12m.'                         
    SXB_12A  'Méth. contraceptive habituelle - condom'                          
    SXB_12B  'Méth. contraceptive hab. - pilule'                                
    SXB_12C  'Méth. contrac. habituelle - diaphragme'                           
    SXB_12D  'Méth. contrac. habituelle - spermicide'                           
    SXB_12F  'Méth. contrac. habituelle - injections'                           
    SXB_12E  'Méth. contraceptive habituelle - autre'                           
    SXB_13A  'Méth. contrac. dernière fois - condom'                            
    SXB_13B  'Méth. contrac. dernière fois - pilule'                            
    SXB_13C  'Méth. contr. dernière fois - diaphragme'                          
    SXB_13D  'Méth. contr. dernière fois - spermicide'                          
    SXB_13F  'Méth. contr. dernière fois - injections'                          
    SXB_13G  'Méth. dernière fois - aucune'                                     
    SXB_13E  'Méth. contrac. dernière fois - autre'                             
    DOACC    'Module : ACC - (F)'                                               
    ACC_10   'Besoin de visiter un médecin spécialiste'                         
    ACC_11   'Diff. à obtenir soins d''un spécialiste'                          
    ACC_12A  'Diff. - à être référer'                                           
    ACC_12B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_12C  'Diff. - absence de spécialiste/région'                            
    ACC_12D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_12E  'Diff. - attendu trop longt./avant voir'                           
    ACC_12F  'Diff. - transport'                                                
    ACC_12G  'Diff. - langue'                                                   
    ACC_12H  'Diff. - coût'                                                     
    ACC_12I  'Diff. - responsabilités pers./familiales'                         
    ACC_12J  'Diff. - détérioration de santé'                                   
    ACC_12K  'Diff. - rendez-vous annulé/reporté'                               
    ACC_12L  'Diff. - attend toujours la visite'                                
    ACC_12M  'Diff. - incapable sortir domicile/santé'                          
    ACC_12N  'Diff. - autre'                                                    
    ACC_20   'Besoin d''une chirurgie non urgente'                              
    ACC_21   'Diff. à obtenir chirurgie non urgente'                            
    ACC_22A  'Diff. - à obtenir un rendez-vous'                                 
    ACC_22B  'Diff. - à obtenir un diagnostic'                                  
    ACC_22C  'Diff. - attendu trp longtemps/test diag.'                         
    ACC_22D  'Diff. - attendu trp longtemps/lit hôp.'                           
    ACC_22E  'Diff. - attendu trp longtemps/chirurgie'                          
    ACC_22F  'Diff. - service non disponible/région'                            
    ACC_22G  'Diff. - transport'                                                
    ACC_22H  'Diff. - langue'                                                   
    ACC_22I  'Diff. - coût'                                                     
    ACC_22J  'Diff. - responsabilités pers./familiales'                         
    ACC_22K  'Diff. - détérioration de santé'                                   
    ACC_22L  'Diff. - rendez-vous annulé/reporté'                               
    ACC_22M  'Diff. - attend toujours la chirurgie'                             
    ACC_22N  'Diff. - incapable sortir domicile/santé'                          
    ACC_22O  'Diff. - autre'                                                    
    ACC_30   'Besoin d''IRM, de CT-Scan, d''angiographie'                       
    ACC_31   'Diff. à obtenir les tests'                                        
    ACC_32A  'Diff. - à être référé'                                            
    ACC_32B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_32C  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_32D  'Diff. - attendu trop longt./avant subir'                          
    ACC_32E  'Diff. - non disponible au moment requis'                          
    ACC_32F  'Diff. - non disponible/région'                                    
    ACC_32G  'Diff. - transport'                                                
    ACC_32H  'Diff. - langue'                                                   
    ACC_32I  'Diff. - coût'                                                     
    ACC_32J  'Diff. - détérioration de santé'                                   
    ACC_32K  'Diff. - ne savait pas où aller'                                   
    ACC_32L  'Diff. - attend toujours le test'                                  
    ACC_32M  'Diff. - incapable sortir domicile/santé'                          
    ACC_32N  'Diff. - autre'                                                    
    ACC_40   'Besoin renseignements santé'                                      
    ACC_40A  'Contact info santé - médecin'                                     
    ACC_40B  'Contact/info santé - CLSC'                                        
    ACC_40C  'Contact info santé - sans rendez-vs'                              
    ACC_40D  'Contact info santé - ligne info. télé.'                           
    ACC_40E  'Contact info santé - salle d''urgence'                            
    ACC_40F  'Contact info santé - autre serv. hôpital'                         
    ACC_40G  'Contact info santé - autre'                                       
    ACC_41   'Diff. à obtenir renseign. Santé'                                  
    ACC_42   'Éprouvé diff. durant hres régulières'                             
    ACC_43A  'Diff. - contacter un médecin/infirmière'                          
    ACC_43B  'Diff. - n''avait pas numéro de téléphone'                         
    ACC_43C  'Diff. - n''a pas eu de réponse'                                   
    ACC_43D  'Diff. - attendu trop longtemps parler'                            
    ACC_43E  'Diff. - renseignements non appropriés'                            
    ACC_43F  'Diff. - langue'                                                   
    ACC_43G  'Diff. - ne savait pas où aller/appeler'                           
    ACC_43H  'Diff. - incapable sortir domicile/santé'                          
    ACC_43I  'Diff. - autre'                                                    
    ACC_44   'Éprouvé diff. durant soirées/fin sem.'                            
    ACC_45A  'Diff. - contacter un médecin/infirmière'                          
    ACC_45B  'Diff. - n''avait pas numéro de téléphone'                         
    ACC_45C  'Diff. - n''a pas eu de réponse'                                   
    ACC_45D  'Diff. - attendu trop longtemps/parler'                            
    ACC_45E  'Diff. - renseignements non appropriés'                            
    ACC_45F  'Diff. - langue'                                                   
    ACC_45G  'Diff. - ne savait pas où aller/appeler'                           
    ACC_45H  'Diff. - incapable sortir domicile/santé'                          
    ACC_45I  'Diff. - autre'                                                    
    ACC_46   'Éprouvé diff. durant/milieu de la nuit'                           
    ACC_47A  'Diff. - contacter un médecin/infirmière'                          
    ACC_47B  'Diff. - n''avait pas numéro de téléphone'                         
    ACC_47C  'Diff. - n''a pas eu de réponse'                                   
    ACC_47D  'Diff. - attendu trop longtemps/parler'                            
    ACC_47E  'Diff. - renseignements non appropriés'                            
    ACC_47F  'Diff. - langue'                                                   
    ACC_47G  'Diff. - ne savait pas où aller/appeler'                           
    ACC_47H  'Diff. - incapable sortir domicile/santé'                          
    ACC_47I  'Diff. - autre'                                                    
    ACC_50A  'A un médecin régulier'                                            
    ACC_50   'Besoin service santé - soi-même/famille'                          
    ACC_51   'Éprouvé diff. obtenir soins routine'                              
    ACC_52   'Éprouvé diff. durant hres régulières'                             
    ACC_53A  'Diff. - contacter un médecin'                                     
    ACC_53B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_53C  'Diff. - n''a pas de médecin de famille'                           
    ACC_53D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_53E  'Diff.-attendu trp longt./avant voir méd.'                         
    ACC_53F  'Diff. - non disponible au moment requis'                          
    ACC_53G  'Diff. - non disponible dans la région'                            
    ACC_53H  'Diff. - transport'                                                
    ACC_53I  'Diff. - langue'                                                   
    ACC_53J  'Diff. - coût'                                                     
    ACC_53K  'Diff. - ne savait pas où aller'                                   
    ACC_53L  'Diff. - incapable sortir domicile/santé'                          
    ACC_53M  'Diff. - autre'                                                    
    ACC_54   'Éprouvé diff. durant soirées/fin sem.'                            
    ACC_55A  'Diff. - contacter un médecin'                                     
    ACC_55B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_55C  'Diff. - n''a pas de médecin de famille'                           
    ACC_55D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_55E  'Diff.-attendu trp longt./avant voir méd.'                         
    ACC_55F  'Diff. - non disponible au moment requis'                          
    ACC_55G  'Diff. - non disponible/région'                                    
    ACC_55H  'Diff. - transport'                                                
    ACC_55I  'Diff. - langue'                                                   
    ACC_55J  'Diff. - coût'                                                     
    ACC_55K  'Diff. - ne savait pas où aller'                                   
    ACC_55L  'Diff. - incapable sortir domicile/santé'                          
    ACC_55M  'Diff. - autre'                                                    
    ACC_60   'Besoin soins immédiats-soi-même/famille'                          
    ACC_61   'Éprouvé diff. obtenir soins immédiats'                            
    ACC_62   'Éprouvé diff. durant hres régulières'                             
    ACC_63A  'Diff. - contacter un médecin'                                     
    ACC_63B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_63C  'Diff. - n''a pas de médecin de famille'                           
    ACC_63D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_63E  'Diff.-attendu trp longt./avant voir méd.'                         
    ACC_63F  'Diff. - non disponible au moment requis'                          
    ACC_63G  'Diff. - non disponible/région'                                    
    ACC_63H  'Diff. - transport'                                                
    ACC_63I  'Diff. - langue'                                                   
    ACC_63J  'Diff. - coût'                                                     
    ACC_63K  'Diff. - ne savait pas où aller'                                   
    ACC_63L  'Diff. - incapable sortir domicile/santé'                          
    ACC_63M  'Diff. - autre'                                                    
    ACC_64   'Éprouvé diff. durant soirées/fin sem.'                            
    ACC_65A  'Diff. - contacter un médecin'                                     
    ACC_65B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_65C  'Diff. - n''a pas de médecin de famille'                           
    ACC_65D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_65E  'Diff.-attendu trp longt./avant voir méd.'                         
    ACC_65F  'Diff. - non disponible au moment requis'                          
    ACC_65G  'Diff. - non disponible/région'                                    
    ACC_65H  'Diff. - transport'                                                
    ACC_65I  'Diff. - langue'                                                   
    ACC_65J  'Diff. - coût'                                                     
    ACC_65K  'Diff. - ne savait pas où aller'                                   
    ACC_65L  'Diff. - incapable sortir domicile/santé'                          
    ACC_65M  'Diff. - autre'                                                    
    ACC_66   'Éprouvé diff. durant/milieu de la nuit'                           
    ACC_67A  'Diff. - contacter un médecin'                                     
    ACC_67B  'Diff. - à obtenir un rendez-vous'                                 
    ACC_67C  'Diff. - n''a pas de médecin de famille'                           
    ACC_67D  'Diff. - attendu trop longtemps/rendez-vs'                         
    ACC_67E  'Diff.-attendu trp longt./avant voir méd.'                         
    ACC_67F  'Diff. - non disponible au moment requis'                          
    ACC_67G  'Diff. - non disponible/région'                                    
    ACC_67H  'Diff. - transport'                                                
    ACC_67I  'Diff. - langue'                                                   
    ACC_67J  'Diff. - coût'                                                     
    ACC_67K  'Diff. - ne savait pas où aller'                                   
    ACC_67L  'Diff. - incapable sortir domicile/santé'                          
    ACC_67M  'Diff. - autre'                                                    
    DOWTM    'Module: WTM - (F)'                                                
    WTM_01   'A eu besoin visiter médecin spécialiste'                          
    WTM_02   'Vis. req. méd. spéc. - genre de problème'                         
    WTM_03   'Personne qui a référé répond./med. spéc.'                         
    WTM_04   'A déjà eu sa visite chez le méd. spéc.'                           
    WTM_05   'Difficulté à rencontrer méd. spécialiste'                         
    WTM_06A  'Diff. - à être référé'                                            
    WTM_06B  'Diff. - à obtenir un rendez-vous'                                 
    WTM_06C  'Diff. - absence de spécialiste/région'                            
    WTM_06D  'Diff. - attendu trop longtemps/rendez-vs'                         
    WTM_06E  'Diff. - attendu trop longtemps/voir méd.'                         
    WTM_06F  'Diff. - transport'                                                
    WTM_06G  'Diff. - langue'                                                   
    WTM_06H  'Diff. - coût'                                                     
    WTM_06I  'Diff. - responsabilités pers./familiales'                         
    WTM_06J  'Diff. - détérioration de la santé'                                
    WTM_06K  'Diff. - rendez-vous annulé/reporté'                               
    WTM_06L  'Diff. - incapable sortir domicile/santé'                          
    WTM_06M  'Diff. - autre'                                                    
    WTM_07A  'Temps attendu pour visiter spécialiste'                           
    WTM_07B  'Temps attendu pour visiter spéc. - unité'                         
    WTM_08A  'Temps attendu jusqu''à date/spécialiste'                          
    WTM_08B  'Temps attendu jusqu''à date/spéc. - unité'                        
    WTM_10   'Opinion du répondant sur temps d''attente'                        
    WTM_11A  'Temps d''attente acceptable'                                      
    WTM_11B  'Temps d''attente acceptable - unité'                              
    WTM_12   'Rendez-vs au spécialiste annulé/reporté'                          
    WTM_13A  'Rendez-vous annulé/reporté - répondant'                           
    WTM_13B  'Rendez-vous annulé/reporté - spécialiste'                         
    WTM_13C  'Rendez-vous annulé/reporté - autre'                               
    WTM_14   'Conséq./la vie dû à l''attente/spéc.'                             
    WTM_15A  'Conséq./attente sur vie - inquiétude'                             
    WTM_15B  'Conséq./attente sur vie - inquiét./fam.'                          
    WTM_15C  'Conséq./attente sur vie - douleur'                                
    WTM_15D  'Conséq./attente sur vie-prob. act. quot'                          
    WTM_15E  'Conséq./attente sur vie - perte emploi'                           
    WTM_15F  'Conséq./attente sur vie - perte revenu'                           
    WTM_15G  'Conséq./attente sur vie - dépend. accrue'                         
    WTM_15H  'Conséq./attente sur vie-usage accru med.'                         
    WTM_15I  'Conséq./attente sur vie - santé détér.'                           
    WTM_15J  'Conséq./attente sur vie - santé amél.'                            
    WTM_15K  'Conséq. / attente sur vie - rel. pers.'                           
    WTM_15L  'Conséq. / attente sur vie - autre'                                
    WTM_16   'Genre de chirurgie requis'                                        
    WTM_17   'A déjà eu cette chirurgie'                                        
    WTM_18   'A dû passé une nuit à hôpital/chirurgie'                          
    WTM_19   'Diff. à obtenir cette chirurgie'                                  
    WTM_20A  'Diff. - à obtenir un rendez-vous'                                 
    WTM_20B  'Diff. - à obtenir un diagnostic'                                  
    WTM_20C  'Diff. - attendu trop longtemps/test diag'                         
    WTM_20D  'Diff. - attendu trop longtemps/lit hôp.'                          
    WTM_20E  'Diff. - attendu trop longtemps/chirurgie'                         
    WTM_20F  'Diff. - service non disponible/région'                            
    WTM_20G  'Diff. - transport'                                                
    WTM_20H  'Diff. - langue'                                                   
    WTM_20I  'Diff. - coût'                                                     
    WTM_20J  'Diff. - responsabilités pers./familiales'                         
    WTM_20K  'Diff. - détérioration de la santé'                                
    WTM_20L  'Diff. - rendez-vous annulé/reporté'                               
    WTM_20M  'Diff. - incapable sortir domicile/santé'                          
    WTM_20N  'Diff. - autre'                                                    
    WTM_21A  'Temps attendu/chirurgie'                                          
    WTM_21B  'Temps attendu/chirurgie-unité'                                    
    WTM_22   'Chirurgie nécessitera nuit à l''hôpital'                          
    WTM_23A  'Temps depuis décision/à chirurgie'                                
    WTM_23B  'Temps depuis déc. à chirurgie - unité'                            
    WTM_24   'Opinion du répondant sur temps d''attente'                        
    WTM_25A  'Temps d''attente acceptable'                                      
    WTM_25B  'Temps d''attente acceptable - unité'                              
    WTM_26   'Chirurgie annulée ou reportée'                                    
    WTM_27A  'Chirurgie annulée/reportée - répondant'                           
    WTM_27B  'Chirurgie annulée/reportée - chirurgien'                          
    WTM_27C  'Chirurgie annulée/reportée - hôpital'                             
    WTM_27D  'Chirurgie annulée/reportée - autre'                               
    WTM_28   'Conséq./la vie dû à l''attente/chirurgie'                         
    WTM_29A  'Conséq./attente sur vie - inquiétude'                             
    WTM_29B  'Conséq./attente sur vie - inquiét./fam.'                          
    WTM_29C  'Conséq./attente sur vie - douleur'                                
    WTM_29D  'Conséq./attente sur vie-prob. act. quot.'                         
    WTM_29E  'Conséq./attente sur vie - perte emploi'                           
    WTM_29F  'Conséq./attente sur vie - perte revenu'                           
    WTM_29G  'Conséq./attente sur vie - dépend. accrue'                         
    WTM_29H  'Conséq./attente sur vie-usage accru med.'                         
    WTM_29I  'Conséq./attente sur vie - santé détér.'                           
    WTM_29J  'Conséq./attente sur vie - santé amél.'                            
    WTM_29K  'Conséq./attente sur vie - rel. pers.'                             
    WTM_29L  'Conséq./attente sur vie - autre'                                  
    WTM_30   'Genre de test diagnostique requis'                                
    WTM_31   'Test diag. requis - genre/prob./santé'                            
    WTM_32   'A déjà eu ce test diagnostique'                                   
    WTM_33   'Endroit de ce test'                                               
    WTM_34   'Endroit de la clinique'                                           
    WTM_35   'Patient hospitalisé au moment de ce test'                         
    WTM_36   'Diff. à obtenir test diagnostique'                                
    WTM_37A  'Diff. - à être référé'                                            
    WTM_37B  'Diff. - à obtenir un rendez-vous'                                 
    WTM_37C  'Diff. - attendu trop long/obt. appt.'                             
    WTM_37D  'Diff. -attendu trop longtemps/subir test'                         
    WTM_37E  'Diff. - service non disp./moment requis'                          
    WTM_37F  'Diff. - service non disponible/région'                            
    WTM_37G  'Diff. - transport'                                                
    WTM_37H  'Diff. - langue'                                                   
    WTM_37I  'Diff. - coût'                                                     
    WTM_37J  'Diff. - détérioration de santé'                                   
    WTM_37K  'Diff. - ne savait pas où aller'                                   
    WTM_37L  'Diff. - incapable sortir domicile/santé'                          
    WTM_37M  'Diff. - autre'                                                    
    WTM_38A  'Temps attendu / test'                                             
    WTM_38B  'Temps attendu décision et test - unité'                           
    WTM_39A  'Période d''attente jusq. date/test diag.'                         
    WTM_39B  'Temps attendu jusqu''''à date/test - unité'                       
    WTM_40   'Opinion du répondant au temps d''attente'                         
    WTM_41A  'Temps d''''attente acceptable'                                    
    WTM_41B  'Temps d''''attente acceptable - unité'                            
    WTM_42   'Test annulé ou reporté'                                           
    WTM_43   'Test annulé ou reporté par'                                       
    WTM_44   'Conséq./sur vie dû à l''attente/test'                             
    WTM_45A  'Conséq./attente sur vie - inquiétude'                             
    WTM_45B  'Conséq./attente sur vie - inquiét./fam.'                          
    WTM_45C  'Conséq./attente sur vie - douleur'                                
    WTM_45D  'Conséq./attente sur vie-prob. act. quot.'                         
    WTM_45E  'Conséq./attente sur vie - perte emploi'                           
    WTM_45F  'Conséq./attente sur vie - perte revenu'                           
    WTM_45G  'Conséq./attente sur vie - dépend. accrue'                         
    WTM_45H  'Conséq./attente sur vie-usage accru méd.'                         
    WTM_45I  'Conséq./attente sur vie - santé détér.'                           
    WTM_45J  'Conséq./attente sur vie - santé amél.'                            
    WTM_45K  'Conséq./attente sur vie - rel. pers.'                             
    WTM_45L  'Conséq./attente sur vie - autre'                                  
    WTMDSO   '# jrs attente/méd.spéc. - vu spéc. - (D)'                         
    WTMDSN   '# jrs attente/méd.spéc. - pas vu - (D)'                           
    WTMDSA   '# jours attente accept. - méd. spéc. (D)'                         
    WTMDCO   '# jrs attente - chir. n-urg.- fait (D)'                           
    WTMDCN   '# jrs attente -chir. n-urg.-pas. fait(D)'                         
    WTMDCA   '# jours attente accept.-chir. n-urg-(D)'                          
    WTMDTO   '# jrs attente - diag.test - subi - (D)'                           
    WTMDTN   '# jrs attente - test diag.-pas subi -(D)'                         
    WTMDTA   '# jours attente accept. - test diag.-(D)'                         
    LBS_01   'A travaillé à un emploi semaine dernière'                         
    LBS_02   'Absent du travail la semaine dernière'                            
    LBS_03   'Plus d''un emploi la semaine dernière'                            
    LBS_11   'A cherché du travail - 4 dern. semaines'                          
    LBS_31   'Employé ou travaille à son compte'                                
    LBSF32   'Rép. insc. - nom entreprise - trav aut.'                          
    LBSF33   'Réponse inscrite - pers. pour qui trav.'                          
    LBSF34   'Réponse inscrite - genre d''entreprise'                           
    LBSF35   'Réponse inscrite - genre de travail'                              
    LBSCSIC  'SCIAN 2007'                                                       
    LBSCSOC  'CNP-S 2006'                                                       
    LBSF36   'Réponse inscrite - fonctions plus imp.'                           
    LBS_42   'Nbre d''heures hab.- emploi princ. actuel'                        
    LBS_53   'Nbre d''heures hab. - autre emploi actuel'                        
    LBSDHPW  'Tot. d''heures hab. trav. actuel - (D)'                           
    LBSDPFT  'Temps plein/partiel-emplois actuels-(D)'                          
    LBSDWSS  'État de l''emploi la sem. dern.-4 gr.-(D)'                        
    LBSDING  'Groupe d''industrie'                                              
    LBSDOCG  'Groupe professionnel'                                             
    SDC_8    'Étudiant actuellement'                                            
    SDC_9    'Étud plein temps/temps partiel/les deux'                          
    SDCCCB13 'Pays de naissance - Codé'                                         
    SDCGCB10 'Pays de naissance - (G)'                                          
    SDC_2    'Citoyen canadien de naissance'                                    
    SDC_3    'Année de l''immigration au Canada'                                
    SDC_4A   'Origine ethnique - Canadien'                                      
    SDC_4B   'Origine ethnique - Français'                                      
    SDC_4C   'Origine ethnique - Anglais'                                       
    SDC_4D   'Origine ethnique - Allemand'                                      
    SDC_4E   'Origine ethnique - Écossais'                                      
    SDC_4F   'Origine ethnique - Irlandais'                                     
    SDC_4G   'Origine ethnique - Italien'                                       
    SDC_4H   'Origine ethnique - Ukrainien'                                     
    SDC_4I   'Origine ethnique - Hollandais'                                    
    SDC_4J   'Origine ethnique - Chinois'                                       
    SDC_4K   'Origine ethnique - Juif'                                          
    SDC_4L   'Origine ethnique - Polonais'                                      
    SDC_4M   'Origine ethnique - Portugais'                                     
    SDC_4N   'Origine ethnique - Sud-Asiatique'                                 
    SDC_4T   'Origine ethnique - Norvégien'                                     
    SDC_4U   'Origine ethnique - Gallois'                                       
    SDC_4V   'Origine ethnique - Suédois'                                       
    SDC_4P   'Origine ethnique - Indien Amérique Nord'                          
    SDC_4Q   'Origine ethnique - Métis'                                         
    SDC_4R   'Origine ethnique - Inuit'                                         
    SDC_4S   'Origine ethnique - autre'                                         
    SDC_41   'Autochtone - Prem nat, Métis, Inuit'                              
    SDC_42A  'Autochtone - Première nation'                                     
    SDC_42B  'Autochtone - Métis'                                               
    SDC_42C  'Autochtone - Inuk/Inuit'                                          
    SDC_43A  'Orig. cult.raciales - Blanc'                                      
    SDC_43C  'Orig. cult./raciales - Sud-Asiatique'                             
    SDC_43B  'Orig. cult./raciales - Chinois(e)'                                
    SDC_43D  'Orig. cult./raciales - Noir'                                      
    SDC_43E  'Orig. cult./raciales - Philippin'                                 
    SDC_43F  'Orig. cult./raciales - Latino-Américain'                          
    SDC_43H  'Orig. cult./raciales - Arabe'                                     
    SDC_43G  'Orig. cult./raciales - Asiat. du Sud-Est'                         
    SDC_43I  'Orig. cult./raciales - Asiatique Occid.'                          
    SDC_43K  'Orig. cult./raciales -Coréen'                                     
    SDC_43J  'Orig. cult./raciales - Japonais'                                  
    SDC_43M  'Orig. cult./raciales - autre'                                     
    SDC_5A_1 'Connaissance des langues officielles'                             
    SDCC5B1  'Langue parlée - maison - Prem. Réponse'                           
    SDCC5B2  'Langue parlée - maison - Deux. Réponse'                           
    SDCC5B3  'Langue parlée - maison - Trois. Réponse'                          
    SDCC61   'Langue maternelle - première réponse'                             
    SDCC62   'Langue maternelle - deuxième réponse'                             
    SDCC63   'Langue maternelle - troisième réponse'                            
    SDCDFOLS 'Première langue officielle parlée'                                
    DHH_OWN  'Propiétaire, locataire'                                           
    SDC_7AA  'Hétérosexuel, homosexuel ou bisexuel'                             
    SDCDLHM  'Première langue officielle - (D)'                                 
    SDCDAIM  'Âge au moment de l''immigration - (D)'                            
    SDCFIMM  'Immigrant - (F)'                                                  
    SDCDRES  'Durée/temps au Can. depuis l''imm. - (D)'                         
    SDCDFL1  'Langue maternelle - (D)'                                          
    SDCDABT  'Identité autochtone'                                              
    SDCDCGT  'Origine culturelle/raciale'                                       
    PMKPROXY 'Personne mieux renseignée'                                        
    EDU_1    'Plus haut niveau études primaires/sec.'                           
    EDU_2    'Obtenu un diplôme d''études secondaires'                          
    EDU_3    'Suivi tout autre cours'                                           
    EDU_4A   'Plus haut certificat ou diplôme obtenu'                           
    EDUDH04  '+ haut niveau/étu. - ménage 4 niv - (D)'                          
    EDUDH10  '+ haut niveau/étu. - ménage 10 niv - (D)'                         
    EDUDR04  '+ haut niveau/étu. - rép. 4 niv - (D)'                            
    EDUDR10  '+ haut niveau études - rép. 10 niv - (D)'                         
    INC_1A   'Source revenu mén.- salaires/traitements'                         
    INC_1B   'Source revenu mén. - travail autonome'                            
    INC_1C   'Source revenu mén. - dividendes&intérêts'                         
    INC_1D   'Source revenu mén. - assurance-emploi'                            
    INC_1E   'Source revenu mén. - accident du travail'                         
    INC_1F   'Source revenu mén.-Régime du Can./Québec'                         
    INC_1G   'Source revenu mén. - régime retr./rentes'                         
    INC_1O   'Source revenu mén. - REER / FERR'                                 
    INC_1H   'Source revenu mén. - Séc. vieill./S.R.G.'                         
    INC_1J   'Source revenu mén. - aide sociale'                                
    INC_1I   'Source revenu mén.- crédit impôt enfants'                         
    INC_1K   'Source revenu mén.-pension alim./enfants'                         
    INC_1L   'Source revenu mén. -pens. alim./conjoint'                         
    INC_1M   'Source revenu mén. - autre'                                       
    INC_1N   'Source revenu mén. - aucune'                                      
    INC_2    'Rev. total/mén. - source principale'                              
    INC_3    'Rev. total/mén.- meilleure estimation'                            
    INC_6A   'Sources du revenu personnel'                                      
    INC_6B   'Sources du revenu personnel'                                      
    INC_6C   'Sources du revenu personnel'                                      
    INC_6D   'Sources du revenu personnel'                                      
    INC_6E   'Sources du revenu personnel'                                      
    INC_6F   'Sources du revenu personnel'                                      
    INC_6G   'Sources du revenu personnel'                                      
    INC_6H   'Sources du revenu personnel'                                      
    INC_6I   'Sources du revenu personnel'                                      
    INC_6J   'Sources du revenu personnel'                                      
    INC_6K   'Sources du revenu personnel'                                      
    INC_6L   'Sources du revenu personnel'                                      
    INC_6M   'Sources du revenu personnel'                                      
    INC_6N   'Sources du revenu personnel'                                      
    INC_6O   'Sources du revenu personnel'                                      
    INC_7    'Source principale du revenu personnel'                            
    INC_8A   'Total revenu personnel'                                           
    INC_8B   'Total revenu personnel'                                           
    INC_8C   'Catégorie de revenu qui s''applique'                              
    INC_8D   'Catégorie de revenu qui s''applique'                              
    INCFIMP4 'Indicateur d''imputation'                                         
    INCDHH   'Rev. total/mén. de toutes sources - (D)'                          
    INCDPER  'Rev. pers. total de toutes sources - (D)'                         
    INCDADR  'Ratio ajusté du revenu des ménages - (D)'                         
    INCDRCA  'Distribution du revenu des ménages - (D)'                         
    INCDRPR  'Distribution du rev. mén.- éch. prv.-(D)'                         
    INCDRRS  'Distribution du rev. mén.- éch. rss -(D)'                         
    WTSFSS1  'Sous-échantillon qui sont valide'                                 
    WTS_F13  'Indicateur de sous-échantillon spéciale'                          
    WTS_S1M  'Poids échantillon - Maître'                                       
    WTS_S1S  'Poids échantillon - Partage'                                      
    .                                                                           
