 format
    GEO_PRV     PROVFM.  
    GEODCMAA    GEOCMAF. 
    GEODPC     $GEO3DPMF.
    GEODHR4     HR4_12FM.
    GEODDHA     GEO_HAFM.
    GEODBCHA    GEODBCFM.
    GEODLHN     GEOLHIN. 
    GEODSAT     GEOSATFM.
    GEODPG11    GEO_PRG. 
    GEODUR      GEO_URFM.
    GEODUR2     GEO_DRFM.
    SAM_CP     $S_CP13FM.
    SAM_TYP     SAME_TYP.
    CASETYPE    CASETPFM.
    SAMDSHR     SAMDSHFM.
    SAMDLNK     YESNOFM. 
    ADM_STA     ADM_STA. 
    ADM_PRX     YESNOFM. 
    ADM_YOI     YEARXFM. 
    ADM_MOI     MONTHFM. 
    ADM_DOI     DAYFM.   
    ADM_N09     TELFM.   
    ADM_N10     YESNOFM. 
    ADM_N11     YESNOFM. 
    ADM_N12     ADM_LNG. 
    ADM_LHH     AM3_LP.  
    DHH_AGE     AGE3DFM. 
    DHH_YOB     YEARFM.  
    DHH_MOB     MONTHFM. 
    DHH_DOB     DAYFM.   
    DHH_SEX     DHC_SEX. 
    DHH_MS      DHC_MAR. 
    DHHDSAGE    AGE3DFM. 
    DHHDYKD     PERS2D.  
    DHHDOKD     PERS2D.  
    DHHDLE5     PERS2D.  
    DHHD611     PERS2D.  
    DHHDL12     PERS2D.  
    DHHDL18     PERS2D.  
    DHHDLVG     DHCDLVG. 
    DHHDECF     DHCDECF. 
    DHHDHSZ     PERS2D.  
    GEN_01      GOOD5FM. 
    GEN_02      GEN_2F.  
    GEN_02A2    GEN02AFM.
    GEN_02B     GOOD5FM. 
    GEN_07      STC_1F.  
    GEN_08      YESNOFM. 
    GEN_09      STC_1F.  
    GEN_10      GEN_10F. 
    GENDHDI     GHCDHDI. 
    GENDMHI     GHCDHDI. 
    GENGSWL     SCR_01FM.
    MAM_037     YESNOFM. 
    HWT_2       HWC_2FM. 
    HWT_2A      HWC_2A.  
    HWT_2B      HWC_2B.  
    HWT_2C      HWC_2C.  
    HWT_2D      HWC_2D.  
    HWT_2E      HWC_2E.  
    HWT_2F      HWC_2F.  
    HWT_3       HWT_FM.  
    HWT_N4      WHTFM.   
    HWT_4       HWS_1F.  
    HWTDHTM     HWT_METR.
    HWTDWTK     HWT_WTK. 
    HWTDBMI     HWTD_BMI.
    HWTDISW     HWTCDISW.
    HWTDCOL     HWTDDCOL.
    HWTDWHO     HWTDWHFM.
    CCC_031     YESNOFM. 
    CCC_035     YESNOFM. 
    CCC_036     YESNOFM. 
    CCC_051     YESNOFM. 
    CCC_061     YESNOFM. 
    CCC_071     YESNOFM. 
    CCC_072     YESNOFM. 
    CCC_073     YESNOFM. 
    CCC_073A    YESNOFM. 
    CCC_073B    YESNOFM. 
    CCC_081     YESNOFM. 
    CCC_091     YESNOFM. 
    CCC_101     YESNOFM. 
    CCC_102     AGE3DFM. 
    CCC_10A     YESNOFM. 
    CCC_10B     YESNOFM. 
    CCC_10C     CCC_10C. 
    CCC_105     YESNOFM. 
    CCC_106     YESNOFM. 
    CCC_121     YESNOFM. 
    CCC_131     YESNOFM. 
    CCC_31A     YESNOFM. 
    CCC_141     YESNOFM. 
    CCC_151     YESNOFM. 
    CCC_161     YESNOFM. 
    CCC_171     YESNOFM. 
    CCC_17A     CCC17AFM.
    CCC_173     YESNOFM. 
    CCC_181     YESNOFM. 
    CCC_280     YESNOFM. 
    CCC_290     YESNOFM. 
    CCCDDIA     CCCDIAFM.
    DOHUI       YESNOFM. 
    HUI_01      YESNOFM. 
    HUI_02      YESNOFM. 
    HUI_03      YESNOFM. 
    HUI_04      YESNOFM. 
    HUI_05      YESNOFM. 
    HUI_06      YESNOFM. 
    HUI_07      YESNOFM. 
    HUI_07A     YESNOFM. 
    HUI_08      YESNOFM. 
    HUI_09      YESNOFM. 
    HUI_10      YESNOFM. 
    HUI_11      YESNOFM. 
    HUI_12      YESNOFM. 
    HUI_13      YESNOFM. 
    HUI_14      YESNOFM. 
    HUI_15      YESNOFM. 
    HUI_16      YESNOFM. 
    HUI_17      YESNOFM. 
    HUI_18      YESNOFM. 
    HUI_19      HSC_19F. 
    HUI_20      YESNOFM. 
    HUI_21      YESNOFM. 
    HUI_22      YESNOFM. 
    HUI_23      HSC_23F. 
    HUI_24      YESNOFM. 
    HUI_25      HSC_25F. 
    HUI_26      HSC_26F. 
    HUI_27      HSC_27F. 
    HUIDVIS     HUIDVIFM.
    HUIDHER     HUIDHEFM.
    HUIDSPE     HUIDSPFM.
    HUIDMOB     HUIDMOFM.
    HUIDDEX     HUIDEXFM.
    HUIDEMO     HUIDEMFM.
    HUIDCOG     HUIDCOFM.
    HUIDHSI     HUIDHSI. 
    HUP_01      YESNOFM. 
    HUP_02      HSC_29F. 
    HUP_03      HSC_30F. 
    HUPDPAD     HSCDPAD. 
    HCU_1AA     YESNOFM. 
    HCU_1BA     YESNOFM. 
    HCU_1BB     YESNOFM. 
    HCU_1BC     YESNOFM. 
    HCU_1BD     YESNOFM. 
    HCU_1BE     YESNOFM. 
    HCU_1A1     YESNOFM. 
    HCU_1A2     HCU1A2FM.
    HCU_1AC     ADM_LN2G.
    CHP_01      YESNOFM. 
    CHP_02      NIGHT3D. 
    CHP_03      YESNOFM. 
    CHP_04      TIMES3D. 
    CHP_05      HCC_CONT.
    CHP_06      YESNOFM. 
    CHP_07      TIMES2D. 
    CHP_08      YESNOFM. 
    CHP_09      TIMES3D. 
    CHP_10      HCC_CONT.
    CHP_11      YESNOFM. 
    CHP_12      TIMES3D. 
    CHP_13      HCC_CONT.
    CHP_14      YESNOFM. 
    CHP_15      TIMES3D. 
    CHPDMDC     CON3DFM. 
    RAC_1       SOMETIME.
    RAC_2A      SOMETIME.
    RAC_2B1     RAC2B1FM.
    RAC_2B2     RAC2B2FM.
    RAC_2C      SOMETIME.
    RAC_5       RAC_5FM. 
    RACDIMP     SOMETIME.
    RACDPAL     SOMETIME.
    DOADL       YESNOFM. 
    ADL_01      YESNOFM. 
    ADL_02      YESNOFM. 
    ADL_03      YESNOFM. 
    ADL_04      YESNOFM. 
    ADL_05      YESNOFM. 
    ADL_06      YESNOFM. 
    ADLF6R      YESNOFM. 
    FLU_160     YESNOFM. 
    FLU_162     FS52F.   
    FLU_164     MONTHFM. 
    FLU_165     INJ_4F.  
    FLU_66A     YESNOFM. 
    FLU_66B     YESNOFM. 
    FLU_66C     YESNOFM. 
    FLU_66D     YESNOFM. 
    FLU_66E     YESNOFM. 
    FLU_66F     YESNOFM. 
    FLU_66G     YESNOFM. 
    FLU_66H     YESNOFM. 
    FLU_66I     YESNOFM. 
    FLU_66J     YESNOFM. 
    FLU_66K     YESNOFM. 
    FLU_66L     YESNOFM. 
    FLU_66M     YESNOFM. 
    FLU_66O     YESNOFM. 
    FLU_66N     YESNOFM. 
    FVC_1A      FVC_1A.  
    FVC_1B      TIMES2D. 
    FVC_1C      TIMES2D. 
    FVC_1D      TIMES3D. 
    FVC_1E      TIMES3D. 
    FVC_2A      FVC_1A.  
    FVC_2B      TIMES2D. 
    FVC_2C      TIMES2D. 
    FVC_2D      TIMES3D. 
    FVC_2E      TIMES3D. 
    FVC_3A      FVC_1A.  
    FVC_3B      TIMES2D. 
    FVC_3C      TIMES2D. 
    FVC_3D      TIMES3D. 
    FVC_3E      TIMES3D. 
    FVC_4A      FVC_1A.  
    FVC_4B      TIMES2D. 
    FVC_4C      TIMES2D. 
    FVC_4D      TIMES3D. 
    FVC_4E      TIMES3D. 
    FVC_5A      FVC_1A.  
    FVC_5B      TIMES2D. 
    FVC_5C      TIMES2D. 
    FVC_5D      TIMES3D. 
    FVC_5E      TIMES3D. 
    FVC_6A      FVC_1A.  
    FVC_6B      SERV2FM. 
    FVC_6C      SERV2FM. 
    FVC_6D      SERV3FM. 
    FVC_6E      SERV3FM. 
    FVCDJUI     FVC_DC.  
    FVCDFRU     FVC_DC.  
    FVCDSAL     FVC_DC.  
    FVCDPOT     FVC_DC.  
    FVCDCAR     FVC_DC.  
    FVCDVEG     FVC_PO.  
    FVCDTOT     FVC_DC.  
    FVCGTOT     FVC_RDA. 
    PAC_1A      YESNOFM. 
    PAC_1B      YESNOFM. 
    PAC_1C      YESNOFM. 
    PAC_1D      YESNOFM. 
    PAC_1E      YESNOFM. 
    PAC_1F      YESNOFM. 
    PAC_1G      YESNOFM. 
    PAC_1H      YESNOFM. 
    PAC_1I      YESNOFM. 
    PAC_1J      YESNOFM. 
    PAC_1K      YESNOFM. 
    PAC_1L      YESNOFM. 
    PAC_1M      YESNOFM. 
    PAC_1N      YESNOFM. 
    PAC_1O      YESNOFM. 
    PAC_1P      YESNOFM. 
    PAC_1Q      YESNOFM. 
    PAC_1R      YESNOFM. 
    PAC_1S      YESNOFM. 
    PAC_1T      YESNOFM. 
    PAC_1Z      YESNOFM. 
    PAC_1U      YESNOFM. 
    PAC_1V      YESNOFM. 
    PAC_1W      YESNOFM. 
    PAC_1X      YESNOFM. 
    PAC_2A      TIMES3D. 
    PAC_3A      PAC_TIME.
    PAC_2B      TIMES3D. 
    PAC_3B      PAC_TIME.
    PAC_2C      TIMES3D. 
    PAC_3C      PAC_TIME.
    PAC_2D      TIMES3D. 
    PAC_3D      PAC_TIME.
    PAC_2E      TIMES3D. 
    PAC_3E      PAC_TIME.
    PAC_2F      TIMES3D. 
    PAC_3F      PAC_TIME.
    PAC_2G      TIMES3D. 
    PAC_3G      PAC_TIME.
    PAC_2H      TIMES3D. 
    PAC_3H      PAC_TIME.
    PAC_2I      TIMES3D. 
    PAC_3I      PAC_TIME.
    PAC_2J      TIMES3D. 
    PAC_3J      PAC_TIME.
    PAC_2K      TIMES3D. 
    PAC_3K      PAC_TIME.
    PAC_2L      TIMES3D. 
    PAC_3L      PAC_TIME.
    PAC_2M      TIMES3D. 
    PAC_3M      PAC_TIME.
    PAC_2N      TIMES3D. 
    PAC_3N      PAC_TIME.
    PAC_2O      TIMES3D. 
    PAC_3O      PAC_TIME.
    PAC_2P      TIMES3D. 
    PAC_3P      PAC_TIME.
    PAC_2Q      TIMES3D. 
    PAC_3Q      PAC_TIME.
    PAC_2R      TIMES3D. 
    PAC_3R      PAC_TIME.
    PAC_2S      TIMES3D. 
    PAC_3S      PAC_TIME.
    PAC_2T      TIMES3D. 
    PAC_3T      PAC_TIME.
    PAC_2Z      TIMES3D. 
    PAC_3Z      PAC_TIME.
    PAC_2U      TIMES3D. 
    PAC_3U      PAC_TIME.
    PAC_2W      TIMES3D. 
    PAC_3W      PAC_TIME.
    PAC_2X      TIMES3D. 
    PAC_3X      PAC_TIME.
    PAC_7       PACF_7FM.
    PAC_7A      TIMES3D. 
    PAC_7B      PAC_TIME.
    PAC_8       PACF_7FM.
    PAC_8A      TIMES3D. 
    PAC_8B      PAC_TIME.
    PACDEE      PACDEE.  
    PACFLEI     YESNOFM. 
    PACDFM      PACDFM.  
    PACDFR      PACDFR.  
    PACFD       YESNOFM. 
    PACDPAI     PACDPAI. 
    PACDLTI     PACDPAI. 
    PACDTLE     PACDTLFM.
    PACFLTI     YESNOFM. 
    DOUPE       YESNOFM. 
    UPE_01A     YESNOFM. 
    UPE_01      PAC_5F.  
    UPE_02      YESNOFM. 
    UPE_02A     PAC_5F.  
    UPE_02B     PAC_5F.  
    UPE_02C     PAC_5F.  
    UPE_02D     PAC_5F.  
    UPE_03A     UPEC3AFM.
    UPE_03B     UPEC3AFM.
    UPE_04A     PAC_5F.  
    UPE_05A     PAC_5F.  
    UPE_05B     PAC_5F.  
    UPE_06      YESNOFM. 
    UPE_06A     PAC_5F.  
    UPE_06B     PAC_5F.  
    UPE_06C     PAC_5F.  
    UPE_07      YESNOFM. 
    UPE_07A     PAC_5F.  
    UPEFILS     YESNOFM. 
    UPEFSKB     YESNOFM. 
    UPEFSNB     YESNOFM. 
    DOINJ       YESNOFM. 
    REP_1A      YESNOFM. 
    REP_2       YESNOFM. 
    REP_3       RPC03FM. 
    REP_3A      YESNOFM. 
    REP_4       YESNOFM. 
    REP_5A      YESNOFM. 
    REP_5B      YESNOFM. 
    REP_5C      YESNOFM. 
    REP_5D      YESNOFM. 
    REP_5F      YESNOFM. 
    REP_5G      YESNOFM. 
    REP_5H      YESNOFM. 
    REP_5I      YESNOFM. 
    INJ_01      YESNOFM. 
    INJ_02      TIMES2D. 
    INJ_03      MONTHFM. 
    INJ_04      INJ_4F.  
    INJ_05      IJC03F.  
    INJ_06      IJC04F.  
    INJ_07      IJC_4A.  
    INJ_08      IJC05F.  
    INJ_09      INJQ09FM.
    INW_01      YESNOFM. 
    INWF02      YESNOFM. 
    INWF03      YESNOFM. 
    INWCSIC    $LBSS_CFM.
    INWCSOC    $LBSS_CFM.
    INWF04      YESNOFM. 
    INWDOCG    $LBSDOCFM.
    INWDING    $LBSDINFM.
    INJ_10      YESNOFM. 
    INJ_11A     INJ11_FM.
    INJ_12      IJC_10B. 
    INJ_12A     INJ12AFM.
    INJ_13      YESNOFM. 
    INJ_14A     YESNOFM. 
    INJ_14B     YESNOFM. 
    INJ_14C     YESNOFM. 
    INJ_14L     YESNOFM. 
    INJ_14M     YESNOFM. 
    INJ_14F     YESNOFM. 
    INJ_14N     YESNOFM. 
    INJ_14O     YESNOFM. 
    INJ_14K     YESNOFM. 
    INJ_15      YESNOFM. 
    INJ_15A     YESNOFM. 
    INJ_16      YESNOFM. 
    INJ_17      IJC_NUM. 
    INJDTBS     INJ_TBS. 
    INJDCAU     INJ_CAU. 
    INJDCBP     IJCD2FM. 
    INJDSTT     INJ_STT. 
    SMK_01A     YESNOFM. 
    SMK_01B     YESNOFM. 
    SMK_01C     AGE3DFM. 
    SMK_202     SMC_2F.  
    SMK_203     AGE3DFM. 
    SMK_204     CIG_NUM. 
    SMK_05B     CIG_NUM. 
    SMK_05C     DAY2DFM. 
    SMK_05D     YESNOFM. 
    SMK_06A     SMKCFM.  
    SMK_06B     MONTHFM. 
    SMK_06C     YEAR3NUM.
    SMK_207     AGE3DFM. 
    SMK_208     CIG_NUM. 
    SMK_09A     SMKCFM.  
    SMK_09B     MONTHFM. 
    SMK_09C     YEAR3NUM.
    SMK_10      YESNOFM. 
    SMK_10A     SMKCFM.  
    SMK_10B     MONTHFM. 
    SMK_10C     YEAR3NUM.
    SMKDSTY     SMCDTYP. 
    SMKDSTP     YEAR3NUM.
    SMKDYCS     YEAR3NUM.
    ETS_10      YESNOFM. 
    ETS_11      PERS2D.  
    ETS_20      YESNOFM. 
    ETS_20B     YESNOFM. 
    ETS_35      YESNOFM. 
    ETS_36      YESNOFM. 
    ETS_37A     YESNOFM. 
    ETS_37B     YESNOFM. 
    ETS_37C     YESNOFM. 
    ETS_37D     YESNOFM. 
    ALC_1       YESNOFM. 
    ALC_2       ALC6_2F. 
    ALC_3       ALC_3F.  
    ALCDTTM     ALCDTTFM.
    DOSXB       YESNOFM. 
    SXB_1       YESNOFM. 
    SXB_2       AGE3DFM. 
    SXB_3       YESNOFM. 
    SXB_4       SHS_4F.  
    SXB_07      YESNOFM. 
    SXB_7A      YESNOFM. 
    SXB_09      AGREEFM. 
    SXB_10      SXB102FM.
    SXB_11      YESNOFM. 
    SXB_12A     YESNOFM. 
    SXB_12B     YESNOFM. 
    SXB_12C     YESNOFM. 
    SXB_12D     YESNOFM. 
    SXB_12F     YESNOFM. 
    SXB_12E     YESNOFM. 
    SXB_13A     YESNOFM. 
    SXB_13B     YESNOFM. 
    SXB_13C     YESNOFM. 
    SXB_13D     YESNOFM. 
    SXB_13F     YESNOFM. 
    SXB_13G     YESNOFM. 
    SXB_13E     YESNOFM. 
    DOACC       YESNOFM. 
    ACC_10      YESNOFM. 
    ACC_11      YESNOFM. 
    ACC_12A     YESNOFM. 
    ACC_12B     YESNOFM. 
    ACC_12C     YESNOFM. 
    ACC_12D     YESNOFM. 
    ACC_12E     YESNOFM. 
    ACC_12F     YESNOFM. 
    ACC_12G     YESNOFM. 
    ACC_12H     YESNOFM. 
    ACC_12I     YESNOFM. 
    ACC_12J     YESNOFM. 
    ACC_12K     YESNOFM. 
    ACC_12L     YESNOFM. 
    ACC_12M     YESNOFM. 
    ACC_12N     YESNOFM. 
    ACC_20      YESNOFM. 
    ACC_21      YESNOFM. 
    ACC_22A     YESNOFM. 
    ACC_22B     YESNOFM. 
    ACC_22C     YESNOFM. 
    ACC_22D     YESNOFM. 
    ACC_22E     YESNOFM. 
    ACC_22F     YESNOFM. 
    ACC_22G     YESNOFM. 
    ACC_22H     YESNOFM. 
    ACC_22I     YESNOFM. 
    ACC_22J     YESNOFM. 
    ACC_22K     YESNOFM. 
    ACC_22L     YESNOFM. 
    ACC_22M     YESNOFM. 
    ACC_22N     YESNOFM. 
    ACC_22O     YESNOFM. 
    ACC_30      YESNOFM. 
    ACC_31      YESNOFM. 
    ACC_32A     YESNOFM. 
    ACC_32B     YESNOFM. 
    ACC_32C     YESNOFM. 
    ACC_32D     YESNOFM. 
    ACC_32E     YESNOFM. 
    ACC_32F     YESNOFM. 
    ACC_32G     YESNOFM. 
    ACC_32H     YESNOFM. 
    ACC_32I     YESNOFM. 
    ACC_32J     YESNOFM. 
    ACC_32K     YESNOFM. 
    ACC_32L     YESNOFM. 
    ACC_32M     YESNOFM. 
    ACC_32N     YESNOFM. 
    ACC_40      YESNOFM. 
    ACC_40A     YESNOFM. 
    ACC_40B     YESNOFM. 
    ACC_40C     YESNOFM. 
    ACC_40D     YESNOFM. 
    ACC_40E     YESNOFM. 
    ACC_40F     YESNOFM. 
    ACC_40G     YESNOFM. 
    ACC_41      YESNOFM. 
    ACC_42      YESNO.   
    ACC_43A     YESNOFM. 
    ACC_43B     YESNOFM. 
    ACC_43C     YESNOFM. 
    ACC_43D     YESNOFM. 
    ACC_43E     YESNOFM. 
    ACC_43F     YESNOFM. 
    ACC_43G     YESNOFM. 
    ACC_43H     YESNOFM. 
    ACC_43I     YESNOFM. 
    ACC_44      YESNO.   
    ACC_45A     YESNOFM. 
    ACC_45B     YESNOFM. 
    ACC_45C     YESNOFM. 
    ACC_45D     YESNOFM. 
    ACC_45E     YESNOFM. 
    ACC_45F     YESNOFM. 
    ACC_45G     YESNOFM. 
    ACC_45H     YESNOFM. 
    ACC_45I     YESNOFM. 
    ACC_46      YESNO.   
    ACC_47A     YESNOFM. 
    ACC_47B     YESNOFM. 
    ACC_47C     YESNOFM. 
    ACC_47D     YESNOFM. 
    ACC_47E     YESNOFM. 
    ACC_47F     YESNOFM. 
    ACC_47G     YESNOFM. 
    ACC_47H     YESNOFM. 
    ACC_47I     YESNOFM. 
    ACC_50A     YESNOFM. 
    ACC_50      YESNOFM. 
    ACC_51      YESNOFM. 
    ACC_52      YESNO.   
    ACC_53A     YESNOFM. 
    ACC_53B     YESNOFM. 
    ACC_53C     YESNOFM. 
    ACC_53D     YESNOFM. 
    ACC_53E     YESNOFM. 
    ACC_53F     YESNOFM. 
    ACC_53G     YESNOFM. 
    ACC_53H     YESNOFM. 
    ACC_53I     YESNOFM. 
    ACC_53J     YESNOFM. 
    ACC_53K     YESNOFM. 
    ACC_53L     YESNOFM. 
    ACC_53M     YESNOFM. 
    ACC_54      YESNO.   
    ACC_55A     YESNOFM. 
    ACC_55B     YESNOFM. 
    ACC_55C     YESNOFM. 
    ACC_55D     YESNOFM. 
    ACC_55E     YESNOFM. 
    ACC_55F     YESNOFM. 
    ACC_55G     YESNOFM. 
    ACC_55H     YESNOFM. 
    ACC_55I     YESNOFM. 
    ACC_55J     YESNOFM. 
    ACC_55K     YESNOFM. 
    ACC_55L     YESNOFM. 
    ACC_55M     YESNOFM. 
    ACC_60      YESNOFM. 
    ACC_61      YESNOFM. 
    ACC_62      YESNO.   
    ACC_63A     YESNOFM. 
    ACC_63B     YESNOFM. 
    ACC_63C     YESNOFM. 
    ACC_63D     YESNOFM. 
    ACC_63E     YESNOFM. 
    ACC_63F     YESNOFM. 
    ACC_63G     YESNOFM. 
    ACC_63H     YESNOFM. 
    ACC_63I     YESNOFM. 
    ACC_63J     YESNOFM. 
    ACC_63K     YESNOFM. 
    ACC_63L     YESNOFM. 
    ACC_63M     YESNOFM. 
    ACC_64      YESNO.   
    ACC_65A     YESNOFM. 
    ACC_65B     YESNOFM. 
    ACC_65C     YESNOFM. 
    ACC_65D     YESNOFM. 
    ACC_65E     YESNOFM. 
    ACC_65F     YESNOFM. 
    ACC_65G     YESNOFM. 
    ACC_65H     YESNOFM. 
    ACC_65I     YESNOFM. 
    ACC_65J     YESNOFM. 
    ACC_65K     YESNOFM. 
    ACC_65L     YESNOFM. 
    ACC_65M     YESNOFM. 
    ACC_66      YESNO.   
    ACC_67A     YESNOFM. 
    ACC_67B     YESNOFM. 
    ACC_67C     YESNOFM. 
    ACC_67D     YESNOFM. 
    ACC_67E     YESNOFM. 
    ACC_67F     YESNOFM. 
    ACC_67G     YESNOFM. 
    ACC_67H     YESNOFM. 
    ACC_67I     YESNOFM. 
    ACC_67J     YESNOFM. 
    ACC_67K     YESNOFM. 
    ACC_67L     YESNOFM. 
    ACC_67M     YESNOFM. 
    DOWTM       YESNOFM. 
    WTM_01      YESNOFM. 
    WTM_02      WTMC02FM.
    WTM_03      WTMC03FM.
    WTM_04      YESNOFM. 
    WTM_05      YESNOFM. 
    WTM_06A     YESNOFM. 
    WTM_06B     YESNOFM. 
    WTM_06C     YESNOFM. 
    WTM_06D     YESNOFM. 
    WTM_06E     YESNOFM. 
    WTM_06F     YESNOFM. 
    WTM_06G     YESNOFM. 
    WTM_06H     YESNOFM. 
    WTM_06I     YESNOFM. 
    WTM_06J     YESNOFM. 
    WTM_06K     YESNOFM. 
    WTM_06L     YESNOFM. 
    WTM_06M     YESNOFM. 
    WTM_07A     WTMC7AFM.
    WTM_07B     WTMC7BFM.
    WTM_08A     WTMC7AFM.
    WTM_08B     WTMC7BFM.
    WTM_10      WTMC10FM.
    WTM_11A     WTMC7AFM.
    WTM_11B     WTMC7BFM.
    WTM_12      YESNOFM. 
    WTM_13A     YESNOFM. 
    WTM_13B     YESNOFM. 
    WTM_13C     YESNOFM. 
    WTM_14      YESNOFM. 
    WTM_15A     YESNOFM. 
    WTM_15B     YESNOFM. 
    WTM_15C     YESNOFM. 
    WTM_15D     YESNOFM. 
    WTM_15E     YESNOFM. 
    WTM_15F     YESNOFM. 
    WTM_15G     YESNOFM. 
    WTM_15H     YESNOFM. 
    WTM_15I     YESNOFM. 
    WTM_15J     YESNOFM. 
    WTM_15K     YESNOFM. 
    WTM_15L     YESNOFM. 
    WTM_16      WTMC16FM.
    WTM_17      YESNOFM. 
    WTM_18      YESNOFM. 
    WTM_19      YESNOFM. 
    WTM_20A     YESNOFM. 
    WTM_20B     YESNOFM. 
    WTM_20C     YESNOFM. 
    WTM_20D     YESNOFM. 
    WTM_20E     YESNOFM. 
    WTM_20F     YESNOFM. 
    WTM_20G     YESNOFM. 
    WTM_20H     YESNOFM. 
    WTM_20I     YESNOFM. 
    WTM_20J     YESNOFM. 
    WTM_20K     YESNOFM. 
    WTM_20L     YESNOFM. 
    WTM_20M     YESNOFM. 
    WTM_20N     YESNOFM. 
    WTM_21A     WTMC7AFM.
    WTM_21B     WTMC7BFM.
    WTM_22      YESNOFM. 
    WTM_23A     WTMC7AFM.
    WTM_23B     WTMC7BFM.
    WTM_24      WTMC10FM.
    WTM_25A     WTMC7AFM.
    WTM_25B     WTMC7BFM.
    WTM_26      YESNOFM. 
    WTM_27A     YESNOFM. 
    WTM_27B     YESNOFM. 
    WTM_27C     YESNOFM. 
    WTM_27D     YESNOFM. 
    WTM_28      YESNOFM. 
    WTM_29A     YESNOFM. 
    WTM_29B     YESNOFM. 
    WTM_29C     YESNOFM. 
    WTM_29D     YESNOFM. 
    WTM_29E     YESNOFM. 
    WTM_29F     YESNOFM. 
    WTM_29G     YESNOFM. 
    WTM_29H     YESNOFM. 
    WTM_29I     YESNOFM. 
    WTM_29J     YESNOFM. 
    WTM_29K     YESNOFM. 
    WTM_29L     YESNOFM. 
    WTM_30      WTMCFM.  
    WTM_31      WTM31FM. 
    WTM_32      YESNOFM. 
    WTM_33      WTM33FM. 
    WTM_34      WTMC34FM.
    WTM_35      YESNOFM. 
    WTM_36      YESNOFM. 
    WTM_37A     YESNOFM. 
    WTM_37B     YESNOFM. 
    WTM_37C     YESNOFM. 
    WTM_37D     YESNOFM. 
    WTM_37E     YESNOFM. 
    WTM_37F     YESNOFM. 
    WTM_37G     YESNOFM. 
    WTM_37H     YESNOFM. 
    WTM_37I     YESNOFM. 
    WTM_37J     YESNOFM. 
    WTM_37K     YESNOFM. 
    WTM_37L     YESNOFM. 
    WTM_37M     YESNOFM. 
    WTM_38A     WTMC7AFM.
    WTM_38B     WTMC7BFM.
    WTM_39A     WTMC7AFM.
    WTM_39B     WTMC7BFM.
    WTM_40      WTMC10FM.
    WTM_41A     WTMC7AFM.
    WTM_41B     WTMC7BFM.
    WTM_42      YESNOFM. 
    WTM_43      WTMC43FM.
    WTM_44      YESNOFM. 
    WTM_45A     YESNOFM. 
    WTM_45B     YESNOFM. 
    WTM_45C     YESNOFM. 
    WTM_45D     YESNOFM. 
    WTM_45E     YESNOFM. 
    WTM_45F     YESNOFM. 
    WTM_45G     YESNOFM. 
    WTM_45H     YESNOFM. 
    WTM_45I     YESNOFM. 
    WTM_45J     YESNOFM. 
    WTM_45K     YESNOFM. 
    WTM_45L     YESNOFM. 
    WTMDSO      DAY4DFM. 
    WTMDSN      DAY4DFM. 
    WTMDSA      DAY4DFM. 
    WTMDCO      DAY4DFM. 
    WTMDCN      DAY4DFM. 
    WTMDCA      DAY4DFM. 
    WTMDTO      DAY4DFM. 
    WTMDTN      DAY4DFM. 
    WTMDTA      DAY4DFM. 
    LBS_01      LSC_1F.  
    LBS_02      YESNOFM. 
    LBS_03      YESNOFM. 
    LBS_11      YESNOFM. 
    LBS_31      LSC_31F. 
    LBSF32      YESNOFM. 
    LBSF33      YESNOFM. 
    LBSF34      YESNOFM. 
    LBSF35      YESNOFM. 
    LBSCSIC    $LBSS_CFM.
    LBSCSOC    $LBSS_CFM.
    LBSF36      YESNOFM. 
    LBS_42      HOUR3DFM.
    LBS_53      HOUR3DFM.
    LBSDHPW     LSCDHPW. 
    LBSDPFT     LBF_PFT. 
    LBSDWSS     LSCDCWS. 
    LBSDING    $LBSDINFM.
    LBSDOCG    $LBSDOCFM.
    SDC_8       YESNOFM. 
    SDC_9       EDUQ06FM.
    SDCCCB13    SDCB10FM.
    SDCGCB10    SDCG10FM.
    SDC_2       YESNOFM. 
    SDC_3       SDYEARFM.
    SDC_4A      YESNOFM. 
    SDC_4B      YESNOFM. 
    SDC_4C      YESNOFM. 
    SDC_4D      YESNOFM. 
    SDC_4E      YESNOFM. 
    SDC_4F      YESNOFM. 
    SDC_4G      YESNOFM. 
    SDC_4H      YESNOFM. 
    SDC_4I      YESNOFM. 
    SDC_4J      YESNOFM. 
    SDC_4K      YESNOFM. 
    SDC_4L      YESNOFM. 
    SDC_4M      YESNOFM. 
    SDC_4N      YESNOFM. 
    SDC_4T      YESNOFM. 
    SDC_4U      YESNOFM. 
    SDC_4V      YESNOFM. 
    SDC_4P      YESNOFM. 
    SDC_4Q      YESNOFM. 
    SDC_4R      YESNOFM. 
    SDC_4S      YESNOFM. 
    SDC_41      YESNOFM. 
    SDC_42A     YESNOFM. 
    SDC_42B     YESNOFM. 
    SDC_42C     YESNOFM. 
    SDC_43A     YESNOFM. 
    SDC_43C     YESNOFM. 
    SDC_43B     YESNOFM. 
    SDC_43D     YESNOFM. 
    SDC_43E     YESNOFM. 
    SDC_43F     YESNOFM. 
    SDC_43H     YESNOFM. 
    SDC_43G     YESNOFM. 
    SDC_43I     YESNOFM. 
    SDC_43K     YESNOFM. 
    SDC_43J     YESNOFM. 
    SDC_43M     YESNOFM. 
    SDC_5A_1    SDCQ5AFM.
    SDCC5B1     SDCC61FM.
    SDCC5B2     SDCC61FM.
    SDCC5B3     SDCC61FM.
    SDCC61      SDCC61FM.
    SDCC62      SDCC61FM.
    SDCC63      SDCC61FM.
    SDCDFOLS    SDCFOLFM.
    DHH_OWN     DHH011FM.
    SDC_7AA     SDC7AFM. 
    SDCDLHM     SDCDLNFM.
    SDCDAIM     AGE3DFM. 
    SDCFIMM     YESNOFM. 
    SDCDRES     AGE3DFM. 
    SDCDFL1     SDCDFLFM.
    SDCDABT     SDC_ABO. 
    SDCDCGT     SDC_CG.  
    PMKPROXY    PMKP18FM.
    EDU_1       EDUGRADE.
    EDU_2       YESNOFM. 
    EDU_3       YESNOFM. 
    EDU_4A      EDUQ4AFM.
    EDUDH04     DVED3FM. 
    EDUDH10     EDU_10DR.
    EDUDR04     EDUDR4FM.
    EDUDR10     EDU_10DR.
    INC_1A      YESNOFM. 
    INC_1B      YESNOFM. 
    INC_1C      YESNOFM. 
    INC_1D      YESNOFM. 
    INC_1E      YESNOFM. 
    INC_1F      YESNOFM. 
    INC_1G      YESNOFM. 
    INC_1O      YESNOFM. 
    INC_1H      YESNOFM. 
    INC_1J      YESNOFM. 
    INC_1I      YESNOFM. 
    INC_1K      YESNOFM. 
    INC_1L      YESNOFM. 
    INC_1M      YESNOFM. 
    INC_1N      YESNOFM. 
    INC_2       INC_Q2FM.
    INC_3       DOLL8_FM.
    INC_6A      YESNOFM. 
    INC_6B      YESNOFM. 
    INC_6C      YESNOFM. 
    INC_6D      YESNOFM. 
    INC_6E      YESNOFM. 
    INC_6F      YESNOFM. 
    INC_6G      YESNOFM. 
    INC_6H      YESNOFM. 
    INC_6I      YESNOFM. 
    INC_6J      YESNOFM. 
    INC_6K      YESNOFM. 
    INC_6L      YESNOFM. 
    INC_6M      YESNOFM. 
    INC_6N      YESNOFM. 
    INC_6O      YESNOFM. 
    INC_7       INC_Q2FM.
    INC_8A      DOLL8_FM.
    INC_8B      INCQ8BFM.
    INC_8C      INC_8CFM.
    INC_8D      INCQ8DFM.
    INCFIMP4    INCMPEFM.
    INCDHH      INC_DHFM.
    INCDPER     INCDPEFM.
    INCDADR     INCRATFM.
    INCDRCA     INCDECFM.
    INCDRPR     INCDECFM.
    INCDRRS     INCDECFM.
                       ;
