default:
  osf:
    token: !expr Sys.getenv("OSF_PAT")
    project_id: !expr Sys.getenv("OSF_PROJECT_ID")
    documentation_component_id: "jm8bx"

  cchs:
    project_id: "6p3n9"
    documentation_component_id: "jm8bx"

  chms:
    project_id: "buva4"
    cycles:
      cycle1: "t4u72"
      cycle2: "afcn5"
      cycle3: "6hdre"
      cycle4: "bw47u"
      cycle5: "5pxdn"
      cycle6: "auf54"

development:
  osf:
    token: !expr Sys.getenv("OSF_PAT")
    project_id: !expr Sys.getenv("OSF_PROJECT_ID")
    documentation_component_id: "jm8bx"

  cchs:
    project_id: "6p3n9"
    documentation_component_id: "jm8bx"

  chms:
    project_id: "buva4"
    cycles:
      cycle1: "t4u72"
      cycle2: "afcn5"
      cycle3: "6hdre"
      cycle4: "bw47u"
      cycle5: "5pxdn"
      cycle6: "auf54"

production:
  osf:
    token: !expr Sys.getenv("OSF_PAT")
    project_id: !expr Sys.getenv("OSF_PROJECT_ID")
    documentation_component_id: "jm8bx"

  cchs:
    project_id: "6p3n9"
    documentation_component_id: "jm8bx"

  chms:
    project_id: "buva4"
    cycles:
      cycle1: "t4u72"
      cycle2: "afcn5"
      cycle3: "6hdre"
      cycle4: "bw47u"
      cycle5: "5pxdn"
      cycle6: "auf54"