 format
    GEO_PRV     PROVFM.  
    GEODPC     $GEO3DPMF.
    GEODHR4     HR4_11FM.
    GEODSHR     GEOSHRFM.
    GEODDHA     GEO_HAFM.
    GEODLHA     GEOLHAFM.
    GEODRHA     HR2007FM.
    GEODBCHA    GEODBCFM.
    GEODLHN     GEOLHIN. 
    GEODSAT     GEOSATFM.
    GEODCMA6    DVCMA6FM.
    GEODPG11    GEO_PRG. 
    GEODUR      GEO_URFM.
    GEODUR2     GEO_DRFM.
    SAM_CP     $S_CP11FM.
    SAM_TYP     SAME_TYP.
    SAMDSHR     SAMDSHFM.
    SAMDLNK     YESNOFM. 
    ADM_STA     ADM_STA. 
    ADM_PRX     YESNOFM. 
    ADM_YOI     YEARXFM. 
    ADM_MOI     MONTHFM. 
    ADM_DOI     DAYFM.   
    ADM_N09     TELFM.   
    ADM_N10     YESNOFM. 
    ADM_N11     YESNOFM. 
    ADM_N12     ADM_LNG. 
    ADM_LHH     AM3_LP.  
    DHH_AGE     AGE3DFM. 
    DHH_YOB     YEARFM.  
    DHH_MOB     MONTHFM. 
    DHH_DOB     DAYFM.   
    DHH_SEX     DHC_SEX. 
    DHH_MS      DHC_MAR. 
    DHHDSAGE    AGE3DFM. 
    DHHDYKD     PERS2D.  
    DHHDOKD     PERS2D.  
    DHHDLE5     PERS2D.  
    DHHD611     PERS2D.  
    DHHDL12     PERS2D.  
    DHHDL18     PERS2D.  
    DHHDLVG     DHCDLVG. 
    DHHDECF     DHCDECF. 
    DHHDHSZ     PERS2D.  
    GEN_01      GOOD5FM. 
    GEN_02      GEN_2F.  
    GEN_02A2    GEN02AFM.
    GEN_02B     GOOD5FM. 
    GEN_07      STC_1F.  
    GEN_08      YESNOFM. 
    GEN_09      STC_1F.  
    GEN_10      GEN_10F. 
    GENDHDI     GHCDHDI. 
    GENDMHI     GHCDHDI. 
    GENGSWL     SCR_01FM.
    DOPMH       YESNOFM. 
    PMH_01      PMHQ01FM.
    PMH_02      PMHQ01FM.
    PMH_03      PMHQ01FM.
    PMH_04      PMHQ01FM.
    PMH_05      PMHQ01FM.
    PMH_06      PMHQ01FM.
    PMH_07      PMHQ01FM.
    PMH_08      PMHQ01FM.
    PMH_09      PMHQ01FM.
    PMH_10      PMHQ01FM.
    PMH_11      PMHQ01FM.
    PMH_12      PMHQ01FM.
    PMH_13      PMHQ01FM.
    PMH_14      PMHQ01FM.
    PMHDCLA     PMHCLAFM.
    PMHDSCR     PMHSCRFM.
    MAM_037     YESNOFM. 
    HWT_2       HWC_2FM. 
    HWT_2A      HWC_2A.  
    HWT_2B      HWC_2B.  
    HWT_2C      HWC_2C.  
    HWT_2D      HWC_2D.  
    HWT_2E      HWC_2E.  
    HWT_2F      HWC_2F.  
    HWT_3       HWT_FM.  
    HWT_N4      WHTFM.   
    HWT_4       HWS_1F.  
    HWTDHTM     HWT_METR.
    HWTDWTK     HWT_WTK. 
    HWTDBMI     HWTD_BMI.
    HWTDISW     HWTCDISW.
    HWTDCOL     HWTDDCOL.
    CCC_031     YESNOFM. 
    CCC_035     YESNOFM. 
    CCC_036     YESNOFM. 
    CCC_051     YESNOFM. 
    CCC_061     YESNOFM. 
    CCC_071     YESNOFM. 
    CCC_072     YESNOFM. 
    CCC_073     YESNOFM. 
    CCC_073A    YESNOFM. 
    CCC_073B    YESNOFM. 
    CCC_081     YESNOFM. 
    CCC_091     YESNOFM. 
    CCC_101     YESNOFM. 
    CCC_102     AGE3DFM. 
    CCC_10A     YESNOFM. 
    CCC_10B     YESNOFM. 
    CCC_10C     CCC_10C. 
    CCC_105     YESNOFM. 
    CCC_106     YESNOFM. 
    CCC_121     YESNOFM. 
    CCC_131     YESNOFM. 
    CCC_31A     YESNOFM. 
    CCC_141     YESNOFM. 
    CCC_151     YESNOFM. 
    CCC_161     YESNOFM. 
    CCC_171     YESNOFM. 
    CCC_17A     CCC17AFM.
    CCC_181     YESNOFM. 
    CCC_280     YESNOFM. 
    CCC_290     YESNOFM. 
    CCCDDIA     CCCDIAFM.
    HUP_01      YESNOFM. 
    HUP_02      HSC_29F. 
    HUP_03      HSC_30F. 
    HUPDPAD     HSCDPAD. 
    HCU_1AA     YESNOFM. 
    HCU_1BA     YESNOFM. 
    HCU_1BB     YESNOFM. 
    HCU_1BC     YESNOFM. 
    HCU_1BD     YESNOFM. 
    HCU_1BE     YESNOFM. 
    HCU_1A1     YESNOFM. 
    HCU_1A2     HCU1A2FM.
    HCU_1AC     ADM_LN2G.
    FLU_160     YESNOFM. 
    FLU_162     FS52F.   
    FLU_164     MONTHFM. 
    FLU_165     INJ_4F.  
    FLU_66A     YESNOFM. 
    FLU_66B     YESNOFM. 
    FLU_66C     YESNOFM. 
    FLU_66D     YESNOFM. 
    FLU_66E     YESNOFM. 
    FLU_66F     YESNOFM. 
    FLU_66G     YESNOFM. 
    FLU_66H     YESNOFM. 
    FLU_66I     YESNOFM. 
    FLU_66J     YESNOFM. 
    FLU_66K     YESNOFM. 
    FLU_66L     YESNOFM. 
    FLU_66M     YESNOFM. 
    FLU_66O     YESNOFM. 
    FLU_66N     YESNOFM. 
    FVC_1A      FVC_1A.  
    FVC_1B      TIMES2D. 
    FVC_1C      TIMES2D. 
    FVC_1D      TIMES3D. 
    FVC_1E      TIMES3D. 
    FVC_2A      FVC_1A.  
    FVC_2B      TIMES2D. 
    FVC_2C      TIMES2D. 
    FVC_2D      TIMES3D. 
    FVC_2E      TIMES3D. 
    FVC_3A      FVC_1A.  
    FVC_3B      TIMES2D. 
    FVC_3C      TIMES2D. 
    FVC_3D      TIMES3D. 
    FVC_3E      TIMES3D. 
    FVC_4A      FVC_1A.  
    FVC_4B      TIMES2D. 
    FVC_4C      TIMES2D. 
    FVC_4D      TIMES3D. 
    FVC_4E      TIMES3D. 
    FVC_5A      FVC_1A.  
    FVC_5B      TIMES2D. 
    FVC_5C      TIMES2D. 
    FVC_5D      TIMES3D. 
    FVC_5E      TIMES3D. 
    FVC_6A      FVC_1A.  
    FVC_6B      SERV2FM. 
    FVC_6C      SERV2FM. 
    FVC_6D      SERV3FM. 
    FVC_6E      SERV3FM. 
    FVCDJUI     FVC_DC.  
    FVCDFRU     FVC_DC.  
    FVCDSAL     FVC_DC.  
    FVCDPOT     FVC_DC.  
    FVCDCAR     FVC_DC.  
    FVCDVEG     FVC_PO.  
    FVCDTOT     FVC_DC.  
    FVCGTOT     FVC_RDA. 
    PAC_1A      YESNOFM. 
    PAC_1B      YESNOFM. 
    PAC_1C      YESNOFM. 
    PAC_1D      YESNOFM. 
    PAC_1E      YESNOFM. 
    PAC_1F      YESNOFM. 
    PAC_1G      YESNOFM. 
    PAC_1H      YESNOFM. 
    PAC_1I      YESNOFM. 
    PAC_1J      YESNOFM. 
    PAC_1K      YESNOFM. 
    PAC_1L      YESNOFM. 
    PAC_1M      YESNOFM. 
    PAC_1N      YESNOFM. 
    PAC_1O      YESNOFM. 
    PAC_1P      YESNOFM. 
    PAC_1Q      YESNOFM. 
    PAC_1R      YESNOFM. 
    PAC_1S      YESNOFM. 
    PAC_1T      YESNOFM. 
    PAC_1Z      YESNOFM. 
    PAC_1U      YESNOFM. 
    PAC_1V      YESNOFM. 
    PAC_1W      YESNOFM. 
    PAC_1X      YESNOFM. 
    PAC_2A      TIMES3D. 
    PAC_3A      PAC_TIME.
    PAC_2B      TIMES3D. 
    PAC_3B      PAC_TIME.
    PAC_2C      TIMES3D. 
    PAC_3C      PAC_TIME.
    PAC_2D      TIMES3D. 
    PAC_3D      PAC_TIME.
    PAC_2E      TIMES3D. 
    PAC_3E      PAC_TIME.
    PAC_2F      TIMES3D. 
    PAC_3F      PAC_TIME.
    PAC_2G      TIMES3D. 
    PAC_3G      PAC_TIME.
    PAC_2H      TIMES3D. 
    PAC_3H      PAC_TIME.
    PAC_2I      TIMES3D. 
    PAC_3I      PAC_TIME.
    PAC_2J      TIMES3D. 
    PAC_3J      PAC_TIME.
    PAC_2K      TIMES3D. 
    PAC_3K      PAC_TIME.
    PAC_2L      TIMES3D. 
    PAC_3L      PAC_TIME.
    PAC_2M      TIMES3D. 
    PAC_3M      PAC_TIME.
    PAC_2N      TIMES3D. 
    PAC_3N      PAC_TIME.
    PAC_2O      TIMES3D. 
    PAC_3O      PAC_TIME.
    PAC_2P      TIMES3D. 
    PAC_3P      PAC_TIME.
    PAC_2Q      TIMES3D. 
    PAC_3Q      PAC_TIME.
    PAC_2R      TIMES3D. 
    PAC_3R      PAC_TIME.
    PAC_2S      TIMES3D. 
    PAC_3S      PAC_TIME.
    PAC_2T      TIMES3D. 
    PAC_3T      PAC_TIME.
    PAC_2Z      TIMES3D. 
    PAC_3Z      PAC_TIME.
    PAC_2U      TIMES3D. 
    PAC_3U      PAC_TIME.
    PAC_2W      TIMES3D. 
    PAC_3W      PAC_TIME.
    PAC_2X      TIMES3D. 
    PAC_3X      PAC_TIME.
    PAC_7       PACF_7FM.
    PAC_7A      TIMES3D. 
    PAC_7B      PAC_TIME.
    PAC_8       PACF_7FM.
    PAC_8A      TIMES3D. 
    PAC_8B      PAC_TIME.
    PACDEE      PACDEE.  
    PACFLEI     YESNOFM. 
    PACDFM      PACDFM.  
    PACDFR      PACDFR.  
    PACFD       YESNOFM. 
    PACDPAI     PACDPAI. 
    PACDLTI     PACDPAI. 
    PACDTLE     PACDTLFM.
    PACFLTI     YESNOFM. 
    DOSAC       YESNOFM. 
    SAC_1       HOUR2DFM.
    SAC_2       HOUR2DFM.
    SAC_3       HOUR2DFM.
    SAC_4       HOUR2DFM.
    SACDTOT     SAC_NUM. 
    SACDTER     SAC_NUM. 
    SMK_01A     YESNOFM. 
    SMK_01B     YESNOFM. 
    SMK_01C     AGE3DFM. 
    SMK_202     SMC_2F.  
    SMK_203     AGE3DFM. 
    SMK_204     CIG_NUM. 
    SMK_05B     CIG_NUM. 
    SMK_05C     DAY2DFM. 
    SMK_05D     YESNOFM. 
    SMK_06A     SMKCFM.  
    SMK_06B     MONTHFM. 
    SMK_06C     YEAR3NUM.
    SMK_207     AGE3DFM. 
    SMK_208     CIG_NUM. 
    SMK_09A     SMKCFM.  
    SMK_09B     MONTHFM. 
    SMK_09C     YEAR3NUM.
    SMK_10      YESNOFM. 
    SMK_10A     SMKCFM.  
    SMK_10B     MONTHFM. 
    SMK_10C     YEAR3NUM.
    SMKDSTY     SMCDTYP. 
    SMKDSTP     YEAR3NUM.
    SMKDYCS     YEAR3NUM.
    ETS_10      YESNOFM. 
    ETS_11      PERS2D.  
    ETS_20      YESNOFM. 
    ETS_20B     YESNOFM. 
    ETS_35      YESNOFM. 
    ETS_36      YESNOFM. 
    ETS_37A     YESNOFM. 
    ETS_37B     YESNOFM. 
    ETS_37C     YESNOFM. 
    ETS_37D     YESNOFM. 
    ALC_1       YESNOFM. 
    ALC_2       ALC6_2F. 
    ALC_3       ALC_3F.  
    ALCDTTM     ALCDTTFM.
    DOMEX       YESNOFM. 
    MEX_01      YESNOFM. 
    MEX_01A     YEARFM.  
    MEX_02      YESNOFM. 
    MEX_03      YESNOFM. 
    MEX_04      MEXE4FM. 
    MEX_05      YESNOFM. 
    MEX_06      MEXE06FM.
    MEX_06A     YESNOFM. 
    MEX_06B     MEXE07FM.
    MEX_08A     MEX_08FM.
    MEX_08B     MEXE8FM. 
    MEX_09      YESNOFM. 
    MEX_09B     MEX09BFM.
    MEX_10      MEXE0FM. 
    MEXDEBF2    MEXBF2FM.
    MEXFEB6     YESNOFM. 
    DOCMH       YESNOFM. 
    CMH_01K     YESNOFM. 
    CMH_01L     TIMES3D. 
    CMH_1MA     YESNOFM. 
    CMH_1MB     YESNOFM. 
    CMH_1MC     YESNOFM. 
    CMH_1MD     YESNOFM. 
    CMH_1ME     YESNOFM. 
    CMH_1MF     YESNOFM. 
    LBS_01      LSC_1F.  
    LBS_02      YESNOFM. 
    LBS_03      YESNOFM. 
    LBS_11      YESNOFM. 
    LBS_31      LSC_31F. 
    LBSF32      YESNOFM. 
    LBSF33      YESNOFM. 
    LBSF34      YESNOFM. 
    LBSF35      YESNOFM. 
    LBSCSIC    $LBSSICFM.
    LBSCSOC    $LBSSOCFM.
    LBSF35S     YESNOFM. 
    LBSF36      YESNOFM. 
    LBS_42      HOUR3DFM.
    LBS_53      HOUR3DFM.
    LBSDHPW     LSCDHPW. 
    LBSDPFT     LBF_PFT. 
    LBSDWSS     LSCDCWS. 
    LBSDING    $LBSDINFM.
    LBSDOCG    $LBSDOCFM.
    SDCCCB10    SDCB10FM.
    SDCGCB10    SDCG10FM.
    SDC_2       YESNOFM. 
    SDC_3       SDYEARFM.
    SDC_4A      YESNOFM. 
    SDC_4B      YESNOFM. 
    SDC_4C      YESNOFM. 
    SDC_4D      YESNOFM. 
    SDC_4E      YESNOFM. 
    SDC_4F      YESNOFM. 
    SDC_4G      YESNOFM. 
    SDC_4H      YESNOFM. 
    SDC_4I      YESNOFM. 
    SDC_4J      YESNOFM. 
    SDC_4K      YESNOFM. 
    SDC_4L      YESNOFM. 
    SDC_4M      YESNOFM. 
    SDC_4N      YESNOFM. 
    SDC_4T      YESNOFM. 
    SDC_4U      YESNOFM. 
    SDC_4V      YESNOFM. 
    SDC_4P      YESNOFM. 
    SDC_4Q      YESNOFM. 
    SDC_4R      YESNOFM. 
    SDC_4S      YESNOFM. 
    SDC_41      YESNOFM. 
    SDC_42A     YESNOFM. 
    SDC_42B     YESNOFM. 
    SDC_42C     YESNOFM. 
    SDC_43A     YESNOFM. 
    SDC_43C     YESNOFM. 
    SDC_43B     YESNOFM. 
    SDC_43D     YESNOFM. 
    SDC_43E     YESNOFM. 
    SDC_43F     YESNOFM. 
    SDC_43H     YESNOFM. 
    SDC_43G     YESNOFM. 
    SDC_43I     YESNOFM. 
    SDC_43K     YESNOFM. 
    SDC_43J     YESNOFM. 
    SDC_43M     YESNOFM. 
    SDC_5A_1    SDCQ5AFM.
    SDCC5B1     SDCC61FM.
    SDCC5B2     SDCC61FM.
    SDCC5B3     SDCC61FM.
    SDCC61      SDCC61FM.
    SDCC62      SDCC61FM.
    SDCC63      SDCC61FM.
    SDCDFOLS    SDCFOLFM.
    DHH_OWN     DHH011FM.
    SDC_7AA     SDC7AFM. 
    SDCDLHM     SDCDLNFM.
    SDCDAIM     AGE3DFM. 
    SDCFIMM     YESNOFM. 
    SDCDRES     AGE3DFM. 
    SDCDFL1     SDCDFLFM.
    SDCDABT     SDC_ABO. 
    SDCDCGT     SDC_CG.  
    PMKPROXY    PMKPROFM.
    DOFSC       YESNOFM. 
    FSC_010     FSCD10FM.
    FSC_020     FSCDFM.  
    FSC_030     FSCDFM.  
    FSC_040     FSCDFM.  
    FSC_050     FSCDFM.  
    FSC_060     FSCDFM.  
    FSC_070     FSCDFM.  
    FSC_080     YESNOFM. 
    FSC_081     FSC81FM. 
    FSC_090     YESNOFM. 
    FSC_100     YESNOFM. 
    FSC_110     YESNOFM. 
    FSC_120     YESNOFM. 
    FSC_121     FSC81FM. 
    FSC_130     YESNOFM. 
    FSC_140     YESNOFM. 
    FSC_141     FSC81FM. 
    FSC_150     YESNOFM. 
    FSC_160     YESNOFM. 
    FSCDHFS2    FSCDHFFM.
    FSCDAFS2    FSCDHFFM.
    FSCDCFS2    FSCDHFFM.
    DONEU       YESNOFM. 
    NEUDNCR     YESNOFM. 
    NEUDNCH     YESNOFM. 
    NEUDMHR     YESNOFM. 
    NEUDMHH     PERS2D.  
    NEUDEPR     YESNOFM. 
    NEUDEPH     PERS2D.  
    NEUDCPR     YESNOFM. 
    NEUDCPH     PERS2D.  
    NEUDSBR     YESNOFM. 
    NEUDSBH     PERS2D.  
    NEUDHCR     YESNOFM. 
    NEUDHCH     PERS2D.  
    NEUDMDR     YESNOFM. 
    NEUDMDH     PERS2D.  
    NEUDDYR     YESNOFM. 
    NEUDDYH     PERS2D.  
    NEUDTSR     YESNOFM. 
    NEUDTSH     PERS2D.  
    NEUDPDR     YESNOFM. 
    NEUDPDH     PERS2D.  
    NEUDALR     YESNOFM. 
    NEUDALH     PERS2D.  
    NEUDHDR     YESNOFM. 
    NEUDHDH     PERS2D.  
    NEUDSTR     YESNOFM. 
    NEUDSTH     PERS2D.  
    NEUDBIR     YESNOFM. 
    NEUDBIH     PERS2D.  
    NEUDBTR     YESNOFM. 
    NEUDBTH     PERS2D.  
    NEUDSIR     YESNOFM. 
    NEUDSIH     PERS2D.  
    NEUDSCR     YESNOFM. 
    NEUDSCH     PERS2D.  
    NEUDADR     YESNOFM. 
    NEUDADH     PERS2D.  
    NEUDMSH     PERS2D.  
    NEUDMSR     YESNOFM. 
    EDU_1       EDUGRADE.
    EDU_2       YESNOFM. 
    EDU_3       YESNOFM. 
    EDU_4A      EDUQ4AFM.
    SDC_8       YESNOFM. 
    SDC_9       EDUQ06FM.
    EDUDH04     DVED3FM. 
    EDUDH10     EDU_10DR.
    EDUDR04     EDUDR4FM.
    EDUDR10     EDU_10DR.
    INC_1A      YESNOFM. 
    INC_1B      YESNOFM. 
    INC_1C      YESNOFM. 
    INC_1D      YESNOFM. 
    INC_1E      YESNOFM. 
    INC_1F      YESNOFM. 
    INC_1G      YESNOFM. 
    INC_1O      YESNOFM. 
    INC_1H      YESNOFM. 
    INC_1J      YESNOFM. 
    INC_1I      YESNOFM. 
    INC_1K      YESNOFM. 
    INC_1L      YESNOFM. 
    INC_1M      YESNOFM. 
    INC_1N      YESNOFM. 
    INC_2       INC_Q2FM.
    INC_3       DOLL8_FM.
    INC_6A      YESNOFM. 
    INC_6B      YESNOFM. 
    INC_6C      YESNOFM. 
    INC_6D      YESNOFM. 
    INC_6E      YESNOFM. 
    INC_6F      YESNOFM. 
    INC_6G      YESNOFM. 
    INC_6H      YESNOFM. 
    INC_6I      YESNOFM. 
    INC_6J      YESNOFM. 
    INC_6K      YESNOFM. 
    INC_6L      YESNOFM. 
    INC_6M      YESNOFM. 
    INC_6N      YESNOFM. 
    INC_6O      YESNOFM. 
    INC_7       INC_Q2FM.
    INC_8A      DOLL8_FM.
    INC_8B      INCQ8BFM.
    INC_8C      INC_8CFM.
    INC_8D      INCQ8DFM.
    INCFIMP     INCIMPFM.
    INCDHH      INC_DHFM.
    INCDPER     INCDPEFM.
    INCDADR     INCRATFM.
    INCDRCA     INCDECFM.
    INCDRPR     INCDECFM.
    INCDRRS     INCDECFM.
    ACCZ_10     YESNOFM. 
    ACCZ_11     YESNOFM. 
    ACCZ_12A    YESNOFM. 
    ACCZ_12B    YESNOFM. 
    ACCZ_12C    YESNOFM. 
    ACCZ_12D    YESNOFM. 
    ACCZ_12E    YESNOFM. 
    ACCZ_12F    YESNOFM. 
    ACCZ_12G    YESNOFM. 
    ACCZ_12H    YESNOFM. 
    ACCZ_12I    YESNOFM. 
    ACCZ_12J    YESNOFM. 
    ACCZ_12K    YESNOFM. 
    ACCZ_12L    YESNOFM. 
    ACCZ_12M    YESNOFM. 
    ACCZ_12N    YESNOFM. 
    ACCZ_20     YESNOFM. 
    ACCZ_21     YESNOFM. 
    ACCZ_22A    YESNOFM. 
    ACCZ_22B    YESNOFM. 
    ACCZ_22C    YESNOFM. 
    ACCZ_22D    YESNOFM. 
    ACCZ_22E    YESNOFM. 
    ACCZ_22F    YESNOFM. 
    ACCZ_22G    YESNOFM. 
    ACCZ_22H    YESNOFM. 
    ACCZ_22I    YESNOFM. 
    ACCZ_22J    YESNOFM. 
    ACCZ_22K    YESNOFM. 
    ACCZ_22L    YESNOFM. 
    ACCZ_22M    YESNOFM. 
    ACCZ_22N    YESNOFM. 
    ACCZ_22O    YESNOFM. 
    ACCZ_30     YESNOFM. 
    ACCZ_31     YESNOFM. 
    ACCZ_32A    YESNOFM. 
    ACCZ_32B    YESNOFM. 
    ACCZ_32C    YESNOFM. 
    ACCZ_32D    YESNOFM. 
    ACCZ_32E    YESNOFM. 
    ACCZ_32F    YESNOFM. 
    ACCZ_32G    YESNOFM. 
    ACCZ_32H    YESNOFM. 
    ACCZ_32I    YESNOFM. 
    ACCZ_32J    YESNOFM. 
    ACCZ_32K    YESNOFM. 
    ACCZ_32L    YESNOFM. 
    ACCZ_32M    YESNOFM. 
    ACCZ_32N    YESNOFM. 
    ACCZ_40     YESNOFM. 
    ACCZ_40A    YESNOFM. 
    ACCZ_40B    YESNOFM. 
    ACCZ_40C    YESNOFM. 
    ACCZ_40D    YESNOFM. 
    ACCZ_40E    YESNOFM. 
    ACCZ_40F    YESNOFM. 
    ACCZ_40G    YESNOFM. 
    ACCZ_41     YESNOFM. 
    ACCZ_42     YESNO.   
    ACCZ_43A    YESNOFM. 
    ACCZ_43B    YESNOFM. 
    ACCZ_43C    YESNOFM. 
    ACCZ_43D    YESNOFM. 
    ACCZ_43E    YESNOFM. 
    ACCZ_43F    YESNOFM. 
    ACCZ_43G    YESNOFM. 
    ACCZ_43H    YESNOFM. 
    ACCZ_43I    YESNOFM. 
    ACCZ_44     YESNO.   
    ACCZ_45A    YESNOFM. 
    ACCZ_45B    YESNOFM. 
    ACCZ_45C    YESNOFM. 
    ACCZ_45D    YESNOFM. 
    ACCZ_45E    YESNOFM. 
    ACCZ_45F    YESNOFM. 
    ACCZ_45G    YESNOFM. 
    ACCZ_45H    YESNOFM. 
    ACCZ_45I    YESNOFM. 
    ACCZ_46     YESNO.   
    ACCZ_47A    YESNOFM. 
    ACCZ_47B    YESNOFM. 
    ACCZ_47C    YESNOFM. 
    ACCZ_47D    YESNOFM. 
    ACCZ_47E    YESNOFM. 
    ACCZ_47F    YESNOFM. 
    ACCZ_47G    YESNOFM. 
    ACCZ_47H    YESNOFM. 
    ACCZ_47I    YESNOFM. 
    ACCZ_50A    YESNOFM. 
    ACCZ_50     YESNOFM. 
    ACCZ_51     YESNOFM. 
    ACCZ_52     YESNO.   
    ACCZ_53A    YESNOFM. 
    ACCZ_53B    YESNOFM. 
    ACCZ_53C    YESNOFM. 
    ACCZ_53D    YESNOFM. 
    ACCZ_53E    YESNOFM. 
    ACCZ_53F    YESNOFM. 
    ACCZ_53G    YESNOFM. 
    ACCZ_53H    YESNOFM. 
    ACCZ_53I    YESNOFM. 
    ACCZ_53J    YESNOFM. 
    ACCZ_53K    YESNOFM. 
    ACCZ_53L    YESNOFM. 
    ACCZ_53M    YESNOFM. 
    ACCZ_54     YESNO.   
    ACCZ_55A    YESNOFM. 
    ACCZ_55B    YESNOFM. 
    ACCZ_55C    YESNOFM. 
    ACCZ_55D    YESNOFM. 
    ACCZ_55E    YESNOFM. 
    ACCZ_55F    YESNOFM. 
    ACCZ_55G    YESNOFM. 
    ACCZ_55H    YESNOFM. 
    ACCZ_55I    YESNOFM. 
    ACCZ_55J    YESNOFM. 
    ACCZ_55K    YESNOFM. 
    ACCZ_55L    YESNOFM. 
    ACCZ_55M    YESNOFM. 
    ACCZ_60     YESNOFM. 
    ACCZ_61     YESNOFM. 
    ACCZ_62     YESNO.   
    ACCZ_63A    YESNOFM. 
    ACCZ_63B    YESNOFM. 
    ACCZ_63C    YESNOFM. 
    ACCZ_63D    YESNOFM. 
    ACCZ_63E    YESNOFM. 
    ACCZ_63F    YESNOFM. 
    ACCZ_63G    YESNOFM. 
    ACCZ_63H    YESNOFM. 
    ACCZ_63I    YESNOFM. 
    ACCZ_63J    YESNOFM. 
    ACCZ_63K    YESNOFM. 
    ACCZ_63L    YESNOFM. 
    ACCZ_63M    YESNOFM. 
    ACCZ_64     YESNO.   
    ACCZ_65A    YESNOFM. 
    ACCZ_65B    YESNOFM. 
    ACCZ_65C    YESNOFM. 
    ACCZ_65D    YESNOFM. 
    ACCZ_65E    YESNOFM. 
    ACCZ_65F    YESNOFM. 
    ACCZ_65G    YESNOFM. 
    ACCZ_65H    YESNOFM. 
    ACCZ_65I    YESNOFM. 
    ACCZ_65J    YESNOFM. 
    ACCZ_65K    YESNOFM. 
    ACCZ_65L    YESNOFM. 
    ACCZ_65M    YESNOFM. 
    ACCZ_66     YESNO.   
    ACCZ_67A    YESNOFM. 
    ACCZ_67B    YESNOFM. 
    ACCZ_67C    YESNOFM. 
    ACCZ_67D    YESNOFM. 
    ACCZ_67E    YESNOFM. 
    ACCZ_67F    YESNOFM. 
    ACCZ_67G    YESNOFM. 
    ACCZ_67H    YESNOFM. 
    ACCZ_67I    YESNOFM. 
    ACCZ_67J    YESNOFM. 
    ACCZ_67K    YESNOFM. 
    ACCZ_67L    YESNOFM. 
    ACCZ_67M    YESNOFM. 
    WTMZ_01     YESNOFM. 
    WTMZ_02     WTMC02FM.
    WTMZ_03     WTMC03FM.
    WTMZ_04     YESNOFM. 
    WTMZ_05     YESNOFM. 
    WTMZ_06A    YESNOFM. 
    WTMZ_06B    YESNOFM. 
    WTMZ_06C    YESNOFM. 
    WTMZ_06D    YESNOFM. 
    WTMZ_06E    YESNOFM. 
    WTMZ_06F    YESNOFM. 
    WTMZ_06G    YESNOFM. 
    WTMZ_06H    YESNOFM. 
    WTMZ_06I    YESNOFM. 
    WTMZ_06J    YESNOFM. 
    WTMZ_06K    YESNOFM. 
    WTMZ_06L    YESNOFM. 
    WTMZ_06M    YESNOFM. 
    WTMZ_07A    WTMC7AFM.
    WTMZ_07B    WTMC7BFM.
    WTMZ_08A    WTMC7AFM.
    WTMZ_08B    WTMC7BFM.
    WTMZ_10     WTMC10FM.
    WTMZ_11A    WTMC7AFM.
    WTMZ_11B    WTMC7BFM.
    WTMZ_12     YESNOFM. 
    WTMZ_13A    YESNOFM. 
    WTMZ_13B    YESNOFM. 
    WTMZ_13C    YESNOFM. 
    WTMZ_14     YESNOFM. 
    WTMZ_15A    YESNOFM. 
    WTMZ_15B    YESNOFM. 
    WTMZ_15C    YESNOFM. 
    WTMZ_15D    YESNOFM. 
    WTMZ_15E    YESNOFM. 
    WTMZ_15F    YESNOFM. 
    WTMZ_15G    YESNOFM. 
    WTMZ_15H    YESNOFM. 
    WTMZ_15I    YESNOFM. 
    WTMZ_15J    YESNOFM. 
    WTMZ_15K    YESNOFM. 
    WTMZ_15L    YESNOFM. 
    WTMZ_16     WTMC16FM.
    WTMZ_17     YESNOFM. 
    WTMZ_18     YESNOFM. 
    WTMZ_19     YESNOFM. 
    WTMZ_20A    YESNOFM. 
    WTMZ_20B    YESNOFM. 
    WTMZ_20C    YESNOFM. 
    WTMZ_20D    YESNOFM. 
    WTMZ_20E    YESNOFM. 
    WTMZ_20F    YESNOFM. 
    WTMZ_20G    YESNOFM. 
    WTMZ_20H    YESNOFM. 
    WTMZ_20I    YESNOFM. 
    WTMZ_20J    YESNOFM. 
    WTMZ_20K    YESNOFM. 
    WTMZ_20L    YESNOFM. 
    WTMZ_20M    YESNOFM. 
    WTMZ_20N    YESNOFM. 
    WTMZ_21A    WTMC7AFM.
    WTMZ_21B    WTMC7BFM.
    WTMZ_22     YESNOFM. 
    WTMZ_23A    WTMC7AFM.
    WTMZ_23B    WTMC7BFM.
    WTMZ_24     WTMC10FM.
    WTMZ_25A    WTMC7AFM.
    WTMZ_25B    WTMC7BFM.
    WTMZ_26     YESNOFM. 
    WTMZ_27A    YESNOFM. 
    WTMZ_27B    YESNOFM. 
    WTMZ_27C    YESNOFM. 
    WTMZ_27D    YESNOFM. 
    WTMZ_28     YESNOFM. 
    WTMZ_29A    YESNOFM. 
    WTMZ_29B    YESNOFM. 
    WTMZ_29C    YESNOFM. 
    WTMZ_29D    YESNOFM. 
    WTMZ_29E    YESNOFM. 
    WTMZ_29F    YESNOFM. 
    WTMZ_29G    YESNOFM. 
    WTMZ_29H    YESNOFM. 
    WTMZ_29I    YESNOFM. 
    WTMZ_29J    YESNOFM. 
    WTMZ_29K    YESNOFM. 
    WTMZ_29L    YESNOFM. 
    WTMZ_30     WTMCFM.  
    WTMZ_31     WTM31FM. 
    WTMZ_32     YESNOFM. 
    WTMZ_33     WTM33FM. 
    WTMZ_34     WTMC34FM.
    WTMZ_35     YESNOFM. 
    WTMZ_36     YESNOFM. 
    WTMZ_37A    YESNOFM. 
    WTMZ_37B    YESNOFM. 
    WTMZ_37C    YESNOFM. 
    WTMZ_37D    YESNOFM. 
    WTMZ_37E    YESNOFM. 
    WTMZ_37F    YESNOFM. 
    WTMZ_37G    YESNOFM. 
    WTMZ_37H    YESNOFM. 
    WTMZ_37I    YESNOFM. 
    WTMZ_37J    YESNOFM. 
    WTMZ_37K    YESNOFM. 
    WTMZ_37L    YESNOFM. 
    WTMZ_37M    YESNOFM. 
    WTMZ_38A    WTMC7AFM.
    WTMZ_38B    WTMC7BFM.
    WTMZ_39A    WTMC7AFM.
    WTMZ_39B    WTMC7BFM.
    WTMZ_40     WTMC10FM.
    WTMZ_41A    WTMC7AFM.
    WTMZ_41B    WTMC7BFM.
    WTMZ_42     YESNOFM. 
    WTMZ_43     WTMC43FM.
    WTMZ_44     YESNOFM. 
    WTMZ_45A    YESNOFM. 
    WTMZ_45B    YESNOFM. 
    WTMZ_45C    YESNOFM. 
    WTMZ_45D    YESNOFM. 
    WTMZ_45E    YESNOFM. 
    WTMZ_45F    YESNOFM. 
    WTMZ_45G    YESNOFM. 
    WTMZ_45H    YESNOFM. 
    WTMZ_45I    YESNOFM. 
    WTMZ_45J    YESNOFM. 
    WTMZ_45K    YESNOFM. 
    WTMZ_45L    YESNOFM. 
    WTMZDSO     DAY4DFM. 
    WTMZDSN     DAY4DFM. 
    WTMZDSA     DAY4DFM. 
    WTMZDCO     DAY4DFM. 
    WTMZDCN     DAY4DFM. 
    WTMZDCA     DAY4DFM. 
    WTMZDTO     DAY4DFM. 
    WTMZDTN     DAY4DFM. 
    WTMZDTA     DAY4DFM. 
                       ;
