INFILE &datafid PAD LRECL = 1386;
INPUT
    @    1   VERDATE                              $     8.      
    @    9   REFPER                               $    13.      
    @   22   SAMPLEID                             $    20.      
    @   42   PERSONID                                   2.      
    @   44   GEO_PRV                                    2.      
    @   46   GEODPC                               $     6.      
    @   52   GEODHR4                                    4.      
    @   56   GEODSHR                                    6.      
    @   62   GEODDHA                                    4.      
    @   66   GEODLHA                                    3.      
    @   69   GEODRHA                                    4.      
    @   73   GEODBCHA                                   4.      
    @   77   GEODLHN                                    4.      
    @   81   GEODDA06                                   8.      
    @   89   GEODFED                                    5.      
    @   94   GEODCSD                                    7.      
    @  101   GEODCD                                     4.      
    @  105   GEODSAT                                    1.      
    @  106   GEODCMA6                                   3.      
    @  109   GEODPG11                                   2.      
    @  111   GEODUR                                     1.      
    @  112   GEODUR2                                    1.      
    @  113   GEODSUBZ                                   6.      
    @  119   SAM_CP                               $     6.      
    @  125   SAM_TYP                                    1.      
    @  126   SAMDSHR                                    1.      
    @  127   SAMDLNK                                    1.      
    @  128   ADM_STA                                    2.      
    @  130   ADM_PRX                                    1.      
    @  131   ADM_YOI                                    4.      
    @  135   ADM_MOI                                    2.      
    @  137   ADM_DOI                                    2.      
    @  139   ADM_N09                                    1.      
    @  140   ADM_N10                                    1.      
    @  141   ADM_N11                                    1.      
    @  142   ADM_N12                                    2.      
    @  144   ADM_LHH                                    1.      
    @  145   DHH_AGE                                    3.      
    @  148   DHH_YOB                                    4.      
    @  152   DHH_MOB                                    2.      
    @  154   DHH_DOB                                    2.      
    @  156   DHH_SEX                                    1.      
    @  157   DHH_MS                                     2.      
    @  159   DHHDSAGE                                   3.      
    @  162   DHHDYKD                                    2.      
    @  164   DHHDOKD                                    2.      
    @  166   DHHDLE5                                    2.      
    @  168   DHHD611                                    2.      
    @  170   DHHDL12                                    2.      
    @  172   DHHDL18                                    2.      
    @  174   DHHDLVG                                    2.      
    @  176   DHHDECF                                    2.      
    @  178   DHHDHSZ                                    2.      
    @  180   GEN_01                                     1.      
    @  181   GEN_02                                     1.      
    @  182   GEN_02A2                                   2.      
    @  184   GEN_02B                                    1.      
    @  185   GEN_07                                     1.      
    @  186   GEN_08                                     1.      
    @  187   GEN_09                                     1.      
    @  188   GEN_10                                     1.      
    @  189   GENDHDI                                    1.      
    @  190   GENDMHI                                    1.      
    @  191   GENGSWL                                    1.      
    @  192   DOPMH                                      1.      
    @  193   PMH_01                                     2.      
    @  195   PMH_02                                     2.      
    @  197   PMH_03                                     2.      
    @  199   PMH_04                                     2.      
    @  201   PMH_05                                     2.      
    @  203   PMH_06                                     2.      
    @  205   PMH_07                                     2.      
    @  207   PMH_08                                     2.      
    @  209   PMH_09                                     2.      
    @  211   PMH_10                                     2.      
    @  213   PMH_11                                     2.      
    @  215   PMH_12                                     2.      
    @  217   PMH_13                                     2.      
    @  219   PMH_14                                     2.      
    @  221   PMHDCLA                                    2.      
    @  223   PMHDSCR                                    2.      
    @  225   MAM_037                                    1.      
    @  226   HWT_2                                      2.      
    @  228   HWT_2A                                     2.      
    @  230   HWT_2B                                     2.      
    @  232   HWT_2C                                     2.      
    @  234   HWT_2D                                     2.      
    @  236   HWT_2E                                     2.      
    @  238   HWT_2F                                     2.      
    @  240   HWT_3                                      3.      
    @  243   HWT_N4                                     1.      
    @  244   HWT_4                                      1.      
    @  245   HWTDHTM                                    5.3     
    @  250   HWTDWTK                                    6.2     
    @  256   HWTDBMI                                    6.2     
    @  262   HWTDISW                                    2.      
    @  264   HWTDCOL                                    1.      
    @  265   CCC_031                                    1.      
    @  266   CCC_035                                    1.      
    @  267   CCC_036                                    1.      
    @  268   CCC_051                                    1.      
    @  269   CCC_061                                    1.      
    @  270   CCC_071                                    1.      
    @  271   CCC_072                                    1.      
    @  272   CCC_073                                    1.      
    @  273   CCC_073A                                   1.      
    @  274   CCC_073B                                   1.      
    @  275   CCC_081                                    1.      
    @  276   CCC_091                                    1.      
    @  277   CCC_101                                    1.      
    @  278   CCC_102                                    3.      
    @  281   CCC_10A                                    1.      
    @  282   CCC_10B                                    1.      
    @  283   CCC_10C                                    2.      
    @  285   CCC_105                                    1.      
    @  286   CCC_106                                    1.      
    @  287   CCC_121                                    1.      
    @  288   CCC_131                                    1.      
    @  289   CCC_31A                                    1.      
    @  290   CCC_141                                    1.      
    @  291   CCC_151                                    1.      
    @  292   CCC_161                                    1.      
    @  293   CCC_171                                    1.      
    @  294   CCC_17A                                    1.      
    @  295   CCC_181                                    1.      
    @  296   CCC_280                                    1.      
    @  297   CCC_290                                    1.      
    @  298   CCCDDIA                                    1.      
    @  299   HUP_01                                     1.      
    @  300   HUP_02                                     1.      
    @  301   HUP_03                                     1.      
    @  302   HUPDPAD                                    1.      
    @  303   HCU_1AA                                    1.      
    @  304   HCU_1BA                                    1.      
    @  305   HCU_1BB                                    1.      
    @  306   HCU_1BC                                    1.      
    @  307   HCU_1BD                                    1.      
    @  308   HCU_1BE                                    1.      
    @  309   HCU_1A1                                    1.      
    @  310   HCU_1A2                                    2.      
    @  312   HCU_1AC                                    2.      
    @  314   FLU_160                                    1.      
    @  315   FLU_162                                    1.      
    @  316   FLU_164                                    2.      
    @  318   FLU_165                                    1.      
    @  319   FLU_66A                                    1.      
    @  320   FLU_66B                                    1.      
    @  321   FLU_66C                                    1.      
    @  322   FLU_66D                                    1.      
    @  323   FLU_66E                                    1.      
    @  324   FLU_66F                                    1.      
    @  325   FLU_66G                                    1.      
    @  326   FLU_66H                                    1.      
    @  327   FLU_66I                                    1.      
    @  328   FLU_66J                                    1.      
    @  329   FLU_66K                                    1.      
    @  330   FLU_66L                                    1.      
    @  331   FLU_66M                                    1.      
    @  332   FLU_66O                                    1.      
    @  333   FLU_66N                                    1.      
    @  334   FVC_1A                                     1.      
    @  335   FVC_1B                                     2.      
    @  337   FVC_1C                                     2.      
    @  339   FVC_1D                                     3.      
    @  342   FVC_1E                                     3.      
    @  345   FVC_2A                                     1.      
    @  346   FVC_2B                                     2.      
    @  348   FVC_2C                                     2.      
    @  350   FVC_2D                                     3.      
    @  353   FVC_2E                                     3.      
    @  356   FVC_3A                                     1.      
    @  357   FVC_3B                                     2.      
    @  359   FVC_3C                                     2.      
    @  361   FVC_3D                                     3.      
    @  364   FVC_3E                                     3.      
    @  367   FVC_4A                                     1.      
    @  368   FVC_4B                                     2.      
    @  370   FVC_4C                                     2.      
    @  372   FVC_4D                                     3.      
    @  375   FVC_4E                                     3.      
    @  378   FVC_5A                                     1.      
    @  379   FVC_5B                                     2.      
    @  381   FVC_5C                                     2.      
    @  383   FVC_5D                                     3.      
    @  386   FVC_5E                                     3.      
    @  389   FVC_6A                                     1.      
    @  390   FVC_6B                                     2.      
    @  392   FVC_6C                                     2.      
    @  394   FVC_6D                                     3.      
    @  397   FVC_6E                                     3.      
    @  400   FVCDJUI                                    5.1     
    @  405   FVCDFRU                                    5.1     
    @  410   FVCDSAL                                    5.1     
    @  415   FVCDPOT                                    5.1     
    @  420   FVCDCAR                                    5.1     
    @  425   FVCDVEG                                    5.1     
    @  430   FVCDTOT                                    5.1     
    @  435   FVCGTOT                                    1.      
    @  436   PAC_1A                                     1.      
    @  437   PAC_1B                                     1.      
    @  438   PAC_1C                                     1.      
    @  439   PAC_1D                                     1.      
    @  440   PAC_1E                                     1.      
    @  441   PAC_1F                                     1.      
    @  442   PAC_1G                                     1.      
    @  443   PAC_1H                                     1.      
    @  444   PAC_1I                                     1.      
    @  445   PAC_1J                                     1.      
    @  446   PAC_1K                                     1.      
    @  447   PAC_1L                                     1.      
    @  448   PAC_1M                                     1.      
    @  449   PAC_1N                                     1.      
    @  450   PAC_1O                                     1.      
    @  451   PAC_1P                                     1.      
    @  452   PAC_1Q                                     1.      
    @  453   PAC_1R                                     1.      
    @  454   PAC_1S                                     1.      
    @  455   PAC_1T                                     1.      
    @  456   PAC_1Z                                     1.      
    @  457   PAC_1U                                     1.      
    @  458   PAC_1V                                     1.      
    @  459   PAC_1W                                     1.      
    @  460   PAC_1X                                     1.      
    @  461   PAC_2A                                     3.      
    @  464   PAC_3A                                     1.      
    @  465   PAC_2B                                     3.      
    @  468   PAC_3B                                     1.      
    @  469   PAC_2C                                     3.      
    @  472   PAC_3C                                     1.      
    @  473   PAC_2D                                     3.      
    @  476   PAC_3D                                     1.      
    @  477   PAC_2E                                     3.      
    @  480   PAC_3E                                     1.      
    @  481   PAC_2F                                     3.      
    @  484   PAC_3F                                     1.      
    @  485   PAC_2G                                     3.      
    @  488   PAC_3G                                     1.      
    @  489   PAC_2H                                     3.      
    @  492   PAC_3H                                     1.      
    @  493   PAC_2I                                     3.      
    @  496   PAC_3I                                     1.      
    @  497   PAC_2J                                     3.      
    @  500   PAC_3J                                     1.      
    @  501   PAC_2K                                     3.      
    @  504   PAC_3K                                     1.      
    @  505   PAC_2L                                     3.      
    @  508   PAC_3L                                     1.      
    @  509   PAC_2M                                     3.      
    @  512   PAC_3M                                     1.      
    @  513   PAC_2N                                     3.      
    @  516   PAC_3N                                     1.      
    @  517   PAC_2O                                     3.      
    @  520   PAC_3O                                     1.      
    @  521   PAC_2P                                     3.      
    @  524   PAC_3P                                     1.      
    @  525   PAC_2Q                                     3.      
    @  528   PAC_3Q                                     1.      
    @  529   PAC_2R                                     3.      
    @  532   PAC_3R                                     1.      
    @  533   PAC_2S                                     3.      
    @  536   PAC_3S                                     1.      
    @  537   PAC_2T                                     3.      
    @  540   PAC_3T                                     1.      
    @  541   PAC_2Z                                     3.      
    @  544   PAC_3Z                                     1.      
    @  545   PAC_2U                                     3.      
    @  548   PAC_3U                                     1.      
    @  549   PAC_2W                                     3.      
    @  552   PAC_3W                                     1.      
    @  553   PAC_2X                                     3.      
    @  556   PAC_3X                                     1.      
    @  557   PAC_7                                      1.      
    @  558   PAC_7A                                     3.      
    @  561   PAC_7B                                     1.      
    @  562   PAC_8                                      1.      
    @  563   PAC_8A                                     3.      
    @  566   PAC_8B                                     1.      
    @  567   PACDEE                                     4.1     
    @  571   PACFLEI                                    1.      
    @  572   PACDFM                                     3.      
    @  575   PACDFR                                     1.      
    @  576   PACFD                                      1.      
    @  577   PACDPAI                                    1.      
    @  578   PACDLTI                                    1.      
    @  579   PACDTLE                                    4.1     
    @  583   PACFLTI                                    1.      
    @  584   DOSAC                                      1.      
    @  585   SAC_1                                      2.      
    @  587   SAC_2                                      2.      
    @  589   SAC_3                                      2.      
    @  591   SAC_4                                      2.      
    @  593   SACDTOT                                    2.      
    @  595   SACDTER                                    2.      
    @  597   SMK_01A                                    1.      
    @  598   SMK_01B                                    1.      
    @  599   SMK_01C                                    3.      
    @  602   SMK_202                                    1.      
    @  603   SMK_203                                    3.      
    @  606   SMK_204                                    3.      
    @  609   SMK_05B                                    3.      
    @  612   SMK_05C                                    2.      
    @  614   SMK_05D                                    1.      
    @  615   SMK_06A                                    1.      
    @  616   SMK_06B                                    2.      
    @  618   SMK_06C                                    3.      
    @  621   SMK_207                                    3.      
    @  624   SMK_208                                    3.      
    @  627   SMK_09A                                    1.      
    @  628   SMK_09B                                    2.      
    @  630   SMK_09C                                    3.      
    @  633   SMK_10                                     1.      
    @  634   SMK_10A                                    1.      
    @  635   SMK_10B                                    2.      
    @  637   SMK_10C                                    3.      
    @  640   SMKDSTY                                    2.      
    @  642   SMKDSTP                                    3.      
    @  645   SMKDYCS                                    3.      
    @  648   ETS_10                                     1.      
    @  649   ETS_11                                     2.      
    @  651   ETS_20                                     1.      
    @  652   ETS_20B                                    1.      
    @  653   ETS_35                                     1.      
    @  654   ETS_36                                     1.      
    @  655   ETS_37A                                    1.      
    @  656   ETS_37B                                    1.      
    @  657   ETS_37C                                    1.      
    @  658   ETS_37D                                    1.      
    @  659   ALC_1                                      1.      
    @  660   ALC_2                                      2.      
    @  662   ALC_3                                      2.      
    @  664   ALCDTTM                                    1.      
    @  665   DOMEX                                      1.      
    @  666   MEX_01                                     1.      
    @  667   MEX_01A                                    4.      
    @  671   MEX_02                                     1.      
    @  672   MEX_03                                     1.      
    @  673   MEX_04                                     2.      
    @  675   MEX_05                                     1.      
    @  676   MEX_06                                     2.      
    @  678   MEX_06A                                    1.      
    @  679   MEX_06B                                    2.      
    @  681   MEX_08A                                    2.      
    @  683   MEX_08B                                    2.      
    @  685   MEX_09                                     1.      
    @  686   MEX_09B                                    1.      
    @  687   MEX_10                                     2.      
    @  689   MEXDEBF2                                   2.      
    @  691   MEXFEB6                                    1.      
    @  692   DOCMH                                      1.      
    @  693   CMH_01K                                    1.      
    @  694   CMH_01L                                    3.      
    @  697   CMH_1MA                                    1.      
    @  698   CMH_1MB                                    1.      
    @  699   CMH_1MC                                    1.      
    @  700   CMH_1MD                                    1.      
    @  701   CMH_1ME                                    1.      
    @  702   CMH_1MF                                    1.      
    @  703   LBS_01                                     1.      
    @  704   LBS_02                                     1.      
    @  705   LBS_03                                     1.      
    @  706   LBS_11                                     1.      
    @  707   LBS_31                                     1.      
    @  708   LBSF32                                     1.      
    @  709   LBSF33                                     1.      
    @  710   LBSF34                                     1.      
    @  711   LBSF35                                     1.      
    @  712   LBSCSIC                              $     5.      
    @  717   LBSCSOC                              $     4.      
    @  721   LBSF35S                                    1.      
    @  722   LBSF36                                     1.      
    @  723   LBS_42                                     3.      
    @  726   LBS_53                                     3.      
    @  729   LBSDHPW                                    3.      
    @  732   LBSDPFT                                    1.      
    @  733   LBSDWSS                                    1.      
    @  734   LBSDING                              $     2.      
    @  736   LBSDOCG                              $     2.      
    @  738   SDCCCB10                                   5.      
    @  743   SDCGCB10                                   2.      
    @  745   SDC_2                                      1.      
    @  746   SDC_3                                      4.      
    @  750   SDC_4A                                     1.      
    @  751   SDC_4B                                     1.      
    @  752   SDC_4C                                     1.      
    @  753   SDC_4D                                     1.      
    @  754   SDC_4E                                     1.      
    @  755   SDC_4F                                     1.      
    @  756   SDC_4G                                     1.      
    @  757   SDC_4H                                     1.      
    @  758   SDC_4I                                     1.      
    @  759   SDC_4J                                     1.      
    @  760   SDC_4K                                     1.      
    @  761   SDC_4L                                     1.      
    @  762   SDC_4M                                     1.      
    @  763   SDC_4N                                     1.      
    @  764   SDC_4T                                     1.      
    @  765   SDC_4U                                     1.      
    @  766   SDC_4V                                     1.      
    @  767   SDC_4P                                     1.      
    @  768   SDC_4Q                                     1.      
    @  769   SDC_4R                                     1.      
    @  770   SDC_4S                                     1.      
    @  771   SDC_41                                     1.      
    @  772   SDC_42A                                    1.      
    @  773   SDC_42B                                    1.      
    @  774   SDC_42C                                    1.      
    @  775   SDC_43A                                    1.      
    @  776   SDC_43C                                    1.      
    @  777   SDC_43B                                    1.      
    @  778   SDC_43D                                    1.      
    @  779   SDC_43E                                    1.      
    @  780   SDC_43F                                    1.      
    @  781   SDC_43H                                    1.      
    @  782   SDC_43G                                    1.      
    @  783   SDC_43I                                    1.      
    @  784   SDC_43K                                    1.      
    @  785   SDC_43J                                    1.      
    @  786   SDC_43M                                    1.      
    @  787   SDC_5A_1                                   1.      
    @  788   SDCC5B1                                    8.      
    @  796   SDCC5B2                                    8.      
    @  804   SDCC5B3                                    8.      
    @  812   SDCC61                                     8.      
    @  820   SDCC62                                     8.      
    @  828   SDCC63                                     8.      
    @  836   SDCDFOLS                                   1.      
    @  837   DHH_OWN                                    1.      
    @  838   SDC_7AA                                    1.      
    @  839   SDCDLHM                                    2.      
    @  841   SDCDAIM                                    3.      
    @  844   SDCFIMM                                    1.      
    @  845   SDCDRES                                    3.      
    @  848   SDCDFL1                                    2.      
    @  850   SDCDABT                                    1.      
    @  851   SDCDCGT                                    2.      
    @  853   PMKPROXY                                   1.      
    @  854   DOFSC                                      1.      
    @  855   FSC_010                                    1.      
    @  856   FSC_020                                    1.      
    @  857   FSC_030                                    1.      
    @  858   FSC_040                                    1.      
    @  859   FSC_050                                    1.      
    @  860   FSC_060                                    1.      
    @  861   FSC_070                                    1.      
    @  862   FSC_080                                    1.      
    @  863   FSC_081                                    1.      
    @  864   FSC_090                                    1.      
    @  865   FSC_100                                    1.      
    @  866   FSC_110                                    1.      
    @  867   FSC_120                                    1.      
    @  868   FSC_121                                    1.      
    @  869   FSC_130                                    1.      
    @  870   FSC_140                                    1.      
    @  871   FSC_141                                    1.      
    @  872   FSC_150                                    1.      
    @  873   FSC_160                                    1.      
    @  874   FSCDHFS2                                   1.      
    @  875   FSCDAFS2                                   1.      
    @  876   FSCDCFS2                                   1.      
    @  877   DONEU                                      1.      
    @  878   NEUDNCR                                    1.      
    @  879   NEUDNCH                                    1.      
    @  880   NEUDMHR                                    1.      
    @  881   NEUDMHH                                    2.      
    @  883   NEUDEPR                                    1.      
    @  884   NEUDEPH                                    2.      
    @  886   NEUDCPR                                    1.      
    @  887   NEUDCPH                                    2.      
    @  889   NEUDSBR                                    1.      
    @  890   NEUDSBH                                    2.      
    @  892   NEUDHCR                                    1.      
    @  893   NEUDHCH                                    2.      
    @  895   NEUDMDR                                    1.      
    @  896   NEUDMDH                                    2.      
    @  898   NEUDDYR                                    1.      
    @  899   NEUDDYH                                    2.      
    @  901   NEUDTSR                                    1.      
    @  902   NEUDTSH                                    2.      
    @  904   NEUDPDR                                    1.      
    @  905   NEUDPDH                                    2.      
    @  907   NEUDALR                                    1.      
    @  908   NEUDALH                                    2.      
    @  910   NEUDHDR                                    1.      
    @  911   NEUDHDH                                    2.      
    @  913   NEUDSTR                                    1.      
    @  914   NEUDSTH                                    2.      
    @  916   NEUDBIR                                    1.      
    @  917   NEUDBIH                                    2.      
    @  919   NEUDBTR                                    1.      
    @  920   NEUDBTH                                    2.      
    @  922   NEUDSIR                                    1.      
    @  923   NEUDSIH                                    2.      
    @  925   NEUDSCR                                    1.      
    @  926   NEUDSCH                                    2.      
    @  928   NEUDADR                                    1.      
    @  929   NEUDADH                                    2.      
    @  931   NEUDMSH                                    2.      
    @  933   NEUDMSR                                    1.      
    @  934   EDU_1                                      1.      
    @  935   EDU_2                                      1.      
    @  936   EDU_3                                      1.      
    @  937   EDU_4A                                     2.      
    @  939   SDC_8                                      1.      
    @  940   SDC_9                                      1.      
    @  941   EDUDH04                                    1.      
    @  942   EDUDH10                                    2.      
    @  944   EDUDR04                                    1.      
    @  945   EDUDR10                                    2.      
    @  947   INC_1A                                     1.      
    @  948   INC_1B                                     1.      
    @  949   INC_1C                                     1.      
    @  950   INC_1D                                     1.      
    @  951   INC_1E                                     1.      
    @  952   INC_1F                                     1.      
    @  953   INC_1G                                     1.      
    @  954   INC_1O                                     1.      
    @  955   INC_1H                                     1.      
    @  956   INC_1J                                     1.      
    @  957   INC_1I                                     1.      
    @  958   INC_1K                                     1.      
    @  959   INC_1L                                     1.      
    @  960   INC_1M                                     1.      
    @  961   INC_1N                                     1.      
    @  962   INC_2                                      2.      
    @  964   INC_3                                      8.      
    @  972   INC_6A                                     1.      
    @  973   INC_6B                                     1.      
    @  974   INC_6C                                     1.      
    @  975   INC_6D                                     1.      
    @  976   INC_6E                                     1.      
    @  977   INC_6F                                     1.      
    @  978   INC_6G                                     1.      
    @  979   INC_6H                                     1.      
    @  980   INC_6I                                     1.      
    @  981   INC_6J                                     1.      
    @  982   INC_6K                                     1.      
    @  983   INC_6L                                     1.      
    @  984   INC_6M                                     1.      
    @  985   INC_6N                                     1.      
    @  986   INC_6O                                     1.      
    @  987   INC_7                                      2.      
    @  989   INC_8A                                     8.      
    @  997   INC_8B                                     1.      
    @  998   INC_8C                                     2.      
    @ 1000   INC_8D                                     2.      
    @ 1002   INCFIMP                                    1.      
    @ 1003   INCDHH                                     2.      
    @ 1005   INCDPER                                    2.      
    @ 1007   INCDADR                                   11.9     
    @ 1018   INCDRCA                                    2.      
    @ 1020   INCDRPR                                    2.      
    @ 1022   INCDRRS                                    2.      
    @ 1024   ACCZ_10                                    1.      
    @ 1025   ACCZ_11                                    1.      
    @ 1026   ACCZ_12A                                   1.      
    @ 1027   ACCZ_12B                                   1.      
    @ 1028   ACCZ_12C                                   1.      
    @ 1029   ACCZ_12D                                   1.      
    @ 1030   ACCZ_12E                                   1.      
    @ 1031   ACCZ_12F                                   1.      
    @ 1032   ACCZ_12G                                   1.      
    @ 1033   ACCZ_12H                                   1.      
    @ 1034   ACCZ_12I                                   1.      
    @ 1035   ACCZ_12J                                   1.      
    @ 1036   ACCZ_12K                                   1.      
    @ 1037   ACCZ_12L                                   1.      
    @ 1038   ACCZ_12M                                   1.      
    @ 1039   ACCZ_12N                                   1.      
    @ 1040   ACCZ_20                                    1.      
    @ 1041   ACCZ_21                                    1.      
    @ 1042   ACCZ_22A                                   1.      
    @ 1043   ACCZ_22B                                   1.      
    @ 1044   ACCZ_22C                                   1.      
    @ 1045   ACCZ_22D                                   1.      
    @ 1046   ACCZ_22E                                   1.      
    @ 1047   ACCZ_22F                                   1.      
    @ 1048   ACCZ_22G                                   1.      
    @ 1049   ACCZ_22H                                   1.      
    @ 1050   ACCZ_22I                                   1.      
    @ 1051   ACCZ_22J                                   1.      
    @ 1052   ACCZ_22K                                   1.      
    @ 1053   ACCZ_22L                                   1.      
    @ 1054   ACCZ_22M                                   1.      
    @ 1055   ACCZ_22N                                   1.      
    @ 1056   ACCZ_22O                                   1.      
    @ 1057   ACCZ_30                                    1.      
    @ 1058   ACCZ_31                                    1.      
    @ 1059   ACCZ_32A                                   1.      
    @ 1060   ACCZ_32B                                   1.      
    @ 1061   ACCZ_32C                                   1.      
    @ 1062   ACCZ_32D                                   1.      
    @ 1063   ACCZ_32E                                   1.      
    @ 1064   ACCZ_32F                                   1.      
    @ 1065   ACCZ_32G                                   1.      
    @ 1066   ACCZ_32H                                   1.      
    @ 1067   ACCZ_32I                                   1.      
    @ 1068   ACCZ_32J                                   1.      
    @ 1069   ACCZ_32K                                   1.      
    @ 1070   ACCZ_32L                                   1.      
    @ 1071   ACCZ_32M                                   1.      
    @ 1072   ACCZ_32N                                   1.      
    @ 1073   ACCZ_40                                    1.      
    @ 1074   ACCZ_40A                                   1.      
    @ 1075   ACCZ_40B                                   1.      
    @ 1076   ACCZ_40C                                   1.      
    @ 1077   ACCZ_40D                                   1.      
    @ 1078   ACCZ_40E                                   1.      
    @ 1079   ACCZ_40F                                   1.      
    @ 1080   ACCZ_40G                                   1.      
    @ 1081   ACCZ_41                                    1.      
    @ 1082   ACCZ_42                                    1.      
    @ 1083   ACCZ_43A                                   1.      
    @ 1084   ACCZ_43B                                   1.      
    @ 1085   ACCZ_43C                                   1.      
    @ 1086   ACCZ_43D                                   1.      
    @ 1087   ACCZ_43E                                   1.      
    @ 1088   ACCZ_43F                                   1.      
    @ 1089   ACCZ_43G                                   1.      
    @ 1090   ACCZ_43H                                   1.      
    @ 1091   ACCZ_43I                                   1.      
    @ 1092   ACCZ_44                                    1.      
    @ 1093   ACCZ_45A                                   1.      
    @ 1094   ACCZ_45B                                   1.      
    @ 1095   ACCZ_45C                                   1.      
    @ 1096   ACCZ_45D                                   1.      
    @ 1097   ACCZ_45E                                   1.      
    @ 1098   ACCZ_45F                                   1.      
    @ 1099   ACCZ_45G                                   1.      
    @ 1100   ACCZ_45H                                   1.      
    @ 1101   ACCZ_45I                                   1.      
    @ 1102   ACCZ_46                                    1.      
    @ 1103   ACCZ_47A                                   1.      
    @ 1104   ACCZ_47B                                   1.      
    @ 1105   ACCZ_47C                                   1.      
    @ 1106   ACCZ_47D                                   1.      
    @ 1107   ACCZ_47E                                   1.      
    @ 1108   ACCZ_47F                                   1.      
    @ 1109   ACCZ_47G                                   1.      
    @ 1110   ACCZ_47H                                   1.      
    @ 1111   ACCZ_47I                                   1.      
    @ 1112   ACCZ_50A                                   1.      
    @ 1113   ACCZ_50                                    1.      
    @ 1114   ACCZ_51                                    1.      
    @ 1115   ACCZ_52                                    1.      
    @ 1116   ACCZ_53A                                   1.      
    @ 1117   ACCZ_53B                                   1.      
    @ 1118   ACCZ_53C                                   1.      
    @ 1119   ACCZ_53D                                   1.      
    @ 1120   ACCZ_53E                                   1.      
    @ 1121   ACCZ_53F                                   1.      
    @ 1122   ACCZ_53G                                   1.      
    @ 1123   ACCZ_53H                                   1.      
    @ 1124   ACCZ_53I                                   1.      
    @ 1125   ACCZ_53J                                   1.      
    @ 1126   ACCZ_53K                                   1.      
    @ 1127   ACCZ_53L                                   1.      
    @ 1128   ACCZ_53M                                   1.      
    @ 1129   ACCZ_54                                    1.      
    @ 1130   ACCZ_55A                                   1.      
    @ 1131   ACCZ_55B                                   1.      
    @ 1132   ACCZ_55C                                   1.      
    @ 1133   ACCZ_55D                                   1.      
    @ 1134   ACCZ_55E                                   1.      
    @ 1135   ACCZ_55F                                   1.      
    @ 1136   ACCZ_55G                                   1.      
    @ 1137   ACCZ_55H                                   1.      
    @ 1138   ACCZ_55I                                   1.      
    @ 1139   ACCZ_55J                                   1.      
    @ 1140   ACCZ_55K                                   1.      
    @ 1141   ACCZ_55L                                   1.      
    @ 1142   ACCZ_55M                                   1.      
    @ 1143   ACCZ_60                                    1.      
    @ 1144   ACCZ_61                                    1.      
    @ 1145   ACCZ_62                                    1.      
    @ 1146   ACCZ_63A                                   1.      
    @ 1147   ACCZ_63B                                   1.      
    @ 1148   ACCZ_63C                                   1.      
    @ 1149   ACCZ_63D                                   1.      
    @ 1150   ACCZ_63E                                   1.      
    @ 1151   ACCZ_63F                                   1.      
    @ 1152   ACCZ_63G                                   1.      
    @ 1153   ACCZ_63H                                   1.      
    @ 1154   ACCZ_63I                                   1.      
    @ 1155   ACCZ_63J                                   1.      
    @ 1156   ACCZ_63K                                   1.      
    @ 1157   ACCZ_63L                                   1.      
    @ 1158   ACCZ_63M                                   1.      
    @ 1159   ACCZ_64                                    1.      
    @ 1160   ACCZ_65A                                   1.      
    @ 1161   ACCZ_65B                                   1.      
    @ 1162   ACCZ_65C                                   1.      
    @ 1163   ACCZ_65D                                   1.      
    @ 1164   ACCZ_65E                                   1.      
    @ 1165   ACCZ_65F                                   1.      
    @ 1166   ACCZ_65G                                   1.      
    @ 1167   ACCZ_65H                                   1.      
    @ 1168   ACCZ_65I                                   1.      
    @ 1169   ACCZ_65J                                   1.      
    @ 1170   ACCZ_65K                                   1.      
    @ 1171   ACCZ_65L                                   1.      
    @ 1172   ACCZ_65M                                   1.      
    @ 1173   ACCZ_66                                    1.      
    @ 1174   ACCZ_67A                                   1.      
    @ 1175   ACCZ_67B                                   1.      
    @ 1176   ACCZ_67C                                   1.      
    @ 1177   ACCZ_67D                                   1.      
    @ 1178   ACCZ_67E                                   1.      
    @ 1179   ACCZ_67F                                   1.      
    @ 1180   ACCZ_67G                                   1.      
    @ 1181   ACCZ_67H                                   1.      
    @ 1182   ACCZ_67I                                   1.      
    @ 1183   ACCZ_67J                                   1.      
    @ 1184   ACCZ_67K                                   1.      
    @ 1185   ACCZ_67L                                   1.      
    @ 1186   ACCZ_67M                                   1.      
    @ 1187   WTMZ_01                                    1.      
    @ 1188   WTMZ_02                                    2.      
    @ 1190   WTMZ_03                                    1.      
    @ 1191   WTMZ_04                                    1.      
    @ 1192   WTMZ_05                                    1.      
    @ 1193   WTMZ_06A                                   1.      
    @ 1194   WTMZ_06B                                   1.      
    @ 1195   WTMZ_06C                                   1.      
    @ 1196   WTMZ_06D                                   1.      
    @ 1197   WTMZ_06E                                   1.      
    @ 1198   WTMZ_06F                                   1.      
    @ 1199   WTMZ_06G                                   1.      
    @ 1200   WTMZ_06H                                   1.      
    @ 1201   WTMZ_06I                                   1.      
    @ 1202   WTMZ_06J                                   1.      
    @ 1203   WTMZ_06K                                   1.      
    @ 1204   WTMZ_06L                                   1.      
    @ 1205   WTMZ_06M                                   1.      
    @ 1206   WTMZ_07A                                   3.      
    @ 1209   WTMZ_07B                                   1.      
    @ 1210   WTMZ_08A                                   3.      
    @ 1213   WTMZ_08B                                   1.      
    @ 1214   WTMZ_10                                    1.      
    @ 1215   WTMZ_11A                                   3.      
    @ 1218   WTMZ_11B                                   1.      
    @ 1219   WTMZ_12                                    1.      
    @ 1220   WTMZ_13A                                   1.      
    @ 1221   WTMZ_13B                                   1.      
    @ 1222   WTMZ_13C                                   1.      
    @ 1223   WTMZ_14                                    1.      
    @ 1224   WTMZ_15A                                   1.      
    @ 1225   WTMZ_15B                                   1.      
    @ 1226   WTMZ_15C                                   1.      
    @ 1227   WTMZ_15D                                   1.      
    @ 1228   WTMZ_15E                                   1.      
    @ 1229   WTMZ_15F                                   1.      
    @ 1230   WTMZ_15G                                   1.      
    @ 1231   WTMZ_15H                                   1.      
    @ 1232   WTMZ_15I                                   1.      
    @ 1233   WTMZ_15J                                   1.      
    @ 1234   WTMZ_15K                                   1.      
    @ 1235   WTMZ_15L                                   1.      
    @ 1236   WTMZ_16                                    2.      
    @ 1238   WTMZ_17                                    1.      
    @ 1239   WTMZ_18                                    1.      
    @ 1240   WTMZ_19                                    1.      
    @ 1241   WTMZ_20A                                   1.      
    @ 1242   WTMZ_20B                                   1.      
    @ 1243   WTMZ_20C                                   1.      
    @ 1244   WTMZ_20D                                   1.      
    @ 1245   WTMZ_20E                                   1.      
    @ 1246   WTMZ_20F                                   1.      
    @ 1247   WTMZ_20G                                   1.      
    @ 1248   WTMZ_20H                                   1.      
    @ 1249   WTMZ_20I                                   1.      
    @ 1250   WTMZ_20J                                   1.      
    @ 1251   WTMZ_20K                                   1.      
    @ 1252   WTMZ_20L                                   1.      
    @ 1253   WTMZ_20M                                   1.      
    @ 1254   WTMZ_20N                                   1.      
    @ 1255   WTMZ_21A                                   3.      
    @ 1258   WTMZ_21B                                   1.      
    @ 1259   WTMZ_22                                    1.      
    @ 1260   WTMZ_23A                                   3.      
    @ 1263   WTMZ_23B                                   1.      
    @ 1264   WTMZ_24                                    1.      
    @ 1265   WTMZ_25A                                   3.      
    @ 1268   WTMZ_25B                                   1.      
    @ 1269   WTMZ_26                                    1.      
    @ 1270   WTMZ_27A                                   1.      
    @ 1271   WTMZ_27B                                   1.      
    @ 1272   WTMZ_27C                                   1.      
    @ 1273   WTMZ_27D                                   1.      
    @ 1274   WTMZ_28                                    1.      
    @ 1275   WTMZ_29A                                   1.      
    @ 1276   WTMZ_29B                                   1.      
    @ 1277   WTMZ_29C                                   1.      
    @ 1278   WTMZ_29D                                   1.      
    @ 1279   WTMZ_29E                                   1.      
    @ 1280   WTMZ_29F                                   1.      
    @ 1281   WTMZ_29G                                   1.      
    @ 1282   WTMZ_29H                                   1.      
    @ 1283   WTMZ_29I                                   1.      
    @ 1284   WTMZ_29J                                   1.      
    @ 1285   WTMZ_29K                                   1.      
    @ 1286   WTMZ_29L                                   1.      
    @ 1287   WTMZ_30                                    1.      
    @ 1288   WTMZ_31                                    1.      
    @ 1289   WTMZ_32                                    1.      
    @ 1290   WTMZ_33                                    1.      
    @ 1291   WTMZ_34                                    1.      
    @ 1292   WTMZ_35                                    1.      
    @ 1293   WTMZ_36                                    1.      
    @ 1294   WTMZ_37A                                   1.      
    @ 1295   WTMZ_37B                                   1.      
    @ 1296   WTMZ_37C                                   1.      
    @ 1297   WTMZ_37D                                   1.      
    @ 1298   WTMZ_37E                                   1.      
    @ 1299   WTMZ_37F                                   1.      
    @ 1300   WTMZ_37G                                   1.      
    @ 1301   WTMZ_37H                                   1.      
    @ 1302   WTMZ_37I                                   1.      
    @ 1303   WTMZ_37J                                   1.      
    @ 1304   WTMZ_37K                                   1.      
    @ 1305   WTMZ_37L                                   1.      
    @ 1306   WTMZ_37M                                   1.      
    @ 1307   WTMZ_38A                                   3.      
    @ 1310   WTMZ_38B                                   1.      
    @ 1311   WTMZ_39A                                   3.      
    @ 1314   WTMZ_39B                                   1.      
    @ 1315   WTMZ_40                                    1.      
    @ 1316   WTMZ_41A                                   3.      
    @ 1319   WTMZ_41B                                   1.      
    @ 1320   WTMZ_42                                    1.      
    @ 1321   WTMZ_43                                    1.      
    @ 1322   WTMZ_44                                    1.      
    @ 1323   WTMZ_45A                                   1.      
    @ 1324   WTMZ_45B                                   1.      
    @ 1325   WTMZ_45C                                   1.      
    @ 1326   WTMZ_45D                                   1.      
    @ 1327   WTMZ_45E                                   1.      
    @ 1328   WTMZ_45F                                   1.      
    @ 1329   WTMZ_45G                                   1.      
    @ 1330   WTMZ_45H                                   1.      
    @ 1331   WTMZ_45I                                   1.      
    @ 1332   WTMZ_45J                                   1.      
    @ 1333   WTMZ_45K                                   1.      
    @ 1334   WTMZ_45L                                   1.      
    @ 1335   WTMZDSO                                    4.      
    @ 1339   WTMZDSN                                    4.      
    @ 1343   WTMZDSA                                    4.      
    @ 1347   WTMZDCO                                    4.      
    @ 1351   WTMZDCN                                    4.      
    @ 1355   WTMZDCA                                    4.      
    @ 1359   WTMZDTO                                    4.      
    @ 1363   WTMZDTN                                    4.      
    @ 1367   WTMZDTA                                    4.      
    @ 1371   WTS_S1M                                    8.2     
    @ 1379   WTS_S1S                                    8.2     
         ;
