 format
    GEOA_PRV    PROVFM.  
    GEOA_HR4   $ADM_4HR. 
    GEOADCMA    DVDCMA.  
    GEOADPRG    GEO_PRG. 
    GEOADUR2    GEO_2UR. 
    GEOADUR5    GEO_5UR. 
    GEOADAB     GEO_AB.  
    GEOADON     GEO_ON.  
    GEOADPE     GEO_PE.  
    SAMA_TYP    ADM_SAM. 
    SAMA_CP     SAM_CP.  
    SAMAFQ4     YESNOFM. 
    SAMADNUM    SAM_RESP.
    ADMA_PRX    PROXYFM. 
    ADMA_IMP    YESNOFM. 
    ADMA_STA    ADM_STA. 
    SAMADSHR   $YESNO_C. 
    SAMADLNK   $YESNO_C. 
    ADMA_N09    TELFM.   
    ADMA_N10    YESNOFM. 
    ADMA_N11    YESNOFM. 
    ADMA_LHH    AM3_LP.  
    ADMA_N12    ADM_LNG. 
    DHHA_AGE    AGE3DFM. 
    DHHA_SEX    DHC_SEX. 
    DHHA_MS     DHC_MAR. 
    GENA_01     GOOD5FM. 
    GENA_02     GEN_2F.  
    GENA_03     GEN_3F.  
    GENA_04     GEN_4F.  
    GENA_05     GEN_4F.  
    GENA_06     GEN_4F.  
    GENA_07     STC_1F.  
    GENA_08     YESNOFM. 
    GENA_09     STC_1F.  
    GENA_10     GEN_10F. 
    GENADHDI    GHCDHDI. 
    CIHAFOPT    YESNOFM. 
    CIHA_1      YESNOFM. 
    CIHA_2      GHS_12F. 
    CIHA_3      YESNOFM. 
    CIHA_4      GHS_14F. 
    CIHA_5      YESNOFM. 
    CIHA_6A     YESNOFM. 
    CIHA_6B     YESNOFM. 
    CIHA_6C     YESNOFM. 
    CIHA_6D     YESNOFM. 
    CIHA_6E     YESNOFM. 
    CIHA_6F     YESNOFM. 
    CIHA_6G     YESNOFM. 
    CIHA_6H     YESNOFM. 
    CIHA_7      YESNOFM. 
    CIHA_8A     YESNOFM. 
    CIHA_8B     YESNOFM. 
    CIHA_8C     YESNOFM. 
    CIHA_8D     YESNOFM. 
    CIHA_8E     YESNOFM. 
    CIHA_8F     YESNOFM. 
    CIHA_8G     YESNOFM. 
    CIHA_8H     YESNOFM. 
    CIHA_8I     YESNOFM. 
    HWTA_2      HWC_2FM. 
    HWTA_2A     HWC_2A.  
    HWTA_2B     HWC_2B.  
    HWTA_2C     HWC_2C.  
    HWTA_2D     HWC_2D.  
    HWTA_2E     HWC_2E.  
    HWTA_2F     HWC_2F.  
    HWTA_3      HWT_FM.  
    HWTA_N4     WHTFM.   
    HWTA_4      HWS_1F.  
    HWTADHTM    HWT_HTM. 
    HWTADHTI    HWT_HTI. 
    HWTADWTK    HWT_WTK. 
    HWTADWTP    HWT_WTP. 
    HWTADBMI    HWT_BMI. 
    HWTADSW     HWC_CODE.
    TWDA_1      YESNOFM. 
    TWDA_2      TWC_NUM. 
    TWDA_3      YESNOFM. 
    TWDA_4      TWC_NUM. 
    TWDA_5      YESNOFM. 
    TWDADDDY    TWC_NUM. 
    HCUA_01     YESNOFM. 
    HCUA_01A    NIGHT3D. 
    HCUA_02A    TIMES3D. 
    HCUA_03A    HCC_CONT.
    HCUA_02B    TIMES2D. 
    HCUA_02C    TIMES3D. 
    HCUA_03C    HCC_CONT.
    HCUA_02D    TIMES3D. 
    HCUA_03D    HCC_CONT.
    HCUA_02E    TIMES3D. 
    HCUA_02F    TIMES3D. 
    HCUA_02G    TIMES3D. 
    HCUA_02H    TIMES3D. 
    HCUA_02I    TIMES3D. 
    HCUA_02J    TIMES3D. 
    HCUA_04A    YESNOFM. 
    HCUA_04     YESNOFM. 
    HCUA_05A    YESNOFM. 
    HCUA_05B    YESNOFM. 
    HCUA_05C    YESNOFM. 
    HCUA_05D    YESNOFM. 
    HCUA_05E    YESNOFM. 
    HCUA_05F    YESNOFM. 
    HCUA_05G    YESNOFM. 
    HCUA_05H    YESNOFM. 
    HCUA_05I    YESNOFM. 
    HCUA_05J    YESNOFM. 
    HCUA_05K    YESNOFM. 
    HCUA_05L    YESNOFM. 
    HCUA_06     YESNOFM. 
    HCUA_07A    YESNOFM. 
    HCUA_07B    YESNOFM. 
    HCUA_07C    YESNOFM. 
    HCUA_07D    YESNOFM. 
    HCUA_07E    YESNOFM. 
    HCUA_07F    YESNOFM. 
    HCUA_07G    YESNOFM. 
    HCUA_07H    YESNOFM. 
    HCUA_07I    YESNOFM. 
    HCUA_07J    YESNOFM. 
    HCUA_07K    YESNOFM. 
    HCUA_07L    YESNOFM. 
    HCUA_07M    YESNOFM. 
    HCUA_07N    YESNOFM. 
    HCUA_08A    YESNOFM. 
    HCUA_08B    YESNOFM. 
    HCUA_08C    YESNOFM. 
    HCUA_08D    YESNOFM. 
    HCUA_08E    YESNOFM. 
    HCUADMDC    CON3DFM. 
    HCUAFHPC    YESNOFM. 
    HMCAFOPT    YESNOFM. 
    HMCA_09     YESNOFM. 
    HMCA_10A    YESNOFM. 
    HMCA_10B    YESNOFM. 
    HMCA_10C    YESNOFM. 
    HMCA_10D    YESNOFM. 
    HMCA_10E    YESNOFM. 
    HMCA_10F    YESNOFM. 
    HMCA_10G    YESNOFM. 
    HMCA_10H    YESNOFM. 
    RACA_1      SOMETIME.
    RACA_2A     SOMETIME.
    RACA_2B     RAC2BFM. 
    RACA_2C     SOMETIME.
    RACA_5      RAC_5F.  
    RACA_6A     YESNOFM. 
    RACA_6B     YESNOFM. 
    RACA_6C     YESNOFM. 
    RACA_6D     YESNOFM. 
    RACA_6E     YESNOFM. 
    RACA_6F     YESNOFM. 
    RACADIMP    SOMETIME.
    RACAF6      YESNOFM. 
    CCCA_011    YESNOFM. 
    CCCA_012    AGE3DFM. 
    CCCA_021    YESNOFM. 
    CCCA_022    AGE3DFM. 
    CCCA_031    YESNOFM. 
    CCCA_032    AGE3DFM. 
    CCCA_035    YESNOFM. 
    CCCA_036    YESNOFM. 
    CCCA_041    YESNOFM. 
    CCCA_042    AGE3DFM. 
    CCCA_051    YESNOFM. 
    CCCA_052    AGE3DFM. 
    CCCA_05A    CCC_D1A. 
    CCCA_061    YESNOFM. 
    CCCA_062    AGE3DFM. 
    CCCA_071    YESNOFM. 
    CCCA_072    AGE3DFM. 
    CCCA_081    YESNOFM. 
    CCCA_082    AGE3DFM. 
    CCCA_91A    YESNOFM. 
    CCCA_92A    AGE3DFM. 
    CCCA_91B    YESNOFM. 
    CCCA_92B    AGE3DFM. 
    CCCA_101    YESNOFM. 
    CCCA_102    AGE3DFM. 
    CCCA_10A    YESNOFM. 
    CCCA_10B    YESNOFM. 
    CCCA_10C    CCC_10C. 
    CCCA_105    YESNOFM. 
    CCCA_111    YESNOFM. 
    CCCA_112    AGE3DFM. 
    CCCA_121    YESNOFM. 
    CCCA_122    AGE3DFM. 
    CCCA_12A    YESNOFM. 
    CCCA_12J    YESNOFM. 
    CCCA_12K    YESNOFM. 
    CCCA_131    YESNOFM. 
    CCCA_132    AGE3DFM. 
    CCCA_13A    YESNOFM. 
    CCCA_13B    YESNOFM. 
    CCCA_13C    YESNOFM. 
    CCCA_13D    YESNOFM. 
    CCCA_13E    YESNOFM. 
    CCCA_13F    YESNOFM. 
    CCCA_141    YESNOFM. 
    CCCA_142    AGE3DFM. 
    CCCA_151    YESNOFM. 
    CCCA_152    AGE3DFM. 
    CCCA_161    YESNOFM. 
    CCCA_162    AGE3DFM. 
    CCCA_171    YESNOFM. 
    CCCA_172    AGE3DFM. 
    CCCA_181    YESNOFM. 
    CCCA_182    AGE3DFM. 
    CCCA_191    YESNOFM. 
    CCCA_192    AGE3DFM. 
    CCCA_201    YESNOFM. 
    CCCA_202    AGE3DFM. 
    CCCA_211    YESNOFM. 
    CCCA_212    AGE3DFM. 
    CCCA_231    YESNOFM. 
    CCCA_232    AGE3DFM. 
    CCCA_241    YESNOFM. 
    CCCA_242    AGE3DFM. 
    CCCA_251    YESNOFM. 
    CCCA_252    AGE3DFM. 
    CCCA_261    YESNOFM. 
    CCCA_262    AGE3DFM. 
    CCCA_221    YESNOFM. 
    CCCAF1      YESNOFM. 
    CCCADTOT    CCCDNUM. 
    DRGAFOPT    YESNOFM. 
    DRGA_1A     YESNOFM. 
    DRGA_1B     YESNOFM. 
    DRGA_1C     YESNOFM. 
    DRGA_1D     YESNOFM. 
    DRGA_1E     YESNOFM. 
    DRGA_1F     YESNOFM. 
    DRGA_1G     YESNOFM. 
    DRGA_1H     YESNOFM. 
    DRGA_1I     YESNOFM. 
    DRGA_1J     YESNOFM. 
    DRGA_1K     YESNOFM. 
    DRGA_1L     YESNOFM. 
    DRGA_1M     YESNOFM. 
    DRGA_1N     YESNOFM. 
    DRGA_1O     YESNOFM. 
    DRGA_1P     YESNOFM. 
    DRGA_1Q     YESNOFM. 
    DRGA_1R     YESNOFM. 
    DRGA_1S     YESNOFM. 
    DRGA_1T     YESNOFM. 
    DRGA_1T1    DGC_1T1F.
    DRGA_1T2    YEARFM.  
    DRGA_1U     YESNOFM. 
    DRGA_1V     YESNOFM. 
    DRGAF1      YESNOFM. 
    BPCA_010    YESNOFM. 
    BPCA_012    WH2_LAST.
    BPCA_16A    YESNOFM. 
    BPCA_16B    YESNOFM. 
    BPCA_16C    YESNOFM. 
    BPCA_16D    YESNOFM. 
    BPCA_16E    YESNOFM. 
    BPCA_16F    YESNOFM. 
    BPCA_16G    YESNOFM. 
    BPCA_16H    YESNOFM. 
    BPCA_16I    YESNOFM. 
    BPCA_16J    YESNOFM. 
    BPCA_16K    YESNOFM. 
    BPCA_16L    YESNOFM. 
    BPCA_16M    YESNOFM. 
    PAPA_020    YESNOFM. 
    PAPA_022    WHC_22F. 
    PAPA_26A    YESNOFM. 
    PAPA_26B    YESNOFM. 
    PAPA_26C    YESNOFM. 
    PAPA_26D    YESNOFM. 
    PAPA_26E    YESNOFM. 
    PAPA_26F    YESNOFM. 
    PAPA_26G    YESNOFM. 
    PAPA_26H    YESNOFM. 
    PAPA_26I    YESNOFM. 
    PAPA_26J    YESNOFM. 
    PAPA_26K    YESNOFM. 
    PAPA_26L    YESNOFM. 
    PAPA_26M    YESNOFM. 
    PAPA_26N    YESNOFM. 
    PAPA_26O    YESNOFM. 
    MAMA_30     YESNOFM. 
    MAMA_31A    YESNOFM. 
    MAMA_31B    YESNOFM. 
    MAMA_31C    YESNOFM. 
    MAMA_31D    YESNOFM. 
    MAMA_31E    YESNOFM. 
    MAMA_31F    YESNOFM. 
    MAMA_31G    YESNOFM. 
    MAMA_31H    YESNOFM. 
    MAMA_32     WH2_LAST.
    MAMA_36A    YESNOFM. 
    MAMA_36B    YESNOFM. 
    MAMA_36C    YESNOFM. 
    MAMA_36D    YESNOFM. 
    MAMA_36E    YESNOFM. 
    MAMA_36F    YESNOFM. 
    MAMA_36G    YESNOFM. 
    MAMA_36H    YESNOFM. 
    MAMA_36I    YESNOFM. 
    MAMA_36J    YESNOFM. 
    MAMA_36K    YESNOFM. 
    MAMA_36L    YESNOFM. 
    MAMA_36M    YESNOFM. 
    MAMA_37     YESNOFM. 
    MAMA_38     YESNOFM. 
    BRXAFOPT    YESNOFM. 
    BRXA_110    YESNOFM. 
    BRXA_112    WH2_LAST.
    BRXA_16A    YESNOFM. 
    BRXA_16B    YESNOFM. 
    BRXA_16C    YESNOFM. 
    BRXA_16D    YESNOFM. 
    BRXA_16E    YESNOFM. 
    BRXA_16F    YESNOFM. 
    BRXA_16G    YESNOFM. 
    BRXA_16H    YESNOFM. 
    BRXA_16I    YESNOFM. 
    BRXA_16J    YESNOFM. 
    BRXA_16K    YESNOFM. 
    BRXA_16L    YESNOFM. 
    BRXA_16M    YESNOFM. 
    BSXAFOPT    YESNOFM. 
    BSXA_120    YESNOFM. 
    BSXA_121    WHS_91F. 
    BSXA_22A    YESNOFM. 
    BSXA_22B    YESNOFM. 
    BSXA_22C    YESNOFM. 
    BSXA_22D    YESNOFM. 
    BSXA_22E    YESNOFM. 
    BSXA_22F    YESNOFM. 
    BSXA_22G    YESNOFM. 
    DENAFOPT    YESNOFM. 
    DENA_130    YESNOFM. 
    DENA_132    DV61FM.  
    DENA_36A    YESNOFM. 
    DENA_36B    YESNOFM. 
    DENA_36C    YESNOFM. 
    DENA_36D    YESNOFM. 
    DENA_36E    YESNOFM. 
    DENA_36F    YESNOFM. 
    DENA_36G    YESNOFM. 
    DENA_36H    YESNOFM. 
    DENA_36I    YESNOFM. 
    DENA_36J    YESNOFM. 
    DENA_36K    YESNOFM. 
    DENA_36L    YESNOFM. 
    DENA_36M    YESNOFM. 
    DENA_36N    YESNOFM. 
    EYXAFOPT    YESNOFM. 
    EYXA_140    YESNOFM. 
    EYXA_142    ACCQ71FM.
    EYXA_46A    YESNOFM. 
    EYXA_46B    YESNOFM. 
    EYXA_46C    YESNOFM. 
    EYXA_46D    YESNOFM. 
    EYXA_46E    YESNOFM. 
    EYXA_46F    YESNOFM. 
    EYXA_46G    YESNOFM. 
    EYXA_46H    YESNOFM. 
    EYXA_46I    YESNOFM. 
    EYXA_46J    YESNOFM. 
    EYXA_46K    YESNOFM. 
    EYXA_46L    YESNOFM. 
    EYXA_46M    YESNOFM. 
    PCUAFOPT    YESNOFM. 
    PCUA_150    YESNOFM. 
    PCUA_151    YESNOFM. 
    PCUA_152    PC42F.   
    PCUA_56A    YESNOFM. 
    PCUA_56B    YESNOFM. 
    PCUA_56C    YESNOFM. 
    PCUA_56D    YESNOFM. 
    PCUA_56E    YESNOFM. 
    PCUA_56F    YESNOFM. 
    PCUA_56G    YESNOFM. 
    PCUA_56H    YESNOFM. 
    PCUA_56I    YESNOFM. 
    PCUA_56J    YESNOFM. 
    PCUA_56K    YESNOFM. 
    PCUA_56L    YESNOFM. 
    PCUA_56M    YESNOFM. 
    FLUAFOPT    YESNOFM. 
    FLUA_160    YESNOFM. 
    FLUA_162    FS52F.   
    FLUA_66A    YESNOFM. 
    FLUA_66B    YESNOFM. 
    FLUA_66C    YESNOFM. 
    FLUA_66D    YESNOFM. 
    FLUA_66E    YESNOFM. 
    FLUA_66F    YESNOFM. 
    FLUA_66G    YESNOFM. 
    FLUA_66H    YESNOFM. 
    FLUA_66I    YESNOFM. 
    FLUA_66J    YESNOFM. 
    FLUA_66K    YESNOFM. 
    FLUA_66L    YESNOFM. 
    FLUA_66M    YESNOFM. 
    FLUA_66N    YESNOFM. 
    PSAA_170    YESNOFM. 
    PSAA_172    WH2_LAST.
    PSAA_73A    YESNOFM. 
    PSAA_73B    YESNOFM. 
    PSAA_73C    YESNOFM. 
    PSAA_73D    YESNOFM. 
    PSAA_73E    YESNOFM. 
    PSAA_73F    YESNOFM. 
    FVCA_1A     FVC_1A.  
    FVCA_1B     TIMES2D. 
    FVCA_1C     TIMES2D. 
    FVCA_1D     TIMES3D. 
    FVCA_1E     TIMES3D. 
    FVCA_2A     FVC_1A.  
    FVCA_2B     TIMES2D. 
    FVCA_2C     TIMES2D. 
    FVCA_2D     TIMES3D. 
    FVCA_2E     TIMES3D. 
    FVCA_3A     FVC_1A.  
    FVCA_3B     TIMES2D. 
    FVCA_3C     TIMES2D. 
    FVCA_3D     TIMES3D. 
    FVCA_3E     TIMES3D. 
    FVCA_4A     FVC_1A.  
    FVCA_4B     TIMES2D. 
    FVCA_4C     TIMES2D. 
    FVCA_4D     TIMES3D. 
    FVCA_4E     TIMES3D. 
    FVCA_5A     FVC_1A.  
    FVCA_5B     TIMES2D. 
    FVCA_5C     TIMES2D. 
    FVCA_5D     TIMES3D. 
    FVCA_5E     TIMES3D. 
    FVCA_6A     FVC_1A.  
    FVCA_6B     SERV2FM. 
    FVCA_6C     SERV2FM. 
    FVCA_6D     SERV3FM. 
    FVCA_6E     SERV3FM. 
    FVCADJUI    FVC_DC.  
    FVCADFRU    FVC_DC.  
    FVCADSAL    FVC_DC.  
    FVCADPOT    FVC_DC.  
    FVCADCAR    FVC_DC.  
    FVCADVEG    FVC_PO.  
    FVCADTOT    FVC_SP.  
    FVCAGTOT    FVC_RDA. 
    PACA_1A     YESNOFM. 
    PACA_1B     YESNOFM. 
    PACA_1C     YESNOFM. 
    PACA_1D     YESNOFM. 
    PACA_1E     YESNOFM. 
    PACA_1F     YESNOFM. 
    PACA_1G     YESNOFM. 
    PACA_1H     YESNOFM. 
    PACA_1I     YESNOFM. 
    PACA_1J     YESNOFM. 
    PACA_1K     YESNOFM. 
    PACA_1L     YESNOFM. 
    PACA_1M     YESNOFM. 
    PACA_1N     YESNOFM. 
    PACA_1O     YESNOFM. 
    PACA_1P     YESNOFM. 
    PACA_1Q     YESNOFM. 
    PACA_1R     YESNOFM. 
    PACA_1S     YESNOFM. 
    PACA_1T     YESNOFM. 
    PACA_1U     YESNOFM. 
    PACA_1V     YESNOFM. 
    PACA_1W     YESNOFM. 
    PACA_1X     YESNOFM. 
    PACA_2A     TIMES3D. 
    PACA_3A     PAC_TIME.
    PACA_2B     TIMES3D. 
    PACA_3B     PAC_TIME.
    PACA_2C     TIMES3D. 
    PACA_3C     PAC_TIME.
    PACA_2D     TIMES3D. 
    PACA_3D     PAC_TIME.
    PACA_2E     TIMES3D. 
    PACA_3E     PAC_TIME.
    PACA_2F     TIMES3D. 
    PACA_3F     PAC_TIME.
    PACA_2G     TIMES3D. 
    PACA_3G     PAC_TIME.
    PACA_2H     TIMES3D. 
    PACA_3H     PAC_TIME.
    PACA_2I     TIMES3D. 
    PACA_3I     PAC_TIME.
    PACA_2J     TIMES3D. 
    PACA_3J     PAC_TIME.
    PACA_2K     TIMES3D. 
    PACA_3K     PAC_TIME.
    PACA_2L     TIMES3D. 
    PACA_3L     PAC_TIME.
    PACA_2M     TIMES3D. 
    PACA_3M     PAC_TIME.
    PACA_2N     TIMES3D. 
    PACA_3N     PAC_TIME.
    PACA_2O     TIMES3D. 
    PACA_3O     PAC_TIME.
    PACA_2P     TIMES3D. 
    PACA_3P     PAC_TIME.
    PACA_2Q     TIMES3D. 
    PACA_3Q     PAC_TIME.
    PACA_2R     TIMES3D. 
    PACA_3R     PAC_TIME.
    PACA_2S     TIMES3D. 
    PACA_3S     PAC_TIME.
    PACA_2T     TIMES3D. 
    PACA_3T     PAC_TIME.
    PACA_2U     TIMES3D. 
    PACA_3U     PAC_TIME.
    PACA_2W     TIMES3D. 
    PACA_3W     PAC_TIME.
    PACA_2X     TIMES3D. 
    PACA_3X     PAC_TIME.
    PACA_4A     PACHOURS.
    PACA_4B     PACHOURS.
    PACA_6      PAC_6F.  
    PACADEE     PACDEE.  
    PACAFLEI    YESNOFM. 
    PACADFM     PACDFM.  
    PACADFR     PACDFR.  
    PACAFD      YESNOFM. 
    PACADPAI    PACDPAI. 
    SACAFOPT    YESNOFM. 
    SACA_1      SAC_1F.  
    SACA_2      SAC_1F.  
    SACA_3      SAC_1F.  
    SACA_4      SAC_1F.  
    SACADTOT    SAC_NUM. 
    UPEAFOPT    YESNOFM. 
    UPEA_101    PAC_5F.  
    UPEA_02A    PAC_5F.  
    UPEA_02B    PAC_5F.  
    UPEA_02C    PAC_5F.  
    UPEA_02D    PAC_5F.  
    UPEA_103    PAC_5F.  
    REPA_1      YESNOFM. 
    REPA_3      RPC03F.  
    REPA_4A     YESNOFM. 
    REPA_4B     YESNOFM. 
    REPA_4C     YESNOFM. 
    REPA_4D     YESNOFM. 
    REPA_4E     YESNOFM. 
    REPA_4F     YESNOFM. 
    INJA_01     YESNOFM. 
    INJA_02     IJC_2F.  
    INJA_03     MONTHFM. 
    INJA_04     INJ_4F.  
    INJA_05     IJC03F.  
    INJA_06     IJC04F.  
    INJA_07     IJC_4A.  
    INJA_08     IJC05F.  
    INJA_09     IJC_9F.  
    INJA_10     YESNOFM. 
    INJA_11     IJC_10A. 
    INJA_12     IJC_10B. 
    INJA_13     YESNOFM. 
    INJA_14A    YESNOFM. 
    INJA_14B    YESNOFM. 
    INJA_14C    YESNOFM. 
    INJA_14D    YESNOFM. 
    INJA_14E    YESNOFM. 
    INJA_14F    YESNOFM. 
    INJA_14G    YESNOFM. 
    INJA_14H    YESNOFM. 
    INJA_14I    YESNOFM. 
    INJA_14J    YESNOFM. 
    INJA_14K    YESNOFM. 
    INJA_15     YESNOFM. 
    INJA_16     YESNOFM. 
    INJA_17     IJC_NUM. 
    INJADTBS    INJ_TBS. 
    INJADCAU    INJ_CAU. 
    INJADCBP    IJCD2F.  
    INJADSTT    INJ_STT. 
    HUIA_01     YESNOFM. 
    HUIA_02     YESNOFM. 
    HUIA_03     YESNOFM. 
    HUIA_04     YESNOFM. 
    HUIA_05     YESNOFM. 
    HUIA_06     YESNOFM. 
    HUIA_07     YESNOFM. 
    HUIA_07A    YESNOFM. 
    HUIA_08     YESNOFM. 
    HUIA_09     YESNOFM. 
    HUIA_10     YESNOFM. 
    HUIA_11     YESNOFM. 
    HUIA_12     YESNOFM. 
    HUIA_13     YESNOFM. 
    HUIA_14     YESNOFM. 
    HUIA_15     YESNOFM. 
    HUIA_16     YESNOFM. 
    HUIA_17     YESNOFM. 
    HUIA_18     YESNOFM. 
    HUIA_19     HSC_19F. 
    HUIA_20     YESNOFM. 
    HUIA_21     YESNOFM. 
    HUIA_22     YESNOFM. 
    HUIA_23     HSC_23F. 
    HUIA_24     YESNOFM. 
    HUIA_25     HSC_25F. 
    HUIA_26     HSC_26F. 
    HUIA_27     HSC_27F. 
    HUIA_28     YESNOFM. 
    HUIA_29     HSC_29F. 
    HUIA_30     HSC_30F. 
    HUIADVIS    HSCDVIS. 
    HUIADHER    HSCDHER. 
    HUIADSPE    HSCDSPE. 
    HUIADMOB    HSCDMOB. 
    HUIADDEX    HSCDDEX. 
    HUIADEMO    HSCDEMO. 
    HUIADCOG    HSCDCOG. 
    HUIADPAD    HSCDPAD. 
    HUIADHSI    HUIDHSI. 
    WSTAFOPT    YESNOFM. 
    WSTA_401    AGREEFM. 
    WSTA_402    AGREEFM. 
    WSTA_403    AGREEFM. 
    WSTA_404    AGREEFM. 
    WSTA_405    AGREEFM. 
    WSTA_406    AGREEFM. 
    WSTA_407    AGREEFM. 
    WSTA_408    AGREEFM. 
    WSTA_409    AGREEFM. 
    WSTA_410    AGREEFM. 
    WSTA_411    AGREEFM. 
    WSTA_412    AGREEFM. 
    WSTA_413    WSTQ2FM. 
    WSTADALL    SCORE2D. 
    WSTADSKI    SCORE2D. 
    WSTADAUT    SCORE2D. 
    WSTADPSY    SCORE2D. 
    WSTADJIN    SCORE1D. 
    WSTADPHY    SCORE1D. 
    WSTADSOC    SCORE2D. 
    SFEAFOPT    YESNOFM. 
    SFEA_501    AGREEFM. 
    SFEA_502    AGREEFM. 
    SFEA_503    AGREEFM. 
    SFEA_504    AGREEFM. 
    SFEA_505    AGREEFM. 
    SFEA_506    AGREEFM. 
    SFEADE1     SCORE2D. 
    MASAFOPT    YESNOFM. 
    MASA_601    AGREEFM. 
    MASA_602    AGREEFM. 
    MASA_603    AGREEFM. 
    MASA_604    AGREEFM. 
    MASA_605    AGREEFM. 
    MASA_606    AGREEFM. 
    MASA_607    AGREEFM. 
    MASADM1     SCORE2D. 
    SMKA_200    YESNOFM. 
    SMKA_01A    YESNOFM. 
    SMKA_01B    YESNOFM. 
    SMKA_01C    AGE3DFM. 
    SMKA_202    SMC_2F.  
    SMKA_203    AGE3DFM. 
    SMKA_204    CIG_NUM. 
    SMKA_05B    DAY3DFM. 
    SMKA_05C    DAY2DFM. 
    SMKA_05D    YESNOFM. 
    SMKA_06A    SMK_LAST.
    SMKA_06B    MONTHFM. 
    SMKA_207    AGE3DFM. 
    SMKA_208    CIG_NUM. 
    SMKA_09A    SMK_LAST.
    SMKA_09B    MONTHFM. 
    SMKA_300    SMK_300F.
    SMKADSTY    SMCDTYP. 
    SMKADYCS    SMCDYRS. 
    SCAAFOPT    YESNOFM. 
    SCAA_1      YESNOFM. 
    SCAA_2      SCA_FM.  
    SCAA_3      YESNOFM. 
    SCAA_4      SCA_FM.  
    SCAA_5      YESNOFM. 
    SCAA_6      YESNOFM. 
    SCAA_7      YESNOFM. 
    SCAADQUI    SCA_QUI. 
    ETSA_1      YESNOFM. 
    ETSA_2A     YESNOFM. 
    ETSA_2B     YESNOFM. 
    ETSA_2C     YESNOFM. 
    ETSA_2D     YESNOFM. 
    ETSA_3      YESNOFM. 
    ETSA_4      YESNOFM. 
    ETSA_5      YESNOFM. 
    ETSA_6A     YESNOFM. 
    ETSA_6B     YESNOFM. 
    ETSA_6C     YESNOFM. 
    ETSA_6D     YESNOFM. 
    TALA_1      YESNOFM. 
    TALA_2      YESNOFM. 
    TALA_3      YESNOFM. 
    TALA_4      YESNOFM. 
    ALCA_1      YESNOFM. 
    ALCA_2      ALC6_2F. 
    ALCA_3      ALC_3F.  
    ALCA_5      YESNOFM. 
    ALCA_5A1    ALC_NUM. 
    ALCA_5A2    ALC_NUM. 
    ALCA_5A3    ALC_NUM. 
    ALCA_5A4    ALC_NUM. 
    ALCA_5A5    ALC_NUM. 
    ALCA_5A6    ALC_NUM. 
    ALCA_5A7    ALC_NUM. 
    ALCA_5B     YESNOFM. 
    ALCA_6      YESNOFM. 
    ALCA_7A     YESNOFM. 
    ALCA_7B     YESNOFM. 
    ALCA_7C     YESNOFM. 
    ALCA_7D     YESNOFM. 
    ALCA_7E     YESNOFM. 
    ALCA_7F     YESNOFM. 
    ALCA_7G     YESNOFM. 
    ALCA_7H     YESNOFM. 
    ALCA_7I     YESNOFM. 
    ALCA_7J     YESNOFM. 
    ALCA_7K     YESNOFM. 
    ALCA_7L     YESNOFM. 
    ALCA_7M     YESNOFM. 
    ALCA_8      AGE3DFM. 
    ALCADTYP    ALCDTYP. 
    ALCADWKY    ALC_NUM. 
    ALCADDLY    ALC_NUM. 
    DUIAFOPT    YESNOFM. 
    DUIA_1      YESNOFM. 
    DUIA_2      YESNOFM. 
    DUIA_3      TIMES3D. 
    DUIA_4      YESNOFM. 
    DUIA_5      YESNOFM. 
    DUIA_6      RSS_FREQ.
    ALDA_1      YESNOFM. 
    ALDA_2      AD_TIMES.
    ALDA_3      YESNOFM. 
    ALDA_4      YESNOFM. 
    ALDA_5      YESNOFM. 
    ALDA_6      YESNOFM. 
    ALDA_7      YESNOFM. 
    ALDA_8      AD_TIMES.
    ALDA_9      YESNOFM. 
    ALDADSF     AD_DSF.  
    ALDADPP     AD_DPP.  
    BRFA_01     YESNOFM. 
    BRFA_01A    YEARFM.  
    BRFA_01B    YESNOFM. 
    BRFA_02     YESNOFM. 
    BRFA_03     YESNOFM. 
    BRFA_04     GHP_26F. 
    BRFA_05     GHP_29F. 
    BRFA_10     YESNOFM. 
    BRFA_11     CIG_NUM. 
    BRFA_12     YESNOFM. 
    BRFA_13     CIG_NUM. 
    BRFA_14     YESNOFM. 
    BRFA_20     YESNOFM. 
    BRFA_21     ALC6_2F. 
    BRFA_22     YESNOFM. 
    BRFA_23     ALC6_2F. 
    SXBAFOPT    YESNOFM. 
    SXBA_1      YESNOFM. 
    SXBA_2      AGE3DFM. 
    SXBA_3      YESNOFM. 
    SXBA_4      SHS_4F.  
    SXBA_5      YESNOFM. 
    SXBA_6      YESNOFM. 
    SXBA_7      SHS_7F.  
    SXBA_7A     YESNOFM. 
    SSMAFOPT    YESNOFM. 
    SSMA_01     FR3DFM.  
    SSMA_02     MOSFM.   
    SSMA_03     MOSFM.   
    SSMA_04     MOSFM.   
    SSMA_05     MOSFM.   
    SSMA_06     MOSFM.   
    SSMA_07     MOSFM.   
    SSMA_08     MOSFM.   
    SSMA_09     MOSFM.   
    SSMA_10     MOSFM.   
    SSMA_11     MOSFM.   
    SSMA_12     MOSFM.   
    SSMA_13     MOSFM.   
    SSMA_14     MOSFM.   
    SSMA_15     MOSFM.   
    SSMA_16     MOSFM.   
    SSMA_17     MOSFM.   
    SSMA_18     MOSFM.   
    SSMA_19     MOSFM.   
    SSMA_20     MOSFM.   
    SSMADTNG    SSCORE2D.
    SSMADAFF    SSCORE2D.
    SSMADSOC    SSCORE2D.
    SSMADEMO    SSCORE2D.
    SPRAFOPT    YESNOFM. 
    SPRA_1      SSCFRQ1F.
    SPRA_2      YESNOFM. 
    SPRA_3      SSS_2F.  
    CMHA_01K    YESNOFM. 
    CMHA_01L    TIMES3D. 
    CMHA_1MA    YESNOFM. 
    CMHA_1MB    YESNOFM. 
    CMHA_1MC    YESNOFM. 
    CMHA_1MD    YESNOFM. 
    CMHA_1ME    YESNOFM. 
    CMHA_1MF    YESNOFM. 
    MDBAFOPT    YESNOFM. 
    MDBA_01     OFTEN2FM.
    MDBA_02     OFTEN2FM.
    MDBA_03     OFTEN2FM.
    MDBA_04     OFTEN2FM.
    MDBA_05     OFTEN2FM.
    MDBA_06     OFTEN2FM.
    MDBA_07     OFTEN2FM.
    MDBA_08     OFTEN2FM.
    MDBA_09     OFTEN2FM.
    MDBA_10     OFTEN2FM.
    MDBA_11     MDB_11F. 
    MDBADPOS    MDB_POS. 
    MDBADNEG    MDB_NEG. 
    MDBADBA1    MDB_1BA. 
    MDBADBA2    MDB_2BA. 
    DISAFOPT    YESNOFM. 
    DISA_01A    ALLTIMEF.
    DISA_01B    ALLTIMEF.
    DISA_01C    ALLTIMEF.
    DISA_01D    ALLTIMEF.
    DISA_01E    ALLTIMEF.
    DISA_01F    ALLTIMEF.
    DISA_01G    MHC_1G.  
    DISA_01H    MHCFRQ2F.
    DISA_01I    MHCFRQ2F.
    DISA_01J    MHC_1J.  
    DISADDS     MHCDDS.  
    DISADCH     MHCDCH.  
    DPSAFOPT    YESNOFM. 
    DPSA_02     YESNOFM. 
    DPSA_03     MHCLNGTH.
    DPSA_04     MHCNUM3F.
    DPSA_05     YESNOFM. 
    DPSA_06     YESNOFM. 
    DPSA_07     MHC_WGHT.
    DPSA_08A    KG3DFM.  
    DPSA_08B    WHTFM.   
    DPSA_09     YESNOFM. 
    DPSA_10     MHCFRQ1F.
    DPSA_11     YESNOFM. 
    DPSA_12     YESNOFM. 
    DPSA_13     YESNOFM. 
    DPSA_14     WEEKNUM. 
    DPSA_15     MONTHFM. 
    DPSA_16     YESNOFM. 
    DPSA_17     MHCLNGTH.
    DPSA_18     MHCNUM3F.
    DPSA_19     YESNOFM. 
    DPSA_20     MHC_WGHT.
    DPSA_21A    KG3DFM.  
    DPSA_21B    WHTFM.   
    DPSA_22     YESNOFM. 
    DPSA_23     MHCFRQ1F.
    DPSA_24     YESNOFM. 
    DPSA_25     YESNOFM. 
    DPSA_26     YESNOFM. 
    DPSA_27     WEEKNUM. 
    DPSA_28     MONTHFM. 
    DPSADSF     MHCDSF.  
    DPSADPP     DPS_DPP. 
    DPSADWK     MHCDWK.  
    DPSADMT     MONTHFM. 
    SUIAFOPT    YESNOFM. 
    SUIA_1      YESNOFM. 
    SUIA_2      YESNOFM. 
    SUIA_3      YESNOFM. 
    SUIA_4      YESNOFM. 
    SUIA_5      YESNOFM. 
    SUIA_6A     YESNOFM. 
    SUIA_6B     YESNOFM. 
    SUIA_6C     YESNOFM. 
    SUIA_6D     YESNOFM. 
    SUIA_6E     YESNOFM. 
    SUIA_6F     YESNOFM. 
    SDCA_1      SDC_1F.  
    SDCA_2      YESNOFM. 
    SDCA_3      SDYEARFM.
    SDCA_4A     YESNOFM. 
    SDCA_4B     YESNOFM. 
    SDCA_4C     YESNOFM. 
    SDCA_4D     YESNOFM. 
    SDCA_4E     YESNOFM. 
    SDCA_4F     YESNOFM. 
    SDCA_4G     YESNOFM. 
    SDCA_4H     YESNOFM. 
    SDCA_4I     YESNOFM. 
    SDCA_4J     YESNOFM. 
    SDCA_4K     YESNOFM. 
    SDCA_4L     YESNOFM. 
    SDCA_4M     YESNOFM. 
    SDCA_4N     YESNOFM. 
    SDCA_4O     YESNOFM. 
    SDCA_4P     YESNOFM. 
    SDCA_4Q     YESNOFM. 
    SDCA_4R     YESNOFM. 
    SDCA_4S     YESNOFM. 
    SDCA_5A     YESNOFM. 
    SDCA_5B     YESNOFM. 
    SDCA_5C     YESNOFM. 
    SDCA_5D     YESNOFM. 
    SDCA_5E     YESNOFM. 
    SDCA_5F     YESNOFM. 
    SDCA_5G     YESNOFM. 
    SDCA_5H     YESNOFM. 
    SDCA_5I     YESNOFM. 
    SDCA_5J     YESNOFM. 
    SDCA_5K     YESNOFM. 
    SDCA_5L     YESNOFM. 
    SDCA_5M     YESNOFM. 
    SDCA_5N     YESNOFM. 
    SDCA_5O     YESNOFM. 
    SDCA_5P     YESNOFM. 
    SDCA_5Q     YESNOFM. 
    SDCA_5R     YESNOFM. 
    SDCA_5S     YESNOFM. 
    SDCA_6A     YESNOFM. 
    SDCA_6B     YESNOFM. 
    SDCA_6C     YESNOFM. 
    SDCA_6D     YESNOFM. 
    SDCA_6E     YESNOFM. 
    SDCA_6F     YESNOFM. 
    SDCA_6G     YESNOFM. 
    SDCA_6H     YESNOFM. 
    SDCA_6I     YESNOFM. 
    SDCA_6J     YESNOFM. 
    SDCA_6K     YESNOFM. 
    SDCA_6L     YESNOFM. 
    SDCA_6M     YESNOFM. 
    SDCA_6N     YESNOFM. 
    SDCA_6O     YESNOFM. 
    SDCA_6P     YESNOFM. 
    SDCA_6Q     YESNOFM. 
    SDCA_6R     YESNOFM. 
    SDCA_6S     YESNOFM. 
    SDCA_7A     YESNOFM. 
    SDCA_7B     YESNOFM. 
    SDCA_7C     YESNOFM. 
    SDCA_7D     YESNOFM. 
    SDCA_7E     YESNOFM. 
    SDCA_7F     YESNOFM. 
    SDCA_7G     YESNOFM. 
    SDCA_7H     YESNOFM. 
    SDCA_7I     YESNOFM. 
    SDCA_7J     YESNOFM. 
    SDCA_7K     YESNOFM. 
    SDCA_7L     YESNOFM. 
    SDCA_7M     YESNOFM. 
    SDCA_8      YESNOFM. 
    SDCA_9      EDC2FM.  
    SDCACCB     SDC_CB.  
    SDCAGCB     SDGCB7FM.
    SDCADAIM    AGE3DFM. 
    SDCAFIMM    YESNOFM. 
    SDCADRES    AGE3DFM. 
    SDCADLNG    SDCDLNG. 
    SDCADRAC    SDC_RAC. 
    EDUA_1      EDUGRADE.
    EDUA_2      YESNOEDU.
    EDUA_3      YESNOEDU.
    EDUA_4      EDUDEGRE.
    EDUADR10    EDU_10DR.
    EDUADR04    DVED3FM. 
    EDUADH10    EDU_10DR.
    EDUADH04    DVED3FM. 
    DHHADHSZ    PERS2D.  
    DHHADL12    PERS2D.  
    DHHADLE5    PERS2D.  
    DHHAD611    PERS2D.  
    DHHADECF    DHCDECF. 
    DHHADLVG    DHCDLVG. 
    DHHADDWE    DHH_DWE. 
    DHHA_OWN    YESNOFM. 
    DHHA_MTG    YESNOFM. 
    DHHA_BED    BED_NUM. 
    LBFA_01     LSC_1F.  
    LBFA_02     YESNOFM. 
    LBFA_03     YESNOFM. 
    LBFA_11     YESNOFM. 
    LBFA_13     LSC_13F. 
    LBFA_21     YESNOFM. 
    LBFA_22     YESNOFM. 
    LBFA_23     YESNOFM. 
    LBFA_31     LSC_31F. 
    LBFA_31A    LBF_31F. 
    LBFA_35     SMS_12F. 
    LBFA_41     LSC_41F. 
    LBFA_42     HOUR5DFM.
    LBFA_43     LSC_43F. 
    LBFA_44     LSC_44F. 
    LBFA_45     LSC_45F. 
    LBFA_46     YESNOFM. 
    LBFA_51     WEEKNUM. 
    LBFA_52     LSC_52F. 
    LBFA_53     HOUR5DFM.
    LBFA_54     YESNOFM. 
    LBFA_61     WEEKNUM. 
    LBFA_71     WEEKNUM. 
    LBFA_72     YESNOFM. 
    LBFA_73     LSC_73F. 
    LBFA_74     LSC_74F. 
    LBFADWSS    LSCDCWS. 
    LBFADWSL    LSCDCWSL.
    LBFADRNW    LSCDRNW. 
    LBFADMJS    LBF_MJS. 
    LBFADHPW    LSCDHPW. 
    LBFADPFT    LBF_PFT. 
    LBFADJST    LSCDJST. 
    LBFADSTU    LBFDSWS. 
    INCAFDN     YESNOFM. 
    INCA_1A     YESNOFM. 
    INCA_1B     YESNOFM. 
    INCA_1C     YESNOFM. 
    INCA_1D     YESNOFM. 
    INCA_1E     YESNOFM. 
    INCA_1F     YESNOFM. 
    INCA_1G     YESNOFM. 
    INCA_1H     YESNOFM. 
    INCA_1I     YESNOFM. 
    INCA_1J     YESNOFM. 
    INCA_1K     YESNOFM. 
    INCA_1L     YESNOFM. 
    INCA_1M     YESNOFM. 
    INCA_1N     YESNOFM. 
    INCA_2      INC8_2F. 
    INCA_3      DOLL6FM. 
    INCA_3A     INC_3A.  
    INCA_3B     INC_3B.  
    INCA_3C     INC_3C.  
    INCA_3D     INC_3D.  
    INCA_3E     INC_3E.  
    INCA_3F     INC_3F.  
    INCA_3G     INC_3G.  
    INCA_4      DOLL6FM. 
    INCA_4A     INC_3A.  
    INCA_4B     INC_3B.  
    INCA_4C     INC_3C.  
    INCA_4D     INC_3D.  
    INCA_4E     INC_3E.  
    INCA_4F     INC_3F.  
    INCA_4G     INC_3G.  
    INCADIA2    INCIA2F. 
    INCADIA4    INCIA4F. 
    INCADIA5    INCIA5F. 
    INCADHH     INCDHH.  
    INCADPER    INCDHH.  
    FINAFDN     YESNOFM. 
    FINA_1      OFTEN2FM.
    FINA_2      OFTEN2FM.
    FINA_3      OFTEN2FM.
    FINAF1      YESNOFM. 
    SATA_11     YESNOFM. 
    SATA_12     GOOD4FM. 
    SATA_13     SATQ3FM. 
    SATA_21A    YESNOFM. 
    SATA_21B    SAT_21BF.
    SATA_22     GOOD4FM. 
    SATA_23     SATQ3FM. 
    SATA_31A    YESNOFM. 
    SATA_31B    SAT_31BF.
    SATA_32     GOOD4FM. 
    SATA_33     SATQ3FM. 
    SATA_41     YESNOFM. 
    SATA_42     GOOD4FM. 
    SATA_43     SATQ3FM. 
    ADMAFFE     YESNOFM. 
    ADMA_PH     ADM_PH.  
    GEOA_HR    $ADM_6HR. 
                       ;
