VARIABLE LABELS                                                                
    SAMPLEID 'Identificateur du ménage'                                         
    PERSONID 'ID - pers. selectionné pour l''int. C2'                           
    GEOA_PRV 'Province'                                                         
    GEOA_HR4 'Région socio-sanitaire (4)'                                       
    GEOA_PC  'Code postal'                                                      
    GEOADEA  'Secteur de dénombrement - (D)'                                    
    GEOADFED 'Circonscription électoale féd. - (D)'                             
    GEOADCSD 'Subdivision de recensement - (D)'                                 
    GEOADCD  'Division de recensement - (D)'                                    
    GEOADCMA 'Région Métropolitaine du Recensement (D)'                         
    GEOADPRG 'Groupe de rég. soc.-san.homologues - (D)'                         
    GEOADUR2 'Région rurale et urbaine - 2 niveaux (D)'                         
    GEOADUR5 'Région rurale et urbaine - 5 niveaux (D)'                         
    GEOADAB  'Région soc.-san. - Alberta seulement (D)'                         
    GEOADON  'Région soc.-san. - Ontario seulement (D)'                         
    GEOADPE  'Région soc.-san. - PEI seulement - (D)'                           
    SAMA_TYP 'Type d''échantillon'                                              
    SAMA_CP  'Période de collecte de l''échantillon'                            
    SAMAFQ4  'Indicateur de 4ième quart'                                        
    SAMADNUM 'Nombre de répondants C2 - ménage - (D)'                           
    ADMA_ENT 'ID - pers. fournissant l''inf. du ménage'                         
    ADMA_PRX 'C2 complété par procuration'                                      
    ADMA_IMP 'Code d''imputation'                                               
    ADMA_DAT 'Date à laquelle l''interview C2 a eu lieu'                        
    ADMA_STA 'État de réponse après traitement'                                 
    SAMADSHR 'Permission de partager les données - (D)'                         
    SAMADLNK 'Permission de jumeler les données - (D)'                          
    ADMA_N09 'Interview au téléphone/en face à face'                            
    ADMA_N10 'Répondant seul durant l''interview'                               
    ADMA_N11 'Réponses biais./présence autre personne'                          
    ADMA_LHH 'Langue de préférence - int. du ménage'                            
    ADMA_N12 'Langue de l''interview'                                           
    DHHA_AGE 'Âge'                                                              
    DHHA_DB  'Date de naissance'                                                
    DHHA_SEX 'Sexe'                                                             
    DHHA_MS  'État matrimonial'                                                 
    GENA_01  'Évaluation personnelle de la santé'                               
    GENA_02  'Eval. pers. de la santé - l''an dern.'                            
    GENA_03  'Nbre/heures passer à dormir chaque nuit'                          
    GENA_04  'Fréq. - problèmes à s''endormir'                                  
    GENA_05  'Fréq. - sommeil est réparateur'                                   
    GENA_06  'Fréq. - difficulté à rester éveillé'                              
    GENA_07  'Évaluation personnelle du stress'                                 
    GENA_08  'A travaillé au cours des 12 dern. mois'                           
    GENA_09  'Éval. pers. - stress au travail'                                  
    GENA_10  'Sentiment d''appartenance - comm. locale'                         
    GENADHDI 'Indice de la description de santé - (D)'                          
    CIHAFOPT 'Ind mod. opt. - changement/amél/la santé'                         
    CIHA_1   'A fait quelque chose - améliorer santé'                           
    CIHA_2   'Changement plus imp. - améliorer santé'                           
    CIHA_3   'Doit faire quelque chose - amél. santé'                           
    CIHA_4   'Chose la plus imp. à faire - amél. santé'                         
    CIHA_5   'Barrière qui empêche l''amél. de la santé'                        
    CIHA_6A  'Rais./aucune amél. - manque de volonté'                           
    CIHA_6B  'Rais./aucune amél. - manque de temps'                             
    CIHA_6C  'Rais./aucune amél. - trop fatigué'                                
    CIHA_6D  'Rais./aucune amél. - trop difficile'                              
    CIHA_6E  'Rais./aucune amél. - trop coûteux'                                
    CIHA_6F  'Rais./aucune amél. - trop stressant'                              
    CIHA_6G  'Rais./aucune amél. - incap./probl. santé'                         
    CIHA_6H  'Rais./aucune amél. - autre'                                       
    CIHA_7   'Intention d''amél. santé/prochaine année'                         
    CIHA_8A  'Amél. santé/proch. année - + d''exercices'                        
    CIHA_8B  'Amél. santé/proch. année - perdre poids'                          
    CIHA_8C  'Amél. santé/proch. année - changer alim.'                         
    CIHA_8D  'Amél. santé/proch. année - cesser fumer'                          
    CIHA_8E  'Amél. santé/proch. année - réduire/tabac'                         
    CIHA_8F  'Amél. santé/proch. année - gérer stress'                          
    CIHA_8G  'Amél. santé/proch. année - réd. stress'                           
    CIHA_8H  'Amél. santé/proch. année - prendre vit.'                          
    CIHA_8I  'Amél. santé/proch. année - autre'                                 
    HWTA_2   'Taille'                                                           
    HWTA_2A  'Taille - hauteur exacte de 1''0" à 1''11"'                        
    HWTA_2B  'Taille - hauteur exacte de 2''0" à 2''11"'                        
    HWTA_2C  'Taille - hauteur exacte de 3''0" à 3''11"'                        
    HWTA_2D  'Taille - hauteur exacte de 4''0" à 4''11"'                        
    HWTA_2E  'Taille - hauteur exacte de 5''0" à 5''11"'                        
    HWTA_2F  'Taille - hauteur exacte de 6''0" à 6''11"'                        
    HWTA_3   'Poids'                                                            
    HWTA_N4  'Poids en livres/en kilogrammes'                                   
    HWTA_4   'Opinion du répondant à propos/son poids'                          
    HWTADHTM 'Taille - mètres (D)'                                              
    HWTADHTI 'Taille - pouces (D)'                                              
    HWTADWTK 'Poids - kilogrammes (D)'                                          
    HWTADWTP 'Poids - livres (D)'                                               
    HWTADBMI 'Indice de la masse corporelle - (D)'                              
    HWTADSW  'Poids standard - (D)'                                             
    TWDA_1   'Alité - à cause de maladie/de blessure'                           
    TWDA_2   'Alité - nombre de jours'                                          
    TWDA_3   'A limité d''activités - maladie/blessure'                         
    TWDA_4   'A limité d''activités - nombre de jours'                          
    TWDA_5   'A un médecin de famille'                                          
    TWDADDDY 'Nombre de jours d''incapacité - (D)'                              
    HCUA_01  'A passé la nuit comme patient'                                    
    HCUA_01A 'Nombre de nuits comme patient'                                    
    HCUA_02A 'Nbre de consult. - médecin fam./omnipr.'                          
    HCUA_03A 'Lieu/plus récente cons. - méd. de fam.'                           
    HCUA_02B 'Nbre de consult. - spécialiste de la vue'                         
    HCUA_02C 'Nbre de consultations - autre médecin'                            
    HCUA_03C 'Lieu/plus récente cons. - autre médecin'                          
    HCUA_02D 'Nbre de consult. - infirmière'                                    
    HCUA_03D 'Lieu/plus récente cons. - infirmière'                             
    HCUA_02E 'Nbre de consult. - dentiste/orthod.'                              
    HCUA_02F 'Nbre de consult. - chiropraticien'                                
    HCUA_02G 'Nbre de consult. - physiothérapeute'                              
    HCUA_02H 'Nbre de consult. - trav.social/cons.'                             
    HCUA_02I 'Nbre de consult. - psychologue'                                   
    HCUA_02J 'Nbre de consult. - orthoph./audiol./erg.'                         
    HCUA_04A 'A participé à un groupe d''entraide'                              
    HCUA_04  'A consulté/intervenant en médecine douce'                         
    HCUA_05A 'Soins alternatifs - massothérapeute'                              
    HCUA_05B 'Soins alternatifs - acupuncteur'                                  
    HCUA_05C 'Soins alternatifs - homéopathe/naturop.'                          
    HCUA_05D 'Soins alternatifs - Feldenkrais/Alexand.'                         
    HCUA_05E 'Soins alternatifs - relaxologue'                                  
    HCUA_05F 'Soins alternatifs - rétroaction biol.'                            
    HCUA_05G 'Soins alternatifs - «rolfer»'                                     
    HCUA_05H 'Soins alternatifs - herboriste'                                   
    HCUA_05I 'Soins alternatifs - réflexologiste'                               
    HCUA_05J 'Soins alternatifs - guérisseur spirituel'                         
    HCUA_05K 'Soins alternatifs - guérisseur religieux'                         
    HCUA_05L 'Soins alternatifs - autre'                                        
    HCUA_06  'Besoin non satisfaits'                                            
    HCUA_07A 'Soins non obtenus - non disp./la région'                          
    HCUA_07B 'Soins non obtenus - non disp./requis'                             
    HCUA_07C 'Soins non obtenus - délai trop long'                              
    HCUA_07D 'Soins non obtenus - consid. comme inad.'                          
    HCUA_07E 'Soins non obtenus - coût'                                         
    HCUA_07F 'Soins non obtenus - trop occupé'                                  
    HCUA_07G 'Soins non obtenus - s''en est pas occupé'                         
    HCUA_07H 'Soins non obtenus - ne savait pas où'                             
    HCUA_07I 'Soins non obtenus - probl. de transport'                          
    HCUA_07J 'Soins non obtenus - problème de langue'                           
    HCUA_07K 'Soins non obtenus - resp. pers./fam'                              
    HCUA_07L 'Soins non obtenus - aversion méd./peur'                           
    HCUA_07M 'Soins non obtenus- décidé ne pas soigner'                         
    HCUA_07N 'Soins non obtenus - autre raison'                                 
    HCUA_08A 'Genre/soins non obt. - problème physique'                         
    HCUA_08B 'Genre/soins non obt. - probl. ém./mental'                         
    HCUA_08C 'Genre/soins non obt. - examen périodique'                         
    HCUA_08D 'Genre/soins non obt. - blessure'                                  
    HCUA_08E 'Genre/soins non obt. - autre'                                     
    HCUADMDC 'Nbre de consultations/médecins - (D)'                             
    HCUAFHPC 'Consultation avec prof. de la santé (F)'                          
    HMCAFOPT 'Indicateur module opt - service/domicile'                         
    HMCA_09  'A reçu des services à domicile'                                   
    HMCA_10A 'Soins domicile reçus - soins infirmiers'                          
    HMCA_10B 'Soins domicile reçus - autres soins'                              
    HMCA_10C 'Soins domicile reçus - hygiène pers.'                             
    HMCA_10D 'Soins domicile reçus - travaux ménagers'                          
    HMCA_10E 'Soins domicile reçus - prép./livr. repas'                         
    HMCA_10F 'Soins domicile reçus - magasinage'                                
    HMCA_10G 'Soins domicile reçus - serv. de relève'                           
    HMCA_10H 'Soins domicile reçus - autre genre'                               
    RACA_1   'A de la difficulté à faire des activités'                         
    RACA_2A  'Reduit - activités - maison'                                      
    RACA_2B  'Reduit - activités - travail / école'                             
    RACA_2C  'Reduit - activités - autres activités'                            
    RACA_5   'Cause du problème de santé'                                       
    RACA_6A  'A besoin de l''aide - préparer les repas'                         
    RACA_6B  'A besoin d''aide - faire les courses'                             
    RACA_6C  'A besoin d''aide - accomplir tâches mén.'                         
    RACA_6D  'A besoin d''aide - faire gros trav./entr.'                        
    RACA_6E  'A besoin d''aide - des soins personnels'                          
    RACA_6F  'A besoin d''aide - se déplac.dans maison'                         
    RACADIMP 'Répercussion des problèmes de santé (D)'                          
    RACAF6   'A besoin de l''aide (F)'                                          
    CCCA_011 'A des allergies alimentaires'                                     
    CCCA_012 'Allergies aliment.- âge/1er diagnostic'                           
    CCCA_021 'A des allergies autres qu''alimentaires'                          
    CCCA_022 'Allergies aliment.- âge/1er diagnostic'                           
    CCCA_031 'Fait de l''asthme'                                                
    CCCA_032 'Asthme - âge/1er diagnostic'                                      
    CCCA_035 'Asthme - a eu des symptômes/des crises'                           
    CCCA_036 'Asthme - a pris des médicaments'                                  
    CCCA_041 'Souffre de fibromyalgie'                                          
    CCCA_042 'Fibromyalgie - âge/1er diagnostic'                                
    CCCA_051 'Souffre d''arthrite/de rhumatisme'                                
    CCCA_052 'Arthr./rhum. - âge/1er diagnostic'                                
    CCCA_05A 'Arthr./rhum. - genre'                                             
    CCCA_061 'Maux de dos autres/fibromyalgie & arthr.'                         
    CCCA_062 'Maux de dos - âge/1er diagnostic'                                 
    CCCA_071 'Fait de l''hypertension'                                          
    CCCA_072 'Hypertension - âge/1er diagnostic'                                
    CCCA_081 'A des migraines'                                                  
    CCCA_082 'Migraines - âge/1er diagnostic'                                   
    CCCA_91A 'Est atteint de bronchite chronique'                               
    CCCA_92A 'Bronchite chronique - âge/1er diagnostic'                         
    CCCA_91B 'Souffre d''emph./bronchopn. chron. obstr.'                        
    CCCA_92B 'Emphysème ou BPCO - âge/1er diagnostic'                           
    CCCA_101 'Est atteint du diabète'                                           
    CCCA_102 'Diabète - âge/1er diagnostic'                                     
    CCCA_10A 'Diabète diagnostic - durant grossesse'                            
    CCCA_10B 'Diabète diagnostic - autre qu''enceinte'                          
    CCCA_10C 'Diabète diagnostic - commencé insuline'                           
    CCCA_105 'Diabète - prend/insuline actuellement'                            
    CCCA_111 'Est atteint d''épilepsie'                                         
    CCCA_112 'Épilepsie - âge/1er diagnostic'                                   
    CCCA_121 'Souffre d''une maladie cardiaque'                                 
    CCCA_122 'Maladie cardiaque - âge/1er diagnostic'                           
    CCCA_12A 'Maladie cardiaque - déjà fait une crise'                          
    CCCA_12J 'Maladie cardiaque - souffre d''angine'                            
    CCCA_12K 'Maladie cardiaque - souffre/insuffisance'                         
    CCCA_131 'Souffre d''un cancer'                                             
    CCCA_132 'Cancer - âge/1er diagnostic'                                      
    CCCA_13A 'Type/cancer  - sein'                                              
    CCCA_13B 'Type/cancer  - prostate'                                          
    CCCA_13C 'Type/cancer  - côlon et rectum'                                   
    CCCA_13D 'Type/cancer  - peau (mélanome)'                                   
    CCCA_13E 'Type/cancer  - peau (sans mélanome)'                              
    CCCA_13F 'Type/cancer  - Autre'                                             
    CCCA_141 'Souffre d''ulcères à l''estomac/intestin'                         
    CCCA_142 'Ulcères - âge/1er diagnostic'                                     
    CCCA_151 'Est atteint/troubles dus acc. vasc. cér.'                         
    CCCA_152 'Accident vasc. cér.-âge/1er diagnostic'                           
    CCCA_161 'Est atteint d''incontinence urinaire'                             
    CCCA_162 'Incont. urinaire - âge/1er diagnostic'                            
    CCCA_171 'Atteint de troubles intest.-Crohn/colite'                         
    CCCA_172 'Crohn/colite - âge/1er diagnostic'                                
    CCCA_181 'Est atteint d''Alzh./autre démence cér.'                          
    CCCA_182 'Alzh./autre dém. - âge/1er diagnostic'                            
    CCCA_191 'Est atteint de cataracte'                                         
    CCCA_192 'Cataracte - âge/1er diagnostic'                                   
    CCCA_201 'Est atteint de glaucome'                                          
    CCCA_202 'Glaucome - âge/1er diagnostic'                                    
    CCCA_211 'Est atteint d''un problème de la thyroïde'                        
    CCCA_212 'Probl./thyroïde - âge/1er diagnostic'                             
    CCCA_231 'Souffre de la maladie de Parkinson'                               
    CCCA_232 'Maladie/Parkinson - âge/1er diagnostic'                           
    CCCA_241 'Souffre de sclérose en plaques'                                   
    CCCA_242 'Sclérose en plaques - âge/1er diagnostic'                         
    CCCA_251 'Souffre du syndrome de fatigue chronique'                         
    CCCA_252 'Syndrome fatigue chron. - âge/1er diagn.'                         
    CCCA_261 'Souffre/sensibilités aux agress. chimiq.'                         
    CCCA_262 'Sensibilité/agr.chim. - âge/1er diagn.'                           
    CCCA_221 'Est atteint/autre probl. de santé chron.'                         
    CCCAF1   'A un problème de santé chroniques - (F)'                          
    CCCADTOT 'Nbre problèmes de santé chroniques - (D)'                         
    DRGAFOPT 'Indicateur module opt - Cons/médicaments'                         
    DRGA_1A  'Médicament - analgésiques'                                        
    DRGA_1B  'Médicament - tranquillisants'                                     
    DRGA_1C  'Médicament - pilules pour maigrir'                                
    DRGA_1D  'Médicament - antidépresseurs'                                     
    DRGA_1E  'Médicament - codéine/Demerol/morphine'                            
    DRGA_1F  'Médicament - contre les allergies'                                
    DRGA_1G  'Médicament - contre l''asthme'                                    
    DRGA_1H  'Médicament - remèdes contre toux/rhume'                           
    DRGA_1I  'Médicament - pénicilline/autres antib.'                           
    DRGA_1J  'Médicament - coeur'                                               
    DRGA_1K  'Médicament - tension artérielle'                                  
    DRGA_1L  'Médicament - diurétiques'                                         
    DRGA_1M  'Médicament - stéroïdes'                                           
    DRGA_1N  'Médicament - insuline'                                            
    DRGA_1O  'Médicament - pilules/contrôler diabète'                           
    DRGA_1P  'Médicament - somnifères'                                          
    DRGA_1Q  'Médicament - maux d''estomac'                                     
    DRGA_1R  'Médicament - laxatifs'                                            
    DRGA_1S  'Médicament - pilules contraceptives'                              
    DRGA_1T  'Médicament - hormones pour la ménopause'                          
    DRGA_1T1 'Hormonothérapie - type'                                           
    DRGA_1T2 'Hormonothérapie commencée - année'                                
    DRGA_1U  'Médicament - thyroïde'                                            
    DRGA_1V  'Médicament - autre'                                               
    DRGAF1   'médicament au cours du dernier mois'                              
    BPCA_010 'Déjà fait prendre sa tension artérielle'                          
    BPCA_012 'Dernière fois/tension artér. a été prise'                         
    BPCA_16A 'Tens. art. pas prise - n''a pu s''en occ.'                        
    BPCA_16B 'Tens. art. pas prise - pas nécess./rép.'                          
    BPCA_16C 'Tens. art. pas prise - pas nécess./méd.'                          
    BPCA_16D 'Tens. art. pas prise - resp. pers./fam.'                          
    BPCA_16E 'Tens. art. pas prise - non disp./requis'                          
    BPCA_16F 'Tens. art. pas prise - non disp./région'                          
    BPCA_16G 'Tens. art. pas prise - délai trop long'                           
    BPCA_16H 'Tens. art. pas prise - probl. transport'                          
    BPCA_16I 'Tens. art. pas prise - probl. de langue'                          
    BPCA_16J 'Tens. art. pas prise - coût'                                      
    BPCA_16K 'Tens. art. pas prise - ne savait pas où'                          
    BPCA_16L 'Tens. art. pas prise - peur'                                      
    BPCA_16M 'Tens. art. pas prise - autre raison'                              
    PAPA_020 'A déjà passé un test PAP'                                         
    PAPA_022 'Dernière fois qu''un test PAP a été passé'                        
    PAPA_26A 'Aucun PAP - pas eu l''occ. de s''en occ.'                         
    PAPA_26B 'Aucun PAP - pas nécess. selon répondante'                         
    PAPA_26C 'Aucun PAP - pas nécess. selon médecin'                            
    PAPA_26D 'Aucun PAP - responsabilités pers./fam.'                           
    PAPA_26E 'Aucun PAP - non disp. lorsque requis'                             
    PAPA_26F 'Aucun PAP - non disp. dans la région'                             
    PAPA_26G 'Aucun PAP - délai trop long'                                      
    PAPA_26H 'Aucun PAP - problèmes de transport'                               
    PAPA_26I 'Aucun PAP - problème de langue'                                   
    PAPA_26J 'Aucun PAP - coût'                                                 
    PAPA_26K 'Aucun PAP - ne savait pas où aller'                               
    PAPA_26L 'Aucun PAP - peur'                                                 
    PAPA_26M 'Aucun PAP - hystérectomie'                                        
    PAPA_26N 'Aucun PAP - n''aime pas se soum./au test'                         
    PAPA_26O 'Aucun PAP - autre raison'                                         
    MAMA_30  'A déjà passé une mammographie'                                    
    MAMA_31A 'A passé mamm. - antécédents familiaux'                            
    MAMA_31B 'A passé mamm. - examen régulier'                                  
    MAMA_31C 'A passé mamm. - âge'                                              
    MAMA_31D 'A passé mamm. - masse dépistée auparav.'                          
    MAMA_31E 'A passé mamm. - suivi d''un traitement'                           
    MAMA_31F 'A passé mamm. - en hormonothérapie'                               
    MAMA_31G 'A passé mamm. - problème mammaire'                                
    MAMA_31H 'A passé mamm. - autre raison'                                     
    MAMA_32  'Dern. fois - mammographie a été passée'                           
    MAMA_36A 'Aucune mamm. - pas eu occ./s''en occuper'                         
    MAMA_36B 'Aucune mammo. - pas nécess. selon rép.'                           
    MAMA_36C 'Aucune mammo. - pas nécess. selon méd.'                           
    MAMA_36D 'Aucune mammo. - resp. pers./familiales'                           
    MAMA_36E 'Aucune mamm. - non disp. lorsque requis'                          
    MAMA_36F 'Aucune mamm. - non disp. dans la région'                          
    MAMA_36G 'Aucune mamm. - délai d''attente trop long'                        
    MAMA_36H 'Aucune mamm. - problèmes de transport'                            
    MAMA_36I 'Aucune mamm. - problème de langue'                                
    MAMA_36J 'Aucune mamm. - coût'                                              
    MAMA_36K 'Aucune mamm. - ne savait pas où aller'                            
    MAMA_36L 'Aucune mamm. - peur'                                              
    MAMA_36M 'Aucune mamm. - autre raison'                                      
    MAMA_37  'Enceinte actuellement'                                            
    MAMA_38  'A subi une hystérectomie'                                         
    BRXAFOPT 'indicateur module opt - examen des seins'                         
    BRXA_110 'A eu examen des seins/profess. de santé'                          
    BRXA_112 'Dernière fois a eu un examen des seins'                           
    BRXA_16A 'Aucun ex./seins - pas eu occ./occuper'                            
    BRXA_16B 'Aucun ex./seins-pas nécess./répondante'                           
    BRXA_16C 'Aucun ex./seins - pas nécessaire/médecin'                         
    BRXA_16D 'Aucun ex./seins - resp. pers./familiales'                         
    BRXA_16E 'Aucun ex./seins - non disp./quand besoin'                         
    BRXA_16F 'Aucun ex./seins - non disp./dans région'                          
    BRXA_16G 'Aucun ex./seins - délai trop long'                                
    BRXA_16H 'Aucun ex./seins - problèmes de transport'                         
    BRXA_16I 'Aucun ex./seins - problème de langue'                             
    BRXA_16J 'Aucun ex./seins - coût'                                           
    BRXA_16K 'Aucun ex./seins - ne savait pas où aller'                         
    BRXA_16L 'Aucun ex./seins - peur'                                           
    BRXA_16M 'Aucun ex./seins - autre raison'                                   
    BSXAFOPT 'indicateur mod opt - auto-examen / seins'                         
    BSXA_120 'A auto-examiné seins pour masse anormale'                         
    BSXA_121 'Fréq./auto-examinatation des seins'                               
    BSXA_22A 'Auto-ex./seins a été appris - médecin'                            
    BSXA_22B 'Auto-ex./seins a été appris - infirmière'                         
    BSXA_22C 'Auto-ex./seins a été appris - livre, etc'                         
    BSXA_22D 'Auto-ex./seins a été appris - TV, etc'                            
    BSXA_22E 'Auto-ex./seins a été appris - mère'                               
    BSXA_22F 'Auto-ex./seins a été appris - soeur'                              
    BSXA_22G 'Auto-ex./seins a été appris - autre'                              
    DENAFOPT 'indicateur module opt - visite/dentiste'                          
    DENA_130 'A visité un dentiste - 12 derniers mois'                          
    DENA_132 'Dernière visite à un dentiste'                                    
    DENA_36A 'Aucune vis. dent. - pas l''occ./s''en occ.'                       
    DENA_36B 'Aucune visite dent. - pas néc./répondant'                         
    DENA_36C 'Aucune visite dent. - pas néc./dentiste'                          
    DENA_36D 'Aucune visite dent. - resp. pers./fam.'                           
    DENA_36E 'Aucune visite dent. - non disp./requis'                           
    DENA_36F 'Aucune visite dent. - non disp./région'                           
    DENA_36G 'Aucune visite dent. - délai trop long'                            
    DENA_36H 'Aucune visite dent. - probl./transport'                           
    DENA_36I 'Aucune visite dent. - problème de langue'                         
    DENA_36J 'Aucune visite dent. - coût'                                       
    DENA_36K 'Aucune visite dent. - ne savait pas où'                           
    DENA_36L 'Aucune visite dent. - peur'                                       
    DENA_36M 'Aucune visite dent. - porte un dentier'                           
    DENA_36N 'Aucune visite dent. - autre raison'                               
    EYXAFOPT 'indicateur module opt - examens / vue'                            
    EYXA_140 'A rendu visite - optométriste/ophtalm.'                           
    EYXA_142 'Dernier examen de la vue'                                         
    EYXA_46A 'Aucun examen/vue - pas occasion/occuper'                          
    EYXA_46B 'Aucun examen/vue - pas nécess./répondant'                         
    EYXA_46C 'Aucun examen/vue - pas nécess./médecin'                           
    EYXA_46D 'Aucun examen/vue - respons. pers./fam'                            
    EYXA_46E 'Aucun examen/vue - non disponible/requis'                         
    EYXA_46F 'Aucun examen/vue - non disponible/région'                         
    EYXA_46G 'Aucun examen/vue - délai trop long'                               
    EYXA_46H 'Aucun examen/vue - probl. de transport'                           
    EYXA_46I 'Aucun examen/vue - problème de langue'                            
    EYXA_46J 'Aucun examen/vue - coût'                                          
    EYXA_46K 'Aucun examen/vue - ne savait pas où'                              
    EYXA_46L 'Aucun examen/vue - peur'                                          
    EYXA_46M 'Aucun examen/vue - autre raison'                                  
    PCUAFOPT 'Indicateur module opt. - Examen général'                          
    PCUA_150 'Ex. général sans avoir problème de santé'                         
    PCUA_151 'Ex. gén. lors consult./probl. de santé'                           
    PCUA_152 'Examen général - la dernière fois'                                
    PCUA_56A 'Aucun ex. gén. - pas eu l''occ./s''en occ.'                       
    PCUA_56B 'Aucun ex. gén. - pas nécess./répondant'                           
    PCUA_56C 'Aucun ex. gén. - pas nécessaire/médecin'                          
    PCUA_56D 'Aucun ex. gén. - resp. pers./familiales'                          
    PCUA_56E 'Aucun ex. gén. - non disp./lors besoin'                           
    PCUA_56F 'Aucun ex. gén. - non disponible/région'                           
    PCUA_56G 'Aucun ex. gén. - délai trop long'                                 
    PCUA_56H 'Aucun ex. gén. - problèmes de transport'                          
    PCUA_56I 'Aucun ex. gén. - problème de langue'                              
    PCUA_56J 'Aucun ex. gén. - coût'                                            
    PCUA_56K 'Aucun ex. gén. - ne savait pas où aller'                          
    PCUA_56L 'Aucun examen gén. - peur'                                         
    PCUA_56M 'Aucun examen gén. - autre raison'                                 
    FLUAFOPT 'indicateur module opt - vaccins / grippe'                         
    FLUA_160 'A déjà reçu un vaccin contre la grippe'                           
    FLUA_162 'Dernière fois/reçu vaccin contre lgrippe'                         
    FLUA_66A 'Aucun vacc. - pas eu l''occasion'                                 
    FLUA_66B 'Aucun vacc. - pas néc./répondant'                                 
    FLUA_66C 'Aucun vacc. - pas néc./médecin'                                   
    FLUA_66D 'Aucun vacc. - resp. pers./fam.'                                   
    FLUA_66E 'Aucun vacc. - non disp./requis'                                   
    FLUA_66F 'Aucun vacc. - non disp./région'                                   
    FLUA_66G 'Aucun vacc. - délai trop long'                                    
    FLUA_66H 'Aucun vacc. - probl. de transp.'                                  
    FLUA_66I 'Aucun vacc. - problème de langue'                                 
    FLUA_66J 'Aucun vacc. - coût'                                               
    FLUA_66K 'Aucun vacc. - ne savait pas où aller'                             
    FLUA_66L 'Aucun vacc. - peur'                                               
    FLUA_66M 'Aucun vacc. - mauvaise réaction'                                  
    FLUA_66N 'Aucun vacc. - autre raison'                                       
    PSAA_170 'A déjà subi le test de sang PSA'                                  
    PSAA_172 'Dernière fois qu''il a subi le test PSA'                          
    PSAA_73A 'Raison/PSA - antécédents familiaux'                               
    PSAA_73B 'Raison/PSA - examen régulier/dépistage'                           
    PSAA_73C 'Raison/PSA - âge'                                                 
    PSAA_73D 'Raison/PSA - suivi/problème antérieur'                            
    PSAA_73E 'Raison/PSA - suivi/trait./cancer/prost.'                          
    PSAA_73F 'Raison/PSA - autre'                                               
    FVCA_1A  'Boire jus de fruits - unité de reportage'                         
    FVCA_1B  'Boire jus de fruits - nbre de fois/jour'                          
    FVCA_1C  'Boire jus de fruits - nbre de fois/sem.'                          
    FVCA_1D  'Boire jus de fruits - nbre de fois/mois'                          
    FVCA_1E  'Boire jus de fruits - nbre de fois/année'                         
    FVCA_2A  'Mange des fruits - unité de reportage'                            
    FVCA_2B  'Mange des fruits - nbre de fois/jour'                             
    FVCA_2C  'Mange des fruits - nbre de fois/sem.'                             
    FVCA_2D  'Mange des fruits - nbre de fois/mois'                             
    FVCA_2E  'Mange des fruits - nbre de fois/année'                            
    FVCA_3A  'Mange/salade verte - unité de reportage'                          
    FVCA_3B  'Mange/salade verte - nbre de fois/jour'                           
    FVCA_3C  'Mange/salade verte - nbre de fois/sem.'                           
    FVCA_3D  'Mange/salade verte - nbre de fois/mois'                           
    FVCA_3E  'Mange/salade verte - nbre de fois/année'                          
    FVCA_4A  'Mange/pom. de terre - unité de reportage'                         
    FVCA_4B  'Mange/pom. de terre - nbre de fois/jour'                          
    FVCA_4C  'Mange/pom. de terre - nbre de fois/sem.'                          
    FVCA_4D  'Mange/pom. de terre - nbre de fois/mois'                          
    FVCA_4E  'Mange/pom. de terre - nbre de fois/année'                         
    FVCA_5A  'Mange/carottes - unité de reportage'                              
    FVCA_5B  'Mange/carottes - nbre de fois/jour'                               
    FVCA_5C  'Mange/carottes - nbre de fois/sem.'                               
    FVCA_5D  'Mange/carottes - nbre de fois/mois'                               
    FVCA_5E  'Mange/carottes - nbre de fois/année'                              
    FVCA_6A  'Mange/autres légumes - unité de. report.'                         
    FVCA_6B  'Mange/autres légumes - portions/jour'                             
    FVCA_6C  'Mange/autres légumes - portions/sem.'                             
    FVCA_6D  'Mange/autres légumes - portions/mois'                             
    FVCA_6E  'Mange/autres légumes - portions/année'                            
    FVCADJUI 'Cons. quotidienne - jus de fruits (D)'                            
    FVCADFRU 'Cons. quotidienne - fruits (D)'                                   
    FVCADSAL 'Cons. quotidienne - salade verte (D)'                             
    FVCADPOT 'Cons. quotidienne - pommes de terre (D)'                          
    FVCADCAR 'Consommation quotidienne - carottes (D)'                          
    FVCADVEG 'Cons. quotidienne - autres légumes (D)'                           
    FVCADTOT 'Cons. Quoti. - total fruits et lég. (D)'                          
    FVCAGTOT 'Cons. Quoti. - total fruits et lég. (G)'                          
    PACA_1A  'Act./3 dern. mois - marche'                                       
    PACA_1B  'Act./3 dern. mois - jardinage/trav. ext.'                         
    PACA_1C  'Act./3 dern. mois - natation'                                     
    PACA_1D  'Act./3 dern. mois - bicyclette'                                   
    PACA_1E  'Act./3 dern. mois - danse mod./sociale'                           
    PACA_1F  'Act./3 dern. mois - exerc. à la maison'                           
    PACA_1G  'Act./3 dern. mois - hockey sur glace'                             
    PACA_1H  'Act./3 dern. mois - patinage sur glace'                           
    PACA_1I  'Act./3 dern. mois - patin à roues align.'                         
    PACA_1J  'Act./3 dern. mois - jogging/course'                               
    PACA_1K  'Act./3 dern. mois - golf'                                         
    PACA_1L  'Act./3 dern. mois - class d''ex. ou aero.'                        
    PACA_1M  'Act./3 dern. mois - ski/planche à neige'                          
    PACA_1N  'Act./3 dern. mois - quilles'                                      
    PACA_1O  'Act./3 dern. mois - baseball/balle molle'                         
    PACA_1P  'Act./3 dern. mois - tennis'                                       
    PACA_1Q  'Act./3 dern. mois - poids/haltères'                               
    PACA_1R  'Act./3 dern. mois - pêche'                                        
    PACA_1S  'Act./3 dern. mois - volleyball'                                   
    PACA_1T  'Act./3 dern. mois - ballon panier'                                
    PACA_1U  'Act./3 dern. mois - autre (#1)'                                   
    PACA_1V  'Activité / 3 derniers mois - aucune act.'                         
    PACA_1W  'Act./3 dern. mois - autre (#2)'                                   
    PACA_1X  'Act./3 dern. mois - autre (#3)'                                   
    PACA_2A  'Nbre de fois participé - marche/exercice'                         
    PACA_3A  'Temps consacré - marche pour l''exercice'                         
    PACA_2B  'Nbre de fois participé - jardinage'                               
    PACA_3B  'Temps consacré - jardinage'                                       
    PACA_2C  'Nbre de fois participé - natation'                                
    PACA_3C  'Temps consacré - natation'                                        
    PACA_2D  'Nbre de fois participé - bicyclette'                              
    PACA_3D  'Temps consacré - bicyclette'                                      
    PACA_2E  'Nbre de fois participé - danse mod./soc.'                         
    PACA_3E  'Temps consacré - danse moderne/sociale'                           
    PACA_2F  'Nbre de fois participé - ex. à la maison'                         
    PACA_3F  'Temps consacré - exercices à la maison'                           
    PACA_2G  'Nbre de fois participé - hockey/glace'                            
    PACA_3G  'Temps consacré - hockey sur glace'                                
    PACA_2H  'Nbre de fois participé - patinage/glace'                          
    PACA_3H  'Temps consacré - patinage sur glace'                              
    PACA_2I  'Nbre de fois part - patin à roues aligné'                         
    PACA_3I  'Temps consacré - patin à roues alignées'                          
    PACA_2J  'Nbre de fois participé - jogging/course'                          
    PACA_3J  'Temps consacré - jogging/course'                                  
    PACA_2K  'Nbre de fois participé - golf'                                    
    PACA_3K  'Temps consacré - golf'                                            
    PACA_2L  'Nbre de fois participé - class d''ex/aero'                        
    PACA_3L  'Temps consacré - exercices dir./aérobie'                          
    PACA_2M  'Nbre de fois - ski alpin/planche à neige'                         
    PACA_3M  'Temps cons. - ski alpin/planche à neige'                          
    PACA_2N  'Nbre de fois participé - quilles'                                 
    PACA_3N  'Temps consacré - quilles'                                         
    PACA_2O  'Nbre fois partic. - baseball/balle molle'                         
    PACA_3O  'Temps consacré - baseball/balle molle'                            
    PACA_2P  'Nbre de fois participé - tennis'                                  
    PACA_3P  'Temps consacré - tennis'                                          
    PACA_2Q  'Nbre de fois participé - poids/haltères'                          
    PACA_3Q  'Temps consacré - poids et haltères'                               
    PACA_2R  'Nbre de fois participé - pêche'                                   
    PACA_3R  'Temps consacré - pêche'                                           
    PACA_2S  'Nbre de fois participé - volleyball'                              
    PACA_3S  'Temps consacré - volleyball'                                      
    PACA_2T  'Nbre de fois participé - ballon panier'                           
    PACA_3T  'Temps consacré - ballon panier'                                   
    PACA_2U  'Nbre de fois participé - autre act. (#1)'                         
    PACA_3U  'Temps consacré - autre activité (#1)'                             
    PACA_2W  'Nbre de fois participé - autre act. (#2)'                         
    PACA_3W  'Temps consacré - autre activité (#2)'                             
    PACA_2X  'Nbre de fois participé - autre act. (#3)'                         
    PACA_3X  'Temps consacré - autre activité (#3)'                             
    PACA_4A  'Nbre heures - marcher rendre trav./école'                         
    PACA_4B  'Nbre heures - bicycl./aller trav./école'                          
    PACA_6   'Niveau d''activité physique quotidien'                            
    PACADEE  'Dépense d''énergie - (D)'                                         
    PACAFLEI 'Part. à activités de loisirs - > 15 min.'                         
    PACADFM  'Fréq. mens./act. phys. > 15 min. - (D)'                           
    PACADFR  'Fréquence - toutes act. physiques - (D)'                          
    PACAFD   'Participation act. Phys - > 15 min.'                              
    PACADPAI 'Indice de l''activité physique - (D)'                             
    SACAFOPT 'Indicateur de module opt - Act. séd.'                             
    SACA_1   'Heures passées - à l''ordinateur'                                 
    SACA_2   'Heures passées - à jouer des jeux vidéo'                          
    SACA_3   'Heures passées - regarder la télé/vidéos'                         
    SACA_4   'Heures passées - à lire'                                          
    SACADTOT 'Heures passées - act. séd. - (D)'                                 
    UPEAFOPT 'Indicateur module opt - Util/précautions'                         
    UPEA_101 'Fréq./porte un casque en vélo'                                    
    UPEA_02A 'Fréq./porte un casque en patin'                                   
    UPEA_02B 'Fréq./porte des protège-poignets'                                 
    UPEA_02C 'Fréq./porte des coudières'                                        
    UPEA_02D 'Fréq./porte des genouillères'                                     
    UPEA_103 'Fréq./porte un casque en ski/planche'                             
    REPA_1   'Blessure - mouvements répétitifs'                                 
    REPA_3   'Partie du corps atteinte/mouv. répétit.'                          
    REPA_4A  'Répétitifs/act. - sports/ex. phys.'                               
    REPA_4B  'Répétitifs/act. - loisirs/passe-temps'                            
    REPA_4C  'Répétitifs/act. - travail rémunéré'                               
    REPA_4D  'Répétitifs/act. - tâches mén., trav. n-r'                         
    REPA_4E  'Répétitifs/act. - sommeil/repas/s. pers.'                         
    REPA_4F  'Répétitifs/act. - autre'                                          
    INJA_01  'Blessé au cours des 12 derniers mois'                             
    INJA_02  'Nombre de blessures'                                              
    INJA_03  'Blessure  - mois'                                                 
    INJA_04  'Blessure - année'                                                 
    INJA_05  'Blessure - genre'                                                 
    INJA_06  'Blessure - partie du corps atteinte'                              
    INJA_07  'Blessure - partie du corps (org. int.)'                           
    INJA_08  'Blessure - lieu'                                                  
    INJA_09  'Blessure - activité'                                              
    INJA_10  'Blessure - chute'                                                 
    INJA_11  'Blessure - manière chute se produit'                              
    INJA_12  'Blessure - cause'                                                 
    INJA_13  'Blessure - a été soigné/48 heures'                                
    INJA_14A 'Blessure traité - bureau du méd.'                                 
    INJA_14B 'Blessure traité - salle d''urgence/hôp.'                          
    INJA_14C 'Blessure traité - clinique externe'                               
    INJA_14D 'Blessure traité - cl. sans rendez-vous'                           
    INJA_14E 'Blessure traité - cl. avec rendez-vous'                           
    INJA_14F 'Blessure traité - CLSC'                                           
    INJA_14G 'Blessure traité - au travail'                                     
    INJA_14H 'Blessure traité - à l''école'                                     
    INJA_14I 'Blessure traité - à la maison'                                    
    INJA_14J 'Blessure traité - consult. tél. uniq.'                            
    INJA_14K 'Blessure traité - autre'                                          
    INJA_15  'Blessure - admis à l''hôpital'                                    
    INJA_16  'Autres blessure - pas limités activités'                          
    INJA_17  'Autres blessures - nombre'                                        
    INJADTBS 'Genre de blessure/partie du corps - (D)'                          
    INJADCAU 'Cause de la blessure - (D)'                                       
    INJADCBP 'Cause de la blessure/lieu d''évén. - (D)'                         
    INJADSTT 'État de la blessure - (D)'                                        
    HUIA_01  'Vision - lire sans lun./verr. cont.'                              
    HUIA_02  'Vision - lire avec lun./verr. cont.'                              
    HUIA_03  'Vision - capable de voir'                                         
    HUIA_04  'Vision - reconnaître ami sans lun./cont.'                         
    HUIA_05  'Vision - reconnaître ami avec lun./cont.'                         
    HUIA_06  'Ouïe - dans un groupe sans prothèse aud.'                         
    HUIA_07  'Ouïe - dans groupe avec prothèse aud.'                            
    HUIA_07A 'Ouïe - capable d''entendre'                                       
    HUIA_08  'Ouïe - dans pièce sil. sans proth. aud.'                          
    HUIA_09  'Ouïe - dans pièce sil. avec proth. aud.'                          
    HUIA_10  'Élocution - parfaitement compris(e)/inc.'                         
    HUIA_11  'Élocution - partiellement compris/inc.'                           
    HUIA_12  'Élocution - parfaitement compris/n-inc.'                          
    HUIA_13  'Élocution - partiellement compris/n-inc.'                         
    HUIA_14  'Mobilité - marche sans diff./sans supp.'                          
    HUIA_15  'Mobilité - capable de marcher'                                    
    HUIA_16  'Mobilité - a besoin un appareil/marcher'                          
    HUIA_17  'Mobilité - a besoin d''aide/pers./marcher'                        
    HUIA_18  'Mobilité - a besoin/fauteuil roulant'                             
    HUIA_19  'Mobilité - fréq. d''util./fauteuil roul.'                         
    HUIA_20  'Mobilité - a bes. aide/dépl./faut. roul.'                         
    HUIA_21  'Dext. - cap. saisir & manip. petits obj.'                         
    HUIA_22  'Dext. - a besoin aide/limitations mains'                          
    HUIA_23  'Dext. - a besoin d''aide avec des tâches'                         
    HUIA_24  'Dext. - a besoin équip. sp./limit. mains'                         
    HUIA_25  'Émotion - évaluation personnelle'                                 
    HUIA_26  'Cognition - capacité/de se souvenir'                              
    HUIA_27  'Cognition - cap./pens. & résoudre probl.'                         
    HUIA_28  'Hab. sans douleurs et malaises'                                   
    HUIA_29  'Douleurs/malaises - intensité habituel'                           
    HUIA_30  'Douleurs/malaises - # activités empêch.'                          
    HUIADVIS 'Code fonct. - troubles/vision - (D)'                              
    HUIADHER 'Code fonct. - troubles/ouïe - (D)'                                
    HUIADSPE 'Code fonct.- troubles/élocution - (D)'                            
    HUIADMOB 'Code fonct. - troubles/mobilité - (D)'                            
    HUIADDEX 'Code fonct. - troubles/dextérité - (D)'                           
    HUIADEMO 'Code fonct. - troubles émotifs - (D)'                             
    HUIADCOG 'Code fonct. - troubles/cognition - (D)'                           
    HUIADPAD 'Code fonct. - act. empêch./douleur - (D)'                         
    HUIADHSI 'Indice de l''état de la santé(HUI3) - (D)'                        
    WSTAFOPT 'indicateur module opt - stress / travail'                         
    WSTA_401 'Stress/travail - doit aquir/connaissance'                         
    WSTA_402 'Stress/travail - niveau élevé/compétence'                         
    WSTA_403 'Stress/travail - liberté de décider'                              
    WSTA_404 'Stress/travail - tâches répétitives'                              
    WSTA_405 'Stress/travail - tâches répétitives'                              
    WSTA_406 'Stress/travail - exempt/demandes oppos.'                          
    WSTA_407 'Stress/travail - bonne sécurité d''emploi'                        
    WSTA_408 'Stress/travail - exige beauc./eff. phys.'                         
    WSTA_409 'Stress/travail - a pouvoir/son travail'                           
    WSTA_410 'Stress/travail - host./confl./collègues'                          
    WSTA_411 'Stress/travail - surv. facilite/travail'                          
    WSTA_412 'Stress/travail - coll. facilit./travail'                          
    WSTA_413 'Stress/travail - satisfait/son travail'                           
    WSTADALL 'Stress/travail - tous les items - (D)'                            
    WSTADSKI 'Stress/trav.: compétence - (D)'                                   
    WSTADAUT 'Stress/trav.: - autorité - (D)'                                   
    WSTADPSY 'Stress/trav.: demandes psycholog. - (D)'                          
    WSTADJIN 'Stress/trav.: insécurité d''emploi - (D)'                         
    WSTADPHY 'Stress/trav.: effort physique - (D)'                              
    WSTADSOC 'Stress/trav.: Soutien social - (D)'                               
    SFEAFOPT 'indicateur module opt. - Estime de soi'                           
    SFEA_501 'Estime de soi - bonne'                                            
    SFEA_502 'Estime de soi - digne'                                            
    SFEA_503 'Estime de soi - capable'                                          
    SFEA_504 'Estime de soi - positive'                                         
    SFEA_505 'Estime de soi - satisfait'                                        
    SFEA_506 'Estime de soi - un raté'                                          
    SFEADE1  'Échelle de l''estime de soi - (D)'                                
    MASAFOPT 'Indicateur module optionnel - Contrôle'                           
    MASA_601 'Contrôle - peu de contrôle'                                       
    MASA_602 'Contrôle - ne peut rés. probl.'                                   
    MASA_603 'Contrôle - ne peut changer choses'                                
    MASA_604 'Contrôle - impuissant'                                            
    MASA_605 'Contrôle - malmené'                                               
    MASA_606 'Contrôle - destin dépend/soi-même'                                
    MASA_607 'Contrôle - peut tout faire'                                       
    MASADM1  'Échelle de maîtrise - (D)'                                        
    SMKA_200 'Membre du mén. fume hab. dans la maison'                          
    SMKA_01A 'A fumé >=100 cigarettes - durant sa vie'                          
    SMKA_01B 'Déjà fumé toute une cigarette'                                    
    SMKA_01C 'Âge - a fumé première cigarette entière'                          
    SMKA_202 'Type de fumeur'                                                   
    SMKA_203 'Âge - a commencé à fumer tous les jours'                          
    SMKA_204 '# cigarettes par jour - (fum. reg.)'                              
    SMKA_05B '# cig. par jour (fumeur occasionnel)'                             
    SMKA_05C '# jours - a fumé 1 cigarette ou plus'                             
    SMKA_05D 'A déjà fumé des cig. tous les jours'                              
    SMKA_06A 'Cessé de fumer - quand (jam. fum. rég.)'                          
    SMKA_06B 'Cessé de fumer - mois (jam. fum rég.)'                            
    SMKA_207 'Âge - a commencé à fumer tous les jours'                          
    SMKA_208 '# cigarettes par jour (anc. fum. reg.)'                           
    SMKA_09A 'Cessé de fumer quot. - quand'                                     
    SMKA_09B 'Cessé de fumer quot. - mois'                                      
    SMKA_300 'Cigarettes - comment obtenu'                                      
    SMKADSTY 'Genre de fumeur - (D)'                                            
    SMKADYCS 'Nbre d''années que répondant a fumé - (D)'                        
    SCAAFOPT 'Ind. module opt. - Outils/cesser/fumer'                           
    SCAA_1   'A utilisé un timbre à la nicotine'                                
    SCAA_2   'Utilité du timbre à la nicotine'                                  
    SCAA_3   'A utilisé - gomme/bonbons à la nicotine'                          
    SCAA_4   'Utilité - gomme/bonbons à la nicotine'                            
    SCAA_5   'A essayé d''arrêter de fumer'                                     
    SCAA_6   'A essayé d''arrêter- timbre à la nicotine'                        
    SCAA_7   'A essayé d''arrêter- gomme/bonbons'                               
    SCAADQUI 'Tentative de cesser de fumer - (D)'                               
    ETSA_1   'Fumée secondaire - la plupart des jours'                          
    ETSA_2A  'Fumée secondaire - à la maison'                                   
    ETSA_2B  'Fumée secondaire - automobile'                                    
    ETSA_2C  'Fumée secondaire - lieux publics'                                 
    ETSA_2D  'Fumée secondaire - visite amis/parents'                           
    ETSA_3   'Fumée cig. - dérange'                                             
    ETSA_4   'Fumée cig. - cause irritation physique'                           
    ETSA_5   'Restrictions - fumer à domicile'                                  
    ETSA_6A  'Restrictions - pas permis'                                        
    ETSA_6B  'Restrictions - permis / certaines pièces'                         
    ETSA_6C  'Restrictions - interdit / jeunes enfants'                         
    ETSA_6D  'Restrictions - autre'                                             
    TALA_1   'A fumé le cigare'                                                 
    TALA_2   'A fumé la pipe'                                                   
    TALA_3   'A utilisé du tabac à priser'                                      
    TALA_4   'A utilisé du tabac à chiquer'                                     
    ALCA_1   'A bu de l''alc. au cours/12 derniers mois'                        
    ALCA_2   'Fréquence de consommation d''alcool'                              
    ALCA_3   'Fréq. de consommation de 5 + verres'                              
    ALCA_5   'A bu de l''alc. durant la semaine écoulée'                        
    ALCA_5A1 'Nombre de verres bus - Dimanche'                                  
    ALCA_5A2 'Nombre de verres bus - Lundi'                                     
    ALCA_5A3 'Nombre de verres bus - Mardi'                                     
    ALCA_5A4 'Nombre de verres bus - Mercredi'                                  
    ALCA_5A5 'Nombre de verres bus - Jeudi'                                     
    ALCA_5A6 'Nombre de verres bus - Vendredi'                                  
    ALCA_5A7 'Nombre de verres bus - Samedi'                                    
    ALCA_5B  'A déjà pris un verre d''alcool'                                   
    ALCA_6   'Consommé rég. > 12 verres d''alc./semaine'                        
    ALCA_7A  'Raison/dim. boire - régime'                                       
    ALCA_7B  'Raison/dim. boire - entraînement sportif'                         
    ALCA_7C  'Raison/dim. boire - grossesse'                                    
    ALCA_7D  'Raison/dim. boire - a vieilli'                                    
    ALCA_7E  'Raison/dim. boire - buvait trop'                                  
    ALCA_7F  'Raison/dim. boire - nuit travail/études'                          
    ALCA_7G  'Raison/dim. boire - nuit/vie famillle'                            
    ALCA_7H  'Raison/dim. boire - nuit/santé physique'                          
    ALCA_7I  'Raison/dim. boire - nuit/vie sociale'                             
    ALCA_7J  'Raison/dim. boire - nuit situat. financ.'                         
    ALCA_7K  'Raison/dim. boire - nuit au bonheur'                              
    ALCA_7L  'Raison/dim. boire - influence fam./amis'                          
    ALCA_7M  'Raison/dim. de boire - autre'                                     
    ALCA_8   'Âge qu''a commencé à boire de l''alcool'                          
    ALCADTYP 'Genre de buveur - (D)'                                            
    ALCADWKY 'Nmbre. verres d''alcool - s. passé - (D)'                         
    ALCADDLY 'Quant. moy. de cons. d''alc./jour - (D)'                          
    DUIAFOPT 'Indicateur module opt - Cond/cons d''alc'                         
    DUIA_1   'Passager avec conducteur ivre'                                    
    DUIA_2   'A un permis de conduire valide'                                   
    DUIA_3   'Nombre de fois qu''a conduit ivre'                                
    DUIA_4   'Sort/va dans endroits où consomme alcool'                         
    DUIA_5   'Arrange pour avoir un conducteur désigné'                         
    DUIA_6   'Arrange/avoir cond. désigné -  fréq.'                             
    ALDA_1   'Soûl - travail/école/prenant soin enfant'                         
    ALDA_2   'Nbre de fois - soûl/souffre excès d''alc.'                        
    ALDA_3   'Être soûl augmentait chances/se blesser'                          
    ALDA_4   'Diff. affectives/psychol. dues à l''alc.'                         
    ALDA_5   'Grand désir/besoin de consommer l''alcool'                        
    ALDA_6   'A passé un mois ou plus à s''enivrer'                             
    ALDA_7   'A bu beaucoup plus que prévu'                                     
    ALDA_8   'Nbre de fois  - bu beauc. plus que prévu'                         
    ALDA_9   'Devait boire plus/ressentir même effet'                           
    ALDADSF  'Dép. à l''alc. - marque/form. court - (D)'                        
    ALDADPP  'Dép. à l''alc. - probabilité prévue - (D)'                        
    BRFA_01  'A donné naissance/5 dernières années'                             
    BRFA_01A 'Année de naissance - dernier bébé'                                
    BRFA_01B 'L''acide folique - dernière grossesse'                            
    BRFA_02  'A allaité son enfant/a essayé d''allaiter'                        
    BRFA_03  'Allaite encore le dernier enfant'                                 
    BRFA_04  'Duré de l''allaitement du dernier enfant'                         
    BRFA_05  'Rais. principale - arrêter l''allaitement'                        
    BRFA_10  'A fumé durant la dernière grossesse'                              
    BRFA_11  'Nbre/cigarettes par jour/grosesse'                                
    BRFA_12  'A fumé pendant l''allaitement/dern. bébé'                         
    BRFA_13  'Nbre/cigarettes par jour/allaitement'                             
    BRFA_14  'Fumée sec. - durant/après grossesse'                              
    BRFA_20  'A bu de l''alc. pendant dern. grossesse'                          
    BRFA_21  'Fréq./consommation d''alcool/grossesse'                           
    BRFA_22  'A bu de l''alcool pendant l''allaitement'                         
    BRFA_23  'Fréq./consommation d''alcool/allaitement'                         
    SXBAFOPT 'Indicateur module opt - Comport. Sexuel'                          
    SXBA_1   'A déjà eu des rapports sexuels'                                   
    SXBA_2   'Âge des premiers rapports sexuels'                                
    SXBA_3   'A eu des rapports sexuels/12 dern. mois'                          
    SXBA_4   'Nbre de part. différents (rapports sex.)'                         
    SXBA_5   'Relation a duré 12 mois ou plus'                                  
    SXBA_6   'Relations qui ont duré moins de 12 mois'                          
    SXBA_7   'Util. de condom/relation(s) durant <1 an'                         
    SXBA_7A  'A utilisé un condom la dernière fois'                             
    SSMAFOPT 'Indicateur module opt - Soutien social'                           
    SSMA_01  'Nombre de parents/d''amis proches'                                
    SSMA_02  'A quelqu''un - aider/si doit garder lit'                          
    SSMA_03  'A quelqu''un - pout l''écouter et parler'                         
    SSMA_04  'A quelqu''un - conseille en sit. de crise'                        
    SSMA_05  'A quelqu''un - pour aller chez le médecin'                        
    SSMA_06  'A quelqu''un - témoigne amour/affection'                          
    SSMA_07  'A quelqu''un - à qui part. du bon temps'                          
    SSMA_08  'A quelqu''un - rens. afin de compr. sit.'                         
    SSMA_09  'A un confident'                                                   
    SSMA_10  'A quelqu''un qui serre dans ses bras'                             
    SSMA_11  'A quelqu''un avec qui se détendre'                                
    SSMA_12  'A quelqu''un pour préparer les repas'                             
    SSMA_13  'A quelqu''un qui donne des conseils'                              
    SSMA_14  'A quelqu''un avec qui faire act. distray.'                        
    SSMA_15  'A quelqu''un/aider/tâches mén. si malade'                         
    SSMA_16  'A quelqu''un/confier inquiét./peurs +int.'                        
    SSMA_17  'A quelqu''un/qui dem. sugg./probl. pers.'                         
    SSMA_18  'A quelqu''un/faire des choses agréables'                          
    SSMA_19  'A quelqu''un qui comprend les problèmes'                          
    SSMA_20  'A quelqu''un/aime/donne sent. d''être dés.'                       
    SSMADTNG 'Support social tangible - EIM - (D)'                              
    SSMADAFF 'Affection - sous-échelle EIM - (D)'                               
    SSMADSOC 'Interaction sociale positive - EIM - (D)'                         
    SSMADEMO 'Support émot./inf.- sous-échelle EIM-(D)'                         
    SPRAFOPT 'Indicateur module opt - Spiritualité'                             
    SPRA_1   'Fréquence - assiste service religieux'                            
    SPRA_2   'Valeurs spirituelles ou foi - importance'                         
    SPRA_3   'Spiritualité - évaluation personnelle'                            
    CMHA_01K 'A consulté profess. de la santé mentale'                          
    CMHA_01L 'Fréq./consulte un professionnel de santé'                         
    CMHA_1MA 'Santé mentale, consulté - méd./famille'                           
    CMHA_1MB 'Santé mentale, consulté - psychiatre'                             
    CMHA_1MC 'Santé mentale, consulté - psychologue'                            
    CMHA_1MD 'Santé mentale, consulté - infirmière'                             
    CMHA_1ME 'Santé mentale, consulté - trav. social'                           
    CMHA_1MF 'Santé mentale, consulté - autre'                                  
    MDBAFOPT 'Indicateur module optionnel - Humeur'                             
    MDBA_01  'Fréq./sentr le plus heureux au monde'                             
    MDBA_02  'Fréq./senti très seul/isolé des gens'                             
    MDBA_03  'Fréq./senti partic. emballé/intéressé'                            
    MDBA_04  'Fréq./senti déprimé ou très malheureux'                           
    MDBA_05  'Fréq./heureux/avoir accompli q''que chose'                        
    MDBA_06  'Fréq./senti ennuyé'                                               
    MDBA_07  'Fréq./senti fier'                                                 
    MDBA_08  'Fréq./senti agité'                                                
    MDBA_09  'Fréq./senti que tout va à merveille'                              
    MDBA_10  'Fréq./senti troublé quand on critique'                            
    MDBA_11  'Bonheur - évaluation personnelle'                                 
    MDBADPOS 'Équilibre affectif - humeur positive (D)'                         
    MDBADNEG 'Équilibre affectif - humeur négative (D)'                         
    MDBADBA1 'Équilibre affectif - méthode A (D)'                               
    MDBADBA2 'Équilibre affectif - méthode B (D)'                               
    DISAFOPT 'Indicateur module optionnel - Détresse'                           
    DISA_01A 'Fréq. - senti triste'                                             
    DISA_01B 'Fréq. - senti nerveux'                                            
    DISA_01C 'Fréq. - senti agité/tenait pas en place'                          
    DISA_01D 'Fréq. - senti désespéré'                                          
    DISA_01E 'Fréq. - senti bon à rien'                                         
    DISA_01F 'Fréq. - senti que tout était un effort'                           
    DISA_01G 'Fréq. - éprouve sentiments'                                       
    DISA_01H 'Fréq. - éprouve sentiments (plus)'                                
    DISA_01I 'Fréq. - éprouve sentiments (moins)'                               
    DISA_01J 'Fréq. - les sentiments perturbent la vie'                         
    DISADDS  'Échelle de détresse - (D)'                                        
    DISADCH  'Échelle chronic. détresse affaibl. - (D)'                         
    DPSAFOPT 'indicateur module optionnel - Dépression'                         
    DPSA_02  'Senti déprimé >=2 sem. dur. dern. année'                          
    DPSA_03  'Dépr. - durée habit. de ces sentiments'                           
    DPSA_04  'Dépr. - nombre fois/éprouve sentiments'                           
    DPSA_05  'Dépr. - perdu intérêt - plupart choses'                           
    DPSA_06  'Dépr. - éprouvait toujours de la fatigue'                         
    DPSA_07  'Dépr. - poids change ou non'                                      
    DPSA_08A 'Dépr. - poids change (montant)'                                   
    DPSA_08B 'Déprimé - poids change (lb./kg.)'                                 
    DPSA_09  'Dépr. - difficulté à trouver le sommeil'                          
    DPSA_10  'Dépr. - fréq./diff. à trouver sommeil'                            
    DPSA_11  'Dépr. - difficulté à se concentrer'                               
    DPSA_12  'Dépr. - senti parfois abattu'                                     
    DPSA_13  'Dépr. - a beaucoup songé à la mort'                               
    DPSA_14  'Dépr. - nbre de sem./cours 12 dern. mois'                         
    DPSA_15  'Mois durant lequel dépr. est survenue'                            
    DPSA_16  'Perdu intérêt - plupart choses aimait'                            
    DPSA_17  'Perte d''intérêt - durée'                                         
    DPSA_18  'Perte d''intérêt - fréquence'                                     
    DPSA_19  'Perte d''intérêt - toujours fatigué'                              
    DPSA_20  'Perte d''intérêt - poids change ou non'                           
    DPSA_21A 'Perte d''intérêt - poids change (montant)'                        
    DPSA_21B 'Perte d''intérêt - poids change (lb./kg.)'                        
    DPSA_22  'Perte d''intérêt - diff. trouver sommeil'                         
    DPSA_23  'Perte d''intérêt - fréq. diff./sommeil'                           
    DPSA_24  'Perte d''intérêt - diff. à se concentrer'                         
    DPSA_25  'Perte d''intérêt - senti parfois abattu'                          
    DPSA_26  'Perte d''intérêt - songé beauc. - la mort'                        
    DPSA_27  'Perte d''intérêt - nombre de semaines'                            
    DPSA_28  'Perte d''intérêt - mois le plus récent'                           
    DPSADSF  'Échelle/dépr. - marque/form. court - (D)'                         
    DPSADPP  'Échelle/dépr. - probabilité prévue - (D)'                         
    DPSADWK  'Nombre/sem. s''est senti déprimé - (D)'                           
    DPSADMT  'Mois spécif. - s''est senti déprimé - (D)'                        
    SUIAFOPT 'Indicateur module optionnel - Suicide'                            
    SUIA_1   'A songé au suicide / vie'                                         
    SUIA_2   'A songé au suicide / 12 dern. mois'                               
    SUIA_3   'A tenté de se suicider / vie'                                     
    SUIA_4   'A tenté de se suicider/12 derniers mois'                          
    SUIA_5   'A consulté prof. santé après tentative'                           
    SUIA_6A  'A consulté médecin de famille/omnipr.'                            
    SUIA_6B  'A consulté psychiatre'                                            
    SUIA_6C  'A consulté psychologue'                                           
    SUIA_6D  'A consulté infirmière'                                            
    SUIA_6E  'A consulté trav. social/conseiller'                               
    SUIA_6F  'A consulté autre'                                                 
    SDCA_1   'Pays de naissance'                                                
    SDCA_2   'Citoyen canadien de naissance'                                    
    SDCA_3   'Année de l''immigration au Canada'                                
    SDCA_4A  'Origine ethnique - canadien'                                      
    SDCA_4B  'Origine ethnique - français'                                      
    SDCA_4C  'Origine ethnique - anglais'                                       
    SDCA_4D  'Origine ethnique - allemand'                                      
    SDCA_4E  'Origine ethnique - écossais'                                      
    SDCA_4F  'Origine ethnique - irlandais'                                     
    SDCA_4G  'Origine ethnique - italien'                                       
    SDCA_4H  'Origine ethnique - ukrainien'                                     
    SDCA_4I  'Origine ethnique - hollandais (néerl.)'                           
    SDCA_4J  'Origine ethnique - chinois'                                       
    SDCA_4K  'Origine ethnique - juif'                                          
    SDCA_4L  'Origine ethnique - polonais'                                      
    SDCA_4M  'Origine ethnique - portugais'                                     
    SDCA_4N  'Origine ethnique - asiatique du sud'                              
    SDCA_4O  'Origine ethnique - noir'                                          
    SDCA_4P  'Origine ethnique - indien/amérique-nord'                          
    SDCA_4Q  'Origine ethnique - métis'                                         
    SDCA_4R  'Origine ethnique - inuit/esquimau'                                
    SDCA_4S  'Origine ethnique - autre'                                         
    SDCA_5A  'Peut converser - anglais'                                         
    SDCA_5B  'Peut converser - français'                                        
    SDCA_5C  'Peut converser - arabe'                                           
    SDCA_5D  'Peut converser - chinois'                                         
    SDCA_5E  'Peut converser - cri'                                             
    SDCA_5F  'Peut converser - allemand'                                        
    SDCA_5G  'Peut converser - grec'                                            
    SDCA_5H  'Peut converser - hongrois'                                        
    SDCA_5I  'Peut converser - italien'                                         
    SDCA_5J  'Peut converser - coréen'                                          
    SDCA_5K  'Peut converser - persan (farsi)'                                  
    SDCA_5L  'Peut converser - polonais'                                        
    SDCA_5M  'Peut converser - portugais'                                       
    SDCA_5N  'Peut converser - pendjabi'                                        
    SDCA_5O  'Peut converser - espagnol'                                        
    SDCA_5P  'Peut converser - tagal (philippin)'                               
    SDCA_5Q  'Peut converser - ukrainien'                                       
    SDCA_5R  'Peut converser - vietnamien'                                      
    SDCA_5S  'Peut converser - autre langue'                                    
    SDCA_6A  'Prem. lang. appr./touj. compr.- anglais'                          
    SDCA_6B  'Prem. lang. appr./touj. compr.- français'                         
    SDCA_6C  'Prem. lang. appr./touj. compr. - arabe'                           
    SDCA_6D  'Prem. lang. appr./touj. compr.- chinois'                          
    SDCA_6E  'Prem. lang. appr./touj. compr. - cri'                             
    SDCA_6F  'Prem. lang. appr./touj. compr.- allemand'                         
    SDCA_6G  'Prem. lang. appr./touj. compr. - grec'                            
    SDCA_6H  'Prem. lang. appr./touj. compr.- hongrois'                         
    SDCA_6I  'Prem. lang. appr./touj. compr.- italien'                          
    SDCA_6J  'Prem. lang. appr./touj. compr. - coréen'                          
    SDCA_6K  'Prem. lang. appr./touj. compr. - persan'                          
    SDCA_6L  'Prem. lang. appr./touj. compr.- polonais'                         
    SDCA_6M  'Prem. lang. appr./touj. compr.-portugais'                         
    SDCA_6N  'Prem. lang. appr./touj. compr.- pendjabi'                         
    SDCA_6O  'Prem. lang. appr./touj. compr.- espagnol'                         
    SDCA_6P  'Prem. lang. appr./touj. compr. - tagal'                           
    SDCA_6Q  'Prem. lang. appr./touj. compr.-ukrainien'                         
    SDCA_6R  'Prem. lang. appr./touj. compr.-vietnam.'                          
    SDCA_6S  'Prem. lang. appr./touj. compr. - autre'                           
    SDCA_7A  'Orig. cult./raciales - blanc'                                     
    SDCA_7B  'Orig. cult./raciales - chinois'                                   
    SDCA_7C  'Orig. cult./raciales - asiatique du sud'                          
    SDCA_7D  'Orig. cult./raciales - noir'                                      
    SDCA_7E  'Orig. cult./raciales - philippin'                                 
    SDCA_7F  'Orig. cult./raciales - latino-américain'                          
    SDCA_7G  'Orig. cult./raciales - asiat. du sud-est'                         
    SDCA_7H  'Orig. cult./raciales - arabe'                                     
    SDCA_7I  'Orig. cult./raciales - asiatique occid.'                          
    SDCA_7J  'Orig. cult./raciales - japonais'                                  
    SDCA_7K  'Orig. cult./raciales - coréen'                                    
    SDCA_7L  'Orig. cult./raciales - autochtone'                                
    SDCA_7M  'Orig. cult./raciales - autre'                                     
    SDCA_8   'Fréquente actuell. - école/coll./univ.'                           
    SDCA_9   'Étudiant à plein temps/à temps partiel'                           
    SDCACCB  'Pays de naissance (C)'                                            
    SDCAGCB  'Pays de naissance - (G)'                                          
    SDCADAIM 'Âge au moment de l''immigration - (D)'                            
    SDCAFIMM 'Statut d''immigrant (D)'                                          
    SDCADRES 'Durée/temps au Can. depuis l''imm. - (D)'                         
    SDCADLNG 'Langue/répondant peut converser - (D)'                            
    SDCADRAC 'Origines culturelles / raciales  - (D)'                           
    EDUA_1   'Plus haut niveau d''étude'                                        
    EDUA_2   'Obtenu un dipôme d''études secondaire'                            
    EDUA_3   'Suivi tout autre cours'                                           
    EDUA_4   'Plus haut certificat ou diplôme obtenu'                           
    EDUADR10 'Plus haut niveau - rép 10 niv - (D)'                              
    EDUADR04 'Plus haut niveau - rép 4 niv - (D)'                               
    EDUADH10 'Plus haut niveau - ménage 10 niv - (D)'                           
    EDUADH04 'Plus haut niveau - ménage 4 niv - (D)'                            
    DHHADHSZ 'Taille de ménage - (D)'                                           
    DHHADL12 'Nbre pers. < 12 ans dans le ménage - (D)'                         
    DHHADLE5 'Nbre pers. <= 5 ans dans le ménage - (D)'                         
    DHHAD611 'Nbre pers. 6-11 ans/dans le mén. - (D)'                           
    DHHADECF 'Type de ménage - (D)'                                             
    DHHADLVG 'Dispositions de vie/rép. sélect. - (D)'                           
    DHHADDWE 'Type de logement - (D)'                                           
    DHHA_OWN 'Logement - propriété d''un membre du mén.'                        
    DHHA_MTG 'Logement - hypothèque'                                            
    DHHA_BED 'Logement - nombre de chambres à coucher'                          
    LBFA_01  'A travaillé - semaine dernière'                                   
    LBFA_02  'Absent - semaine dernière'                                        
    LBFA_03  'Plus d''un emploi - semaine dernière'                             
    LBFA_11  'A cherché du travail - 4 dern. semaines'                          
    LBFA_13  'Ne travaille pas présentement - raison'                           
    LBFA_21  'A travaillé - 12 derniers mois'                                   
    LBFA_22  'A cherché du travail - 12 derniers mois'                          
    LBFA_23  'Plus d''un emploi / entreprise'                                   
    LBFA_31  'État du travail à son compte'                                     
    LBFA_31A 'Occupation'                                                       
    LBFA_35  'Restrictions sur l''usage/tabac/travail'                          
    LBFA_41  'Absence - raison principale'                                      
    LBFA_42  'Nombre d''heures au travail hab.'                                 
    LBFA_43  'Nombre d''heures préféré'                                         
    LBFA_44  'Horaire de travail habituel'                                      
    LBFA_45  'Horaire de travail habituel - raison'                             
    LBFA_46  'Travail les fins de semaine'                                      
    LBFA_51  'Plus d''un emploi / ent. - # semaines'                            
    LBFA_52  'Plus d''un emploi ou entreprise - raison'                         
    LBFA_53  'Autre emploi - nombre d''heures'                                  
    LBFA_54  'Autre emploi - travaille/fins de semaine'                         
    LBFA_61  'Semaines employées - nombre/an dernier'                           
    LBFA_71  'Recherche/année dern. - nbre/semaines'                            
    LBFA_72  'Recherche/année dern. - nbre/sem./conf.'                          
    LBFA_73  'Recherche/an dern. - raison/pas chercher'                         
    LBFA_74  'Recherche/année dern. - périodes'                                 
    LBFADWSS 'L''état de l''emploi sem. dern. (4) - (D)'                        
    LBFADWSL 'L''état de l''emploi sem. dern. (6) - (D)'                        
    LBFADRNW 'Raison sans emploi/sem. dern. - (D)'                              
    LBFADMJS 'L''état d''emploi multiple - (D)'                                 
    LBFADHPW 'Heures totales habit. trav./sem. - (D)'                           
    LBFADPFT 'Hres Rég. Trav. - temps plein / partiel'                          
    LBFADJST 'État d''emploi au cours/l''an dern. - (D)'                        
    LBFADSTU 'L''état de l''emploi des étudiants - (D)'                         
    INCAFDN  'Indicateur du revenu familial'                                    
    INCA_1A  'Source de revenu - salaires/traitements'                          
    INCA_1B  'Source de revenu - travail autonome'                              
    INCA_1C  'Source de revenu - dividendes & intérêts'                         
    INCA_1D  'Source de revenu - assurance-emploi'                              
    INCA_1E  'Source de revenu - accident du travail'                           
    INCA_1F  'Source de revenu - Régime du Can./Québec'                         
    INCA_1G  'Source de revenu - régime retr./rentes'                           
    INCA_1H  'Source de revenu - Séc. vieill./S.R.G.'                           
    INCA_1I  'Source de revenu - crédit impôt enfants'                          
    INCA_1J  'Source de revenu - aide sociale'                                  
    INCA_1K  'Source de revenu - pension alim./enfants'                         
    INCA_1L  'Source de revenu - pens. alim./conjoint'                          
    INCA_1M  'Source de revenu - autre'                                         
    INCA_1N  'Source de revenu - aucune'                                        
    INCA_2   'Rev. total du mén. - source principale'                           
    INCA_3   'Rev. total du mén.- meilleure estimation'                         
    INCA_3A  'Rev. total/mén. - <20 000$ or >=20 000$'                          
    INCA_3B  'Rev. total/mén. - <10 000$ ou >=10 000$'                          
    INCA_3C  'Rev. total/mén. - <5 000$ ou >=5 000$'                            
    INCA_3D  'Rev. total/mén. - <15 000$ ou >=15 000$'                          
    INCA_3E  'Rev. total/mén. - <40 000$ ou >=40 000$'                          
    INCA_3F  'Rev. total/mén. - <30 000$ ou >=30 000$'                          
    INCA_3G  'Rev. total/mén. - >=50 000$'                                      
    INCA_4   'Rev. pers. total - meilleure estimation'                          
    INCA_4A  'Rev. pers. total - <20 000$ ou >=20 000$'                         
    INCA_4B  'Rev. pers. total - <10 000$ ou >=10 000$'                         
    INCA_4C  'Rev. pers. total - <5 000$ ou >=5 000$'                           
    INCA_4D  'Rev. pers. total - <15 000$ ou >=15 000$'                         
    INCA_4E  'Rev. pers. total - <40 000$ ou >=40 000$'                         
    INCA_4F  'Rev. pers. total - <30 000$ ou >=30 000$'                         
    INCA_4G  'Rev. pers. total - >= 50 000$'                                    
    INCADIA2 'Capacité du revenu - 2 groupes - (D)'                             
    INCADIA4 'Capacité du revenu - 4 groupes - (D)'                             
    INCADIA5 'Capacité du revenu - 5 groupes - (D)'                             
    INCADHH  'Rev. total/mén. de toutes sources - (D)'                          
    INCADPER 'Rev. pers. total de toutes sources - (D)'                         
    FINAFDN  'Indicateur d''insécurité alimentaire'                             
    FINA_1   'Inquiét - pas suffisamment de nouriture'                          
    FINA_2   'N''avait pas suffisamment de nourriture'                          
    FINA_3   'Pas manger - qualité / variété désirées'                          
    FINAF1   'De l''insécurité alimentaire'                                     
    SATA_11  'Reçu soins de santé - derniers 12 mois'                           
    SATA_12  'Qualité - soins de santé'                                         
    SATA_13  'Satisfaction - soins de santé'                                    
    SATA_21A 'Reçu soins à l''hopital'                                          
    SATA_21B 'Soins hospitalier - genre de patient'                             
    SATA_22  'Qualité - soins hospitaliers'                                     
    SATA_23  'Satisfaction - soins hospitaliers'                                
    SATA_31A 'A reçu soins de santé d''un médecin'                              
    SATA_31B 'Type de médecin'                                                  
    SATA_32  'Qualité - soins de santé d''un médecin'                           
    SATA_33  'Satisfaction - soins de santé d''un méd.'                         
    SATA_41  'A reçu des soins de santé communautaire'                          
    SATA_42  'Qualité - soins de santé communautaire'                           
    SATA_43  'Satisfaction - soins de santé comm.'                              
    WTSA_S   'Poids échan. - poids de partage'                                  
    WTSA_Q4S 'Poids échan. - poids de partage - Q4'                             
    WTSA_PES 'Poids échan. - poids de partage - IPE'                            
    WTSA_M   'Poids échan. - poids maître'                                      
    WTSA_Q4M 'Poids échan. - poids maître - Q4'                                 
    WTSA_PEM 'Poids échan. - poids maître - IPE'                                
    ADMAFFE  'Indicateur - var. d''évaluation de base'                          
    ADMA_PH  'Nombre de téléphones'                                             
    GEOA_HR  'Région socio-sanitaire (6)'                                       
    .                                                                           
