VARIABLE LABELS
    VERDATE        "Date de création du fichier"
    REFPER         "Période de référence"
    SAMPLEID       "Identificateur du cas"
    PERSONID       "Identificateur de la personne sélectionnée - interview santé"
    GEO_PRV        "Province de résidence du répondant"
    GEODVPC        "Code postal - (D)"
    GEODVD16       "Aire de diffusion du Recensement de 2016 (AD) - (D)"
    GEODVCSD       "Subdivision du Recensement de 2016 (SDR) - (D)"
    GEODVFED       "Circonscriptions électorales fédérales du Recensement 2016 (CÉF) - (D)"
    GEODVCD        "Division du recensement de 2016 (DR) - (D)"
    GEODVCMA       "Région métropolitaine du Recensement de 2016 (RMR) - (D)"
    GEODVCA        "Agglomération de recensement de 2016 (AR) - (D)"
    GEODVSAT       "Type de classification des secteurs statistiques (CSS) - (D)"
    GEODVHR4       "Région sociosanitaire - (D)"
    GEODVP16       "Groupes de régions sociosanitaires homologues de 2016 - (D)"
    GEODVUR        "Type de centre de population ou de région rurale - (D)"
    GEODVUR2       "Type de centre de population ou de région rurale - regroupé - (D)"
    GEODVPSZ       "Classification du centre de population ou de la région rurale - (D)"
    GEODVBHA       "Health Authority - Colombie-Britannique (ASCB) - (D)"
    GEODVLHN       "Réseau local d'intégration des services de santé de l'Ontario - (D)"
    GEODVSLH       "Sous-réseau local intégration des services de santé de l'Ontario - (D)"
    GEODVASZ       "Sous-zones - Alberta - (D)"
    SAM_CP         "Période de collecte de l'échantillon"
    FRAMETYP       "Base de sondage"
    SAMDVSHR       "Permission sur le partage de données - (D)"
    SAMDVLNK       "Permission sur le jumelage de données - (D)"
    ADM_STA        "État de réponse après traitement des données"
    ADM_YOI        "Année de l'interview"
    ADM_MOI        "Mois de l'interview"
    ADM_DOI        "Jour de l'interview"
    ADM_LHH        "Langue de préférence - interview du ménage"
    DHH_SEX        "Sexe à la naissance"
    GDR_010        "Genre"
    DHH_MS         "État matrimonial"
    DHHDVHSZ       "Taille du ménage - (D)"
    DHHDVLVG       "Disposition de vie du répondant sélectionné - (D)"
    DHHDVYKD       "Nombre de personnes de moins de 16 ans dans le ménage - (D)"
    DHHDVOKD       "Nombre de personnes de 16 à 17 ans dans le ménage - (D)"
    DHHDV611       "Nombre de personnes de 6 à 11 ans dans le ménage - (D)"
    DHHDVEFS       "Situation de la famille économique (type de ménage) - (D)"
    DHHDVL12       "Nombre de personnes de moins de 12 ans dans le ménage - (D)"
    DHHDVL18       "Nombre de personnes de moins de 18 ans dans le ménage - (D)"
    DHHDVLE5       "Nombre de personnes de 5 ans ou moins dans le ménage - (D)"
    DHHDVA65       "Nombre de personnes de 65 ans et plus dans le ménage - (D)"
    DHHDVAOS       "Âge du conjoint - (D)"
    ADM_PRX        "Composante santé complétée par procuration"
    DHH_AGE        "Âge"
    DHH_DOB        "Jour de naissance"
    DHH_MOB        "Mois de naissance"
    DHH_YOB        "Année de naissance"
    DOMAC          "Activité principale - Ind d'inclusion - (F)"
    MAC_005        "Activité principale - semaine dernière"
    MAC_010        "A travaillé à un emploi / entreprise - 12 mo"
    MAC_015        "Fréquente actuellement école / collège / cégep / université"
    MAC_020        "Statut d'étudiant"
    MAC_025        "Enceinte actuellement"
    EHG2_01        "Le plus haut niveau d'études primaires /  secondaires achevé"
    EHG2_02        "A obtenu un diplôme d'études secondaires /  équivalent"
    EHG2_03        "Autre cours - attestation / certificat / diplôme"
    EHG2_04        "Le plus haut certificat / diplôme / grade obtenu"
    EHG2DVR3       "Plus haut niveau de scolarité - répondant, 3 niveaux - (D)"
    EHG2DVH3       "Plus haut niveau de scolarité - ménage, 3 niveaux - (D)"
    EHG2DVR9       "Plus haut niveau de scolarité - répondant, 9 niveaux - (D)"
    EHG2DVH9       "Plus haut niveau de scolarité - ménage, 9 niveaux - (D)"
    DOGEN          "État de santé général - Ind d'inclusion - (F)"
    GEN_005        "Santé perçue"
    GEN_010        "Satisfaction de vie en général"
    GEN_015        "Santé mentale perçue"
    GEN_020        "Stress perçu dans la vie"
    GEN_025        "Stress perçu au travail"
    GEN_030        "Sentiment d'appartenance à la communauté locale"
    GENDVHDI       "Santé perçue - (D)"
    GENDVMHI       "Santé mentale perçue - (D)"
    GENDVSWL       "Satisfaction à l'égard de la vie en général - (D)"
    DOCOV2         "COVID-19 - Ind d'inclusion - (F)"
    COV2_005       "Santé mentale perçue avant / pendant pandémie"
    COV2_10A       "Précautions COVID-19 - se lave les mains plus souvent"
    COV2_10B       "Précautions COVID-19 - porte un masque dans les espaces publics"
    COV2_10C       "Précautions COVID-19 - garde distance de 2  m / 6 pi avec les autres"
    COV2_10D       "Précautions COVID-19 - évite les foules / rassemblements"
    COV2_10E       "Précautions COVID-19 - évite quitter maison raisons non-essentielles"
    COV2_10F       "Précautions COVID-19 - travaille de la maison"
    COV2_10G       "Précautions COVID-19 - utilise services livraison / ramassage magasin"
    COV2_10H       "Précautions COVID-19 - s'isole si symptômes"
    COV2_10I       "Précautions COVID-19 - autre précaution"
    COV2_10J       "Précautions COVID-19 - aucune précaution prise"
    COV2_038       "A reçu un vaccin contre la COVID-19"
    COV2_040       "Probabilité de choisir de recevoir le vaccin contre la COVID-19"
    DOHWT          "Taille et poids - Ind d'inclusion - (F)"
    HWT_005        "Taille (autodéclarée)"
    HWT_010        "Taille - taille exacte de 1'0"" à 1'11"" (autodéclarée)"
    HWT_015        "Taille - taille exacte de 2'0"" à 2'11"" (autodéclarée)"
    HWT_020        "Taille - taille exacte de 3'0"" à 3'11"" (autodéclarée)"
    HWT_025        "Taille - taille exacte de 4'0"" à 4'11"" (autodéclarée)"
    HWT_030        "Taille - taille exacte de 5'0"" à 5'11"" (autodéclarée)"
    HWT_035        "Taille - taille exacte de 6'0"" à 6'11"" (autodéclarée)"
    HWT_040        "Poids (autodéclaré)"
    HWT_045        "Poids - unité de mesure en livres ou kilogrammes (autodéclaré)"
    HWT_050        "Autoperception du poids - embonpoint / trop maigre / à peu près normal"
    HWTDVHTM       "Taille (en mètres) - autodéclarée - (D)"
    HWTDVWTK       "Poids (en kilogrammes) - autodéclarés - (D)"
    HWTDVBMI       "Indice de masse corporelle (autodéclaré) - (D)"
    HWTDVCOL       "IMC 12 à 17 ans (autodéclaré) - classification de Cole - (D)"
    HWTDVISW       "IMC classification 18 ans et + (autodéclaré) - standard intl - (D)"
    HWTDVWHO       "IMC 12 à 17 ans (autodéclaré) - classification de l'OMS - (D)"
    HWTDVCOR       "Indice de masse corporelle (ajusté) - (D)"
    HWTDVBCC       "IMC classification 18 ans et + (ajusté) - standard intl - (D)"
    DOCCC          "Problèmes de santé chroniques - Ind d'inclusion - (F)"
    CCC_035        "Fait de l'apnée du sommeil"
    CCC_045        "Souffre de fibromyalgie"
    CCC_050        "Souffre d'arthrite (ex. arthrose, arthrite rhumatoide, goutte)"
    CCC_055        "A des maux de dos (excluant scoliose, fibromyalgie et arthrite)"
    CCC_060        "Souffre d'ostéoporose"
    CCC_065        "Fait de l'hypertension"
    CCC_070        "Hypertension - a pris des médicaments - 1 mo"
    CCC_075        "A un taux  élevé de cholestérol / lipides sanguins"
    CCC_080        "Taux élevé de cholestérol / lipides - a pris des médicaments - 1 mo"
    CCC_085        "A une maladie cardiaque"
    CCC_087        "A reçu un diagnostic de maladie cardiaque - vie"
    CCC_090        "Atteint de troubles dus à un accident vasculaire cérébral"
    CCC_095        "Atteint du diabète"
    CCC_100        "Diabète - âge au premier diagnostic"
    CCC_105        "Diabète - diagnostic - durant grossesse"
    CCC_110        "Diabète - diagnostic - autre que durant grossesse"
    CCC_115        "Diabète - temps entre diagnostic et début insuline"
    CCC_120        "Diabète - prend actuellement de l'insuline"
    CCC_125        "Diabète - pris pilules pour contrôler niveau de sucre - 1 mo"
    CCC_130        "A un cancer"
    CCC_135        "A reçu un diagnostic de cancer - vie"
    CCC_145        "Atteint d'Alzheimer ou autre démence"
    CCC_185        "Souffre du syndrome de fatigue chronique"
    CCC_190        "Souffre de sensibilités aux agresseurs chimiques"
    CCC_195        "Atteint trouble de l'humeur (dépression, bipolaire, manie, dysthymie)"
    CCC_200        "Atteint d'un trouble d'anxiété (phobie, TOC, panique)"
    CCCDVDIA       "Type de diabète - (D)"
    DOADL          "Activités de la vie quotidienne - Ind d'inclusion - (F)"
    ADL_005        "Difficulté - préparer les repas"
    ADL_010        "Difficulté - faire des commissions"
    ADL_015        "Difficulté - accomplir les tâches ménagères quotidiennes"
    ADL_020        "Difficulté - soins personnels / prendre des médicaments"
    ADL_025        "Difficulté - se déplacer dans la maison"
    ADL_030        "Difficulté - s'occuper de ses finances personnelles"
    ADLDVIHS       "Indice activités instrumentales vie quot - maintien à domicile - (D)"
    ADLDVIPC       "Indice activités instrumentales vie quot - soins personnels - (D)"
    DOSLP          "Sommeil - Ind d'inclusion - (F)"
    SLP_005        "Nombre d'heures habituel de sommeil par nuit"
    SLP_010        "Problèmes à s'endormir ou à rester endormi - fréquence"
    SLP_015        "Sommeil réparateur - fréquence"
    SLP_020        "Difficulté à rester éveillé - fréquence"
    DOFVC          "Consommation de fruits et de légumes - Ind d'inclusion - (F)"
    FVC_004        "A bu des jus de fruit purs - 1 mo"
    FVC_005        "A bu des jus de fruit purs - nbre de fois - 1 mo"
    FVC_005A       "A bu des jus de fruit purs - période déclarée"
    FVC_009        "A mangé des fruits - 1 mo"
    FVC_010        "A mangé des fruits - nbre de fois - 1 mo"
    FVC_010A       "A mangé des fruits - période déclarée"
    FVC_014        "A mangé légumes vert foncé - 1 mo"
    FVC_015        "A mangé des légumes vert foncé - nbre de fois - 1 mo"
    FVC_015A       "A mangé légumes vert foncé - période déclarée"
    FVC_019        "A mangé des légumes orange - 1 mo"
    FVC_020        "A mangé des légumes orange - nbre de fois - 1 mo"
    FVC_020A       "A mangé des légumes orange - période déclarée"
    FVC_024        "A mangé des pommes de terre non frites - 1 mo"
    FVC_025        "A mangé des pommes de terre non frites - nbre de fois - 1 mo"
    FVC_025A       "A mangé des pommes de terre non frites - période déclarée"
    FVC_029        "A mangé d'autres genres de légumes - 1 mo"
    FVC_030        "A mangé d'autres genres de légumes - nbre de fois - 1 mo"
    FVC_030A       "A mangé d'autres genres de légumes - période déclarée"
    FVCDVJUI       "Consommation quotidienne - jus de fruit purs - (D)"
    FVCDVFRU       "Consommation quotidienne - fruits - (D)"
    FVCDVGRN       "Consommation quotidienne - légumes vert foncé - (D)"
    FVCDVORA       "Consommation quotidienne - légumes orange - (D)"
    FVCDVPOT       "Consommation quotidienne - pommes de terre - (D)"
    FVCDVVEG       "Consommation quotidienne - autres légumes - (D)"
    FVCDVTOT       "Consommation quotidienne - fruits et légumes - (D)"
    FVCDVGDT       "Groupement consommation quotidienne totale - fruits et légumes - (D)"
    DOSMK          "Usage du tabac - Ind d'inclusion - (F)"
    SMK_005        "Type de fumeur (tous les jours / à l'occasion / jamais) - actuellement"
    SMK_010        "A fumé - 30 j"
    SMK_015        "A fumé tous les jours - 30 j"
    SMK_020        "A fumé plus de 100 cigarettes - vie"
    SMK_025        "A fumé une cigarette entière - vie"
    SMK_030        "A fumé tous les jours - vie (fumeur occasionnel / ancien)"
    SMK_035        "Âge - a fumé première cigarette entière"
    SMK_040        "Âge - a commencé à fumer tous les jours (fumeur quot / ancien quot)"
    SMK_045        "Nbre de cigarettes fumées par jour (fumeur quotidien)"
    SMK_050        "Nbre de cigarettes fumées par jour (fumeur occasionnel)"
    SMK_055        "Nbre de jours - a fumé 1 cigarette ou plus (fumeur occasionnel) - 1 mo"
    SMK_060        "A cessé de fumer - quand (ancien fumeur occasionnel)"
    SMK_065        "A cessé de fumer - mois (ancien fumeur occasionnel)"
    SMK_070        "A cessé de fumer - nbre d'années (ancien fumeur occasionnel)"
    SMK_075        "Nbre de cigarettes fumées par jour (ancien fumeur quotidien)"
    SMK_080        "A cessé de fumer tous les jours - quand (ancien fumeur quotidien)"
    SMK_085        "A cessé de fumer tous les jours - mois (ancien fumeur quotidien)"
    SMK_090        "A cessé de fumer tous les jours - nbre d'années (ancien fumeur quot)"
    SMK_095        "A cessé de fumer complètement (ancien fumeur quotidien)"
    SMK_100        "A cessé de fumer complètement - quand (ancien fumeur quotidien)"
    SMK_105        "A cessé de fumer complètement - mois (ancien fumeur quotidien)"
    SMK_110        "A cessé de fumer complètement - nbre d'années (ancien fumeur quot)"
    SMKDVSTY       "Statut du fumeur (type 2) - définition traditionnelle - (D)"
    SMKDVYCS       "Nbre années depuis lesquelles répondant fume tous les jours - (D)"
    SMKDVSTP       "Nbre années a cessé de fumer complètement - (D)"
    DOSCH2         "Usage du tabac - les étapes du changement 2 - Ind d’inclusion - (F)"
    SCH2_005       "Envisage de cesser de fumer dans les prochains 6 mois"
    SCH2_015       "A arrêté de fumer pendant au moins 24h - 12 mo"
    DOTAL2         "Produits alternatifs du tabac 2 (TAL2) - Ind d'inclusion - (F)"
    TAL2_005       "A fumé des petits cigares /  cigarillos - 30 j"
    TAL2_010       "A fumé des petits cigares /  cigarillos - natures / aromatisés"
    TAL2_015       "A fumé autres cigares - 30 j"
    TAL2_025       "A fumé la pipe - 30 j"
    TAL2_030       "A mâché / prisé du tabac - 30 j"
    TAL2_035       "A fumé du tabac dans une pipe à eau - 30 j"
    TAL2DVUS       "Consommation produits alternatifs du tabac 2 - (D)"
    DOECV          "E-Cigarette et vapotage - Ind d'inclusion - (F)"
    ECV_005        "A essayé cigarette électronique / appareil vapotage - vie"
    ECV_010        "A essayé cigarette électronique / appareil vapotage - âge"
    ECV_015        "A essayé cigarette électro / appareil vapotage / cigarette - premier"
    ECV_020        "A utilisé cigarette électro / appareil de vapotage - fréquence - 30 j"
    ECVDVSMK       "Consommation cigarette éléctro / appareil vapotage et cigarette - (D)"
    DOALC          "Consommation d'alcool - Ind d'inclusion - (F)"
    ALC_005        "A pris un verre d'alcool - vie"
    ALC_010        "A bu de l'alcool - 12 mo"
    ALC_015        "A bu de l'alcool - fréquence - 12 mo"
    ALC_020        "A bu 5+ / 4+ verres même occasion - fréquence - 12 mo"
    ALCDVTTM       "Genre de buveur - 12 mois - (D)"
    DOMED          "Utilisation de médicaments - Ind d'inclusion - (F)"
    MED_005        "A utilisé analgésiques - produits avec codéine - 12 mo"
    MED_010        "A utilisé analgésiques - produits avec oxycodone - 12 mo"
    MED_015        "A utilisé analgésiques - autres produits opioïdes - 12  mois"
    MED_020        "A utilisé analgésiques - fréquence - 12 mo"
    MED_025        "A utilisé analgésiques - prescrits - 12 mo"
    MED_030        "A utilisé analgésiques - surconsommation - 12 mo"
    MED_035        "A utilisé analgésiques - pour expérience / effet - 12 mo"
    MED_040        "A utilisé analgésiques - pour se sentir mieux / stress - 12 mo"
    MED_045        "A utilisé analgésiques - modifiés - 12 mo"
    MED_050        "A utilisé stimulants - 12 mo"
    MED_055        "A utilisé stimulants - fréquence - 12 mo"
    MED_060        "A utilisé stimulants - prescrits - 12 mo"
    MED_065        "A utilisé stimulants - surconsommation - 12 mo"
    MED_070        "A utilisé stimulants - pour expérience / effet - 12 mo"
    MED_075        "A utilisé stimulants - pour raisons autres que prescrites - 12 mo"
    MED_080        "A utilisé sédatifs - 12 mo"
    MED_085        "A utilisé sédatifs - fréquence - 12 mo"
    MED_090        "A utilisé sédatifs - prescrits - 12 mo"
    MED_095        "A utilisé sédatifs - surconsommation - 12 mo"
    MED_100        "A utilisé sédatifs - pour expérience / effet - 12 mo"
    DOCAN          "Utilisation du cannabis - Ind d'inclusion - (F)"
    CAN_005        "A utilisé cannabis - vie"
    CAN_010        "A utilisé cannabis - première fois - âge"
    CAN_015        "A utilisé cannabis - 12 mo"
    CAN_020        "A utilisé cannabis - fréquence - 12 mo"
    CAN_025        "A utilisé cannabis - méthode utilisée le plus souvent - 12 mo"
    CAN_030        "A utilisé cannabis - fins médicales - 12 mo"
    CAN_035A       "A utilisé cannabis - fins médicales - douleur - 12 mo"
    CAN_035B       "A utilisé cannabis - fins médicales - nausées / vomissements - 12 mo"
    CAN_035C       "A utilisé cannabis - fins médicales - manque d'appétit - 12 mo"
    CAN_035D       "A utilisé cannabis - fins médicales - maux de tête / migraines - 12 mo"
    CAN_035E       "A utilisé cannabis - fins médicales - spasmes / convulsions - 12 mo"
    CAN_035F       "A utilisé cannabis - fins médicales - anxiété / dépression - 12 mo"
    CAN_035G       "A utilisé cannabis - fins médicales - stress post-traumatique - 12 mo"
    CAN_035H       "A utilisé cannabis - fins médicales - problèmes sommeil - 12 mo"
    CAN_035I       "A utilisé cannabis - fins médicales - sevrage d'opioïdes - 12 mo"
    CAN_035J       "A utilisé cannabis - fins médicales - autre - 12 mo"
    CAN_040        "A utilisé cannabis - a un document médical pour utilisation médicale"
    CAN_045        "A utilisé cannabis - a causé problèmes - 12 mo"
    CAN_050        "A utilisé cannabis - n'a pas répondu aux attentes normales - 12 mo"
    CAN_055        "A utilisé cannabis - qqn inquiet / suggéré de réduire - 12 mo"
    CAN_060        "A utilisé cannabis - fréquence - 30 j"
    CAN_065        "A utilisé cannabis - tous les jours - âge"
    CANDVLIO       "Consommation de cannabis - vie (incluant « juste une fois » ) - (D)"
    CANDVLEO       "Consommation de cannabis - vie (excluant « juste une fois » ) - (D)"
    CANDVYIO       "Consommation de cannabis - 12 mo (incluant « juste une fois ») - (D)"
    CANDVYEO       "Consommation de cannabis - 12 mo (excluant « juste une fois ») - (D)"
    CANDVF12       "Cannabis - fréquence de consommation - 12 mo - (D)"
    CANDVLS5       "Statut du consommateur de cannabis - vie - 5 catégories - (D)"
    CANDVLS3       "Statut du consommateur de cannabis - vie - 3 catégories - (D)"
    DODRG          "Usage de substances - Ind d'inclusion - (F)"
    DRG_020        "A pris cocaïne (crack, cocaïne épurée, poudre, neige) - vie"
    DRG_025        "A pris cocaïne (crack, cocaïne épurée, poudre, neige) - 12 mo"
    DRG_030        "A pris amphétamines / speed / méthamphétamines / cristal - vie"
    DRG_035        "A pris amphétamines / speed / méthamphétamines / cristal - 12 mo"
    DRG_040        "A pris ecstasy - vie"
    DRG_045        "A pris ecstasy - 12 mo"
    DRG_050        "A pris drogues hallucinogènes - vie"
    DRG_055        "A pris drogues hallucinogènes - 12 mo"
    DRG_060        "A reniflé colle / essence / autres solvants - vie"
    DRG_065        "A reniflé colle / essence / autres solvants - 12 mo"
    DRG_070        "S'est injecté drogue non prescrite - vie (3 catégories)"
    DRG_075        "S'est injecté drogue non prescrite - 12 mo"
    DRG_080A       "S'est injecté drogue non prescrite - cocaïne"
    DRG_080B       "S'est injecté drogue non prescrite - héroïne / opium"
    DRG_080C       "S'est injecté drogue non prescrite - méthamphétamine"
    DRG_080D       "S'est injecté drogue non prescrite - stéroïdes"
    DRG_080E       "S'est injecté drogue non prescrite - autre"
    DRG_080F       "S'est injecté drogue non prescrite - jamais"
    DRGDVLCO       "Consommation cocaïne - vie - (D)"
    DRGDVLAM       "Consommation amphétamines / speed - vie - (D)"
    DRGDVLEX       "Consommation ecstasy - vie - (D)"
    DRGDVLHA       "Consommation hallucinogènes - vie - (D)"
    DRGDVLGL       "Inhalation colle / essence / autres solvants - vie - (D)"
    DRGDVINJ       "Injection drogue illicite - vie - (D)"
    DRGDVYA        "Consommation toute drogue illicite - 12 mo - (D)"
    DRGDVLA        "Consommation toute drogue illicite - vie - (D)"
    DOPAA          "Activités physiques - adultes 18 ans et plus - Ind d'inclusion - (F)"
    PAA_005        "Déplacement actif - 7 j"
    PAA_010A       "Déplacement actif - lundi"
    PAA_010B       "Déplacement actif - mardi"
    PAA_010C       "Déplacement actif - mercredi"
    PAA_010D       "Déplacement actif - jeudi"
    PAA_010E       "Déplacement actif - vendredi"
    PAA_010F       "Déplacement actif - samedi"
    PAA_010G       "Déplacement actif - dimanche"
    PAA_015        "Déplacement actif - 7 j - total - heures"
    PAA_020        "Déplacement actif - 7 j - total - minutes"
    PAA_030        "Sport / cond physique / act physique loisir - 7 j"
    PAA_035        "Sport / cond phys / act phys loisir - transpiré"
    PAA_040A       "Sport / cond physique / act physique loisir - lundi"
    PAA_040B       "Sport / cond physique / act physique loisir - mardi"
    PAA_040C       "Sport / cond physique / act physique loisir - mercredi"
    PAA_040D       "Sport / cond physique / act physique loisir - jeudi"
    PAA_040E       "Sport / cond physique / act physique loisir - vendredi"
    PAA_040F       "Sport / cond physique / act physique loisir - samedi"
    PAA_040G       "Sport / cond physique / act physique loisir- dimanche"
    PAA_045        "Sport / cond physique / act physique loisir - 7 j - total - heures"
    PAA_050        "Sport / cond physique / act physique loisir - 7 j - total - minutes"
    PAA_060        "Autres activités physiques - 7 j"
    PAA_065        "Autres activités physiques - transpiré"
    PAA_070A       "Autres activités physiques - lundi"
    PAA_070B       "Autres activités physiques - mardi"
    PAA_070C       "Autres activités physiques - mercredi"
    PAA_070D       "Autres activités physiques - jeudi"
    PAA_070E       "Autres activités physiques - vendredi"
    PAA_070F       "Autres activités physiques - samedi"
    PAA_070G       "Autres activités physiques - dimanche"
    PAA_075        "Autres activités physiques - 7 j - total - heures"
    PAA_080        "Autres activités physiques - 7 j - total - minutes"
    PAA_095        "Activités physiques - intensité élevée"
    PAA_100        "Activités physiques - intensité élevée - 7 j - total - heures"
    PAA_105        "Activités physiques - intensité élevée - 7 j - total - minutes"
    PAADVTRV       "Total minutes - déplacements actifs - 7 j - (D)"
    PAADVTRA       "Nbre moyen minutes par jour - déplacements actifs - 7 j - (D)"
    PAADVREC       "Total minutes - activités physiques récréatives - 7 j - (D)"
    PAADVRCA       "Nbre moyen minutes par jour - act physiques récréatives - 7 j - (D)"
    PAADVOTH       "Total minutes - autres activités physiques - 7 j - (D)"
    PAADVOTA       "Nbre moyen minutes par jour - autres activités physiques - 7 j - (D)"
    PAADVMVA       "Total minutes - activités physiques modérée à vigoureuse - 7 j - (D)"
    PAADVACV       "Indicateur de l'activité physique - (D)"
    PAADVAC2       "Autre indicateur de l'activité physique - (D)"
    PAADVVIG       "Total minutes - activités physiques vigoureuses - 7 j - (D)"
    PAADVVOL       "Niveau d'activité hebdomadaire - 7 j (MET*mins/semaine) - (D)"
    PAADVWHO       "Physiquement actif selon les recommandations de l'OMS - (D)"
    PAADVMON       "A fait de l'activité physique - Lundi - (D)"
    PAADVTUE       "A fait de l'activité physique - Mardi - (D)"
    PAADVWED       "A fait de l'activité physique - Mercredi - (D)"
    PAADVTHU       "A fait de l'activité physique - Jeudi - (D)"
    PAADVFRI       "A fait de l'activité physique - Vendredi - (D)"
    PAADVSAT       "A fait de l'activité physique - Samedi - (D)"
    PAADVSUN       "A fait de l'activité physique - Dimanche - (D)"
    PAADVDYS       "Nbre de  jours - physiquement actif - 7 j - (D)"
    PAADVWKD       "Nbre de  jours - physiquement actif - jours de semaine - 7 j - (D)"
    PAADVWND       "Nbre de  jours - physiquement actif - fin de semaine - 7 j - (D)"
    DOPAY          "Activités physiques pour les jeunes - Ind d'inclusion - (F)"
    PAY_005A       "Activités physiques - fréquenté l'école - 7 j"
    PAY_005B       "Activités physiques - fréquenté un camp de jour - 7 j"
    PAY_005C       "Activités physiques - occupé un emploi rémunéré ou non rémunéré - 7 j"
    PAY_005D       "Activités physiques - aucun des choix ci-dessus - 7 j"
    PAY_010        "Déplacement actif - 7 j"
    PAY_025        "Activités physiques loisir - école / camp - 7 j"
    PAY_030        "Sport / cond phys / act phys loisir - école / camp - transpiré"
    PAY_045        "Activités physiques - temps de loisirs - 7 j"
    PAY_050        "Activités physiques - temps de loisirs - transpiré"
    PAY_065        "Autres activités physiques - 7 j"
    PAY_070        "Autres activités physiques - transpiré"
    PAY_090        "Activités physiques - intensité élevée"
    PAY_095A       "Activités physiques - intensité élevée - hier"
    PAY_095B       "Activités physiques - intensité élevée - 2 j"
    PAY_095C       "Activités physiques - intensité élevée - 3 j"
    PAY_095D       "Activités physiques - intensité élevée - 4 j"
    PAY_095E       "Activités physiques - intensité élevée - 5 j"
    PAY_095F       "Activités physiques - intensité élevée - 6 j"
    PAY_095G       "Activités physiques - intensité élevée - 7 j"
    PAY_100        "Activités physiques - intensité élevée - 7 j - total - heures"
    PAY_105        "Activités physiques - intensité élevée - 7 j - total - minutes"
    PAYDVTTR       "Total minutes - déplacements actifs - 7 j - (D)"
    PAYDVTSC       "Total minutes - act phys récréatives école/camp - 5 j semaine - (D)"
    PAYDVADL       "Total minutes - activités physiques durant loisirs - 7 j - (D)"
    PAYDVTOA       "Total minutes - autres activités physiques - 7 j - (D)"
    PAYDVTMN       "Total minutes - activités physiques - Lundi - (D)"
    PAYDVTTU       "Total minutes - activités physiques - Mardi - (D)"
    PAYDVTWD       "Total minutes - activités physiques - Mercredi - (D)"
    PAYDVTTH       "Total minutes - activités physiques - Jeudi - (D)"
    PAYDVTFR       "Total minutes - activités physiques - Vendredi - (D)"
    PAYDVTST       "Total minutes - activités physiques - Samedi - (D)"
    PAYDVTSN       "Total minutes - activités physiques - Dimanche - (D)"
    PAYDVDYS       "Nbre de  jours - physiquement actif - 7 j - (D)"
    PAYDVMNS       "Total minutes - activités physiques - 7 j - (D)"
    PAYDVAV7       "Nbre moyen minutes par jour - activités physiques - 7 j - (D)"
    PAYDVTWK       "Total minutes - activités physiques - jours de semaine - 7 j - (D)"
    PAYDVTWN       "Total minutes - activités physiques - fin de semaine - 7 j - (D)"
    PAYDVDPG       "Nbre de jours - respecté / excédé directives activité physique - (D)"
    PAYDVPAI       "Indicateur d'activité physique des jeunes - (D)"
    PAYDVVIG       "Total minutes - activités physiques vigoureuses - 7 j - (D)"
    PAYDVWK1       "Activité physique - directive hebdomadaire spéciale 1 - (D)"
    PAYDVWK2       "Activité physique - directive hebdomadaire spéciale 2 - (D)"
    PAYDVWK3       "Activité physique - directive hebdomadaire spéciale 3 - (D)"
    PAYDVPAG       "Satisfait aux Directives canadiennes en matière d'act phys - 7 j - (D)"
    DOSBE          "Comportements sédentaires - Ind d'inclusion - (F)"
    SBE_005        "Temps libre assis/couché regarder écran - jour école/travail - 7j"
    SBE_010        "Temps libre assis/couché regarder écran - pas jour école/travail - 7j"
    DOMEX          "Expériences maternelles - Ind d'inclusion - (F)"
    MEX_005        "Prend un supplément vitaminique avec acide folique"
    MEX_010        "A donné naissance - 5 ans"
    MEX_020        "Date de naissance du bébé - jour"
    MEX_025        "Date de naissance du bébé - mois"
    MEX_030        "Date de naissance du bébé - année"
    MEX_040        "Supplément acide folique - 3 mo avant grossesse"
    MEX_045        "Supplément acide folique - 3 mo avant grossesse - tous les jours"
    MEX_050        "Supplément acide folique - 3 premiers mo grossesse"
    MEX_055        "Supplément acide folique - 3 premiers mo grossesse - tous les jours"
    MEX_060        "Supplément acide folique - sais peut prévenir anomalies congénitales"
    MEX_065        "Supplément de fer - durant grossesse"
    MEX_070        "Poids avant grossesse"
    MEX_075        "Poids avant grossesse - livres / kilogrammes"
    MEX_080        "Poids pris pendant grossesse"
    MEX_085        "Poids pris pendant grossesse - livres / kilogrammes"
    MEX_090        "Sommeil partagé avec bébé moins de 12 mo - fréquence"
    MEX_095        "Sommeil partagé avec bébé moins de 12 mo - raison"
    MEX_100        "A allaité dernier bébé"
    MEX_105        "N'a pas allaité dernier bébé - raison"
    MEX_110        "Allaite encore dernier bébé"
    MEX_115        "A allaité dernier bébé - durée - chiffre"
    MEX_115A       "A allaité dernier bébé - durée - période déclarée"
    MEX_120        "Allaitement - raison pour avoir arrêté"
    MEX_125        "Supplément de vitamine D - bébé moins de 12 mo"
    MEX_130        "Supplément de vitamine D - bébé plus de 12 mo"
    MEX_140        "Supplément de vitamine D - fréquence générale"
    MEX_150        "Alimentation du bébé - autres liquides (lait, eau, jus)"
    MEX_155        "Alimentation du bébé - autres liquides - âge - chiffre"
    MEX_160        "Alimentation du bébé - autres liquides - âge - période déclarée"
    MEX_170        "Alimentation du bébé - aliments solides"
    MEX_175        "Alimentation du bébé - aliments solides - âge - chiffre"
    MEX_180        "Alimentation du bébé - aliments solides - âge - période déclarée"
    MEX_190        "Alimentation du bébé - premier aliment solide"
    MEX_195        "Alimentation du bébé - autres liquides / aliments solides - raison"
    MEXDVWBK       "Poids avant la grossesse (en kilogrammes) - (D)"
    MEXDVWGK       "Gain de poids pendant la grossesse (en kilogrammes) - (D)"
    MEXDVBM6       "Allaitement exclusif pendant 6 mois (ou plus) - (D)"
    MEXDVLBM       "Durée d'allaitement exclusif - (D)"
    MEXDVVTD       "Administration de vitamine D à l'enfant - (D)"
    DOMXS          "Expériences maternelles - usage du tabac  - Ind d'inclusion - (F)"
    MXS_005        "A fumé des cigarettes - 3 mois avant la dernière grossesse"
    MXS_010        "A fumé des cigarettes - après avoir su être enceinte"
    MXS_015        "A fumé des cigarettes - 3 derniers mois de la grossesse"
    MXS_020        "Exposition à la fumée secondaire durant la dernière grossesse"
    DOMXA          "Expériences maternelles - consommation alcool - Ind d'inclusion - (F)"
    MXA_005        "A bu de l'alcool 3 mois avant la dernière grossesse"
    MXA_010        "A bu de l'alcool 3 mois avant la dernière grossesse - fréquence"
    MXA_015        "A bu de l'alcool après avoir su être enceinte"
    MXA_020        "A bu de l'alcool après avoir su être enceinte - fréquence"
    MXA_025        "A bu de l'alcool 3 derniers mois de la grossesse"
    MXA_030        "A bu de l'alcool 3 derniers mois de la grossesse - fréquence"
    MXA_035        "A bu de l'alcool durant l'allaitement du dernier bébé"
    MXA_040        "A bu de l'alcool durant l'allaitement du dernier bébé - fréquence"
    DODEP          "Dépression - Ind d'inclusion - (F)"
    DEP_005        "Peu d'intérêt / plaisir à faire choses - 2 sem"
    DEP_010        "S'est senti triste / déprimé / désespéré - 2 sem"
    DEP_015        "Difficulté à s'endormir / rester endormi / trop dormi - 2 sem"
    DEP_020        "Fatigué / peu d'énergie - 2 sem"
    DEP_025        "Peu d'appétit / trop manger - 2 sem"
    DEP_030        "Mauvaise perception de soi / perdant / pas satisfait attentes - 2 sem"
    DEP_035        "Difficultés à se concentrer sur des choses - 2 sem"
    DEP_040        "Bougé ou parlé lentement / agité - 2 sem"
    DEP_045        "Pensées d'être mieux mort / se blesser- 2 sem"
    DEP_050        "Difficulté avec travail / tâches à la maison / relations"
    DEPDVPHQ       "Échelle de gravité de la dépression - (D)"
    DEPDVSEV       "Échelle de dépression - gravité de la dépression - (D)"
    DOSPS          "Provisions sociales - Ind d'inclusion - (F)"
    SPS_015        "Relations - sentiment de sécurité affective et de bien-être"
    SPS_020        "Relations - quelqu'un pour discuter de décisions importantes"
    SPS_025        "Relations - compétence et savoir-faire sont reconnus"
    SPS_035        "Relations - fait partie d'un groupe qui partage attitudes et croyances"
    SPS_050        "Relations - gens sur qui compter en cas d'urgence"
    DOPHC          "Soins de santé primaires - Ind d'inclusion - (F)"
    PHC_005        "Endroit habituel pour soins immédiats pour problème mineur"
    PHC_010        "Endroit habituel pour soins immédiats pour problème mineur - type"
    PHC_015        "Endroit habituel pour soins immédiats - bureau de médecin - type"
    PHC_020        "A un fournisseur habituel de soins de santé"
    PHC_025A       "Aucun fournisseur habituel de soins - pas besoin"
    PHC_025B       "Aucun fournisseur habituel de soins - aucun disponible dans la région"
    PHC_025C       "Aucun fournisseur habituel de soins - ne prend pas nouveaux patients"
    PHC_025D       "Aucun fournisseur habituel de soins - n'a pas essayé d'en trouver un"
    PHC_025E       "Aucun fournisseur habituel de soins - parti / retraité"
    PHC_025F       "Aucun fournisseur habituel de soins - autre"
    PHC_030        "Fournisseur habituel de soins de santé - type"
    PHC_035        "Soins immédiats pour problème mineur - temps d'attente"
    PHC_040        "Fournisseur habituel de soins de santé - langue de communication"
    PHC_045        "Fournisseur habituel de soins de santé - infirmières impliquées"
    PHC_050        "Fournisseur habituel soins santé - autres professionnels même bureau"
    PHC_055A       "Autre fournisseur habituel de soins de santé - autre médecin"
    PHC_055B       "Autre fournisseur habituel de soins de santé - spécialiste"
    PHC_055C       "Autre fournisseur habituel de soins de santé - infirmière"
    PHC_055D       "Autre fournisseur habituel de soins de santé - chiropraticien"
    PHC_055E       "Autre fournisseur habituel de soins de santé - diététiste autorisé"
    PHC_055F       "Autre fournisseur habituel de soins de santé - pharmacien"
    PHC_055G       "Autre fournisseur habituel de soins de santé - physiothérapeute"
    PHC_055H       "Autre fournisseur habituel de soins de santé - psychologue"
    PHC_055I       "Autre fournisseur habituel de soins de santé - travailleur social"
    PHC_055J       "Autre fournisseur habituel de soins de santé - autre"
    PHC_055K       "Autre fournisseur habituel de soins de santé - aucun"
    PHC_060        "Niveau de coordination entre fournisseur habituel de soins et autres"
    DOHMC          "Services de soins de santé à domicile - Ind d'inclusion - (F)"
    HMC_005A       "Soins à domicile reçus - soins infirmiers - 12 mo"
    HMC_005B       "Soins à domicile reçus - autres soins de santé - 12 mo"
    HMC_005C       "Soins à domicile reçus - équipements médicaux - 12 mo"
    HMC_005D       "Soins à domicile reçus - soins personnels / aide ménagère - 12 mo"
    HMC_005G       "Soins à domicile reçus - soins palliatifs / fin de vie - 12 mo"
    HMC_005E       "Soins à domicile reçus - autres services - 12 mo"
    HMC_005F       "N'a pas reçu de soins à domicile - 12 mo"
    HMC_10_1       "Personne à qui services fournis - soins infirmiers"
    HMC_10_2       "Personne à qui services fournis - autres soins de santé"
    HMC_10_3       "Personne à qui services fournis - équipements médicaux"
    HMC_10_4       "Personne à qui services fournis - soins pers / aide ménagère"
    HMC_10_6       "Personne à qui services fournis - soins palliatifs"
    HMC_10_5       "Personne à qui services fournis - autres services"
    HMC_15_1       "Durée services fournis - soins infirmiers"
    HMC_15_2       "Durée services fournis - autres soins de santé"
    HMC_15_3       "Durée services fournis -  équipements médicaux"
    HMC_15_4       "Durée services fournis - soins pers / aide ménagère"
    HMC_15_6       "Durée services fournis - soins palliatifs"
    HMC_15_5       "Durée services fournis - autres services"
    HMC_20_1       "Coût mensuel services fournis - soins infirmiers - 12 mo"
    HMC_20_2       "Coût mensuel services fournis - autres soins de santé - 12 mo"
    HMC_20_3       "Coût mensuel services fournis - équipements médicaux - 12 mo"
    HMC_20_4       "Coût mensuel services fournis - soins pers / aide ménagère - 12 mo"
    HMC_20_6       "Coût mensuel services fournis - soins palliatifs - 12 mo"
    HMC_20_5       "Coût mensuel services fournis - autres services - 12 mo"
    HMC_025A       "Qui a payé soins à domicile - eux-mêmes"
    HMC_025B       "Qui a payé soins à domicile - famille / ami dans même ménage"
    HMC_025C       "Qui a payé soins à domicile - quelqu'un à l'extérieur du ménage"
    HMC_025D       "Qui a payé soins à domicile - assurances"
    HMC_025E       "Qui a payé soins à domicile - gouvernement"
    HMC_025F       "Qui a payé soins à domicile - autre"
    HMC_030        "Satisfaction avec les services de soins à domicile reçus"
    HMC_035A       "Soins à domicile non satisfaisants - mauvaise qualité"
    HMC_035B       "Soins à domicile non satisfaisants - besoins insatisfaits"
    HMC_035C       "Soins à domicile non satisfaisants - services insuffisants"
    HMC_035D       "Soins à domicile non satisfaisants - temps attente trop long"
    HMC_035E       "Soins à domicile non satisfaisants - autre raison"
    HMC_037        "Soins à domicile a aidé à demeurer à la maison"
    HMC_038A       "Soins à domicile pas aidé à demeurer maison - mauvaise qualité"
    HMC_038B       "Soins à domicile pas aidé à demeurer maison - besoins insatisfaits"
    HMC_038C       "Soins à domicile pas aidé à demeurer maison - services insuffisants"
    HMC_038D       "Soins à domicile pas aidé à demeurer maison - temps attente trop long"
    HMC_038E       "Soins à domicile pas aidé à demeurer maison - coût trop élevé"
    HMC_038F       "Soins à domicile pas aidé à demeurer maison - autre raison"
    HMC_040        "Perception soins à domicile requis mais pas reçus - 12 mo"
    HMC_045        "Soins à domicile requis - pour qui"
    HMC_050A       "Soins à domicile requis - soins infirmiers"
    HMC_050B       "Soins à domicile requis - autres soins de santé"
    HMC_050C       "Soins à domicile requis - équipements médicaux"
    HMC_050D       "Soins à domicile requis - soins personnels / aide ménagère"
    HMC_050F       "Soins à domicile requis - soins palliatifs / fin de vie"
    HMC_050E       "Soins à domicile requis - autres services"
    HMC_055A       "Soins à domicile non-reçus - non disponibles dans la région"
    HMC_055B       "Soins à domicile non-reçus - non disponibles au moment requis"
    HMC_055C       "Soins à domicile non-reçus - temps d'attente trop long"
    HMC_055D       "Soins à domicile non-reçus - coût"
    HMC_055E       "Soins à domicile non-reçus - ne s'en est pas occupé"
    HMC_055F       "Soins à domicile non-reçus - ne savait pas où aller"
    HMC_055G       "Soins à domicile non-reçus - barrière linguistique"
    HMC_055H       "Soins à domicile non-reçus - décidé de ne pas demander"
    HMC_055I       "Soins à domicile non-reçus - médecin ne jugeait pas nécessaire"
    HMC_055J       "Soins à domicile non-reçus - pas admissible aux soins à domicile"
    HMC_055K       "Soins à domicile non-reçus - toujours en attente"
    HMC_055L       "Soins à domicile non-reçus - autre"
    HMC_060A       "Prestataire de soins à domicile - programme du govt"
    HMC_060B       "Prestataire de soins à domicile - organisme privé"
    HMC_060C       "Prestataire de soins à domicile - famille / ami / voisin"
    HMC_060D       "Prestataire de soins à domicile - organisme bénévole"
    HMC_060E       "Prestataire de soins à domicile - n'a pas tenté d'en obtenir"
    HMC_060F       "Prestataire de soins à domicile - autre"
    HMCDVVRH       "Soins de santé à domicile reçus - (D)"
    HMCDVHLP       "Ménages où services soins domicile ont aidé à demeurer à maison - (D)"
    DOLBF          "Population active - Ind d'inclusion - (F)"
    LBF_01         "A travaillé à un emploi / entreprise - semaine dernière"
    LBF_02         "Absent de l'emploi / entreprise - semaine dernière"
    LBF_03         "Absent de l'emploi / entreprise - raison - semaine dernière"
    LBF_10         "Employé ou travaille à son compte"
    LBFF11         "Réponse inscrite - nom de l'entreprise (travailleur autonome) - (F)"
    LBFF12         "Réponse inscrite - nom de compagnie / entreprise / personne - (F)"
    LBFF13         "Réponse inscrite - type d'entreprise / industrie / service - (F)"
    LBFCSIC        "Système classification industries de l'Amérique du Nord (SCIAN) 2017"
    LBFF14         "Réponse inscrite - type de travail / occupation - (F)"
    LBFF15         "Réponse inscrite - activités principales - (F)"
    LBFCSOC        "Classification nationale des professions (CNP) 2016"
    LBF_16         "Nbre heures travaillées habituellement / semaine - emploi princ actuel"
    LBF_030        "Avait plus d'un emploi / entreprise - semaine dernière"
    LBF_035        "Nbre heures travaillées habituellement / semaine - autre emploi actuel"
    LBFDVWSS       "Statut d'emploi de la semaine dernière - (D)"
    LBFDVING       "Groupe d'industrie - (D)"
    LBFDVOCG       "Groupe professionnel - (D)"
    LBFDVHPW       "Nombre total d'heures habituellement travaillées / semaine - (D)"
    LBFDVPFT       "Statut emploi temps plein / partiel (total heures habituelles) - (D)"
    DOSDC          "Renseignements sociodémographiques - Ind d'inclusion - (F)"
    SDCCCOB        "Pays de naissance - codé"
    SDC_IM2        "Province / territoire de naissance"
    SDC_IM3        "Statut d'immigrant reçu au Canada"
    SDC_IM4        "Année est devenu immigrant reçu au Canada"
    SDC_010A       "Origine ethnique / culturelle - Canadien"
    SDC_010B       "Origine ethnique / culturelle - Français"
    SDC_010C       "Origine ethnique / culturelle - Anglais"
    SDC_010D       "Origine ethnique / culturelle - Allemand"
    SDC_010E       "Origine ethnique / culturelle - Écossais"
    SDC_010F       "Origine ethnique / culturelle - Irlandais"
    SDC_010G       "Origine ethnique / culturelle - Italien"
    SDC_010H       "Origine ethnique / culturelle - Ukrainien"
    SDC_010I       "Origine ethnique / culturelle - Hollandais (Néerlandais)"
    SDC_010J       "Origine ethnique / culturelle - Chinois"
    SDC_010K       "Origine ethnique / culturelle - Juif"
    SDC_010L       "Origine ethnique / culturelle - Polonais"
    SDC_010M       "Origine ethnique / culturelle - Portugais"
    SDC_010N       "Origine ethnique / culturelle - Sud-Asiatique"
    SDC_010O       "Origine ethnique / culturelle - Norvégien"
    SDC_010P       "Origine ethnique / culturelle - Gallois"
    SDC_010Q       "Origine ethnique / culturelle - Suédois"
    SDC_010R       "Origine ethnique / culturelle - Premières nations"
    SDC_010S       "Origine ethnique / culturelle - Métis"
    SDC_010T       "Origine ethnique / culturelle - Inuit"
    SDC_010U       "Origine ethnique / culturelle - autre"
    SDC_015        "Identité autochtone - Première Nation / Métis / Inuk (Inuit)"
    SDC_016A       "Autochtone - Première nation"
    SDC_016B       "Autochtone - Métis"
    SDC_016C       "Autochtone - Inuk (Inuit)"
    SDC_020A       "Appartenance groupes raciaux / culturels - Blanc"
    SDC_020B       "Appartenance groupes raciaux / culturels  - Sud-Asiatique"
    SDC_020C       "Appartenance groupes raciaux / culturels  - Chinois"
    SDC_020D       "Appartenance groupes raciaux / culturels  - Noir"
    SDC_020E       "Appartenance groupes raciaux / culturels - Philippin"
    SDC_020F       "Appartenance groupes raciaux / culturels  - Latino-Américain"
    SDC_020G       "Appartenance groupes raciaux / culturels  - Arabe"
    SDC_020H       "Appartenance groupes raciaux / culturels - Asiatique du Sud-Est"
    SDC_020I       "Appartenance groupes raciaux / culturels - Asiatique occidental"
    SDC_020J       "Appartenance groupes raciaux / culturels  - Coréen"
    SDC_020K       "Appartenance groupes raciaux / culturels  - Japonais"
    VMRNIE         "Appartenance groupes raciaux / culturels  - minorité visible n.i.a."
    VMROTHER       "Appartenance groupes raciaux / culturels  - pas une minorité visible"
    SDC_025        "Connaissance des langues officielles"
    SDC_027        "Service militaire canadien"
    SDC_037        "Orientation sexuelle"
    DHH_OWN        "Régime de propriété - Propriétaire ou locataire"
    SDCC2_1        "Langue parlée plus souvent à la maison - 1ère réponse"
    SDCC2_2        "Langue parlée plus souvent à la maison - 2e réponse"
    SDCC2_3        "Langue parlée plus souvent à la maison - 3e réponse"
    SDCC3_1        "Langue maternelle - 1ère réponse"
    SDCC3_2        "Langue maternelle - 2e réponse"
    SDCC3_3        "Langue maternelle - 3e réponse"
    SDCDVCB        "Pays de naissance - groupée - (D)"
    SDCDVIMM       "Indicateur d'immigrant - (D)"
    SDCDVRES       "Nombre d'années au Canada depuis l'immigration - (D)"
    SDCDVALI       "Âge - répondant devenu immigrant reçu la 1ère fois au Canada - (D)"
    SDCDVABT       "Identité autochtone - (D)"
    SDCDVVM        "Groupe de minorité visible du répondant - (D)"
    SDCDVFLA       "Indicateur de minorité visible - (D)"
    SDCDVLHM       "Langue(s) parlée(s) le plus souvent à la maison - (D)"
    SDCDVFL1       "Première langue apprise dans l'enfance - langue maternelle - (D)"
    SDCDVFLS       "Première langue officielle parlée - (D)"
    DOPMK          "Personne la mieux renseignée au sujet du ménage - Ind d'inclusion (F)"
    PMKPROXY       "Personne la mieux renseignée au sujet du ménage - (F)"
    DOFSC          "Sécurité alimentaire - Ind d'inclusion - (F)"
    FSC_010        "Peur de manquer de nourriture - 12 mo"
    FSC_015        "Plus de nourriture et pas d'argent pour acheter d'autre - 12 mo"
    FSC_020        "N'avait pas les moyens de manger repas équilibrés - 12 mo"
    FSC_025        "Comptait sur aliments peu coûteux pour nourrir les enfants - 12 mo"
    FSC_030        "Ne pouvait pas servir repas équilibrés aux enfants - 12 mo"
    FSC_035        "Enfants ne mangeaient pas assez - 12 mo"
    FSC_040        "Adultes ont sauté ou réduit la portion des repas - 12 mo"
    FSC_045        "Adultes ont sauté ou réduit les repas - fréquence - 12 mo"
    FSC_050        "A mangé moins qu'aurait dû - 12 mo"
    FSC_055        "A eu faim mais pas les moyens d'avoir assez de nourriture - 12 mo"
    FSC_060        "A perdu du poids pcq pas assez d'argent pour nourriture - 12 mo"
    FSC_065        "Adultes ont passé journée entière sans manger - 12 mo"
    FSC_070        "Adultes ont passé journée entière sans manger - fréquence - 12 mo"
    FSC_075        "A réduit la portion des repas des enfants - 12 mo"
    FSC_080        "Enfants ont sauté des repas - 12 mo"
    FSC_085        "Enfants ont sauté des repas - fréquence - 12 mo"
    FSC_090        "Enfants ont eu faim mais pas moyens d'avoir plus nourriture - 12 mo"
    FSC_095        "Enfants ont passé une journée entière sans manger - 12 mo"
    FSCDVAF2       "Sécurité alimentaire - état des adultes (incluant marginale) - (D)"
    FSCDVCF2       "Sécurité alimentaire - état des enfants (incluant marginale) - (D)"
    FSCDVHF2       "État de sécurité alimentaire du ménage - (incluant marginale) - (D)"
    DOADM          "Renseignements administratifs - Ind d'inclusion - (F)"
    ADM_040        "Interview effectuée au téléphone ou en face à face"
    ADM_045        "Répondant seul durant l'interview"
    ADM_050        "Réponses possiblement biaisées par la présence d'une autre personne"
    ADM_055        "Langue de l'interview"
    CASEMODE       "Plateforme de collecte"
    WTS_S          "Poids échantillon - Partage"
    .
 
