 format
    GEO_PRV     PROVFM.  
    GEODPC     $GEO3DPMF.
    GEODHR4     HR2007FM.
    GEODSHR     GEOSHRFM.
    GEODDHA     GEODHAFM.
    GEODLHA     GEOLHAFM.
    GEODLHN     GEOLHIN. 
    GEODSAT     GEOSATFM.
    GEODCMA6    DVCMA6FM.
    GEODPG09    GEO_PRG. 
    GEODUR      GEODURFM.
    GEODUR2     GEO_2UR. 
    GEODPSZ     GEODPSFM.
    SAM_CP     $S_CP09FM.
    SAM_TYP     SAME_TYP.
    SAMDSHR     YESNOFM. 
    SAMDLNK     YESNOFM. 
    ADM_STA     ADM_STA. 
    ADM_PRX     YESNOFM. 
    ADM_YOI     YEARXFM. 
    ADM_MOI     MONTHFM. 
    ADM_DOI     DAYFM.   
    ADM_N09     TELFM.   
    ADM_N10     YESNOFM. 
    ADM_N11     YESNOFM. 
    ADM_N12     ADM_LNG. 
    ADM_LHH     AM3_LP.  
    DHH_AGE     AGE3DFM. 
    DHH_YOB     YEARFM.  
    DHH_MOB     MONTHFM. 
    DHH_DOB     DAYFM.   
    DHH_SEX     DHC_SEX. 
    DHH_MS      DHC_MAR. 
    DHHDSAGE    AGE3DFM. 
    DHHDYKD     PERS2D.  
    DHHDOKD     PERS2D.  
    DHHDLE5     PERS2D.  
    DHHD611     PERS2D.  
    DHHDL12     PERS2D.  
    DHHDL18     PERS2D.  
    DHHDLVG     DHCDLVG. 
    DHHDECF     DHCDECF. 
    DHHDHSZ     PERS2D.  
    GEN_01      GOOD5FM. 
    GEN_02      GEN_2F.  
    GEN_02A2    GEN02AFM.
    GEN_02B     GOOD5FM. 
    GEN_07      STC_1F.  
    GEN_08      YESNOFM. 
    GEN_09      STC_1F.  
    GEN_10      GEN_10F. 
    GENDHDI     GHCDHDI. 
    GENDMHI     GHCDHDI. 
    GENGSWL     SCR_01FM.
    MAM_037     YESNOFM. 
    HWT_2       HWC_2FM. 
    HWT_2A      HWC_2A.  
    HWT_2B      HWC_2B.  
    HWT_2C      HWC_2C.  
    HWT_2D      HWC_2D.  
    HWT_2E      HWC_2E.  
    HWT_2F      HWC_2F.  
    HWT_3       HWT_FM.  
    HWT_N4      WHTFM.   
    HWT_4       HWS_1F.  
    HWTDHTM     HWT_METR.
    HWTDWTK     HWT_WTK. 
    HWTDBMI     HWTD_BMI.
    HWTDISW     HWTCDISW.
    HWTDCOL     HWTDDCOL.
    CCC_031     YESNOFM. 
    CCC_035     YESNOFM. 
    CCC_036     YESNOFM. 
    CCC_051     YESNOFM. 
    CCC_061     YESNOFM. 
    CCC_071     YESNOFM. 
    CCC_072     YESNOFM. 
    CCC_073     YESNOFM. 
    CCC_073A    YESNOFM. 
    CCC_073B    YESNOFM. 
    CCC_081     YESNOFM. 
    CCC_091     YESNOFM. 
    CCC_101     YESNOFM. 
    CCC_102     AGE3DFM. 
    CCC_10A     YESNOFM. 
    CCC_10B     YESNOFM. 
    CCC_10C     CCC_10C. 
    CCC_105     YESNOFM. 
    CCC_106     YESNOFM. 
    CCC_121     YESNOFM. 
    CCC_131     YESNOFM. 
    CCC_31A     YESNOFM. 
    CCC_141     YESNOFM. 
    CCC_151     YESNOFM. 
    CCC_161     YESNOFM. 
    CCC_171     YESNOFM. 
    CCC_17A     CCC17AFM.
    CCC_181     YESNOFM. 
    CCC_280     YESNOFM. 
    CCC_290     YESNOFM. 
    CCCDDIA     CCCDIAFM.
    DOHUI       YESNOFM. 
    HUI_01      YESNOFM. 
    HUI_02      YESNOFM. 
    HUI_03      YESNOFM. 
    HUI_04      YESNOFM. 
    HUI_05      YESNOFM. 
    HUI_06      YESNOFM. 
    HUI_07      YESNOFM. 
    HUI_07A     YESNOFM. 
    HUI_08      YESNOFM. 
    HUI_09      YESNOFM. 
    HUI_10      YESNOFM. 
    HUI_11      YESNOFM. 
    HUI_12      YESNOFM. 
    HUI_13      YESNOFM. 
    HUI_14      YESNOFM. 
    HUI_15      YESNOFM. 
    HUI_16      YESNOFM. 
    HUI_17      YESNOFM. 
    HUI_18      YESNOFM. 
    HUI_19      HSC_19F. 
    HUI_20      YESNOFM. 
    HUI_21      YESNOFM. 
    HUI_22      YESNOFM. 
    HUI_23      HSC_23F. 
    HUI_24      YESNOFM. 
    HUI_25      HSC_25F. 
    HUI_26      HSC_26F. 
    HUI_27      HSC_27F. 
    HUIDVIS     HUIDVIFM.
    HUIDHER     HUIDHEFM.
    HUIDSPE     HUIDSPFM.
    HUIDMOB     HUIDMOFM.
    HUIDDEX     HUIDEXFM.
    HUIDEMO     HUIDEMFM.
    HUIDCOG     HUIDCOFM.
    HUIDHSI     HUIDHSI. 
    HUP_01      YESNOFM. 
    HUP_02      HSC_29F. 
    HUP_03      HSC_30F. 
    HUPDPAD     HSCDPAD. 
    HCU_1AA     YESNOFM. 
    HCU_1BA     YESNOFM. 
    HCU_1BB     YESNOFM. 
    HCU_1BC     YESNOFM. 
    HCU_1BD     YESNOFM. 
    HCU_1BE     YESNOFM. 
    HCU_1A1     YESNOFM. 
    HCU_1A2     HCU1A2FM.
    HCU_1AC     ADM_LN2G.
    CHP_01      YESNOFM. 
    CHP_02      NIGHT3D. 
    CHP_03      YESNOFM. 
    CHP_04      TIMES3D. 
    CHP_05      HCC_CONT.
    CHP_06      YESNOFM. 
    CHP_07      TIMES2D. 
    CHP_08      YESNOFM. 
    CHP_09      TIMES3D. 
    CHP_10      HCC_CONT.
    CHP_11      YESNOFM. 
    CHP_12      TIMES3D. 
    CHP_13      HCC_CONT.
    CHP_14      YESNOFM. 
    CHP_15      TIMES3D. 
    CHP_16      YESNOFM. 
    CHP_17      TIMES3D. 
    CHP_18      YESNOFM. 
    CHP_19      TIMES3D. 
    CHP_20      YESNOFM. 
    CHP_21      TIMES3D. 
    CHP_22      YESNOFM. 
    CHP_23      TIMES3D. 
    CHP_24      YESNOFM. 
    CHP_25      TIMES3D. 
    CHPDMDC     CON3DFM. 
    CHPFCOP     YESNOFM. 
    RAC_1       SOMETIME.
    RAC_2A      SOMETIME.
    RAC_2B1     RAC2B1FM.
    RAC_2B2     RAC2B2FM.
    RAC_2C      SOMETIME.
    RAC_5       RAC_5FM. 
    RACDIMP     SOMETIME.
    RACDPAL     SOMETIME.
    DOADL       YESNOFM. 
    ADL_01      YESNOFM. 
    ADL_02      YESNOFM. 
    ADL_03      YESNOFM. 
    ADL_04      YESNOFM. 
    ADL_05      YESNOFM. 
    ADL_06      YESNOFM. 
    ADLF6R      YESNOFM. 
    FLU_160     YESNOFM. 
    FLU_162     FS52F.   
    FLU_164     MONTHFM. 
    FLU_165     INJ_4F.  
    FLU_66A     YESNOFM. 
    FLU_66B     YESNOFM. 
    FLU_66C     YESNOFM. 
    FLU_66D     YESNOFM. 
    FLU_66E     YESNOFM. 
    FLU_66F     YESNOFM. 
    FLU_66G     YESNOFM. 
    FLU_66H     YESNOFM. 
    FLU_66I     YESNOFM. 
    FLU_66J     YESNOFM. 
    FLU_66K     YESNOFM. 
    FLU_66L     YESNOFM. 
    FLU_66M     YESNOFM. 
    FLU_66O     YESNOFM. 
    FLU_66N     YESNOFM. 
    FVC_1A      FVC_1A.  
    FVC_1B      TIMES2D. 
    FVC_1C      TIMES2D. 
    FVC_1D      TIMES3D. 
    FVC_1E      TIMES3D. 
    FVC_2A      FVC_1A.  
    FVC_2B      TIMES2D. 
    FVC_2C      TIMES2D. 
    FVC_2D      TIMES3D. 
    FVC_2E      TIMES3D. 
    FVC_3A      FVC_1A.  
    FVC_3B      TIMES2D. 
    FVC_3C      TIMES2D. 
    FVC_3D      TIMES3D. 
    FVC_3E      TIMES3D. 
    FVC_4A      FVC_1A.  
    FVC_4B      TIMES2D. 
    FVC_4C      TIMES2D. 
    FVC_4D      TIMES3D. 
    FVC_4E      TIMES3D. 
    FVC_5A      FVC_1A.  
    FVC_5B      TIMES2D. 
    FVC_5C      TIMES2D. 
    FVC_5D      TIMES3D. 
    FVC_5E      TIMES3D. 
    FVC_6A      FVC_1A.  
    FVC_6B      SERV2FM. 
    FVC_6C      SERV2FM. 
    FVC_6D      SERV3FM. 
    FVC_6E      SERV3FM. 
    FVCDJUI     FVC_DC.  
    FVCDFRU     FVC_DC.  
    FVCDSAL     FVC_DC.  
    FVCDPOT     FVC_DC.  
    FVCDCAR     FVC_DC.  
    FVCDVEG     FVC_PO.  
    FVCDTOT     FVC_SP.  
    FVCGTOT     FVC_RDA. 
    PAC_1A      YESNOFM. 
    PAC_1B      YESNOFM. 
    PAC_1C      YESNOFM. 
    PAC_1D      YESNOFM. 
    PAC_1E      YESNOFM. 
    PAC_1F      YESNOFM. 
    PAC_1G      YESNOFM. 
    PAC_1H      YESNOFM. 
    PAC_1I      YESNOFM. 
    PAC_1J      YESNOFM. 
    PAC_1K      YESNOFM. 
    PAC_1L      YESNOFM. 
    PAC_1M      YESNOFM. 
    PAC_1N      YESNOFM. 
    PAC_1O      YESNOFM. 
    PAC_1P      YESNOFM. 
    PAC_1Q      YESNOFM. 
    PAC_1R      YESNOFM. 
    PAC_1S      YESNOFM. 
    PAC_1T      YESNOFM. 
    PAC_1Z      YESNOFM. 
    PAC_1U      YESNOFM. 
    PAC_1V      YESNOFM. 
    PAC_1W      YESNOFM. 
    PAC_1X      YESNOFM. 
    PAC_2A      TIMES3D. 
    PAC_3A      PAC_TIME.
    PAC_2B      TIMES3D. 
    PAC_3B      PAC_TIME.
    PAC_2C      TIMES3D. 
    PAC_3C      PAC_TIME.
    PAC_2D      TIMES3D. 
    PAC_3D      PAC_TIME.
    PAC_2E      TIMES3D. 
    PAC_3E      PAC_TIME.
    PAC_2F      TIMES3D. 
    PAC_3F      PAC_TIME.
    PAC_2G      TIMES3D. 
    PAC_3G      PAC_TIME.
    PAC_2H      TIMES3D. 
    PAC_3H      PAC_TIME.
    PAC_2I      TIMES3D. 
    PAC_3I      PAC_TIME.
    PAC_2J      TIMES3D. 
    PAC_3J      PAC_TIME.
    PAC_2K      TIMES3D. 
    PAC_3K      PAC_TIME.
    PAC_2L      TIMES3D. 
    PAC_3L      PAC_TIME.
    PAC_2M      TIMES3D. 
    PAC_3M      PAC_TIME.
    PAC_2N      TIMES3D. 
    PAC_3N      PAC_TIME.
    PAC_2O      TIMES3D. 
    PAC_3O      PAC_TIME.
    PAC_2P      TIMES3D. 
    PAC_3P      PAC_TIME.
    PAC_2Q      TIMES3D. 
    PAC_3Q      PAC_TIME.
    PAC_2R      TIMES3D. 
    PAC_3R      PAC_TIME.
    PAC_2S      TIMES3D. 
    PAC_3S      PAC_TIME.
    PAC_2T      TIMES3D. 
    PAC_3T      PAC_TIME.
    PAC_2Z      TIMES3D. 
    PAC_3Z      PAC_TIME.
    PAC_2U      TIMES3D. 
    PAC_3U      PAC_TIME.
    PAC_2W      TIMES3D. 
    PAC_3W      PAC_TIME.
    PAC_2X      TIMES3D. 
    PAC_3X      PAC_TIME.
    PAC_7       PACF_7FM.
    PAC_7A      TIMES3D. 
    PAC_7B      PAC_TIME.
    PAC_8       PACF_7FM.
    PAC_8A      TIMES3D. 
    PAC_8B      PAC_TIME.
    PACDEE      PACDEE.  
    PACFLEI     YESNOFM. 
    PACDFM      PACDFM.  
    PACDFR      PACDFR.  
    PACFD       YESNOFM. 
    PACDPAI     PACDPAI. 
    PACDLTI     PACDPAI. 
    PACDTLE     PACDTLFM.
    PACFLTI     YESNOFM. 
    DOUPE       YESNOFM. 
    UPE_01A     YESNOFM. 
    UPE_01      PAC_5F.  
    UPE_02      YESNOFM. 
    UPE_02A     PAC_5F.  
    UPE_02B     PAC_5F.  
    UPE_02C     PAC_5F.  
    UPE_02D     PAC_5F.  
    UPE_03A     UPEC3AFM.
    UPE_03B     UPEC3AFM.
    UPE_04A     PAC_5F.  
    UPE_05A     PAC_5F.  
    UPE_05B     PAC_5F.  
    UPE_06      YESNOFM. 
    UPE_06A     PAC_5F.  
    UPE_06B     PAC_5F.  
    UPE_06C     PAC_5F.  
    UPE_07      YESNOFM. 
    UPE_07A     PAC_5F.  
    UPEFILS     YESNOFM. 
    UPEFSKB     YESNOFM. 
    UPEFSNB     YESNOFM. 
    DOINJ       YESNOFM. 
    REP_1A      YESNOFM. 
    REP_2       YESNOFM. 
    REP_3       RPC03FM. 
    REP_3A      YESNOFM. 
    REP_4       YESNOFM. 
    REP_5A      YESNOFM. 
    REP_5B      YESNOFM. 
    REP_5C      YESNOFM. 
    REP_5D      YESNOFM. 
    REP_5F      YESNOFM. 
    REP_5G      YESNOFM. 
    REP_5H      YESNOFM. 
    REP_5I      YESNOFM. 
    INJ_01      YESNOFM. 
    INJ_02      TIMES2D. 
    INJ_03      MONTHFM. 
    INJ_04      INJ_4F.  
    INJ_05      IJC03F.  
    INJ_06      IJC04F.  
    INJ_07      IJC_4A.  
    INJ_08      IJC05F.  
    INJ_09      INJQ09FM.
    INW_01      YESNOFM. 
    INWF02      YESNOFM. 
    INWF03      YESNOFM. 
    INWF03S     YESNOFM. 
    INWF04      YESNOFM. 
    INWDOCG    $LBSDOCFM.
    INWDING    $LBSDINFM.
    INJ_10      YESNOFM. 
    INJ_11A     INJ11AFM.
    INJ_12      IJC_10B. 
    INJ_12A     INJ12AFM.
    INJ_13      YESNOFM. 
    INJ_14A     YESNOFM. 
    INJ_14B     YESNOFM. 
    INJ_14C     YESNOFM. 
    INJ_14L     YESNOFM. 
    INJ_14M     YESNOFM. 
    INJ_14F     YESNOFM. 
    INJ_14N     YESNOFM. 
    INJ_14O     YESNOFM. 
    INJ_14K     YESNOFM. 
    INJ_15      YESNOFM. 
    INJ_15A     YESNOFM. 
    INJ_16      YESNOFM. 
    INJ_17      IJC_NUM. 
    INJDTBS     INJ_TBS. 
    INJDCAU     INJ_CAU. 
    INJDCBP     IJCD2FM. 
    INJDSTT     INJ_STT. 
    SMK_01A     YESNOFM. 
    SMK_01B     YESNOFM. 
    SMK_01C     AGE3DFM. 
    SMK_202     SMC_2F.  
    SMK_203     AGE3DFM. 
    SMK_204     CIG_NUM. 
    SMK_05B     CIG_NUM. 
    SMK_05C     DAY2DFM. 
    SMK_05D     YESNOFM. 
    SMK_06A     SMKCFM.  
    SMK_06B     MONTHFM. 
    SMK_06C     YEAR3NUM.
    SMK_207     AGE3DFM. 
    SMK_208     CIG_NUM. 
    SMK_09A     SMKCFM.  
    SMK_09B     MONTHFM. 
    SMK_09C     YEAR3NUM.
    SMK_10      YESNOFM. 
    SMK_10A     SMKCFM.  
    SMK_10B     MONTHFM. 
    SMK_10C     YEAR3NUM.
    SMKDSTY     SMCDTYP. 
    SMKDSTP     YEAR3NUM.
    SMKDYCS     YEAR3NUM.
    ETS_10      YESNOFM. 
    ETS_11      PERS2D.  
    ETS_20      YESNOFM. 
    ETS_20B     YESNOFM. 
    ETS_35      YESNOFM. 
    ETS_36      YESNOFM. 
    ETS_37A     YESNOFM. 
    ETS_37B     YESNOFM. 
    ETS_37C     YESNOFM. 
    ETS_37D     YESNOFM. 
    ALC_1       YESNOFM. 
    ALC_2       ALC6_2F. 
    ALC_3       ALC_3F.  
    ALCDTTM     ALCDTTFM.
    MEX_01      YESNOFM. 
    MEX_01A     YEARFM.  
    MEX_02      YESNOFM. 
    MEX_03      YESNOFM. 
    MEX_04      MEXE4FM. 
    MEX_05      YESNOFM. 
    MEX_06      MEXE06FM.
    MEX_07      MEXE07FM.
    MEX_08      MEXE8FM. 
    MEX_09      YESNOFM. 
    MEX_10      MEXE0FM. 
    MEXDEBF     MEXCDEFM.
    MEXFEB6     YESNOFM. 
    DOSXB       YESNOFM. 
    SXB_1       YESNOFM. 
    SXB_2       AGE3DFM. 
    SXB_3       YESNOFM. 
    SXB_4       SHS_4F.  
    SXB_07      YESNOFM. 
    SXB_7A      YESNOFM. 
    SXB_09      AGREEFM. 
    SXB_10      SXB102FM.
    SXB_11      YESNOFM. 
    SXB_12A     YESNOFM. 
    SXB_12B     YESNOFM. 
    SXB_12C     YESNOFM. 
    SXB_12D     YESNOFM. 
    SXB_12F     YESNOFM. 
    SXB_12E     YESNOFM. 
    SXB_13A     YESNOFM. 
    SXB_13B     YESNOFM. 
    SXB_13C     YESNOFM. 
    SXB_13D     YESNOFM. 
    SXB_13F     YESNOFM. 
    SXB_13G     YESNOFM. 
    SXB_13E     YESNOFM. 
    SDC_1       SDC_1FM. 
    SDC_2       YESNOFM. 
    SDC_3       SDYEARFM.
    SDC_4A      YESNOFM. 
    SDC_4B      YESNOFM. 
    SDC_4C      YESNOFM. 
    SDC_4D      YESNOFM. 
    SDC_4E      YESNOFM. 
    SDC_4F      YESNOFM. 
    SDC_4G      YESNOFM. 
    SDC_4H      YESNOFM. 
    SDC_4I      YESNOFM. 
    SDC_4J      YESNOFM. 
    SDC_4K      YESNOFM. 
    SDC_4L      YESNOFM. 
    SDC_4M      YESNOFM. 
    SDC_4N      YESNOFM. 
    SDC_4T      YESNOFM. 
    SDC_4U      YESNOFM. 
    SDC_4V      YESNOFM. 
    SDC_4P      YESNOFM. 
    SDC_4Q      YESNOFM. 
    SDC_4R      YESNOFM. 
    SDC_4S      YESNOFM. 
    SDC_41      YESNOFM. 
    SDC_42A     YESNOFM. 
    SDC_42B     YESNOFM. 
    SDC_42C     YESNOFM. 
    SDC_43A     YESNOFM. 
    SDC_43B     YESNOFM. 
    SDC_43C     YESNOFM. 
    SDC_43D     YESNOFM. 
    SDC_43E     YESNOFM. 
    SDC_43F     YESNOFM. 
    SDC_43G     YESNOFM. 
    SDC_43H     YESNOFM. 
    SDC_43I     YESNOFM. 
    SDC_43J     YESNOFM. 
    SDC_43K     YESNOFM. 
    SDC_43M     YESNOFM. 
    SDC_5A      YESNOFM. 
    SDC_5B      YESNOFM. 
    SDC_5C      YESNOFM. 
    SDC_5D      YESNOFM. 
    SDC_5E      YESNOFM. 
    SDC_5F      YESNOFM. 
    SDC_5G      YESNOFM. 
    SDC_5H      YESNOFM. 
    SDC_5I      YESNOFM. 
    SDC_5J      YESNOFM. 
    SDC_5K      YESNOFM. 
    SDC_5L      YESNOFM. 
    SDC_5M      YESNOFM. 
    SDC_5N      YESNOFM. 
    SDC_5O      YESNOFM. 
    SDC_5P      YESNOFM. 
    SDC_5Q      YESNOFM. 
    SDC_5R      YESNOFM. 
    SDC_5T      YESNOFM. 
    SDC_5U      YESNOFM. 
    SDC_5V      YESNOFM. 
    SDC_5W      YESNOFM. 
    SDC_5S      YESNOFM. 
    SDC_5AA     YESNOFM. 
    SDC_5AB     YESNOFM. 
    SDC_5AC     YESNOFM. 
    SDC_5AD     YESNOFM. 
    SDC_5AE     YESNOFM. 
    SDC_5AF     YESNOFM. 
    SDC_5AG     YESNOFM. 
    SDC_5AH     YESNOFM. 
    SDC_5AI     YESNOFM. 
    SDC_5AJ     YESNOFM. 
    SDC_5AK     YESNOFM. 
    SDC_5AL     YESNOFM. 
    SDC_5AM     YESNOFM. 
    SDC_5AN     YESNOFM. 
    SDC_5AO     YESNOFM. 
    SDC_5AP     YESNOFM. 
    SDC_5AQ     YESNOFM. 
    SDC_5AR     YESNOFM. 
    SDC_5AT     YESNOFM. 
    SDC_5AU     YESNOFM. 
    SDC_5AV     YESNOFM. 
    SDC_5AW     YESNOFM. 
    SDC_5AS     YESNOFM. 
    SDC_6A      YESNOFM. 
    SDC_6B      YESNOFM. 
    SDC_6C      YESNOFM. 
    SDC_6D      YESNOFM. 
    SDC_6E      YESNOFM. 
    SDC_6F      YESNOFM. 
    SDC_6G      YESNOFM. 
    SDC_6H      YESNOFM. 
    SDC_6I      YESNOFM. 
    SDC_6J      YESNOFM. 
    SDC_6K      YESNOFM. 
    SDC_6L      YESNOFM. 
    SDC_6M      YESNOFM. 
    SDC_6N      YESNOFM. 
    SDC_6O      YESNOFM. 
    SDC_6P      YESNOFM. 
    SDC_6Q      YESNOFM. 
    SDC_6R      YESNOFM. 
    SDC_6T      YESNOFM. 
    SDC_6U      YESNOFM. 
    SDC_6V      YESNOFM. 
    SDC_6W      YESNOFM. 
    SDC_6S      YESNOFM. 
    DHH_OWN     YESNOFM. 
    SDC_7AA     SDC7AFM. 
    SDCCCB      SDC_CB.  
    SDCGCB      SDGCB7FM.
    SDCDLHM     SDCDLNG. 
    SDCDAIM     AGE3DFM. 
    SDCFIMM     YESNOFM. 
    SDCDRES     AGE3DFM. 
    SDCDLNG     SDCDLNG. 
    SDCDFL1     SDCDLNG. 
    SDCDABT     SDC_ABO. 
    SDCDCGT     SDC_CG.  
    EDU_1       EDUGRADE.
    EDU_2       YESNOFM. 
    EDU_3       YESNOFM. 
    EDU_4       EDUDEGRE.
    SDC_8       YESNOFM. 
    SDC_9       LBF_PFT. 
    EDUDH04     DVED3FM. 
    EDUDH10     EDU_10DR.
    EDUDR04     DVED3FM. 
    EDUDR10     EDU_10DR.
    LBS_01      LSC_1F.  
    LBS_02      YESNOFM. 
    LBS_03      YESNOFM. 
    LBS_11      YESNOFM. 
    LBS_31      LSC_31F. 
    LBSF32      YESNOFM. 
    LBSF33      YESNOFM. 
    LBSF34      YESNOFM. 
    LBSF35      YESNOFM. 
    LBSF35S     YESNOFM. 
    LBSF36      YESNOFM. 
    LBS_42      HOUR3DFM.
    LBS_53      HOUR3DFM.
    LBSDHPW     LSCDHPW. 
    LBSDPFT     LBF_PFT. 
    LBSDWSS     LSCDCWS. 
    LBSDING    $LBSDINFM.
    LBSDOCG    $LBSDOCFM.
    INC_1A      YESNOFM. 
    INC_1B      YESNOFM. 
    INC_1C      YESNOFM. 
    INC_1D      YESNOFM. 
    INC_1E      YESNOFM. 
    INC_1F      YESNOFM. 
    INC_1G      YESNOFM. 
    INC_1O      YESNOFM. 
    INC_1H      YESNOFM. 
    INC_1J      YESNOFM. 
    INC_1I      YESNOFM. 
    INC_1K      YESNOFM. 
    INC_1L      YESNOFM. 
    INC_1M      YESNOFM. 
    INC_1N      YESNOFM. 
    INC_2       INC_Q2FM.
    INC_3       DOLL6FM. 
    INC_5A      INC_5AFM.
    INC_5B      INC_5BFM.
    INC_5C      INC_5CFM.
    INC_6A      YESNOFM. 
    INC_6B      YESNOFM. 
    INC_6C      YESNOFM. 
    INC_6D      YESNOFM. 
    INC_6E      YESNOFM. 
    INC_6F      YESNOFM. 
    INC_6G      YESNOFM. 
    INC_6H      YESNOFM. 
    INC_6I      YESNOFM. 
    INC_6K      YESNOFM. 
    INC_6J      YESNOFM. 
    INC_6L      YESNOFM. 
    INC_6M      YESNOFM. 
    INC_6N      YESNOFM. 
    INC_6O      YESNOFM. 
    INC_7       INC_Q2FM.
    INC_8A      DOLL6FM. 
    INC_8B      INC_8BFM.
    INC_8C      INC_8CFM.
    INC_8D      INCQ8DFM.
    INCDHH      INCPERFM.
    INCDPER     INCPERFM.
    INCDADR     INCRATFM.
    INCDRCA     INCDECFM.
    INCDRPR     INCDECFM.
    INCDRRS     INCDECFM.
    ACCZ_10     YESNOFM. 
    ACCZ_11     YESNOFM. 
    ACCZ_12A    YESNOFM. 
    ACCZ_12B    YESNOFM. 
    ACCZ_12C    YESNOFM. 
    ACCZ_12D    YESNOFM. 
    ACCZ_12E    YESNOFM. 
    ACCZ_12F    YESNOFM. 
    ACCZ_12G    YESNOFM. 
    ACCZ_12H    YESNOFM. 
    ACCZ_12I    YESNOFM. 
    ACCZ_12J    YESNOFM. 
    ACCZ_12K    YESNOFM. 
    ACCZ_12L    YESNOFM. 
    ACCZ_12M    YESNOFM. 
    ACCZ_12N    YESNOFM. 
    ACCZ_20     YESNOFM. 
    ACCZ_21     YESNOFM. 
    ACCZ_22A    YESNOFM. 
    ACCZ_22B    YESNOFM. 
    ACCZ_22C    YESNOFM. 
    ACCZ_22D    YESNOFM. 
    ACCZ_22E    YESNOFM. 
    ACCZ_22F    YESNOFM. 
    ACCZ_22G    YESNOFM. 
    ACCZ_22H    YESNOFM. 
    ACCZ_22I    YESNOFM. 
    ACCZ_22J    YESNOFM. 
    ACCZ_22K    YESNOFM. 
    ACCZ_22L    YESNOFM. 
    ACCZ_22M    YESNOFM. 
    ACCZ_22N    YESNOFM. 
    ACCZ_22O    YESNOFM. 
    ACCZ_30     YESNOFM. 
    ACCZ_31     YESNOFM. 
    ACCZ_32A    YESNOFM. 
    ACCZ_32B    YESNOFM. 
    ACCZ_32C    YESNOFM. 
    ACCZ_32D    YESNOFM. 
    ACCZ_32E    YESNOFM. 
    ACCZ_32F    YESNOFM. 
    ACCZ_32G    YESNOFM. 
    ACCZ_32H    YESNOFM. 
    ACCZ_32I    YESNOFM. 
    ACCZ_32J    YESNOFM. 
    ACCZ_32K    YESNOFM. 
    ACCZ_32L    YESNOFM. 
    ACCZ_32M    YESNOFM. 
    ACCZ_32N    YESNOFM. 
    ACCZ_40     YESNOFM. 
    ACCZ_40A    YESNOFM. 
    ACCZ_40B    YESNOFM. 
    ACCZ_40C    YESNOFM. 
    ACCZ_40D    YESNOFM. 
    ACCZ_40E    YESNOFM. 
    ACCZ_40F    YESNOFM. 
    ACCZ_40G    YESNOFM. 
    ACCZ_41     YESNOFM. 
    ACCZ_42     YESNO.   
    ACCZ_43A    YESNOFM. 
    ACCZ_43B    YESNOFM. 
    ACCZ_43C    YESNOFM. 
    ACCZ_43D    YESNOFM. 
    ACCZ_43E    YESNOFM. 
    ACCZ_43F    YESNOFM. 
    ACCZ_43G    YESNOFM. 
    ACCZ_43H    YESNOFM. 
    ACCZ_43I    YESNOFM. 
    ACCZ_44     YESNO.   
    ACCZ_45A    YESNOFM. 
    ACCZ_45B    YESNOFM. 
    ACCZ_45C    YESNOFM. 
    ACCZ_45D    YESNOFM. 
    ACCZ_45E    YESNOFM. 
    ACCZ_45F    YESNOFM. 
    ACCZ_45G    YESNOFM. 
    ACCZ_45H    YESNOFM. 
    ACCZ_45I    YESNOFM. 
    ACCZ_46     YESNO.   
    ACCZ_47A    YESNOFM. 
    ACCZ_47B    YESNOFM. 
    ACCZ_47C    YESNOFM. 
    ACCZ_47D    YESNOFM. 
    ACCZ_47E    YESNOFM. 
    ACCZ_47F    YESNOFM. 
    ACCZ_47G    YESNOFM. 
    ACCZ_47H    YESNOFM. 
    ACCZ_47I    YESNOFM. 
    ACCZ_50A    YESNOFM. 
    ACCZ_50     YESNOFM. 
    ACCZ_51     YESNOFM. 
    ACCZ_52     YESNO.   
    ACCZ_53A    YESNOFM. 
    ACCZ_53B    YESNOFM. 
    ACCZ_53C    YESNOFM. 
    ACCZ_53D    YESNOFM. 
    ACCZ_53E    YESNOFM. 
    ACCZ_53F    YESNOFM. 
    ACCZ_53G    YESNOFM. 
    ACCZ_53H    YESNOFM. 
    ACCZ_53I    YESNOFM. 
    ACCZ_53J    YESNOFM. 
    ACCZ_53K    YESNOFM. 
    ACCZ_53L    YESNOFM. 
    ACCZ_53M    YESNOFM. 
    ACCZ_54     YESNO.   
    ACCZ_55A    YESNOFM. 
    ACCZ_55B    YESNOFM. 
    ACCZ_55C    YESNOFM. 
    ACCZ_55D    YESNOFM. 
    ACCZ_55E    YESNOFM. 
    ACCZ_55F    YESNOFM. 
    ACCZ_55G    YESNOFM. 
    ACCZ_55H    YESNOFM. 
    ACCZ_55I    YESNOFM. 
    ACCZ_55J    YESNOFM. 
    ACCZ_55K    YESNOFM. 
    ACCZ_55L    YESNOFM. 
    ACCZ_55M    YESNOFM. 
    ACCZ_60     YESNOFM. 
    ACCZ_61     YESNOFM. 
    ACCZ_62     YESNO.   
    ACCZ_63A    YESNOFM. 
    ACCZ_63B    YESNOFM. 
    ACCZ_63C    YESNOFM. 
    ACCZ_63D    YESNOFM. 
    ACCZ_63E    YESNOFM. 
    ACCZ_63F    YESNOFM. 
    ACCZ_63G    YESNOFM. 
    ACCZ_63H    YESNOFM. 
    ACCZ_63I    YESNOFM. 
    ACCZ_63J    YESNOFM. 
    ACCZ_63K    YESNOFM. 
    ACCZ_63L    YESNOFM. 
    ACCZ_63M    YESNOFM. 
    ACCZ_64     YESNO.   
    ACCZ_65A    YESNOFM. 
    ACCZ_65B    YESNOFM. 
    ACCZ_65C    YESNOFM. 
    ACCZ_65D    YESNOFM. 
    ACCZ_65E    YESNOFM. 
    ACCZ_65F    YESNOFM. 
    ACCZ_65G    YESNOFM. 
    ACCZ_65H    YESNOFM. 
    ACCZ_65I    YESNOFM. 
    ACCZ_65J    YESNOFM. 
    ACCZ_65K    YESNOFM. 
    ACCZ_65L    YESNOFM. 
    ACCZ_65M    YESNOFM. 
    ACCZ_66     YESNO.   
    ACCZ_67A    YESNOFM. 
    ACCZ_67B    YESNOFM. 
    ACCZ_67C    YESNOFM. 
    ACCZ_67D    YESNOFM. 
    ACCZ_67E    YESNOFM. 
    ACCZ_67F    YESNOFM. 
    ACCZ_67G    YESNOFM. 
    ACCZ_67H    YESNOFM. 
    ACCZ_67I    YESNOFM. 
    ACCZ_67J    YESNOFM. 
    ACCZ_67K    YESNOFM. 
    ACCZ_67L    YESNOFM. 
    ACCZ_67M    YESNOFM. 
    WTMZ_01     YESNOFM. 
    WTMZ_02     WTMC02FM.
    WTMZ_03     WTMC03FM.
    WTMZ_04     YESNOFM. 
    WTMZ_05     YESNOFM. 
    WTMZ_06A    YESNOFM. 
    WTMZ_06B    YESNOFM. 
    WTMZ_06C    YESNOFM. 
    WTMZ_06D    YESNOFM. 
    WTMZ_06E    YESNOFM. 
    WTMZ_06F    YESNOFM. 
    WTMZ_06G    YESNOFM. 
    WTMZ_06H    YESNOFM. 
    WTMZ_06I    YESNOFM. 
    WTMZ_06J    YESNOFM. 
    WTMZ_06K    YESNOFM. 
    WTMZ_06L    YESNOFM. 
    WTMZ_06M    YESNOFM. 
    WTMZ_07A    WTMC7AFM.
    WTMZ_07B    WTMC7BFM.
    WTMZ_08A    WTMC7AFM.
    WTMZ_08B    WTMC7BFM.
    WTMZ_10     WTMC10FM.
    WTMZ_11A    WTMC7AFM.
    WTMZ_11B    WTMC7BFM.
    WTMZ_12     YESNOFM. 
    WTMZ_13A    YESNOFM. 
    WTMZ_13B    YESNOFM. 
    WTMZ_13C    YESNOFM. 
    WTMZ_14     YESNOFM. 
    WTMZ_15A    YESNOFM. 
    WTMZ_15B    YESNOFM. 
    WTMZ_15C    YESNOFM. 
    WTMZ_15D    YESNOFM. 
    WTMZ_15E    YESNOFM. 
    WTMZ_15F    YESNOFM. 
    WTMZ_15G    YESNOFM. 
    WTMZ_15H    YESNOFM. 
    WTMZ_15I    YESNOFM. 
    WTMZ_15J    YESNOFM. 
    WTMZ_15K    YESNOFM. 
    WTMZ_15L    YESNOFM. 
    WTMZ_16     WTMC16FM.
    WTMZ_17     YESNOFM. 
    WTMZ_18     YESNOFM. 
    WTMZ_19     YESNOFM. 
    WTMZ_20A    YESNOFM. 
    WTMZ_20B    YESNOFM. 
    WTMZ_20C    YESNOFM. 
    WTMZ_20D    YESNOFM. 
    WTMZ_20E    YESNOFM. 
    WTMZ_20F    YESNOFM. 
    WTMZ_20G    YESNOFM. 
    WTMZ_20H    YESNOFM. 
    WTMZ_20I    YESNOFM. 
    WTMZ_20J    YESNOFM. 
    WTMZ_20K    YESNOFM. 
    WTMZ_20L    YESNOFM. 
    WTMZ_20M    YESNOFM. 
    WTMZ_20N    YESNOFM. 
    WTMZ_21A    WTMC7AFM.
    WTMZ_21B    WTMC7BFM.
    WTMZ_22     YESNOFM. 
    WTMZ_23A    WTMC7AFM.
    WTMZ_23B    WTMC7BFM.
    WTMZ_24     WTMC10FM.
    WTMZ_25A    WTMC7AFM.
    WTMZ_25B    WTMC7BFM.
    WTMZ_26     YESNOFM. 
    WTMZ_27A    YESNOFM. 
    WTMZ_27B    YESNOFM. 
    WTMZ_27C    YESNOFM. 
    WTMZ_27D    YESNOFM. 
    WTMZ_28     YESNOFM. 
    WTMZ_29A    YESNOFM. 
    WTMZ_29B    YESNOFM. 
    WTMZ_29C    YESNOFM. 
    WTMZ_29D    YESNOFM. 
    WTMZ_29E    YESNOFM. 
    WTMZ_29F    YESNOFM. 
    WTMZ_29G    YESNOFM. 
    WTMZ_29H    YESNOFM. 
    WTMZ_29I    YESNOFM. 
    WTMZ_29J    YESNOFM. 
    WTMZ_29K    YESNOFM. 
    WTMZ_29L    YESNOFM. 
    WTMZ_30     WTMCFM.  
    WTMZ_31     WTM31FM. 
    WTMZ_32     YESNOFM. 
    WTMZ_33     WTM33FM. 
    WTMZ_34     WTMC34FM.
    WTMZ_35     YESNOFM. 
    WTMZ_36     YESNOFM. 
    WTMZ_37A    YESNOFM. 
    WTMZ_37B    YESNOFM. 
    WTMZ_37C    YESNOFM. 
    WTMZ_37D    YESNOFM. 
    WTMZ_37E    YESNOFM. 
    WTMZ_37F    YESNOFM. 
    WTMZ_37G    YESNOFM. 
    WTMZ_37H    YESNOFM. 
    WTMZ_37I    YESNOFM. 
    WTMZ_37J    YESNOFM. 
    WTMZ_37K    YESNOFM. 
    WTMZ_37L    YESNOFM. 
    WTMZ_37M    YESNOFM. 
    WTMZ_38A    WTMC7AFM.
    WTMZ_38B    WTMC7BFM.
    WTMZ_39A    WTMC7AFM.
    WTMZ_39B    WTMC7BFM.
    WTMZ_40     WTMC10FM.
    WTMZ_41A    WTMC7AFM.
    WTMZ_41B    WTMC7BFM.
    WTMZ_42     YESNOFM. 
    WTMZ_43     WTMC43FM.
    WTMZ_44     YESNOFM. 
    WTMZ_45A    YESNOFM. 
    WTMZ_45B    YESNOFM. 
    WTMZ_45C    YESNOFM. 
    WTMZ_45D    YESNOFM. 
    WTMZ_45E    YESNOFM. 
    WTMZ_45F    YESNOFM. 
    WTMZ_45G    YESNOFM. 
    WTMZ_45H    YESNOFM. 
    WTMZ_45I    YESNOFM. 
    WTMZ_45J    YESNOFM. 
    WTMZ_45K    YESNOFM. 
    WTMZ_45L    YESNOFM. 
    WTMZDSO     DAY4DFM. 
    WTMZDSN     DAY4DFM. 
    WTMZDSA     DAY4DFM. 
    WTMZDCO     DAY4DFM. 
    WTMZDCN     DAY4DFM. 
    WTMZDCA     DAY4DFM. 
    WTMZDTO     DAY4DFM. 
    WTMZDTN     DAY4DFM. 
    WTMZDTA     DAY4DFM. 
                       ;
