INFILE &datafid PAD LRECL = 1496;
INPUT
    @    1   VERDATE                              $     8.      
    @    9   REFPER                               $    13.      
    @   22   SAMPLEID                             $    20.      
    @   42   PERSONID                                   2.      
    @   44   GEO_PRV                                    2.      
    @   46   GEODPC                               $     6.      
    @   52   GEODHR4                                    4.      
    @   56   GEODSHR                                    6.      
    @   62   GEODDHA                                    4.      
    @   66   GEODLHA                                    3.      
    @   69   GEODLHN                                    4.      
    @   73   GEODDA06                                   8.      
    @   81   GEODFED                                    5.      
    @   86   GEODCSD                                    7.      
    @   93   GEODCD                                     4.      
    @   97   GEODSAT                                    1.      
    @   98   GEODCMA6                                   3.      
    @  101   GEODPG09                                   2.      
    @  103   GEODUR                                     1.      
    @  104   GEODUR2                                    1.      
    @  105   GEODPSZ                                    1.      
    @  106   SAM_CP                               $     6.      
    @  112   SAM_TYP                                    1.      
    @  113   SAMDSHR                                    1.      
    @  114   SAMDLNK                                    1.      
    @  115   ADM_STA                                    2.      
    @  117   ADM_PRX                                    1.      
    @  118   ADM_YOI                                    4.      
    @  122   ADM_MOI                                    2.      
    @  124   ADM_DOI                                    2.      
    @  126   ADM_N09                                    1.      
    @  127   ADM_N10                                    1.      
    @  128   ADM_N11                                    1.      
    @  129   ADM_N12                                    2.      
    @  131   ADM_LHH                                    1.      
    @  132   DHH_AGE                                    3.      
    @  135   DHH_YOB                                    4.      
    @  139   DHH_MOB                                    2.      
    @  141   DHH_DOB                                    2.      
    @  143   DHH_SEX                                    1.      
    @  144   DHH_MS                                     2.      
    @  146   DHHDSAGE                                   3.      
    @  149   DHHDYKD                                    2.      
    @  151   DHHDOKD                                    2.      
    @  153   DHHDLE5                                    2.      
    @  155   DHHD611                                    2.      
    @  157   DHHDL12                                    2.      
    @  159   DHHDL18                                    2.      
    @  161   DHHDLVG                                    2.      
    @  163   DHHDECF                                    2.      
    @  165   DHHDHSZ                                    2.      
    @  167   GEN_01                                     1.      
    @  168   GEN_02                                     1.      
    @  169   GEN_02A2                                   2.      
    @  171   GEN_02B                                    1.      
    @  172   GEN_07                                     1.      
    @  173   GEN_08                                     1.      
    @  174   GEN_09                                     1.      
    @  175   GEN_10                                     1.      
    @  176   GENDHDI                                    1.      
    @  177   GENDMHI                                    1.      
    @  178   GENGSWL                                    1.      
    @  179   MAM_037                                    1.      
    @  180   HWT_2                                      2.      
    @  182   HWT_2A                                     2.      
    @  184   HWT_2B                                     2.      
    @  186   HWT_2C                                     2.      
    @  188   HWT_2D                                     2.      
    @  190   HWT_2E                                     2.      
    @  192   HWT_2F                                     2.      
    @  194   HWT_3                                      3.      
    @  197   HWT_N4                                     1.      
    @  198   HWT_4                                      1.      
    @  199   HWTDHTM                                    5.3     
    @  204   HWTDWTK                                    6.2     
    @  210   HWTDBMI                                    6.2     
    @  216   HWTDISW                                    2.      
    @  218   HWTDCOL                                    1.      
    @  219   CCC_031                                    1.      
    @  220   CCC_035                                    1.      
    @  221   CCC_036                                    1.      
    @  222   CCC_051                                    1.      
    @  223   CCC_061                                    1.      
    @  224   CCC_071                                    1.      
    @  225   CCC_072                                    1.      
    @  226   CCC_073                                    1.      
    @  227   CCC_073A                                   1.      
    @  228   CCC_073B                                   1.      
    @  229   CCC_081                                    1.      
    @  230   CCC_091                                    1.      
    @  231   CCC_101                                    1.      
    @  232   CCC_102                                    3.      
    @  235   CCC_10A                                    1.      
    @  236   CCC_10B                                    1.      
    @  237   CCC_10C                                    2.      
    @  239   CCC_105                                    1.      
    @  240   CCC_106                                    1.      
    @  241   CCC_121                                    1.      
    @  242   CCC_131                                    1.      
    @  243   CCC_31A                                    1.      
    @  244   CCC_141                                    1.      
    @  245   CCC_151                                    1.      
    @  246   CCC_161                                    1.      
    @  247   CCC_171                                    1.      
    @  248   CCC_17A                                    1.      
    @  249   CCC_181                                    1.      
    @  250   CCC_280                                    1.      
    @  251   CCC_290                                    1.      
    @  252   CCCDDIA                                    1.      
    @  253   DOHUI                                      1.      
    @  254   HUI_01                                     1.      
    @  255   HUI_02                                     1.      
    @  256   HUI_03                                     1.      
    @  257   HUI_04                                     1.      
    @  258   HUI_05                                     1.      
    @  259   HUI_06                                     1.      
    @  260   HUI_07                                     1.      
    @  261   HUI_07A                                    1.      
    @  262   HUI_08                                     1.      
    @  263   HUI_09                                     1.      
    @  264   HUI_10                                     1.      
    @  265   HUI_11                                     1.      
    @  266   HUI_12                                     1.      
    @  267   HUI_13                                     1.      
    @  268   HUI_14                                     1.      
    @  269   HUI_15                                     1.      
    @  270   HUI_16                                     1.      
    @  271   HUI_17                                     1.      
    @  272   HUI_18                                     1.      
    @  273   HUI_19                                     1.      
    @  274   HUI_20                                     1.      
    @  275   HUI_21                                     1.      
    @  276   HUI_22                                     1.      
    @  277   HUI_23                                     1.      
    @  278   HUI_24                                     1.      
    @  279   HUI_25                                     1.      
    @  280   HUI_26                                     1.      
    @  281   HUI_27                                     1.      
    @  282   HUIDVIS                                    2.      
    @  284   HUIDHER                                    2.      
    @  286   HUIDSPE                                    1.      
    @  287   HUIDMOB                                    2.      
    @  289   HUIDDEX                                    2.      
    @  291   HUIDEMO                                    1.      
    @  292   HUIDCOG                                    2.      
    @  294   HUIDHSI                                    6.3     
    @  300   HUP_01                                     1.      
    @  301   HUP_02                                     1.      
    @  302   HUP_03                                     1.      
    @  303   HUPDPAD                                    1.      
    @  304   HCU_1AA                                    1.      
    @  305   HCU_1BA                                    1.      
    @  306   HCU_1BB                                    1.      
    @  307   HCU_1BC                                    1.      
    @  308   HCU_1BD                                    1.      
    @  309   HCU_1BE                                    1.      
    @  310   HCU_1A1                                    1.      
    @  311   HCU_1A2                                    2.      
    @  313   HCU_1AC                                    2.      
    @  315   CHP_01                                     1.      
    @  316   CHP_02                                     3.      
    @  319   CHP_03                                     1.      
    @  320   CHP_04                                     3.      
    @  323   CHP_05                                     2.      
    @  325   CHP_06                                     1.      
    @  326   CHP_07                                     2.      
    @  328   CHP_08                                     1.      
    @  329   CHP_09                                     3.      
    @  332   CHP_10                                     2.      
    @  334   CHP_11                                     1.      
    @  335   CHP_12                                     3.      
    @  338   CHP_13                                     2.      
    @  340   CHP_14                                     1.      
    @  341   CHP_15                                     3.      
    @  344   CHP_16                                     1.      
    @  345   CHP_17                                     3.      
    @  348   CHP_18                                     1.      
    @  349   CHP_19                                     3.      
    @  352   CHP_20                                     1.      
    @  353   CHP_21                                     3.      
    @  356   CHP_22                                     1.      
    @  357   CHP_23                                     3.      
    @  360   CHP_24                                     1.      
    @  361   CHP_25                                     3.      
    @  364   CHPDMDC                                    3.      
    @  367   CHPFCOP                                    1.      
    @  368   RAC_1                                      1.      
    @  369   RAC_2A                                     1.      
    @  370   RAC_2B1                                    1.      
    @  371   RAC_2B2                                    1.      
    @  372   RAC_2C                                     1.      
    @  373   RAC_5                                      2.      
    @  375   RACDIMP                                    1.      
    @  376   RACDPAL                                    1.      
    @  377   DOADL                                      1.      
    @  378   ADL_01                                     1.      
    @  379   ADL_02                                     1.      
    @  380   ADL_03                                     1.      
    @  381   ADL_04                                     1.      
    @  382   ADL_05                                     1.      
    @  383   ADL_06                                     1.      
    @  384   ADLF6R                                     1.      
    @  385   FLU_160                                    1.      
    @  386   FLU_162                                    1.      
    @  387   FLU_164                                    2.      
    @  389   FLU_165                                    1.      
    @  390   FLU_66A                                    1.      
    @  391   FLU_66B                                    1.      
    @  392   FLU_66C                                    1.      
    @  393   FLU_66D                                    1.      
    @  394   FLU_66E                                    1.      
    @  395   FLU_66F                                    1.      
    @  396   FLU_66G                                    1.      
    @  397   FLU_66H                                    1.      
    @  398   FLU_66I                                    1.      
    @  399   FLU_66J                                    1.      
    @  400   FLU_66K                                    1.      
    @  401   FLU_66L                                    1.      
    @  402   FLU_66M                                    1.      
    @  403   FLU_66O                                    1.      
    @  404   FLU_66N                                    1.      
    @  405   FVC_1A                                     1.      
    @  406   FVC_1B                                     2.      
    @  408   FVC_1C                                     2.      
    @  410   FVC_1D                                     3.      
    @  413   FVC_1E                                     3.      
    @  416   FVC_2A                                     1.      
    @  417   FVC_2B                                     2.      
    @  419   FVC_2C                                     2.      
    @  421   FVC_2D                                     3.      
    @  424   FVC_2E                                     3.      
    @  427   FVC_3A                                     1.      
    @  428   FVC_3B                                     2.      
    @  430   FVC_3C                                     2.      
    @  432   FVC_3D                                     3.      
    @  435   FVC_3E                                     3.      
    @  438   FVC_4A                                     1.      
    @  439   FVC_4B                                     2.      
    @  441   FVC_4C                                     2.      
    @  443   FVC_4D                                     3.      
    @  446   FVC_4E                                     3.      
    @  449   FVC_5A                                     1.      
    @  450   FVC_5B                                     2.      
    @  452   FVC_5C                                     2.      
    @  454   FVC_5D                                     3.      
    @  457   FVC_5E                                     3.      
    @  460   FVC_6A                                     1.      
    @  461   FVC_6B                                     2.      
    @  463   FVC_6C                                     2.      
    @  465   FVC_6D                                     3.      
    @  468   FVC_6E                                     3.      
    @  471   FVCDJUI                                    5.1     
    @  476   FVCDFRU                                    5.1     
    @  481   FVCDSAL                                    5.1     
    @  486   FVCDPOT                                    5.1     
    @  491   FVCDCAR                                    5.1     
    @  496   FVCDVEG                                    5.1     
    @  501   FVCDTOT                                    5.1     
    @  506   FVCGTOT                                    1.      
    @  507   PAC_1A                                     1.      
    @  508   PAC_1B                                     1.      
    @  509   PAC_1C                                     1.      
    @  510   PAC_1D                                     1.      
    @  511   PAC_1E                                     1.      
    @  512   PAC_1F                                     1.      
    @  513   PAC_1G                                     1.      
    @  514   PAC_1H                                     1.      
    @  515   PAC_1I                                     1.      
    @  516   PAC_1J                                     1.      
    @  517   PAC_1K                                     1.      
    @  518   PAC_1L                                     1.      
    @  519   PAC_1M                                     1.      
    @  520   PAC_1N                                     1.      
    @  521   PAC_1O                                     1.      
    @  522   PAC_1P                                     1.      
    @  523   PAC_1Q                                     1.      
    @  524   PAC_1R                                     1.      
    @  525   PAC_1S                                     1.      
    @  526   PAC_1T                                     1.      
    @  527   PAC_1Z                                     1.      
    @  528   PAC_1U                                     1.      
    @  529   PAC_1V                                     1.      
    @  530   PAC_1W                                     1.      
    @  531   PAC_1X                                     1.      
    @  532   PAC_2A                                     3.      
    @  535   PAC_3A                                     1.      
    @  536   PAC_2B                                     3.      
    @  539   PAC_3B                                     1.      
    @  540   PAC_2C                                     3.      
    @  543   PAC_3C                                     1.      
    @  544   PAC_2D                                     3.      
    @  547   PAC_3D                                     1.      
    @  548   PAC_2E                                     3.      
    @  551   PAC_3E                                     1.      
    @  552   PAC_2F                                     3.      
    @  555   PAC_3F                                     1.      
    @  556   PAC_2G                                     3.      
    @  559   PAC_3G                                     1.      
    @  560   PAC_2H                                     3.      
    @  563   PAC_3H                                     1.      
    @  564   PAC_2I                                     3.      
    @  567   PAC_3I                                     1.      
    @  568   PAC_2J                                     3.      
    @  571   PAC_3J                                     1.      
    @  572   PAC_2K                                     3.      
    @  575   PAC_3K                                     1.      
    @  576   PAC_2L                                     3.      
    @  579   PAC_3L                                     1.      
    @  580   PAC_2M                                     3.      
    @  583   PAC_3M                                     1.      
    @  584   PAC_2N                                     3.      
    @  587   PAC_3N                                     1.      
    @  588   PAC_2O                                     3.      
    @  591   PAC_3O                                     1.      
    @  592   PAC_2P                                     3.      
    @  595   PAC_3P                                     1.      
    @  596   PAC_2Q                                     3.      
    @  599   PAC_3Q                                     1.      
    @  600   PAC_2R                                     3.      
    @  603   PAC_3R                                     1.      
    @  604   PAC_2S                                     3.      
    @  607   PAC_3S                                     1.      
    @  608   PAC_2T                                     3.      
    @  611   PAC_3T                                     1.      
    @  612   PAC_2Z                                     3.      
    @  615   PAC_3Z                                     1.      
    @  616   PAC_2U                                     3.      
    @  619   PAC_3U                                     1.      
    @  620   PAC_2W                                     3.      
    @  623   PAC_3W                                     1.      
    @  624   PAC_2X                                     3.      
    @  627   PAC_3X                                     1.      
    @  628   PAC_7                                      1.      
    @  629   PAC_7A                                     3.      
    @  632   PAC_7B                                     1.      
    @  633   PAC_8                                      1.      
    @  634   PAC_8A                                     3.      
    @  637   PAC_8B                                     1.      
    @  638   PACDEE                                     4.1     
    @  642   PACFLEI                                    1.      
    @  643   PACDFM                                     3.      
    @  646   PACDFR                                     1.      
    @  647   PACFD                                      1.      
    @  648   PACDPAI                                    1.      
    @  649   PACDLTI                                    1.      
    @  650   PACDTLE                                    4.1     
    @  654   PACFLTI                                    1.      
    @  655   DOUPE                                      1.      
    @  656   UPE_01A                                    1.      
    @  657   UPE_01                                     1.      
    @  658   UPE_02                                     1.      
    @  659   UPE_02A                                    1.      
    @  660   UPE_02B                                    1.      
    @  661   UPE_02C                                    1.      
    @  662   UPE_02D                                    1.      
    @  663   UPE_03A                                    1.      
    @  664   UPE_03B                                    1.      
    @  665   UPE_04A                                    1.      
    @  666   UPE_05A                                    1.      
    @  667   UPE_05B                                    1.      
    @  668   UPE_06                                     1.      
    @  669   UPE_06A                                    1.      
    @  670   UPE_06B                                    1.      
    @  671   UPE_06C                                    1.      
    @  672   UPE_07                                     1.      
    @  673   UPE_07A                                    1.      
    @  674   UPEFILS                                    1.      
    @  675   UPEFSKB                                    1.      
    @  676   UPEFSNB                                    1.      
    @  677   DOINJ                                      1.      
    @  678   REP_1A                                     1.      
    @  679   REP_2                                      1.      
    @  680   REP_3                                      2.      
    @  682   REP_3A                                     1.      
    @  683   REP_4                                      1.      
    @  684   REP_5A                                     1.      
    @  685   REP_5B                                     1.      
    @  686   REP_5C                                     1.      
    @  687   REP_5D                                     1.      
    @  688   REP_5F                                     1.      
    @  689   REP_5G                                     1.      
    @  690   REP_5H                                     1.      
    @  691   REP_5I                                     1.      
    @  692   INJ_01                                     1.      
    @  693   INJ_02                                     2.      
    @  695   INJ_03                                     2.      
    @  697   INJ_04                                     1.      
    @  698   INJ_05                                     2.      
    @  700   INJ_06                                     2.      
    @  702   INJ_07                                     1.      
    @  703   INJ_08                                     2.      
    @  705   INJ_09                                     2.      
    @  707   INW_01                                     1.      
    @  708   INWF02                                     1.      
    @  709   INWF03                                     1.      
    @  710   INWCSIC                              $     5.      
    @  715   INWCSOC                              $     4.      
    @  719   INWF03S                                    1.      
    @  720   INWF04                                     1.      
    @  721   INWDOCG                              $     2.      
    @  723   INWDING                              $     2.      
    @  725   INJ_10                                     1.      
    @  726   INJ_11A                                    2.      
    @  728   INJ_12                                     2.      
    @  730   INJ_12A                                    1.      
    @  731   INJ_13                                     1.      
    @  732   INJ_14A                                    1.      
    @  733   INJ_14B                                    1.      
    @  734   INJ_14C                                    1.      
    @  735   INJ_14L                                    1.      
    @  736   INJ_14M                                    1.      
    @  737   INJ_14F                                    1.      
    @  738   INJ_14N                                    1.      
    @  739   INJ_14O                                    1.      
    @  740   INJ_14K                                    1.      
    @  741   INJ_15                                     1.      
    @  742   INJ_15A                                    1.      
    @  743   INJ_16                                     1.      
    @  744   INJ_17                                     2.      
    @  746   INJDTBS                                    4.      
    @  750   INJDCAU                                    2.      
    @  752   INJDCBP                                    4.      
    @  756   INJDSTT                                    1.      
    @  757   SMK_01A                                    1.      
    @  758   SMK_01B                                    1.      
    @  759   SMK_01C                                    3.      
    @  762   SMK_202                                    1.      
    @  763   SMK_203                                    3.      
    @  766   SMK_204                                    3.      
    @  769   SMK_05B                                    3.      
    @  772   SMK_05C                                    2.      
    @  774   SMK_05D                                    1.      
    @  775   SMK_06A                                    1.      
    @  776   SMK_06B                                    2.      
    @  778   SMK_06C                                    3.      
    @  781   SMK_207                                    3.      
    @  784   SMK_208                                    3.      
    @  787   SMK_09A                                    1.      
    @  788   SMK_09B                                    2.      
    @  790   SMK_09C                                    3.      
    @  793   SMK_10                                     1.      
    @  794   SMK_10A                                    1.      
    @  795   SMK_10B                                    2.      
    @  797   SMK_10C                                    3.      
    @  800   SMKDSTY                                    2.      
    @  802   SMKDSTP                                    3.      
    @  805   SMKDYCS                                    3.      
    @  808   ETS_10                                     1.      
    @  809   ETS_11                                     2.      
    @  811   ETS_20                                     1.      
    @  812   ETS_20B                                    1.      
    @  813   ETS_35                                     1.      
    @  814   ETS_36                                     1.      
    @  815   ETS_37A                                    1.      
    @  816   ETS_37B                                    1.      
    @  817   ETS_37C                                    1.      
    @  818   ETS_37D                                    1.      
    @  819   ALC_1                                      1.      
    @  820   ALC_2                                      2.      
    @  822   ALC_3                                      2.      
    @  824   ALCDTTM                                    1.      
    @  825   MEX_01                                     1.      
    @  826   MEX_01A                                    4.      
    @  830   MEX_02                                     1.      
    @  831   MEX_03                                     1.      
    @  832   MEX_04                                     2.      
    @  834   MEX_05                                     1.      
    @  835   MEX_06                                     2.      
    @  837   MEX_07                                     2.      
    @  839   MEX_08                                     2.      
    @  841   MEX_09                                     1.      
    @  842   MEX_10                                     2.      
    @  844   MEXDEBF                                    2.      
    @  846   MEXFEB6                                    1.      
    @  847   DOSXB                                      1.      
    @  848   SXB_1                                      1.      
    @  849   SXB_2                                      3.      
    @  852   SXB_3                                      1.      
    @  853   SXB_4                                      1.      
    @  854   SXB_07                                     1.      
    @  855   SXB_7A                                     1.      
    @  856   SXB_09                                     1.      
    @  857   SXB_10                                     2.      
    @  859   SXB_11                                     1.      
    @  860   SXB_12A                                    1.      
    @  861   SXB_12B                                    1.      
    @  862   SXB_12C                                    1.      
    @  863   SXB_12D                                    1.      
    @  864   SXB_12F                                    1.      
    @  865   SXB_12E                                    1.      
    @  866   SXB_13A                                    1.      
    @  867   SXB_13B                                    1.      
    @  868   SXB_13C                                    1.      
    @  869   SXB_13D                                    1.      
    @  870   SXB_13F                                    1.      
    @  871   SXB_13G                                    1.      
    @  872   SXB_13E                                    1.      
    @  873   SDC_1                                      2.      
    @  875   SDC_2                                      1.      
    @  876   SDC_3                                      4.      
    @  880   SDC_4A                                     1.      
    @  881   SDC_4B                                     1.      
    @  882   SDC_4C                                     1.      
    @  883   SDC_4D                                     1.      
    @  884   SDC_4E                                     1.      
    @  885   SDC_4F                                     1.      
    @  886   SDC_4G                                     1.      
    @  887   SDC_4H                                     1.      
    @  888   SDC_4I                                     1.      
    @  889   SDC_4J                                     1.      
    @  890   SDC_4K                                     1.      
    @  891   SDC_4L                                     1.      
    @  892   SDC_4M                                     1.      
    @  893   SDC_4N                                     1.      
    @  894   SDC_4T                                     1.      
    @  895   SDC_4U                                     1.      
    @  896   SDC_4V                                     1.      
    @  897   SDC_4P                                     1.      
    @  898   SDC_4Q                                     1.      
    @  899   SDC_4R                                     1.      
    @  900   SDC_4S                                     1.      
    @  901   SDC_41                                     1.      
    @  902   SDC_42A                                    1.      
    @  903   SDC_42B                                    1.      
    @  904   SDC_42C                                    1.      
    @  905   SDC_43A                                    1.      
    @  906   SDC_43B                                    1.      
    @  907   SDC_43C                                    1.      
    @  908   SDC_43D                                    1.      
    @  909   SDC_43E                                    1.      
    @  910   SDC_43F                                    1.      
    @  911   SDC_43G                                    1.      
    @  912   SDC_43H                                    1.      
    @  913   SDC_43I                                    1.      
    @  914   SDC_43J                                    1.      
    @  915   SDC_43K                                    1.      
    @  916   SDC_43M                                    1.      
    @  917   SDC_5A                                     1.      
    @  918   SDC_5B                                     1.      
    @  919   SDC_5C                                     1.      
    @  920   SDC_5D                                     1.      
    @  921   SDC_5E                                     1.      
    @  922   SDC_5F                                     1.      
    @  923   SDC_5G                                     1.      
    @  924   SDC_5H                                     1.      
    @  925   SDC_5I                                     1.      
    @  926   SDC_5J                                     1.      
    @  927   SDC_5K                                     1.      
    @  928   SDC_5L                                     1.      
    @  929   SDC_5M                                     1.      
    @  930   SDC_5N                                     1.      
    @  931   SDC_5O                                     1.      
    @  932   SDC_5P                                     1.      
    @  933   SDC_5Q                                     1.      
    @  934   SDC_5R                                     1.      
    @  935   SDC_5T                                     1.      
    @  936   SDC_5U                                     1.      
    @  937   SDC_5V                                     1.      
    @  938   SDC_5W                                     1.      
    @  939   SDC_5S                                     1.      
    @  940   SDC_5AA                                    1.      
    @  941   SDC_5AB                                    1.      
    @  942   SDC_5AC                                    1.      
    @  943   SDC_5AD                                    1.      
    @  944   SDC_5AE                                    1.      
    @  945   SDC_5AF                                    1.      
    @  946   SDC_5AG                                    1.      
    @  947   SDC_5AH                                    1.      
    @  948   SDC_5AI                                    1.      
    @  949   SDC_5AJ                                    1.      
    @  950   SDC_5AK                                    1.      
    @  951   SDC_5AL                                    1.      
    @  952   SDC_5AM                                    1.      
    @  953   SDC_5AN                                    1.      
    @  954   SDC_5AO                                    1.      
    @  955   SDC_5AP                                    1.      
    @  956   SDC_5AQ                                    1.      
    @  957   SDC_5AR                                    1.      
    @  958   SDC_5AT                                    1.      
    @  959   SDC_5AU                                    1.      
    @  960   SDC_5AV                                    1.      
    @  961   SDC_5AW                                    1.      
    @  962   SDC_5AS                                    1.      
    @  963   SDC_6A                                     1.      
    @  964   SDC_6B                                     1.      
    @  965   SDC_6C                                     1.      
    @  966   SDC_6D                                     1.      
    @  967   SDC_6E                                     1.      
    @  968   SDC_6F                                     1.      
    @  969   SDC_6G                                     1.      
    @  970   SDC_6H                                     1.      
    @  971   SDC_6I                                     1.      
    @  972   SDC_6J                                     1.      
    @  973   SDC_6K                                     1.      
    @  974   SDC_6L                                     1.      
    @  975   SDC_6M                                     1.      
    @  976   SDC_6N                                     1.      
    @  977   SDC_6O                                     1.      
    @  978   SDC_6P                                     1.      
    @  979   SDC_6Q                                     1.      
    @  980   SDC_6R                                     1.      
    @  981   SDC_6T                                     1.      
    @  982   SDC_6U                                     1.      
    @  983   SDC_6V                                     1.      
    @  984   SDC_6W                                     1.      
    @  985   SDC_6S                                     1.      
    @  986   DHH_OWN                                    1.      
    @  987   SDC_7AA                                    1.      
    @  988   SDCCCB                                     3.      
    @  991   SDCGCB                                     2.      
    @  993   SDCDLHM                                    2.      
    @  995   SDCDAIM                                    3.      
    @  998   SDCFIMM                                    1.      
    @  999   SDCDRES                                    3.      
    @ 1002   SDCDLNG                                    2.      
    @ 1004   SDCDFL1                                    2.      
    @ 1006   SDCDABT                                    1.      
    @ 1007   SDCDCGT                                    2.      
    @ 1009   EDU_1                                      1.      
    @ 1010   EDU_2                                      1.      
    @ 1011   EDU_3                                      1.      
    @ 1012   EDU_4                                      2.      
    @ 1014   SDC_8                                      1.      
    @ 1015   SDC_9                                      1.      
    @ 1016   EDUDH04                                    1.      
    @ 1017   EDUDH10                                    2.      
    @ 1019   EDUDR04                                    1.      
    @ 1020   EDUDR10                                    2.      
    @ 1022   LBS_01                                     1.      
    @ 1023   LBS_02                                     1.      
    @ 1024   LBS_03                                     1.      
    @ 1025   LBS_11                                     1.      
    @ 1026   LBS_31                                     1.      
    @ 1027   LBSF32                                     1.      
    @ 1028   LBSF33                                     1.      
    @ 1029   LBSF34                                     1.      
    @ 1030   LBSF35                                     1.      
    @ 1031   LBSCSIC                              $     5.      
    @ 1036   LBSCSOC                              $     4.      
    @ 1040   LBSF35S                                    1.      
    @ 1041   LBSF36                                     1.      
    @ 1042   LBS_42                                     3.      
    @ 1045   LBS_53                                     3.      
    @ 1048   LBSDHPW                                    3.      
    @ 1051   LBSDPFT                                    1.      
    @ 1052   LBSDWSS                                    1.      
    @ 1053   LBSDING                              $     2.      
    @ 1055   LBSDOCG                              $     2.      
    @ 1057   INC_1A                                     1.      
    @ 1058   INC_1B                                     1.      
    @ 1059   INC_1C                                     1.      
    @ 1060   INC_1D                                     1.      
    @ 1061   INC_1E                                     1.      
    @ 1062   INC_1F                                     1.      
    @ 1063   INC_1G                                     1.      
    @ 1064   INC_1O                                     1.      
    @ 1065   INC_1H                                     1.      
    @ 1066   INC_1J                                     1.      
    @ 1067   INC_1I                                     1.      
    @ 1068   INC_1K                                     1.      
    @ 1069   INC_1L                                     1.      
    @ 1070   INC_1M                                     1.      
    @ 1071   INC_1N                                     1.      
    @ 1072   INC_2                                      2.      
    @ 1074   INC_3                                      6.      
    @ 1080   INC_5A                                     1.      
    @ 1081   INC_5B                                     2.      
    @ 1083   INC_5C                                     2.      
    @ 1085   INC_6A                                     1.      
    @ 1086   INC_6B                                     1.      
    @ 1087   INC_6C                                     1.      
    @ 1088   INC_6D                                     1.      
    @ 1089   INC_6E                                     1.      
    @ 1090   INC_6F                                     1.      
    @ 1091   INC_6G                                     1.      
    @ 1092   INC_6H                                     1.      
    @ 1093   INC_6I                                     1.      
    @ 1094   INC_6K                                     1.      
    @ 1095   INC_6J                                     1.      
    @ 1096   INC_6L                                     1.      
    @ 1097   INC_6M                                     1.      
    @ 1098   INC_6N                                     1.      
    @ 1099   INC_6O                                     1.      
    @ 1100   INC_7                                      2.      
    @ 1102   INC_8A                                     6.      
    @ 1108   INC_8B                                     1.      
    @ 1109   INC_8C                                     2.      
    @ 1111   INC_8D                                     2.      
    @ 1113   INCDHH                                     2.      
    @ 1115   INCDPER                                    2.      
    @ 1117   INCDADR                                   11.9     
    @ 1128   INCDRCA                                    2.      
    @ 1130   INCDRPR                                    2.      
    @ 1132   INCDRRS                                    2.      
    @ 1134   ACCZ_10                                    1.      
    @ 1135   ACCZ_11                                    1.      
    @ 1136   ACCZ_12A                                   1.      
    @ 1137   ACCZ_12B                                   1.      
    @ 1138   ACCZ_12C                                   1.      
    @ 1139   ACCZ_12D                                   1.      
    @ 1140   ACCZ_12E                                   1.      
    @ 1141   ACCZ_12F                                   1.      
    @ 1142   ACCZ_12G                                   1.      
    @ 1143   ACCZ_12H                                   1.      
    @ 1144   ACCZ_12I                                   1.      
    @ 1145   ACCZ_12J                                   1.      
    @ 1146   ACCZ_12K                                   1.      
    @ 1147   ACCZ_12L                                   1.      
    @ 1148   ACCZ_12M                                   1.      
    @ 1149   ACCZ_12N                                   1.      
    @ 1150   ACCZ_20                                    1.      
    @ 1151   ACCZ_21                                    1.      
    @ 1152   ACCZ_22A                                   1.      
    @ 1153   ACCZ_22B                                   1.      
    @ 1154   ACCZ_22C                                   1.      
    @ 1155   ACCZ_22D                                   1.      
    @ 1156   ACCZ_22E                                   1.      
    @ 1157   ACCZ_22F                                   1.      
    @ 1158   ACCZ_22G                                   1.      
    @ 1159   ACCZ_22H                                   1.      
    @ 1160   ACCZ_22I                                   1.      
    @ 1161   ACCZ_22J                                   1.      
    @ 1162   ACCZ_22K                                   1.      
    @ 1163   ACCZ_22L                                   1.      
    @ 1164   ACCZ_22M                                   1.      
    @ 1165   ACCZ_22N                                   1.      
    @ 1166   ACCZ_22O                                   1.      
    @ 1167   ACCZ_30                                    1.      
    @ 1168   ACCZ_31                                    1.      
    @ 1169   ACCZ_32A                                   1.      
    @ 1170   ACCZ_32B                                   1.      
    @ 1171   ACCZ_32C                                   1.      
    @ 1172   ACCZ_32D                                   1.      
    @ 1173   ACCZ_32E                                   1.      
    @ 1174   ACCZ_32F                                   1.      
    @ 1175   ACCZ_32G                                   1.      
    @ 1176   ACCZ_32H                                   1.      
    @ 1177   ACCZ_32I                                   1.      
    @ 1178   ACCZ_32J                                   1.      
    @ 1179   ACCZ_32K                                   1.      
    @ 1180   ACCZ_32L                                   1.      
    @ 1181   ACCZ_32M                                   1.      
    @ 1182   ACCZ_32N                                   1.      
    @ 1183   ACCZ_40                                    1.      
    @ 1184   ACCZ_40A                                   1.      
    @ 1185   ACCZ_40B                                   1.      
    @ 1186   ACCZ_40C                                   1.      
    @ 1187   ACCZ_40D                                   1.      
    @ 1188   ACCZ_40E                                   1.      
    @ 1189   ACCZ_40F                                   1.      
    @ 1190   ACCZ_40G                                   1.      
    @ 1191   ACCZ_41                                    1.      
    @ 1192   ACCZ_42                                    1.      
    @ 1193   ACCZ_43A                                   1.      
    @ 1194   ACCZ_43B                                   1.      
    @ 1195   ACCZ_43C                                   1.      
    @ 1196   ACCZ_43D                                   1.      
    @ 1197   ACCZ_43E                                   1.      
    @ 1198   ACCZ_43F                                   1.      
    @ 1199   ACCZ_43G                                   1.      
    @ 1200   ACCZ_43H                                   1.      
    @ 1201   ACCZ_43I                                   1.      
    @ 1202   ACCZ_44                                    1.      
    @ 1203   ACCZ_45A                                   1.      
    @ 1204   ACCZ_45B                                   1.      
    @ 1205   ACCZ_45C                                   1.      
    @ 1206   ACCZ_45D                                   1.      
    @ 1207   ACCZ_45E                                   1.      
    @ 1208   ACCZ_45F                                   1.      
    @ 1209   ACCZ_45G                                   1.      
    @ 1210   ACCZ_45H                                   1.      
    @ 1211   ACCZ_45I                                   1.      
    @ 1212   ACCZ_46                                    1.      
    @ 1213   ACCZ_47A                                   1.      
    @ 1214   ACCZ_47B                                   1.      
    @ 1215   ACCZ_47C                                   1.      
    @ 1216   ACCZ_47D                                   1.      
    @ 1217   ACCZ_47E                                   1.      
    @ 1218   ACCZ_47F                                   1.      
    @ 1219   ACCZ_47G                                   1.      
    @ 1220   ACCZ_47H                                   1.      
    @ 1221   ACCZ_47I                                   1.      
    @ 1222   ACCZ_50A                                   1.      
    @ 1223   ACCZ_50                                    1.      
    @ 1224   ACCZ_51                                    1.      
    @ 1225   ACCZ_52                                    1.      
    @ 1226   ACCZ_53A                                   1.      
    @ 1227   ACCZ_53B                                   1.      
    @ 1228   ACCZ_53C                                   1.      
    @ 1229   ACCZ_53D                                   1.      
    @ 1230   ACCZ_53E                                   1.      
    @ 1231   ACCZ_53F                                   1.      
    @ 1232   ACCZ_53G                                   1.      
    @ 1233   ACCZ_53H                                   1.      
    @ 1234   ACCZ_53I                                   1.      
    @ 1235   ACCZ_53J                                   1.      
    @ 1236   ACCZ_53K                                   1.      
    @ 1237   ACCZ_53L                                   1.      
    @ 1238   ACCZ_53M                                   1.      
    @ 1239   ACCZ_54                                    1.      
    @ 1240   ACCZ_55A                                   1.      
    @ 1241   ACCZ_55B                                   1.      
    @ 1242   ACCZ_55C                                   1.      
    @ 1243   ACCZ_55D                                   1.      
    @ 1244   ACCZ_55E                                   1.      
    @ 1245   ACCZ_55F                                   1.      
    @ 1246   ACCZ_55G                                   1.      
    @ 1247   ACCZ_55H                                   1.      
    @ 1248   ACCZ_55I                                   1.      
    @ 1249   ACCZ_55J                                   1.      
    @ 1250   ACCZ_55K                                   1.      
    @ 1251   ACCZ_55L                                   1.      
    @ 1252   ACCZ_55M                                   1.      
    @ 1253   ACCZ_60                                    1.      
    @ 1254   ACCZ_61                                    1.      
    @ 1255   ACCZ_62                                    1.      
    @ 1256   ACCZ_63A                                   1.      
    @ 1257   ACCZ_63B                                   1.      
    @ 1258   ACCZ_63C                                   1.      
    @ 1259   ACCZ_63D                                   1.      
    @ 1260   ACCZ_63E                                   1.      
    @ 1261   ACCZ_63F                                   1.      
    @ 1262   ACCZ_63G                                   1.      
    @ 1263   ACCZ_63H                                   1.      
    @ 1264   ACCZ_63I                                   1.      
    @ 1265   ACCZ_63J                                   1.      
    @ 1266   ACCZ_63K                                   1.      
    @ 1267   ACCZ_63L                                   1.      
    @ 1268   ACCZ_63M                                   1.      
    @ 1269   ACCZ_64                                    1.      
    @ 1270   ACCZ_65A                                   1.      
    @ 1271   ACCZ_65B                                   1.      
    @ 1272   ACCZ_65C                                   1.      
    @ 1273   ACCZ_65D                                   1.      
    @ 1274   ACCZ_65E                                   1.      
    @ 1275   ACCZ_65F                                   1.      
    @ 1276   ACCZ_65G                                   1.      
    @ 1277   ACCZ_65H                                   1.      
    @ 1278   ACCZ_65I                                   1.      
    @ 1279   ACCZ_65J                                   1.      
    @ 1280   ACCZ_65K                                   1.      
    @ 1281   ACCZ_65L                                   1.      
    @ 1282   ACCZ_65M                                   1.      
    @ 1283   ACCZ_66                                    1.      
    @ 1284   ACCZ_67A                                   1.      
    @ 1285   ACCZ_67B                                   1.      
    @ 1286   ACCZ_67C                                   1.      
    @ 1287   ACCZ_67D                                   1.      
    @ 1288   ACCZ_67E                                   1.      
    @ 1289   ACCZ_67F                                   1.      
    @ 1290   ACCZ_67G                                   1.      
    @ 1291   ACCZ_67H                                   1.      
    @ 1292   ACCZ_67I                                   1.      
    @ 1293   ACCZ_67J                                   1.      
    @ 1294   ACCZ_67K                                   1.      
    @ 1295   ACCZ_67L                                   1.      
    @ 1296   ACCZ_67M                                   1.      
    @ 1297   WTMZ_01                                    1.      
    @ 1298   WTMZ_02                                    2.      
    @ 1300   WTMZ_03                                    1.      
    @ 1301   WTMZ_04                                    1.      
    @ 1302   WTMZ_05                                    1.      
    @ 1303   WTMZ_06A                                   1.      
    @ 1304   WTMZ_06B                                   1.      
    @ 1305   WTMZ_06C                                   1.      
    @ 1306   WTMZ_06D                                   1.      
    @ 1307   WTMZ_06E                                   1.      
    @ 1308   WTMZ_06F                                   1.      
    @ 1309   WTMZ_06G                                   1.      
    @ 1310   WTMZ_06H                                   1.      
    @ 1311   WTMZ_06I                                   1.      
    @ 1312   WTMZ_06J                                   1.      
    @ 1313   WTMZ_06K                                   1.      
    @ 1314   WTMZ_06L                                   1.      
    @ 1315   WTMZ_06M                                   1.      
    @ 1316   WTMZ_07A                                   3.      
    @ 1319   WTMZ_07B                                   1.      
    @ 1320   WTMZ_08A                                   3.      
    @ 1323   WTMZ_08B                                   1.      
    @ 1324   WTMZ_10                                    1.      
    @ 1325   WTMZ_11A                                   3.      
    @ 1328   WTMZ_11B                                   1.      
    @ 1329   WTMZ_12                                    1.      
    @ 1330   WTMZ_13A                                   1.      
    @ 1331   WTMZ_13B                                   1.      
    @ 1332   WTMZ_13C                                   1.      
    @ 1333   WTMZ_14                                    1.      
    @ 1334   WTMZ_15A                                   1.      
    @ 1335   WTMZ_15B                                   1.      
    @ 1336   WTMZ_15C                                   1.      
    @ 1337   WTMZ_15D                                   1.      
    @ 1338   WTMZ_15E                                   1.      
    @ 1339   WTMZ_15F                                   1.      
    @ 1340   WTMZ_15G                                   1.      
    @ 1341   WTMZ_15H                                   1.      
    @ 1342   WTMZ_15I                                   1.      
    @ 1343   WTMZ_15J                                   1.      
    @ 1344   WTMZ_15K                                   1.      
    @ 1345   WTMZ_15L                                   1.      
    @ 1346   WTMZ_16                                    2.      
    @ 1348   WTMZ_17                                    1.      
    @ 1349   WTMZ_18                                    1.      
    @ 1350   WTMZ_19                                    1.      
    @ 1351   WTMZ_20A                                   1.      
    @ 1352   WTMZ_20B                                   1.      
    @ 1353   WTMZ_20C                                   1.      
    @ 1354   WTMZ_20D                                   1.      
    @ 1355   WTMZ_20E                                   1.      
    @ 1356   WTMZ_20F                                   1.      
    @ 1357   WTMZ_20G                                   1.      
    @ 1358   WTMZ_20H                                   1.      
    @ 1359   WTMZ_20I                                   1.      
    @ 1360   WTMZ_20J                                   1.      
    @ 1361   WTMZ_20K                                   1.      
    @ 1362   WTMZ_20L                                   1.      
    @ 1363   WTMZ_20M                                   1.      
    @ 1364   WTMZ_20N                                   1.      
    @ 1365   WTMZ_21A                                   3.      
    @ 1368   WTMZ_21B                                   1.      
    @ 1369   WTMZ_22                                    1.      
    @ 1370   WTMZ_23A                                   3.      
    @ 1373   WTMZ_23B                                   1.      
    @ 1374   WTMZ_24                                    1.      
    @ 1375   WTMZ_25A                                   3.      
    @ 1378   WTMZ_25B                                   1.      
    @ 1379   WTMZ_26                                    1.      
    @ 1380   WTMZ_27A                                   1.      
    @ 1381   WTMZ_27B                                   1.      
    @ 1382   WTMZ_27C                                   1.      
    @ 1383   WTMZ_27D                                   1.      
    @ 1384   WTMZ_28                                    1.      
    @ 1385   WTMZ_29A                                   1.      
    @ 1386   WTMZ_29B                                   1.      
    @ 1387   WTMZ_29C                                   1.      
    @ 1388   WTMZ_29D                                   1.      
    @ 1389   WTMZ_29E                                   1.      
    @ 1390   WTMZ_29F                                   1.      
    @ 1391   WTMZ_29G                                   1.      
    @ 1392   WTMZ_29H                                   1.      
    @ 1393   WTMZ_29I                                   1.      
    @ 1394   WTMZ_29J                                   1.      
    @ 1395   WTMZ_29K                                   1.      
    @ 1396   WTMZ_29L                                   1.      
    @ 1397   WTMZ_30                                    1.      
    @ 1398   WTMZ_31                                    1.      
    @ 1399   WTMZ_32                                    1.      
    @ 1400   WTMZ_33                                    1.      
    @ 1401   WTMZ_34                                    1.      
    @ 1402   WTMZ_35                                    1.      
    @ 1403   WTMZ_36                                    1.      
    @ 1404   WTMZ_37A                                   1.      
    @ 1405   WTMZ_37B                                   1.      
    @ 1406   WTMZ_37C                                   1.      
    @ 1407   WTMZ_37D                                   1.      
    @ 1408   WTMZ_37E                                   1.      
    @ 1409   WTMZ_37F                                   1.      
    @ 1410   WTMZ_37G                                   1.      
    @ 1411   WTMZ_37H                                   1.      
    @ 1412   WTMZ_37I                                   1.      
    @ 1413   WTMZ_37J                                   1.      
    @ 1414   WTMZ_37K                                   1.      
    @ 1415   WTMZ_37L                                   1.      
    @ 1416   WTMZ_37M                                   1.      
    @ 1417   WTMZ_38A                                   3.      
    @ 1420   WTMZ_38B                                   1.      
    @ 1421   WTMZ_39A                                   3.      
    @ 1424   WTMZ_39B                                   1.      
    @ 1425   WTMZ_40                                    1.      
    @ 1426   WTMZ_41A                                   3.      
    @ 1429   WTMZ_41B                                   1.      
    @ 1430   WTMZ_42                                    1.      
    @ 1431   WTMZ_43                                    1.      
    @ 1432   WTMZ_44                                    1.      
    @ 1433   WTMZ_45A                                   1.      
    @ 1434   WTMZ_45B                                   1.      
    @ 1435   WTMZ_45C                                   1.      
    @ 1436   WTMZ_45D                                   1.      
    @ 1437   WTMZ_45E                                   1.      
    @ 1438   WTMZ_45F                                   1.      
    @ 1439   WTMZ_45G                                   1.      
    @ 1440   WTMZ_45H                                   1.      
    @ 1441   WTMZ_45I                                   1.      
    @ 1442   WTMZ_45J                                   1.      
    @ 1443   WTMZ_45K                                   1.      
    @ 1444   WTMZ_45L                                   1.      
    @ 1445   WTMZDSO                                    4.      
    @ 1449   WTMZDSN                                    4.      
    @ 1453   WTMZDSA                                    4.      
    @ 1457   WTMZDCO                                    4.      
    @ 1461   WTMZDCN                                    4.      
    @ 1465   WTMZDCA                                    4.      
    @ 1469   WTMZDTO                                    4.      
    @ 1473   WTMZDTN                                    4.      
    @ 1477   WTMZDTA                                    4.      
    @ 1481   WTS_S1M                                    8.2     
    @ 1489   WTS_S1S                                    8.2     
         ;
