 format
    GEO_PRV     PROVFM.  
    GEODHR4     HR2007FM.
    GEODLHN     GEOLHIN. 
    GEODSAT     GEOSATFM.
    GEODCMA6    DVCMA6FM.
    GEODCMA1    GEOCMAFM.
    GEODPRG     GEOPRGFM.
    GEODUR      GEODURFM.
    GEODUR2     GEO_2UR. 
    GEODPSZ     GEODPSFM.
    SAM_CP     $YR0708FM.
    SAM_TYP     SAME_TYP.
    ADM_STA     ADM_STA. 
    ADM_PRX     YESNOFM. 
    ADM_YOI     YEARXFM. 
    ADM_MOI     MONTHFM. 
    ADM_DOI     DAYFM.   
    ADM_N09     TELFM.   
    ADM_N10     YESNOFM. 
    ADM_N11     YESNOFM. 
    ADM_N12     ADM_LNG. 
    SAMDSHR     YESNOFM. 
    SAMDLNK     YESNOFM. 
    ADM_LHH     AM3_LP.  
    DHH_AGE     AGE3DFM. 
    DHH_YOB     YEARFM.  
    DHH_MOB     MONTHFM. 
    DHH_DOB     DAYFM.   
    DHHDYKD     PERS2D.  
    DHHDOKD     PERS2D.  
    DHH_SEX     DHC_SEX. 
    DHH_MS      DHC_MAR. 
    GEN_01      GOOD5FM. 
    GEN_02      GEN_2F.  
    GEN_02A     SCR_01FM.
    GEN_02B     GOOD5FM. 
    GEN_07      STC_1F.  
    GEN_08      YESNOFM. 
    GEN_09      STC_1F.  
    GEN_10      GEN_10F. 
    GENDHDI     GHCDHDI. 
    GENDMHI     GHCDHDI. 
    ORGFOPT     YESNOFM. 
    ORG_1       YESNOFM. 
    ORG_2       ORG_2Q.  
    SLPFOPT     YESNOFM. 
    SLP_01      GEN_3F.  
    SLP_02      MOSFM.   
    SLP_03      MOSFM.   
    SLP_04      MOSFM.   
    CIHFTH      YESNOFM. 
    CIH_1       YESNOFM. 
    CIH_2       CIH_2FM. 
    CIH_3       YESNOFM. 
    CIH_4       CIH_2FM. 
    CIH_5       YESNOFM. 
    CIH_6A      YESNOFM. 
    CIH_6I      YESNOFM. 
    CIH_6B      YESNOFM. 
    CIH_6J      YESNOFM. 
    CIH_6K      YESNOFM. 
    CIH_6G      YESNOFM. 
    CIH_6F      YESNOFM. 
    CIH_6E      YESNOFM. 
    CIH_6L      YESNOFM. 
    CIH_6M      YESNOFM. 
    CIH_6N      YESNOFM. 
    CIH_6H      YESNOFM. 
    CIH_7       YESNOFM. 
    CIH_8A      YESNOFM. 
    CIH_8B      YESNOFM. 
    CIH_8C      YESNOFM. 
    CIH_8J      YESNOFM. 
    CIH_8K      YESNOFM. 
    CIH_8G      YESNOFM. 
    CIH_8L      YESNOFM. 
    CIH_8H      YESNOFM. 
    CIH_8I      YESNOFM. 
    OH1FTH      YESNOFM. 
    OH1_20      GOOD5FM. 
    OH1_21A     YESNOFM. 
    OH1_21B     YESNOFM. 
    OH1_21C     YESNOFM. 
    OH1_22      GAD_04FM.
    OH1FCHW     YESNOFM. 
    HCSFOPT     YESNOFM. 
    HCS_1       PAS12FM. 
    HCS_2       PAS12FM. 
    HCS_3       PAS12FM. 
    HCS_4       PAS12FM. 
    MAM_037     YESNOFM. 
    HWT_2       HWC_2FM. 
    HWT_2A      HWC_2A.  
    HWT_2B      HWC_2B.  
    HWT_2C      HWC_2C.  
    HWT_2D      HWC_2D.  
    HWT_2E      HWC_2E.  
    HWT_2F      HWC_2F.  
    HWT_3       HWT_FM.  
    HWT_N4      WHTFM.   
    HWT_4       HWS_1F.  
    HWTDHTM     HWT_METR.
    HWTDWTK     HWT_WTK. 
    HWTDBMI     HWTD_BMI.
    HWTDISW     HWTCDISW.
    HWTDCOL     HWTDDCOL.
    CCC_031     YESNOFM. 
    CCC_035     YESNOFM. 
    CCC_036     YESNOFM. 
    CCC_051     YESNOFM. 
    CCC_061     YESNOFM. 
    CCC_071     YESNOFM. 
    CCC_072     YESNOFM. 
    CCC_073     YESNOFM. 
    CCC_081     YESNOFM. 
    CCC_91A     YESNOFM. 
    CCC_91E     YESNOFM. 
    CCC_91F     YESNOFM. 
    CCC_101     YESNOFM. 
    CCC_102     AGE3DFM. 
    CCC_10A     YESNOFM. 
    CCC_10B     YESNOFM. 
    CCC_10C     CCC_10C. 
    CCC_105     YESNOFM. 
    CCC_106     YESNOFM. 
    CCC_121     YESNOFM. 
    CCC_131     YESNOFM. 
    CCC_31A     YESNOFM. 
    CCC_141     YESNOFM. 
    CCC_151     YESNOFM. 
    CCC_161     YESNOFM. 
    CCC_171     YESNOFM. 
    CCC_17A     CCC17AFM.
    CCC_181     YESNOFM. 
    CCC_280     YESNOFM. 
    CCC_290     YESNOFM. 
    DIAFOPT     YESNOFM. 
    DIA_01      YESNOFM. 
    DIA_02      TIMES3D. 
    DIA_03      DIAE03FM.
    DIA_04      TIMES3D. 
    DIA_05      YESNOFM. 
    DIA_06      YESNOFM. 
    DIA_07      DIAE07FM.
    DIA_08      FVC_1A.  
    DIA_N8B     TIMES3D. 
    DIA_N8C     TIMES3D. 
    DIA_N8D     TIMES3D. 
    DIA_N8E     TIMES3D. 
    DIA_09      FVC_1A.  
    DIA_N9B     TIMES3D. 
    DIA_N9C     TIMES3D. 
    DIA_N9D     TIMES3D. 
    DIA_N9E     TIMES3D. 
    DIA_10      YESNOFM. 
    DIA_11      YESNOFM. 
    HUIFOPT     YESNOFM. 
    HUI_01      YESNOFM. 
    HUI_02      YESNOFM. 
    HUI_03      YESNOFM. 
    HUI_04      YESNOFM. 
    HUI_05      YESNOFM. 
    HUI_06      YESNOFM. 
    HUI_07      YESNOFM. 
    HUI_07A     YESNOFM. 
    HUI_08      YESNOFM. 
    HUI_09      YESNOFM. 
    HUI_10      YESNOFM. 
    HUI_11      YESNOFM. 
    HUI_12      YESNOFM. 
    HUI_13      YESNOFM. 
    HUI_14      YESNOFM. 
    HUI_15      YESNOFM. 
    HUI_16      YESNOFM. 
    HUI_17      YESNOFM. 
    HUI_18      YESNOFM. 
    HUI_19      HSC_19F. 
    HUI_20      YESNOFM. 
    HUI_21      YESNOFM. 
    HUI_22      YESNOFM. 
    HUI_23      HSC_23F. 
    HUI_24      YESNOFM. 
    HUI_25      HSC_25F. 
    HUI_26      HSC_26F. 
    HUI_27      HSC_27F. 
    HUIDVIS     HUIDVIFM.
    HUIDHER     HUIDHEFM.
    HUIDSPE     HUIDSPFM.
    HUIDMOB     HUIDMOFM.
    HUIDDEX     HUIDEXFM.
    HUIDEMO     HUIDEMFM.
    HUIDCOG     HUIDCOFM.
    HUIDHSI     HUIDHSI. 
    HUP_01      YESNOFM. 
    HUP_02      HSC_29F. 
    HUP_03      HSC_30F. 
    HUPDPAD     HSCDPAD. 
    HCU_1AA     YESNOFM. 
    HCU_1BA     YESNOFM. 
    HCU_1BB     YESNOFM. 
    HCU_1BC     YESNOFM. 
    HCU_1BD     YESNOFM. 
    HCU_1BE     YESNOFM. 
    HCU_1A1     YESNOFM. 
    HCU_1A2     HCU1A2FM.
    HCU_1AC     ADM_LN2G.
    HCU_01      YESNOFM. 
    HCU_01A     NIGHT3D. 
    HCU_02AA    YESNOFM. 
    HCU_02A     TIMES3D. 
    HCU_03A     HCC_CONT.
    HCU_02BB    YESNOFM. 
    HCU_02B     TIMES3D. 
    HCU_02CC    YESNOFM. 
    HCU_02C     TIMES3D. 
    HCU_03C     HCC_CONT.
    HCU_02DD    YESNOFM. 
    HCU_02D     TIMES3D. 
    HCU_03D     HCC_CONT.
    HCU_02EE    YESNOFM. 
    HCU_02E     TIMES3D. 
    HCU_02FF    YESNOFM. 
    HCU_02F     TIMES3D. 
    HCU_02GG    YESNOFM. 
    HCU_02G     TIMES3D. 
    HCU_02II    YESNOFM. 
    HCU_02I     TIMES3D. 
    HCU_02HH    YESNOFM. 
    HCU_02H     TIMES3D. 
    HCU_02JJ    YESNOFM. 
    HCU_02J     TIMES3D. 
    HCUDMDC     CON3DFM. 
    HCUFCOP     YESNOFM. 
    HMCFOPT     YESNOFM. 
    HMC_09      YESNOFM. 
    HMC_10A     YESNOFM. 
    HMC_10B     YESNOFM. 
    HMC_10I     YESNOFM. 
    HMC_10C     YESNOFM. 
    HMC_10D     YESNOFM. 
    HMC_10E     YESNOFM. 
    HMC_10F     YESNOFM. 
    HMC_10G     YESNOFM. 
    HMC_10H     YESNOFM. 
    HMC_11      YESNOFM. 
    HMC_12A     YESNOFM. 
    HMC_12B     YESNOFM. 
    HMC_12G     YESNOFM. 
    HMC_12C     YESNOFM. 
    HMC_12D     YESNOFM. 
    HMC_12E     YESNOFM. 
    HMC_12F     YESNOFM. 
    HMC_3AA     YESNOFM. 
    HMC_3AB     YESNOFM. 
    HMC_3AI     YESNOFM. 
    HMC_3AC     YESNOFM. 
    HMC_3AD     YESNOFM. 
    HMC_3AE     YESNOFM. 
    HMC_3AF     YESNOFM. 
    HMC_3AG     YESNOFM. 
    HMC_3AH     YESNOFM. 
    HMC_3BA     YESNOFM. 
    HMC_3BB     YESNOFM. 
    HMC_3BI     YESNOFM. 
    HMC_3BC     YESNOFM. 
    HMC_3BD     YESNOFM. 
    HMC_3BE     YESNOFM. 
    HMC_3BF     YESNOFM. 
    HMC_3BG     YESNOFM. 
    HMC_3BH     YESNOFM. 
    HMC_3GA     YESNOFM. 
    HMC_3GB     YESNOFM. 
    HMC_3GI     YESNOFM. 
    HMC_3GC     YESNOFM. 
    HMC_3GD     YESNOFM. 
    HMC_3GE     YESNOFM. 
    HMC_3GF     YESNOFM. 
    HMC_3GG     YESNOFM. 
    HMC_3GH     YESNOFM. 
    HMC_3CA     YESNOFM. 
    HMC_3CB     YESNOFM. 
    HMC_3CI     YESNOFM. 
    HMC_3CC     YESNOFM. 
    HMC_3CD     YESNOFM. 
    HMC_3CE     YESNOFM. 
    HMC_3CF     YESNOFM. 
    HMC_3CG     YESNOFM. 
    HMC_3CH     YESNOFM. 
    HMC_3DA     YESNOFM. 
    HMC_3DB     YESNOFM. 
    HMC_3DI     YESNOFM. 
    HMC_3DC     YESNOFM. 
    HMC_3DD     YESNOFM. 
    HMC_3DE     YESNOFM. 
    HMC_3DF     YESNOFM. 
    HMC_3DG     YESNOFM. 
    HMC_3DH     YESNOFM. 
    HMC_3EA     YESNOFM. 
    HMC_3EB     YESNOFM. 
    HMC_3EI     YESNOFM. 
    HMC_3EC     YESNOFM. 
    HMC_3ED     YESNOFM. 
    HMC_3EE     YESNOFM. 
    HMC_3EF     YESNOFM. 
    HMC_3EG     YESNOFM. 
    HMC_3EH     YESNOFM. 
    HMC_3FA     YESNOFM. 
    HMC_3FB     YESNOFM. 
    HMC_3FI     YESNOFM. 
    HMC_3FC     YESNOFM. 
    HMC_3FD     YESNOFM. 
    HMC_3FE     YESNOFM. 
    HMC_3FF     YESNOFM. 
    HMC_3FG     YESNOFM. 
    HMC_3FH     YESNOFM. 
    HMC_14      YESNOFM. 
    HMC_15A     YESNOFM. 
    HMC_15B     YESNOFM. 
    HMC_15C     YESNOFM. 
    HMC_15D     YESNOFM. 
    HMC_15E     YESNOFM. 
    HMC_15F     YESNOFM. 
    HMC_15G     YESNOFM. 
    HMC_15H     YESNOFM. 
    HMC_15I     YESNOFM. 
    HMC_15J     YESNOFM. 
    HMC_15K     YESNOFM. 
    HMC_15L     YESNOFM. 
    HMC_15N     YESNOFM. 
    HMC_15O     YESNOFM. 
    HMC_15M     YESNOFM. 
    HMC_16A     YESNOFM. 
    HMC_16B     YESNOFM. 
    HMC_16I     YESNOFM. 
    HMC_16C     YESNOFM. 
    HMC_16D     YESNOFM. 
    HMC_16E     YESNOFM. 
    HMC_16F     YESNOFM. 
    HMC_16G     YESNOFM. 
    HMC_16H     YESNOFM. 
    HMC_17A     YESNOFM. 
    HMC_17B     YESNOFM. 
    HMC_17C     YESNOFM. 
    HMC_17D     YESNOFM. 
    HMC_17E     YESNOFM. 
    HMCFRHC     YESNOFM. 
    PASFOPT     YESNOFM. 
    PAS_11      YESNOFM. 
    PAS_12      PAS12FM. 
    PAS_13      SATQ3FM. 
    PAS_21A     YESNOFM. 
    PAS_21B     SAT_21BF.
    PAS_22      PAS12FM. 
    PAS_23      SATQ3FM. 
    PAS_31A     YESNOFM. 
    PAS_31B     SAT_31BF.
    PAS_32      PAS12FM. 
    PAS_33      SATQ3FM. 
    PSCFOPT     YESNOFM. 
    PSC_1       YESNOFM. 
    PSC_2       PAS12FM. 
    PSC_3       SATQ3FM. 
    RAC_1       SOMETIME.
    RAC_2A      SOMETIME.
    RAC_2B1     RAC2B1FM.
    RAC_2B2     RAC2B2FM.
    RAC_2C      SOMETIME.
    RAC_5       RAC_5FM. 
    RAC_6A      YESNOFM. 
    RAC_6B1     YESNOFM. 
    RAC_6C      YESNOFM. 
    RAC_6E      YESNOFM. 
    RAC_6F      YESNOFM. 
    RAC_6G      YESNOFM. 
    RACDIMP     SOMETIME.
    RACDPAL     SOMETIME.
    RACF6R      YESNOFM. 
    FLU_160     YESNOFM. 
    FLU_162     FS52F.   
    FLU_164     MONTHFM. 
    FLU_165     INJ_4F.  
    FLU_66A     YESNOFM. 
    FLU_66B     YESNOFM. 
    FLU_66C     YESNOFM. 
    FLU_66D     YESNOFM. 
    FLU_66E     YESNOFM. 
    FLU_66F     YESNOFM. 
    FLU_66G     YESNOFM. 
    FLU_66H     YESNOFM. 
    FLU_66I     YESNOFM. 
    FLU_66J     YESNOFM. 
    FLU_66K     YESNOFM. 
    FLU_66L     YESNOFM. 
    FLU_66M     YESNOFM. 
    FLU_66O     YESNOFM. 
    FLU_66N     YESNOFM. 
    BPCFOPT     YESNOFM. 
    BPC_010     YESNOFM. 
    BPC_012     WH2_LAST.
    BPC_16A     YESNOFM. 
    BPC_16B     YESNOFM. 
    BPC_16C     YESNOFM. 
    BPC_16D     YESNOFM. 
    BPC_16E     YESNOFM. 
    BPC_16F     YESNOFM. 
    BPC_16G     YESNOFM. 
    BPC_16H     YESNOFM. 
    BPC_16I     YESNOFM. 
    BPC_16J     YESNOFM. 
    BPC_16K     YESNOFM. 
    BPC_16L     YESNOFM. 
    BPC_16N     YESNOFM. 
    BPC_16M     YESNOFM. 
    PAPFOPT     YESNOFM. 
    PAP_020     YESNOFM. 
    PAP_022     WHC_22F. 
    PAP_26A     YESNOFM. 
    PAP_26B     YESNOFM. 
    PAP_26C     YESNOFM. 
    PAP_26D     YESNOFM. 
    PAP_26E     YESNOFM. 
    PAP_26F     YESNOFM. 
    PAP_26G     YESNOFM. 
    PAP_26H     YESNOFM. 
    PAP_26I     YESNOFM. 
    PAP_26J     YESNOFM. 
    PAP_26K     YESNOFM. 
    PAP_26L     YESNOFM. 
    PAP_26M     YESNOFM. 
    PAP_26N     YESNOFM. 
    PAP_26P     YESNOFM. 
    PAP_26O     YESNOFM. 
    MAMFOPT     YESNOFM. 
    MAM_030     YESNOFM. 
    MAM_31A     YESNOFM. 
    MAM_31B     YESNOFM. 
    MAM_31C     YESNOFM. 
    MAM_31D     YESNOFM. 
    MAM_31E     YESNOFM. 
    MAM_31F     YESNOFM. 
    MAM_31G     YESNOFM. 
    MAM_31H     YESNOFM. 
    MAM_032     WH2_LAST.
    MAM_36A     YESNOFM. 
    MAM_36B     YESNOFM. 
    MAM_36C     YESNOFM. 
    MAM_36D     YESNOFM. 
    MAM_36E     YESNOFM. 
    MAM_36F     YESNOFM. 
    MAM_36G     YESNOFM. 
    MAM_36H     YESNOFM. 
    MAM_36I     YESNOFM. 
    MAM_36J     YESNOFM. 
    MAM_36K     YESNOFM. 
    MAM_36L     YESNOFM. 
    MAM_36N     YESNOFM. 
    MAM_36O     YESNOFM. 
    MAM_36M     YESNOFM. 
    MAM_038     YESNOFM. 
    BRXFOPT     YESNOFM. 
    BRX_110     YESNOFM. 
    BRX_112     WH2_LAST.
    BRX_16A     YESNOFM. 
    BRX_16B     YESNOFM. 
    BRX_16C     YESNOFM. 
    BRX_16D     YESNOFM. 
    BRX_16E     YESNOFM. 
    BRX_16F     YESNOFM. 
    BRX_16G     YESNOFM. 
    BRX_16H     YESNOFM. 
    BRX_16I     YESNOFM. 
    BRX_16J     YESNOFM. 
    BRX_16K     YESNOFM. 
    BRX_16L     YESNOFM. 
    BRX_16N     YESNOFM. 
    BRX_16O     YESNOFM. 
    BRX_16M     YESNOFM. 
    BSXFOPT     YESNOFM. 
    BSX_120     YESNOFM. 
    BSX_121     WHS_91F. 
    BSX_22A     YESNOFM. 
    BSX_22B     YESNOFM. 
    BSX_22C     YESNOFM. 
    BSX_22D     YESNOFM. 
    BSX_22H     YESNOFM. 
    BSX_22G     YESNOFM. 
    PSAFOPT     YESNOFM. 
    PSA_170     YESNOFM. 
    PSA_172     PSACFM.  
    PSA_73A     YESNOFM. 
    PSA_73B     YESNOFM. 
    PSA_73C     YESNOFM. 
    PSA_73G     YESNOFM. 
    PSA_73D     YESNOFM. 
    PSA_73E     YESNOFM. 
    PSA_73F     YESNOFM. 
    PSA_174     YESNOFM. 
    PSA_175     PSACFM.  
    CCSFOPT     YESNOFM. 
    CCS_180     YESNOFM. 
    CCS_182     CCS182FM.
    CCS_83A     YESNOFM. 
    CCS_83B     YESNOFM. 
    CCS_83C     YESNOFM. 
    CCS_83G     YESNOFM. 
    CCS_83D     YESNOFM. 
    CCS_83E     YESNOFM. 
    CCS_83F     YESNOFM. 
    CCS_184     YESNOFM. 
    CCS_185     CCS182FM.
    CCS_86A     YESNOFM. 
    CCS_86B     YESNOFM. 
    CCS_86C     YESNOFM. 
    CCS_86G     YESNOFM. 
    CCS_86D     YESNOFM. 
    CCS_86E     YESNOFM. 
    CCS_86F     YESNOFM. 
    CCS_187     YESNOFM. 
    EYXFOPT     YESNOFM. 
    EYX_140     YESNOFM. 
    EYX_142     EYX142FM.
    EYX_46A     YESNOFM. 
    EYX_46B     YESNOFM. 
    EYX_46C     YESNOFM. 
    EYX_46D     YESNOFM. 
    EYX_46E     YESNOFM. 
    EYX_46F     YESNOFM. 
    EYX_46G     YESNOFM. 
    EYX_46H     YESNOFM. 
    EYX_46I     YESNOFM. 
    EYX_46J     YESNOFM. 
    EYX_46K     YESNOFM. 
    EYX_46L     YESNOFM. 
    EYX_46N     YESNOFM. 
    EYX_46M     YESNOFM. 
    DENFOPT     YESNOFM. 
    DEN_130     YESNOFM. 
    DEN_132     DV61FM.  
    DEN_36A     YESNOFM. 
    DEN_36B     YESNOFM. 
    DEN_36C     YESNOFM. 
    DEN_36D     YESNOFM. 
    DEN_36E     YESNOFM. 
    DEN_36F     YESNOFM. 
    DEN_36G     YESNOFM. 
    DEN_36H     YESNOFM. 
    DEN_36I     YESNOFM. 
    DEN_36J     YESNOFM. 
    DEN_36K     YESNOFM. 
    DEN_36L     YESNOFM. 
    DEN_36M     YESNOFM. 
    DEN_36O     YESNOFM. 
    DEN_36N     YESNOFM. 
    OH2FOPT     YESNOFM. 
    OH2_10      OH2C10FM.
    OH2_11      YESNOFM. 
    OH2_11A     YESNOFM. 
    OH2_11B     YESNOFM. 
    OH2_11C     YESNOFM. 
    OH2_12      YESNOFM. 
    OH2_13      YESNOFM. 
    OH2_20      YESNOFM. 
    OH2_21      YESNOFM. 
    OH2_22      YESNOFM. 
    OH2_23      GAD_04FM.
    OH2_24      GAD_04FM.
    OH2_25A     YESNOFM. 
    OH2_25B     YESNOFM. 
    OH2_25C     YESNOFM. 
    OH2_25D     YESNOFM. 
    OH2_25E     YESNOFM. 
    OH2_25F     YESNOFM. 
    OH2_25G     YESNOFM. 
    OH2_30      OH2C30FM.
    OH2FLIM     OH2SIMFM.
    OH2FOFP     OH2CDFM. 
    FDCFOPT     YESNOFM. 
    FDC_1A      FDC1AFM. 
    FDC_1B      FDC1AFM. 
    FDC_1C      FDC1AFM. 
    FDC_1D      FDC1AFM. 
    FDC_2A      FDC1AFM. 
    FDC_2B      FDC1AFM. 
    FDC_2C      FDC1AFM. 
    FDC_3A      FDC1AFM. 
    FDC_3B      FDC1AFM. 
    FDC_3C      FDC1AFM. 
    FDC_3D      FDC1AFM. 
    FDC_3E      FDC1AFM. 
    FDCFCAH     YESNOFM. 
    FDCFCHO     YESNOFM. 
    FDCFAVD     YESNOFM. 
    DSUFOPT     YESNOFM. 
    DSU_1A      YESNOFM. 
    DSU_1B      YESNOFM. 
    DSU_1C      DAY2DFM. 
    DSU_1D      DAY2DFM. 
    DSUDCON     DSUCDCON.
    FVC_1A      FVC_1A.  
    FVC_1B      TIMES2D. 
    FVC_1C      TIMES2D. 
    FVC_1D      TIMES3D. 
    FVC_1E      TIMES3D. 
    FVC_2A      FVC_1A.  
    FVC_2B      TIMES2D. 
    FVC_2C      TIMES2D. 
    FVC_2D      TIMES3D. 
    FVC_2E      TIMES3D. 
    FVC_3A      FVC_1A.  
    FVC_3B      TIMES2D. 
    FVC_3C      TIMES2D. 
    FVC_3D      TIMES3D. 
    FVC_3E      TIMES3D. 
    FVC_4A      FVC_1A.  
    FVC_4B      TIMES2D. 
    FVC_4C      TIMES2D. 
    FVC_4D      TIMES3D. 
    FVC_4E      TIMES3D. 
    FVC_5A      FVC_1A.  
    FVC_5B      TIMES2D. 
    FVC_5C      TIMES2D. 
    FVC_5D      TIMES3D. 
    FVC_5E      TIMES3D. 
    FVC_6A      FVC_1A.  
    FVC_6B      SERV2FM. 
    FVC_6C      SERV2FM. 
    FVC_6D      SERV3FM. 
    FVC_6E      SERV3FM. 
    FVCDJUI     FVC_DC.  
    FVCDFRU     FVC_DC.  
    FVCDSAL     FVC_DC.  
    FVCDPOT     FVC_DC.  
    FVCDCAR     FVC_DC.  
    FVCDVEG     FVC_PO.  
    FVCDTOT     FVC_SP.  
    FVCGTOT     FVC_RDA. 
    PAC_1A      YESNOFM. 
    PAC_1B      YESNOFM. 
    PAC_1C      YESNOFM. 
    PAC_1D      YESNOFM. 
    PAC_1E      YESNOFM. 
    PAC_1F      YESNOFM. 
    PAC_1G      YESNOFM. 
    PAC_1H      YESNOFM. 
    PAC_1I      YESNOFM. 
    PAC_1J      YESNOFM. 
    PAC_1K      YESNOFM. 
    PAC_1L      YESNOFM. 
    PAC_1M      YESNOFM. 
    PAC_1N      YESNOFM. 
    PAC_1O      YESNOFM. 
    PAC_1P      YESNOFM. 
    PAC_1Q      YESNOFM. 
    PAC_1R      YESNOFM. 
    PAC_1S      YESNOFM. 
    PAC_1T      YESNOFM. 
    PAC_1Z      YESNOFM. 
    PAC_1U      YESNOFM. 
    PAC_1V      YESNOFM. 
    PAC_1W      YESNOFM. 
    PAC_1X      YESNOFM. 
    PAC_2A      TIMES3D. 
    PAC_3A      PAC_TIME.
    PAC_2B      TIMES3D. 
    PAC_3B      PAC_TIME.
    PAC_2C      TIMES3D. 
    PAC_3C      PAC_TIME.
    PAC_2D      TIMES3D. 
    PAC_3D      PAC_TIME.
    PAC_2E      TIMES3D. 
    PAC_3E      PAC_TIME.
    PAC_2F      TIMES3D. 
    PAC_3F      PAC_TIME.
    PAC_2G      TIMES3D. 
    PAC_3G      PAC_TIME.
    PAC_2H      TIMES3D. 
    PAC_3H      PAC_TIME.
    PAC_2I      TIMES3D. 
    PAC_3I      PAC_TIME.
    PAC_2J      TIMES3D. 
    PAC_3J      PAC_TIME.
    PAC_2K      TIMES3D. 
    PAC_3K      PAC_TIME.
    PAC_2L      TIMES3D. 
    PAC_3L      PAC_TIME.
    PAC_2M      TIMES3D. 
    PAC_3M      PAC_TIME.
    PAC_2N      TIMES3D. 
    PAC_3N      PAC_TIME.
    PAC_2O      TIMES3D. 
    PAC_3O      PAC_TIME.
    PAC_2P      TIMES3D. 
    PAC_3P      PAC_TIME.
    PAC_2Q      TIMES3D. 
    PAC_3Q      PAC_TIME.
    PAC_2R      TIMES3D. 
    PAC_3R      PAC_TIME.
    PAC_2S      TIMES3D. 
    PAC_3S      PAC_TIME.
    PAC_2T      TIMES3D. 
    PAC_3T      PAC_TIME.
    PAC_2Z      TIMES3D. 
    PAC_3Z      PAC_TIME.
    PAC_2U      TIMES3D. 
    PAC_3U      PAC_TIME.
    PAC_2W      TIMES3D. 
    PAC_3W      PAC_TIME.
    PAC_2X      TIMES3D. 
    PAC_3X      PAC_TIME.
    PAC_7       PACF_7FM.
    PAC_7A      TIMES3D. 
    PAC_7B      PAC_TIME.
    PAC_8       PACF_7FM.
    PAC_8A      TIMES3D. 
    PAC_8B      PAC_TIME.
    PACDEE      PACDEE.  
    PACDFM      PACDFM.  
    PACFLEI     YESNOFM. 
    PACDFR      PACDFR.  
    PACFD       YESNOFM. 
    PACDPAI     PACDPAI. 
    PACDTLE     PACDTLFM.
    PACDLTI     PACDPAI. 
    PACFLTI     YESNOFM. 
    SACFTH      YESNOFM. 
    SAC_1       SAC_1F.  
    SAC_2       SAC_1F.  
    SAC_3       SAC_1F.  
    SAC_4       SAC_1F.  
    SACDTOT     SAC_NUM. 
    SACDTER     SAC_NUM. 
    UPEFOPT     YESNOFM. 
    UPE_01      PAC_5F.  
    UPE_02A     PAC_5F.  
    UPE_02B     PAC_5F.  
    UPE_02C     PAC_5F.  
    UPE_03A     UPEC3AFM.
    UPE_03B     UPEC3AFM.
    UPE_04A     PAC_5F.  
    UPE_05A     PAC_5F.  
    UPE_05B     PAC_5F.  
    UPE_06      YESNOFM. 
    UPE_06A     PAC_5F.  
    UPE_06B     PAC_5F.  
    UPE_06C     PAC_5F.  
    UPEFILS     YESNOFM. 
    UPEFSNB     YESNOFM. 
    UPEFSKB     YESNOFM. 
    SSBFOPT     YESNOFM. 
    SSB_01      YESNOFM. 
    SSB_02      YESNOFM. 
    SSB_03      YESNOFM. 
    SSB_06      SSBE06FM.
    SSB_07      SSBE07FM.
    SSB_08      SSBE07FM.
    SSB_09A     SSBE07FM.
    SSB_09B     SSBE07FM.
    SSB_10      SSBE10FM.
    SSB_11      SSBE07FM.
    SSB_12      SSBE10FM.
    SSB_13      YESNOFM. 
    SSB_14      YESNOFM. 
    SSB_15      MELANOFM.
    INJFOPT     YESNOFM. 
    REP_1       YESNOFM. 
    REP_3       RPC03FM. 
    REP_4A      YESNOFM. 
    REP_4B      YESNOFM. 
    REP_4C      YESNOFM. 
    REP_4G      YESNOFM. 
    REP_4D      YESNOFM. 
    REP_4E      YESNOFM. 
    REP_4F      YESNOFM. 
    INJ_01      YESNOFM. 
    INJ_02      TIMES2D. 
    INJ_03      MONTHFM. 
    INJ_04      INJ_4F.  
    INJ_05      IJC03F.  
    INJ_06      IJC04F.  
    INJ_07      IJC_4A.  
    INJ_08      IJC05F.  
    INJ_09      IJC_9F.  
    INJ_10      YESNOFM. 
    INJ_11      IJC_10A. 
    INJ_12      IJC_10B. 
    INJ_13      YESNOFM. 
    INJ_14A     YESNOFM. 
    INJ_14B     YESNOFM. 
    INJ_14C     YESNOFM. 
    INJ_14D     YESNOFM. 
    INJ_14E     YESNOFM. 
    INJ_14F     YESNOFM. 
    INJ_14G     YESNOFM. 
    INJ_14H     YESNOFM. 
    INJ_14I     YESNOFM. 
    INJ_14J     YESNOFM. 
    INJ_14K     YESNOFM. 
    INJ_15      YESNOFM. 
    INJ_16      YESNOFM. 
    INJ_17      IJC_NUM. 
    INJDTBS     INJ_TBS. 
    INJDCAU     INJ_CAU. 
    INJDCBP     IJCD2FM. 
    INJDSTT     INJ_STT. 
    SWLFOPT     YESNOFM. 
    SWL_02      SCR_01FM.
    SWL_03      SCR_01FM.
    SWL_04      SCR_01FM.
    SWL_05      SCR_01FM.
    SWL_06      SCR_01FM.
    SWL_07      SCR_01FM.
    SWL_08      SCR_01FM.
    SWL_09      SCR_01FM.
    SWL_10      SCR_01FM.
    STSFOPT     YESNOFM. 
    STS_1       GOOD5FM. 
    STS_2       GOOD5FM. 
    STS_3       STR_3FM. 
    STCFOPT     YESNOFM. 
    STC_61      GAD_04FM.
    STC_62      GAD_04FM.
    STC_63      GAD_04FM.
    STC_64      GAD_04FM.
    STC_65A     GAD_04FM.
    STC_65B     STR06FM. 
    STC_65C     GAD_04FM.
    STC_65D     GAD_04FM.
    STC_66      GAD_04FM.
    STC_67      GAD_04FM.
    STC_68      GAD_04FM.
    STC_69      GAD_04FM.
    STC_610     GAD_04FM.
    STC_611     GAD_04FM.
    RLEFOPT     YESNOFM. 
    RLE_201     YESNOFM. 
    RLE_202     YESNOFM. 
    RLE_203     YESNOFM. 
    RLE_204     YESNOFM. 
    RLE_205     YESNOFM. 
    RLE_206     YESNOFM. 
    RLE_207     YESNOFM. 
    RLE_208     YESNOFM. 
    RLE_209     YESNOFM. 
    RLE_210     YESNOFM. 
    RLE_211     YESNOFM. 
    CSTFOPT     YESNOFM. 
    CST_1       YESNOFM. 
    CST_2       YESNOFM. 
    CST_3       YESNOFM. 
    CST_4       YESNOFM. 
    CST_5       YESNOFM. 
    CST_6       YESNOFM. 
    CST_7       YESNOFM. 
    WSTFOPT     YESNOFM. 
    WST_401     AGREEFM. 
    WST_402     AGREEFM. 
    WST_403     AGREEFM. 
    WST_404     AGREEFM. 
    WST_405     AGREEFM. 
    WST_406     AGREEFM. 
    WST_407     AGREEFM. 
    WST_408     AGREEFM. 
    WST_409     AGREEFM. 
    WST_410     AGREEFM. 
    WST_411     AGREEFM. 
    WST_412     AGREEFM. 
    WST_12A     AGREEFM. 
    WST_413     WSTQ2FM. 
    WSTDSKI     SCORE2D. 
    WSTDAUT     SCORE2D. 
    WSTDPSY     SCORE2D. 
    WSTDJIN     SCORE1D. 
    WSTDPHY     SCORE1D. 
    WSTDSOC     SCORE2D. 
    WSTDJST     SCORE3FM.
    SFEFOPT     YESNOFM. 
    SFE_501     AGREEFM. 
    SFE_502     AGREEFM. 
    SFE_503     AGREEFM. 
    SFE_504     AGREEFM. 
    SFE_505     AGREEFM. 
    SFE_506     AGREEFM. 
    SFEDE1      SCORE2D. 
    MASFOPT     YESNOFM. 
    MAS_601     AGREEFM. 
    MAS_602     AGREEFM. 
    MAS_603     AGREEFM. 
    MAS_604     AGREEFM. 
    MAS_605     AGREEFM. 
    MAS_606     AGREEFM. 
    MAS_607     AGREEFM. 
    MASDM1      SCORE2D. 
    SMK_01A     YESNOFM. 
    SMK_01B     YESNOFM. 
    SMK_01C     AGE3DFM. 
    SMK_202     SMC_2F.  
    SMK_203     AGE3DFM. 
    SMK_204     CIG_NUM. 
    SMK_05B     CIG_NUM. 
    SMK_05C     DAY2DFM. 
    SMK_05D     YESNOFM. 
    SMK_06A     SMKCFM.  
    SMK_06B     MONTHFM. 
    SMK_06C     YEAR3NUM.
    SMK_207     AGE3DFM. 
    SMK_208     CIG_NUM. 
    SMK_09A     SMKCFM.  
    SMK_09B     MONTHFM. 
    SMK_09C     YEAR3NUM.
    SMK_10      YESNOFM. 
    SMK_10A     SMKCFM.  
    SMK_10B     MONTHFM. 
    SMK_10C     YEAR3NUM.
    SMKDSTY     SMCDTYP. 
    SMKDSTP     YEAR3NUM.
    SMKDYCS     YEAR3NUM.
    SCHFOPT     YESNOFM. 
    SCH_1       YESNOFM. 
    SCH_2       YESNOFM. 
    SCH_3       YESNOFM. 
    SCH_4       TIMES2D. 
    SCHDSTG     SCHCDSTG.
    NDEFOPT     YESNOFM. 
    NDE_1       NDE1FM.  
    NDE_2       YESNOFM. 
    NDE_3       NDE3FM.  
    NDE_4       YESNOFM. 
    NDE_5       YESNOFM. 
    NDEDFTT     NDECDFM. 
    SCAFOPT     YESNOFM. 
    SCA_10      YESNOFM. 
    SCA_10A     SCA_FM.  
    SCA_11      YESNOFM. 
    SCA_11A     SCA_FM.  
    SCA_12      YESNOFM. 
    SCA_12A     SCA_FM.  
    SCA_50      YESNOFM. 
    SCA_60      YESNOFM. 
    SCA_61      YESNOFM. 
    SCA_62      YESNOFM. 
    SCADQUI     SCA_QUI. 
    SPCFOPT     YESNOFM. 
    SPC_10      YESNOFM. 
    SPC_11      YESNOFM. 
    SPC_12      YESNOFM. 
    SPC_13      YESNOFM. 
    SPC_14A     YESNOFM. 
    SPC_14B     YESNOFM. 
    SPC_14C     YESNOFM. 
    SPC_14D     YESNOFM. 
    SPC_14E     YESNOFM. 
    SPC_14F     YESNOFM. 
    SPC_14G     YESNOFM. 
    SPC_20      YESNOFM. 
    SPC_21      YESNOFM. 
    SPC_22      YESNOFM. 
    YSMFOPT     YESNOFM. 
    YSM_1       SMK_300F.
    YSM_2       YESNOFM. 
    YSM_3       YESNOFM. 
    YSM_4       YESNOFM. 
    YSM_5       YESNOFM. 
    ETS_10      YESNOFM. 
    ETS_11      PERS2D.  
    ETS_20      YESNOFM. 
    ETS_20B     YESNOFM. 
    ETS_5       YESNOFM. 
    ETS_6A      YESNOFM. 
    ETS_6B      YESNOFM. 
    ETS_6C      YESNOFM. 
    ETS_6D      YESNOFM. 
    TALFOPT     YESNOFM. 
    TAL_1       YESNOFM. 
    TAL_2       YESNOFM. 
    TAL_3       YESNOFM. 
    TAL_4       YESNOFM. 
    ALC_1       YESNOFM. 
    ALC_2       ALC6_2F. 
    ALC_3       ALC_3F.  
    ALCDTTM     ALCDTTFM.
    ALWFOPT     YESNOFM. 
    ALW_1       YESNOFM. 
    ALW_2A1     ALC_NUM. 
    ALW_2A2     ALC_NUM. 
    ALW_2A3     ALC_NUM. 
    ALW_2A4     ALC_NUM. 
    ALW_2A5     ALC_NUM. 
    ALW_2A6     ALC_NUM. 
    ALW_2A7     ALC_NUM. 
    ALWDDLY     ALWDDLFM.
    ALWDWKY     ALWDWKFM.
    ALNFOPT     YESNOFM. 
    ALN_1       YESNOFM. 
    ALN_2       YESNOFM. 
    ALN_3A      YESNOFM. 
    ALN_3B      YESNOFM. 
    ALN_3C      YESNOFM. 
    ALN_3D      YESNOFM. 
    ALN_3E      YESNOFM. 
    ALN_3F      YESNOFM. 
    ALN_3G      YESNOFM. 
    ALN_3H      YESNOFM. 
    ALN_3I      YESNOFM. 
    ALN_3J      YESNOFM. 
    ALN_3K      YESNOFM. 
    ALN_3L      YESNOFM. 
    ALN_3N      YESNOFM. 
    ALN_3M      YESNOFM. 
    ALNDTYP     ALCDTYP. 
    DRVFOPT     YESNOFM. 
    DRV_01A     YESNOFM. 
    DRV_01B     YESNOFM. 
    DRV_02      PAC_5F.  
    DRV_03      GAD_04FM.
    DRV_04      GAD_04FM.
    DRV_05      DRVC05FM.
    DRV_06      DRVC06FM.
    DRV_07      YESNOFM. 
    DRV_07A     TIMES2D. 
    DRV_08A     DRV8AFM. 
    DRV_08B     DRV8BFM. 
    DRV_09      DRV09FM. 
    DRV_10      YESNOFM. 
    DRV_10A     TIMES2D. 
    DRV_11A     YESNOFM. 
    DRV_11B     YESNOFM. 
    DRV_12      PAC_5F.  
    DRV_13      YESNOFM. 
    DRV_13A     TIMES2D. 
    DRV_14      YESNOFM. 
    DRV_14A     TIMES2D. 
    DRVFSBU     DRVCDSBU.
    ALDFOPT     YESNOFM. 
    ALD_01      YESNOFM. 
    ALD_02      AD_TIMES.
    ALD_03      YESNOFM. 
    ALD_04      YESNOFM. 
    ALD_05      YESNOFM. 
    ALD_06      YESNOFM. 
    ALD_07      YESNOFM. 
    ALD_08      AD_TIMES.
    ALD_09      YESNOFM. 
    ALD_10      YESNOFM. 
    ALD_11      YESNOFM. 
    ALD_12      YESNOFM. 
    ALD_13      YESNOFM. 
    ALD_14      YESNOFM. 
    ALD_15A     ALD_UOA. 
    ALD_5B1     DEPINTER.
    ALD_5B2     MIA_272F.
    ALD_15C     ALD_UOA. 
    ALD_15D     ALD_UOA. 
    ALDDSF      AD_DSF.  
    ALDDINT     INTFFM.  
    ALDDPP      AD_DPP.  
    ALDFINT     YESNOFM. 
    MEX_01      YESNOFM. 
    MEX_01A     YEARFM.  
    MEX_02      YESNOFM. 
    MEX_03      YESNOFM. 
    MEX_04      MEXE4FM. 
    MEX_05      YESNOFM. 
    MEX_06      MEXE06FM.
    MEX_07      MEXE07FM.
    MEX_08      MEXE8FM. 
    MEX_09      YESNOFM. 
    MEX_10      MEXE0FM. 
    MEXDEBF     MEXCDEFM.
    MEXFEB6     YESNOFM. 
    MXAFOPT     YESNOFM. 
    MXA_01      YESNOFM. 
    MXA_02      ALC6_2F. 
    MXA_03      YESNOFM. 
    MXA_04      ALC6_2F. 
    MXSFOPT     YESNOFM. 
    MXS_01      SMC_2F.  
    MXS_02      CIG_NUM. 
    MXS_03      CIG_NUM. 
    MXS_04      SMC_2F.  
    MXS_05      CIG_NUM. 
    MXS_06      CIG_NUM. 
    MXS_07      YESNOFM. 
    IDGFOPT     YESNOFM. 
    IDG_01      IDG4_FM. 
    IDG_02      YESNOFM. 
    IDG_03      IDG3_2FM.
    IDG_04      IDG4_FM. 
    IDG_05      YESNOFM. 
    IDG_06      IDG3_2FM.
    IDG_07      IDG4_FM. 
    IDG_08      YESNOFM. 
    IDG_09      IDG3_2FM.
    IDG_10      IDG4_FM. 
    IDG_11      YESNOFM. 
    IDG_12      IDG3_2FM.
    IDG_13      IDG4_FM. 
    IDG_14      YESNOFM. 
    IDG_15      IDG3_2FM.
    IDG_16      IDG4_FM. 
    IDG_17      YESNOFM. 
    IDG_18      IDG3_2FM.
    IDG_19      IDG4_FM. 
    IDG_20      YESNOFM. 
    IDG_21      IDG3_2FM.
    IDG_22      IDG4_FM. 
    IDG_23      YESNOFM. 
    IDG_24      IDG3_2FM.
    IDG_25A     YESNOFM. 
    IDG_25B     YESNOFM. 
    IDG_25C     YESNOFM. 
    IDG_25D     YESNOFM. 
    IDG_25E     YESNOFM. 
    IDG_25F     YESNOFM. 
    IDG_25G     YESNOFM. 
    IDG_25H     YESNOFM. 
    IDG_26A     ALD_UOA. 
    IDG_6B1     DEPINTER.
    IDG_6B2     MIA_272F.
    IDG_26C     ALD_UOA. 
    IDG_26D     ALD_UOA. 
    IDGFLCA     YESNOFM. 
    IDGFLCM     YESNOFM. 
    IDGFYCM     YESNOFM. 
    IDGFLCO     YESNOFM. 
    IDGFLAM     YESNOFM. 
    IDGFLEX     YESNOFM. 
    IDGFLHA     YESNOFM. 
    IDGFLGL     YESNOFM. 
    IDGFLHE     YESNOFM. 
    IDGFLST     YESNOFM. 
    IDGFLA      YESNOFM. 
    IDGFLAC     YESNOFM. 
    IDGFYA      YESNOFM. 
    IDGFYAC     YESNOFM. 
    IDGDINT     INTFFM.  
    IDGFINT     YESNOFM. 
    CPGFOPT     YESNOFM. 
    CPG_01A     DAILYFM. 
    CPG_01B     DAILYFM. 
    CPG_01C     DAILYFM. 
    CPG_01D     DAILYFM. 
    CPG_01E     DAILYFM. 
    CPG_01F     DAILYFM. 
    CPG_01G     DAILYFM. 
    CPG_01H     DAILYFM. 
    CPG_01I     DAILYFM. 
    CPG_01J     DAILYFM. 
    CPG_01K     DAILYFM. 
    CPG_01L     DAILYFM. 
    CPG_01M     DAILYFM. 
    CPG_01N     CPG01NFM.
    CPG_02      CPG_02FM.
    CPG_03      NEVER_1D.
    CPG_04      NEVER_1D.
    CPG_05      NEVER_1D.
    CPG_06      NEVER_1D.
    CPG_07      NEVER_1D.
    CPG_08      NEVER_1D.
    CPG_09      NEVER_1D.
    CPG_10      NEVER_1D.
    CPG_11      NEVER_1D.
    CPG_12      NEVER_1D.
    CPG_13      NEVER_1D.
    CPG_14      NEVER_1D.
    CPG_15      NEVER_1D.
    CPG_16      NEVER_1D.
    CPG_17      YESNOFM. 
    CPG_18      YESNOFM. 
    CPG_19A     ALD_UOA. 
    CPG_9B1     DEPINTER.
    CPG_9B2     MIA_272F.
    CPG_19C     ALD_UOA. 
    CPG_19D     ALD_UOA. 
    CPGFGAM     YESNOFM. 
    CPGDSEV     CPGBDSEM.
    CPGDTYP     CPGBDTYP.
    CPGDACT     CPGBDACT.
    CPGDINT     INTFFM.  
    CPGFINT     YESNOFM. 
    SXBFOPT     YESNOFM. 
    SXB_1       YESNOFM. 
    SXB_2       AGE3DFM. 
    SXB_3       YESNOFM. 
    SXB_4       SHS_4F.  
    SXB_07      YESNOFM. 
    SXB_7A      YESNOFM. 
    SXB_09      AGREEFM. 
    SXB_10      SXB102FM.
    SXB_11      YESNOFM. 
    SXB_12A     YESNOFM. 
    SXB_12B     YESNOFM. 
    SXB_12C     YESNOFM. 
    SXB_12D     YESNOFM. 
    SXB_12F     YESNOFM. 
    SXB_12E     YESNOFM. 
    SXB_13A     YESNOFM. 
    SXB_13B     YESNOFM. 
    SXB_13C     YESNOFM. 
    SXB_13D     YESNOFM. 
    SXB_13F     YESNOFM. 
    SXB_13G     YESNOFM. 
    SXB_13E     YESNOFM. 
    PWBFOPT     YESNOFM. 
    PWB_01      SSM_FREQ.
    PWB_02      SSM_FREQ.
    PWB_03      SSM_FREQ.
    PWB_04      SSM_FREQ.
    PWB_05      SSM_FREQ.
    PWB_06      SSM_FREQ.
    PWB_07      SSM_FREQ.
    PWB_08      SSM_FREQ.
    PWB_09      SSM_FREQ.
    PWB_10      SSM_FREQ.
    PWB_11      SSM_FREQ.
    PWB_12      SSM_FREQ.
    PWB_13      SSM_FREQ.
    PWB_14      SSM_FREQ.
    PWB_15      SSM_FREQ.
    PWB_16      SSM_FREQ.
    PWB_17      SSM_FREQ.
    PWB_18      SSM_FREQ.
    PWB_19      SSM_FREQ.
    PWB_20      SSM_FREQ.
    PWB_21      SSM_FREQ.
    PWB_22      SSM_FREQ.
    PWB_23      SSM_FREQ.
    PWB_24      SSM_FREQ.
    PWB_25      SSM_FREQ.
    PWBDPWB     PWBBDPWB.
    SSAFOPT     YESNOFM. 
    SSA_01      FR3DFM.  
    SSA_02      MOSFM.   
    SSA_03      MOSFM.   
    SSA_04      MOSFM.   
    SSA_05      MOSFM.   
    SSA_06      MOSFM.   
    SSA_07      MOSFM.   
    SSA_08      MOSFM.   
    SSA_09      MOSFM.   
    SSA_10      MOSFM.   
    SSA_11      MOSFM.   
    SSA_12      MOSFM.   
    SSA_13      MOSFM.   
    SSA_14      MOSFM.   
    SSA_15      MOSFM.   
    SSA_16      MOSFM.   
    SSA_17      MOSFM.   
    SSA_18      MOSFM.   
    SSA_19      MOSFM.   
    SSA_20      MOSFM.   
    SSADTNG     SCORE2D. 
    SSADAFF     SCORE2D. 
    SSADSOC     SCORE2D. 
    SSADEMO     SCORE2D. 
    SSUFOPT     YESNOFM. 
    SSU_21A     YESNOFM. 
    SSU_21B     SSM_FREQ.
    SSU_22A     YESNOFM. 
    SSU_22B     SSM_FREQ.
    SSU_23A     YESNOFM. 
    SSU_23B     SSM_FREQ.
    SSU_24A     YESNOFM. 
    SSU_24B     SSM_FREQ.
    SPVFOPT     YESNOFM. 
    SPV_1       YESNOFM. 
    SPV_2       MHC_1J.  
    SPV_3       MHC_1J.  
    SPV_4       MHC_1J.  
    SPV_5       SPR_REL. 
    SPV_6       SPR6FM.  
    SPV_7       SPR_7F.  
    CMHFOPT     YESNOFM. 
    CMH_01K     YESNOFM. 
    CMH_01L     TIMES3D. 
    CMH_1MA     YESNOFM. 
    CMH_1MB     YESNOFM. 
    CMH_1MC     YESNOFM. 
    CMH_1MD     YESNOFM. 
    CMH_1ME     YESNOFM. 
    CMH_1MF     YESNOFM. 
    DISFOPT     YESNOFM. 
    DIS_10A     ALLTIMEF.
    DIS_10B     ALLTIMEF.
    DIS_10C     ALLTIMEF.
    DIS_10D     ALLTIMEF.
    DIS_10E     ALLTIMEF.
    DIS_10F     ALLTIMEF.
    DIS_10G     ALLTIMEF.
    DIS_10H     ALLTIMEF.
    DIS_10I     ALLTIMEF.
    DIS_10J     ALLTIMEF.
    DIS_10K     MHC_1G.  
    DIS_10L     MHCFRQ2F.
    DIS_10M     MHCFRQ2F.
    DIS_10N     MHC_1J.  
    DISDK6      DISBDK.  
    DISDDSX     DISB10DK.
    DISDCHR     MHCDCH.  
    DPSFOPT     YESNOFM. 
    DPS_02      YESNOFM. 
    DPS_03      MHCLNGTH.
    DPS_04      MHCNUM3F.
    DPS_05      YESNOFM. 
    DPS_06      YESNOFM. 
    DPS_07      MHC_WGHT.
    DPS_08A     HWT_FM.  
    DPS_08B     WHTFM.   
    DPS_09      YESNOFM. 
    DPS_10      MHCFRQ1F.
    DPS_11      YESNOFM. 
    DPS_12      YESNOFM. 
    DPS_13      YESNOFM. 
    DPS_14      WEEKNUM. 
    DPS_15      MONTHFM. 
    DPS_16      YESNOFM. 
    DPS_17      MHCLNGTH.
    DPS_18      MHCNUM3F.
    DPS_19      YESNOFM. 
    DPS_20      MHC_WGHT.
    DPS_21A     HWT_FM.  
    DPS_21B     WHTFM.   
    DPS_22      YESNOFM. 
    DPS_23      MHCFRQ1F.
    DPS_24      YESNOFM. 
    DPS_25      YESNOFM. 
    DPS_26      YESNOFM. 
    DPS_27      WEEKNUM. 
    DPS_28      MONTHFM. 
    DPSDSF      MHCDSF.  
    DPSDPP      DPS_DPP. 
    DPSDWK      WEEKNUM. 
    DPSDMT      MONTHFM. 
    SUIFOPT     YESNOFM. 
    SUI_1       YESNOFM. 
    SUI_2       YESNOFM. 
    SUI_3       YESNOFM. 
    SUI_4       YESNOFM. 
    SUI_5       YESNOFM. 
    SUI_6A      YESNOFM. 
    SUI_6B      YESNOFM. 
    SUI_6C      YESNOFM. 
    SUI_6D      YESNOFM. 
    SUI_6E      YESNOFM. 
    SUI_6G      YESNOFM. 
    SUI_6H      YESNOFM. 
    SUI_6F      YESNOFM. 
    SFRFOPT     YESNOFM. 
    SFR_03      SFRC3FM. 
    SFR_04      SFRC3FM. 
    SFR_05      SFRC3FM. 
    SFR_06      SFRC3FM. 
    SFR_07      SFRC3FM. 
    SFR_08      SFRC3FM. 
    SFR_09      SFRC3FM. 
    SFR_10      SFRC3FM. 
    SFR_11      SFRC3FM. 
    SFR_12      SFRC3FM. 
    SFR_13      YESNOFM. 
    SFR_14      YESNOFM. 
    SFR_15      YESNOFM. 
    SFR_16      YESNOFM. 
    SFR_17      YESNOFM. 
    SFR_18      YESNOFM. 
    SFR_19      YESNOFM. 
    SFR_20      SFR20FM. 
    SFR_21      SFR21FM. 
    SFR_22      SFR20FM. 
    SFR_23      SFR23FM. 
    SFR_24      SFR23FM. 
    SFR_25      SFR23FM. 
    SFR_26      SFR23FM. 
    SFR_27      SFR23FM. 
    SFR_28      SFR23FM. 
    SFR_29      SFR23FM. 
    SFR_30      SFR23FM. 
    SFR_31      SFR23FM. 
    SFR_32      SFR23FM. 
    SFR_33      SFR33FM. 
    SFR_34      SFR33FM. 
    SFR_35      SFR33FM. 
    SFR_36      SFR33FM. 
    SFRDPFS     SCORE3D. 
    SFRDSFS     SCORE3D. 
    SFRDPRF     SCORE3D. 
    SFRDMRF     SCORE3D. 
    SFRDGMH     SCORE3D. 
    SFRDVTS     SCORE3D. 
    SFRDBPS     SCORE3D. 
    SFRDGHP     SCORE3D. 
    SFRDPCS     SCORE2D. 
    SFRDMCS     SCORE2D. 
    ACCFOPT     YESNOFM. 
    ACC_10      YESNOFM. 
    ACC_11      YESNOFM. 
    ACC_12A     YESNOFM. 
    ACC_12B     YESNOFM. 
    ACC_12C     YESNOFM. 
    ACC_12D     YESNOFM. 
    ACC_12E     YESNOFM. 
    ACC_12F     YESNOFM. 
    ACC_12G     YESNOFM. 
    ACC_12H     YESNOFM. 
    ACC_12I     YESNOFM. 
    ACC_12J     YESNOFM. 
    ACC_12K     YESNOFM. 
    ACC_12L     YESNOFM. 
    ACC_12M     YESNOFM. 
    ACC_12N     YESNOFM. 
    ACC_20      YESNOFM. 
    ACC_21      YESNOFM. 
    ACC_22A     YESNOFM. 
    ACC_22B     YESNOFM. 
    ACC_22C     YESNOFM. 
    ACC_22D     YESNOFM. 
    ACC_22E     YESNOFM. 
    ACC_22F     YESNOFM. 
    ACC_22G     YESNOFM. 
    ACC_22H     YESNOFM. 
    ACC_22I     YESNOFM. 
    ACC_22J     YESNOFM. 
    ACC_22K     YESNOFM. 
    ACC_22L     YESNOFM. 
    ACC_22M     YESNOFM. 
    ACC_22N     YESNOFM. 
    ACC_22O     YESNOFM. 
    ACC_30      YESNOFM. 
    ACC_31      YESNOFM. 
    ACC_32A     YESNOFM. 
    ACC_32B     YESNOFM. 
    ACC_32C     YESNOFM. 
    ACC_32D     YESNOFM. 
    ACC_32E     YESNOFM. 
    ACC_32F     YESNOFM. 
    ACC_32G     YESNOFM. 
    ACC_32H     YESNOFM. 
    ACC_32I     YESNOFM. 
    ACC_32J     YESNOFM. 
    ACC_32K     YESNOFM. 
    ACC_32L     YESNOFM. 
    ACC_32M     YESNOFM. 
    ACC_32N     YESNOFM. 
    ACC_40      YESNOFM. 
    ACC_40A     YESNOFM. 
    ACC_40B     YESNOFM. 
    ACC_40C     YESNOFM. 
    ACC_40D     YESNOFM. 
    ACC_40E     YESNOFM. 
    ACC_40F     YESNOFM. 
    ACC_40G     YESNOFM. 
    ACC_41      YESNOFM. 
    ACC_42      YESNO.   
    ACC_43A     YESNOFM. 
    ACC_43B     YESNOFM. 
    ACC_43C     YESNOFM. 
    ACC_43D     YESNOFM. 
    ACC_43E     YESNOFM. 
    ACC_43F     YESNOFM. 
    ACC_43G     YESNOFM. 
    ACC_43H     YESNOFM. 
    ACC_43I     YESNOFM. 
    ACC_44      YESNO.   
    ACC_45A     YESNOFM. 
    ACC_45B     YESNOFM. 
    ACC_45C     YESNOFM. 
    ACC_45D     YESNOFM. 
    ACC_45E     YESNOFM. 
    ACC_45F     YESNOFM. 
    ACC_45G     YESNOFM. 
    ACC_45H     YESNOFM. 
    ACC_45I     YESNOFM. 
    ACC_46      YESNO.   
    ACC_47A     YESNOFM. 
    ACC_47B     YESNOFM. 
    ACC_47C     YESNOFM. 
    ACC_47D     YESNOFM. 
    ACC_47E     YESNOFM. 
    ACC_47F     YESNOFM. 
    ACC_47G     YESNOFM. 
    ACC_47H     YESNOFM. 
    ACC_47I     YESNOFM. 
    ACC_50A     YESNOFM. 
    ACC_50      YESNOFM. 
    ACC_51      YESNOFM. 
    ACC_52      YESNO.   
    ACC_53A     YESNOFM. 
    ACC_53B     YESNOFM. 
    ACC_53C     YESNOFM. 
    ACC_53D     YESNOFM. 
    ACC_53E     YESNOFM. 
    ACC_53F     YESNOFM. 
    ACC_53G     YESNOFM. 
    ACC_53H     YESNOFM. 
    ACC_53I     YESNOFM. 
    ACC_53J     YESNOFM. 
    ACC_53K     YESNOFM. 
    ACC_53L     YESNOFM. 
    ACC_53M     YESNOFM. 
    ACC_54      YESNO.   
    ACC_55A     YESNOFM. 
    ACC_55B     YESNOFM. 
    ACC_55C     YESNOFM. 
    ACC_55D     YESNOFM. 
    ACC_55E     YESNOFM. 
    ACC_55F     YESNOFM. 
    ACC_55G     YESNOFM. 
    ACC_55H     YESNOFM. 
    ACC_55I     YESNOFM. 
    ACC_55J     YESNOFM. 
    ACC_55K     YESNOFM. 
    ACC_55L     YESNOFM. 
    ACC_55M     YESNOFM. 
    ACC_60      YESNOFM. 
    ACC_61      YESNOFM. 
    ACC_62      YESNO.   
    ACC_63A     YESNOFM. 
    ACC_63B     YESNOFM. 
    ACC_63C     YESNOFM. 
    ACC_63D     YESNOFM. 
    ACC_63E     YESNOFM. 
    ACC_63F     YESNOFM. 
    ACC_63G     YESNOFM. 
    ACC_63H     YESNOFM. 
    ACC_63I     YESNOFM. 
    ACC_63J     YESNOFM. 
    ACC_63K     YESNOFM. 
    ACC_63L     YESNOFM. 
    ACC_63M     YESNOFM. 
    ACC_64      YESNO.   
    ACC_65A     YESNOFM. 
    ACC_65B     YESNOFM. 
    ACC_65C     YESNOFM. 
    ACC_65D     YESNOFM. 
    ACC_65E     YESNOFM. 
    ACC_65F     YESNOFM. 
    ACC_65G     YESNOFM. 
    ACC_65H     YESNOFM. 
    ACC_65I     YESNOFM. 
    ACC_65J     YESNOFM. 
    ACC_65K     YESNOFM. 
    ACC_65L     YESNOFM. 
    ACC_65M     YESNOFM. 
    ACC_66      YESNO.   
    ACC_67A     YESNOFM. 
    ACC_67B     YESNOFM. 
    ACC_67C     YESNOFM. 
    ACC_67D     YESNOFM. 
    ACC_67E     YESNOFM. 
    ACC_67F     YESNOFM. 
    ACC_67G     YESNOFM. 
    ACC_67H     YESNOFM. 
    ACC_67I     YESNOFM. 
    ACC_67J     YESNOFM. 
    ACC_67K     YESNOFM. 
    ACC_67L     YESNOFM. 
    ACC_67M     YESNOFM. 
    INSFOPT     YESNOFM. 
    INS_1       YESNOFM. 
    INS_1A      YESNOFM. 
    INS_1B      YESNOFM. 
    INS_1C      YESNOFM. 
    INS_2       YESNOFM. 
    INS_2A      YESNOFM. 
    INS_2B      YESNOFM. 
    INS_2C      YESNOFM. 
    INS_3       YESNOFM. 
    INS_3A      YESNOFM. 
    INS_3B      YESNOFM. 
    INS_3C      YESNOFM. 
    INS_4       YESNOFM. 
    INS_4A      YESNOFM. 
    INS_4B      YESNOFM. 
    INS_4C      YESNOFM. 
    SDC_1       SDC_1FM. 
    SDC_2       YESNOFM. 
    SDC_3       SDYEARFM.
    SDC_4A      YESNOFM. 
    SDC_4B      YESNOFM. 
    SDC_4C      YESNOFM. 
    SDC_4D      YESNOFM. 
    SDC_4E      YESNOFM. 
    SDC_4F      YESNOFM. 
    SDC_4G      YESNOFM. 
    SDC_4H      YESNOFM. 
    SDC_4I      YESNOFM. 
    SDC_4J      YESNOFM. 
    SDC_4K      YESNOFM. 
    SDC_4L      YESNOFM. 
    SDC_4M      YESNOFM. 
    SDC_4N      YESNOFM. 
    SDC_4T      YESNOFM. 
    SDC_4U      YESNOFM. 
    SDC_4V      YESNOFM. 
    SDC_4P      YESNOFM. 
    SDC_4Q      YESNOFM. 
    SDC_4R      YESNOFM. 
    SDC_4S      YESNOFM. 
    SDC_41      YESNOFM. 
    SDC_42A     YESNOFM. 
    SDC_42B     YESNOFM. 
    SDC_42C     YESNOFM. 
    SDC_43A     YESNOFM. 
    SDC_43B     YESNOFM. 
    SDC_43C     YESNOFM. 
    SDC_43D     YESNOFM. 
    SDC_43E     YESNOFM. 
    SDC_43F     YESNOFM. 
    SDC_43G     YESNOFM. 
    SDC_43H     YESNOFM. 
    SDC_43I     YESNOFM. 
    SDC_43J     YESNOFM. 
    SDC_43K     YESNOFM. 
    SDC_43M     YESNOFM. 
    SDC_5A      YESNOFM. 
    SDC_5B      YESNOFM. 
    SDC_5C      YESNOFM. 
    SDC_5D      YESNOFM. 
    SDC_5E      YESNOFM. 
    SDC_5F      YESNOFM. 
    SDC_5G      YESNOFM. 
    SDC_5H      YESNOFM. 
    SDC_5I      YESNOFM. 
    SDC_5J      YESNOFM. 
    SDC_5K      YESNOFM. 
    SDC_5L      YESNOFM. 
    SDC_5M      YESNOFM. 
    SDC_5N      YESNOFM. 
    SDC_5O      YESNOFM. 
    SDC_5P      YESNOFM. 
    SDC_5Q      YESNOFM. 
    SDC_5R      YESNOFM. 
    SDC_5T      YESNOFM. 
    SDC_5U      YESNOFM. 
    SDC_5V      YESNOFM. 
    SDC_5W      YESNOFM. 
    SDC_5S      YESNOFM. 
    SDC_5AA     YESNOFM. 
    SDC_5AB     YESNOFM. 
    SDC_5AC     YESNOFM. 
    SDC_5AD     YESNOFM. 
    SDC_5AE     YESNOFM. 
    SDC_5AF     YESNOFM. 
    SDC_5AG     YESNOFM. 
    SDC_5AH     YESNOFM. 
    SDC_5AI     YESNOFM. 
    SDC_5AJ     YESNOFM. 
    SDC_5AK     YESNOFM. 
    SDC_5AL     YESNOFM. 
    SDC_5AM     YESNOFM. 
    SDC_5AN     YESNOFM. 
    SDC_5AO     YESNOFM. 
    SDC_5AP     YESNOFM. 
    SDC_5AQ     YESNOFM. 
    SDC_5AR     YESNOFM. 
    SDC_5AT     YESNOFM. 
    SDC_5AU     YESNOFM. 
    SDC_5AV     YESNOFM. 
    SDC_5AW     YESNOFM. 
    SDC_5AS     YESNOFM. 
    SDC_6A      YESNOFM. 
    SDC_6B      YESNOFM. 
    SDC_6C      YESNOFM. 
    SDC_6D      YESNOFM. 
    SDC_6E      YESNOFM. 
    SDC_6F      YESNOFM. 
    SDC_6G      YESNOFM. 
    SDC_6H      YESNOFM. 
    SDC_6I      YESNOFM. 
    SDC_6J      YESNOFM. 
    SDC_6K      YESNOFM. 
    SDC_6L      YESNOFM. 
    SDC_6M      YESNOFM. 
    SDC_6N      YESNOFM. 
    SDC_6O      YESNOFM. 
    SDC_6P      YESNOFM. 
    SDC_6Q      YESNOFM. 
    SDC_6R      YESNOFM. 
    SDC_6T      YESNOFM. 
    SDC_6U      YESNOFM. 
    SDC_6V      YESNOFM. 
    SDC_6W      YESNOFM. 
    SDC_6S      YESNOFM. 
    SDC_7AA     SDC7AFM. 
    SDCCCB      SDC_CB.  
    SDCGCB      SDGCB7FM.
    SDCDAIM     AGE3DFM. 
    SDCFIMM     YESNOFM. 
    SDCDRES     AGE3DFM. 
    SDCDABT     SDC_ABO. 
    SDCDCGT     SDC_CG.  
    SDCDLNG     SDCDLNG. 
    SDCDFL1     SDCDLNG. 
    SDCDLHM     SDCDLNG. 
    EDU_1       EDUGRADE.
    EDU_2       YESNOFM. 
    EDU_3       YESNOFM. 
    EDU_4       EDUDEGRE.
    SDC_8       YESNOFM. 
    SDC_9       LBF_PFT. 
    EDUDH04     DVED3FM. 
    EDUDH10     EDU_10DR.
    EDUDR04     DVED3FM. 
    EDUDR10     EDU_10DR.
    LBS_01      LSC_1F.  
    LBS_02      YESNOFM. 
    LBS_03      YESNOFM. 
    LBS_11      YESNOFM. 
    LBS_31      LSC_31F. 
    LBS_42      HOUR3DFM.
    ETS_7       SMS_12F. 
    LBS_53      HOUR3DFM.
    LBSF32      YESNOFM. 
    LBSF33      YESNOFM. 
    LBSF34      YESNOFM. 
    LBSF35      YESNOFM. 
    LBSF35S     YESNOFM. 
    LBSF36      YESNOFM. 
    LBSDHPW     LSCDHPW. 
    LBSDPFT     LBF_PFT. 
    LBSDWSS     LSCDCWS. 
    LBSDING    $LBSDINFM.
    LBSDOCG    $LBSDOCFM.
    PAFFTH      YESNOFM. 
    PAF_01      YESNOFM. 
    PAF_02      YESNOFM. 
    PAF_03      YESNOFM. 
    PAF_04      YESNOFM. 
    PAF_05      YESNOFM. 
    PAF_06      YESNOFM. 
    PAF_07      YESNOFM. 
    PAF_08      YESNOFM. 
    PAFFACC     YESNOFM. 
    DHHDHSZ     PERS2D.  
    DHHDL12     PERS2D.  
    DHHDLE5     PERS2D.  
    DHHD611     PERS2D.  
    DHHDECF     DHCDECF. 
    DHHDLVG     DHCDLVG. 
    DHHDDWE     DHH_DWE. 
    DHH_OWN     YESNOFM. 
    DHH_BED     BED_NUM. 
    HMSFOPT     YESNOFM. 
    HMS_1       YESNOFM. 
    HMS_2       YESNOFM. 
    HMS_3       YESNOFM. 
    HMS_4       HMSC4FM. 
    HMS_5       YESNOFM. 
    HMS_6       YESNOFM. 
    INC_1A      YESNOFM. 
    INC_1B      YESNOFM. 
    INC_1C      YESNOFM. 
    INC_1D      YESNOFM. 
    INC_1E      YESNOFM. 
    INC_1F      YESNOFM. 
    INC_1G      YESNOFM. 
    INC_1H      YESNOFM. 
    INC_1I      YESNOFM. 
    INC_1J      YESNOFM. 
    INC_1K      YESNOFM. 
    INC_1L      YESNOFM. 
    INC_1M      YESNOFM. 
    INC_1N      YESNOFM. 
    INC_2       INC8_2F. 
    INC_3       DOLL6FM. 
    INC_3A      INC_3A.  
    INC_3B      INC_3B.  
    INC_3C      INC_3C.  
    INC_3D      INC_3D.  
    INC_3E      INC_3E.  
    INC_3F      INC_3F.  
    INC_3G      INC_3GFM.
    INC_4       DOLL6FM. 
    INC_4A      INC_3A.  
    INC_4B      INC_3B.  
    INC_4C      INC_3C.  
    INC_4D      INC_3D.  
    INC_4E      INC_3E.  
    INC_4F      INC_3F.  
    INC_4G      INC_3GFM.
    INCDHH      INCDHHFM.
    INCDPER     INCDHHFM.
    INCDADR     INCRATFM.
    INCDRCA     INCDECFM.
    INCDRPR     INCDECFM.
    INCDRRS     INCDECFM.
    FSCFTH      YESNOFM. 
    FSC_010     FSCD10FM.
    FSC_020     FSCDFM.  
    FSC_030     FSCDFM.  
    FSC_040     FSCDFM.  
    FSC_050     FSCDFM.  
    FSC_060     FSCDFM.  
    FSC_070     FSCDFM.  
    FSC_080     YESNOFM. 
    FSC_081     FSC81FM. 
    FSC_090     YESNOFM. 
    FSC_100     YESNOFM. 
    FSC_110     YESNOFM. 
    FSC_120     YESNOFM. 
    FSC_121     FSC81FM. 
    FSC_130     YESNOFM. 
    FSC_140     YESNOFM. 
    FSC_141     FSC81FM. 
    FSC_150     YESNOFM. 
    FSC_160     YESNOFM. 
    FSCDHFS     FSC_DHFS.
    FSCDHFS2    FSCDHFFM.
                       ;
