 format
    GEO_PRV     PROVFM.  
    GEODCMAA    GEOCMAF. 
    GEODPC     $GEO3DPMF.
    GEODHR4     HR4_12FM.
    GEODDHA     GEO_HAFM.
    GEODBCHA    GEODBCFM.
    GEODLHN     GEOLHIN. 
    GEODSAT     GEOSATFM.
    GEODPG11    GEO_PRG. 
    GEODUR      GEO_URFM.
    GEODUR2     GEO_DRFM.
    SAM_CP     $S_CP14FM.
    SAM_TYP     SAME_TYP.
    CASETYPE    CASETPFM.
    SAMDSHR     SAMDSHFM.
    SAMDLNK     YESNOFM. 
    ADM_STA     ADM_STA. 
    ADM_PRX     YESNOFM. 
    ADM_YOI     YEARXFM. 
    ADM_MOI     MONTHFM. 
    ADM_DOI     DAYFM.   
    ADM_N09     TELFM.   
    ADM_N10     YESNOFM. 
    ADM_N11     YESNOFM. 
    ADM_N12     ADM_LNG. 
    ADM_LHH     AM3_LP.  
    DHH_AGE     AGE3DFM. 
    DHH_YOB     YEARFM.  
    DHH_MOB     MONTHFM. 
    DHH_DOB     DAYFM.   
    DHH_SEX     DHC_SEX. 
    DHH_MS      DHC_MAR. 
    DHHDSAGE    AGE3DFM. 
    DHHDYKD     PERS2D.  
    DHHDOKD     PERS2D.  
    DHHDLE5     PERS2D.  
    DHHD611     PERS2D.  
    DHHDL12     PERS2D.  
    DHHDL18     PERS2D.  
    DHHDLVG     DHCDLVG. 
    DHHDECF     DHCDECF. 
    DHHDHSZ     PERS2D.  
    GEN_01      GOOD5FM. 
    GEN_02      GEN_2F.  
    GEN_02A2    GEN02AFM.
    GEN_02B     GOOD5FM. 
    GEN_07      STC_1F.  
    GEN_08      YESNOFM. 
    GEN_09      STC_1F.  
    GEN_10      GEN_10F. 
    GENDHDI     GHCDHDI. 
    GENDMHI     GHCDHDI. 
    GENGSWL     SCR_01FM.
    DOORG       YESNOFM. 
    ORG_1       YESNOFM. 
    ORG_2       ORG_2Q.  
    DOSLP       YESNOFM. 
    SLP_01      GEN_3F.  
    SLP_02      MOSFM.   
    SLP_03      MOSFM.   
    SLP_04      MOSFM.   
    DOCIH       YESNOFM. 
    CIH_1       YESNOFM. 
    CIH_2       CIH_2FM. 
    CIH_3       YESNOFM. 
    CIH_4       CIH_2FM. 
    CIH_5       YESNOFM. 
    CIH_6A      YESNOFM. 
    CIH_6I      YESNOFM. 
    CIH_6B      YESNOFM. 
    CIH_6J      YESNOFM. 
    CIH_6K      YESNOFM. 
    CIH_6G      YESNOFM. 
    CIH_6F      YESNOFM. 
    CIH_6E      YESNOFM. 
    CIH_6L      YESNOFM. 
    CIH_6M      YESNOFM. 
    CIH_6N      YESNOFM. 
    CIH_6H      YESNOFM. 
    CIH_7       YESNOFM. 
    CIH_8A      YESNOFM. 
    CIH_8B      YESNOFM. 
    CIH_8C      YESNOFM. 
    CIH_8J      YESNOFM. 
    CIH_8K      YESNOFM. 
    CIH_8G      YESNOFM. 
    CIH_8L      YESNOFM. 
    CIH_8H      YESNOFM. 
    CIH_8I      YESNOFM. 
    DOOH1       YESNOFM. 
    OH1_20      GOOD5FM. 
    OH1_21A     YESNOFM. 
    OH1_21B     YESNOFM. 
    OH1_21C     YESNOFM. 
    OH1_22      GAD_04FM.
    DOHCS       YESNOFM. 
    HCS_1       PAS12FM. 
    HCS_2       PAS12FM. 
    HCS_3       PAS12FM. 
    HCS_4       PAS12FM. 
    MAM_037     YESNOFM. 
    HWT_2       HWC_2FM. 
    HWT_2A      HWC_2A.  
    HWT_2B      HWC_2B.  
    HWT_2C      HWC_2C.  
    HWT_2D      HWC_2D.  
    HWT_2E      HWC_2E.  
    HWT_2F      HWC_2F.  
    HWT_3       HWT_FM.  
    HWT_N4      WHTFM.   
    HWT_4       HWS_1F.  
    HWTDHTM     HWT_METR.
    HWTDWTK     HWT_WTK. 
    HWTDBMI     HWTD_BMI.
    HWTDISW     HWTCDISW.
    HWTDCOL     HWTDDCOL.
    HWTDWHO     HWTDWHFM.
    CCC_031     YESNOFM. 
    CCC_035     YESNOFM. 
    CCC_036     YESNOFM. 
    CCC_041     YESNOFM. 
    CCC_051     YESNOFM. 
    CCC_061     YESNOFM. 
    CCC_071     YESNOFM. 
    CCC_072     YESNOFM. 
    CCC_073     YESNOFM. 
    CCC_073A    YESNOFM. 
    CCC_073B    YESNOFM. 
    CCC_081     YESNOFM. 
    CCC_091     YESNOFM. 
    CCC_101     YESNOFM. 
    CCC_102     AGE3DFM. 
    CCC_10A     YESNOFM. 
    CCC_10B     YESNOFM. 
    CCC_10C     CCC_10C. 
    CCC_105     YESNOFM. 
    CCC_106     YESNOFM. 
    CCC_121     YESNOFM. 
    CCC_131     YESNOFM. 
    CCC_31A     YESNOFM. 
    CCC_141     YESNOFM. 
    CCC_151     YESNOFM. 
    CCC_161     YESNOFM. 
    CCC_171     YESNOFM. 
    CCC_17A     CCC17AFM.
    CCC_173     YESNOFM. 
    CCC_181     YESNOFM. 
    CCC_251     YESNOFM. 
    CCC_261     YESNOFM. 
    CCC_280     YESNOFM. 
    CCC_290     YESNOFM. 
    CCCDDIA     CCCDIAFM.
    DODIA       YESNOFM. 
    DIA_01      YESNOFM. 
    DIA_02      TIMES3D. 
    DIA_03      DIAE03FM.
    DIA_04      TIMES3D. 
    DIA_05      YESNOFM. 
    DIA_06      YESNOFM. 
    DIA_07      DIAE07FM.
    DIA_08      FVC_1A.  
    DIA_N8B     TIMES3D. 
    DIA_N8C     TIMES3D. 
    DIA_N8D     TIMES3D. 
    DIA_N8E     TIMES3D. 
    DIA_09      FVC_1A.  
    DIA_N9B     TIMES3D. 
    DIA_N9C     TIMES3D. 
    DIA_N9D     TIMES3D. 
    DIA_N9E     TIMES3D. 
    DIA_10      YESNOFM. 
    DIA_11      YESNOFM. 
    DOHUI       YESNOFM. 
    HUI_01      YESNOFM. 
    HUI_02      YESNOFM. 
    HUI_03      YESNOFM. 
    HUI_04      YESNOFM. 
    HUI_05      YESNOFM. 
    HUI_06      YESNOFM. 
    HUI_07      YESNOFM. 
    HUI_07A     YESNOFM. 
    HUI_08      YESNOFM. 
    HUI_09      YESNOFM. 
    HUI_10      YESNOFM. 
    HUI_11      YESNOFM. 
    HUI_12      YESNOFM. 
    HUI_13      YESNOFM. 
    HUI_14      YESNOFM. 
    HUI_15      YESNOFM. 
    HUI_16      YESNOFM. 
    HUI_17      YESNOFM. 
    HUI_18      YESNOFM. 
    HUI_19      HSC_19F. 
    HUI_20      YESNOFM. 
    HUI_21      YESNOFM. 
    HUI_22      YESNOFM. 
    HUI_23      HSC_23F. 
    HUI_24      YESNOFM. 
    HUI_25      HSC_25F. 
    HUI_26      HSC_26F. 
    HUI_27      HSC_27F. 
    HUIDVIS     HUIDVIFM.
    HUIDHER     HUIDHEFM.
    HUIDSPE     HUIDSPFM.
    HUIDMOB     HUIDMOFM.
    HUIDDEX     HUIDEXFM.
    HUIDEMO     HUIDEMFM.
    HUIDCOG     HUIDCOFM.
    HUIDHSI     HUIDHSI. 
    HUP_01      YESNOFM. 
    HUP_02      HSC_29F. 
    HUP_03      HSC_30F. 
    HUPDPAD     HSCDPAD. 
    HCU_1AA     YESNOFM. 
    HCU_1BA     YESNOFM. 
    HCU_1BB     YESNOFM. 
    HCU_1BC     YESNOFM. 
    HCU_1BD     YESNOFM. 
    HCU_1BE     YESNOFM. 
    HCU_1A1     YESNOFM. 
    HCU_1A2     HCU1A2FM.
    HCU_1AC     ADM_LN2G.
    CHP_01      YESNOFM. 
    CHP_02      NIGHT3D. 
    CHP_03      YESNOFM. 
    CHP_04      TIMES3D. 
    CHP_05      HCC_CONT.
    CHP_06      YESNOFM. 
    CHP_07      TIMES2D. 
    CHP_08      YESNOFM. 
    CHP_09      TIMES3D. 
    CHP_10      HCC_CONT.
    CHP_11      YESNOFM. 
    CHP_12      TIMES3D. 
    CHP_13      HCC_CONT.
    CHP_14      YESNOFM. 
    CHP_15      TIMES3D. 
    CHPDMDC     CON3DFM. 
    DOCP2       YESNOFM. 
    CHP_16      YESNOFM. 
    CHP_17      TIMES3D. 
    CHP_18      YESNOFM. 
    CHP_19      TIMES3D. 
    CHP_20      YESNOFM. 
    CHP_21      TIMES3D. 
    CHP_22      YESNOFM. 
    CHP_23      TIMES3D. 
    CHP_24      YESNOFM. 
    CHP_25      TIMES3D. 
    DOUCN       YESNOFM. 
    UCN_010     YESNOFM. 
    UCN_020A    YESNOFM. 
    UCN_020B    YESNOFM. 
    UCN_020C    YESNOFM. 
    UCN_020D    YESNOFM. 
    UCN_020E    YESNOFM. 
    UCN_020F    YESNOFM. 
    UCN_020G    YESNOFM. 
    UCN_020H    YESNOFM. 
    UCN_020I    YESNOFM. 
    UCN_020J    YESNOFM. 
    UCN_030A    YESNOFM. 
    UCN_030B    YESNOFM. 
    UCN_030C    YESNOFM. 
    UCN_030D    YESNOFM. 
    UCN_030E    YESNOFM. 
    UCN_040A    YESNOFM. 
    UCN_040B    YESNOFM. 
    UCN_040C    YESNOFM. 
    UCN_040D    YESNOFM. 
    UCN_040E    YESNOFM. 
    UCN_040F    YESNOFM. 
    UCN_040G    YESNOFM. 
    DOHMC       YESNOFM. 
    HMC_09      YESNOFM. 
    HMC_10A     YESNOFM. 
    HMC_10B     YESNOFM. 
    HMC_10I     YESNOFM. 
    HMC_10C     YESNOFM. 
    HMC_10D     YESNOFM. 
    HMC_10E     YESNOFM. 
    HMC_10F     YESNOFM. 
    HMC_10G     YESNOFM. 
    HMC_10H     YESNOFM. 
    HMC_11      YESNOFM. 
    HMC_12A     YESNOFM. 
    HMC_12B     YESNOFM. 
    HMC_12G     YESNOFM. 
    HMC_12C     YESNOFM. 
    HMC_12D     YESNOFM. 
    HMC_12E     YESNOFM. 
    HMC_12F     YESNOFM. 
    HMC_13A     YESNOFM. 
    HMC_13B     YESNOFM. 
    HMC_13C     YESNOFM. 
    HMC_13D     YESNOFM. 
    HMC_13E     YESNOFM. 
    HMC_13F     YESNOFM. 
    HMC_13G     YESNOFM. 
    HMC_13H     YESNOFM. 
    HMC_13I     YESNOFM. 
    HMC_14      YESNOFM. 
    HMC_15A     YESNOFM. 
    HMC_15B     YESNOFM. 
    HMC_15C     YESNOFM. 
    HMC_15D     YESNOFM. 
    HMC_15E     YESNOFM. 
    HMC_15F     YESNOFM. 
    HMC_15G     YESNOFM. 
    HMC_15H     YESNOFM. 
    HMC_15I     YESNOFM. 
    HMC_15J     YESNOFM. 
    HMC_15K     YESNOFM. 
    HMC_15L     YESNOFM. 
    HMC_15N     YESNOFM. 
    HMC_15O     YESNOFM. 
    HMC_15M     YESNOFM. 
    HMC_16A     YESNOFM. 
    HMC_16B     YESNOFM. 
    HMC_16I     YESNOFM. 
    HMC_16C     YESNOFM. 
    HMC_16D     YESNOFM. 
    HMC_16E     YESNOFM. 
    HMC_16F     YESNOFM. 
    HMC_16G     YESNOFM. 
    HMC_16H     YESNOFM. 
    HMC_17A     YESNOFM. 
    HMC_17B     YESNOFM. 
    HMC_17C     YESNOFM. 
    HMC_17D     YESNOFM. 
    HMC_17E     YESNOFM. 
    HMCFRHC     YESNOFM. 
    DOPAS       YESNOFM. 
    PAS_11      YESNOFM. 
    PAS_12      PAS12FM. 
    PAS_13      SATQ3FM. 
    PAS_21A     YESNOFM. 
    PAS_21B     SAT_21BF.
    PAS_22      PAS12FM. 
    PAS_23      SATQ3FM. 
    PAS_31A     YESNOFM. 
    PAS_31B     SAT_31BF.
    PAS_32      PAS12FM. 
    PAS_33      SATQ3FM. 
    DOPSC       YESNOFM. 
    PSC_1       YESNOFM. 
    PSC_2       PAS12FM. 
    PSC_3       SATQ3FM. 
    RAC_1       SOMETIME.
    RAC_2A      SOMETIME.
    RAC_2B1     RAC2B1FM.
    RAC_2B2     RAC2B2FM.
    RAC_2C      SOMETIME.
    RAC_5       RAC_5FM. 
    RACDIMP     SOMETIME.
    RACDPAL     SOMETIME.
    DOADL       YESNOFM. 
    ADL_01      YESNOFM. 
    ADL_02      YESNOFM. 
    ADL_03      YESNOFM. 
    ADL_04      YESNOFM. 
    ADL_05      YESNOFM. 
    ADL_06      YESNOFM. 
    ADLF6R      YESNOFM. 
    FLU_160     YESNOFM. 
    FLU_162     FS52F.   
    FLU_164     MONTHFM. 
    FLU_165     INJ_4F.  
    FLU_66A     YESNOFM. 
    FLU_66B     YESNOFM. 
    FLU_66C     YESNOFM. 
    FLU_66D     YESNOFM. 
    FLU_66E     YESNOFM. 
    FLU_66F     YESNOFM. 
    FLU_66G     YESNOFM. 
    FLU_66H     YESNOFM. 
    FLU_66I     YESNOFM. 
    FLU_66J     YESNOFM. 
    FLU_66K     YESNOFM. 
    FLU_66L     YESNOFM. 
    FLU_66M     YESNOFM. 
    FLU_66O     YESNOFM. 
    FLU_66N     YESNOFM. 
    DOBPC       YESNOFM. 
    BPC_010     YESNOFM. 
    BPC_012     WH2_LAST.
    BPC_013     YESNOFM. 
    BPC_16A     YESNOFM. 
    BPC_16B     YESNOFM. 
    BPC_16C     YESNOFM. 
    BPC_16D     YESNOFM. 
    BPC_16E     YESNOFM. 
    BPC_16F     YESNOFM. 
    BPC_16G     YESNOFM. 
    BPC_16H     YESNOFM. 
    BPC_16I     YESNOFM. 
    BPC_16J     YESNOFM. 
    BPC_16K     YESNOFM. 
    BPC_16L     YESNOFM. 
    BPC_16N     YESNOFM. 
    BPC_16M     YESNOFM. 
    DOPAP       YESNOFM. 
    PAP_020     YESNOFM. 
    PAP_022     WHC_22F. 
    PAP_26A     YESNOFM. 
    PAP_26B     YESNOFM. 
    PAP_26C     YESNOFM. 
    PAP_26D     YESNOFM. 
    PAP_26E     YESNOFM. 
    PAP_26F     YESNOFM. 
    PAP_26G     YESNOFM. 
    PAP_26H     YESNOFM. 
    PAP_26I     YESNOFM. 
    PAP_26J     YESNOFM. 
    PAP_26K     YESNOFM. 
    PAP_26L     YESNOFM. 
    PAP_26M     YESNOFM. 
    PAP_26N     YESNOFM. 
    PAP_26P     YESNOFM. 
    PAP_26O     YESNOFM. 
    DOMAM       YESNOFM. 
    MAM_030     YESNOFM. 
    MAM_31A     YESNOFM. 
    MAM_31B     YESNOFM. 
    MAM_31C     YESNOFM. 
    MAM_31D     YESNOFM. 
    MAM_31E     YESNOFM. 
    MAM_31F     YESNOFM. 
    MAM_31G     YESNOFM. 
    MAM_31H     YESNOFM. 
    MAM_032     WH2_LAST.
    MAM_36A     YESNOFM. 
    MAM_36B     YESNOFM. 
    MAM_36C     YESNOFM. 
    MAM_36D     YESNOFM. 
    MAM_36E     YESNOFM. 
    MAM_36F     YESNOFM. 
    MAM_36G     YESNOFM. 
    MAM_36H     YESNOFM. 
    MAM_36I     YESNOFM. 
    MAM_36J     YESNOFM. 
    MAM_36K     YESNOFM. 
    MAM_36L     YESNOFM. 
    MAM_36N     YESNOFM. 
    MAM_36O     YESNOFM. 
    MAM_36M     YESNOFM. 
    MAM_038     YESNOFM. 
    DOPSA       YESNOFM. 
    PSA_170     YESNOFM. 
    PSA_172     PSACFM.  
    PSA_73A     YESNOFM. 
    PSA_73B     YESNOFM. 
    PSA_73C     YESNOFM. 
    PSA_73G     YESNOFM. 
    PSA_73D     YESNOFM. 
    PSA_73E     YESNOFM. 
    PSA_73F     YESNOFM. 
    PSA_174     YESNOFM. 
    PSA_175     PSACFM.  
    DOCCS       YESNOFM. 
    CCS_180     YESNOFM. 
    CCS_182     CCS182FM.
    CCS_83A     YESNOFM. 
    CCS_83B     YESNOFM. 
    CCS_83C     YESNOFM. 
    CCS_83G     YESNOFM. 
    CCS_83D     YESNOFM. 
    CCS_83E     YESNOFM. 
    CCS_83F     YESNOFM. 
    CCS_184     YESNOFM. 
    CCS_185     CCS182FM.
    CCS_86A     YESNOFM. 
    CCS_86B     YESNOFM. 
    CCS_86C     YESNOFM. 
    CCS_86G     YESNOFM. 
    CCS_86D     YESNOFM. 
    CCS_86E     YESNOFM. 
    CCS_86F     YESNOFM. 
    CCS_187     YESNOFM. 
    DOEYX       YESNOFM. 
    EYX_140     YESNOFM. 
    EYX_142     EYX142FM.
    EYX_46A     YESNOFM. 
    EYX_46B     YESNOFM. 
    EYX_46C     YESNOFM. 
    EYX_46D     YESNOFM. 
    EYX_46E     YESNOFM. 
    EYX_46F     YESNOFM. 
    EYX_46G     YESNOFM. 
    EYX_46H     YESNOFM. 
    EYX_46I     YESNOFM. 
    EYX_46J     YESNOFM. 
    EYX_46K     YESNOFM. 
    EYX_46L     YESNOFM. 
    EYX_46N     YESNOFM. 
    EYX_46M     YESNOFM. 
    DODEN       YESNOFM. 
    DEN_130     YESNOFM. 
    DEN_132     DV61FM.  
    DEN_36A     YESNOFM. 
    DEN_36B     YESNOFM. 
    DEN_36C     YESNOFM. 
    DEN_36D     YESNOFM. 
    DEN_36E     YESNOFM. 
    DEN_36F     YESNOFM. 
    DEN_36G     YESNOFM. 
    DEN_36H     YESNOFM. 
    DEN_36I     YESNOFM. 
    DEN_36J     YESNOFM. 
    DEN_36K     YESNOFM. 
    DEN_36L     YESNOFM. 
    DEN_36M     YESNOFM. 
    DEN_36O     YESNOFM. 
    DEN_36N     YESNOFM. 
    DOOH2       YESNOFM. 
    OH2_10      OH2C10FM.
    OH2_11      YESNOFM. 
    OH2_11A     YESNOFM. 
    OH2_11B     YESNOFM. 
    OH2_11C     YESNOFM. 
    OH2_12      YESNOFM. 
    OH2_13      YESNOFM. 
    OH2_20      YESNOFM. 
    OH2_21      YESNOFM. 
    OH2_22      YESNOFM. 
    OH2_23      GAD_04FM.
    OH2_24      GAD_04FM.
    OH2_25A     YESNOFM. 
    OH2_25B     YESNOFM. 
    OH2_25C     YESNOFM. 
    OH2_25D     YESNOFM. 
    OH2_25E     YESNOFM. 
    OH2_25F     YESNOFM. 
    OH2_25G     YESNOFM. 
    OH2_30      OH2C30FM.
    OH2FLIM     OH2SIMFM.
    OH2FOFP     OH2CDFM. 
    DOFDC       YESNOFM. 
    FDC_1A      FDC1AFM. 
    FDC_1B      FDC1AFM. 
    FDC_1C      FDC1AFM. 
    FDC_1D      FDC1AFM. 
    FDC_2A      FDC1AFM. 
    FDC_2B      FDC1AFM. 
    FDC_2C      FDC1AFM. 
    FDC_3A      FDC1AFM. 
    FDC_3B      FDC1AFM. 
    FDC_3C      FDC1AFM. 
    FDC_3D      FDC1AFM. 
    FDC_3E      FDC1AFM. 
    FDCFAVD     YESNOFM. 
    FDCFCAH     YESNOFM. 
    FDCFCHO     YESNOFM. 
    FVC_1A      FVC_1A.  
    FVC_1B      TIMES2D. 
    FVC_1C      TIMES2D. 
    FVC_1D      TIMES3D. 
    FVC_1E      TIMES3D. 
    FVC_2A      FVC_1A.  
    FVC_2B      TIMES2D. 
    FVC_2C      TIMES2D. 
    FVC_2D      TIMES3D. 
    FVC_2E      TIMES3D. 
    FVC_3A      FVC_1A.  
    FVC_3B      TIMES2D. 
    FVC_3C      TIMES2D. 
    FVC_3D      TIMES3D. 
    FVC_3E      TIMES3D. 
    FVC_4A      FVC_1A.  
    FVC_4B      TIMES2D. 
    FVC_4C      TIMES2D. 
    FVC_4D      TIMES3D. 
    FVC_4E      TIMES3D. 
    FVC_5A      FVC_1A.  
    FVC_5B      TIMES2D. 
    FVC_5C      TIMES2D. 
    FVC_5D      TIMES3D. 
    FVC_5E      TIMES3D. 
    FVC_6A      FVC_1A.  
    FVC_6B      SERV2FM. 
    FVC_6C      SERV2FM. 
    FVC_6D      SERV3FM. 
    FVC_6E      SERV3FM. 
    FVCDJUI     FVC_DC.  
    FVCDFRU     FVC_DC.  
    FVCDSAL     FVC_DC.  
    FVCDPOT     FVC_DC.  
    FVCDCAR     FVC_DC.  
    FVCDVEG     FVC_PO.  
    FVCDTOT     FVC_DC.  
    FVCGTOT     FVC_RDA. 
    PAC_1A      YESNOFM. 
    PAC_1B      YESNOFM. 
    PAC_1C      YESNOFM. 
    PAC_1D      YESNOFM. 
    PAC_1E      YESNOFM. 
    PAC_1F      YESNOFM. 
    PAC_1G      YESNOFM. 
    PAC_1H      YESNOFM. 
    PAC_1I      YESNOFM. 
    PAC_1J      YESNOFM. 
    PAC_1K      YESNOFM. 
    PAC_1L      YESNOFM. 
    PAC_1M      YESNOFM. 
    PAC_1N      YESNOFM. 
    PAC_1O      YESNOFM. 
    PAC_1P      YESNOFM. 
    PAC_1Q      YESNOFM. 
    PAC_1R      YESNOFM. 
    PAC_1S      YESNOFM. 
    PAC_1T      YESNOFM. 
    PAC_1Z      YESNOFM. 
    PAC_1U      YESNOFM. 
    PAC_1V      YESNOFM. 
    PAC_1W      YESNOFM. 
    PAC_1X      YESNOFM. 
    PAC_2A      TIMES3D. 
    PAC_3A      PAC_TIME.
    PAC_2B      TIMES3D. 
    PAC_3B      PAC_TIME.
    PAC_2C      TIMES3D. 
    PAC_3C      PAC_TIME.
    PAC_2D      TIMES3D. 
    PAC_3D      PAC_TIME.
    PAC_2E      TIMES3D. 
    PAC_3E      PAC_TIME.
    PAC_2F      TIMES3D. 
    PAC_3F      PAC_TIME.
    PAC_2G      TIMES3D. 
    PAC_3G      PAC_TIME.
    PAC_2H      TIMES3D. 
    PAC_3H      PAC_TIME.
    PAC_2I      TIMES3D. 
    PAC_3I      PAC_TIME.
    PAC_2J      TIMES3D. 
    PAC_3J      PAC_TIME.
    PAC_2K      TIMES3D. 
    PAC_3K      PAC_TIME.
    PAC_2L      TIMES3D. 
    PAC_3L      PAC_TIME.
    PAC_2M      TIMES3D. 
    PAC_3M      PAC_TIME.
    PAC_2N      TIMES3D. 
    PAC_3N      PAC_TIME.
    PAC_2O      TIMES3D. 
    PAC_3O      PAC_TIME.
    PAC_2P      TIMES3D. 
    PAC_3P      PAC_TIME.
    PAC_2Q      TIMES3D. 
    PAC_3Q      PAC_TIME.
    PAC_2R      TIMES3D. 
    PAC_3R      PAC_TIME.
    PAC_2S      TIMES3D. 
    PAC_3S      PAC_TIME.
    PAC_2T      TIMES3D. 
    PAC_3T      PAC_TIME.
    PAC_2Z      TIMES3D. 
    PAC_3Z      PAC_TIME.
    PAC_2U      TIMES3D. 
    PAC_3U      PAC_TIME.
    PAC_2W      TIMES3D. 
    PAC_3W      PAC_TIME.
    PAC_2X      TIMES3D. 
    PAC_3X      PAC_TIME.
    PAC_7       PACF_7FM.
    PAC_7A      TIMES3D. 
    PAC_7B      PAC_TIME.
    PAC_8       PACF_7FM.
    PAC_8A      TIMES3D. 
    PAC_8B      PAC_TIME.
    PACDEE      PACDEE.  
    PACFLEI     YESNOFM. 
    PACDFM      PACDFM.  
    PACDFR      PACDFR.  
    PACFD       YESNOFM. 
    PACDPAI     PACDPAI. 
    PACDLTI     PACDPAI. 
    PACDTLE     PACDTLFM.
    PACFLTI     YESNOFM. 
    DOSCP       YESNOFM. 
    SCP_01      SCP_01FM.
    SCP_02      YESNOFM. 
    SCP_03      YESNOFM. 
    SCP_04      YESNOFM. 
    SCPDSTG     SCHCDSTG.
    DOSAC       YESNOFM. 
    SAC_1       HOUR2DFM.
    SAC_2       HOUR2DFM.
    SAC_3       HOUR2DFM.
    SAC_4       HOUR2DFM.
    SACDTOT     SAC_NUM. 
    SACDTER     SAC_NUM. 
    DOUPE       YESNOFM. 
    UPE_01A     YESNOFM. 
    UPE_01      PAC_5F.  
    UPE_02      YESNOFM. 
    UPE_02A     PAC_5F.  
    UPE_02B     PAC_5F.  
    UPE_02C     PAC_5F.  
    UPE_02D     PAC_5F.  
    UPE_03A     UPEC3AFM.
    UPE_03B     UPEC3AFM.
    UPE_04A     PAC_5F.  
    UPE_05A     PAC_5F.  
    UPE_05B     PAC_5F.  
    UPE_06      YESNOFM. 
    UPE_06A     PAC_5F.  
    UPE_06B     PAC_5F.  
    UPE_06C     PAC_5F.  
    UPE_07      YESNOFM. 
    UPE_07A     PAC_5F.  
    UPEFILS     YESNOFM. 
    UPEFSKB     YESNOFM. 
    UPEFSNB     YESNOFM. 
    DOSSB       YESNOFM. 
    SSB_01      YESNOFM. 
    SSB_02      YESNOFM. 
    SSB_03      YESNOFM. 
    SSB_06      SSBE06FM.
    SSB_07      SSBE07FM.
    SSB_08      SSBE07FM.
    SSB_09A     SSBE07FM.
    SSB_09B     SSBE07FM.
    SSB_10      SSBE10FM.
    SSB_11      SSBE07FM.
    SSB_12      SSBE10FM.
    SSB_13      YESNOFM. 
    SSB_14      YESNOFM. 
    SSB_15      MELANOFM.
    DOINJ       YESNOFM. 
    REP_1A      YESNOFM. 
    REP_2       YESNOFM. 
    REP_3       RPC03FM. 
    REP_3A      YESNOFM. 
    REP_4       YESNOFM. 
    REP_5A      YESNOFM. 
    REP_5B      YESNOFM. 
    REP_5C      YESNOFM. 
    REP_5D      YESNOFM. 
    REP_5F      YESNOFM. 
    REP_5G      YESNOFM. 
    REP_5H      YESNOFM. 
    REP_5I      YESNOFM. 
    INJ_01      YESNOFM. 
    INJ_02      TIMES2D. 
    INJ_03      MONTHFM. 
    INJ_04      INJ_4F.  
    INJ_05      IJC03F.  
    INJ_06      IJC04F.  
    INJ_07      IJC_4A.  
    INJ_08      IJC05F.  
    INJ_09      INJQ09FM.
    INW_01      YESNOFM. 
    INWF02      YESNOFM. 
    INWF03      YESNOFM. 
    INWCSIC    $LBSS_CFM.
    INWCSOC    $LBSS_CFM.
    INWF04      YESNOFM. 
    INWDOCG    $LBSDOCFM.
    INWDING    $LBSDINFM.
    INJ_10      YESNOFM. 
    INJ_11A     INJ11_FM.
    INJ_12      IJC_10B. 
    INJ_12A     INJ12AFM.
    INJ_13      YESNOFM. 
    INJ_14A     YESNOFM. 
    INJ_14B     YESNOFM. 
    INJ_14C     YESNOFM. 
    INJ_14L     YESNOFM. 
    INJ_14M     YESNOFM. 
    INJ_14F     YESNOFM. 
    INJ_14N     YESNOFM. 
    INJ_14O     YESNOFM. 
    INJ_14K     YESNOFM. 
    INJ_15      YESNOFM. 
    INJ_15A     YESNOFM. 
    INJ_16      YESNOFM. 
    INJ_17      IJC_NUM. 
    INJDTBS     INJ_TBS. 
    INJDCAU     INJ_CAU. 
    INJDCBP     IJCD2FM. 
    INJDSTT     INJ_STT. 
    DOSWL       YESNOFM. 
    SWL_02      SCR_01FM.
    SWL_03      SCR_01FM.
    SWL_04      SCR_01FM.
    SWL_05      SCR_01FM.
    SWL_06      SCR_01FM.
    SWL_07      SCR_01FM.
    SWL_08      SCR_01FM.
    SWL_09      SCR_01FM.
    SWL_10      SCR_01FM.
    DOSTS       YESNOFM. 
    STS_1       GOOD5FM. 
    STS_2       GOOD5FM. 
    STS_3       STR_3FM. 
    SMK_01A     YESNOFM. 
    SMK_01B     YESNOFM. 
    SMK_01C     AGE3DFM. 
    SMK_202     SMC_2F.  
    SMK_203     AGE3DFM. 
    SMK_204     CIG_NUM. 
    SMK_05B     CIG_NUM. 
    SMK_05C     DAY2DFM. 
    SMK_05D     YESNOFM. 
    SMK_06A     SMKCFM.  
    SMK_06B     MONTHFM. 
    SMK_06C     YEAR3NUM.
    SMK_207     AGE3DFM. 
    SMK_208     CIG_NUM. 
    SMK_09A     SMKCFM.  
    SMK_09B     MONTHFM. 
    SMK_09C     YEAR3NUM.
    SMK_10      YESNOFM. 
    SMK_10A     SMKCFM.  
    SMK_10B     MONTHFM. 
    SMK_10C     YEAR3NUM.
    SMKDSTY     SMCDTYP. 
    SMKDSTP     YEAR3NUM.
    SMKDYCS     YEAR3NUM.
    DOSCH       YESNOFM. 
    SCH_1       YESNOFM. 
    SCH_2       YESNOFM. 
    SCH_3       YESNOFM. 
    SCH_4       TIMES2D. 
    SCHDSTG     SCHCDSTG.
    DOSCA       YESNOFM. 
    SCA_10      YESNOFM. 
    SCA_10A     SCA_FM.  
    SCA_11      SCA_FM.  
    SCA_11A     SCA_FM.  
    SCA_12      YESNOFM. 
    SCA_12A     SCA_FM.  
    SCA_50      YESNOFM. 
    SCA_60      YESNOFM. 
    SCA_61      YESNOFM. 
    SCA_62      YESNOFM. 
    SCADQUI     SCA_QUI. 
    DOSPC       YESNOFM. 
    SPC_10      YESNOFM. 
    SPC_11      YESNOFM. 
    SPC_12      YESNOFM. 
    SPC_13      YESNOFM. 
    SPC_14A     YESNOFM. 
    SPC_14B     YESNOFM. 
    SPC_14C     YESNOFM. 
    SPC_14D     YESNOFM. 
    SPC_14E     YESNOFM. 
    SPC_14F     YESNOFM. 
    SPC_14G     YESNOFM. 
    SPC_20      YESNOFM. 
    SPC_21      YESNOFM. 
    SPC_22      YESNOFM. 
    DOYSM       YESNOFM. 
    YSM_1       SMK_300F.
    YSM_2       YESNOFM. 
    YSM_3       YESNOFM. 
    YSM_4       YESNOFM. 
    YSM_5       YESNOFM. 
    ETS_10      YESNOFM. 
    ETS_11      PERS2D.  
    ETS_20      YESNOFM. 
    ETS_20B     YESNOFM. 
    ETS_35      YESNOFM. 
    ETS_36      YESNOFM. 
    ETS_37A     YESNOFM. 
    ETS_37B     YESNOFM. 
    ETS_37C     YESNOFM. 
    ETS_37D     YESNOFM. 
    DOTAL       YESNOFM. 
    TAL_1       YESNOFM. 
    TAL_2       YESNOFM. 
    TAL_3       YESNOFM. 
    TAL_4       YESNOFM. 
    ALC_1       YESNOFM. 
    ALC_2       ALC6_2F. 
    ALC_3       ALC_3F.  
    ALCDTTM     ALCDTTFM.
    DOALW       YESNOFM. 
    ALW_1       YESNOFM. 
    ALW_2A1     ALC_NUM. 
    ALW_2A2     ALC_NUM. 
    ALW_2A3     ALC_NUM. 
    ALW_2A4     ALC_NUM. 
    ALW_2A5     ALC_NUM. 
    ALW_2A6     ALC_NUM. 
    ALW_2A7     ALC_NUM. 
    ALWDWKY     ALWDWKFM.
    ALWDDLY     ALWDDLFM.
    DODRV       YESNOFM. 
    DRV_01A     YESNOFM. 
    DRV_01B     YESNOFM. 
    DRV_02      PAC_5F.  
    DRV_03A     GAD_04FM.
    DRV_03B     GAD_04FM.
    DRV_04      GAD_04FM.
    DRV_05      DRVC05FM.
    DRV_06      DRVC06FM.
    DRV_07      YESNOFM. 
    DRV_07A     TIMES2D. 
    DRV_08A     DRV8AFM. 
    DRV_08B     DRV8BFM. 
    DRV_09      DRV09FM. 
    DRV_10      YESNOFM. 
    DRV_10A     TIMES2D. 
    DRV_11A     YESNOFM. 
    DRV_11B     YESNOFM. 
    DRV_12      PAC_5F.  
    DRV_13      YESNOFM. 
    DRV_13A     TIMES2D. 
    DRV_14      YESNOFM. 
    DRV_14A     TIMES2D. 
    DRVFSBU     DRVCDSBU.
    DOALD       YESNOFM. 
    ALD_01      YESNOFM. 
    ALD_02      AD_TIMES.
    ALD_03      YESNOFM. 
    ALD_04      YESNOFM. 
    ALD_05      YESNOFM. 
    ALD_06      YESNOFM. 
    ALD_07      YESNOFM. 
    ALD_08      AD_TIMES.
    ALD_09      YESNOFM. 
    ALD_10      YESNOFM. 
    ALD_11      YESNOFM. 
    ALD_12      YESNOFM. 
    ALD_13      YESNOFM. 
    ALD_14      YESNOFM. 
    ALD_15A     ALD_UOA. 
    ALD_5B1     DEPINTER.
    ALD_5B2     MIA_272F.
    ALD_15C     ALD_UOA. 
    ALD_15D     ALD_UOA. 
    ALDDSF      AD_DSF.  
    ALDDPP      AD_DPP.  
    ALDDINT     INTFFM.  
    ALDFINT     YESNOFM. 
    DOMEX       YESNOFM. 
    MEX_01      YESNOFM. 
    MEX_01A     YEARFM.  
    MEX_02      YESNOFM. 
    MEX_03      YESNOFM. 
    MEX_04      MEXE4FM. 
    MEX_05      YESNOFM. 
    MEX_06      MEX_08FM.
    MEX_06A     YESNOFM. 
    MEX_06B     MEXE07FM.
    MEX_08A     MEX_08FM.
    MEX_08B     MEXE8FM. 
    MEX_09      YESNOFM. 
    MEX_09B     MEX09BFM.
    MEX_10      MEXE0FM. 
    MEXDEBF2    MEXBF2FM.
    MEXFEB6     YESNOFM. 
    DOMXA       YESNOFM. 
    MXA_01      YESNOFM. 
    MXA_02      ALC6_2F. 
    MXA_03      YESNOFM. 
    MXA_04      ALC6_2F. 
    DOMXS       YESNOFM. 
    MXS_01      SMC_2F.  
    MXS_02      CIG_NUM. 
    MXS_03      CIG_NUM. 
    MXS_04      SMC_2F.  
    MXS_05      CIG_NUM. 
    MXS_06      CIG_NUM. 
    MXS_07      YESNOFM. 
    DOIDG       YESNOFM. 
    IDG_01      IDG4_FM. 
    IDG_02      YESNOFM. 
    IDG_03      IDG3_2FM.
    IDG_04      IDG4_FM. 
    IDG_05      YESNOFM. 
    IDG_06      IDG3_2FM.
    IDG_07      IDG4_FM. 
    IDG_08      YESNOFM. 
    IDG_09      IDG3_2FM.
    IDG_10      IDG4_FM. 
    IDG_11      YESNOFM. 
    IDG_12      IDG3_2FM.
    IDG_13      IDG4_FM. 
    IDG_14      YESNOFM. 
    IDG_15      IDG3_2FM.
    IDG_16      IDG4_FM. 
    IDG_17      YESNOFM. 
    IDG_18      IDG3_2FM.
    IDG_19      IDG4_FM. 
    IDG_20      YESNOFM. 
    IDG_21      IDG3_2FM.
    IDG_22      IDG4_FM. 
    IDG_23      YESNOFM. 
    IDG_24      IDG3_2FM.
    IDG_25A     YESNOFM. 
    IDG_25B     YESNOFM. 
    IDG_25C     YESNOFM. 
    IDG_25D     YESNOFM. 
    IDG_25E     YESNOFM. 
    IDG_25F     YESNOFM. 
    IDG_25G     YESNOFM. 
    IDG_25H     YESNOFM. 
    IDG_26A     ALD_UOA. 
    IDG_6B1     DEPINTER.
    IDG_6B2     MIA_272F.
    IDG_26C     ALD_UOA. 
    IDG_26D     ALD_UOA. 
    IDGFLCA     YESNOFM. 
    IDGFLCM     YESNOFM. 
    IDGFYCM     YESNOFM. 
    IDGFLCO     YESNOFM. 
    IDGFLAM     YESNOFM. 
    IDGFLEX     YESNOFM. 
    IDGFLHA     YESNOFM. 
    IDGFLGL     YESNOFM. 
    IDGFLHE     YESNOFM. 
    IDGFLST     YESNOFM. 
    IDGFLA      YESNOFM. 
    IDGFLAC     YESNOFM. 
    IDGFYA      YESNOFM. 
    IDGFYAC     YESNOFM. 
    IDGDINT     INTFFM.  
    IDGFINT     YESNOFM. 
    DOCPG       YESNOFM. 
    CPG_01A     DAILYFM. 
    CPG_01B     DAILYFM. 
    CPG_01C     DAILYFM. 
    CPG_01D     DAILYFM. 
    CPG_01E     DAILYFM. 
    CPG_01F     DAILYFM. 
    CPG_01G     DAILYFM. 
    CPG_01H     DAILYFM. 
    CPG_01I     DAILYFM. 
    CPG_01J     DAILYFM. 
    CPG_01K     DAILYFM. 
    CPG_01L     DAILYFM. 
    CPG_01M     DAILYFM. 
    CPG_01N     CPG01NFM.
    CPG_02      CPG_02FM.
    CPG_03      NEVER_1D.
    CPG_04      NEVER_1D.
    CPG_05      NEVER_1D.
    CPG_06      NEVER_1D.
    CPG_07      NEVER_1D.
    CPG_08      NEVER_1D.
    CPG_09      NEVER_1D.
    CPG_10      NEVER_1D.
    CPG_11      NEVER_1D.
    CPG_12      NEVER_1D.
    CPG_13      NEVER_1D.
    CPG_14      NEVER_1D.
    CPG_15      NEVER_1D.
    CPG_16      NEVER_1D.
    CPG_17      YESNOFM. 
    CPG_18      YESNOFM. 
    CPG_19A     ALD_UOA. 
    CPG_9B1     DEPINTER.
    CPG_9B2     MIA_272F.
    CPG_19C     ALD_UOA. 
    CPG_19D     ALD_UOA. 
    CPGFGAM     YESNOFM. 
    CPGDSEV     CPGBDSEM.
    CPGDTYP     CPGBDTYP.
    CPGDACT     CPGBDACT.
    CPGDINT     INTFFM.  
    CPGFINT     YESNOFM. 
    DOSXB       YESNOFM. 
    SXB_1       YESNOFM. 
    SXB_2       AGE3DFM. 
    SXB_3       YESNOFM. 
    SXB_4       SHS_4F.  
    SXB_07      YESNOFM. 
    SXB_7A      YESNOFM. 
    SXB_09      AGREEFM. 
    SXB_10      SXB102FM.
    SXB_11      YESNOFM. 
    SXB_12A     YESNOFM. 
    SXB_12B     YESNOFM. 
    SXB_12C     YESNOFM. 
    SXB_12D     YESNOFM. 
    SXB_12F     YESNOFM. 
    SXB_12E     YESNOFM. 
    SXB_13A     YESNOFM. 
    SXB_13B     YESNOFM. 
    SXB_13C     YESNOFM. 
    SXB_13D     YESNOFM. 
    SXB_13F     YESNOFM. 
    SXB_13G     YESNOFM. 
    SXB_13E     YESNOFM. 
    DOSPS       YESNOFM. 
    SPS_01      XPAD01FM.
    SPS_02      XPAD01FM.
    SPS_03      XPAD01FM.
    SPS_04      XPAD01FM.
    SPS_05      XPAD01FM.
    SPS_06      XPAD01FM.
    SPS_07      XPAD01FM.
    SPS_08      XPAD01FM.
    SPS_09      XPAD01FM.
    SPS_10      XPAD01FM.
    SPSDCON     SPSCONFM.
    SPSDATT     SPSATTFM.
    SPSDGUI     SPSGUIFM.
    SPSDALL     SPSALLFM.
    SPSDINT     SPSINTFM.
    SPSDWOR     SPSWORFM.
    DOCMH       YESNOFM. 
    CMH_01K     YESNOFM. 
    CMH_01L     TIMES3D. 
    CMH_1MA     YESNOFM. 
    CMH_1MB     YESNOFM. 
    CMH_1MC     YESNOFM. 
    CMH_1MD     YESNOFM. 
    CMH_1ME     YESNOFM. 
    CMH_1MF     YESNOFM. 
    DOMDB       YESNOFM. 
    MDB_1       OFTEN2FM.
    MDB_2       OFTEN2FM.
    MDB_3       OFTEN2FM.
    MDB_4       OFTEN2FM.
    MDB_5       OFTEN2FM.
    MDB_6       OFTEN2FM.
    MDB_7       OFTEN2FM.
    MDB_8       OFTEN2FM.
    MDB_9       OFTEN2FM.
    MDB_10      OFTEN2FM.
    MDB_11      MDB_11F. 
    MDBDPOS     MDB_POS. 
    MDBDNEG     MDB_NEG. 
    MDBDBA1     MDB_1BA. 
    MDBDBA2     MDB_2BA. 
    DODIS       YESNOFM. 
    DIS_10A     ALLTIMEF.
    DIS_10B     ALLTIMEF.
    DIS_10C     ALLTIMEF.
    DIS_10D     ALLTIMEF.
    DIS_10E     ALLTIMEF.
    DIS_10F     ALLTIMEF.
    DIS_10G     ALLTIMEF.
    DIS_10H     ALLTIMEF.
    DIS_10I     ALLTIMEF.
    DIS_10J     ALLTIMEF.
    DIS_10K     MHC_1G.  
    DIS_10L     MHCFRQ2F.
    DIS_10M     MHCFRQ2F.
    DIS_10N     MHC_1J.  
    DISDK6      DISBDK.  
    DISDCHR     MHCDCH.  
    DISDDSX     DISB10DK.
    DODEP       YESNOFM. 
    DPS_02      YESNOFM. 
    DPS_03      MHCLNGTH.
    DPS_04      MHCNUM3F.
    DPS_05      YESNOFM. 
    DPS_06      YESNOFM. 
    DPS_07      MHC_WGHT.
    DPS_08A     HWT_FM.  
    DPS_08B     WHTFM.   
    DPS_09      YESNOFM. 
    DPS_10      MHCFRQ1F.
    DPS_11      YESNOFM. 
    DPS_12      YESNOFM. 
    DPS_13      YESNOFM. 
    DPS_14      WEEKNUM. 
    DPS_15      MONTHFM. 
    DPS_16      YESNOFM. 
    DPS_17      MHCLNGTH.
    DPS_18      MHCNUM3F.
    DPS_19      YESNOFM. 
    DPS_20      MHC_WGHT.
    DPS_21A     HWT_FM.  
    DPS_21B     WHTFM.   
    DPS_22      YESNOFM. 
    DPS_23      MHCFRQ1F.
    DPS_24      YESNOFM. 
    DPS_25      YESNOFM. 
    DPS_26      YESNOFM. 
    DPS_27      WEEKNUM. 
    DPS_28      MONTHFM. 
    DPSDSF      MHCDSF.  
    DPSDPP      DPS_DPP. 
    DPSDWK      WEEKNUM. 
    DPSDMT      MONTHFM. 
    DOSUI       YESNOFM. 
    SUI_1       YESNOFM. 
    SUI_2       YESNOFM. 
    SUI_3       YESNOFM. 
    SUI_4       YESNOFM. 
    SUI_5       YESNOFM. 
    SUI_6A      YESNOFM. 
    SUI_6B      YESNOFM. 
    SUI_6C      YESNOFM. 
    SUI_6D      YESNOFM. 
    SUI_6E      YESNOFM. 
    SUI_6G      YESNOFM. 
    SUI_6H      YESNOFM. 
    SUI_6F      YESNOFM. 
    DOSFR       YESNOFM. 
    SFR_03      SFRC3FM. 
    SFR_04      SFRC3FM. 
    SFR_05      SFRC3FM. 
    SFR_06      SFRC3FM. 
    SFR_07      SFRC3FM. 
    SFR_08      SFRC3FM. 
    SFR_09      SFRC3FM. 
    SFR_10      SFRC3FM. 
    SFR_11      SFRC3FM. 
    SFR_12      SFRC3FM. 
    SFR_13      YESNOFM. 
    SFR_14      YESNOFM. 
    SFR_15      YESNOFM. 
    SFR_16      YESNOFM. 
    SFR_17      YESNOFM. 
    SFR_18      YESNOFM. 
    SFR_19      YESNOFM. 
    SFR_20      SFR20FM. 
    SFR_21      SFR21FM. 
    SFR_22      SFR20FM. 
    SFR_23      SFR23FM. 
    SFR_24      SFR23FM. 
    SFR_25      SFR23FM. 
    SFR_26      SFR23FM. 
    SFR_27      SFR23FM. 
    SFR_28      SFR23FM. 
    SFR_29      SFR23FM. 
    SFR_30      SFR23FM. 
    SFR_31      SFR23FM. 
    SFR_32      SFR23FM. 
    SFR_33      SFR33FM. 
    SFR_34      SFR33FM. 
    SFR_35      SFR33FM. 
    SFR_36      SFR33FM. 
    SFRDPFS     SCORE3D. 
    SFRDSFS     SCORE3D. 
    SFRDPRF     SCORE3D. 
    SFRDMRF     SCORE3D. 
    SFRDGMH     SCORE3D. 
    SFRDVTS     SCORE3D. 
    SFRDBPS     SCORE3D. 
    SFRDGHP     SCORE3D. 
    SFRDPCS     SCORE2D. 
    SFRDMCS     SCORE2D. 
    DOACC       YESNOFM. 
    ACC_10      YESNOFM. 
    ACC_11      YESNOFM. 
    ACC_12A     YESNOFM. 
    ACC_12B     YESNOFM. 
    ACC_12C     YESNOFM. 
    ACC_12D     YESNOFM. 
    ACC_12E     YESNOFM. 
    ACC_12F     YESNOFM. 
    ACC_12G     YESNOFM. 
    ACC_12H     YESNOFM. 
    ACC_12I     YESNOFM. 
    ACC_12J     YESNOFM. 
    ACC_12K     YESNOFM. 
    ACC_12L     YESNOFM. 
    ACC_12M     YESNOFM. 
    ACC_12N     YESNOFM. 
    ACC_20      YESNOFM. 
    ACC_21      YESNOFM. 
    ACC_22A     YESNOFM. 
    ACC_22B     YESNOFM. 
    ACC_22C     YESNOFM. 
    ACC_22D     YESNOFM. 
    ACC_22E     YESNOFM. 
    ACC_22F     YESNOFM. 
    ACC_22G     YESNOFM. 
    ACC_22H     YESNOFM. 
    ACC_22I     YESNOFM. 
    ACC_22J     YESNOFM. 
    ACC_22K     YESNOFM. 
    ACC_22L     YESNOFM. 
    ACC_22M     YESNOFM. 
    ACC_22N     YESNOFM. 
    ACC_22O     YESNOFM. 
    ACC_30      YESNOFM. 
    ACC_31      YESNOFM. 
    ACC_32A     YESNOFM. 
    ACC_32B     YESNOFM. 
    ACC_32C     YESNOFM. 
    ACC_32D     YESNOFM. 
    ACC_32E     YESNOFM. 
    ACC_32F     YESNOFM. 
    ACC_32G     YESNOFM. 
    ACC_32H     YESNOFM. 
    ACC_32I     YESNOFM. 
    ACC_32J     YESNOFM. 
    ACC_32K     YESNOFM. 
    ACC_32L     YESNOFM. 
    ACC_32M     YESNOFM. 
    ACC_32N     YESNOFM. 
    ACC_40      YESNOFM. 
    ACC_40A     YESNOFM. 
    ACC_40B     YESNOFM. 
    ACC_40C     YESNOFM. 
    ACC_40D     YESNOFM. 
    ACC_40E     YESNOFM. 
    ACC_40F     YESNOFM. 
    ACC_40G     YESNOFM. 
    ACC_41      YESNOFM. 
    ACC_42      YESNO.   
    ACC_43A     YESNOFM. 
    ACC_43B     YESNOFM. 
    ACC_43C     YESNOFM. 
    ACC_43D     YESNOFM. 
    ACC_43E     YESNOFM. 
    ACC_43F     YESNOFM. 
    ACC_43G     YESNOFM. 
    ACC_43H     YESNOFM. 
    ACC_43I     YESNOFM. 
    ACC_44      YESNO.   
    ACC_45A     YESNOFM. 
    ACC_45B     YESNOFM. 
    ACC_45C     YESNOFM. 
    ACC_45D     YESNOFM. 
    ACC_45E     YESNOFM. 
    ACC_45F     YESNOFM. 
    ACC_45G     YESNOFM. 
    ACC_45H     YESNOFM. 
    ACC_45I     YESNOFM. 
    ACC_46      YESNO.   
    ACC_47A     YESNOFM. 
    ACC_47B     YESNOFM. 
    ACC_47C     YESNOFM. 
    ACC_47D     YESNOFM. 
    ACC_47E     YESNOFM. 
    ACC_47F     YESNOFM. 
    ACC_47G     YESNOFM. 
    ACC_47H     YESNOFM. 
    ACC_47I     YESNOFM. 
    ACC_50A     YESNOFM. 
    ACC_50      YESNOFM. 
    ACC_51      YESNOFM. 
    ACC_52      YESNO.   
    ACC_53A     YESNOFM. 
    ACC_53B     YESNOFM. 
    ACC_53C     YESNOFM. 
    ACC_53D     YESNOFM. 
    ACC_53E     YESNOFM. 
    ACC_53F     YESNOFM. 
    ACC_53G     YESNOFM. 
    ACC_53H     YESNOFM. 
    ACC_53I     YESNOFM. 
    ACC_53J     YESNOFM. 
    ACC_53K     YESNOFM. 
    ACC_53L     YESNOFM. 
    ACC_53M     YESNOFM. 
    ACC_54      YESNO.   
    ACC_55A     YESNOFM. 
    ACC_55B     YESNOFM. 
    ACC_55C     YESNOFM. 
    ACC_55D     YESNOFM. 
    ACC_55E     YESNOFM. 
    ACC_55F     YESNOFM. 
    ACC_55G     YESNOFM. 
    ACC_55H     YESNOFM. 
    ACC_55I     YESNOFM. 
    ACC_55J     YESNOFM. 
    ACC_55K     YESNOFM. 
    ACC_55L     YESNOFM. 
    ACC_55M     YESNOFM. 
    ACC_60      YESNOFM. 
    ACC_61      YESNOFM. 
    ACC_62      YESNO.   
    ACC_63A     YESNOFM. 
    ACC_63B     YESNOFM. 
    ACC_63C     YESNOFM. 
    ACC_63D     YESNOFM. 
    ACC_63E     YESNOFM. 
    ACC_63F     YESNOFM. 
    ACC_63G     YESNOFM. 
    ACC_63H     YESNOFM. 
    ACC_63I     YESNOFM. 
    ACC_63J     YESNOFM. 
    ACC_63K     YESNOFM. 
    ACC_63L     YESNOFM. 
    ACC_63M     YESNOFM. 
    ACC_64      YESNO.   
    ACC_65A     YESNOFM. 
    ACC_65B     YESNOFM. 
    ACC_65C     YESNOFM. 
    ACC_65D     YESNOFM. 
    ACC_65E     YESNOFM. 
    ACC_65F     YESNOFM. 
    ACC_65G     YESNOFM. 
    ACC_65H     YESNOFM. 
    ACC_65I     YESNOFM. 
    ACC_65J     YESNOFM. 
    ACC_65K     YESNOFM. 
    ACC_65L     YESNOFM. 
    ACC_65M     YESNOFM. 
    ACC_66      YESNO.   
    ACC_67A     YESNOFM. 
    ACC_67B     YESNOFM. 
    ACC_67C     YESNOFM. 
    ACC_67D     YESNOFM. 
    ACC_67E     YESNOFM. 
    ACC_67F     YESNOFM. 
    ACC_67G     YESNOFM. 
    ACC_67H     YESNOFM. 
    ACC_67I     YESNOFM. 
    ACC_67J     YESNOFM. 
    ACC_67K     YESNOFM. 
    ACC_67L     YESNOFM. 
    ACC_67M     YESNOFM. 
    DOWTM       YESNOFM. 
    WTM_01      YESNOFM. 
    WTM_02      WTMC02FM.
    WTM_03      WTMC03FM.
    WTM_04      YESNOFM. 
    WTM_05      YESNOFM. 
    WTM_06A     YESNOFM. 
    WTM_06B     YESNOFM. 
    WTM_06C     YESNOFM. 
    WTM_06D     YESNOFM. 
    WTM_06E     YESNOFM. 
    WTM_06F     YESNOFM. 
    WTM_06G     YESNOFM. 
    WTM_06H     YESNOFM. 
    WTM_06I     YESNOFM. 
    WTM_06J     YESNOFM. 
    WTM_06K     YESNOFM. 
    WTM_06L     YESNOFM. 
    WTM_06M     YESNOFM. 
    WTM_07A     WTMC7AFM.
    WTM_07B     WTMC7BFM.
    WTM_08A     WTMC7AFM.
    WTM_08B     WTMC7BFM.
    WTM_10      WTMC10FM.
    WTM_11A     WTMC7AFM.
    WTM_11B     WTMC7BFM.
    WTM_12      YESNOFM. 
    WTM_13A     YESNOFM. 
    WTM_13B     YESNOFM. 
    WTM_13C     YESNOFM. 
    WTM_14      YESNOFM. 
    WTM_15A     YESNOFM. 
    WTM_15B     YESNOFM. 
    WTM_15C     YESNOFM. 
    WTM_15D     YESNOFM. 
    WTM_15E     YESNOFM. 
    WTM_15F     YESNOFM. 
    WTM_15G     YESNOFM. 
    WTM_15H     YESNOFM. 
    WTM_15I     YESNOFM. 
    WTM_15J     YESNOFM. 
    WTM_15K     YESNOFM. 
    WTM_15L     YESNOFM. 
    WTM_16      WTMC16FM.
    WTM_17      YESNOFM. 
    WTM_18      YESNOFM. 
    WTM_19      YESNOFM. 
    WTM_20A     YESNOFM. 
    WTM_20B     YESNOFM. 
    WTM_20C     YESNOFM. 
    WTM_20D     YESNOFM. 
    WTM_20E     YESNOFM. 
    WTM_20F     YESNOFM. 
    WTM_20G     YESNOFM. 
    WTM_20H     YESNOFM. 
    WTM_20I     YESNOFM. 
    WTM_20J     YESNOFM. 
    WTM_20K     YESNOFM. 
    WTM_20L     YESNOFM. 
    WTM_20M     YESNOFM. 
    WTM_20N     YESNOFM. 
    WTM_21A     WTMC7AFM.
    WTM_21B     WTMC7BFM.
    WTM_22      YESNOFM. 
    WTM_23A     WTMC7AFM.
    WTM_23B     WTMC7BFM.
    WTM_24      WTMC10FM.
    WTM_25A     WTMC7AFM.
    WTM_25B     WTMC7BFM.
    WTM_26      YESNOFM. 
    WTM_27A     YESNOFM. 
    WTM_27B     YESNOFM. 
    WTM_27C     YESNOFM. 
    WTM_27D     YESNOFM. 
    WTM_28      YESNOFM. 
    WTM_29A     YESNOFM. 
    WTM_29B     YESNOFM. 
    WTM_29C     YESNOFM. 
    WTM_29D     YESNOFM. 
    WTM_29E     YESNOFM. 
    WTM_29F     YESNOFM. 
    WTM_29G     YESNOFM. 
    WTM_29H     YESNOFM. 
    WTM_29I     YESNOFM. 
    WTM_29J     YESNOFM. 
    WTM_29K     YESNOFM. 
    WTM_29L     YESNOFM. 
    WTM_30      WTMCFM.  
    WTM_31      WTM31FM. 
    WTM_32      YESNOFM. 
    WTM_33      WTM33FM. 
    WTM_34      WTMC34FM.
    WTM_35      YESNOFM. 
    WTM_36      YESNOFM. 
    WTM_37A     YESNOFM. 
    WTM_37B     YESNOFM. 
    WTM_37C     YESNOFM. 
    WTM_37D     YESNOFM. 
    WTM_37E     YESNOFM. 
    WTM_37F     YESNOFM. 
    WTM_37G     YESNOFM. 
    WTM_37H     YESNOFM. 
    WTM_37I     YESNOFM. 
    WTM_37J     YESNOFM. 
    WTM_37K     YESNOFM. 
    WTM_37L     YESNOFM. 
    WTM_37M     YESNOFM. 
    WTM_38A     WTMC7AFM.
    WTM_38B     WTMC7BFM.
    WTM_39A     WTMC7AFM.
    WTM_39B     WTMC7BFM.
    WTM_40      WTMC10FM.
    WTM_41A     WTMC7AFM.
    WTM_41B     WTMC7BFM.
    WTM_42      YESNOFM. 
    WTM_43      WTMC43FM.
    WTM_44      YESNOFM. 
    WTM_45A     YESNOFM. 
    WTM_45B     YESNOFM. 
    WTM_45C     YESNOFM. 
    WTM_45D     YESNOFM. 
    WTM_45E     YESNOFM. 
    WTM_45F     YESNOFM. 
    WTM_45G     YESNOFM. 
    WTM_45H     YESNOFM. 
    WTM_45I     YESNOFM. 
    WTM_45J     YESNOFM. 
    WTM_45K     YESNOFM. 
    WTM_45L     YESNOFM. 
    WTMDSO      DAY4DFM. 
    WTMDSN      DAY4DFM. 
    WTMDSA      DAY4DFM. 
    WTMDCO      DAY4DFM. 
    WTMDCN      DAY4DFM. 
    WTMDCA      DAY4DFM. 
    WTMDTO      DAY4DFM. 
    WTMDTN      DAY4DFM. 
    WTMDTA      DAY4DFM. 
    LBS_01      LSC_1F.  
    LBS_02      YESNOFM. 
    LBS_03      YESNOFM. 
    LBS_11      YESNOFM. 
    LBS_31      LSC_31F. 
    LBSF32      YESNOFM. 
    LBSF33      YESNOFM. 
    LBSF34      YESNOFM. 
    LBSF35      YESNOFM. 
    LBSCSIC    $LBSS_CFM.
    LBSCSOC    $LBSS_CFM.
    LBSF36      YESNOFM. 
    LBS_42      HOUR3DFM.
    LBS_53      HOUR3DFM.
    LBSDHPW     LSCDHPW. 
    LBSDPFT     LBF_PFT. 
    LBSDWSS     LSCDCWS. 
    LBSDING    $LBSDINFM.
    LBSDOCG    $LBSDOCFM.
    DOLOP       YESNOFM. 
    LOP_015     YESNOFM. 
    LOP_020     LOP020FM.
    LOP_030     YESNOFM. 
    LOP_040     DAY2DFM. 
    LOP_050     LOP050FM.
    LOP_060     YESNOFM. 
    LOP_070     DAY2DFM. 
    LOP_080     YESNOFM. 
    LOP_81A     YESNOFM. 
    LOP_81B     YESNOFM. 
    LOP_81C     YESNOFM. 
    LOP_81D     YESNOFM. 
    LOP_81E     YESNOFM. 
    LOP_082     DAY2DFM. 
    LOP_083     DAY2DFM. 
    LOP_084     DAY2DFM. 
    LOP_085     DAY2DFM. 
    LOP_086     DAY2DFM. 
    LOP_090     YESNOFM. 
    LOP_100     DAY2DFM. 
    EDU_1       EDUGRADE.
    EDU_2       YESNOFM. 
    EDU_3       YESNOFM. 
    EDU_4A      EDUQ4AFM.
    EDUDH04     DVED3FM. 
    EDUDH10     EDU_10DR.
    EDUDR04     EDUDR4FM.
    EDUDR10     EDU_10DR.
    SDC_8       YESNOFM. 
    SDC_9       EDUQ06FM.
    SDCCCB13    SDCB10FM.
    SDCGCB10    SDCG10FM.
    SDC_2       YESNOFM. 
    SDC_3       SDYEARFM.
    SDC_4A      YESNOFM. 
    SDC_4B      YESNOFM. 
    SDC_4C      YESNOFM. 
    SDC_4D      YESNOFM. 
    SDC_4E      YESNOFM. 
    SDC_4F      YESNOFM. 
    SDC_4G      YESNOFM. 
    SDC_4H      YESNOFM. 
    SDC_4I      YESNOFM. 
    SDC_4J      YESNOFM. 
    SDC_4K      YESNOFM. 
    SDC_4L      YESNOFM. 
    SDC_4M      YESNOFM. 
    SDC_4N      YESNOFM. 
    SDC_4T      YESNOFM. 
    SDC_4U      YESNOFM. 
    SDC_4V      YESNOFM. 
    SDC_4P      YESNOFM. 
    SDC_4Q      YESNOFM. 
    SDC_4R      YESNOFM. 
    SDC_4S      YESNOFM. 
    SDC_41      YESNOFM. 
    SDC_42A     YESNOFM. 
    SDC_42B     YESNOFM. 
    SDC_42C     YESNOFM. 
    SDC_43A     YESNOFM. 
    SDC_43C     YESNOFM. 
    SDC_43B     YESNOFM. 
    SDC_43D     YESNOFM. 
    SDC_43E     YESNOFM. 
    SDC_43F     YESNOFM. 
    SDC_43H     YESNOFM. 
    SDC_43G     YESNOFM. 
    SDC_43I     YESNOFM. 
    SDC_43K     YESNOFM. 
    SDC_43J     YESNOFM. 
    SDC_43M     YESNOFM. 
    SDC_5A_1    SDCQ5AFM.
    SDCC5B1     SDCC61FM.
    SDCC5B2     SDCC61FM.
    SDCC5B3     SDCC61FM.
    SDCC61      SDCC61FM.
    SDCC62      SDCC61FM.
    SDCC63      SDCC61FM.
    SDCDFOLS    SDCFOLFM.
    DHH_OWN     DHH011FM.
    SDC_7AA     SDC7AFM. 
    SDCDLHM     SDCDLNFM.
    SDCDAIM     AGE3DFM. 
    SDCFIMM     YESNOFM. 
    SDCDRES     AGE3DFM. 
    SDCDFL1     SDCDFLFM.
    SDCDABT     SDC_ABO. 
    SDCDCGT     SDC_CG.  
    PMKPROXY    PMKP18FM.
    DOINS       YESNOFM. 
    INS_1       YESNOFM. 
    INS_1A      YESNOFM. 
    INS_1B      YESNOFM. 
    INS_1C      YESNOFM. 
    INS_2       YESNOFM. 
    INS_2A      YESNOFM. 
    INS_2B      YESNOFM. 
    INS_2C      YESNOFM. 
    INS_3       YESNOFM. 
    INS_3A      YESNOFM. 
    INS_3B      YESNOFM. 
    INS_3C      YESNOFM. 
    INS_4       YESNOFM. 
    INS_4A      YESNOFM. 
    INS_4B      YESNOFM. 
    INS_4C      YESNOFM. 
    DOFSC       YESNOFM. 
    FSC_010     FSCD10FM.
    FSC_020     FSCDFM.  
    FSC_030     FSCDFM.  
    FSC_040     FSCDFM.  
    FSC_050     FSCDFM.  
    FSC_060     FSCDFM.  
    FSC_070     FSCDFM.  
    FSC_080     YESNOFM. 
    FSC_081     FSC81FM. 
    FSC_090     YESNOFM. 
    FSC_100     YESNOFM. 
    FSC_110     YESNOFM. 
    FSC_120     YESNOFM. 
    FSC_121     FSC81FM. 
    FSC_130     YESNOFM. 
    FSC_140     YESNOFM. 
    FSC_141     FSC81FM. 
    FSC_150     YESNOFM. 
    FSC_160     YESNOFM. 
    FSCDHFS2    FSCDHFFM.
    FSCDAFS2    FSCDHFFM.
    FSCDCFS2    FSCDHFFM.
    INC_1A      YESNOFM. 
    INC_1B      YESNOFM. 
    INC_1C      YESNOFM. 
    INC_1D      YESNOFM. 
    INC_1E      YESNOFM. 
    INC_1F      YESNOFM. 
    INC_1G      YESNOFM. 
    INC_1O      YESNOFM. 
    INC_1H      YESNOFM. 
    INC_1J      YESNOFM. 
    INC_1I      YESNOFM. 
    INC_1K      YESNOFM. 
    INC_1L      YESNOFM. 
    INC_1M      YESNOFM. 
    INC_1N      YESNOFM. 
    INC_2       INC_Q2FM.
    INC_3       DOLL8_FM.
    INC_6A      YESNOFM. 
    INC_6B      YESNOFM. 
    INC_6C      YESNOFM. 
    INC_6D      YESNOFM. 
    INC_6E      YESNOFM. 
    INC_6F      YESNOFM. 
    INC_6G      YESNOFM. 
    INC_6H      YESNOFM. 
    INC_6I      YESNOFM. 
    INC_6J      YESNOFM. 
    INC_6K      YESNOFM. 
    INC_6L      YESNOFM. 
    INC_6M      YESNOFM. 
    INC_6N      YESNOFM. 
    INC_6O      YESNOFM. 
    INC_7       INC_Q2FM.
    INC_8A      DOLL8_FM.
    INC_8B      INCQ8BFM.
    INC_8C      INC_8CFM.
    INC_8D      INCQ8DFM.
    INCFIMP4    INCMPEFM.
    INCDHH      INC_DHFM.
    INCDPER     INCDPEFM.
    INCDADR     INCRATFM.
    INCDRCA     INCDECFM.
    INCDRPR     INCDECFM.
    INCDRRS     INCDECFM.
                       ;
