INFILE &datafid PAD LRECL = 1246;
INPUT
    @    1   SAMPLEID                             $ 20.      
    @   21   PERSONID                                2.      
    @   23   GEOE_PRV                                2.      
    @   25   GEOEDHR4                                4.      
    @   29   GEOEDSHR                                6.      
    @   35   GEOEDLHN                                4.      
    @   39   GEOEDDA                                 8.      
    @   47   GEOEDFED                                5.      
    @   52   GEOEDCSD                                7.      
    @   59   GEOEDCD                                 4.      
    @   63   GEOEDSAT                                1.      
    @   64   GEOEDCMA                                3.      
    @   67   GEOEDPRG                                2.      
    @   69   GEOEDUR7                                1.      
    @   70   GEOEDUR2                                1.      
    @   71   GEOEDPC                              $  6.      
    @   77   SAME_CP                              $  6.      
    @   83   SAME_TYP                                1.      
    @   84   SAMEDSHR                                1.      
    @   85   SAMEDLNK                                1.      
    @   86   ADME_STA                                2.      
    @   88   ADME_PRX                                1.      
    @   89   ADME_YOI                                4.      
    @   93   ADME_MOI                                2.      
    @   95   ADME_DOI                                2.      
    @   97   ADME_N09                                1.      
    @   98   ADME_N10                                1.      
    @   99   ADME_N11                                1.      
    @  100   ADME_N12                                2.      
    @  102   ADME_LHH                                1.      
    @  103   DHHE_AGE                                3.      
    @  106   DHHE_YOB                                4.      
    @  110   DHHE_MOB                                2.      
    @  112   DHHE_DOB                                2.      
    @  114   DHHE_SEX                                1.      
    @  115   DHHE_MS                                 2.      
    @  117   GENE_01                                 1.      
    @  118   GENE_02                                 1.      
    @  119   GENE_02A                                1.      
    @  120   GENE_02B                                1.      
    @  121   GENE_07                                 1.      
    @  122   GENE_08                                 1.      
    @  123   GENE_09                                 1.      
    @  124   GENE_10                                 1.      
    @  125   GENEDHDI                                1.      
    @  126   GENEDMHI                                1.      
    @  127   HWTE_2                                  2.      
    @  129   HWTE_2A                                 2.      
    @  131   HWTE_2B                                 2.      
    @  133   HWTE_2C                                 2.      
    @  135   HWTE_2D                                 2.      
    @  137   HWTE_2E                                 2.      
    @  139   HWTE_2F                                 2.      
    @  141   HWTE_3                                  3.      
    @  144   HWTE_N4                                 1.      
    @  145   HWTE_4                                  1.      
    @  146   HWTEDHTM                                5.3     
    @  151   HWTEDWTK                                6.2     
    @  157   HWTEDBMI                                6.2     
    @  163   HWTEDISW                                2.      
    @  165   HWTEDCOL                                1.      
    @  166   CCCE_011                                1.      
    @  167   CCCE_021                                1.      
    @  168   CCCE_031                                1.      
    @  169   CCCE_035                                1.      
    @  170   CCCE_036                                1.      
    @  171   CCCE_041                                1.      
    @  172   CCCE_051                                1.      
    @  173   CCCE_05A                                1.      
    @  174   CCCE_061                                1.      
    @  175   CCCE_071                                1.      
    @  176   CCCE_072                                1.      
    @  177   CCCE_073                                1.      
    @  178   CCCE_074                                1.      
    @  179   CCCE_75A                                1.      
    @  180   CCCE_75B                                1.      
    @  181   CCCE_75C                                1.      
    @  182   CCCE_75D                                1.      
    @  183   CCCE_081                                1.      
    @  184   CCCE_91A                                1.      
    @  185   CCCE_91E                                1.      
    @  186   CCCE_91F                                1.      
    @  187   CCCE_101                                1.      
    @  188   CCCE_102                                3.      
    @  191   CCCE_10A                                1.      
    @  192   CCCE_10B                                1.      
    @  193   CCCE_10C                                2.      
    @  195   CCCE_105                                1.      
    @  196   CCCE_106                                1.      
    @  197   CCCE_111                                1.      
    @  198   CCCE_121                                1.      
    @  199   CCCE_131                                1.      
    @  200   CCCE_31A                                1.      
    @  201   CCCE_13A                                1.      
    @  202   CCCE_13B                                1.      
    @  203   CCCE_13C                                1.      
    @  204   CCCE_13D                                1.      
    @  205   CCCE_13E                                1.      
    @  206   CCCE_13F                                1.      
    @  207   CCCE_141                                1.      
    @  208   CCCE_151                                1.      
    @  209   CCCE_161                                1.      
    @  210   CCCE_171                                1.      
    @  211   CCCE_17A                                1.      
    @  212   CCCE_181                                1.      
    @  213   CCCE_191                                1.      
    @  214   CCCE_201                                1.      
    @  215   CCCE_211                                1.      
    @  216   CCCE_251                                1.      
    @  217   CCCE_261                                1.      
    @  218   CCCE_271                                1.      
    @  219   CCCE_280                                1.      
    @  220   CCCE_290                                1.      
    @  221   CCCE_321                                1.      
    @  222   CCCE_331                                1.      
    @  223   CCCE_33A                                1.      
    @  224   CCCE_33B                                1.      
    @  225   CCCE_33C                                1.      
    @  226   CCCE_33D                                1.      
    @  227   CCCE_341                                1.      
    @  228   CCCE_901                                1.      
    @  229   CCCEF1                                  1.      
    @  230   HCUE_1AA                                1.      
    @  231   HCUE_1BA                                1.      
    @  232   HCUE_1BB                                1.      
    @  233   HCUE_1BC                                1.      
    @  234   HCUE_1BD                                1.      
    @  235   HCUE_1BE                                1.      
    @  236   HCUE_1AC                                2.      
    @  238   HCUE_01                                 1.      
    @  239   HCUE_01A                                3.      
    @  242   HCUE_02A                                3.      
    @  245   HCUE_02B                                2.      
    @  247   HCUE_02C                                3.      
    @  250   HCUE_02D                                3.      
    @  253   HCUE_02E                                3.      
    @  256   HCUE_02F                                3.      
    @  259   HCUE_02G                                3.      
    @  262   HCUE_02H                                3.      
    @  265   HCUE_02I                                3.      
    @  268   HCUE_02J                                3.      
    @  271   HCUE_03A                                2.      
    @  273   HCUE_3A1                                1.      
    @  274   HCUE_03C                                2.      
    @  276   HCUE_3C1                                1.      
    @  277   HCUE_03D                                2.      
    @  279   HCUE_3D1                                1.      
    @  280   HCUE_04A                                1.      
    @  281   HCUE_04                                 1.      
    @  282   HCUE_05A                                1.      
    @  283   HCUE_05B                                1.      
    @  284   HCUE_05C                                1.      
    @  285   HCUE_05D                                1.      
    @  286   HCUE_05E                                1.      
    @  287   HCUE_05F                                1.      
    @  288   HCUE_05G                                1.      
    @  289   HCUE_05H                                1.      
    @  290   HCUE_05I                                1.      
    @  291   HCUE_05J                                1.      
    @  292   HCUE_05K                                1.      
    @  293   HCUE_05L                                1.      
    @  294   HCUE_06                                 1.      
    @  295   HCUE_07A                                1.      
    @  296   HCUE_07B                                1.      
    @  297   HCUE_07C                                1.      
    @  298   HCUE_07D                                1.      
    @  299   HCUE_07E                                1.      
    @  300   HCUE_07F                                1.      
    @  301   HCUE_07G                                1.      
    @  302   HCUE_07H                                1.      
    @  303   HCUE_07I                                1.      
    @  304   HCUE_07J                                1.      
    @  305   HCUE_07K                                1.      
    @  306   HCUE_07L                                1.      
    @  307   HCUE_07M                                1.      
    @  308   HCUE_07O                                1.      
    @  309   HCUE_07P                                1.      
    @  310   HCUE_07N                                1.      
    @  311   HCUE_08A                                1.      
    @  312   HCUE_08B                                1.      
    @  313   HCUE_08C                                1.      
    @  314   HCUE_08D                                1.      
    @  315   HCUE_08E                                1.      
    @  316   HCUE_09A                                1.      
    @  317   HCUE_09B                                1.      
    @  318   HCUE_09C                                1.      
    @  319   HCUE_09D                                1.      
    @  320   HCUE_09E                                1.      
    @  321   HCUE_09F                                1.      
    @  322   HCUE_09G                                1.      
    @  323   HCUE_09H                                1.      
    @  324   HCUEDMDC                                3.      
    @  327   HCUEFCOP                                1.      
    @  328   HMCE_09                                 1.      
    @  329   HMCE_10A                                1.      
    @  330   HMCE_10B                                1.      
    @  331   HMCE_10C                                1.      
    @  332   HMCE_10D                                1.      
    @  333   HMCE_10E                                1.      
    @  334   HMCE_10F                                1.      
    @  335   HMCE_10G                                1.      
    @  336   HMCE_10H                                1.      
    @  337   HMCE_10I                                1.      
    @  338   HMCE_11                                 1.      
    @  339   HMCE_12A                                1.      
    @  340   HMCE_12B                                1.      
    @  341   HMCE_12G                                1.      
    @  342   HMCE_12C                                1.      
    @  343   HMCE_12D                                1.      
    @  344   HMCE_12E                                1.      
    @  345   HMCE_12F                                1.      
    @  346   HMCE_3AA                                1.      
    @  347   HMCE_3AB                                1.      
    @  348   HMCE_3AI                                1.      
    @  349   HMCE_3AC                                1.      
    @  350   HMCE_3AD                                1.      
    @  351   HMCE_3AE                                1.      
    @  352   HMCE_3AF                                1.      
    @  353   HMCE_3AG                                1.      
    @  354   HMCE_3AH                                1.      
    @  355   HMCE_3BA                                1.      
    @  356   HMCE_3BB                                1.      
    @  357   HMCE_3BI                                1.      
    @  358   HMCE_3BC                                1.      
    @  359   HMCE_3BD                                1.      
    @  360   HMCE_3BE                                1.      
    @  361   HMCE_3BF                                1.      
    @  362   HMCE_3BG                                1.      
    @  363   HMCE_3BH                                1.      
    @  364   HMCE_3GA                                1.      
    @  365   HMCE_3GB                                1.      
    @  366   HMCE_3GI                                1.      
    @  367   HMCE_3GC                                1.      
    @  368   HMCE_3GD                                1.      
    @  369   HMCE_3GE                                1.      
    @  370   HMCE_3GF                                1.      
    @  371   HMCE_3GG                                1.      
    @  372   HMCE_3GH                                1.      
    @  373   HMCE_3CA                                1.      
    @  374   HMCE_3CB                                1.      
    @  375   HMCE_3CI                                1.      
    @  376   HMCE_3CC                                1.      
    @  377   HMCE_3CD                                1.      
    @  378   HMCE_3CE                                1.      
    @  379   HMCE_3CF                                1.      
    @  380   HMCE_3CG                                1.      
    @  381   HMCE_3CH                                1.      
    @  382   HMCE_3DA                                1.      
    @  383   HMCE_3DB                                1.      
    @  384   HMCE_3DI                                1.      
    @  385   HMCE_3DC                                1.      
    @  386   HMCE_3DD                                1.      
    @  387   HMCE_3DE                                1.      
    @  388   HMCE_3DF                                1.      
    @  389   HMCE_3DG                                1.      
    @  390   HMCE_3DH                                1.      
    @  391   HMCE_3EA                                1.      
    @  392   HMCE_3EB                                1.      
    @  393   HMCE_3EI                                1.      
    @  394   HMCE_3EC                                1.      
    @  395   HMCE_3ED                                1.      
    @  396   HMCE_3EE                                1.      
    @  397   HMCE_3EF                                1.      
    @  398   HMCE_3EG                                1.      
    @  399   HMCE_3EH                                1.      
    @  400   HMCE_3FA                                1.      
    @  401   HMCE_3FB                                1.      
    @  402   HMCE_3FI                                1.      
    @  403   HMCE_3FC                                1.      
    @  404   HMCE_3FD                                1.      
    @  405   HMCE_3FE                                1.      
    @  406   HMCE_3FF                                1.      
    @  407   HMCE_3FG                                1.      
    @  408   HMCE_3FH                                1.      
    @  409   HMCE_14                                 1.      
    @  410   HMCE_15A                                1.      
    @  411   HMCE_15B                                1.      
    @  412   HMCE_15C                                1.      
    @  413   HMCE_15D                                1.      
    @  414   HMCE_15E                                1.      
    @  415   HMCE_15F                                1.      
    @  416   HMCE_15G                                1.      
    @  417   HMCE_15H                                1.      
    @  418   HMCE_15I                                1.      
    @  419   HMCE_15J                                1.      
    @  420   HMCE_15K                                1.      
    @  421   HMCE_15L                                1.      
    @  422   HMCE_15M                                1.      
    @  423   HMCE_15N                                1.      
    @  424   HMCE_15O                                1.      
    @  425   HMCE_16A                                1.      
    @  426   HMCE_16B                                1.      
    @  427   HMCE_16C                                1.      
    @  428   HMCE_16D                                1.      
    @  429   HMCE_16E                                1.      
    @  430   HMCE_16F                                1.      
    @  431   HMCE_16G                                1.      
    @  432   HMCE_16H                                1.      
    @  433   HMCE_16I                                1.      
    @  434   HMCE_17A                                1.      
    @  435   HMCE_17B                                1.      
    @  436   HMCE_17C                                1.      
    @  437   HMCE_17D                                1.      
    @  438   HMCE_17E                                1.      
    @  439   HMCEFRHC                                1.      
    @  440   RACE_1                                  1.      
    @  441   RACE_2A                                 1.      
    @  442   RACE_2B1                                1.      
    @  443   RACE_2B2                                1.      
    @  444   RACE_2C                                 1.      
    @  445   RACE_5                                  2.      
    @  447   RACE_5B1                                1.      
    @  448   RACE_5B2                                1.      
    @  449   RACE_6A                                 1.      
    @  450   RACE_6B1                                1.      
    @  451   RACE_6C                                 1.      
    @  452   RACE_6D                                 1.      
    @  453   RACE_6E                                 1.      
    @  454   RACE_6F                                 1.      
    @  455   RACE_6G                                 1.      
    @  456   RACE_7A                                 1.      
    @  457   RACE_7B                                 1.      
    @  458   RACE_7C                                 1.      
    @  459   RACE_8A                                 1.      
    @  460   RACE_8B                                 1.      
    @  461   RACE_8C                                 1.      
    @  462   RACE_8D                                 1.      
    @  463   RACEDIMP                                1.      
    @  464   RACEDPAL                                1.      
    @  465   RACEF6R                                 1.      
    @  466   RACEF7                                  1.      
    @  467   TWDE_1                                  1.      
    @  468   TWDE_2                                  2.      
    @  470   TWDE_2A                                 1.      
    @  471   TWDE_2B                                 2.      
    @  473   TWDE_3                                  1.      
    @  474   TWDE_4                                  2.      
    @  476   TWDE_4A                                 1.      
    @  477   TWDE_4B                                 2.      
    @  479   TWDE_5A                                 1.      
    @  480   TWDE_6                                  2.      
    @  482   TWDE_6A                                 1.      
    @  483   TWDE_6B                                 2.      
    @  485   TWDEDDDY                                2.      
    @  487   TWDEDDDM                                2.      
    @  489   TWDEDDDP                                2.      
    @  491   FLUE_160                                1.      
    @  492   FLUE_162                                1.      
    @  493   FLUE_66A                                1.      
    @  494   FLUE_66B                                1.      
    @  495   FLUE_66C                                1.      
    @  496   FLUE_66D                                1.      
    @  497   FLUE_66E                                1.      
    @  498   FLUE_66F                                1.      
    @  499   FLUE_66G                                1.      
    @  500   FLUE_66H                                1.      
    @  501   FLUE_66I                                1.      
    @  502   FLUE_66J                                1.      
    @  503   FLUE_66K                                1.      
    @  504   FLUE_66L                                1.      
    @  505   FLUE_66M                                1.      
    @  506   FLUE_66O                                1.      
    @  507   FLUE_66N                                1.      
    @  508   PAPE_020                                1.      
    @  509   PAPE_022                                1.      
    @  510   PAPE_26A                                1.      
    @  511   PAPE_26B                                1.      
    @  512   PAPE_26C                                1.      
    @  513   PAPE_26D                                1.      
    @  514   PAPE_26E                                1.      
    @  515   PAPE_26F                                1.      
    @  516   PAPE_26G                                1.      
    @  517   PAPE_26H                                1.      
    @  518   PAPE_26I                                1.      
    @  519   PAPE_26J                                1.      
    @  520   PAPE_26K                                1.      
    @  521   PAPE_26L                                1.      
    @  522   PAPE_26M                                1.      
    @  523   PAPE_26N                                1.      
    @  524   PAPE_26P                                1.      
    @  525   PAPE_26O                                1.      
    @  526   MAME_030                                1.      
    @  527   MAME_31A                                1.      
    @  528   MAME_31B                                1.      
    @  529   MAME_31C                                1.      
    @  530   MAME_31D                                1.      
    @  531   MAME_31E                                1.      
    @  532   MAME_31F                                1.      
    @  533   MAME_31G                                1.      
    @  534   MAME_31H                                1.      
    @  535   MAME_032                                1.      
    @  536   MAME_36A                                1.      
    @  537   MAME_36B                                1.      
    @  538   MAME_36C                                1.      
    @  539   MAME_36D                                1.      
    @  540   MAME_36E                                1.      
    @  541   MAME_36F                                1.      
    @  542   MAME_36G                                1.      
    @  543   MAME_36H                                1.      
    @  544   MAME_36I                                1.      
    @  545   MAME_36J                                1.      
    @  546   MAME_36K                                1.      
    @  547   MAME_36L                                1.      
    @  548   MAME_36M                                1.      
    @  549   MAME_36N                                1.      
    @  550   MAME_36O                                1.      
    @  551   MAME_037                                1.      
    @  552   MAME_038                                1.      
    @  553   PACE_1A                                 1.      
    @  554   PACE_1B                                 1.      
    @  555   PACE_1C                                 1.      
    @  556   PACE_1D                                 1.      
    @  557   PACE_1E                                 1.      
    @  558   PACE_1F                                 1.      
    @  559   PACE_1G                                 1.      
    @  560   PACE_1H                                 1.      
    @  561   PACE_1I                                 1.      
    @  562   PACE_1J                                 1.      
    @  563   PACE_1K                                 1.      
    @  564   PACE_1L                                 1.      
    @  565   PACE_1M                                 1.      
    @  566   PACE_1N                                 1.      
    @  567   PACE_1O                                 1.      
    @  568   PACE_1P                                 1.      
    @  569   PACE_1Q                                 1.      
    @  570   PACE_1R                                 1.      
    @  571   PACE_1S                                 1.      
    @  572   PACE_1T                                 1.      
    @  573   PACE_1Z                                 1.      
    @  574   PACE_1U                                 1.      
    @  575   PACE_1V                                 1.      
    @  576   PACE_1W                                 1.      
    @  577   PACE_1X                                 1.      
    @  578   PACE_2A                                 3.      
    @  581   PACE_3A                                 1.      
    @  582   PACE_2B                                 3.      
    @  585   PACE_3B                                 1.      
    @  586   PACE_2C                                 3.      
    @  589   PACE_3C                                 1.      
    @  590   PACE_2D                                 3.      
    @  593   PACE_3D                                 1.      
    @  594   PACE_2E                                 3.      
    @  597   PACE_3E                                 1.      
    @  598   PACE_2F                                 3.      
    @  601   PACE_3F                                 1.      
    @  602   PACE_2G                                 3.      
    @  605   PACE_3G                                 1.      
    @  606   PACE_2H                                 3.      
    @  609   PACE_3H                                 1.      
    @  610   PACE_2I                                 3.      
    @  613   PACE_3I                                 1.      
    @  614   PACE_2J                                 3.      
    @  617   PACE_3J                                 1.      
    @  618   PACE_2K                                 3.      
    @  621   PACE_3K                                 1.      
    @  622   PACE_2L                                 3.      
    @  625   PACE_3L                                 1.      
    @  626   PACE_2M                                 3.      
    @  629   PACE_3M                                 1.      
    @  630   PACE_2N                                 3.      
    @  633   PACE_3N                                 1.      
    @  634   PACE_2O                                 3.      
    @  637   PACE_3O                                 1.      
    @  638   PACE_2P                                 3.      
    @  641   PACE_3P                                 1.      
    @  642   PACE_2Q                                 3.      
    @  645   PACE_3Q                                 1.      
    @  646   PACE_2R                                 3.      
    @  649   PACE_3R                                 1.      
    @  650   PACE_2S                                 3.      
    @  653   PACE_3S                                 1.      
    @  654   PACE_2T                                 3.      
    @  657   PACE_3T                                 1.      
    @  658   PACE_2Z                                 3.      
    @  661   PACE_3Z                                 1.      
    @  662   PACE_2U                                 3.      
    @  665   PACE_3U                                 1.      
    @  666   PACE_2W                                 3.      
    @  669   PACE_3W                                 1.      
    @  670   PACE_2X                                 3.      
    @  673   PACE_3X                                 1.      
    @  674   PACE_4A                                 2.      
    @  676   PACE_4B                                 2.      
    @  678   PACE_6                                  1.      
    @  679   PACEDEE                                 4.1     
    @  683   PACEFLEI                                1.      
    @  684   PACEDFM                                 3.      
    @  687   PACEDFR                                 1.      
    @  688   PACEFD                                  1.      
    @  689   PACEDPAI                                1.      
    @  690   SMKE_01A                                1.      
    @  691   SMKE_01B                                1.      
    @  692   SMKE_01C                                3.      
    @  695   SMKE_202                                1.      
    @  696   SMKE_203                                3.      
    @  699   SMKE_204                                3.      
    @  702   SMKE_05B                                3.      
    @  705   SMKE_05C                                2.      
    @  707   SMKE_05D                                1.      
    @  708   SMKE_06A                                1.      
    @  709   SMKE_06B                                2.      
    @  711   SMKE_06C                                3.      
    @  714   SMKE_207                                3.      
    @  717   SMKE_208                                3.      
    @  720   SMKE_09A                                1.      
    @  721   SMKE_09B                                2.      
    @  723   SMKE_09C                                3.      
    @  726   SMKE_10                                 1.      
    @  727   SMKE_10A                                1.      
    @  728   SMKE_10B                                2.      
    @  730   SMKE_10C                                3.      
    @  733   SMKEDSTY                                2.      
    @  735   SMKEDSTP                                3.      
    @  738   SMKEDYCS                                3.      
    @  741   YSME_1                                  2.      
    @  743   YSME_2                                  1.      
    @  744   YSME_3                                  1.      
    @  745   YSME_4                                  1.      
    @  746   YSME_5                                  1.      
    @  747   ETSE_10                                 1.      
    @  748   ETSE_11                                 2.      
    @  750   ETSE_20                                 1.      
    @  751   ETSE_20B                                1.      
    @  752   ETSE_5                                  1.      
    @  753   ETSE_6A                                 1.      
    @  754   ETSE_6B                                 1.      
    @  755   ETSE_6C                                 1.      
    @  756   ETSE_6D                                 1.      
    @  757   ALCE_1                                  1.      
    @  758   ALCE_2                                  2.      
    @  760   ALCE_3                                  2.      
    @  762   ALCE_5                                  1.      
    @  763   ALCE_5A1                                3.      
    @  766   ALCE_5A2                                3.      
    @  769   ALCE_5A3                                3.      
    @  772   ALCE_5A4                                3.      
    @  775   ALCE_5A5                                3.      
    @  778   ALCE_5A6                                3.      
    @  781   ALCE_5A7                                3.      
    @  784   ALCE_5B                                 1.      
    @  785   ALCE_6                                  1.      
    @  786   ALCE_7A                                 1.      
    @  787   ALCE_7B                                 1.      
    @  788   ALCE_7C                                 1.      
    @  789   ALCE_7D                                 1.      
    @  790   ALCE_7E                                 1.      
    @  791   ALCE_7F                                 1.      
    @  792   ALCE_7G                                 1.      
    @  793   ALCE_7H                                 1.      
    @  794   ALCE_7I                                 1.      
    @  795   ALCE_7J                                 1.      
    @  796   ALCE_7K                                 1.      
    @  797   ALCE_7L                                 1.      
    @  798   ALCE_7M                                 1.      
    @  799   ALCE_7N                                 1.      
    @  800   ALCE_8                                  3.      
    @  803   ALCEDTYP                                1.      
    @  804   ALCEDDLY                                3.      
    @  807   ALCEDWKY                                3.      
    @  810   MEXE_01                                 1.      
    @  811   MEXE_01A                                4.      
    @  815   MEXE_02                                 1.      
    @  816   MEXE_03                                 1.      
    @  817   MEXE_04                                 2.      
    @  819   MEXE_05                                 1.      
    @  820   MEXE_06                                 2.      
    @  822   MEXE_07                                 2.      
    @  824   MEXE_08                                 2.      
    @  826   MEXE_09                                 1.      
    @  827   MEXE_10                                 2.      
    @  829   MEXE_20                                 1.      
    @  830   MEXE_21                                 3.      
    @  833   MEXE_22                                 3.      
    @  836   MEXE_23                                 1.      
    @  837   MEXE_24                                 3.      
    @  840   MEXE_25                                 3.      
    @  843   MEXE_26                                 1.      
    @  844   MEXE_30                                 1.      
    @  845   MEXE_31                                 2.      
    @  847   MEXE_32                                 1.      
    @  848   MEXE_33                                 2.      
    @  850   MEXEDEBF                                2.      
    @  852   MEXEFEB4                                1.      
    @  853   REPE_1                                  1.      
    @  854   REPE_3                                  2.      
    @  856   REPE_4A                                 1.      
    @  857   REPE_4B                                 1.      
    @  858   REPE_4C                                 1.      
    @  859   REPE_4G                                 1.      
    @  860   REPE_4D                                 1.      
    @  861   REPE_4E                                 1.      
    @  862   REPE_4F                                 1.      
    @  863   INJE_01                                 1.      
    @  864   INJE_02                                 2.      
    @  866   INJE_03                                 2.      
    @  868   INJE_04                                 1.      
    @  869   INJE_05                                 2.      
    @  871   INJE_06                                 2.      
    @  873   INJE_07                                 1.      
    @  874   INJE_08                                 2.      
    @  876   INJE_09                                 2.      
    @  878   INJE_10                                 1.      
    @  879   INJE_11                                 2.      
    @  881   INJE_12                                 2.      
    @  883   INJE_13                                 1.      
    @  884   INJE_14A                                1.      
    @  885   INJE_14B                                1.      
    @  886   INJE_14C                                1.      
    @  887   INJE_14D                                1.      
    @  888   INJE_14E                                1.      
    @  889   INJE_14F                                1.      
    @  890   INJE_14G                                1.      
    @  891   INJE_14H                                1.      
    @  892   INJE_14I                                1.      
    @  893   INJE_14J                                1.      
    @  894   INJE_14K                                1.      
    @  895   INJE_15                                 1.      
    @  896   INJE_16                                 1.      
    @  897   INJE_17                                 2.      
    @  899   INJEDTBS                                4.      
    @  903   INJEDCAU                                2.      
    @  905   INJEDCBP                                4.      
    @  909   INJEDSTT                                1.      
    @  910   SXBE_1                                  1.      
    @  911   SXBE_2                                  3.      
    @  914   SXBE_3                                  1.      
    @  915   SXBE_4                                  1.      
    @  916   SXBE_07                                 1.      
    @  917   SXBE_7A                                 1.      
    @  918   SXBE_09                                 1.      
    @  919   SXBE_10                                 2.      
    @  921   SXBE_11                                 1.      
    @  922   SXBE_12A                                1.      
    @  923   SXBE_12B                                1.      
    @  924   SXBE_12C                                1.      
    @  925   SXBE_12D                                1.      
    @  926   SXBE_12F                                1.      
    @  927   SXBE_12E                                1.      
    @  928   SXBE_13A                                1.      
    @  929   SXBE_13B                                1.      
    @  930   SXBE_13C                                1.      
    @  931   SXBE_13D                                1.      
    @  932   SXBE_13E                                1.      
    @  933   SXBE_13F                                1.      
    @  934   SXBE_13G                                1.      
    @  935   LBSE_01                                 1.      
    @  936   LBSE_02                                 1.      
    @  937   LBSE_03                                 1.      
    @  938   LBSE_11                                 1.      
    @  939   LBSE_42                                 3.      
    @  942   ETSE_7                                  1.      
    @  943   LBSE_53                                 3.      
    @  946   LBSEDHPW                                3.      
    @  949   LBSEDPFT                                1.      
    @  950   LBSEDWSS                                1.      
    @  951   SDCEFPRD                                1.      
    @  952   SDCE_1                                  2.      
    @  954   SDCE_2                                  1.      
    @  955   SDCE_3                                  4.      
    @  959   SDCE_4A                                 1.      
    @  960   SDCE_4B                                 1.      
    @  961   SDCE_4C                                 1.      
    @  962   SDCE_4D                                 1.      
    @  963   SDCE_4E                                 1.      
    @  964   SDCE_4F                                 1.      
    @  965   SDCE_4G                                 1.      
    @  966   SDCE_4H                                 1.      
    @  967   SDCE_4I                                 1.      
    @  968   SDCE_4J                                 1.      
    @  969   SDCE_4K                                 1.      
    @  970   SDCE_4L                                 1.      
    @  971   SDCE_4M                                 1.      
    @  972   SDCE_4N                                 1.      
    @  973   SDCE_4T                                 1.      
    @  974   SDCE_4U                                 1.      
    @  975   SDCE_4V                                 1.      
    @  976   SDCE_4P                                 1.      
    @  977   SDCE_4Q                                 1.      
    @  978   SDCE_4R                                 1.      
    @  979   SDCE_4S                                 1.      
    @  980   SDCE_41                                 1.      
    @  981   SDCE_42A                                1.      
    @  982   SDCE_42B                                1.      
    @  983   SDCE_42C                                1.      
    @  984   SDCE_43A                                1.      
    @  985   SDCE_43B                                1.      
    @  986   SDCE_43C                                1.      
    @  987   SDCE_43D                                1.      
    @  988   SDCE_43E                                1.      
    @  989   SDCE_43F                                1.      
    @  990   SDCE_43G                                1.      
    @  991   SDCE_43H                                1.      
    @  992   SDCE_43I                                1.      
    @  993   SDCE_43J                                1.      
    @  994   SDCE_43K                                1.      
    @  995   SDCE_43M                                1.      
    @  996   SDCE_5A                                 1.      
    @  997   SDCE_5B                                 1.      
    @  998   SDCE_5C                                 1.      
    @  999   SDCE_5D                                 1.      
    @ 1000   SDCE_5E                                 1.      
    @ 1001   SDCE_5F                                 1.      
    @ 1002   SDCE_5G                                 1.      
    @ 1003   SDCE_5H                                 1.      
    @ 1004   SDCE_5I                                 1.      
    @ 1005   SDCE_5J                                 1.      
    @ 1006   SDCE_5K                                 1.      
    @ 1007   SDCE_5L                                 1.      
    @ 1008   SDCE_5M                                 1.      
    @ 1009   SDCE_5N                                 1.      
    @ 1010   SDCE_5O                                 1.      
    @ 1011   SDCE_5P                                 1.      
    @ 1012   SDCE_5Q                                 1.      
    @ 1013   SDCE_5R                                 1.      
    @ 1014   SDCE_5T                                 1.      
    @ 1015   SDCE_5U                                 1.      
    @ 1016   SDCE_5V                                 1.      
    @ 1017   SDCE_5W                                 1.      
    @ 1018   SDCE_5S                                 1.      
    @ 1019   SDCE_5AA                                2.      
    @ 1021   SDCE_6A                                 1.      
    @ 1022   SDCE_6B                                 1.      
    @ 1023   SDCE_6C                                 1.      
    @ 1024   SDCE_6D                                 1.      
    @ 1025   SDCE_6E                                 1.      
    @ 1026   SDCE_6F                                 1.      
    @ 1027   SDCE_6G                                 1.      
    @ 1028   SDCE_6H                                 1.      
    @ 1029   SDCE_6I                                 1.      
    @ 1030   SDCE_6J                                 1.      
    @ 1031   SDCE_6K                                 1.      
    @ 1032   SDCE_6L                                 1.      
    @ 1033   SDCE_6M                                 1.      
    @ 1034   SDCE_6N                                 1.      
    @ 1035   SDCE_6O                                 1.      
    @ 1036   SDCE_6P                                 1.      
    @ 1037   SDCE_6Q                                 1.      
    @ 1038   SDCE_6R                                 1.      
    @ 1039   SDCE_6T                                 1.      
    @ 1040   SDCE_6U                                 1.      
    @ 1041   SDCE_6V                                 1.      
    @ 1042   SDCE_6W                                 1.      
    @ 1043   SDCE_6S                                 1.      
    @ 1044   SDCE_7A                                 1.      
    @ 1045   SDCE_7B                                 1.      
    @ 1046   SDCE_7C                                 1.      
    @ 1047   SDCE_7D                                 1.      
    @ 1048   SDCE_7E                                 1.      
    @ 1049   SDCE_7F                                 1.      
    @ 1050   SDCE_7G                                 1.      
    @ 1051   SDCE_7H                                 1.      
    @ 1052   SDCE_7I                                 1.      
    @ 1053   SDCE_7J                                 1.      
    @ 1054   SDCE_7K                                 1.      
    @ 1055   SDCE_7L                                 1.      
    @ 1056   SDCE_7M                                 1.      
    @ 1057   SDCE_7BA                                1.      
    @ 1058   SDCE_7AA                                1.      
    @ 1059   SDCE_8                                  1.      
    @ 1060   SDCE_9                                  1.      
    @ 1061   SDCECCB                                 3.      
    @ 1064   SDCEGCB                                 2.      
    @ 1066   SDCEDAIM                                3.      
    @ 1069   SDCEFIMM                                1.      
    @ 1070   SDCEDRES                                3.      
    @ 1073   SDCEFABT                                1.      
    @ 1074   SDCEGCGT                                1.      
    @ 1075   SDCEDCGT                                2.      
    @ 1077   SDCEDLNG                                2.      
    @ 1079   SDCEDFL1                                2.      
    @ 1081   EDUE_1                                  1.      
    @ 1082   EDUE_2                                  1.      
    @ 1083   EDUE_3                                  1.      
    @ 1084   EDUE_4                                  2.      
    @ 1086   EDUEDH04                                1.      
    @ 1087   EDUEDH10                                2.      
    @ 1089   EDUEDR04                                1.      
    @ 1090   EDUEDR10                                2.      
    @ 1092   DHHEDHSZ                                2.      
    @ 1094   DHHEDL12                                2.      
    @ 1096   DHHEDLE5                                2.      
    @ 1098   DHHED611                                2.      
    @ 1100   DHHEDECF                                2.      
    @ 1102   DHHEDLVG                                2.      
    @ 1104   DHHEDDWE                                2.      
    @ 1106   DHHE_OWN                                1.      
    @ 1107   DHHE_BED                                2.      
    @ 1109   INCE_1A                                 1.      
    @ 1110   INCE_1B                                 1.      
    @ 1111   INCE_1C                                 1.      
    @ 1112   INCE_1D                                 1.      
    @ 1113   INCE_1E                                 1.      
    @ 1114   INCE_1F                                 1.      
    @ 1115   INCE_1G                                 1.      
    @ 1116   INCE_1H                                 1.      
    @ 1117   INCE_1I                                 1.      
    @ 1118   INCE_1J                                 1.      
    @ 1119   INCE_1K                                 1.      
    @ 1120   INCE_1L                                 1.      
    @ 1121   INCE_1M                                 1.      
    @ 1122   INCE_1N                                 1.      
    @ 1123   INCE_2                                  2.      
    @ 1125   INCE_3                                  6.      
    @ 1131   INCE_3A                                 1.      
    @ 1132   INCE_3B                                 1.      
    @ 1133   INCE_3C                                 1.      
    @ 1134   INCE_3D                                 1.      
    @ 1135   INCE_3E                                 1.      
    @ 1136   INCE_3F                                 1.      
    @ 1137   INCE_3G                                 1.      
    @ 1138   INCE_4                                  6.      
    @ 1144   INCE_4A                                 1.      
    @ 1145   INCE_4B                                 1.      
    @ 1146   INCE_4C                                 1.      
    @ 1147   INCE_4D                                 1.      
    @ 1148   INCE_4E                                 1.      
    @ 1149   INCE_4F                                 1.      
    @ 1150   INCE_4G                                 1.      
    @ 1151   INCEDHH                                 2.      
    @ 1153   INCEDPER                                2.      
    @ 1155   INCEDADR                               11.9     
    @ 1166   INCEDRCA                                2.      
    @ 1168   INCEDRPR                                2.      
    @ 1170   INCEDRRS                                2.      
    @ 1172   MHWZ_N1                                 1.      
    @ 1173   MHWZ_N1A                                1.      
    @ 1174   MHWZ_N1B                                1.      
    @ 1175   MHWZ_N1C                                1.      
    @ 1176   MHWZ_N1D                                1.      
    @ 1177   MHWZ_N1E                                1.      
    @ 1178   MHWZ_N1F                                1.      
    @ 1179   MHWZ_N1G                                1.      
    @ 1180   MHWZ_2                                  1.      
    @ 1181   MHWZ_N2                                 6.2     
    @ 1187   MHWZ_N3                                 1.      
    @ 1188   MHWZ_N3A                                1.      
    @ 1189   MHWZ_N3B                                1.      
    @ 1190   MHWZ_N3C                                1.      
    @ 1191   MHWZ_N3D                                1.      
    @ 1192   MHWZ_N4                                 1.      
    @ 1193   MHWZ_N5                                 1.      
    @ 1194   MHWZ_N5A                                1.      
    @ 1195   MHWZ_N5B                                1.      
    @ 1196   MHWZ_N5C                                1.      
    @ 1197   MHWZ_N5D                                1.      
    @ 1198   MHWZ_N5E                                1.      
    @ 1199   MHWZ_6                                  1.      
    @ 1200   MHWZ_N6                                 6.2     
    @ 1206   MHWZ_N7                                 1.      
    @ 1207   MHWZ_N7A                                1.      
    @ 1208   MHWZ_N7B                                1.      
    @ 1209   MHWZ_N7C                                1.      
    @ 1210   MHWZ_N7D                                1.      
    @ 1211   MHWZDHTM                                5.3     
    @ 1216   MHWZDWTK                                6.2     
    @ 1222   MHWZDBMI                                6.2     
    @ 1228   MHWZDISW                                2.      
    @ 1230   MHWZDCOL                                1.      
    @ 1231   WTSE_S2S                                8.2     
    @ 1239   WTSE_S2M                                8.2     
         ;
