 format
    GEOE_PRV    PROVFM.  
    GEOEDHR4    GEOE_4HR.
    GEOEDSHR    GEOESHR. 
    GEOEDLHN    GEOLHIN. 
    GEOEDSAT    GEOSATFM.
    GEOEDCMA    DVDCMA.  
    GEOEDPRG    GEO_PRG. 
    GEOEDUR7    GEODUR7F.
    GEOEDUR2    GEO_2UR. 
    SAME_CP    $SAM_CP.  
    SAME_TYP    SAME_TYP.
    SAMEDSHR    YESNOFM. 
    SAMEDLNK    YESNOFM. 
    ADME_STA    ADM_STA. 
    ADME_PRX    YESNOFM. 
    ADME_YOI    YEARFM.  
    ADME_MOI    MONTHFM. 
    ADME_DOI    DAYFM.   
    ADME_N09    TELFM.   
    ADME_N10    YESNOFM. 
    ADME_N11    YESNOFM. 
    ADME_N12    ADM_LNG. 
    ADME_LHH    AM3_LP.  
    DHHE_AGE    AGE3DFM. 
    DHHE_YOB    YEARFM.  
    DHHE_MOB    MONTHFM. 
    DHHE_DOB    DAYFM.   
    DHHE_SEX    DHC_SEX. 
    DHHE_MS     DHC_MAR. 
    GENE_01     GOOD5FM. 
    GENE_02     GEN_2F.  
    GENE_02A    SCR_01FM.
    GENE_02B    GOOD5FM. 
    GENE_07     STC_1F.  
    GENE_08     YESNOFM. 
    GENE_09     STC_1F.  
    GENE_10     GEN_10F. 
    GENEDHDI    GHCDHDI. 
    GENEDMHI    GHCDHDI. 
    HWTE_2      HWC_2FM. 
    HWTE_2A     HWC_2A.  
    HWTE_2B     HWC_2B.  
    HWTE_2C     HWC_2C.  
    HWTE_2D     HWC_2D.  
    HWTE_2E     HWC_2E.  
    HWTE_2F     HWC_2F.  
    HWTE_3      HWT_FM.  
    HWTE_N4     WHTFM.   
    HWTE_4      HWS_1F.  
    HWTEDHTM    HWT_METR.
    HWTEDWTK    HWT_WTK. 
    HWTEDBMI    HWTD_BMI.
    HWTEDISW    HWTCDISW.
    HWTEDCOL    HWTDDCOL.
    CCCE_011    YESNOFM. 
    CCCE_021    YESNOFM. 
    CCCE_031    YESNOFM. 
    CCCE_035    YESNOFM. 
    CCCE_036    YESNOFM. 
    CCCE_041    YESNOFM. 
    CCCE_051    YESNOFM. 
    CCCE_05A    CCC_05A. 
    CCCE_061    YESNOFM. 
    CCCE_071    YESNOFM. 
    CCCE_072    YESNOFM. 
    CCCE_073    YESNOFM. 
    CCCE_074    YESNOFM. 
    CCCE_75A    YESNOFM. 
    CCCE_75B    YESNOFM. 
    CCCE_75C    YESNOFM. 
    CCCE_75D    YESNOFM. 
    CCCE_081    YESNOFM. 
    CCCE_91A    YESNOFM. 
    CCCE_91E    YESNOFM. 
    CCCE_91F    YESNOFM. 
    CCCE_101    YESNOFM. 
    CCCE_102    AGE3DFM. 
    CCCE_10A    YESNOFM. 
    CCCE_10B    YESNOFM. 
    CCCE_10C    CCC_10C. 
    CCCE_105    YESNOFM. 
    CCCE_106    YESNOFM. 
    CCCE_111    YESNOFM. 
    CCCE_121    YESNOFM. 
    CCCE_131    YESNOFM. 
    CCCE_31A    YESNOFM. 
    CCCE_13A    YESNOFM. 
    CCCE_13B    YESNOFM. 
    CCCE_13C    YESNOFM. 
    CCCE_13D    YESNOFM. 
    CCCE_13E    YESNOFM. 
    CCCE_13F    YESNOFM. 
    CCCE_141    YESNOFM. 
    CCCE_151    YESNOFM. 
    CCCE_161    YESNOFM. 
    CCCE_171    YESNOFM. 
    CCCE_17A    CCC17AFM.
    CCCE_181    YESNOFM. 
    CCCE_191    YESNOFM. 
    CCCE_201    YESNOFM. 
    CCCE_211    YESNOFM. 
    CCCE_251    YESNOFM. 
    CCCE_261    YESNOFM. 
    CCCE_271    YESNOFM. 
    CCCE_280    YESNOFM. 
    CCCE_290    YESNOFM. 
    CCCE_321    YESNOFM. 
    CCCE_331    YESNOFM. 
    CCCE_33A    YESNOFM. 
    CCCE_33B    YESNOFM. 
    CCCE_33C    YESNOFM. 
    CCCE_33D    YESNOFM. 
    CCCE_341    YESNOFM. 
    CCCE_901    YESNOFM. 
    CCCEF1      YESNOFM. 
    HCUE_1AA    YESNOFM. 
    HCUE_1BA    YESNOFM. 
    HCUE_1BB    YESNOFM. 
    HCUE_1BC    YESNOFM. 
    HCUE_1BD    YESNOFM. 
    HCUE_1BE    YESNOFM. 
    HCUE_1AC    ADM_LN2G.
    HCUE_01     YESNOFM. 
    HCUE_01A    NIGHT3D. 
    HCUE_02A    TIMES3D. 
    HCUE_02B    TIMES2D. 
    HCUE_02C    TIMES3D. 
    HCUE_02D    TIMES3D. 
    HCUE_02E    TIMES3D. 
    HCUE_02F    TIMES3D. 
    HCUE_02G    TIMES3D. 
    HCUE_02H    TIMES3D. 
    HCUE_02I    TIMES3D. 
    HCUE_02J    TIMES3D. 
    HCUE_03A    HCC_CONT.
    HCUE_3A1    HCUE31FM.
    HCUE_03C    HCC_CONT.
    HCUE_3C1    HCUE31FM.
    HCUE_03D    HCC_CONT.
    HCUE_3D1    HCUE31FM.
    HCUE_04A    YESNOFM. 
    HCUE_04     YESNOFM. 
    HCUE_05A    YESNOFM. 
    HCUE_05B    YESNOFM. 
    HCUE_05C    YESNOFM. 
    HCUE_05D    YESNOFM. 
    HCUE_05E    YESNOFM. 
    HCUE_05F    YESNOFM. 
    HCUE_05G    YESNOFM. 
    HCUE_05H    YESNOFM. 
    HCUE_05I    YESNOFM. 
    HCUE_05J    YESNOFM. 
    HCUE_05K    YESNOFM. 
    HCUE_05L    YESNOFM. 
    HCUE_06     YESNOFM. 
    HCUE_07A    YESNOFM. 
    HCUE_07B    YESNOFM. 
    HCUE_07C    YESNOFM. 
    HCUE_07D    YESNOFM. 
    HCUE_07E    YESNOFM. 
    HCUE_07F    YESNOFM. 
    HCUE_07G    YESNOFM. 
    HCUE_07H    YESNOFM. 
    HCUE_07I    YESNOFM. 
    HCUE_07J    YESNOFM. 
    HCUE_07K    YESNOFM. 
    HCUE_07L    YESNOFM. 
    HCUE_07M    YESNOFM. 
    HCUE_07O    YESNOFM. 
    HCUE_07P    YESNOFM. 
    HCUE_07N    YESNOFM. 
    HCUE_08A    YESNOFM. 
    HCUE_08B    YESNOFM. 
    HCUE_08C    YESNOFM. 
    HCUE_08D    YESNOFM. 
    HCUE_08E    YESNOFM. 
    HCUE_09A    YESNOFM. 
    HCUE_09B    YESNOFM. 
    HCUE_09C    YESNOFM. 
    HCUE_09D    YESNOFM. 
    HCUE_09E    YESNOFM. 
    HCUE_09F    YESNOFM. 
    HCUE_09G    YESNOFM. 
    HCUE_09H    YESNOFM. 
    HCUEDMDC    CON3DFM. 
    HCUEFCOP    YESNOFM. 
    HMCE_09     YESNOFM. 
    HMCE_10A    YESNOFM. 
    HMCE_10B    YESNOFM. 
    HMCE_10C    YESNOFM. 
    HMCE_10D    YESNOFM. 
    HMCE_10E    YESNOFM. 
    HMCE_10F    YESNOFM. 
    HMCE_10G    YESNOFM. 
    HMCE_10H    YESNOFM. 
    HMCE_10I    YESNOFM. 
    HMCE_11     YESNOFM. 
    HMCE_12A    YESNOFM. 
    HMCE_12B    YESNOFM. 
    HMCE_12G    YESNOFM. 
    HMCE_12C    YESNOFM. 
    HMCE_12D    YESNOFM. 
    HMCE_12E    YESNOFM. 
    HMCE_12F    YESNOFM. 
    HMCE_3AA    YESNOFM. 
    HMCE_3AB    YESNOFM. 
    HMCE_3AI    YESNOFM. 
    HMCE_3AC    YESNOFM. 
    HMCE_3AD    YESNOFM. 
    HMCE_3AE    YESNOFM. 
    HMCE_3AF    YESNOFM. 
    HMCE_3AG    YESNOFM. 
    HMCE_3AH    YESNOFM. 
    HMCE_3BA    YESNOFM. 
    HMCE_3BB    YESNOFM. 
    HMCE_3BI    YESNOFM. 
    HMCE_3BC    YESNOFM. 
    HMCE_3BD    YESNOFM. 
    HMCE_3BE    YESNOFM. 
    HMCE_3BF    YESNOFM. 
    HMCE_3BG    YESNOFM. 
    HMCE_3BH    YESNOFM. 
    HMCE_3GA    YESNOFM. 
    HMCE_3GB    YESNOFM. 
    HMCE_3GI    YESNOFM. 
    HMCE_3GC    YESNOFM. 
    HMCE_3GD    YESNOFM. 
    HMCE_3GE    YESNOFM. 
    HMCE_3GF    YESNOFM. 
    HMCE_3GG    YESNOFM. 
    HMCE_3GH    YESNOFM. 
    HMCE_3CA    YESNOFM. 
    HMCE_3CB    YESNOFM. 
    HMCE_3CI    YESNOFM. 
    HMCE_3CC    YESNOFM. 
    HMCE_3CD    YESNOFM. 
    HMCE_3CE    YESNOFM. 
    HMCE_3CF    YESNOFM. 
    HMCE_3CG    YESNOFM. 
    HMCE_3CH    YESNOFM. 
    HMCE_3DA    YESNOFM. 
    HMCE_3DB    YESNOFM. 
    HMCE_3DI    YESNOFM. 
    HMCE_3DC    YESNOFM. 
    HMCE_3DD    YESNOFM. 
    HMCE_3DE    YESNOFM. 
    HMCE_3DF    YESNOFM. 
    HMCE_3DG    YESNOFM. 
    HMCE_3DH    YESNOFM. 
    HMCE_3EA    YESNOFM. 
    HMCE_3EB    YESNOFM. 
    HMCE_3EI    YESNOFM. 
    HMCE_3EC    YESNOFM. 
    HMCE_3ED    YESNOFM. 
    HMCE_3EE    YESNOFM. 
    HMCE_3EF    YESNOFM. 
    HMCE_3EG    YESNOFM. 
    HMCE_3EH    YESNOFM. 
    HMCE_3FA    YESNOFM. 
    HMCE_3FB    YESNOFM. 
    HMCE_3FI    YESNOFM. 
    HMCE_3FC    YESNOFM. 
    HMCE_3FD    YESNOFM. 
    HMCE_3FE    YESNOFM. 
    HMCE_3FF    YESNOFM. 
    HMCE_3FG    YESNOFM. 
    HMCE_3FH    YESNOFM. 
    HMCE_14     YESNOFM. 
    HMCE_15A    YESNOFM. 
    HMCE_15B    YESNOFM. 
    HMCE_15C    YESNOFM. 
    HMCE_15D    YESNOFM. 
    HMCE_15E    YESNOFM. 
    HMCE_15F    YESNOFM. 
    HMCE_15G    YESNOFM. 
    HMCE_15H    YESNOFM. 
    HMCE_15I    YESNOFM. 
    HMCE_15J    YESNOFM. 
    HMCE_15K    YESNOFM. 
    HMCE_15L    YESNOFM. 
    HMCE_15M    YESNOFM. 
    HMCE_15N    YESNOFM. 
    HMCE_15O    YESNOFM. 
    HMCE_16A    YESNOFM. 
    HMCE_16B    YESNOFM. 
    HMCE_16C    YESNOFM. 
    HMCE_16D    YESNOFM. 
    HMCE_16E    YESNOFM. 
    HMCE_16F    YESNOFM. 
    HMCE_16G    YESNOFM. 
    HMCE_16H    YESNOFM. 
    HMCE_16I    YESNOFM. 
    HMCE_17A    YESNOFM. 
    HMCE_17B    YESNOFM. 
    HMCE_17C    YESNOFM. 
    HMCE_17D    YESNOFM. 
    HMCE_17E    YESNOFM. 
    HMCEFRHC    YESNOFM. 
    RACE_1      RAC2BFM. 
    RACE_2A     RAC2BFM. 
    RACE_2B1    RAC2B1FM.
    RACE_2B2    RAC2B2FM.
    RACE_2C     RAC2BFM. 
    RACE_5      RAC_5FM. 
    RACE_5B1    YESNOFM. 
    RACE_5B2    RAC5B2F. 
    RACE_6A     YESNOFM. 
    RACE_6B1    YESNOFM. 
    RACE_6C     YESNOFM. 
    RACE_6D     YESNOFM. 
    RACE_6E     YESNOFM. 
    RACE_6F     YESNOFM. 
    RACE_6G     YESNOFM. 
    RACE_7A     YESNOFM. 
    RACE_7B     YESNOFM. 
    RACE_7C     YESNOFM. 
    RACE_8A     YESNOFM. 
    RACE_8B     YESNOFM. 
    RACE_8C     YESNOFM. 
    RACE_8D     YESNOFM. 
    RACEDIMP    SOMETIME.
    RACEDPAL    SOMETIME.
    RACEF6R     YESNOFM. 
    RACEF7      YESNOFM. 
    TWDE_1      YESNOFM. 
    TWDE_2      TWC_NUM. 
    TWDE_2A     YESNOFM. 
    TWDE_2B     TWC_NUM. 
    TWDE_3      YESNOFM. 
    TWDE_4      TWC_NUM. 
    TWDE_4A     YESNOFM. 
    TWDE_4B     TWC_NUM. 
    TWDE_5A     YESNOFM. 
    TWDE_6      TWC_NUM. 
    TWDE_6A     YESNOFM. 
    TWDE_6B     TWC_NUM. 
    TWDEDDDY    TWC_NUM. 
    TWDEDDDM    TWC_NUM. 
    TWDEDDDP    TWC_NUM. 
    FLUE_160    YESNOFM. 
    FLUE_162    FS52F.   
    FLUE_66A    YESNOFM. 
    FLUE_66B    YESNOFM. 
    FLUE_66C    YESNOFM. 
    FLUE_66D    YESNOFM. 
    FLUE_66E    YESNOFM. 
    FLUE_66F    YESNOFM. 
    FLUE_66G    YESNOFM. 
    FLUE_66H    YESNOFM. 
    FLUE_66I    YESNOFM. 
    FLUE_66J    YESNOFM. 
    FLUE_66K    YESNOFM. 
    FLUE_66L    YESNOFM. 
    FLUE_66M    YESNOFM. 
    FLUE_66O    YESNOFM. 
    FLUE_66N    YESNOFM. 
    PAPE_020    YESNOFM. 
    PAPE_022    WHC_22F. 
    PAPE_26A    YESNOFM. 
    PAPE_26B    YESNOFM. 
    PAPE_26C    YESNOFM. 
    PAPE_26D    YESNOFM. 
    PAPE_26E    YESNOFM. 
    PAPE_26F    YESNOFM. 
    PAPE_26G    YESNOFM. 
    PAPE_26H    YESNOFM. 
    PAPE_26I    YESNOFM. 
    PAPE_26J    YESNOFM. 
    PAPE_26K    YESNOFM. 
    PAPE_26L    YESNOFM. 
    PAPE_26M    YESNOFM. 
    PAPE_26N    YESNOFM. 
    PAPE_26P    YESNOFM. 
    PAPE_26O    YESNOFM. 
    MAME_030    YESNOFM. 
    MAME_31A    YESNOFM. 
    MAME_31B    YESNOFM. 
    MAME_31C    YESNOFM. 
    MAME_31D    YESNOFM. 
    MAME_31E    YESNOFM. 
    MAME_31F    YESNOFM. 
    MAME_31G    YESNOFM. 
    MAME_31H    YESNOFM. 
    MAME_032    WH2_LAST.
    MAME_36A    YESNOFM. 
    MAME_36B    YESNOFM. 
    MAME_36C    YESNOFM. 
    MAME_36D    YESNOFM. 
    MAME_36E    YESNOFM. 
    MAME_36F    YESNOFM. 
    MAME_36G    YESNOFM. 
    MAME_36H    YESNOFM. 
    MAME_36I    YESNOFM. 
    MAME_36J    YESNOFM. 
    MAME_36K    YESNOFM. 
    MAME_36L    YESNOFM. 
    MAME_36M    YESNOFM. 
    MAME_36N    YESNOFM. 
    MAME_36O    YESNOFM. 
    MAME_037    YESNOFM. 
    MAME_038    YESNOFM. 
    PACE_1A     YESNOFM. 
    PACE_1B     YESNOFM. 
    PACE_1C     YESNOFM. 
    PACE_1D     YESNOFM. 
    PACE_1E     YESNOFM. 
    PACE_1F     YESNOFM. 
    PACE_1G     YESNOFM. 
    PACE_1H     YESNOFM. 
    PACE_1I     YESNOFM. 
    PACE_1J     YESNOFM. 
    PACE_1K     YESNOFM. 
    PACE_1L     YESNOFM. 
    PACE_1M     YESNOFM. 
    PACE_1N     YESNOFM. 
    PACE_1O     YESNOFM. 
    PACE_1P     YESNOFM. 
    PACE_1Q     YESNOFM. 
    PACE_1R     YESNOFM. 
    PACE_1S     YESNOFM. 
    PACE_1T     YESNOFM. 
    PACE_1Z     YESNOFM. 
    PACE_1U     YESNOFM. 
    PACE_1V     YESNOFM. 
    PACE_1W     YESNOFM. 
    PACE_1X     YESNOFM. 
    PACE_2A     TIMES3D. 
    PACE_3A     PAC_TIME.
    PACE_2B     TIMES3D. 
    PACE_3B     PAC_TIME.
    PACE_2C     TIMES3D. 
    PACE_3C     PAC_TIME.
    PACE_2D     TIMES3D. 
    PACE_3D     PAC_TIME.
    PACE_2E     TIMES3D. 
    PACE_3E     PAC_TIME.
    PACE_2F     TIMES3D. 
    PACE_3F     PAC_TIME.
    PACE_2G     TIMES3D. 
    PACE_3G     PAC_TIME.
    PACE_2H     TIMES3D. 
    PACE_3H     PAC_TIME.
    PACE_2I     TIMES3D. 
    PACE_3I     PAC_TIME.
    PACE_2J     TIMES3D. 
    PACE_3J     PAC_TIME.
    PACE_2K     TIMES3D. 
    PACE_3K     PAC_TIME.
    PACE_2L     TIMES3D. 
    PACE_3L     PAC_TIME.
    PACE_2M     TIMES3D. 
    PACE_3M     PAC_TIME.
    PACE_2N     TIMES3D. 
    PACE_3N     PAC_TIME.
    PACE_2O     TIMES3D. 
    PACE_3O     PAC_TIME.
    PACE_2P     TIMES3D. 
    PACE_3P     PAC_TIME.
    PACE_2Q     TIMES3D. 
    PACE_3Q     PAC_TIME.
    PACE_2R     TIMES3D. 
    PACE_3R     PAC_TIME.
    PACE_2S     TIMES3D. 
    PACE_3S     PAC_TIME.
    PACE_2T     TIMES3D. 
    PACE_3T     PAC_TIME.
    PACE_2Z     TIMES3D. 
    PACE_3Z     PAC_TIME.
    PACE_2U     TIMES3D. 
    PACE_3U     PAC_TIME.
    PACE_2W     TIMES3D. 
    PACE_3W     PAC_TIME.
    PACE_2X     TIMES3D. 
    PACE_3X     PAC_TIME.
    PACE_4A     PACHOURS.
    PACE_4B     PACHOURS.
    PACE_6      PAC_6F.  
    PACEDEE     PACDEE.  
    PACEFLEI    YESNOFM. 
    PACEDFM     PACDFM.  
    PACEDFR     PACDFR.  
    PACEFD      YESNOFM. 
    PACEDPAI    PACDPAI. 
    SMKE_01A    YESNOFM. 
    SMKE_01B    YESNOFM. 
    SMKE_01C    AGE3DFM. 
    SMKE_202    SMC_2F.  
    SMKE_203    AGE3DFM. 
    SMKE_204    CIG_NUM. 
    SMKE_05B    CIG_NUM. 
    SMKE_05C    DAY2DFM. 
    SMKE_05D    YESNOFM. 
    SMKE_06A    SMKCFM.  
    SMKE_06B    MONTHFM. 
    SMKE_06C    YEAR3NUM.
    SMKE_207    AGE3DFM. 
    SMKE_208    CIG_NUM. 
    SMKE_09A    SMKCFM.  
    SMKE_09B    MONTHFM. 
    SMKE_09C    YEAR3NUM.
    SMKE_10     YESNOFM. 
    SMKE_10A    SMKCFM.  
    SMKE_10B    MONTHFM. 
    SMKE_10C    YEAR3NUM.
    SMKEDSTY    SMCDTYP. 
    SMKEDSTP    YEAR3NUM.
    SMKEDYCS    SMCDYRS. 
    YSME_1      SMK_300F.
    YSME_2      YESNOFM. 
    YSME_3      YESNOFM. 
    YSME_4      YESNOFM. 
    YSME_5      YESNOFM. 
    ETSE_10     YESNOFM. 
    ETSE_11     PERS2D.  
    ETSE_20     YESNOFM. 
    ETSE_20B    YESNOFM. 
    ETSE_5      YESNOFM. 
    ETSE_6A     YESNOFM. 
    ETSE_6B     YESNOFM. 
    ETSE_6C     YESNOFM. 
    ETSE_6D     YESNOFM. 
    ALCE_1      YESNOFM. 
    ALCE_2      ALC6_2F. 
    ALCE_3      ALC_3F.  
    ALCE_5      YESNOFM. 
    ALCE_5A1    ALC_NUM. 
    ALCE_5A2    ALC_NUM. 
    ALCE_5A3    ALC_NUM. 
    ALCE_5A4    ALC_NUM. 
    ALCE_5A5    ALC_NUM. 
    ALCE_5A6    ALC_NUM. 
    ALCE_5A7    ALC_NUM. 
    ALCE_5B     YESNOFM. 
    ALCE_6      YESNOFM. 
    ALCE_7A     YESNOFM. 
    ALCE_7B     YESNOFM. 
    ALCE_7C     YESNOFM. 
    ALCE_7D     YESNOFM. 
    ALCE_7E     YESNOFM. 
    ALCE_7F     YESNOFM. 
    ALCE_7G     YESNOFM. 
    ALCE_7H     YESNOFM. 
    ALCE_7I     YESNOFM. 
    ALCE_7J     YESNOFM. 
    ALCE_7K     YESNOFM. 
    ALCE_7L     YESNOFM. 
    ALCE_7M     YESNOFM. 
    ALCE_7N     YESNOFM. 
    ALCE_8      AGE3DFM. 
    ALCEDTYP    ALCDTYP. 
    ALCEDDLY    ALC_NUM. 
    ALCEDWKY    ALC_NUM. 
    MEXE_01     YESNOFM. 
    MEXE_01A    YEARFM.  
    MEXE_02     YESNOFM. 
    MEXE_03     YESNOFM. 
    MEXE_04     MEXE4FM. 
    MEXE_05     YESNOFM. 
    MEXE_06     MEXE06FM.
    MEXE_07     MEXE07FM.
    MEXE_08     MEXE8FM. 
    MEXE_09     YESNOFM. 
    MEXE_10     MEXE0FM. 
    MEXE_20     SMC_2F.  
    MEXE_21     CIG_NUM. 
    MEXE_22     CIG_NUM. 
    MEXE_23     SMC_2F.  
    MEXE_24     CIG_NUM. 
    MEXE_25     CIG_NUM. 
    MEXE_26     YESNOFM. 
    MEXE_30     YESNOFM. 
    MEXE_31     ALC6_2F. 
    MEXE_32     YESNOFM. 
    MEXE_33     ALC6_2F. 
    MEXEDEBF    MEXCDEFM.
    MEXEFEB4    YESNOFM. 
    REPE_1      YESNOFM. 
    REPE_3      RPC03FM. 
    REPE_4A     YESNOFM. 
    REPE_4B     YESNOFM. 
    REPE_4C     YESNOFM. 
    REPE_4G     YESNOFM. 
    REPE_4D     YESNOFM. 
    REPE_4E     YESNOFM. 
    REPE_4F     YESNOFM. 
    INJE_01     YESNOFM. 
    INJE_02     IJC_2F.  
    INJE_03     MONTHFM. 
    INJE_04     INJ_4F.  
    INJE_05     IJC03F.  
    INJE_06     IJC04F.  
    INJE_07     IJC_4A.  
    INJE_08     IJC05F.  
    INJE_09     IJC_9F.  
    INJE_10     YESNOFM. 
    INJE_11     IJC_10A. 
    INJE_12     IJC_10B. 
    INJE_13     YESNOFM. 
    INJE_14A    YESNOFM. 
    INJE_14B    YESNOFM. 
    INJE_14C    YESNOFM. 
    INJE_14D    YESNOFM. 
    INJE_14E    YESNOFM. 
    INJE_14F    YESNOFM. 
    INJE_14G    YESNOFM. 
    INJE_14H    YESNOFM. 
    INJE_14I    YESNOFM. 
    INJE_14J    YESNOFM. 
    INJE_14K    YESNOFM. 
    INJE_15     YESNOFM. 
    INJE_16     YESNOFM. 
    INJE_17     IJC_NUM. 
    INJEDTBS    INJ_TBS. 
    INJEDCAU    INJ_CAU. 
    INJEDCBP    IJCD2FM. 
    INJEDSTT    INJ_STT. 
    SXBE_1      YESNOFM. 
    SXBE_2      AGE3DFM. 
    SXBE_3      YESNOFM. 
    SXBE_4      SHS_4F.  
    SXBE_07     YESNOFM. 
    SXBE_7A     YESNOFM. 
    SXBE_09     AGREEFM. 
    SXBE_10     SXBC10FM.
    SXBE_11     YESNOFM. 
    SXBE_12A    YESNOFM. 
    SXBE_12B    YESNOFM. 
    SXBE_12C    YESNOFM. 
    SXBE_12D    YESNOFM. 
    SXBE_12F    YESNOFM. 
    SXBE_12E    YESNOFM. 
    SXBE_13A    YESNOFM. 
    SXBE_13B    YESNOFM. 
    SXBE_13C    YESNOFM. 
    SXBE_13D    YESNOFM. 
    SXBE_13E    YESNOFM. 
    SXBE_13F    YESNOFM. 
    SXBE_13G    YESNOFM. 
    LBSE_01     LSC_1F.  
    LBSE_02     YESNOFM. 
    LBSE_03     YESNOFM. 
    LBSE_11     YESNOFM. 
    LBSE_42     HOUR3DFM.
    ETSE_7      SMS_12F. 
    LBSE_53     HOUR3DFM.
    LBSEDHPW    LSCDHPW. 
    LBSEDPFT    LBF_PFT. 
    LBSEDWSS    LSCDCWS. 
    SDCEFPRD    YESNOFM. 
    SDCE_1      SDC_1FM. 
    SDCE_2      YESNOFM. 
    SDCE_3      SDYEARFM.
    SDCE_4A     YESNOFM. 
    SDCE_4B     YESNOFM. 
    SDCE_4C     YESNOFM. 
    SDCE_4D     YESNOFM. 
    SDCE_4E     YESNOFM. 
    SDCE_4F     YESNOFM. 
    SDCE_4G     YESNOFM. 
    SDCE_4H     YESNOFM. 
    SDCE_4I     YESNOFM. 
    SDCE_4J     YESNOFM. 
    SDCE_4K     YESNOFM. 
    SDCE_4L     YESNOFM. 
    SDCE_4M     YESNOFM. 
    SDCE_4N     YESNOFM. 
    SDCE_4T     YESNOFM. 
    SDCE_4U     YESNOFM. 
    SDCE_4V     YESNOFM. 
    SDCE_4P     YESNOFM. 
    SDCE_4Q     YESNOFM. 
    SDCE_4R     YESNOFM. 
    SDCE_4S     YESNOFM. 
    SDCE_41     YESNOFM. 
    SDCE_42A    YESNOFM. 
    SDCE_42B    YESNOFM. 
    SDCE_42C    YESNOFM. 
    SDCE_43A    YESNOFM. 
    SDCE_43B    YESNOFM. 
    SDCE_43C    YESNOFM. 
    SDCE_43D    YESNOFM. 
    SDCE_43E    YESNOFM. 
    SDCE_43F    YESNOFM. 
    SDCE_43G    YESNOFM. 
    SDCE_43H    YESNOFM. 
    SDCE_43I    YESNOFM. 
    SDCE_43J    YESNOFM. 
    SDCE_43K    YESNOFM. 
    SDCE_43M    YESNOFM. 
    SDCE_5A     YESNOFM. 
    SDCE_5B     YESNOFM. 
    SDCE_5C     YESNOFM. 
    SDCE_5D     YESNOFM. 
    SDCE_5E     YESNOFM. 
    SDCE_5F     YESNOFM. 
    SDCE_5G     YESNOFM. 
    SDCE_5H     YESNOFM. 
    SDCE_5I     YESNOFM. 
    SDCE_5J     YESNOFM. 
    SDCE_5K     YESNOFM. 
    SDCE_5L     YESNOFM. 
    SDCE_5M     YESNOFM. 
    SDCE_5N     YESNOFM. 
    SDCE_5O     YESNOFM. 
    SDCE_5P     YESNOFM. 
    SDCE_5Q     YESNOFM. 
    SDCE_5R     YESNOFM. 
    SDCE_5T     YESNOFM. 
    SDCE_5U     YESNOFM. 
    SDCE_5V     YESNOFM. 
    SDCE_5W     YESNOFM. 
    SDCE_5S     YESNOFM. 
    SDCE_5AA    ADM_LN2G.
    SDCE_6A     YESNOFM. 
    SDCE_6B     YESNOFM. 
    SDCE_6C     YESNOFM. 
    SDCE_6D     YESNOFM. 
    SDCE_6E     YESNOFM. 
    SDCE_6F     YESNOFM. 
    SDCE_6G     YESNOFM. 
    SDCE_6H     YESNOFM. 
    SDCE_6I     YESNOFM. 
    SDCE_6J     YESNOFM. 
    SDCE_6K     YESNOFM. 
    SDCE_6L     YESNOFM. 
    SDCE_6M     YESNOFM. 
    SDCE_6N     YESNOFM. 
    SDCE_6O     YESNOFM. 
    SDCE_6P     YESNOFM. 
    SDCE_6Q     YESNOFM. 
    SDCE_6R     YESNOFM. 
    SDCE_6T     YESNOFM. 
    SDCE_6U     YESNOFM. 
    SDCE_6V     YESNOFM. 
    SDCE_6W     YESNOFM. 
    SDCE_6S     YESNOFM. 
    SDCE_7A     YESNOFM. 
    SDCE_7B     YESNOFM. 
    SDCE_7C     YESNOFM. 
    SDCE_7D     YESNOFM. 
    SDCE_7E     YESNOFM. 
    SDCE_7F     YESNOFM. 
    SDCE_7G     YESNOFM. 
    SDCE_7H     YESNOFM. 
    SDCE_7I     YESNOFM. 
    SDCE_7J     YESNOFM. 
    SDCE_7K     YESNOFM. 
    SDCE_7L     YESNOFM. 
    SDCE_7M     YESNOFM. 
    SDCE_7BA    SDCE7BA. 
    SDCE_7AA    SDC7AFM. 
    SDCE_8      YESNOFM. 
    SDCE_9      EDC2FM.  
    SDCECCB     SDC_CB.  
    SDCEGCB     SDGCB7FM.
    SDCEDAIM    AGE3DFM. 
    SDCEFIMM    YESNOFM. 
    SDCEDRES    AGE3DFM. 
    SDCEFABT    SDC_ABO. 
    SDCEGCGT    SDCGRAC. 
    SDCEDCGT    SDC_CG.  
    SDCEDLNG    SDCDLNG. 
    SDCEDFL1    SDCDLNG. 
    EDUE_1      EDUGRADE.
    EDUE_2      YESNOFM. 
    EDUE_3      YESNOFM. 
    EDUE_4      EDUDEGRE.
    EDUEDH04    DVED3FM. 
    EDUEDH10    EDU_10DR.
    EDUEDR04    DVED3FM. 
    EDUEDR10    EDU_10DR.
    DHHEDHSZ    PERS2D.  
    DHHEDL12    PERS2D.  
    DHHEDLE5    PERS2D.  
    DHHED611    PERS2D.  
    DHHEDECF    DHCDECF. 
    DHHEDLVG    DHCDLVG. 
    DHHEDDWE    DHH_DWE. 
    DHHE_OWN    YESNOFM. 
    DHHE_BED    BED_NUM. 
    INCE_1A     YESNOFM. 
    INCE_1B     YESNOFM. 
    INCE_1C     YESNOFM. 
    INCE_1D     YESNOFM. 
    INCE_1E     YESNOFM. 
    INCE_1F     YESNOFM. 
    INCE_1G     YESNOFM. 
    INCE_1H     YESNOFM. 
    INCE_1I     YESNOFM. 
    INCE_1J     YESNOFM. 
    INCE_1K     YESNOFM. 
    INCE_1L     YESNOFM. 
    INCE_1M     YESNOFM. 
    INCE_1N     YESNOFM. 
    INCE_2      INC8_2F. 
    INCE_3      DOLL6FM. 
    INCE_3A     INC_3A.  
    INCE_3B     INC_3B.  
    INCE_3C     INC_3C.  
    INCE_3D     INC_3D.  
    INCE_3E     INC_3E.  
    INCE_3F     INC_3F.  
    INCE_3G     INC_3GFM.
    INCE_4      DOLL6FM. 
    INCE_4A     INC_3A.  
    INCE_4B     INC_3B.  
    INCE_4C     INC_3C.  
    INCE_4D     INC_3D.  
    INCE_4E     INC_3E.  
    INCE_4F     INC_3F.  
    INCE_4G     INC_3GFM.
    INCEDHH     INCDHHFM.
    INCEDPER    INCDHHFM.
    INCEDADR    INCRATFM.
    INCEDRCA    INCDECFM.
    INCEDRPR    INCDECFM.
    INCEDRRS    INCDECFM.
    MHWZ_N1     YESNOFM. 
    MHWZ_N1A    YESNOFM. 
    MHWZ_N1B    YESNOFM. 
    MHWZ_N1C    YESNOFM. 
    MHWZ_N1D    YESNOFM. 
    MHWZ_N1E    YESNOFM. 
    MHWZ_N1F    YESNOFM. 
    MHWZ_N1G    YESNOFM. 
    MHWZ_2      YESNOFM. 
    MHWZ_N2     MSWDFM.  
    MHWZ_N3     YESNOFM. 
    MHWZ_N3A    YESNOFM. 
    MHWZ_N3B    YESNOFM. 
    MHWZ_N3C    YESNOFM. 
    MHWZ_N3D    YESNOFM. 
    MHWZ_N4     MSWFM.   
    MHWZ_N5     YESNOFM. 
    MHWZ_N5A    YESNOFM. 
    MHWZ_N5B    YESNOFM. 
    MHWZ_N5C    YESNOFM. 
    MHWZ_N5D    YESNOFM. 
    MHWZ_N5E    YESNOFM. 
    MHWZ_6      YESNOFM. 
    MHWZ_N6     MSHEFM.  
    MHWZ_N7     YESNOFM. 
    MHWZ_N7A    YESNOFM. 
    MHWZ_N7B    YESNOFM. 
    MHWZ_N7C    YESNOFM. 
    MHWZ_N7D    YESNOFM. 
    MHWZDHTM    HWT_HTM. 
    MHWZDWTK    HWT_WTK. 
    MHWZDBMI    HWTD_BMI.
    MHWZDISW    HWTCDISW.
    MHWZDCOL    HWTDDCOL.
                       ;
