label variable VERDATE   "Date of file creation"
label variable REFPER    "Reference period"
label variable SAMPLEID  "Record identifier"
label variable INSTANCE  "Person identifier of selected respondent  - health interview"
label variable COLMODE   "Collection mode - 18+"
label variable COLMODEY  "Collection mode - 12-17 (youth respondents)"
label variable COLMODEP  "Collection mode - 12-17 (PMK respondents)"
label variable COL_LANG  "Collection language"
label variable GEO_PRV   "Province of residence of respondent"
label variable GEODVPC   "Postal code - (D)"
label variable GEODVD16  "2016 Census dissemination area (DA) - (D)"
label variable GEODVCSD  "2016 Census subdivision (CSD) - (D)"
label variable GEODVFED  "2016 Census federal electoral district (FED) - (D)"
label variable GEODVCD   "2016 Census division (CD) - (D)"
label variable GEODVCMA  "2016 Census metropolitan area (CMA) - (D)"
label variable GEODVCA   "2016 Census agglomeration (CA) - (D)"
label variable GEODVSAT  "Statistical area classification type (SAT) - (D)"
label variable GEODVHR4  "Health region - (D)"
label variable GEODVP16  "Peer group 2016 - (D)"
label variable GEODVUR   "Population centre or rural area type - (D)"
label variable GEODVUR2  "Population centre or rural area type - grouped - (D)"
label variable GEODVPSZ  "Population centre or rural area classification - (D)"
label variable GEODVBHA  "British Columbia Health Authority (BCHA) - (D)"
label variable GEODVHCS  "Ontario home and community care support services (HCCSS) - (D)"
label variable GEODVSHC  "Ontario HCCSS sub-region - (D)"
label variable GEODVASZ  "Alberta subzone - (D)"
label variable SAM_CP    "Sampled collection period"
label variable ADM_YOI   "Year of interview"
label variable ADM_MOI   "Month of interview"
label variable ADM_DOI   "Day of interview"
label variable SAMDVLNK  "Permission to link data - (D)"
label variable SAMDVSHR  "Permission to share data - (D)"
label variable DHHDVHSZ  "Household size - (D)"
label variable DHHDVLVG  "Living / family arrangement of selected respondent - (D)"
label variable DHHDV611  "Number of persons in household between 6 and 11 years of age - (D)"
label variable DHHDVOKD  "Number of persons in household 16 or 17 years of age - (D)"
label variable DHHDVL12  "Number of persons in household less than 12 years of age - (D)"
label variable DHHDVYKD  "Number of persons in household less than 16 years of age - (D)"
label variable DHHDVLE5  "Number of persons in household 5 years old or less - (D)"
label variable DHHDVA65  "Number of persons in household aged 65 and older - (D)"
label variable DHHDVAOS  "Age of spouse - (D)"
label variable DHHDVL18  "Number of persons in household less than 18 years of age - (D)"
label variable PROXYSEX  "Respondent gender and whether interview conducted by proxy"
label variable DWL_01A   "Dwelling ownership - own or rent"
label variable ED_05     "Highest certificate, diploma or degree completed"
label variable EDDVR3    "Highest level of education - respondent, 3 levels - (D)"
label variable EDDVH3    "Highest level of education - household, 3 levels - (D)"
label variable AGE_01A   "Year of birth"
label variable AGE_01B   "Month of birth"
label variable AGE_01C   "Day of birth"
label variable AWCAGE    "Age"
label variable DHH_SEX   "Sex at birth"
label variable GDRA_10   "Gender"
label variable GENDER_2  "Gender - imputed"
label variable DOMAC     "Main activity (1) - Inclusion Flag - (F)"
label variable MAC_05    "Main activity - worked at job / business - 12 mo"
label variable MA_02     "Main activity - 12 mo"
label variable MA_03     "Worked at job / business - 7 d"
label variable DOEDC     "School attendance - Inclusion Flag - (F)"
label variable EDC_10    "Currently attending school / college / CEGEP / university"
label variable EDC_20    "Student status"
label variable DOGEN     "General health - Inclusion Flag - (F)"
label variable GEN_01    "Perceived health"
label variable GEN_05    "Perceived mental health"
label variable GEN_10    "Perceived life stress"
label variable GEN_15    "Perceived stress at work"
label variable GEN_20    "Sense of belonging to local community"
label variable DOLSM     "Life satisfaction measures - Inclusion Flag - (F)"
label variable LSM_01    "Satisfaction with life in general"
label variable LSMDVSWL  "Satisfaction with life in general (D)"
label variable DOPRS     "Pregnancy - Inclusion Flag - (F)"
label variable PRS_05    "Currently pregnant"
label variable DOHWT     "Height and weight - Inclusion Flag - (F)"
label variable HWT_05A   "Height (self-reported) - Feet"
label variable HWT_05B   "Height (self-reported) - Inches"
label variable HWT_05C   "Height (self-reported) - Centimetres"
label variable HWT_40A   "Weight (self-reported)"
label variable HWT_40B   "Weight (self-reported) - unit of measure in pounds or kilograms"
label variable HWTDVHTM  "Height (metres) - self-reported - (D)"
label variable HWTDVWTK  "Weight (kilograms) - self-reported - (D)"
label variable HWTDVBMI  "Body mass index (self-reported) - (D)"
label variable HWTDVCOL  "BMI classification age 12 to 17 (self-reported) - Cole - (D)"
label variable HWTDVISW  "BMI classification age 18 + (self-reported) - Intl standard - (D)"
label variable HWTDVWHO  "BMI classification age 12 to 17 (self-reported) - WHO - (D)"
label variable HWTDVCOR  "Body mass index (adjusted) - (D)"
label variable HWTDVBCC  "BMI classification age 18 + (adjusted) - Intl standard - (D)"
label variable DOWTP     "Weight perception - Inclusion Flag - (F)"
label variable WTP_50    "Self-perceived weight - overweight / underweight / just about right"
label variable DOCOV2    "COVID-19 (2) - Inclusion Flag - (F)"
label variable COV2_005  "Self-perceived mental health - before / during pandemic"
label variable COV2_10A  "COVID-19 precautions - washes hands more frequently"
label variable COV2_10B  "COVID-19 precautions - wears a mask in public places"
label variable COV2_10C  "COVID-19 precautions - keeps a 2 m / 6 ft distance from others"
label variable COV2_10D  "COVID-19 precautions - avoids crowds / large gatherings"
label variable COV2_10E  "COVID-19 precautions - avoids leaving house for non-essential reasons"
label variable COV2_10F  "COVID-19 precautions - works from home"
label variable COV2_10G  "COVID-19 precautions - uses delivery / curb side pick-up services"
label variable COV2_10H  "COVID-19 precautions - self-isolates if symptoms"
label variable COV2_10I  "COVID-19 precautions - other precaution"
label variable COV2_10J  "COVID-19 precautions - no precautions taken"
label variable COV2_015  "Has experienced COVID-19 symptoms - last 3 months"
label variable COV2_020  "Followed public health recommendations while COVID-19 symptoms"
label variable COV2_038  "Received COVID-19 vaccine"
label variable COV2_030  "COVID-19 vaccine - requires 1 or 2 doses"
label variable COV2_035  "COVID-19 vaccine - number of doses received so far"
label variable COV2_041  "COVID-19 vaccine - main reason why not vaccinated"
label variable COV2_45A  "COVID-19 vaccine - reasons don't want - not at high risk"
label variable COV2_45B  "COVID-19 vaccine - reasons don't want - won't be very sick"
label variable COV2_45C  "COVID-19 vaccine - reasons don't want - pandemic severity overstated"
label variable COV2_45D  "COVID-19 vaccine - reasons don't want - vaccines are not effective"
label variable COV2_45E  "COVID-19 vaccine - reasons don't want - vaccines are not safe"
label variable COV2_45F  "COVID-19 vaccine - reasons don't want - don't trust its effectiveness"
label variable COV2_45G  "COVID-19 vaccine - reasons don't want - don't trust its safety"
label variable COV2_45H  "COVID-19 vaccine - reasons don't want -  philosophical / religious"
label variable COV2_45I  "COVID-19 vaccine - reasons don't want - other reason"
label variable COV2_040  "COVID-19 vaccine - likeliness of getting it"
label variable COV2_55A  "COVID-19 vaccine - main reason for not getting second dose"
label variable COV2_060  "COVID-19 vaccine - likeliness of getting 2nd dose"
label variable DOCOV3    "COVID-19 (3) - Inclusion Flag - (F)"
label variable COV3_005  "COVID-19 vaccine - likeliness of getting additional dose if offered"
label variable DOCCC     "Chronic conditions - Inclusion Flag - (F)"
label variable CCC_05    "Has diabetes"
label variable CCC_10    "Diabetes - age first diagnosed"
label variable CCC_15    "Diabetes - diagnosed - during pregnancy"
label variable CCC_20    "Diabetes - diagnosed - other than during pregnancy"
label variable CCC_30    "Diabetes - time between diagnosis and start of insulin"
label variable CCC_35    "Diabetes - currently takes insulin"
label variable CCC_40    "Diabetes - took pills to control blood sugar - 1 mo"
label variable CCC_45    "Has been diagnosed with cancer - lifetime"
label variable CCC_50    "Cancer - age first diagnosed"
label variable CCC_55    "Cancer - received treatment - 12 mo"
label variable CCC_60A   "Type of cancer - breast"
label variable CCC_65A   "Type of cancer - prostate"
label variable CCC_60B   "Type of cancer - colorectal"
label variable CCC_60C   "Type of cancer - skin - melanoma"
label variable CCC_60D   "Type of cancer - skin - non-melanoma"
label variable CCC_60E   "Type of cancer - ovarian"
label variable CCC_60F   "Type of cancer - cervical"
label variable CCC_60G   "Type of cancer - uterine"
label variable CCC_60H   "Type of cancer - lung"
label variable CCC_60I   "Type of cancer - other"
label variable CCC_65    "Has heart disease"
label variable CCC_70    "Heart disease - age first diagnosed"
label variable CCC_75    "Has had a heart attack - lifetime"
label variable CCC_80    "Has high blood pressure"
label variable CCC_85    "High blood pressure - took medication - 1 mo"
label variable CCC_90    "Has had high blood cholesterol - lifetime"
label variable CCC_95    "Suffers from the effects of a stroke"
label variable CCC_100   "Has osteoporosis"
label variable CCC_105   "Has fibromyalgia"
label variable CCC_110   "Fibromyalgia - age first symptoms"
label variable CCC_115   "Fibromyalgia - age first diagnosed"
label variable CCC_120   "Has arthritis (e.g. osteoarthritis, rheumatoid arthritis, gout)"
label variable CCC_125   "Has back problems (excluding scoliosis, fibromyalgia and arthritis)"
label variable CCC_130   "Back problems - diagnosed by health professional"
label variable CCC_135   "Has a mood disorder (depression, bipolar, mania, dysthymia)"
label variable CCCDVDIA  "Diabetes type - 12 months - (D)"
label variable DOCC1     "Chronic conditions (1) - Inclusion Flag - (F)"
label variable CC1_140   "Has an anxiety disorder (phobia, panic, generalized anxiety)"
label variable CC1_145   "Has post-traumatic stress disorder (PTSD)"
label variable CC1_150   "Has Alzheimer's Disease / other dementia"
label variable CC1_155   "Has chronic fatigue syndrome"
label variable CC1_160   "Chronic fatigue syndrome - age first symptoms"
label variable CC1_165   "Chronic fatigue syndrome - age first diagnosed"
label variable CC1_170   "Has multiple chemical sensitivities (MCS)"
label variable CC1_175   "Multiple chemical sensitivities - age first symptoms"
label variable CC1_180   "Multiple chemical sensitivities- age first diagnosed"
label variable DOWDM     "Abilities - Inclusion Flag - (F)"
label variable WDM_05    "Difficulty - seeing"
label variable WDM_10    "Difficulty - hearing"
label variable WDM_15    "Difficulty - walking / climbing steps"
label variable WDM_20    "Difficulty - remembering / concentrating"
label variable WDM_25    "Difficulty - self-care"
label variable WDM_30    "Difficulty - communicating"
label variable DOINJ     "Injuries - Inclusion Flag - (F)"
label variable INJ_05A   "Injuries - head injury / concussion - 12 mo"
label variable INJ_05AA  "Head injury / concussion - freq - 12 mo"
label variable INJ_05B   "Injuries - broken / fractured bone - 12 mo"
label variable INJ_05BA  "Broken / fractured bone - freq - 12 mo"
label variable INJ_05C   "Injuries - cut / puncture - 12 mo"
label variable INJ_05CA  "Cut / puncture - freq - 12 mo"
label variable INJ_10    "Head injury / concussion - activity performed"
label variable INJ_15    "Head injury / concussion - result of a fall"
label variable INJ_15A   "Head injury / concussion - type of fall"
label variable INJ_20    "Head injury / concussion - consulted health care professional"
label variable INJ_20A   "Head injury / concussion - health professional - place"
label variable INJ_25    "Head injury / concussion - admitted to hospital overnight"
label variable INJ_30    "Broken / fractured bone - activity performed"
label variable INJ_35    "Broken / fractured bone - body part"
label variable INJ_40    "Broken / fractured bone - result of a fall"
label variable INJ_40A   "Broken / fractured bone - type of fall"
label variable INJ_45    "Broken / fractured bone - consulted health care professional"
label variable INJ_45A   "Broken / fractured bone - health professional - place"
label variable INJ_50    "Broken / fractured bone - admitted to hospital overnight"
label variable INJ_55    "Cut / puncture - activity performed"
label variable INJ_60    "Cut / puncture - body part"
label variable INJ_65    "Cut / puncture - result of a fall"
label variable INJ_70    "Cut / puncture - consulted health care professional"
label variable INJ_70A   "Cut / puncture - health professional - place"
label variable INJ_75    "Cut / puncture - admitted to hospital overnight"
label variable DOOHM     "Oral health - Inclusion Flag - (F)"
label variable OHM_05    "Perceived oral health"
label variable OHM_10    "Has at least one of own teeth"
label variable OHM_15    "Persistent / on-going mouth pain - frequency - 12 mo"
label variable DOOHM3    "Oral Health 3 - Inlcusion Flag - (F)"
label variable OHM3_05   "Visit dental professional - frequency"
label variable OHM3_10   "Visited dental professional - last time"
label variable OHM3_15   "Avoided going to a dental professional due to cost - 12 mo"
label variable OHM3_18   "Avoided having recommended dental treatment due to cost - 12 mo"
label variable OHM3_20A  "Type dental treatment avoided due to cost - check-ups / cleanings"
label variable OHM3_20B  "Type dental treatment avoided due to cost - fillings"
label variable OHM3_20C  "Type dental treatment avoided due to cost - root canal treatment"
label variable OHM3_20D  "Type dental treatment avoided due to cost - tooth extraction"
label variable OHM3_20E  "Type dental treatment avoided due to cost - tooth replacement"
label variable OHM3_20F  "Type dental treatment avoided due to cost - no response provided"
label variable OHM3_45   "Insurance - dental expenses - all / part cost coverage"
label variable OHM3_50A  "Type of dental insurance - employer"
label variable OHM3_50B  "Type of insurance dental - private plan"
label variable OHM3_50C  "Type of insurance dental - government paid plan"
label variable OHM3_50D  "Type of insurance dental - college or university"
label variable OHM3_50E  "Type of insurance dental - don't know"
label variable DOUPE     "Use of protective equipment - Inclusion Flag - (F)"
label variable UPE_05    "Bicycling - 12 mo"
label variable UPE_10    "Bicycling - helmet - frequency"
label variable UPE_15    "Rollerblading - 12 mo"
label variable UPE_20    "Rollerblading - helmet - frequency"
label variable UPE_25    "Rollerblading - wrist protectors - frequency"
label variable UPE_30    "Rollerblading - elbow pads - frequency"
label variable UPE_35    "Rollerblading - knee pads - frequency"
label variable UPE_40A   "Downhill skiing - 12 mo"
label variable UPE_45    "Downhill skiing - helmet - frequency"
label variable UPE_40B   "Snowboarding - 12 mo"
label variable UPE_50    "Snowboarding - helmet - frequency"
label variable UPE_55    "Snowboarding - wrist protectors - frequency"
label variable UPE_60A   "Skateboarding - 12 mo"
label variable UPE_65    "Skateboarding - helmet - frequency"
label variable UPE_70    "Skateboarding - wrist protectors - frequency"
label variable UPE_75    "Skateboarding - elbow pads - frequency"
label variable UPE_80    "Ice hockey - 12 mo"
label variable UPE_85    "Ice hockey - mouth guard - frequency"
label variable DOCSS     "Current smoking status - Inclusion Flag - (F)"
label variable CSS_05    "Smoked a whole cigarette - lifetime"
label variable CSS_10    "Smoked first whole cigarette - Age"
label variable CSS_15    "Smoked more than 100 cigarettes - lifetime"
label variable CSS_20    "Smoked - frequency - 30 d"
label variable CSS_25    "Num of cigarettes smoked daily (daily smoker)"
label variable CSS_35    "Smoked 1 cigarette or more (occasional smoker) - Num of days - 30 d"
label variable CSS_30    "Num of cigarettes smoked daily (occasional smoker)"
label variable CSS_40    "Made serious attempt to stop smoking - 12 mo"
label variable DOSPU     "Smoking - past use - Inclusion Flag - (F)"
label variable SPU_05    "Smoked daily - lifetime (occasional / former smoker)"
label variable SPU_10A   "Stopped smoking - month (former occasional smoker)"
label variable SPU_10B   "Stopped smoking - year (former occasional smoker)"
label variable SPU_15    "Began smoking daily - age (daily / former daily smoker)"
label variable SPU_20    "Num of cigarettes smoked daily (former daily smoker)"
label variable SPU_25A   "Stopped smoking daily - month (former daily smoker)"
label variable SPU_25B   "Stopped smoking daily - year (former daily smoker)"
label variable SPU_30    "Quit smoking completely (former daily smoker)"
label variable SPU_35A   "Quit smoking completely - month (former daily smoker)"
label variable SPU_35B   "Quit smoking completely - year (former daily smoker)"
label variable SMKDVSTY  "Smoking status (type 2) - traditional definition - (D)"
label variable SMKDVYCS  "Num of years respondent has smoked daily - (D)"
label variable SMKDVSTP  "Num of years since respondent stopped smoking completely - (D)"
label variable DOECV     "Electronic cigarettes and vaping - Inclusion Flag - (F)"
label variable ECV_05    "Tried e-cigarette / vaping device - life"
label variable ECV_10    "Tried e-cigarette / vaping device - age"
label variable ECV_15    "Used e-cigarette / vaping device - freq - 30 d"
label variable ECV_20    "Used e-cigarette - llast time - nicotine"
label variable ECVDVSMK  "E-Cigarette / vaping device and cigarette use - (D)"
label variable DOECV2    "Electronic cigarette and vaping 2 - Inlcusion Flag - (F)"
label variable ECV2_05A  "Vape - e-liquid with nicotine - num of days - 30 d"
label variable ECV2_05B  "Vape - e-liquid without nicotine - num of days - 30 d"
label variable ECV2_05C  "Vape - e-liquid unkown content- num of days - 30 d"
label variable ECV2_10   "Tried to quit smoking with e-cigarette / vaping device - 12 mo"
label variable ECV2_15   "Tried first - e-cigarette / vaping device or cigarette"
label variable DOALC     "Alcohol use - Inclusion Flag - (F)"
label variable ALC_05    "Had a drink - lifetime"
label variable ALC_10    "Drank alcohol - 12 mo"
label variable ALC_15    "Drank alcohol - frequency - 12 mo"
label variable ALC_20    "Drank 5+ / 4+ drinks one occasion - frequency - 12 mo"
label variable ALCDVTTM  "Type of drinker - 12 months - (D)"
label variable DOPRM     "Medication use - pain relievers - Inclusion Flag - (F)"
label variable PRM_10    "Taken pain relievers - codeine products - 12 mo"
label variable PRM_15    "Taken pain relievers - oxycodone products - 12 mo"
label variable PRM_20    "Taken pain relievers - fentanyl products - 12 mo"
label variable PRM_25    "Taken pain relievers - other opioid products - 12 mo"
label variable PRM_30    "Taken pain relievers - frequency - 12 mo"
label variable PRM_35    "Taken pain relievers - prescribed - 12 mo"
label variable PRM_40A   "Taken pain relievers - higher dose - 12 mo"
label variable PRM_40B   "Taken pain relievers - more often - 12 mo"
label variable PRM_50    "Taken pain relievers - reasons other than pain relief - 12 mo"
label variable PRM_55    "Taken pain relievers - tampered - 12 mo"
label variable PRMDV12M  "Pain relief medication use - 12 mo - (D)"
label variable DOCAN     "Cannabis use - Inclusion Flag - (F)"
label variable CAN_05    "Used cannabis - lifetime"
label variable CAN_05A   "Used cannabis - once or more - lifetime"
label variable CAN_05B   "Used cannabis - first time - age"
label variable CAN_05C   "Used cannabis - 12 mo"
label variable CAN_10    "Used cannabis - frequency - 12 mo"
label variable CAN_15A   "Used cannabis - method - smoked - 12 mo"
label variable CAN_15B   "Used cannabis - method - vaporized - 12 mo"
label variable CAN_15C   "Used cannabis - method - swallowed - 12 mo"
label variable CAN_15D   "Used cannabis - method - absorbed - 12 mo"
label variable CAN_15E   "Used cannabis - method - other - 12 mo"
label variable CAN_15BA  "Used cannabis - vaporized - dried flower, leaf"
label variable CAN_15BB  "Used cannabis - vaporized - cannabis liquid"
label variable CAN_15BC  "Used cannabis -  vaporized - cannabis solid"
label variable CAN_20    "Used cannabis - method used most often - 12 mo"
label variable CAN_25A   "Used cannabis - product - Dried flower or leaf - 12 mo"
label variable CAN_25B   "Used cannabis - product - hashish - 12 mo"
label variable CAN_25C   "Used cannabis - product - cannabis oil - 12 mo"
label variable CAN_25D   "Used cannabis - product - cannabis vape pens / cartridges - 12 mo"
label variable CAN_25E   "Used cannabis - product - cannabis concentrates - 12 mo"
label variable CAN_25F   "Used cannabis - product - àcannabis edible food products - 12 mo"
label variable CAN_25G   "Used cannabis - product - cannabis beverages - 12 mo"
label variable CAN_25H   "Used cannabis - product - topicals - 12 mo"
label variable CAN_25I   "Used cannabis - product - other - 12 mo"
label variable CAN_30    "Used cannabis - purpose - 12 mo"
label variable CAN_35A   "Used cannabis - medical purpose - pain - 12 mo"
label variable CAN_35B   "Used cannabis - medical purpose - nausea vomiting - 12 mo"
label variable CAN_35C   "Used cannabis - medical purpose- lack of appetite - 12 mo"
label variable CAN_35D   "Used cannabis - medical purpose- headaches / migraines - 12 mo"
label variable CAN_35E   "Used cannabis - medical purpose - muscle spasms / seizures - 12 mo"
label variable CAN_35F   "Used cannabis - medical purpose- anxiety / depression - 12 mo"
label variable CAN_35G   "Used cannabis - medical purpose- symptoms of PTSD - 12 mo"
label variable CAN_35H   "Used cannabis - medical purpose- problems sleeping - 12 mo"
label variable CAN_35I   "Used cannabis - purpose- opioid withdrawal symptoms - 12 mo"
label variable CAN_35J   "Used cannabis - medical purpose- other - 12 mo"
label variable CAN_40    "Used cannabis - has a medical document for medical purposes use"
label variable CAN_45    "Used cannabis - num of days - 30 d"
label variable CAN_50    "Used cannabis - daily - age"
label variable CANDVF12  "Cannabis - frequency of use - 12 mo - (D)"
label variable CANDVLEO  "Cannabis use - lifetime (excluding ''just once'') - (D)"
label variable CANDVLIO  "Cannabis use - lifetime (including ''just once'') - (D)"
label variable CANDVLS3  "Cannabis user status - lifetime - 3 categories - (D)"
label variable CANDVLS5  "Cannabis user status - lifetime - 5 categories - (D)"
label variable CANDVYEO  "Cannabis use - 12 mo (excluding ''just once'') - (D)"
label variable CANDVYIO  "Cannabis use - 12 mo (including ''just once'') - (D)"
label variable DOMEX     "Maternal experiences - Inclusion Flag - (F)"
label variable MEX_05    "Takes vitamin supplement with folic acid"
label variable MEX_10    "Gave birth - last 5 years"
label variable MEX_12    "Single or multiple birth - last pregnancy"
label variable MEX_20    "Baby's date of birth - day"
label variable MEX_25    "Baby's date of birth - month"
label variable MEX_30    "Baby's date of birth - year"
label variable MEX_40    "Took folic acid supplement - 3 mo before pregnancy"
label variable MEX_50    "Took folic acid supplement - first 3 mo of pregnancy"
label variable MEX_65    "Took iron supplement - during pregnancy"
label variable MEX_70    "Weight - before pregnancy"
label variable MEX_75    "Weight - before pregnancy - pounds / kilograms"
label variable MEX_80    "Weight - gained during pregnancy"
label variable MEX_85    "Weight - gained during pregnancy - pounds / kilograms"
label variable MEX_90    "Co-sleeping with baby less than 12 mo - frequency"
label variable MEX_100   "Breastfed last baby"
label variable MEX_105   "Did not breastfeed last baby - reason"
label variable MEX_110   "Still breastfeeding last baby"
label variable MEX_115A  "Stopped breastfeeding - baby's age"
label variable MEX_115B  "Stopped breastfeeding - baby's age - time period"
label variable MEX_120   "Stopped breastfeeding - reason"
label variable MEX_125   "Gave baby vitamin D supplement - less than 1 yr old"
label variable MEX_150   "Introduced liquids to baby - during breastfeeding"
label variable MEX_155   "Introduced liquids to baby - baby's age"
label variable MEX_160   "Introduced liquids to baby - baby's age - time period"
label variable MEX_170   "Introduced solids to baby"
label variable MEX_175   "Introduced solids to baby - baby's age"
label variable MEX_180   "Introduced solids to baby - baby's age - time period"
label variable MEX_190   "Introduced solids to baby - first solid food"
label variable MEXDVBM6  "Exclusively breastfed for 6 months (or more) - (D)"
label variable MEXDVLBM  "Length of exclusive breastfeeding - (D)"
label variable MEXDVWBK  "Weight before pregnancy - kilograms - (D)"
label variable MEXDVWGK  "Weight gained during pregnancy - kilograms - (D)"
label variable DOMXS     "Maternal experiences - Smoking - Inclusion Flag - (F)"
label variable MXS_05    "Smoked cigarettes - 3 months before last pregnancy"
label variable MXS_10    "Smoked cigarettes - 3 months before last pregnancy - frequency"
label variable MXS_15    "Smoked cigarettes - after finding out about pregnancy"
label variable MXS_20    "Smoked cigarettes - after finding out about pregnancy - frequency"
label variable MXS_35    "Exposure to second-hand smoke during pregnancy"
label variable DOMXA     "Maternal experiences - Alcohol use - Inclusion Flag - (F)"
label variable MXA_05    "Drank alcohol - 3 months before last pregnancy"
label variable MXA_10    "Drank alcohol - 3 months before last pregnancy - frequency"
label variable MXA_12    "Drank alcohol - 3 months before last pregnancy - num of drinks"
label variable MXA_15    "Drank alcohol - after finding out about pregnancy - frequency"
label variable MXA_20    "Drank alcohol - after finding out about pregnancy - frequency"
label variable MXA_22    "Drank alcohol - after finding out about pregnancy - num of drinks"
label variable MXA_35    "Drank alcohol - while breastfeeding / since giving birth"
label variable MXA_40    "Drank alcohol - while breastfeeding / since giving birth - frequency"
label variable MXA_42    "Drank alcohol - while breastfeeding / since giving birth - num drinks"
label variable DOFLU     "Flu shots - Inclusion Flag - (F)"
label variable FLU_05    "Had seasonal flu vaccine - 12 mo"
label variable FLU_10    "Last seasonal flu vaccine - month"
label variable FLU_15    "Last seasonal flu vaccine - current / last year"
label variable FLU_20A   "No flu vaccine - 12 mo - didn't think necessary"
label variable FLU_20B   "No flu vaccine - 12 mo - concern about side effects"
label variable FLU_20C   "No flu vaccine - 12 mo - flu is not that severe"
label variable FLU_20D   "No flu vaccine - 12 mo - flu vaccine doesn't work"
label variable FLU_20E   "No flu vaccine - 12 mo - previous bad reaction"
label variable FLU_20F   "No flu vaccine - 12 mo - other"
label variable DORHC     "Regular health care provider - Inclusion Flag - (F)"
label variable RHC_05    "Regular health care provider"
label variable DOLMAM    "Labour market activities - Inclusion Flag - (F)"
label variable LMAM_01   "Worked at job / business - past week"
label variable LMAM_02   "Absent from job / business - past week"
label variable LMAM_03   "Absent from job / business - reason - past week"
label variable DOLMA3    "Labour market activities (LMA3) - Inclusion Flag - (F)"
label variable LMA3_01   "Employee or self-employed"
label variable DOLMA4    "Labour market activities (LMA4) - Inclusion Flag - (F)"
label variable LMA4FQ01  "Response entered - name of business (self-employed) - (F)"
label variable LMA4FQ02  "Response entered - name of company / business / person - (F)"
label variable LMA4FQ03  "Response entered - type of business / industry / service - (F)"
label variable LBFCSIC   "North American Industry Classification System (NAICS) 2017"
label variable DOLMA5    "Labour market activities (LMA5) - Inclusion Flag - (F)"
label variable LMA5FQ01  "Response entered - type of work - (F)"
label variable LMA5FQ02  "Response entered - main activities / duties - (F)"
label variable LBFCSOC   "National Occupation Classification (NOC) 2016"
label variable DOLMA6    "Labour market activities (LMA6) - Inclusion Flag - (F)"
label variable LMA6_01   "Usual num of hours worked / week - current main job"
label variable DOLBF     "Labour market activities (LBF) - Inclusion Flag - (F)"
label variable LBF_11    "Had more than one job / business - past week"
label variable LBF_12    "Usual num of hours worked / week - current other job"
label variable LBFDVHPW  "Total usual number of hours worked / week - (D)"
label variable LBFDVING  "Industry group - (D)"
label variable LBFDVOCG  "Occupation group - (D)"
label variable LBFDVPFT  "Full-time / part-time working status (for total usual hours) - (D)"
label variable LBFDVWSS  "Working status last week - (D)"
label variable DOLM      "Telework - Inclusion Flag - (F)"
label variable LM_025    "Location worked most hours - 30 d"
label variable DOIM      "Place of birth, immigration and citizenship - Inclusion Flag - (F)"
label variable IM_01A    "Country of birth - Canada / Outside"
label variable IM_01A1   "Province / territory of birth"
label variable SDCCCOB   "Country of birth - coded"
label variable IM_02     "Year first came to live in Canada"
label variable IM_03     "Landed immigrant - life"
label variable IM_04     "Year first became a landed immigrant"
label variable IM_05A    "Canadian citizen"
label variable IM_05B    "Citizen of country other than Canada"
label variable IM_05A1   "Canadian citizen by birth / natualization"
label variable SDCCCOC   "Country of citizenship - coded - excludes Canada"
label variable SDCDVCB   "Country of birth - grouped - (D)"
label variable SDCDVIMM  "Immigrant flag - (D)"
label variable SDCDVRES  "Number of years in Canada since immigration - (D)"
label variable SDCDVALI  "Age - respondent first became a landed immigrant in Canada - (D)"
label variable SDCDVABT  "Aboriginal Identity - (D)"
label variable SDCDVVM   "Visible minority group of respondent - (D)"
label variable SDCDVFLA  "Visible minority flag - (D)"
label variable SDCDVLHM  "Language(s) spoken most often at home - (D)"
label variable SDCDVFL1  "Language 1st learned at home in childhood - mother tongue - (D)"
label variable SDCDVFLS  "First official language spoken - (D)"
label variable DOABM     "Indigenous identity - Inclusion Flag - (F)"
label variable ABM_01A   "No indigenous identity"
label variable ABM_01B   "Indigenous identity - First Nations"
label variable ABM_01C   "Indigenous identity - Métis"
label variable ABM_01D   "Indigenous identity- Inuk (Inuit)"
label variable DOPG      "Population group - Inclusion Flag - (F)"
label variable PG_05A    "Belonging racial / cultural groups - White"
label variable PG_05B    "Belonging racial / cultural groups - South Asian"
label variable PG_05C    "Belonging racial / cultural groups - Chinese"
label variable PG_05D    "Belonging racial / cultural groups - Black"
label variable PG_05E    "Belonging racial / cultural groups - Filipino"
label variable PG_05F    "Belonging racial / cultural groups - Arab"
label variable PG_05G    "Belonging racial / cultural groups - Latin American"
label variable PG_05H    "Belonging racial / cultural groups - Southeast Asian"
label variable PG_05I    "Belonging racial / cultural groups - West Asian"
label variable PG_05J    "Belonging racial / cultural groups - Korean"
label variable PG_05K    "Belonging racial / cultural groups - Japanese"
label variable VMRNIE    "Belonging racial / cultural groups - visible minority n.i.e."
label variable VMROTHER  "Belonging racial / cultural groups - not a visible minority"
label variable DOLAN     "Language - Inclusion Flag - (F)"
label variable LAN_01    "Knowledge of official languages"
label variable LAN_02A   "Language most often spoken at home - English"
label variable LAN_02B   "Language most often spoken at home - French"
label variable LAN_02C   "Language most often spoken at home - Other"
label variable LAN_04A   "Mother tongue - English"
label variable LAN_04B   "Mother tongue - French"
label variable LAN_04C   "Mother tongue - Other"
label variable DOSOR     "Sexual orientation - Inclusion Flag - (F)"
label variable SOR_01    "Sexual orientation"
label variable DOHMC     "Home care services - Inclusion Flag - (F)"
label variable HMC_005A  "Home care services received - nursing care - 12 mo"
label variable HMC_005B  "Home care services received - other health care - 12 mo"
label variable HMC_005C  "Home care services received - medical equipment - 12 mo"
label variable HMC_005D  "Home care services received - personal / home support - 12 mo"
label variable HMC_005E  "Home care services received - palliative / end-of-life care - 12 mo"
label variable HMC_005F  "Home care services received - other services - 12 mo"
label variable HMC_005G  "No one in household received any home care services - 12 mo"
label variable HMC_010A  "Person who received home care services - nursing care"
label variable HMC_010B  "Person who received home care services - other health care"
label variable HMC_010C  "Person who received home care services - medical equipment"
label variable HMC_010D  "Person who received home care services - personal / home support"
label variable HMC_010E  "Person who received home care services - palliative care"
label variable HMC_010F  "Person who received home care services - other services"
label variable HMC_015A  "Duration services provided - nursing care"
label variable HMC_015B  "Duration services provided - other health care"
label variable HMC_015C  "Duration services provided - medical equipment"
label variable HMC_015D  "Duration services provided - personal / home support"
label variable HMC_015E  "Duration services provided - palliative care"
label variable HMC_015F  "Duration services provided - other services"
label variable HMC_020A  "Monthly cost services provided - nursing care - 12 mo"
label variable HMC_020B  "Monthly cost services provided - other health care - 12 mo"
label variable HMC_020C  "Monthly cost services provided - medical equipment - 12 mo"
label variable HMC_020D  "Monthly cost services provided - personal / home support - 12 mo"
label variable HMC_020E  "Monthly cost services provided - palliative care - 12 mo"
label variable HMC_020F  "Monthly cost services provided - other services - 12 mo"
label variable HMC_025A  "Who paid home care services - out of own pocket"
label variable HMC_025B  "Who paid home care services - family / friend in same household"
label variable HMC_025C  "Who paid home care services - someone living outside the household"
label variable HMC_025D  "Who paid home care services - insurance"
label variable HMC_025E  "Who paid home care services - government"
label variable HMC_025F  "Who paid home care services - other"
label variable HMC_030   "Satisfaction with home care services received"
label variable HMC_035A  "Unsatisfactory home care services - poor quality"
label variable HMC_035B  "Unsatisfactory home care services - needs not addressed"
label variable HMC_035C  "Unsatisfactory home care services - insufficient services"
label variable HMC_035D  "Unsatisfactory home care services - long wait time"
label variable HMC_035E  "Unsatisfactory home care services  - other reason"
label variable HMC_037   "Home care services helped stay at home"
label variable HMC_038A  "Home care services didn't help stay at home - poor quality"
label variable HMC_038B  "Home care services didn't help stay at home - needs not addressed"
label variable HMC_038C  "Home care services didn't help stay at home - insufficient services"
label variable HMC_038D  "Home care services didn't help stay at home - long wait time"
label variable HMC_038E  "Home care services didn't help stay at home - cost too high"
label variable HMC_038F  "Home care services didn't help stay at home - other reason"
label variable HMC_040   "Perception home care services needed but not received - 12 mo"
label variable HMC_045   "Home care services needed - for who"
label variable HMC_050A  "Home care services needed - nursing care"
label variable HMC_050B  "Home care services needed - other health care"
label variable HMC_050C  "Home care services needed - medical equipment"
label variable HMC_050D  "Home care services needed - personal / home support"
label variable HMC_050E  "Home care services needed - palliative / end-of-life care"
label variable HMC_050F  "Home care services needed - other services"
label variable HMC_055A  "Home care services not received - not available in the area"
label variable HMC_055B  "Home care services not received - not available at time required"
label variable HMC_055C  "Home care services not received - waiting time too long"
label variable HMC_055D  "Home care services not received - cost"
label variable HMC_055E  "Home care services not received - didn't get around to it"
label variable HMC_055F  "Home care services not received - didn't know where to go"
label variable HMC_055G  "Home care services not received - language barrier"
label variable HMC_055H  "Home care services not received - decided not to seek services"
label variable HMC_055I  "Home care services not received - doctor didn't think was necessary"
label variable HMC_055J  "Home care services not received - not eligible for home care"
label variable HMC_055K  "Home care services not received - still waiting for home care"
label variable HMC_055L  "Home care services not received - other"
label variable HMC_060A  "Home care services provider - govt Home Care Program"
label variable HMC_060B  "Home care services provider - private agency"
label variable HMC_060C  "Home care services provider - family member / friend / neighbour"
label variable HMC_060D  "Home care services provider - volunteer organization"
label variable HMC_060E  "Home care services provider - nowhere / did not try"
label variable HMC_060F  "Home care services provider - other"
label variable HMCDVVRH  "Received home care services - (D)"
label variable HMCDVHLP  "Households where home care services helped recipients stay home - (D)"
label variable DOINL     "Insurance coverage (INL) - Inclusion Flag - (F)"
label variable INL_05    "Insurance - long-term care costs - all / part cost coverage"
label variable DOINP     "Insurance coverage (INP) - Inclusion Flag - (F)"
label variable INP_05    "Insurance - prescription medications - all / part cost coverage"
label variable DOPCN     "Presciption cost - Inclusion Flag - (F)"
label variable PCN_05    "Had prescriptions for medication - 12 mo"
label variable PCN_10A   "Didn’t fill prescription - cost - 12 mo"
label variable PCN_10B   "Didn't collect prescription -cost - 12 mo"
label variable PCN_10C   "Skipped medicine doses - cost - 12 mo"
label variable PCN_10D   "Reduced medicine dosage - cost - 12 mo"
label variable PCN_10E   "Delayed filling prescription - cost - 12 mo"
label variable DOFSC     "Food security - Inclusion Flag - (F)"
label variable FSC_10    "Worried food would run out - 12 mo"
label variable FSC_15    "Food didn't last and no money to buy more - 12 mo"
label variable FSC_20    "Could not afford to eat balanced meals - 12 mo"
label variable FSC_25    "Relied on few kinds of low-cost food to feed children - 12 mo"
label variable FSC_30    "Could not feed children a balanced meal - 12 mo"
label variable FSC_35    "Children were not eating enough - 12 mo"
label variable FSC_40    "Adults skipped meals or cut size - 12 mo"
label variable FSC_45    "Adults skipped meals or cut size - frequency - 12 mo"
label variable FSC_50    "Ate less than felt should - 12 mo"
label variable FSC_55    "Was hungry but couldn't afford enough food - 12 mo"
label variable FSC_60    "Lost weight because not enough money for food - 12 mo"
label variable FSC_65    "Adults did not eat for whole day - 12 mo"
label variable FSC_70    "Adults did not eat whole day - frequency - 12 mo"
label variable FSC_75    "Cut size of children's meals - 12 mo"
label variable FSC_80    "Children skipped meals - 12 mo"
label variable FSC_85    "Children skipped meals - frequency - 12 mo"
label variable FSC_90    "Children were hungry but could not afford more food - 12 mo"
label variable FSC_95    "Children did not eat for whole day - 12 mo"
label variable FSCDVAF2  "Food security - adult status (including marginally) - (D)"
label variable FSCDVCF2  "Food security - child status (including marginally) - (D)"
label variable FSCDVHF2  "Household food security status (including marginally) - (D)"
label variable DOINC     "Total household income - Inclusion Flag - (F)"
label variable INC_005A  "Source household income - wages and salaries"
label variable INC_005B  "Source household income - self-employment"
label variable INC_005C  "Source household income - dividends and interest"
label variable INC_005D  "Source household income - employment insurance"
label variable INC_005E  "Source household income - workers' compensation"
label variable INC_005F  "Source household income - Canada / Quebec Pension Plan"
label variable INC_005G  "Source household income - job-related retirement pensions"
label variable INC_005H  "Source household income - RRSP / RRIF"
label variable INC_005I  "Source household income - Old Age Security / GIS"
label variable INC_005J  "Source household income - social assistance / welfare"
label variable INC_005K  "Source household income - Child Tax Benefit"
label variable INC_005L  "Source household income - child support"
label variable INC_005M  "Source household income - alimony"
label variable INC_005N  "Source household income - other"
label variable INC_005O  "Source household income - none"
label variable INC_010   "Source household income - supplement for people with disabilities"
label variable INC_015   "Household income - main source"
label variable INC_021   "Total household income before taxes - best estimate"
label variable INC_025A  "Source personal income - wages and salaries"
label variable INC_025B  "Source personal income - self-employment"
label variable INC_025C  "Source personal income - dividends and interest"
label variable INC_025D  "Source personal income - employment insurance"
label variable INC_025E  "Source personal income - workers' compensation"
label variable INC_025F  "Source personal income - Canada / Quebec Pension Plan"
label variable INC_025G  "Source personal income - job-related retirement pensions"
label variable INC_025H  "Source personal income - RRSP / RRIF"
label variable INC_025I  "Source personal income - Old Age Security / GIS"
label variable INC_025J  "Source personal income - social assistance / welfare"
label variable INC_025K  "Source personal income - Child Tax Benefit"
label variable INC_025L  "Source personal income - child support"
label variable INC_025M  "Source personal income - alimony"
label variable INC_025N  "Source personal income - other"
label variable INC_025O  "Source personal income - none"
label variable INC_030   "Source personal income - supplement for people with disabilities"
label variable INC_035   "Personal income - main source"
label variable INC_041   "Total personal income before taxes - best estimate"
label variable INCFIMPH  "Household income source flag - (F)"
label variable INCDVHH   "Total household income - all sources - (D)"
label variable INCDVPER  "Personal income - all sources - (D)"
label variable INCDVADR  "Adjusted household income ratio - national level - (D)"
label variable INCDVRCA  "Distribution of household income ratio - national level - (D)"
label variable INCDVRPR  "Distribution of household income - provincial level - (D)"
label variable INCDVRRS  "Distribution of household income - health region level - (D)"
label variable WTS_M     "Weights - Master"
label variable WTS_S     "Weights - Share"
