label variable VERDATE   "Date de création du fichier"
label variable REFPER    "Période de référence"
label variable SAMPLEID  "Identificateur du cas"
label variable INSTANCE  "Identificateur de la personne sélectionnée - interview santé"
label variable COLMODE   "Mode de collecte - 18 ans+"
label variable COLMODEY  "Mode de collecte 12-17 ans (jeunes répondants)"
label variable COLMODEP  "Mode de collecte 12-17 ans (PMR répondants)"
label variable COL_LANG  "Langue de la collecte"
label variable GEO_PRV   "Province de résidence du répondant"
label variable GEODVPC   "Code postal - (D)"
label variable GEODVD16  "Aire de diffusion du Recensement de 2016 (AD) - (D)"
label variable GEODVCSD  "Subdivision du Recensement de 2016 (SDR) - (D)"
label variable GEODVFED  "Circonscriptions électorales fédérales du Recensement 2016 (CÉF) - (D)"
label variable GEODVCD   "Division du recensement de 2016 (DR) - (D)"
label variable GEODVCMA  "Région métropolitaine du Recensement de 2016 (RMR) - (D)"
label variable GEODVCA   "Agglomération de recensement de 2016 (AR) - (D)"
label variable GEODVSAT  "Type de classification des secteurs statistiques (CSS) - (D)"
label variable GEODVHR4  "Région sociosanitaire - (D)"
label variable GEODVP16  "Groupes de régions sociosanitaires homologues de 2016 - (D)"
label variable GEODVUR   "Type de centre de population ou de région rurale - (D)"
label variable GEODVUR2  "Type de centre de population ou de région rurale - regroupé - (D)"
label variable GEODVPSZ  "Classification du centre de population ou de la région rurale - (D)"
label variable GEODVBHA  "Health Authority - Colombie-Britannique (ASCB) - (D)"
label variable GEODVHCS  "Services de soutien domicile / communautaire Ontario (SSDMC) - (D)"
label variable GEODVSHC  "Sous-région du SSDMC de l'Ontario - (D)"
label variable GEODVASZ  "Sous-zones - Alberta - (D)"
label variable SAM_CP    "Période de collecte de l'échantillon"
label variable ADM_YOI   "Année de l'interview"
label variable ADM_MOI   "Mois de l'interview"
label variable ADM_DOI   "Jour de l'interview"
label variable SAMDVLNK  "Permission sur le jumelage de données - (D)"
label variable SAMDVSHR  "Permission sur le partage de données - (D)"
label variable DHHDVHSZ  "Taille du ménage - (D)"
label variable DHHDVLVG  "Disposition de vie du répondant sélectionné - (D)"
label variable DHHDV611  "Nombre de personnes de 6 à 11 ans dans le ménage - (D)"
label variable DHHDVOKD  "Nombre de personnes de 16 à 17 ans dans le ménage - (D)"
label variable DHHDVL12  "Nombre de personnes de moins de 12 ans dans le ménage - (D)"
label variable DHHDVYKD  "Nombre de personnes de moins de 16 ans dans le ménage - (D)"
label variable DHHDVLE5  "Nombre de personnes de 5 ans ou moins dans le ménage - (D)"
label variable DHHDVA65  "Nombre de personnes de 65 ans et plus dans le ménage - (D)"
label variable DHHDVAOS  "Âge du conjoint - (D)"
label variable DHHDVL18  "Nombre de personnes de moins de 18 ans dans le ménage - (D)"
label variable PROXYSEX  "Sexe du répondant sélectionné et si interview faite par procuration"
label variable DWL_01A   "Régime de propriété - Propriétaire ou locataire"
label variable ED_05     "Le plus haut certificat / diplôme / grade obtenu"
label variable EDDVR3    "Plus haut niveau de scolarité - répondant, 3 niveaux - (D)"
label variable EDDVH3    "Plus haut niveau de scolarité - ménage, 3 niveaux - (D)"
label variable AGE_01A   "Année de naissance"
label variable AGE_01B   "Mois de naissance"
label variable AGE_01C   "Jour de naissance"
label variable AWCAGE    "Âge"
label variable DHH_SEX   "Sexe à la naissance"
label variable GDRA_10   "Genre"
label variable GENDER_2  "Genre - imputé"
label variable DOMAC     "Activité principale (1) - Ind d'inclusion - (F)"
label variable MAC_05    "Activité principale - a travaillé à un emploi / entreprise - 12 mo"
label variable MA_02     "Activité principale - 12 mo"
label variable MA_03     "A travaillé à un emploi / entreprise - 7 j"
label variable DOEDC     "Fréquentation scolaire - Ind d'inclusion - (F)"
label variable EDC_10    "Fréquente actuellement école / collège / cégep / université"
label variable EDC_20    "Statut d'étudiant"
label variable DOGEN     "État de santé général - Ind d'inclusion - (F)"
label variable GEN_01    "Perception santé"
label variable GEN_05    "Perception santé mentale"
label variable GEN_10    "Perception stress dans la vie"
label variable GEN_15    "Perception stress au travail"
label variable GEN_20    "Sentiment d'appartenance à la communauté locale"
label variable DOLSM     "Mesures satisfaction à l'égard de la vie - Ind d'inclusion - (F)"
label variable LSM_01    "Satisfaction de vie en général"
label variable LSMDVSWL  "Satisfaction de vie en général (D)"
label variable DOPRS     "Grossesse - Ind d'inclusion - (F)"
label variable PRS_05    "Enceinte actuellement"
label variable DOHWT     "Taille et poids - Ind d'inclusion - (F)"
label variable HWT_05A   "Taille (autodéclarée) - Pieds"
label variable HWT_05B   "Taille (autodéclarée) - Pouces"
label variable HWT_05C   "Taille (autodéclarée) - Centimètres"
label variable HWT_40A   "Poids (autodéclaré)"
label variable HWT_40B   "Poids (autodéclaré) - unité de mesure en livres ou kilogrammes"
label variable HWTDVHTM  "Taille (en mètres) - autodéclarée - (D)"
label variable HWTDVWTK  "Poids (kilogrammes) - autodéclarés - (D)"
label variable HWTDVBMI  "Indice de masse corporelle (autodéclaré) - (D)"
label variable HWTDVCOL  "IMC classification 12 à 17 ans (autodéclaré) - Cole - (D)"
label variable HWTDVISW  "IMC classification 18 ans + (autodéclaré) - standard intl - (D)"
label variable HWTDVWHO  "IMC classification 12 à 17 ans (autodéclaré) - OMS - (D)"
label variable HWTDVCOR  "Indice de masse corporelle (ajusté) - (D)"
label variable HWTDVBCC  "IMC classification 18 ans + (ajusté) - standard intl - (D)"
label variable DOWTP     "Perception du poids - Ind d'inclusion - (F)"
label variable WTP_50    "Autoperception du poids - embonpoint / trop maigre / à peu près normal"
label variable DOCOV2    "COVID-19 (2) - Ind d'inclusion - (F)"
label variable COV2_005  "Santé mentale perçue avant / pendant pandémie"
label variable COV2_10A  "Précautions COVID-19 - se lave les mains plus souvent"
label variable COV2_10B  "Précautions COVID-19 - porte un masque dans les espaces publics"
label variable COV2_10C  "Précautions COVID-19 - garde distance de 2 m / 6 pi avec les autres"
label variable COV2_10D  "Précautions COVID-19 - évite les foules / rassemblements"
label variable COV2_10E  "Précautions COVID-19 - évite quitter maison raisons non-essentielles"
label variable COV2_10F  "Précautions COVID-19 - travaille de la maison"
label variable COV2_10G  "Précautions COVID-19 - utilise services livraison / ramassage magasin"
label variable COV2_10H  "Précautions COVID-19 - s'isole si symptômes"
label variable COV2_10I  "Précautions COVID-19 - autre précaution"
label variable COV2_10J  "Précautions COVID-19 - aucune précaution prise"
label variable COV2_015  "A ressenti symptômes de la COVID-19 - 3 derniers mois"
label variable COV2_020  "A suivi recommandations santé publique pendant les symptômes COVID-19"
label variable COV2_038  "A reçu un vaccin contre la COVID-19"
label variable COV2_030  "Vaccin COVID-19  - nécessite 1 ou 2 doses"
label variable COV2_035  "Vaccin COVID-19 - nombre de doses reçues jusqu'à présent"
label variable COV2_041  "Vaccin COVID-19 - principale raison pas vacciné"
label variable COV2_45A  "Vaccin COVID-19 - raisons pas vouloir - pas un grand risque"
label variable COV2_45B  "Vaccin COVID-19 - raisons pas vouloir - sera pas très malade"
label variable COV2_45C  "Vaccin COVID-19 - raisons pas vouloir - gravité pandémie exagérée"
label variable COV2_45D  "Vaccin COVID-19 - raisons pas vouloir - vaccins ne sont pas efficaces"
label variable COV2_45E  "Vaccin COVID-19 - raisons pas vouloir - vaccins sont dangereux"
label variable COV2_45F  "Vaccin COVID-19 - raisons pas vouloir - doute de son éfficacité"
label variable COV2_45G  "Vaccin COVID-19 - raisons pas vouloir - doute du danger"
label variable COV2_45H  "Vaccin COVID-19 - raisons pas vouloir - philosophiques / religieuses"
label variable COV2_45I  "Vaccin COVID-19 - raisons pas vouloir - autre raison"
label variable COV2_040  "Vaccin COVID-19 - probabilité de choisir de le recevoir"
label variable COV2_55A  "Vaccin COVID-19 - raisons de ne pas avoir reçu la deuxième dose"
label variable COV2_060  "Vaccin COVID-19 - probabilité de choisir de recevoir 2e dose"
label variable DOCOV3    "COVID-19 (3) - Ind d'inclusion - (F)"
label variable COV3_005  "Vaccin COVID-19 - probabilité de recevoir dose supp si offert"
label variable DOCCC     "Conditions chroniques - Ind d'inclusion - (F)"
label variable CCC_05    "Atteint du diabète"
label variable CCC_10    "Diabète - âge au premier diagnostic"
label variable CCC_15    "Diabète - diagnostic - durant grossesse"
label variable CCC_20    "Diabète - diagnostic - autre que durant grossesse"
label variable CCC_30    "Diabète - temps entre diagnostic et début insuline"
label variable CCC_35    "Diabète - prend actuellement de l'insuline"
label variable CCC_40    "Diabète - pris pilules pour contrôler niveau de sucre - 1 mo"
label variable CCC_45    "A reçu un diagnostic de cancer - vie"
label variable CCC_50    "Cancer - âge au premier diagnostic"
label variable CCC_55    "Cancer - a reçu traitement - 12 mo"
label variable CCC_60A   "Type de cancer - du sein"
label variable CCC_65A   "Type de cancer - prostate"
label variable CCC_60B   "Type de cancer - du colon / rectum"
label variable CCC_60C   "Type de cancer - peau - mélanome"
label variable CCC_60D   "Type de cancer - peau - sans mélanome"
label variable CCC_60E   "Type de cancer - ovaire"
label variable CCC_60F   "Type de cancer - col de l'utérus"
label variable CCC_60G   "Type de cancer - utérus"
label variable CCC_60H   "Type de cancer - poumon"
label variable CCC_60I   "Type de cancer - autre"
label variable CCC_65    "A une maladie cardiaque"
label variable CCC_70    "Maladie cardiaque - âge au premier diagnostic"
label variable CCC_75    "A eu crise cardiaque - vie"
label variable CCC_80    "Fait de l'hypertension"
label variable CCC_85    "Hypertension - a pris des médicaments - 1 mo"
label variable CCC_90    "A eu tax cholestérol sanguin élevé - vie"
label variable CCC_95    "Atteint de troubles dus à un AVC"
label variable CCC_100   "Souffre d'ostéoporose"
label variable CCC_105   "Souffre de fibromyalgie"
label variable CCC_110   "Fibromyalgie - âge premiers symptômes"
label variable CCC_115   "Fibromyalgie - âge au premier diagnostic"
label variable CCC_120   "Souffre d'arthrite (ex. arthrose, arthrite rhumatoide, goutte)"
label variable CCC_125   "A des maux de dos (excluant scoliose, fibromyalgie et arthrite)"
label variable CCC_130   "Maux de dos - diagnostiqué par un prefessionel de la santé"
label variable CCC_135   "Atteint trouble de l'humeur (dépression, bipolaire, manie, dysthymie)"
label variable CCCDVDIA  "Type de diabète - 12 mois - (D)"
label variable DOCC1     "Conditions chroniques (1) - Ind d'inclusion - (F)"
label variable CC1_140   "Atteint d'un trouble d'anxiété (phobie, panique, anxiété généralisé)"
label variable CC1_145   "Atteint d'un trouble de touble post-traumatique (TSPT)"
label variable CC1_150   "Atteint d'Alzheimer / autre démence"
label variable CC1_155   "A le syndrome de fatigue chronique"
label variable CC1_160   "Syndrome de fatigue chronique - âge premiers symptômes"
label variable CC1_165   "Syndrome de fatigue chronique - âge au premier diagnostic"
label variable CC1_170   "A des sensibilités aux agresseurs chimiques (SAC)"
label variable CC1_175   "Sensibilités aux agresseurs chimiques - âge premiers symptômes"
label variable CC1_180   "Sensibilités aux agresseurs chimiques - âge au premier diagnostic"
label variable DOEAH     "Habitudes alimentaires - Ind d'inclusion - (F)"
label variable EAH_05A   "A mangé de la nourriture d'un restaurant - nbre de fois - 30 j"
label variable EAH_05B   "A mangé de la nourriture d'un restaurant - période déclarée"
label variable EAH_10A   "A bu du jus de fruit pur - nbre de fois - 30 j"
label variable EAH_10B   "A bu du jus de fruit pur - période déclarée"
label variable EAH_15A   "A bu des boissons à saveur de fruits / sportives - nbre de fois - 30 j"
label variable EAH_15B   "A bu des boissons à saveur de fruits / sportives - période déclarée"
label variable EAH_20A   "A bu des boissons gazeuses régulières - nbre de fois - 30 j"
label variable EAH_20B   "A bu des boissons gazeuses régulières - période déclarée"
label variable EAH_25A   "A bu des boissons sucrées au café / thé glacé - nbre de fois - 30 j"
label variable EAH_25B   "A bu des boissons sucrées au café / thé glacé - période déclarée"
label variable EAH_30A   "A bu des boissons énergisantes - nbre de fois - 30 j"
label variable EAH_30B   "A bu des boissons énergisantes - période déclarée"
label variable EAH_35A   "A bu du lait au chocolat - nbre de fois - 30 j"
label variable EAH_35B   "A bu du lait au chocolat - période déclarée"
label variable EAH_40A   "A mangé des fruits - nbre de fois - 30 j"
label variable EAH_40B   "A mangé des fruits - période déclarée"
label variable EAH_45A   "A mangé des légumes verts foncé - nbre de fois - 30 j"
label variable EAH_45B   "A mangé des légumes verts foncé - période déclarée"
label variable EAH_50A   "A mangé des légumes orange - nbre de fois - 30 j"
label variable EAH_50B   "A mangé des légumes orange - période déclarée"
label variable EAH_55A   "A mangé des légumes féculents - nbre de fois - 30 j"
label variable EAH_55B   "A mangé des légumes féculents - période déclarée"
label variable EAH_60A   "A mangé d'autres légumes - nbre de fois - 30 j"
label variable EAH_60B   "A mangé d'autres légumes - période déclarée"
label variable EAHDVCHO  "Consommation quotidienne - lait au chocolat - (D)"
label variable EAHDVFFD  "Consommation quotidienne - boissons à saveur fruits / sportives - (D)"
label variable EAHDVFRU  "Consommation quotidienne - fruits - (D)"
label variable EAHDVGRN  "Consommation quotidienne - légumes vert foncé - (D)"
label variable EAHDVJUI  "Consommation quotidienne - jus de fruit purs - (D)"
label variable EAHDVORA  "Consommation quotidienne - légumes orange - (D)"
label variable EAHDVSCD  "Consommation quotidienne - boissons sucrées au café / thé glacé - (D)"
label variable EAHDVSOD  "Consommation quotidienne - boissons gazeuses régulières - (D)"
label variable EAHDVSTA  "Consommation quotidienne - légumes féculents - (D)"
label variable EAHDVVEG  "Consommation quotidienne - autres légumes - (D)"
label variable EAHDVEND  "Consommation quotidienne - boissons énergisantes - (D)"
label variable EAHDVBVT  "Consommation quotidienne - boissons - (D)"
label variable EAHDVBVG  "Groupement de la consommation quotidienne totale - boissons - (D)"
label variable EAHDVFVT  "Consommation quotidienne - fruits et légumes - (D)"
label variable EAHDVFVG  "Groupement consommation quotidienne totale - fruits et légumes - (D)"
label variable DOPAA     "Activités physiques - Ind d'inclusion - (F)"
label variable PAA_05    "Déplacement actif - 7 j"
label variable PAA_10A   "Déplacement actif - lundi"
label variable PAA_10B   "Déplacement actif - mardi"
label variable PAA_10C   "Déplacement actif - mercredi"
label variable PAA_10D   "Déplacement actif - jeudi"
label variable PAA_10E   "Déplacement actif - vendredi"
label variable PAA_10F   "Déplacement actif - samedi"
label variable PAA_10G   "Déplacement actif - dimanche"
label variable PAA_15A   "Déplacement actif - 7 j - total - heures"
label variable PAA_15B   "Déplacement actif - 7 j - total - minutes"
label variable PAA_30    "Sport / cond physique / act physique loisir - 7 j"
label variable PAA_35    "Sport / cond phys / act phys loisir - transpiré"
label variable PAA_40A   "Sport / cond physique / act physique loisir - lundi"
label variable PAA_40B   "Sport / cond physique / act physique loisir - mardi"
label variable PAA_40C   "Sport / cond physique / act physique loisir - mercredi"
label variable PAA_40D   "Sport / cond physique / act physique loisir - jeudi"
label variable PAA_40E   "Sport / cond physique / act physique loisir - vendredi"
label variable PAA_40F   "Sport / cond physique / act physique loisir - samedi"
label variable PAA_40G   "Sport / cond physique / act physique loisir- dimanche"
label variable PAA_45A   "Sport / cond physique / act physique loisir - 7 j - total - heures"
label variable PAA_45B   "Sport / cond physique / act physique loisir - 7 j - total - minutes"
label variable PAA_60    "Autres activités physiques - 7 j"
label variable PAA_65    "Autres activités physiques - transpiré"
label variable PAA_70A   "Autres activités physiques - lundi"
label variable PAA_70B   "Autres activités physiques - mardi"
label variable PAA_70C   "Autres activités physiques - mercredi"
label variable PAA_70D   "Autres activités physiques - jeudi"
label variable PAA_70E   "Autres activités physiques - vendredi"
label variable PAA_70F   "Autres activités physiques - samedi"
label variable PAA_70G   "Autres activités physiques - dimanche"
label variable PAA_75A   "Autres activités physiques - 7 j - total - heures"
label variable PAA_75B   "Autres activités physiques - 7 j - total - minutes"
label variable PAA_95    "Activités physiques - intensité élevée"
label variable PAA_100A  "Activités physiques - intensité élevée - 7 j - total - heures"
label variable PAA_100B  "Activités physiques - intensité élevée - 7 j - total - minutes"
label variable PAADVMVA  "Total minutes - activités physiques modérée à vigoureuse - 7 j - (D)"
label variable PAADVACV  "Indicateur de l'activité physique - (D)"
label variable PAADVAC2  "Autre indicateur de l'activité physique - (D)"
label variable PAADVVIG  "Total minutes - activités physiques vigoureuses - 7 j - (D)"
label variable PAADVVOL  "Niveau d'activité hebdomadaire - 7 j (MET*mins/semaine) - (D)"
label variable PAADVWHO  "Physiquement actif selon les recommandations de l'OMS - (D)"
label variable DOPAY     "Activités physiques - jeunesse - Ind d'inclusion - (F)"
label variable PAY_05A   "Activités physiques - fréquenté l'école - 7 j"
label variable PAY_05B   "Activités physiques - fréquenté un camp de jour - 7 j"
label variable PAY_05C   "Activités physiques - travaillé, payé ou non - 7 j"
label variable PAY_05D   "Activités physiques - aucun des choix ci-dessus - 7 j"
label variable PAY_10    "Déplacement actif - 7 j"
label variable PAY_15AA  "Déplacement actif - heures - hier"
label variable PAY_15AB  "Déplacement actif - minutes - hier"
label variable PAY_15BA  "Déplacement actif - heures - 2 j"
label variable PAY_15BB  "Déplacement actif - minutes - 2 j"
label variable PAY_15CA  "Déplacement actif - heures - 3 j"
label variable PAY_15CB  "Déplacement actif - minutes - 3 j"
label variable PAY_15DA  "Déplacement actif - heures - 4 j"
label variable PAY_15DB  "Déplacement actif - minutes - 4 j"
label variable PAY_15EA  "Déplacement actif - heures - 5 j"
label variable PAY_15EB  "Déplacement actif - minutes - 5 j"
label variable PAY_15FA  "Déplacement actif - heures - 6 j"
label variable PAY_15FB  "Déplacement actif - minutes - 6 j"
label variable PAY_15GA  "Déplacement actif - heures - 7 j"
label variable PAY_15GB  "Déplacement actif - minutes - 7 j"
label variable PAY_20    "Activités physiques loisir - école / camp - 7 j"
label variable PAY_25    "Activités physiques loisir - école / camp - transpiré"
label variable PAY_30AA  "Activités physiques loisir - école / camp - heures - hier"
label variable PAY_30AB  "Activités physiques loisir - école / camp - minutes - hier"
label variable PAY_30BA  "Activités physiques loisir - école / camp - heures - 2 j"
label variable PAY_30BB  "Activités physiques loisir - école / camp - minutes - 2 j"
label variable PAY_30CA  "Activités physiques loisir - école / camp - heures - 3 j"
label variable PAY_30CB  "Activités physiques loisir - école / camp - minutes - 3 j"
label variable PAY_30DA  "Activités physiques loisir - école / camp - heures - 4 j"
label variable PAY_30DB  "Activités physiques loisir - école / camp - minutes - 4 j"
label variable PAY_30EA  "Activités physiques loisir - école / camp - heures - 5 j"
label variable PAY_30EB  "Activités physiques loisir - école / camp - minutes - 5 j"
label variable PAY_30FA  "Activités physiques loisir - école / camp - heures - 6 j"
label variable PAY_30FB  "Activités physiques loisir - école / camp - minutes - 6 j"
label variable PAY_30GA  "Activités physiques loisir - école / camp - heures - 7 j"
label variable PAY_30GB  "Activités physiques loisir - école / camp - minutes - 7 j"
label variable PAY_35    "Activités physiques - temps de loisirs - 7 j"
label variable PAY_40    "Activités physiques - temps de loisirs - transpiré"
label variable PAY_45AA  "Activités physique - loisirs - heures - hier"
label variable PAY_45AB  "Activités physiques - loisirs - minutes - hier"
label variable PAY_45BA  "Activités physique - loisirs - heures - 2 j"
label variable PAY_45BB  "Activités physiques - loisirs - minutes - 2 j"
label variable PAY_45CA  "Activités physique - loisirs - heures - 3 j"
label variable PAY_45CB  "Activités physiques - loisirs - minutes - 3 j"
label variable PAY_45DA  "Activités physique - loisirs - heures - 4 j"
label variable PAY_45DB  "Activités physiques - loisirs - minutes - 4 j"
label variable PAY_45EA  "Activités physique - loisirs - heures - 5 j"
label variable PAY_45EB  "Activités physiques - loisirs - minutes - 5 j"
label variable PAY_45FA  "Activités physique - loisirs - heures - 6 j"
label variable PAY_45FB  "Activités physiques - loisirs - minutes - 6 j"
label variable PAY_45GA  "Activités physique - loisirs - heures - 7 j"
label variable PAY_45GB  "Activités physiques - loisirs - minutes - 7 j"
label variable PAY_50    "Autres activités physiques - 7 j"
label variable PAY_55    "Autres activités physiques - transpiré"
label variable PAY_60AA  "Autres activités physiques - heures - hier"
label variable PAY_60AB  "Autres activités physiques - minutes - hier"
label variable PAY_60BA  "Autres activités physiques - heures - 2 j"
label variable PAY_60BB  "Autres activités physiques - minutes - 2 j"
label variable PAY_60CA  "Autres activités physiques - heures - 3 j"
label variable PAY_60CB  "Autres activités physiques - minutes - 3 j"
label variable PAY_60DA  "Autres activités physiques - heures - 4 j"
label variable PAY_60DB  "Autres activités physiques - minutes - 4 j"
label variable PAY_60EA  "Autres activités physiques - heures - 5 j"
label variable PAY_60EB  "Autres activités physiques - minutes - 5 j"
label variable PAY_60FA  "Autres activités physiques - heures - 6 j"
label variable PAY_60FB  "Autres activités physiques - minutes - 6 j"
label variable PAY_60GA  "Autres activités physiques - heures - 7 j"
label variable PAY_60GB  "Autres activités physiques - minutes - 7 j"
label variable PAY_65    "Activités physiques - intensité élevée"
label variable PAY_70A   "Activités physiques - intensité élevée - hier"
label variable PAY_70B   "Activités physiques - intensité élevée - 2 j"
label variable PAY_70C   "Activités physiques - intensité élevée - 3 j"
label variable PAY_70D   "Activités physiques - intensité élevée - 4 j"
label variable PAY_70E   "Activités physiques - intensité élevée - 5 j"
label variable PAY_70F   "Activités physiques - intensité élevée - 6 j"
label variable PAY_70G   "Activités physiques - intensité élevée - 7 j"
label variable PAY_75A   "Activités physiques - intensité élevée - 7 j - total - heures"
label variable PAY_75B   "Activités physiques - intensité élevée - 7 j - total - minutes"
label variable DOSBE     "Comportements sédentaires - Ind d'inclusion - (F)"
label variable SBE_005   "Temps libre assis/couché regarder écran - jour école/travail - 7j"
label variable SBE_010   "Temps libre assis/couché regarder écran - pas jour école/travail - 7j"
label variable DOSLP     "Sommeil - Ind d'inclusion - (F)"
label variable SLP_005   "Nombre d'heures habituel de sommeil par nuit"
label variable SLP_010   "Problèmes à s'endormir ou à rester endormi - fréquence"
label variable SLP_015   "Sommeil réparateur - fréquence"
label variable SLP_020   "Difficulté à rester éveillé - fréquence"
label variable DOCSS     "Usage actuel de la cigarette - Ind d'inclusion - (F)"
label variable CSS_05    "A fumé une cigarette entière - vie"
label variable CSS_10    "A fumé première cigarette entière - Âge"
label variable CSS_15    "A fumé plus de 100 cigarettes - vie"
label variable CSS_20    "A fumé - fréquence - 30 j"
label variable CSS_25    "Nbre de cigarettes fumées par jour (fumeur quotidien)"
label variable CSS_35    "A fumé 1 cigarette ou plus (fumeur occasionnel) - nbre de jours - 30 j"
label variable CSS_30    "Nbre de cigarettes fumées par jour (fumeur occasionnel)"
label variable CSS_40    "A sérieusement essayé d'arrêter de fumer - 12 mo"
label variable DOSPU     "Usage antérieur du tabac - Ind d'inclusion - (F)"
label variable SPU_05    "A fumé tous les jours - vie (fumeur occasionnel / ancien)"
label variable SPU_10A   "A cessé de fumer - mois (ancien fumeur occasionnel)"
label variable SPU_10B   "A cessé de fumer - année (ancien fumeur occasionnel)"
label variable SPU_15    "A commencé à fumer tous les jours - âge (fumeur quot / ancien quot)"
label variable SPU_20    "Nbre de cigarettes fumées par jour (ancien fumeur quotidien)"
label variable SPU_25A   "A cessé de fumer tous les jours - mois (ancien fumeur quotidien)"
label variable SPU_25B   "A cessé de fumer tous les jours - année (ancien fumeur quotidien)"
label variable SPU_30    "A cessé de fumer complètement (ancien fumeur quotidien)"
label variable SPU_35A   "A cessé de fumer complètement - mois (ancien fumeur quotidien)"
label variable SPU_35B   "A cessé de fumer complètement - année (ancien fumeur quotidien)"
label variable SMKDVSTY  "Statut du fumeur (type 2) - définition traditionnelle - (D)"
label variable SMKDVYCS  "Nbre d'années depuis répondant fume tous les jours - (D)"
label variable SMKDVSTP  "Nbre d'années depuis répondant a cessé de fumer complètement - (D)"
label variable DOECV     "Cigarettes électroniques et vapotage - Ind d'inclusion - (F)"
label variable ECV_05    "A essayé cigarette électronique / appareil vapotage - vie"
label variable ECV_10    "A essayé cigarette électronique / appareil vapotage - âge"
label variable ECV_15    "A utilisé cigarette électronique / appareil de vapotage - fréq - 30 j"
label variable ECV_20    "A utilisé cigarette électro - dernière fois - nicotine"
label variable ECVDVSMK  "Consommation de cigarette électronique- (D)"
label variable DOECV2    "Cigarettes électroniques et vapotage 2 - Ind d'inclusion - (F)"
label variable ECV2_05A  "A vapoté - liquide avec nicotine - nbre jours - 30 j"
label variable ECV2_05B  "A vapoté - liquide sans nicotine - nbre jours - 30 j"
label variable ECV2_05C  "A vapoté - liquide contenu inconnu - nbre jours - 30 j"
label variable ECV2_10   "A tenté cesser fumer avec cigarette électro / appareil vape - 12 mo"
label variable ECV2_15   "A essayé en premier - cigarette électro / appareil vape ou cigarette"
label variable DOALC     "Consommation d'alcool - Ind d'inclusion - (F)"
label variable ALC_05    "A pris un verre d'alcool - vie"
label variable ALC_10    "A bu de l'alcool - 12 mo"
label variable ALC_15    "A bu de l'alcool - fréquence - 12 mo"
label variable ALC_20    "A bu 5+ / 4+ verres même occasion - fréquence - 12 mo"
label variable ALCDVTTM  "Genre de buveur - 12 mois - (D)"
label variable DOPRM     "Utilisation de médicaments - antidouleur - Ind d'inclusion - (F)"
label variable PRM_10    "A utilisé analgésiques - produits avec codéine - 12 mo"
label variable PRM_15    "A utilisé analgésiques - produits avec oxycodone - 12 mo"
label variable PRM_20    "A utilisé analgésiques - produits avec fentanyl - 12 mo"
label variable PRM_25    "A utilisé analgésiques - autres produits opioïdes - 12  mo"
label variable PRM_30    "A utilisé analgésiques - fréquence - 12 mo"
label variable PRM_35    "A utilisé analgésiques - prescrits - 12 mo"
label variable PRM_40A   "A utilisé analgésiques - dose excessive - 12 mo"
label variable PRM_40B   "A utilisé analgésiques - plus fréquemment - 12 mo"
label variable PRM_50    "A utilisé analgésiques - raisons autres que contrôle douleur - 12 mo"
label variable PRM_55    "A utilisé analgésiques - modifiés - 12 mo"
label variable PRMDV12M  "Utilisation de médicaments antidouleur - 12 mo - (D)"
label variable DOCAN     "Consommation de cannabis - Ind d'inclusion - (F)"
label variable CAN_05    "A utilisé cannabis - vie"
label variable CAN_05A   "A utilisé cannabis - une fois ou plus - vie"
label variable CAN_05B   "A utilisé cannabis - première fois - âge"
label variable CAN_05C   "A utilisé cannabis - 12 mo"
label variable CAN_10    "A utilisé cannabis - fréquence - 12 mo"
label variable CAN_15A   "A utilisé cannabis - méthode - fumé - 12 mo"
label variable CAN_15B   "A utilisé cannabis - méthode - vaporisé - 12 mo"
label variable CAN_15C   "A utilisé cannabis - méthode - avalé - 12 mo"
label variable CAN_15D   "A utilisé cannabis - méthode - absorbé - 12 mo"
label variable CAN_15E   "A utilisé cannabis - méthode - autre - 12 mo"
label variable CAN_15BA  "A utilisé cannabis - vaporisé - fleurs, feuilles séchées"
label variable CAN_15BB  "A utilisé cannabis - vaporisé - cannabis liquide"
label variable CAN_15BC  "A utilisé cannabis - vaporisé - cannabis solide"
label variable CAN_20    "A utilisé cannabis - méthode utilisée plus souvent - 12 mo"
label variable CAN_25A   "A utilisé cannabis - produit - fleurs, feuilles séchées - 12 mo"
label variable CAN_25B   "A utilisé cannabis - produit - haschisch - 12 mo"
label variable CAN_25C   "A utilisé cannabis - produit - huile cannabis - 12 mo"
label variable CAN_25D   "A utilisé cannabis - produit - cartouches huile / vap stylos - 12 mo"
label variable CAN_25E   "A utilisé cannabis - produit - concentrés de cannabis - 12 mo"
label variable CAN_25F   "A utilisé cannabis - produit - produits alimentaires - 12 mo"
label variable CAN_25G   "A utilisé cannabis - produit - boissons au cannabis - 12 mo"
label variable CAN_25H   "A utilisé cannabis - produit - substances topiques - 12 mo"
label variable CAN_25I   "A utilisé cannabis - produit - autre - 12 mo"
label variable CAN_30    "A utilisé cannabis - raison - 12 mo"
label variable CAN_35A   "A utilisé cannabis - fins médicales - douleur - 12 mo"
label variable CAN_35B   "A utilisé cannabis - fins médicales - nausées vomissements - 12 mo"
label variable CAN_35C   "A utilisé cannabis - fins médicales - manque d'appétit - 12 mo"
label variable CAN_35D   "A utilisé cannabis - fins médicales - maux de tête / migraines - 12 mo"
label variable CAN_35E   "A utilisé cannabis - fins médicales - spasmes / convulsions - 12 mo"
label variable CAN_35F   "A utilisé cannabis - fins médicales -anxiété / dépression - 12 mo"
label variable CAN_35G   "A utilisé cannabis - fins médicales -stress post-traumatique - 12 mo"
label variable CAN_35H   "A utilisé cannabis - fins médicales -problèmes sommeil - 12 mo"
label variable CAN_35I   "A utilisé cannabis - fins médicales -sevrage d'opioïdes - 12 mo"
label variable CAN_35J   "A utilisé cannabis - fins médicales -autre - 12 mo"
label variable CAN_40    "A utilisé cannabis - a un document médical pour utilisation médicale"
label variable CAN_45    "A utilisé cannabis - nbre de jours - 30 j"
label variable CAN_50    "A utilisé cannabis - tous les jours - âge"
label variable CANDVF12  "Cannabis - fréquence de consommation - 12 mo - (D)"
label variable CANDVLEO  "Consommation de cannabis - vie (excluant « juste une fois » ) - (D)"
label variable CANDVLIO  "Consommation de cannabis - vie (incluant « juste une fois » ) - (D)"
label variable CANDVLS3  "Statut du consommateur de cannabis - vie - 3 catégories - (D)"
label variable CANDVLS5  "Statut du consommateur de cannabis - vie - 5 catégories - (D)"
label variable CANDVYEO  "Consommation de cannabis - 12 mo (excluant « juste une fois ») - (D)"
label variable CANDVYIO  "Consommation de cannabis - 12 mo (incluant « juste une fois ») - (D)"
label variable DOMEX     "Expériences de maternité - Ind d'inclusion - (F)"
label variable MEX_05    "Prend un supplément vitaminique avec acide folique"
label variable MEX_10    "A donné naissance - 5 dernières années"
label variable MEX_12    "Naissance simple ou multiple - dernière grossesse"
label variable MEX_20    "Date de naissance du bébé - jour"
label variable MEX_25    "Date de naissance du bébé - mois"
label variable MEX_30    "Date de naissance du bébé - année"
label variable MEX_40    "A pris supplément d'acide folique - 3 mo avant grossesse"
label variable MEX_50    "A pris supplément d'acide folique - premier 3 mo de la grossesse"
label variable MEX_65    "A pris supplément de fer - pendant grossesse"
label variable MEX_70    "Poids - avant grossesse"
label variable MEX_75    "Poids - avant grossesse - livres / kilogrammes"
label variable MEX_80    "Poids - pris pendant grossesse"
label variable MEX_85    "Poids - pris pendant grossesse - livres / kilogrammes"
label variable MEX_90    "Sommeil partagé avec bébé moins de 12 mo - fréquence"
label variable MEX_100   "A allaité dernier bébé"
label variable MEX_105   "N'a pas allaité dernier bébé - raison"
label variable MEX_110   "Allaite encore dernier bébé"
label variable MEX_115A  "A cessé d'allaiter - âge du bébé"
label variable MEX_115B  "A cessé d'allaiter - âge du bébé - période de temps"
label variable MEX_120   "A cessé d'allaiter - raison"
label variable MEX_125   "A donné supplément de vitamine D au bébé - moins d'un an"
label variable MEX_150   "Ajout de liquides à l'alimentation du bébé - pendant allaitement"
label variable MEX_155   "Ajout liquides à l'alimentation du bébé - âge du bébé"
label variable MEX_160   "Ajout liquides à l'alimentation du bébé - âge bébé - période de temps"
label variable MEX_170   "Ajout aliments solides à l'alimentation du bébé"
label variable MEX_175   "Ajout de solides à l'alimentation du bébé - âge du bébé"
label variable MEX_180   "Ajout solides à l'alimentation du bébé - âge bébé - période de temps"
label variable MEX_190   "Ajout de solides à l'alimentation du bébé - premier aliment"
label variable MEXDVBM6  "Allaitement exclusif pendant 6 mois (ou plus) - (D)"
label variable MEXDVLBM  "Durée d'allaitement exclusif - (D)"
label variable MEXDVWBK  "Poids avant la grossesse - kilogrammes - (D)"
label variable MEXDVWGK  "Gain de poids pendant la grossesse - kilogrammes - (D)"
label variable DOMXS     "Expériences maternelles - usage du tabac - Ind d'inclusion - (F)"
label variable MXS_05    "A fumé des cigarettes - 3 mois avant la dernière grossesse"
label variable MXS_10    "A fumé des cigarettes - 3 mois avant la dernière grossesse - fréquence"
label variable MXS_15    "A fumé des cigarettes - après avoir su être enceinte"
label variable MXS_20    "A fumé des cigarettes - après avoir su être enceinte - fréquence"
label variable MXS_35    "Exposition à la fumée secondaire durant la dernière grossesse"
label variable DOMXA     "Expériences maternelles - consommation alcool - Ind d'inclusion - (F)"
label variable MXA_05    "A bu alcool - 3 mois avant la dernière grossesse"
label variable MXA_10    "A bu alcool - 3 mois avant la dernière grossesse - fréquence"
label variable MXA_12    "A bu alcool - 3 mois avant la dernière grossesse - nbre de verres"
label variable MXA_15    "A bu alcool - après avoir su être enceinte"
label variable MXA_20    "A bu alcool - après avoir su être enceinte - fréquence"
label variable MXA_22    "A bu alcool - après avoir su être enceinte - nbre de verres"
label variable MXA_35    "A bu alcool - durant allaitement / depuis accouchement"
label variable MXA_40    "A bu alcool - durant allaitement / depuis accouchement - fréquence"
label variable MXA_42    "A bu alcool durant allaitement / depuis accouchement - nbre de verres"
label variable DORHC     "Fournisseur habituel de soins de santé - Ind d'inclusion - (F)"
label variable RHC_05    "Fournisseur habituel de soins de santé"
label variable DOLMAM    "Activité sur le marché du travail - Ind d'inclusion - (F)"
label variable LMAM_01   "A travaillé à un emploi / entreprise - semaine dernière"
label variable LMAM_02   "Absent de l'emploi / entreprise - semaine dernière"
label variable LMAM_03   "Absent de l'emploi / entreprise - raison - semaine dernière"
label variable DOLMA3    "Activité sur le marché du travail (LMA3) - Ind d'inclusion - (F)"
label variable LMA3_01   "Employé ou travaille à son compte"
label variable DOLMA4    "Activité sur le marché du travail (LMA4) - Ind d'inclusion - (F)"
label variable LMA4FQ01  "Réponse inscrite - nom de l'entreprise (travailleur autonome) - (F)"
label variable LMA4FQ02  "Réponse inscrite - nom de compagnie / entreprise / personne - (F)"
label variable LMA4FQ03  "Réponse inscrite - type d'entreprise / industrie / service - (F)"
label variable LBFCSIC   "Système classification industries de l'Amérique du Nord (SCIAN) 2017"
label variable DOLMA5    "Activité sur le marché du travail (LMA5) - Ind d'inclusion - (F)"
label variable LMA5FQ01  "Réponse inscrite - type de travail - (F)"
label variable LMA5FQ02  "Réponse inscrite - activités / fonctions principales - (F)"
label variable LBFCSOC   "Classification nationale des professions (CNP) 2016"
label variable DOLMA6    "Activité sur le marché du travail (LMA6) - Ind d'inclusion - (F)"
label variable LMA6_01   "Nbre heures travaillées habituellement / semaine - emploi princ actuel"
label variable DOLBF     "Activité sur le marché du travail (LBF) - Ind d'inclusion - (F)"
label variable LBF_11    "Avait plus d'un emploi / entreprise - semaine dernière"
label variable LBF_12    "Nbre heures travaillées habituellement / semaine - autre emploi actuel"
label variable LBFDVHPW  "Nombre total d'heures habituellement travaillées / semaine - (D)"
label variable LBFDVING  "Groupe d'industrie - (D)"
label variable LBFDVOCG  "Groupe professionnel - (D)"
label variable LBFDVPFT  "Statut emploi temps plein / partiel (total heures habituelles) - (D)"
label variable LBFDVWSS  "Statut d'emploi de la semaine dernière - (D)"
label variable DOLM      "Télétravail - Ind d'inclusion - (F)"
label variable LM_025    "Endroit travaillé le plus d'heures - 30 j"
label variable DOIM      "Lieu de naissance, immigration et citoyenneté - Ind d'inclusion - (F)"
label variable IM_01A    "Pays de naissance - Canada / Extérieur"
label variable IM_01A1   "Province / territoire de naissance"
label variable SDCCCOB   "Pays de naissance - codé"
label variable IM_02     "Année venu vivre au Canada pour la première fois"
label variable IM_03     "Immigrant reçu - vie"
label variable IM_04     "Année devenu un immigrant reçu"
label variable IM_05A    "Citoyen canadien"
label variable IM_05B    "Citoyen d'un pays autre que le Canada"
label variable IM_05A1   "Citoyen canadien par naissance / par naturalisation"
label variable SDCCCOC   "Pays de citoyenneté - codé - Canada exclu"
label variable SDCDVCB   "Pays de naissance - groupée - (D)"
label variable SDCDVIMM  "Indicateur d'immigrant - (D)"
label variable SDCDVRES  "Nombre d'années au Canada depuis l'immigration - (D)"
label variable SDCDVALI  "Âge - répondant devenu immigrant reçu la 1ère fois au Canada - (D)"
label variable SDCDVABT  "Identité autochtone - (D)"
label variable SDCDVVM   "Groupe de minorité visible du répondant - (D)"
label variable SDCDVFLA  "Indicateur de minorité visible - (D)"
label variable SDCDVLHM  "Langue(s) parlée(s) le plus souvent à la maison - (D)"
label variable SDCDVFL1  "Première langue apprise dans l'enfance - langue maternelle - (D)"
label variable SDCDVFLS  "Première langue officielle parlée - (D)"
label variable DOABM     "Identité autochtone - Ind d'inclusion - (F)"
label variable ABM_01A   "Pas d'identité autochtone"
label variable ABM_01B   "Identité autochtone - Première Nation"
label variable ABM_01C   "Identité autochtone - Métis"
label variable ABM_01D   "Identité autochtone - Inuk (Inuit)"
label variable DOPG      "Groupe de population - Ind d'inclusion - (F)"
label variable PG_05A    "Appartenance groupes raciaux / culturels - Blanc"
label variable PG_05B    "Appartenance groupes raciaux / culturels - Sud-Asiatique"
label variable PG_05C    "Appartenance groupes raciaux / culturels - Chinois"
label variable PG_05D    "Appartenance groupes raciaux / culturels - Noir"
label variable PG_05E    "Appartenance groupes raciaux / culturels - Philippin"
label variable PG_05F    "Appartenance groupes raciaux / culturels - Arabe"
label variable PG_05G    "Appartenance groupes raciaux / culturels - Latino-Américain"
label variable PG_05H    "Appartenance groupes raciaux / culturels - Asiatique du Sud-Est"
label variable PG_05I    "Appartenance groupes raciaux / culturels - Asiatique occidental"
label variable PG_05J    "Appartenance groupes raciaux / culturels - Coréen"
label variable PG_05K    "Appartenance groupes raciaux / culturels - Japonais"
label variable VMRNIE    "Appartenance groupes raciaux / culturels  - minorité visible n.i.a."
label variable VMROTHER  "Appartenance groupes raciaux / culturels  - pas une minorité visible"
label variable DOLAN     "Langue - Ind d'inclusion - (F)"
label variable LAN_01    "Connaissance des langues officielles"
label variable LAN_02A   "Langue parlée plus souvent à la maison - Anglais"
label variable LAN_02B   "Langue parlée plus souvent à la maison - Français"
label variable LAN_02C   "Langue parlée plus souvent à la maison - Autre"
label variable LAN_04A   "Langue maternelle - Anglais"
label variable LAN_04B   "Langue maternelle - Français"
label variable LAN_04C   "Langue maternelle - Autre"
label variable DOSOR     "Orientation sexuelle - Ind d'inclusion - (F)"
label variable SOR_01    "Orientation sexuelle"
label variable DOHMC     "Services de soins de santé à domicile - Ind d'inclusion - (F)"
label variable HMC_005A  "Soins à domicile reçus - soins infirmiers - 12 mo"
label variable HMC_005B  "Soins à domicile reçus - autres soins de santé - 12 mo"
label variable HMC_005C  "Soins à domicile reçus - équipements médicaux - 12 mo"
label variable HMC_005D  "Soins à domicile reçus - soins personnels / aide ménagère - 12 mo"
label variable HMC_005E  "Soins à domicile reçus - soins palliatifs / fin de vie - 12 mo"
label variable HMC_005F  "Soins à domicile reçus - autres services - 12 mo"
label variable HMC_005G  "Aucun membre du ménage n'a reçu services de soins à domicile - 12 mo"
label variable HMC_010A  "Personne qui a reçu soins à domicile - soins infirmiers"
label variable HMC_010B  "Personne qui a reçu soins à domicile - autres soins de santé"
label variable HMC_010C  "Personne qui a reçu soins à domicile - équipements médicaux"
label variable HMC_010D  "Personne qui a reçu soins à domicile - soins perso / aide ménagère"
label variable HMC_010E  "Personne qui a reçu soins à domicile - soins palliatifs"
label variable HMC_010F  "Personne qui a reçu soins à domicile - autres services"
label variable HMC_015A  "Durée services fournis - soins infirmiers"
label variable HMC_015B  "Durée services fournis - autres soins de santé"
label variable HMC_015C  "Durée services fournis -  équipements médicaux"
label variable HMC_015D  "Durée services fournis - soins perso / aide ménagère"
label variable HMC_015E  "Durée services fournis - soins palliatifs"
label variable HMC_015F  "Durée services fournis - autres services"
label variable HMC_020A  "Coût mensuel services fournis - soins infirmiers - 12 mo"
label variable HMC_020B  "Coût mensuel services fournis - autres soins de santé - 12 mo"
label variable HMC_020C  "Coût mensuel services fournis - équipements médicaux - 12 mo"
label variable HMC_020D  "Coût mensuel services fournis - soinso pers / aide ménagère - 12 mo"
label variable HMC_020E  "Coût mensuel services fournis - soins palliatifs - 12 mo"
label variable HMC_020F  "Coût mensuel services fournis - autres services - 12 mo"
label variable HMC_025A  "Qui a payé soins à domicile - eux-mêmes"
label variable HMC_025B  "Qui a payé soins à domicile - famille / ami dans même ménage"
label variable HMC_025C  "Qui a payé soins à domicile - quelqu'un à l'extérieur du ménage"
label variable HMC_025D  "Qui a payé soins à domicile - assurances"
label variable HMC_025E  "Qui a payé soins à domicile - gouvernement"
label variable HMC_025F  "Qui a payé soins à domicile - autre"
label variable HMC_030   "Satisfaction avec les services de soins à domicile reçus"
label variable HMC_035A  "Soins à domicile non satisfaisants - mauvaise qualité"
label variable HMC_035B  "Soins à domicile non satisfaisants - besoins insatisfaits"
label variable HMC_035C  "Soins à domicile non satisfaisants - services insuffisants"
label variable HMC_035D  "Soins à domicile non satisfaisants - temps attente trop long"
label variable HMC_035E  "Soins à domicile non satisfaisants - autre raison"
label variable HMC_037   "Soins à domicile a aidé à demeurer à la maison"
label variable HMC_038A  "Soins à domicile pas aidé à demeurer maison - mauvaise qualité"
label variable HMC_038B  "Soins à domicile pas aidé à demeurer maison - besoins insatisfaits"
label variable HMC_038C  "Soins à domicile pas aidé à demeurer maison - services insuffisants"
label variable HMC_038D  "Soins à domicile pas aidé à demeurer maison - temps attente trop long"
label variable HMC_038E  "Soins à domicile pas aidé à demeurer maison - coût trop élevé"
label variable HMC_038F  "Soins à domicile pas aidé à demeurer maison - autre raison"
label variable HMC_040   "Perception soins à domicile requis mais pas reçus - 12 mo"
label variable HMC_045   "Soins à domicile requis - pour qui"
label variable HMC_050A  "Soins à domicile requis - soins infirmiers"
label variable HMC_050B  "Soins à domicile requis - autres soins de santé"
label variable HMC_050C  "Soins à domicile requis - équipements médicaux"
label variable HMC_050D  "Soins à domicile requis - soins personnels / aide ménagère"
label variable HMC_050E  "Soins à domicile requis - soins palliatifs / fin de vie"
label variable HMC_050F  "Soins à domicile requis - autres services"
label variable HMC_055A  "Soins à domicile non-reçus - non disponibles dans la région"
label variable HMC_055B  "Soins à domicile non-reçus - non disponibles au moment requis"
label variable HMC_055C  "Soins à domicile non-reçus - temps d'attente trop long"
label variable HMC_055D  "Soins à domicile non-reçus - coût"
label variable HMC_055E  "Soins à domicile non-reçus - ne s'en est pas occupé"
label variable HMC_055F  "Soins à domicile non-reçus - ne savait pas où aller"
label variable HMC_055G  "Soins à domicile non-reçus - barrière linguistique"
label variable HMC_055H  "Soins à domicile non-reçus - décidé de ne pas demander"
label variable HMC_055I  "Soins à domicile non-reçus - médecin ne jugeait pas nécessaire"
label variable HMC_055J  "Soins à domicile non-reçus - pas admissible aux soins à domicile"
label variable HMC_055K  "Soins à domicile non-reçus - toujours en attente"
label variable HMC_055L  "Soins à domicile non-reçus - autre"
label variable HMC_060A  "Prestataire de soins à domicile - programme du govt"
label variable HMC_060B  "Prestataire de soins à domicile - organisme privé"
label variable HMC_060C  "Prestataire de soins à domicile - famille / ami / voisin"
label variable HMC_060D  "Prestataire de soins à domicile - organisme bénévole"
label variable HMC_060E  "Prestataire de soins à domicile - nulle part / pas tenté d'en obtenir"
label variable HMC_060F  "Prestataire de soins à domicile - autre"
label variable HMCDVVRH  "Services de soins de santé à domicile reçus - (D)"
label variable HMCDVHLP  "Ménages où services soins domicile ont aidé à demeurer à maison - (D)"
label variable DOFSC     "Sécurité alimentaire - Ind d'inclusion - (F)"
label variable FSC_10    "Peur de manquer de nourriture - 12 mo"
label variable FSC_15    "Plus de nourriture et pas d'argent pour en racheter - 12 mo"
label variable FSC_20    "N'avait pas les moyens de manger repas équilibrés - 12 mo"
label variable FSC_25    "Comptait sur aliments peu coûteux pour nourrir les enfants - 12 mo"
label variable FSC_30    "Ne pouvait pas servir repas équilibrés aux enfants - 12 mo"
label variable FSC_35    "Enfants ne mangeaient pas assez - 12 mo"
label variable FSC_40    "Adultes ont sauté repas ou réduit la portion- 12 mo"
label variable FSC_45    "Adultes ont sauté repas ou réduit portion - fréquence - 12 mo"
label variable FSC_50    "A mangé moins qu'aurait dû - 12 mo"
label variable FSC_55    "A eu faim mais pas les moyens d'avoir assez de nourriture - 12 mo"
label variable FSC_60    "A perdu du poids pcq pas assez d'argent pour nourriture - 12 mo"
label variable FSC_65    "Adultes ont passé journée entière sans manger - 12 mo"
label variable FSC_70    "Adultes ont passé journée entière sans manger - fréquence - 12 mo"
label variable FSC_75    "A réduit la portion des repas des enfants - 12 mo"
label variable FSC_80    "Enfants ont sauté des repas - 12 mo"
label variable FSC_85    "Enfants ont sauté des repas - fréquence - 12 mo"
label variable FSC_90    "Enfants ont eu faim mais pas moyens d'avoir plus nourriture - 12 mo"
label variable FSC_95    "Enfants ont passé une journée entière sans manger - 12 mo"
label variable FSCDVAF2  "Sécurité alimentaire - état des adultes (incluant marginale) - (D)"
label variable FSCDVCF2  "Sécurité alimentaire - état des enfants (incluant marginale) - (D)"
label variable FSCDVHF2  "État de sécurité alimentaire du ménage - (incluant marginale) - (D)"
label variable DOINC     "Revenu total du ménage - Ind d'inclusion - (F)"
label variable INC_005A  "Source revenu du ménage - salaires et traitements"
label variable INC_005B  "Source revenu du ménage - travail autonome"
label variable INC_005C  "Source revenu du ménage - dividendes et intérêts"
label variable INC_005D  "Source revenu du ménage - prestations d'assurance-emploi"
label variable INC_005E  "Source revenu du ménage - indemnités d'accident du travail"
label variable INC_005F  "Source revenu du ménage - Régime de pensions du Canada / Québec"
label variable INC_005G  "Source revenu du ménage - pensions de retraite d'un employeur"
label variable INC_005H  "Source revenu du ménage - REER / FERR"
label variable INC_005I  "Source revenu du ménage - sécurité de la vieillesse / SRG"
label variable INC_005J  "Source revenu du ménage - aide sociale / bien-être"
label variable INC_005K  "Source revenu du ménage - prestations fiscales pour enfants"
label variable INC_005L  "Source revenu du ménage - pension alimentaire aux enfants"
label variable INC_005M  "Source revenu du ménage - pension alimentaire au conjoint (e)"
label variable INC_005N  "Source revenu du ménage - autre"
label variable INC_005O  "Source revenu du ménage - aucune"
label variable INC_010   "Source revenu du ménage - prestation pour personnes avec incapacité"
label variable INC_015   "Revenu du ménage - source principale"
label variable INC_021   "Revenu total du ménage avant taxes - meilleure estimation"
label variable INC_025A  "Source revenu personnel - salaires et traitements"
label variable INC_025B  "Source revenu personnel - travail autonome"
label variable INC_025C  "Source revenu personnel - dividendes et intérêts"
label variable INC_025D  "Source revenu personnel - prestation d'assurance-emploi"
label variable INC_025E  "Source revenu personnel - indemnités d'accident du travail"
label variable INC_025F  "Source revenu personnel - Régime de pensions du Canada / Quebec"
label variable INC_025G  "Source revenu personnel - pensions de retraite d'un employeur"
label variable INC_025H  "Source revenu personnel - REER / FERR"
label variable INC_025I  "Source revenu personnel - sécurité de la vieillesse / SRG"
label variable INC_025J  "Source revenu personnel - aide sociale / bien-être"
label variable INC_025K  "Source revenu personnel - prestations fiscales pour enfants"
label variable INC_025L  "Source revenu personnel - pension alimentaire aux enfants"
label variable INC_025M  "Source revenu personnel - pension alimentaire au conjoint(e)"
label variable INC_025N  "Source revenu personnel - autre"
label variable INC_025O  "Source revenu personnel - aucune"
label variable INC_030   "Source revenu personnel - prestation pour personnes avec incapacité"
label variable INC_035   "Revenu personnel - source principale"
label variable INC_041   "Revenu personnel total avant taxes - meilleure estimation"
label variable INCFIMPH  "Indicateur de source du revenu du ménage - (F)"
label variable INCDVHH   "Revenu total du ménage - de toutes sources - (D)"
label variable INCDVPER  "Revenu personnel - de toutes sources - (D)"
label variable INCDVADR  "Ratio ajusté du revenu du ménage - échelle nationale - (D)"
label variable INCDVRCA  "Distribution du revenu du ménage - échelle nationale - (D)"
label variable INCDVRPR  "Distribution du revenu du ménage - échelle provinciale - (D)"
label variable INCDVRRS  "Distribution du revenu du ménage - échelle région sociosanitaire - (D)"
label variable WTS_M     "Poids échantillon - Maître"
label variable WTS_S     "Poids échantillon - Partage"
