VALUE LABELS
              /ABM_01A ABM_01B ABM_01C ABM_01D ALC_05 ALC_10 CAN_05 CAN_05C CAN_15A CAN_15B CAN_15BA CAN_15BB CAN_15BC
               CAN_15C CAN_15D CAN_15E CAN_25A CAN_25B CAN_25C CAN_25D CAN_25E CAN_25F CAN_25G CAN_25H CAN_25I CAN_35A
               CAN_35B CAN_35C CAN_35D CAN_35E CAN_35F CAN_35G CAN_35H CAN_35I CAN_35J CAN_40 CC1_140 CC1_145 CC1_150
               CC1_155 CC1_170 CCC_05 CCC_100 CCC_105 CCC_120 CCC_125 CCC_130 CCC_135 CCC_15 CCC_20 CCC_35 CCC_40
               CCC_45 CCC_55 CCC_60A CCC_60B CCC_60C CCC_60D CCC_60E CCC_60F CCC_60G CCC_60H CCC_60I CCC_65 CCC_65A
               CCC_75 CCC_80 CCC_85 CCC_90 CCC_95 COV2_015 COV2_020 COV2_10A COV2_10B COV2_10C COV2_10D COV2_10E
               COV2_10F COV2_10G COV2_10H COV2_10I COV2_10J COV2_45A COV2_45B COV2_45C COV2_45D COV2_45E COV2_45F
               COV2_45G COV2_45H COV2_45I CSS_05 CSS_15 CSS_40 DOABM DOALC DOCAN DOCC1 DOCCC DOCOV2 DOCOV3 DOCSS DOEAH
               DOECV DOECV2 DOEDC DOFSC DOGEN DOHMC DOHWT DOIM DOINC DOLAN DOLBF DOLM DOLMA3 DOLMA4 DOLMA5 DOLMA6
               DOLMAM DOLSM DOMAC DOMEX DOMXA DOMXS DOPAA DOPAY DOPG DOPRM DOPRS DORHC DOSBE DOSLP DOSOR DOSPU DOWTP
               ECV2_10 ECV_05 ECV_20 EDC_10 FSC_40 FSC_50 FSC_55 FSC_60 FSC_65 FSC_75 FSC_80 FSC_90 FSC_95 HMC_005A
               HMC_005B HMC_005C HMC_005D HMC_005E HMC_005F HMC_005G HMC_025A HMC_025B HMC_025C HMC_025D HMC_025E
               HMC_025F HMC_035A HMC_035B HMC_035C HMC_035D HMC_035E HMC_038A HMC_038B HMC_038C HMC_038D HMC_038E
               HMC_038F HMC_040 HMC_050A HMC_050B HMC_050C HMC_050D HMC_050E HMC_050F HMC_055A HMC_055B HMC_055C
               HMC_055D HMC_055E HMC_055F HMC_055G HMC_055H HMC_055I HMC_055J HMC_055K HMC_055L HMC_060A HMC_060B
               HMC_060C HMC_060D HMC_060E HMC_060F IM_03 IM_05A IM_05B INC_005A INC_005B INC_005C INC_005D INC_005E
               INC_005F INC_005G INC_005H INC_005I INC_005J INC_005K INC_005L INC_005M INC_005N INC_005O INC_010
               INC_025A INC_025B INC_025C INC_025D INC_025E INC_025F INC_025G INC_025H INC_025I INC_025J INC_025K
               INC_025L INC_025M INC_025N INC_025O INC_030 LAN_02A LAN_02B LAN_02C LAN_04A LAN_04B LAN_04C LBF_11
               LMAM_02 MAC_05 MA_03 MEX_05 MEX_10 MEX_100 MEX_110 MEX_150 MEX_170 MXA_05 MXA_15 MXA_35 MXS_05 MXS_15
               MXS_35 PAA_05 PAA_10A PAA_10B PAA_10C PAA_10D PAA_10E PAA_10F PAA_10G PAA_30 PAA_35 PAA_40A PAA_40B
               PAA_40C PAA_40D PAA_40E PAA_40F PAA_40G PAA_60 PAA_65 PAA_70A PAA_70B PAA_70C PAA_70D PAA_70E PAA_70F
               PAA_70G PAA_95 PAY_05A PAY_05B PAY_05C PAY_05D PAY_10 PAY_20 PAY_25 PAY_35 PAY_40 PAY_50 PAY_55 PAY_65
               PAY_70A PAY_70B PAY_70C PAY_70D PAY_70E PAY_70F PAY_70G PG_05A PG_05B PG_05C PG_05D PG_05E PG_05F PG_05G
               PG_05H PG_05I PG_05J PG_05K PRM_10 PRM_15 PRM_20 PRM_25 PRM_40A PRM_40B PRM_50 PRM_55 PRS_05 SPU_05
               SPU_30 VMRNIE VMROTHER
                    1   "Yes"
                    2   "No"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ADM_DOI
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /ADM_MOI AGE_01B MEX_25 SPU_10A SPU_25A SPU_35A
                   01   "January"
                   02   "February"
                   03   "March"
                   04   "April"
                   05   "May"
                   06   "June"
                   07   "July"
                   08   "August"
                   09   "September"
                   10   "October"
                   11   "November"
                   12   "December"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /ADM_YOI
                 2022   "Year of interview"
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /AGE_01A MEX_30 SPU_10B SPU_25B SPU_35B
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /AGE_01C MEX_20
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /ALCDVTTM
                    1   "Regular drinker"
                    2   "Occasional drinker"
                    3   "Did not drink in the last 12 months"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ALC_15
                   01   "Less than once a month"
                   02   "Once a month"
                   03   "2 to 3 times a month"
                   04   "Once a week"
                   05   "2 to 3 times a week"
                   06   "4 to 5 times a week"
                   07   "Daily or almost daily"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /ALC_20
                   01   "Never"
                   02   "Less than once a month"
                   03   "Once a month"
                   04   "2 to 3 times a month"
                   05   "Once a week"
                   06   "More than once a week"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /AWCAGE CAN_05B CAN_50 CC1_160 CC1_165 CC1_175 CC1_180 CCC_10 CCC_110 CCC_115 CCC_50 CCC_70 CSS_10 ECV_10
               SPU_15
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /CANDVF12
                   01   "Has not used cannabis - 12 mo"
                   02   "Has used cannabis lest than once a month, incl ""just once"""
                   03   "Has used cannabis 1 to 3 times a month"
                   04   "Has used cannabis once a week"
                   05   "Has used cannabis more than once a week"
                   06   "Has used cannabis daily / almost daily"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /CANDVLEO
                    1   "Has used cannabis more than once - lifetime"
                    2   "Has not used cannabis more than once - lifetime"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CANDVLIO
                    1   "Has used cannabis - lifetime"
                    2   "Has never used cannabis - lifetime"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CANDVLS3
                    1   "Non user"
                    2   "Past user"
                    3   "Current user"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CANDVLS5
                    1   "Has never used cannabis - lifetime"
                    2   "Cannabis just once in lifetime and not in past 12 mo"
                    3   "Cannabis just once in lifetime and in past 12 mo"
                    4   "Cannabis more than once in lifetime and not in past 12 mo"
                    5   "Cannabis more than once in lifetime and in past 12 mo"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CANDVYEO
                    1   "Has used cannabis - 12 mo"
                    2   "Has not used cannabis more than once - 12 mo"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CANDVYIO
                    1   "Has used cannabis - 12 mo"
                    2   "Has not used cannabis - 12 mo"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CAN_05A
                    1   "Just once"
                    2   "More than once"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CAN_10
                    1   "Less than once a month"
                    2   "1 to 3 times a month"
                    3   "Once a week"
                    4   "More than once a week"
                    5   "Daily or almost daily"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CAN_20
                    1   "Smoked"
                    2   "Vaporized"
                    3   "Swallowed"
                    4   "Absorbed"
                    5   "Other method"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CAN_30
                    1   "Non-medical purposes only"
                    2   "Medical purposes only"
                    3   "Both medical and non-medical purposes"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CAN_45
                   01   "Never"
                   02   "1 day"
                   03   "2 or 3 days"
                   04   "1 or 2 days per week"
                   05   "3 or 4 days per week"
                   06   "5 or 6 days per week"
                   07   "Daily"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /CCCDVDIA
                    1   "Type 1 diabetes"
                    2   "Type 2 diabetes"
                    3   "Gestational diabetes"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CCC_30
                   01   "Less than 1 month"
                   02   "1 month to less than 2 months"
                   03   "2 months to less than 6 months"
                   04   "6 months to less than 1 year"
                   05   "1 year or more"
                   06   "Never"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /COLMODE COLMODEP COLMODEY
                    1   "r-EQ: self response by electronic questionnaire"
                    2   "i-EQ: Interviewer administered EQ by telephone"
                    3   "i-EQ: Interviewer administered EQ in person"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COL_LANG
                    1   "English"
                    2   "French"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_005
                    1   "Much better now"
                    2   "Somewhat better now"
                    3   "About the same"
                    4   "Somewhat worse now"
                    5   "Much worse now"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_030
                    1   "One dose"
                    2   "Two doses"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_035
                    1   "One dose"
                    2   "Two doses"
                    3   "Three doses"
                    4   "Four doses or more"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_038
                    1   "Yes, received at least one dose of a vaccine"
                    2   "No"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_040 COV2_060 COV3_005
                    1   "Very likely"
                    2   "Somewhat likely"
                    3   "Somewhat unlikely"
                    4   "Very unlikely"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /COV2_041
                   01   "Don't want to be vaccinated at this time"
                   02   "Don't want to be vaccinated at all"
                   03   "Don’t have confidence in the vaccine that was offered"
                   04   "Appointment in the future"
                   05   "Not been able to get an appointment yet"
                   06   "Don't know where to go to get vaccinated"
                   07   "Sick at the time the vaccine was offered"
                   08   "Vaccine is not recommended for me"
                   09   "Already had COVID-19"
                   10   "Haven’t had the time"
                   11   "Don’t think it'snecessary, risks of having COVID-19 are low"
                   12   "Other reason"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /COV2_55A
                   01   "One dose is enough to protect against COVID-19"
                   02   "Was not aware that needed a 2nd dose"
                   03   "Bad reaction to the first dose"
                   04   "Concerns about side effects associated with the 2nd dose"
                   05   "Vaccine wanted for 2nd dose is not available"
                   06   "Appointment in the future"
                   07   "Too much trouble getting a 2nd appointment"
                   08   "Already had COVID-19"
                   09   "Don’t think it's necessary, risks of having COVID-19 are low"
                   10   "Other reason"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /CSS_20
                    1   "Every day"
                    2   "Less than 1X / day, but at least 1X / week"
                    3   "Less than 1X / week, but at least 1X in the past month"
                    4   "Not at all"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /CSS_25 CSS_30 SPU_20
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /CSS_35 ECV2_05A ECV2_05B ECV2_05C
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDV611
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVA65
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVAOS
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /DHHDVHSZ
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVL12
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVL18
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVLE5
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVLVG
                   01   "Unattached individual living alone"
                   02   "Unattached individual living with others"
                   03   "Individual living with spouse / partner"
                   04   "Parent living with spouse / partner and children"
                   05   "Single parent living with children"
                   06   "Child living with a single parent"
                   07   "Child living with a single parent and siblings"
                   08   "Child living with two parents"
                   09   "Child living with two parents and siblings"
                   10   "Other"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVOKD
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHHDVYKD
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /DHH_SEX
                    1   "Male"
                    2   "Female"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /DWL_01A
                    1   "Yes, owned, even if it is still being paid for"
                    2   "No, rented, even if no cash rent is paid"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /EAHDVBVG
                    1   "Drinks beverages less than 5 times per day"
                    2   "Drinks beverages between 5 and 10 times per day"
                    3   "Drinks beverages more than 10 times per day"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /EAHDVBVT EAHDVFVT
               9999.6   "Valid skip"
               9999.7   "Don't know"
               9999.8   "Refusal"
               9999.9   "Not stated"
              /EAHDVCHO EAHDVEND EAHDVFFD EAHDVFRU EAHDVGRN EAHDVJUI EAHDVORA EAHDVSCD EAHDVSOD EAHDVSTA EAHDVVEG
                999.6   "Valid skip"
                999.7   "Don't know"
                999.8   "Refusal"
                999.9   "Not stated"
              /EAHDVFVG
                    1   "Eats fruits and vegetables less than 5 times per day"
                    2   "Eats fruits and vegetables between 5 and 10 times per day"
                    3   "Eats fruits and vegetables more than 10 times per day"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /EAH_05A EAH_10A EAH_15A EAH_20A EAH_25A EAH_30A EAH_35A EAH_40A EAH_45A EAH_50A EAH_55A EAH_60A
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /EAH_05B EAH_10B EAH_15B EAH_20B EAH_25B EAH_30B EAH_35B EAH_40B EAH_45B EAH_50B EAH_55B EAH_60B
                    1   "Per month"
                    2   "Per week"
                    3   "Per day"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ECV2_15
                    1   "E-cigarette or vaping device"
                    2   "Cigarette"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ECVDVSMK
                    1   "Tried e-cigarette/vaping device first"
                    2   "Tried cigarette first"
                    3   "Only tried e-cigarette/vaping device"
                    4   "Only tried cigarette"
                    5   "Never tried an e-cigarette/vaping device or cigarette"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ECV_15
                    1   "Every day"
                    2   "Almost every day"
                    3   "At least once a week"
                    4   "At least once in the past month"
                    5   "Never"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /EDC_20
                    1   "Full-time student"
                    2   "Part-time student"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /EDDVH3 EDDVR3
                    1   "Less than secondary school graduation"
                    2   "Secondary school graduation, no post-secondary education"
                    3   "Post-secondary certificate/diploma / university degree"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /ED_05
                   01   "Less than high school diploma or its equivalent"
                   02   "High school diploma or a high school equivalency certificate"
                   03   "Trade certificate or diploma"
                   04   "College/CEGEP/other non-university certificate or diploma"
                   05   "University certificate or diploma below the bachelor's level"
                   06   "Bachelor's degree (e.g. B.A., B.Sc., LL.B.)"
                   07   "University certificate, diploma, degree above the BA level"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /FSCDVAF2 FSCDVCF2 FSCDVHF2
                    0   "Food secure"
                    1   "Marginally food insecure"
                    2   "Moderately food insecure"
                    3   "Severely food insecure"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /FSC_10 FSC_15 FSC_20 FSC_25 FSC_30 FSC_35
                    1   "Often true"
                    2   "Sometimes true"
                    3   "Never true"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /FSC_45 FSC_70 FSC_85
                    1   "Almost every month"
                    2   "Some months but not every month"
                    3   "Only 1 or 2 months"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GDRA_10
                    1   "Man"
                    2   "Woman"
                    3   "Non-binary person"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GENDER_2
                    1   "Men+"
                    2   "Women+"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEN_01 GEN_05
                    1   "Excellent"
                    2   "Very good"
                    3   "Good"
                    4   "Fair"
                    5   "Poor"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEN_10 GEN_15
                    1   "Not at all stressful"
                    2   "Not very stressful"
                    3   "A bit stressful"
                    4   "Quite a bit stressful"
                    5   "Extremely stressful"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEN_20
                    1   "Very strong"
                    2   "Somewhat strong"
                    3   "Somewhat weak"
                    4   "Very weak"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEODVBHA
                 5910   "Interior"
                 5920   "Fraser"
                 5930   "Vancouver"
                 5940   "Vancouver Island"
                 5950   "Northern"
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /GEODVCA
                  000   "No CA assigned"
                  005   "Bay Roberts"
                  010   "Grand Falls-Windsor"
                  011   "Gander"
                  015   "Corner Brook"
                  105   "Charlottetown"
                  110   "Summerside"
                  210   "Kentville"
                  215   "Truro"
                  220   "New Glasgow"
                  225   "Cape Breton"
                  320   "Fredericton"
                  328   "Bathurst"
                  329   "Miramichi"
                  330   "Campbellton"
                  335   "Edmundston"
                  403   "Matane"
                  404   "Rimouski"
                  405   "Rivière-du-Loup"
                  406   "Baie-Comeau"
                  410   "Alma"
                  411   "Dolbeau-Mistassini"
                  412   "Sept-Îles"
                  423   "Sainte-Marie"
                  428   "Saint-Georges"
                  430   "Thetford Mines"
                  437   "Cowansville"
                  440   "Victoriaville"
                  444   "Shawinigan"
                  447   "Drummondville"
                  450   "Granby"
                  452   "Saint-Hyacinthe"
                  454   "Sorel-Tracy"
                  456   "Joliette"
                  465   "Salaberry-de-Valleyfield"
                  468   "Lachute"
                  480   "Val-d'Or"
                  485   "Rouyn-Noranda"
                  501   "Cornwall"
                  502   "Hawkesbury"
                  507   "Arnprior"
                  509   "Carleton Place"
                  512   "Brockville"
                  515   "Pembroke"
                  516   "Petawawa"
                  527   "Cobourg"
                  528   "Port Hope"
                  530   "Kawartha Lakes"
                  531   "Centre Wellington"
                  533   "Ingersoll"
                  544   "Woodstock"
                  546   "Tillsonburg"
                  547   "Norfolk"
                  553   "Stratford"
                  556   "Chatham-Kent"
                  557   "Leamington"
                  562   "Sarnia"
                  565   "Wasaga Beach"
                  566   "Owen Sound"
                  567   "Collingwood"
                  569   "Orillia"
                  571   "Midland"
                  575   "North Bay"
                  582   "Elliot Lake"
                  586   "Timmins"
                  590   "Sault Ste. Marie"
                  598   "Kenora"
                  603   "Winkler"
                  605   "Steinbach"
                  607   "Portage la Prairie"
                  610   "Brandon"
                  640   "Thompson"
                  710   "Yorkton"
                  715   "Moose Jaw"
                  720   "Swift Current"
                  735   "North Battleford"
                  745   "Prince Albert"
                  750   "Estevan"
                  755   "Weyburn"
                  805   "Medicine Hat"
                  806   "Brooks"
                  820   "Okotoks"
                  821   "High River"
                  826   "Strathmore"
                  828   "Canmore"
                  830   "Red Deer"
                  831   "Sylvan Lake"
                  832   "Lacombe"
                  833   "Camrose"
                  840   "Lloydminster"
                  845   "Cold Lake"
                  850   "Grande Prairie"
                  860   "Wood Buffalo"
                  865   "Wetaskiwin"
                  905   "Cranbrook"
                  907   "Nelson"
                  913   "Penticton"
                  918   "Vernon"
                  920   "Salmon Arm"
                  925   "Kamloops"
                  930   "Chilliwack"
                  934   "Squamish"
                  937   "Duncan"
                  938   "Nanaimo"
                  939   "Parksville"
                  940   "Port Alberni"
                  943   "Courtenay"
                  944   "Campbell River"
                  945   "Powell River"
                  950   "Williams Lake"
                  952   "Quesnel"
                  955   "Prince Rupert"
                  965   "Terrace"
                  970   "Prince George"
                  975   "Dawson Creek"
                  977   "Fort St. John"
                  990   "Whitehorse"
                  995   "Yellowknife"
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /GEODVCMA
                  000   "No CMA assigned"
                  001   "St. John's"
                  205   "Halifax"
                  305   "Moncton"
                  310   "Saint John"
                  408   "Saguenay"
                  421   "Québec"
                  433   "Sherbrooke"
                  442   "Trois-Rivières"
                  462   "Montréal"
                  505   "Ottawa-Gatineau"
                  521   "Kingston"
                  522   "Belleville"
                  529   "Peterborough"
                  532   "Oshawa"
                  535   "Toronto"
                  537   "Hamilton"
                  539   "St. Catharines - Niagara"
                  541   "Kitchener - Cambridge - Waterloo"
                  543   "Brantford"
                  550   "Guelph"
                  555   "London"
                  559   "Windsor"
                  568   "Barrie"
                  580   "Greater Sudbury / Grand Sudbury"
                  595   "Thunder Bay"
                  602   "Winnipeg"
                  705   "Regina"
                  725   "Saskatoon"
                  810   "Lethbridge"
                  825   "Calgary"
                  835   "Edmonton"
                  915   "Kelowna"
                  932   "Abbotsford - Mission"
                  933   "Vancouver"
                  935   "Victoria"
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /GEODVHR4
                 1011   "Eastern Regional"
                 1012   "Central Regional"
                 1013   "Western Regional"
                 1014   "Labrador-Grenfell Regional"
                 1100   "Prince Edward Island"
                 1201   "Zone 1 - Western"
                 1202   "Zone 2 - Northern"
                 1203   "Zone 3 - Eastern"
                 1204   "Zone 4 - Central"
                 1301   "Zone 1 (Moncton area)"
                 1302   "Zone 2 (Saint John area)"
                 1303   "Zone 3 (Fredericton area)"
                 1304   "Zone 4 (Edmundston area)"
                 1305   "Zone 5 (Campbellton area)"
                 1306   "Zone 6 (Bathurst area)"
                 1307   "Zone 7 (Miramichi area)"
                 2401   "Bas-Saint-Laurent"
                 2402   "Saguenay - Lac-Saint-Jean"
                 2403   "Capitale-Nationale"
                 2404   "Mauricie et du Centre-du-Québec"
                 2405   "L'Estrie"
                 2406   "Région de Montréal"
                 2407   "L'Outaouais"
                 2408   "L'Abitibi-Témiscamingue"
                 2409   "Côte-Nord"
                 2410   "Nord-du-Québec"
                 2411   "Gaspésie - Îles-de-la-Madeleine"
                 2412   "Chaudière-Appalaches"
                 2413   "Région de Laval"
                 2414   "Région de Lanaudière"
                 2415   "Région des Laurentides"
                 2416   "Montérégie"
                 2417   "Nunavik"
                 2418   "Terres-Cries-de-la-Baie-James"
                 3526   "The District of Algoma HU"
                 3527   "Brant County HU"
                 3530   "Durham Regional HU"
                 3531   "Elgin-St Thomas HU"
                 3533   "Grey Bruce HU"
                 3534   "Haldimand-Norfolk HU"
                 3535   "Haliburton, Kawartha, Pine Ridge District HU"
                 3536   "Halton Regional HU"
                 3537   "City of Hamilton HU"
                 3538   "Hastings and Prince Edward Counties HU"
                 3539   "Huron County HU"
                 3540   "Chatham-Kent HU"
                 3541   "Kingston, Frontenac and Lennox and Addington HU"
                 3542   "Lambton HU"
                 3543   "Leeds, Grenville and Lanark District HU"
                 3544   "Middlesex-London HU"
                 3546   "Niagara Regional Area HU"
                 3547   "North Bay Parry Sound District HU"
                 3549   "Northwestern HU"
                 3551   "City of Ottawa HU"
                 3552   "Oxford County HU"
                 3553   "Peel Regional HU"
                 3554   "Perth District HU"
                 3555   "Peterborough County-City HU"
                 3556   "Porcupine HU"
                 3557   "Renfrew County and District HU"
                 3558   "Eastern Ontario HU"
                 3560   "Simcoe Muskoka District HU"
                 3561   "Sudbury and District HU"
                 3562   "Thunder Bay District HU"
                 3563   "Timiskaming HU"
                 3565   "Waterloo HU"
                 3566   "Wellington-Dufferin-Guelph HU"
                 3568   "Windsor-Essex County HU"
                 3570   "York Regional HU"
                 3575   "Oxford Elgin St. Thomas HU"
                 3595   "City of Toronto HU"
                 4601   "Winnipeg RHA"
                 4602   "Prairie Mountain Health"
                 4603   "Interlake-Eastern Regional Health"
                 4604   "Northern RHA"
                 4605   "Southern Health"
                 4701   "Sun Country RHA"
                 4702   "Five Hills RHA"
                 4703   "Cypress RHA"
                 4704   "Regina Qu'Appelle RHA"
                 4705   "Sunrise RHA"
                 4706   "Saskatoon RHA"
                 4707   "Heartland RHA"
                 4708   "Kelsey Trail RHA"
                 4709   "Prince Albert Parkland RHA"
                 4710   "Prairie North RHA"
                 4711   "Mamawetan Churchill River RHA"
                 4712   "Keewatin Yatthé RHA"
                 4713   "Athabasca Health Authority"
                 4714   "Mamawetan/Keewatin/Athabasca"
                 4831   "South Zone"
                 4832   "Calgary Zone"
                 4833   "Central Zone"
                 4834   "Edmonton Zone"
                 4835   "North Zone"
                 5911   "East Kootenay HSDA"
                 5912   "Kootenay-Boundary HSDA"
                 5913   "Okanagan HSDA"
                 5914   "Thompson/Cariboo HSDA"
                 5921   "Fraser East HSDA"
                 5922   "Fraser North HSDA"
                 5923   "Fraser South HSDA"
                 5931   "Richmond HSDA"
                 5932   "Vancouver HSDA"
                 5933   "North Shore/Coast Garibaldi HSDA"
                 5941   "South Vancouver Island HSDA"
                 5942   "Central Vancouver Island HSDA"
                 5943   "North Vancouver Island HSDA"
                 5951   "Northwest HSDA"
                 5952   "Northern Interior HSDA"
                 5953   "Northeast HSDA"
                 6001   "Yukon"
                 6101   "Northwest Territories"
                 6201   "Nunavut"
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /GEODVP16
                   01   "Health Region Peer Group A"
                   02   "Health Region Peer Group B"
                   03   "Health Region Peer Group C"
                   04   "Health Region Peer Group D"
                   05   "Health Region Peer Group E"
                   06   "Health Region Peer Group F"
                   07   "Health Region Peer Group G"
                   08   "Health Region Peer Group H"
                   09   "Health Region Peer Group I"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /GEODVPSZ
                    1   "Rural area (less than 1,000)"
                    2   "Small population centre (1,000 to 29,999)"
                    3   "Medium population centre (30,000 to 99,999)"
                    4   "Large urban population centre (100,000 or greater)"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEODVSAT
                  001   "CMA"
                  002   "Tracted CA"
                  003   "Non-tracted CA"
                  004   "Strongly influenced zone"
                  005   "Moderately influenced zone"
                  006   "Weakly influenced zone"
                  007   "Non-influenced zone"
                  008   "Territories"
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /GEODVUR
                   01   "Core"
                   02   "Fringe"
                   03   "Rural area inside of a CMA or CA"
                   04   "Population centre outside of a CMA and CA"
                   05   "Rural area outside of a CMA or CA"
                   06   "Secondary core"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /GEODVUR2
                    1   "Population Centre"
                    2   "Rural Area"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /GEO_PRV
                   10   "NEWFOUNDLAND AND LABRADOR"
                   11   "PRINCE EDWARD ISLAND"
                   12   "NOVA SCOTIA"
                   13   "NEW BRUNSWICK"
                   24   "QUEBEC"
                   35   "ONTARIO"
                   46   "MANITOBA"
                   47   "SASKATCHEWAN"
                   48   "ALBERTA"
                   59   "BRITISH COLUMBIA"
                   60   "YUKON"
                   61   "NORTHWEST TERRITORIES"
                   62   "NUNAVUT"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HMCDVHLP
                    1   "Services were very helpful or somewhat helpful"
                    2   "Services were not helpful"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HMCDVVRH
                    1   "Received some home care - 12 mo"
                    2   "No one received any home care services - 12 mo"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HMC_010A HMC_010B HMC_010C HMC_010D HMC_010E HMC_010F
                    1   "You"
                    2   "Another member of the household"
                    3   "You and another member of the household"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HMC_015A HMC_015B HMC_015C HMC_015D HMC_015E HMC_015F
                   01   "Less than 1 month"
                   02   "1 month to less than 3 months"
                   03   "3 months to less than 6 months"
                   04   "6 months to less than 1 year"
                   05   "1 year to 3 years"
                   06   "More than 3 years"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HMC_020A HMC_020B HMC_020C HMC_020D HMC_020E HMC_020F
                   01   "$0"
                   02   "$1 to less than $50"
                   03   "$50 to less than $100"
                   04   "$100  to less than $200"
                   05   "$200 to less than $300"
                   06   "$300 to less than $400"
                   07   "$400 to less than $1,000"
                   08   "$1,000 and more"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HMC_030
                    1   "Very satisfied"
                    2   "Somewhat satisfied"
                    3   "Neither satisfied nor dissatisfied"
                    4   "Somewhat dissatisfied"
                    5   "Very dissatisfied"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HMC_037
                    1   "Very helpful"
                    2   "Somewhat helpful"
                    3   "Not helpful"
                    4   "Reason for homecare was unrelated to staying at home"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HMC_045
                    1   "You only"
                    2   "Other household member"
                    3   "You and other household member"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HWTDVBCC HWTDVISW
                   01   "Underweight"
                   02   "Normal weight"
                   03   "Overweight"
                   04   "Obese - Class I"
                   05   "Obese - Class II"
                   06   "Obese - Class III"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HWTDVBMI
               999.96   "Valid skip"
               999.97   "Don't know"
               999.98   "Refusal"
               999.99   "Not stated"
              /HWTDVCOL HWTDVWHO
                    1   "Thinness"
                    2   "Normal"
                    3   "Overweight"
                    4   "Obese"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /HWTDVCOR
               999.96   "Valid skip"
               999.97   "Don't know"
               999.98   "Refusal"
               999.99   "Not stated"
              /HWTDVHTM
                9.996   "Valid skip"
                9.997   "Don't know"
                9.998   "Refusal"
                9.999   "Not stated"
              /HWTDVWTK
               999.96   "Valid skip"
               999.97   "Don't know"
               999.98   "Refusal"
               999.99   "Not stated"
              /HWT_05A
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HWT_05B
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /HWT_05C
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /HWT_40A MEX_70 MEX_80
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /HWT_40B MEX_75 MEX_85
                    1   "Pounds"
                    2   "Kilograms"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /IM_01A
                    1   "Born in Canada"
                    2   "Born outside Canada"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /IM_01A1
                   10   "Newfoundland and Labrador"
                   11   "Prince Edward Island"
                   12   "Nova Scotia"
                   13   "New Brunswick"
                   24   "Quebec"
                   35   "Ontario"
                   46   "Manitoba"
                   47   "Saskatchewan"
                   48   "Alberta"
                   59   "British Columbia"
                   60   "Yukon"
                   61   "Northwest Territories"
                   62   "Nunavut"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /IM_02
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /IM_04
                 9996   "Valid skip"
                 9997   "Don't know"
                 9998   "Refusal"
                 9999   "Not stated"
              /IM_05A1
                    1   "By birth"
                    2   "By naturalization"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /INCDVADR
          9.999999996   "Valid skip"
          9.999999997   "Don't know"
          9.999999998   "Refusal"
          9.999999999   "Not stated"
              /INCDVHH
                   01   "No income or income loss"
                   02   "Less than $5,000"
                   03   "$5,000 to $9,999"
                   04   "$10,000 to $14,999"
                   05   "$15,000 to $19,999"
                   06   "$20,000 to $29,999"
                   07   "$30,000 to $39,999"
                   08   "$40,000 to $49,999"
                   09   "$50,000 to $59,999"
                   10   "$60,000 to $69,999"
                   11   "$70,000 to $79,999"
                   12   "$80,000 to $89,999"
                   13   "$90,000 to $99,999"
                   14   "$100,000 to $149,999"
                   15   "$150,000 or more"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /INCDVPER
                   01   "No income or income loss"
                   02   "Less than $5,000"
                   03   "$5,000 to $9,999"
                   04   "$10,000 to $14,999"
                   05   "$15,000 to $19,999"
                   06   "$20,000 to $29,999"
                   07   "$30,000 to $39,999"
                   08   "$40,000 to $49,999"
                   09   "$50,000 to $59,999"
                   10   "$60,000 to $69,999"
                   11   "$70,000 to $79,999"
                   12   "$80,000 to $89,999"
                   13   "$90,000 to $99,999"
                   14   "$100,000 or more"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /INCDVRCA INCDVRPR INCDVRRS
                   01   "Decile 1"
                   02   "Decile 2"
                   03   "Decile 3"
                   04   "Decile 4"
                   05   "Decile 5"
                   06   "Decile 6"
                   07   "Decile 7"
                   08   "Decile 8"
                   09   "Decile 9"
                   10   "Decile 10"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /INCFIMPH
                   01   "Reported"
                   02   "Imputed"
                   09   "Not stated (no income information available)"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /INC_015 INC_035
                   01   "Wages and salaries"
                   02   "Income from self-employment"
                   03   "Dividends and interest (e.g., on bonds, savings)"
                   04   "Employment insurance"
                   05   "Workers' compensation"
                   06   "Benefits from Canada or Quebec Pension Plan"
                   07   "Job-related retirement pensions, superannuation, annuities"
                   08   "RRSP/RRIF"
                   09   "Old Age Security and Guaranteed Income Supplement"
                   10   "Provincial or municipal social  assistance or welfare"
                   11   "Child Tax Benefit or family allowances"
                   12   "Child support"
                   13   "Alimony"
                   14   "Other (e.g., rental income, scholarships)"
                   15   "None"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /INC_021 INC_041
             99999996   "Valid skip"
             99999997   "Don't know"
             99999998   "Refusal"
             99999999   "Not stated"
              /LAN_01
                    1   "English only"
                    2   "French only"
                    3   "Both English and French"
                    4   "Neither English nor French"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LBFCSIC LBFCSOC
               "9995"   "Could not be coded"
               "9996"   "Valid skip"
               "9997"   "Don't know"
               "9998"   "Refusal"
               "9999"   "Not stated"
              /LBFDVHPW
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /LBFDVING
                   01   "Agriculture, forestry, fishing and hunting"
                   02   "Mining, quarrying, and oil/gas extraction"
                   03   "Utilities"
                   04   "Construction"
                   05   "Manufacturing"
                   06   "Wholesale trade"
                   07   "Retail trade"
                   08   "Transportation and warehousing"
                   09   "Information and cultural industries"
                   10   "Finance and insurance"
                   11   "Real estate and rental and leasing"
                   12   "Professional, scientific and technical services"
                   13   "Management of companies and enterprises"
                   14   "Admin, support, waste management, remediation services"
                   15   "Educational services"
                   16   "Health care and social assistance"
                   17   "Arts, entertainment and recreation"
                   18   "Accommodation and food services"
                   19   "Other services (except public administration)"
                   20   "Public administration"
                   95   "Could not be coded"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /LBFDVOCG
                   01   "Management occupations"
                   02   "Business, finance and administration occupations"
                   03   "Natural and applied sciences and related occupations"
                   04   "Health occupations"
                   05   "Occupations in education, law, social/community/gov services"
                   06   "Occupations in art, culture, recreation and sport"
                   07   "Sales and service occupations"
                   08   "Trades, transport, equip operators and related occupations"
                   09   "Natural resources, agriculture and related occupations"
                   10   "Occupations in manufacturing and utilities"
                   95   "Could not be coded"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /LBFDVPFT
                    1   "Full-time"
                    2   "Part-time"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LBFDVWSS
                    1   "Worked at a job / business - last week"
                    2   "Absent from work / business - last week"
                    3   "Did not have a job - last week"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LBF_12 LMA6_01
                999.6   "Valid skip"
                999.7   "Don't know"
                999.8   "Refusal"
                999.9   "Not stated"
              /LMA3_01
                    1   "Employee"
                    2   "Self-employed"
                    3   "Working in a family business without pay"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LMA4FQ01 LMA4FQ02 LMA4FQ03 LMA5FQ01 LMA5FQ02
                    1   "Yes"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LMAM_01
                    1   "Yes"
                    2   "No"
                    3   "Permanently unable to work"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LMAM_03
                   01   "Vacation"
                   02   "Own illness or disability"
                   03   "Caring for own children"
                   04   "Caring for elder relative"
                   05   "Maternity or parental leave"
                   06   "Other personal or family responsibilities"
                   07   "Labour dispute (strike or lockout)"
                   08   "Temporary layoff due to business conditions"
                   09   "Seasonal layoff"
                   10   "Casual job, no work available"
                   11   "Work schedule"
                   12   "Self-employed, no work available"
                   13   "Seasonal business"
                   14   "Other"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /LM_025
                    1   "At a fixed location outside the home"
                    2   "Outside the home with no fixed location"
                    3   "At home"
                    4   "Absent from work"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LSMDVSWL
                    1   "Very satisfied"
                    2   "Satisfied"
                    3   "Neither satisfied nor dissatisfied"
                    4   "Dissatisfied"
                    5   "Very dissatisfied"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /LSM_01
                   00   "Very dissatisfied"
                   01   "|"
                   02   "|"
                   03   "|"
                   04   "|"
                   05   "|"
                   06   "|"
                   07   "|"
                   08   "|"
                   09   "V"
                   10   "Very satisfied"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /MA_02
                   01   "Looking for paid work"
                   02   "Going to school"
                   03   "Caring for your children"
                   04   "Household work"
                   05   "Retired"
                   06   "Maternity, paternity or parental leave"
                   07   "Long term illness"
                   08   "Volunteering or care-giving other than for your children"
                   09   "Other"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /MEXDVBM6
                    1   "Had exclusively breastfed last baby at least 6 months"
                    2   "Had not exclusively breastfeed last baby at least 6 months"
                    3   "Has not breastfed her last baby at all"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEXDVLBM
                   00   "Has not breastfed or given breastmilk to last baby"
                   01   "Less than 1 week"
                   02   "1 week to less than 1 month"
                   03   "1 month to less than 2 months"
                   04   "2 months to less than 3 months"
                   05   "3 months to less than 4 months"
                   06   "4 months to less than 5 months"
                   07   "5 months to less than 6 months"
                   08   "6 months or more"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /MEXDVWBK MEXDVWGK
               999.96   "Valid skip"
               999.97   "Don't know"
               999.98   "Refusal"
               999.99   "Not stated"
              /MEX_105
                    1   "Did not want to breastfeed"
                    2   "No support or information to breastfeed"
                    3   "Medical condition"
                    4   "Other"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEX_115A MEX_155 MEX_175
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /MEX_115B MEX_160 MEX_180
                    1   "Days"
                    2   "Weeks"
                    3   "Months"
                    4   "Years"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEX_12
                    1   "Single birth"
                    2   "Multiple births"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEX_120
                   01   "Not enough breast milk"
                   02   "Child weaned themselves"
                   03   "Planned to stop at this time"
                   04   "Difficulty with breastfeeding"
                   05   "Medical condition"
                   06   "Other"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /MEX_125 MEX_90
                    1   "Every day or almost every day"
                    2   "Occasionally"
                    3   "Never"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEX_190
                    1   "Infant cereals"
                    2   "Fruits or vegetables"
                    3   "Meat and meat alternatives"
                    4   "Other"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MEX_40 MEX_50 MEX_65
                    1   "Yes"
                    2   "No"
                    3   "Don't know"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MXA_10 MXA_20 MXA_40
                    1   "A few times a month or less"
                    2   "Once or twice a week"
                    3   "Many times a week"
                    4   "Everyday"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MXA_12 MXA_22 MXA_42
                    1   "One drink"
                    2   "Two drinks"
                    3   "Three drinks"
                    4   "More than three"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /MXS_10 MXS_20
                    1   "Everyday"
                    2   "Almost everyday"
                    3   "A few times a week"
                    4   "Rarely"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /PAADVAC2 PAADVWHO
                    1   "Level 1"
                    2   "Level 2"
                    3   "Level 3"
                    4   "Level 4"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /PAADVACV
                    1   "Physically active at / above recommended level from CPAG"
                    2   "Physically active below recommended level from CPAG"
                    3   "No physical activity minutes reported"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /PAADVMVA
                99996   "Valid skip"
                99997   "Don't know"
                99998   "Refusal"
                99999   "Not stated"
              /PAADVVIG
                99996   "Valid skip"
                99997   "Don't know"
                99998   "Refusal"
                99999   "Not stated"
              /PAADVVOL
                99996   "Valid skip"
                99997   "Don't know"
                99998   "Refusal"
                99999   "Not stated"
              /PAA_100A PAA_15A PAA_45A PAA_75A PAY_75A
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /PAA_100B PAA_15B PAA_45B PAA_75B PAY_15AB PAY_15BB PAY_15CB PAY_15DB PAY_15EB PAY_15FB PAY_15GB PAY_30AB
               PAY_30BB PAY_30CB PAY_30DB PAY_30EB PAY_30FB PAY_30GB PAY_45AB PAY_45BB PAY_45CB PAY_45DB PAY_45EB
               PAY_45FB PAY_45GB PAY_60AB PAY_60BB PAY_60CB PAY_60DB PAY_60EB PAY_60FB PAY_60GB PAY_75B
                   00   "0"
                   05   "5"
                   10   "10"
                   15   "15"
                   20   "20"
                   25   "25"
                   30   "30"
                   35   "35"
                   40   "40"
                   45   "45"
                   50   "50"
                   55   "55"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /PAY_15AA PAY_15BA PAY_15CA PAY_15DA PAY_15EA PAY_15FA PAY_15GA PAY_30AA PAY_30BA PAY_30CA PAY_30DA
               PAY_30EA PAY_30FA PAY_30GA PAY_45AA PAY_45BA PAY_45CA PAY_45DA PAY_45EA PAY_45FA PAY_45GA PAY_60AA
               PAY_60BA PAY_60CA PAY_60DA PAY_60EA PAY_60FA PAY_60GA
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /PRMDV12M
                    1   "Has used a pain reliever - 12 mo"
                    2   "Has not used a pain reliever - 12 mo"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /PRM_30
                   01   "Once or twice"
                   02   "3 to 11 times a year"
                   03   "About once a month"
                   04   "2 or 3 times a month"
                   05   "About once or twice a week"
                   06   "3 or 4 times a week"
                   07   "Daily or almost daily"
                   08   "As needed, or following surgery"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /PRM_35
                    1   "No, none were prescribed"
                    2   "Yes, they all were prescribed"
                    3   "Some were prescribed and others were not"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /PROXYSEX
                    1   "Male, non proxy interview"
                    2   "Female, non proxy interview"
                    3   "Male, proxy interview"
                    4   "Female, proxy interview"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /RHC_05
                    1   "Family doctor or general practitioner"
                    2   "Medical specialist"
                    3   "Nurse practitioner"
                    4   "Other"
                    5   "Don’t have a regular health care provider"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SAMDVLNK
                    1   "Respondent agreed to link information"
                    2   "Respondent did not agree to link information"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SAMDVSHR
                    1   "Yes"
                    2   "No"
                    3   "Partial"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SAM_CP
             "202201"   "February - May"
             "202204"   "April - June"
             "202207"   "July - September"
             "202210"   "October - December"
             "999996"   "Valid skip"
             "999997"   "Don't know"
             "999998"   "Refusal"
             "999999"   "Not stated"
              /SBE_005
                   01   "2 hours or less per day"
                   02   "More than 2 hours but less than 4 hours"
                   03   "4 hours to less than 6 hours"
                   04   "6 hours to less than 8 hours"
                   05   "8 hours or more per day"
                   06   "Was not at work or school"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SBE_010
                    1   "2 hours or less per day"
                    2   "More than 2 hours but less than 4 hours"
                    3   "4 hours to less than 6 hours"
                    4   "6 hours to less than 8 hours"
                    5   "8 hours or more per day"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SDCCCOB SDCCCOC
              "10000"   "America"
              "11000"   "North America"
              "11124"   "Canada"
              "11304"   "Greenland"
              "11666"   "Saint Pierre and Miquelon"
              "11840"   "United States"
              "12000"   "Central America"
              "12084"   "Belize"
              "12188"   "Costa Rica"
              "12222"   "El Salvador"
              "12320"   "Guatemala"
              "12340"   "Honduras"
              "12484"   "Mexico"
              "12558"   "Nicaragua"
              "12591"   "Panama"
              "13000"   "Caribbean"
              "13028"   "Antigua and Barbuda"
              "13044"   "Bahamas"
              "13052"   "Barbados"
              "13060"   "Bermuda"
              "13092"   "Virgin Islands, British"
              "13136"   "Cayman Islands"
              "13192"   "Cuba"
              "13212"   "Dominica"
              "13214"   "Dominican Republic"
              "13308"   "Grenada"
              "13312"   "Guadeloupe"
              "13332"   "Haiti"
              "13388"   "Jamaica"
              "13474"   "Martinique"
              "13500"   "Montserrat"
              "13531"   "Curaçao"
              "13533"   "Aruba"
              "13534"   "Sint-Maarteen (Dutch part)"
              "13535"   "Bonaire, Sint Eustatius and Saba"
              "13630"   "Puerto Rico"
              "13652"   "Saint Barthélemy"
              "13659"   "Saint Kitts and Nevis"
              "13660"   "Anguilla"
              "13662"   "Saint Lucia"
              "13663"   "Saint Martin (French part)"
              "13670"   "Saint Vincent and the Grenadines"
              "13780"   "Trinidad and Tobago"
              "13796"   "Turks and Caicos"
              "13850"   "Virgin Islands, United States"
              "14000"   "South America"
              "14032"   "Argentina"
              "14068"   "Bolivia"
              "14076"   "Brazil"
              "14152"   "Chile"
              "14170"   "Colombia"
              "14218"   "Ecuador"
              "14238"   "Falkland Islands"
              "14239"   "South Georgia and the South Sandwich Islands"
              "14254"   "French Guiana"
              "14328"   "Guyana"
              "14600"   "Paraguay"
              "14604"   "Peru"
              "14740"   "Suriname"
              "14858"   "Uruguay"
              "14862"   "Venezuela"
              "20000"   "Europe"
              "21000"   "Western Europe"
              "21040"   "Austria"
              "21056"   "Belgium"
              "21250"   "France"
              "21276"   "Germany"
              "21438"   "Liechtenstein"
              "21442"   "Luxembourg"
              "21492"   "Monaco"
              "21528"   "Netherlands"
              "21756"   "Switzerland"
              "22000"   "Eastern Europe, Czechoslovakia, USSR"
              "22100"   "Bulgaria"
              "22112"   "Belarus"
              "22203"   "Czechia"
              "22233"   "Estonia"
              "22348"   "Hungary"
              "22428"   "Latvia"
              "22440"   "Lithuania"
              "22498"   "Moldova"
              "22616"   "Poland"
              "22642"   "Romania"
              "22643"   "Russian Federation"
              "22703"   "Slovakia"
              "22804"   "Ukraine"
              "23000"   "Northern Europe"
              "23208"   "Denmark"
              "23234"   "Faroe Islands"
              "23246"   "Finland"
              "23248"   "Aland Islands"
              "23352"   "Iceland"
              "23372"   "Ireland"
              "23578"   "Norway"
              "23680"   "Sark"
              "23744"   "Svalbard and Jan Mayen"
              "23752"   "Sweden"
              "23826"   "United kingdom"
              "23831"   "Guernsey"
              "23832"   "Jersey"
              "23833"   "Isle of Man"
              "24000"   "Southern Europe, Yugoslavia"
              "24008"   "Albania"
              "24020"   "Andorra"
              "24070"   "Bosnia and Herzegovina"
              "24191"   "Croatia"
              "24292"   "Gibraltar"
              "24300"   "Greece"
              "24336"   "Holy See (Vatican City State)"
              "24380"   "Italy"
              "24470"   "Malta"
              "24499"   "Montenegro"
              "24620"   "Portugal"
              "24674"   "San Marino"
              "24688"   "Serbia"
              "24705"   "Slovenia"
              "24724"   "Spain"
              "24807"   "Macedonia, Republic of"
              "24983"   "Kosovo"
              "30000"   "Africa"
              "31000"   "Western Africa"
              "31132"   "Cabo Verde"
              "31204"   "Benin"
              "31270"   "Gambia"
              "31288"   "Ghana"
              "31324"   "Guinea"
              "31384"   "Côte d'Ivoire"
              "31430"   "Liberia"
              "31466"   "Mali"
              "31478"   "Mauritania"
              "31562"   "Niger"
              "31566"   "Nigeria"
              "31624"   "Guinea-Bissau"
              "31654"   "Saint Helena"
              "31686"   "Senegal"
              "31694"   "Sierra Leone"
              "31768"   "Togo"
              "31854"   "Burkina Faso"
              "32000"   "Eastern Africa"
              "32108"   "Burundi"
              "32174"   "Comoros"
              "32175"   "Mayotte"
              "32231"   "Ethiopia"
              "32232"   "Eritrea"
              "32262"   "Djibouti"
              "32404"   "Kenya"
              "32450"   "Madagascar"
              "32454"   "Malawi"
              "32480"   "Mauritius"
              "32508"   "Mozambique"
              "32638"   "Réunion"
              "32646"   "Rwanda"
              "32690"   "Seychelles"
              "32706"   "Somalia"
              "32716"   "Zimbabwe"
              "32728"   "South Sudan"
              "32800"   "Uganda"
              "32834"   "Tanzania"
              "32894"   "Zambia"
              "33000"   "Northern Africa"
              "33012"   "Algeria"
              "33434"   "Libya"
              "33504"   "Morocco"
              "33729"   "Sudan"
              "33732"   "Western Sahara"
              "33788"   "Tunisia"
              "33818"   "Egypt"
              "34000"   "Central Africa"
              "34024"   "Angola"
              "34120"   "Cameroon"
              "34140"   "Central African Republic"
              "34148"   "Chad"
              "34178"   "Congo, Republic of"
              "34180"   "Congo, Democratic Republic of the"
              "34226"   "Equatorial Guinea"
              "34266"   "Gabon"
              "34678"   "Sao Tome and Principe"
              "35000"   "Southern Africa"
              "35072"   "Botswana"
              "35426"   "Lesotho"
              "35516"   "Namibia"
              "35710"   "South Africa, Republic of"
              "35748"   "Swaziland"
              "40000"   "Asia"
              "41000"   "Middle East, Kurdistan, West Central Asia"
              "41004"   "Afghanistan"
              "41031"   "Azerbaijan"
              "41048"   "Bahrain"
              "41051"   "Armenia"
              "41196"   "Cyprus"
              "41268"   "Georgia"
              "41275"   "West Bank and Gaza Strip (Palestine)"
              "41364"   "Iran"
              "41368"   "Iraq"
              "41376"   "Israel"
              "41398"   "Kazakhstan"
              "41400"   "Jordan"
              "41414"   "Kuwait"
              "41417"   "Kyrgyzstan"
              "41422"   "Lebanon"
              "41512"   "Oman"
              "41634"   "Qatar"
              "41682"   "Saudi Arabia"
              "41760"   "Syria"
              "41762"   "Tajikistan"
              "41784"   "United Arab Emirates"
              "41792"   "Turkey"
              "41795"   "Turkmenistan"
              "41860"   "Uzbekistan"
              "41887"   "Yemen"
              "42000"   "Eastern Asia, Korea"
              "42156"   "China"
              "42158"   "Taiwan"
              "42344"   "Hong Kong"
              "42392"   "Japan"
              "42408"   "Korea, North"
              "42410"   "Korea, South"
              "42446"   "Macao"
              "42496"   "Mongolia"
              "43000"   "South East Asia"
              "43096"   "Brunei Darussalam"
              "43104"   "Burma (Myanmar)"
              "43116"   "Cambodia"
              "43360"   "Indonesia"
              "43418"   "Laos"
              "43458"   "Malaysia"
              "43608"   "Philippines"
              "43626"   "Timor-Leste"
              "43702"   "Singapore"
              "43704"   "Viet Nam"
              "43764"   "Thailand"
              "44000"   "Southern Asia"
              "44050"   "Bangladesh"
              "44064"   "Bhutan"
              "44086"   "British Indian Ocean Territory"
              "44144"   "Sri Lanka"
              "44356"   "India"
              "44462"   "Maldives"
              "44524"   "Nepal"
              "44586"   "Pakistan"
              "50000"   "Oceania"
              "51016"   "American Samoa"
              "51036"   "Australia"
              "51090"   "Solomon Islands"
              "51162"   "Christmas Island"
              "51166"   "Cocos (Keeling) Islands"
              "51184"   "Cook Islands"
              "51242"   "Fiji"
              "51258"   "French Polynesia"
              "51296"   "Kiribati"
              "51316"   "Guam"
              "51520"   "Nauru"
              "51540"   "New Caledonia"
              "51548"   "Vanuatu"
              "51554"   "New Zealand"
              "51570"   "Niue"
              "51574"   "Norfolk Island"
              "51580"   "Northern Mariana Islands"
              "51581"   "United States Minor Outlying Islands"
              "51583"   "Micronesia, Federated States of"
              "51584"   "Marshall Islands"
              "51585"   "Palau"
              "51598"   "Papua New Guinea"
              "51612"   "Pitcairn"
              "51772"   "Tokelau"
              "51776"   "Tonga"
              "51798"   "Tuvalu"
              "51876"   "Wallis and Futuna"
              "51882"   "Samoa"
              "60000"   "Antarctica adjacent islands"
              "61010"   "Antarctica"
              "61074"   "Bouvet Island"
              "61260"   "French Southern Territories"
              "61334"   "Heard Island and McDonald Islands"
              "80000"   "Born At Sea"
              "90000"   "Other"
              "99996"   "Valid skip"
              "99997"   "Don't know"
              "99998"   "Refusal"
              "99999"   "Not stated"
              /SDCDVABT
                    1   "Indigenous identity (First Nations, Métis, Inuk/Inuit)"
                    2   "Non-Indigenous identity"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SDCDVALI
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /SDCDVCB
                   01   "Canada"
                   02   "Other - North America"
                   03   "South, Central America, Caribbean and Bermuda"
                   04   "Europe"
                   05   "Africa"
                   06   "Asia"
                   07   "Oceania"
                   08   "Antarctica and adjacent islands"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SDCDVFL1 SDCDVLHM
                   01   "English"
                   02   "French"
                   03   "English and French"
                   04   "English, French and Other"
                   05   "English and Other"
                   06   "French and Other"
                   07   "Other"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SDCDVFLA
                    1   "Visible minority"
                    2   "Not a visible minority"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SDCDVFLS
                    1   "English"
                    2   "French"
                    3   "English and French"
                    4   "Neither English nor French"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SDCDVIMM
                    1   "Non-immigrant (citizen by birth)"
                    2   "Immigrant (landed immigrant or citizen by naturalization)"
                    3   "Non-permanent resident"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SDCDVRES
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /SDCDVVM
                   01   "South Asian"
                   02   "Chinese"
                   03   "Black"
                   04   "Filipino"
                   05   "Latin American"
                   06   "Arab"
                   07   "Southeast Asian"
                   08   "West Asian"
                   09   "Korean"
                   10   "Japanese"
                   11   "Visible minority n.i.e"
                   12   "Multiple visible minorities"
                   13   "Not a visible minority"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SLP_005
                   01   "Under 2 hours"
                   02   "2 hours to less than 3 hours"
                   03   "3 hours to less than 4 hours"
                   04   "4 hours to less than 5 hours"
                   05   "5 hours to less than 6 hours"
                   06   "6 hours to less than 7 hours"
                   07   "7 hours to less than 8 hours"
                   08   "8 hours to less than 9 hours"
                   09   "9 hours to less than 10 hours"
                   10   "10 hours to less than 11 hours"
                   11   "11 hours to less than 12 hours"
                   12   "12 hours or more"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SLP_010 SLP_015 SLP_020
                    1   "Never"
                    2   "Rarely"
                    3   "Sometimes"
                    4   "Most of the time"
                    5   "All of the time"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /SMKDVSTP
               999.96   "Valid skip"
               999.97   "Don't know"
               999.98   "Refusal"
               999.99   "Not stated"
              /SMKDVSTY
                   01   "Current daily smoker"
                   02   "Current occasional smoker"
                   03   "Former daily smoker (non-smoker now)"
                   04   "Former occasional smoker (non-smoker now)"
                   05   "Experimental smoker (>1 cig, <100 cig)"
                   06   "Lifetime abstainer (never smoked a whole cigarette)"
                   96   "Valid skip"
                   97   "Don't know"
                   98   "Refusal"
                   99   "Not stated"
              /SMKDVYCS
                  996   "Valid skip"
                  997   "Don't know"
                  998   "Refusal"
                  999   "Not stated"
              /SOR_01
                    1   "Heterosexual"
                    2   "Lesbian or gay"
                    3   "Bisexual"
                    4   "Or please specify"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
              /WTP_50
                    1   "Overweight"
                    2   "Underweight"
                    3   "Just about right"
                    6   "Valid skip"
                    7   "Don't know"
                    8   "Refusal"
                    9   "Not stated"
    .
 
