VARIABLE LABELS
    VERDATE        "Date of file creation"
    REFPER         "Reference period"
    SAMPLEID       "Record identifier"
    INSTANCE       "Person identifier of selected respondent  - health interview"
    COLMODE        "Collection mode - 18+"
    COLMODEY       "Collection mode - 12-17 (youth respondents)"
    COLMODEP       "Collection mode - 12-17 (PMK respondents)"
    COL_LANG       "Collection language"
    GEO_PRV        "Province of residence of respondent"
    GEODVPC        "Postal code - (D)"
    GEODVD16       "2016 Census dissemination area (DA) - (D)"
    GEODVCSD       "2016 Census subdivision (CSD) - (D)"
    GEODVFED       "2016 Census federal electoral district (FED) - (D)"
    GEODVCD        "2016 Census division (CD) - (D)"
    GEODVCMA       "2016 Census metropolitan area (CMA) - (D)"
    GEODVCA        "2016 Census agglomeration (CA) - (D)"
    GEODVSAT       "Statistical area classification type (SAT) - (D)"
    GEODVHR4       "Health region - (D)"
    GEODVP16       "Peer group 2016 - (D)"
    GEODVUR        "Population centre or rural area type - (D)"
    GEODVUR2       "Population centre or rural area type - grouped - (D)"
    GEODVPSZ       "Population centre or rural area classification - (D)"
    GEODVBHA       "British Columbia Health Authority (BCHA) - (D)"
    GEODVHCS       "Ontario home and community care support services (HCCSS) - (D)"
    GEODVSHC       "Ontario HCCSS sub-region - (D)"
    GEODVASZ       "Alberta subzone - (D)"
    SAM_CP         "Sampled collection period"
    ADM_YOI        "Year of interview"
    ADM_MOI        "Month of interview"
    ADM_DOI        "Day of interview"
    SAMDVLNK       "Permission to link data - (D)"
    SAMDVSHR       "Permission to share data - (D)"
    DHHDVHSZ       "Household size - (D)"
    DHHDVLVG       "Living / family arrangement of selected respondent - (D)"
    DHHDV611       "Number of persons in household between 6 and 11 years of age - (D)"
    DHHDVOKD       "Number of persons in household 16 or 17 years of age - (D)"
    DHHDVL12       "Number of persons in household less than 12 years of age - (D)"
    DHHDVYKD       "Number of persons in household less than 16 years of age - (D)"
    DHHDVLE5       "Number of persons in household 5 years old or less - (D)"
    DHHDVA65       "Number of persons in household aged 65 and older - (D)"
    DHHDVAOS       "Age of spouse - (D)"
    DHHDVL18       "Number of persons in household less than 18 years of age - (D)"
    PROXYSEX       "Respondent gender and whether interview conducted by proxy"
    DWL_01A        "Dwelling ownership - own or rent"
    ED_05          "Highest certificate, diploma or degree completed"
    EDDVR3         "Highest level of education - respondent, 3 levels - (D)"
    EDDVH3         "Highest level of education - household, 3 levels - (D)"
    AGE_01A        "Year of birth"
    AGE_01B        "Month of birth"
    AGE_01C        "Day of birth"
    AWCAGE         "Age"
    DHH_SEX        "Sex at birth"
    GDRA_10        "Gender"
    GENDER_2       "Gender - imputed"
    DOMAC          "Main activity (1) - Inclusion Flag - (F)"
    MAC_05         "Main activity - worked at job / business - 12 mo"
    MA_02          "Main activity - 12 mo"
    MA_03          "Worked at job / business - 7 d"
    DOEDC          "School attendance - Inclusion Flag - (F)"
    EDC_10         "Currently attending school / college / CEGEP / university"
    EDC_20         "Student status"
    DOGEN          "General health - Inclusion Flag - (F)"
    GEN_01         "Perceived health"
    GEN_05         "Perceived mental health"
    GEN_10         "Perceived life stress"
    GEN_15         "Perceived stress at work"
    GEN_20         "Sense of belonging to local community"
    DOLSM          "Life satisfaction measures - Inclusion Flag - (F)"
    LSM_01         "Satisfaction with life in general"
    LSMDVSWL       "Satisfaction with life in general (D)"
    DOPRS          "Pregnancy - Inclusion Flag - (F)"
    PRS_05         "Currently pregnant"
    DOHWT          "Height and weight - Inclusion Flag - (F)"
    HWT_05A        "Height (self-reported) - Feet"
    HWT_05B        "Height (self-reported) - Inches"
    HWT_05C        "Height (self-reported) - Centimetres"
    HWT_40A        "Weight (self-reported)"
    HWT_40B        "Weight (self-reported) - unit of measure in pounds or kilograms"
    HWTDVHTM       "Height (metres) - self-reported - (D)"
    HWTDVWTK       "Weight (kilograms) - self-reported - (D)"
    HWTDVBMI       "Body mass index (self-reported) - (D)"
    HWTDVCOL       "BMI classification age 12 to 17 (self-reported) - Cole - (D)"
    HWTDVISW       "BMI classification age 18 + (self-reported) - Intl standard - (D)"
    HWTDVWHO       "BMI classification age 12 to 17 (self-reported) - WHO - (D)"
    HWTDVCOR       "Body mass index (adjusted) - (D)"
    HWTDVBCC       "BMI classification age 18 + (adjusted) - Intl standard - (D)"
    DOWTP          "Weight perception - Inclusion Flag - (F)"
    WTP_50         "Self-perceived weight - overweight / underweight / just about right"
    DOCOV2         "COVID-19 (2) - Inclusion Flag - (F)"
    COV2_005       "Self-perceived mental health - before / during pandemic"
    COV2_10A       "COVID-19 precautions - washes hands more frequently"
    COV2_10B       "COVID-19 precautions - wears a mask in public places"
    COV2_10C       "COVID-19 precautions - keeps a 2 m / 6 ft distance from others"
    COV2_10D       "COVID-19 precautions - avoids crowds / large gatherings"
    COV2_10E       "COVID-19 precautions - avoids leaving house for non-essential reasons"
    COV2_10F       "COVID-19 precautions - works from home"
    COV2_10G       "COVID-19 precautions - uses delivery / curb side pick-up services"
    COV2_10H       "COVID-19 precautions - self-isolates if symptoms"
    COV2_10I       "COVID-19 precautions - other precaution"
    COV2_10J       "COVID-19 precautions - no precautions taken"
    COV2_015       "Has experienced COVID-19 symptoms - last 3 months"
    COV2_020       "Followed public health recommendations while COVID-19 symptoms"
    COV2_038       "Received COVID-19 vaccine"
    COV2_030       "COVID-19 vaccine - requires 1 or 2 doses"
    COV2_035       "COVID-19 vaccine - number of doses received so far"
    COV2_041       "COVID-19 vaccine - main reason why not vaccinated"
    COV2_45A       "COVID-19 vaccine - reasons don't want - not at high risk"
    COV2_45B       "COVID-19 vaccine - reasons don't want - won't be very sick"
    COV2_45C       "COVID-19 vaccine - reasons don't want - pandemic severity overstated"
    COV2_45D       "COVID-19 vaccine - reasons don't want - vaccines are not effective"
    COV2_45E       "COVID-19 vaccine - reasons don't want - vaccines are not safe"
    COV2_45F       "COVID-19 vaccine - reasons don't want - don't trust its effectiveness"
    COV2_45G       "COVID-19 vaccine - reasons don't want - don't trust its safety"
    COV2_45H       "COVID-19 vaccine - reasons don't want -  philosophical / religious"
    COV2_45I       "COVID-19 vaccine - reasons don't want - other reason"
    COV2_040       "COVID-19 vaccine - likeliness of getting it"
    COV2_55A       "COVID-19 vaccine - main reason for not getting second dose"
    COV2_060       "COVID-19 vaccine - likeliness of getting 2nd dose"
    DOCOV3         "COVID-19 (3) - Inclusion Flag - (F)"
    COV3_005       "COVID-19 vaccine - likeliness of getting additional dose if offered"
    DOCCC          "Chronic conditions - Inclusion Flag - (F)"
    CCC_05         "Has diabetes"
    CCC_10         "Diabetes - age first diagnosed"
    CCC_15         "Diabetes - diagnosed - during pregnancy"
    CCC_20         "Diabetes - diagnosed - other than during pregnancy"
    CCC_30         "Diabetes - time between diagnosis and start of insulin"
    CCC_35         "Diabetes - currently takes insulin"
    CCC_40         "Diabetes - took pills to control blood sugar - 1 mo"
    CCC_45         "Has been diagnosed with cancer - lifetime"
    CCC_50         "Cancer - age first diagnosed"
    CCC_55         "Cancer - received treatment - 12 mo"
    CCC_60A        "Type of cancer - breast"
    CCC_65A        "Type of cancer - prostate"
    CCC_60B        "Type of cancer - colorectal"
    CCC_60C        "Type of cancer - skin - melanoma"
    CCC_60D        "Type of cancer - skin - non-melanoma"
    CCC_60E        "Type of cancer - ovarian"
    CCC_60F        "Type of cancer - cervical"
    CCC_60G        "Type of cancer - uterine"
    CCC_60H        "Type of cancer - lung"
    CCC_60I        "Type of cancer - other"
    CCC_65         "Has heart disease"
    CCC_70         "Heart disease - age first diagnosed"
    CCC_75         "Has had a heart attack - lifetime"
    CCC_80         "Has high blood pressure"
    CCC_85         "High blood pressure - took medication - 1 mo"
    CCC_90         "Has had high blood cholesterol - lifetime"
    CCC_95         "Suffers from the effects of a stroke"
    CCC_100        "Has osteoporosis"
    CCC_105        "Has fibromyalgia"
    CCC_110        "Fibromyalgia - age first symptoms"
    CCC_115        "Fibromyalgia - age first diagnosed"
    CCC_120        "Has arthritis (e.g. osteoarthritis, rheumatoid arthritis, gout)"
    CCC_125        "Has back problems (excluding scoliosis, fibromyalgia and arthritis)"
    CCC_130        "Back problems - diagnosed by health professional"
    CCC_135        "Has a mood disorder (depression, bipolar, mania, dysthymia)"
    CCCDVDIA       "Diabetes type - 12 months - (D)"
    DOCC1          "Chronic conditions (1) - Inclusion Flag - (F)"
    CC1_140        "Has an anxiety disorder (phobia, panic, generalized anxiety)"
    CC1_145        "Has post-traumatic stress disorder (PTSD)"
    CC1_150        "Has Alzheimer's Disease / other dementia"
    CC1_155        "Has chronic fatigue syndrome"
    CC1_160        "Chronic fatigue syndrome - age first symptoms"
    CC1_165        "Chronic fatigue syndrome - age first diagnosed"
    CC1_170        "Has multiple chemical sensitivities (MCS)"
    CC1_175        "Multiple chemical sensitivities - age first symptoms"
    CC1_180        "Multiple chemical sensitivities- age first diagnosed"
    DOEAH          "Eating habits - Inclusion Flag - (F)"
    EAH_05A        "Ate food from a restaurant - num of times - 30 d"
    EAH_05B        "Ate food from a restaurant - reporting period"
    EAH_10A        "Drank pure fruit juice - num of times - 30 d"
    EAH_10B        "Drank pure fruit juice - reporting period"
    EAH_15A        "Drank fruit flavoured / sports drinks - num of times - 30 d"
    EAH_15B        "Drank fruit flavoured / sports drinks - reporting period"
    EAH_20A        "Drank regular soft drinks - num of times - 30 d"
    EAH_20B        "Drank regular soft drinks - reporting period"
    EAH_25A        "Drank sweetened coffee drinks / iced tea - num of times - 30 d"
    EAH_25B        "Drank sweetened coffee drinks / iced tea - reporting period"
    EAH_30A        "Drank energy drinks - num of times - 30 d"
    EAH_30B        "Drank energy drinks - reporting period"
    EAH_35A        "Drank chocolate milk - num of times - 30 d"
    EAH_35B        "Drank chocolate milk - reporting period"
    EAH_40A        "Ate fruits - num of times - 30 d"
    EAH_40B        "Ate fruits - reporting period"
    EAH_45A        "Ate dark green vegetables - num of times - 30 d"
    EAH_45B        "Ate dark green vegetables - reporting period"
    EAH_50A        "Ate orange-coloured vegetables - num of times - 30 d"
    EAH_50B        "Ate orange-coloured vegetables - reporting period"
    EAH_55A        "Ate starchy vegetables - num of times - 30 d"
    EAH_55B        "Ate starchy vegetables - reporting period"
    EAH_60A        "Ate other vegetables - num of times - 30 d"
    EAH_60B        "Ate other vegetables - reporting period"
    EAHDVCHO       "Daily consumption - chocolate milk - (D)"
    EAHDVFFD       "Daily consumption - fruit flavoured drinks or sports drinks - (D)"
    EAHDVFRU       "Daily consumption - fruit - (D)"
    EAHDVGRN       "Daily consumption - dark green vegetables - (D)"
    EAHDVJUI       "Daily consumption - pure fruit juice - (D)"
    EAHDVORA       "Daily consumption - orange-coloured vegetables - (D)"
    EAHDVSCD       "Daily consumption - sweetened coffee drinks / iced tea - (D)"
    EAHDVSOD       "Daily consumption - regular soft drinks - (D)"
    EAHDVSTA       "Daily consumption - starchy vegetables - (D)"
    EAHDVVEG       "Daily consumption - other vegetables - (D)"
    EAHDVEND       "Daily consumption - energy drinks - (D)"
    EAHDVBVT       "Daily consumption - beverages - (D)"
    EAHDVBVG       "Grouping of total daily consumption - beverages - (D)"
    EAHDVFVT       "Daily consumption - fruits and vegetables - (D)"
    EAHDVFVG       "Grouping of total daily consumption - fruits and vegetables - (D)"
    DOPAA          "Physical activities - adults - Inclusion Flag - (F)"
    PAA_05         "Active transportation - 7 d"
    PAA_10A        "Active transportation - Monday"
    PAA_10B        "Active transportation - Tuesday"
    PAA_10C        "Active transportation - Wednesday"
    PAA_10D        "Active transportation - Thursday"
    PAA_10E        "Active transportation - Friday"
    PAA_10F        "Active transportation - Saturday"
    PAA_10G        "Active transportation - Sunday"
    PAA_15A        "Active transportation  - 7 d - total - hours"
    PAA_15B        "Active transportation - 7 d - total - minutes"
    PAA_30         "Sports / fitness / recreational physical act - 7 d"
    PAA_35         "Sports / fitness / recreational physical act - sweat"
    PAA_40A        "Sports / fitness / recreational physical act - Monday"
    PAA_40B        "Sports / fitness / recreational physical act - Tuesday"
    PAA_40C        "Sports / fitness / recreational physical act  - Wednesday"
    PAA_40D        "Sports / fitness / recreational physical act - Thursday"
    PAA_40E        "Sports / fitness / recreational physical act - Friday"
    PAA_40F        "Sports / fitness / recreational physical act - Saturday"
    PAA_40G        "Sports / fitness / recreational physical act - Sunday"
    PAA_45A        "Sports / fitness / recreational physical act - 7 d - total - hours"
    PAA_45B        "Sports / fitness / recreational physical act - 7 d - total - minutes"
    PAA_60         "Other physical activities - 7 d"
    PAA_65         "Other physical activities - sweat"
    PAA_70A        "Other physical activities -  Monday"
    PAA_70B        "Other physical activities - Tuesday"
    PAA_70C        "Other physical activities - Wednesday"
    PAA_70D        "Other physical activities - Thursday"
    PAA_70E        "Other physical activities - Friday"
    PAA_70F        "Other physical activities - Saturday"
    PAA_70G        "Other physical activities - Sunday"
    PAA_75A        "Other physical activities - 7 d - total - hours"
    PAA_75B        "Other physical activities - 7 d - total - minutes"
    PAA_95         "Physical activities - vigorous intensity"
    PAA_100A       "Physical activities - vigorous intensity - 7 d - total - hours"
    PAA_100B       "Physical activities - vigorous intensity - 7 d - total - minutes"
    PAADVMVA       "Total minutes - moderate to vigorous physical activities - 7 d - (D)"
    PAADVACV       "Physical activity indicator - (D)"
    PAADVAC2       "Alternate physical activity indicator - (D)"
    PAADVVIG       "Total minutes - vigorous physical activities - 7 d - (D)"
    PAADVVOL       "Volume of weekly activity - 7 d (METs*mins/week) - (D)"
    PAADVWHO       "Physically active based on WHO guidelines - (D)"
    DOPAY          "Physical activities - youth - Inclusion Flag - (F)"
    PAY_05A        "Physical activities - attend school - 7 d"
    PAY_05B        "Physical activities - attend a day camp - 7 d"
    PAY_05C        "Physical activities  - worked, paid or unpaid - 7 d"
    PAY_05D        "Physical activities - none of the above - 7 d"
    PAY_10         "Active transportation - 7 d"
    PAY_15AA       "Active transportation - hours - yesterday"
    PAY_15AB       "Active transportation - minutes - yesterday"
    PAY_15BA       "Active transportation - hours - 2 d"
    PAY_15BB       "Active transportation - minutes - 2 d"
    PAY_15CA       "Active transportation - hours - 3 d"
    PAY_15CB       "Active transportation - minutes - 3 d"
    PAY_15DA       "Active transportation - hours - 4 d"
    PAY_15DB       "Active transportation - minutes - 4 d"
    PAY_15EA       "Active transportation - hours - 5 d"
    PAY_15EB       "Active transportation - minutes - 5 d"
    PAY_15FA       "Active transportation - hours - 6 d"
    PAY_15FB       "Active transportation - minutes - 6 d"
    PAY_15GA       "Active transportation - hours - 7 d"
    PAY_15GB       "Active transportation - minutes - 7 d"
    PAY_20         "Recreational physical activities - school / camp - 7 d"
    PAY_25         "Recreational physical activities - school / camp - sweat"
    PAY_30AA       "Recreational physical activities - school / camp - hours - yesterday"
    PAY_30AB       "Recreational physical activities - school / camp - minutes - yesterday"
    PAY_30BA       "Recreational physical activities - school / camp - hours - 2 d"
    PAY_30BB       "Recreational physical activities - school / camp - minutes - 2 d"
    PAY_30CA       "Recreational physical activities - school / camp - hours - 3 d"
    PAY_30CB       "Recreational physical activities - school / camp - minutes - 3 d"
    PAY_30DA       "Recreational physical activities - school / camp - hours - 4 d"
    PAY_30DB       "Recreational physical activities - school / camp - minutes - 4 d"
    PAY_30EA       "Recreational physical activities - school / camp - hours - 5 d"
    PAY_30EB       "Recreational physical activities - school / camp - minutes - 5 d"
    PAY_30FA       "Recreational physical activities - school / camp - hours - 6 d"
    PAY_30FB       "Recreational physical activities - school / camp - minutes - 6 d"
    PAY_30GA       "Recreational physical activities - school / camp - hours - 7 d"
    PAY_30GB       "Recreational physical activities - school / camp - minutes - 7 d"
    PAY_35         "Physical activities - leisure time - 7 d"
    PAY_40         "Physical activities - leisure time - sweat"
    PAY_45AA       "Physical activities - leisure time - hours - yesterday"
    PAY_45AB       "Physical activities - leisure time - minutes - yesterday"
    PAY_45BA       "Physical activities - leisure time - hours - 2 d"
    PAY_45BB       "Physical activities - leisure time - minutes - 2 d"
    PAY_45CA       "Physical activities - leisure time - hours - 3 d"
    PAY_45CB       "Physical activities - leisure time - minutes - 3 d"
    PAY_45DA       "Physical activities - leisure time - hours - 4 d"
    PAY_45DB       "Physical activities - leisure time - minutes - 4 d"
    PAY_45EA       "Physical activities - leisure time - hours - 5 d"
    PAY_45EB       "Physical activities - leisure time - minutes - 5 d"
    PAY_45FA       "Physical activities - leisure time - hours - 6 d"
    PAY_45FB       "Physical activities - leisure time - minutes - 6 d"
    PAY_45GA       "Physical activities - leisure time - hours - 7 d"
    PAY_45GB       "Physical activities - leisure time - minutes - 7 d"
    PAY_50         "Other physical activities - 7 d"
    PAY_55         "Other physical activities - sweat"
    PAY_60AA       "Other physical activities - hours - yesterday"
    PAY_60AB       "Other physical activities - minutes - yesterday"
    PAY_60BA       "Other physical activities - hours - 2 d"
    PAY_60BB       "Other physical activities - minutes - 2 d"
    PAY_60CA       "Other physical activities - hours - 3 d"
    PAY_60CB       "Other physical activities - minutes - 3 d"
    PAY_60DA       "Other physical activities - hours - 4 d"
    PAY_60DB       "Other physical activities - minutes - 4 d"
    PAY_60EA       "Other physical activities - hours - 5 d"
    PAY_60EB       "Other physical activities - minutes - 5 d"
    PAY_60FA       "Other physical activities - hours - 6 d"
    PAY_60FB       "Other physical activities - minutes - 6 d"
    PAY_60GA       "Other physical activities - hours - 7 d"
    PAY_60GB       "Other physical activities - minutes - 7 d"
    PAY_65         "Physical activities - vigorous intensity"
    PAY_70A        "Physical activities - vigorous intensity - yesterday"
    PAY_70B        "Physical activities - vigorous intensity - 2 d"
    PAY_70C        "Physical activities - vigorous intensity - 3 d"
    PAY_70D        "Physical activities - vigorous intensity - 4 d"
    PAY_70E        "Physical activities - vigorous intensity - 5 d"
    PAY_70F        "Physical activities - vigorous intensity - 6 d"
    PAY_70G        "Physical activities - vigorous intensity - 7 d"
    PAY_75A        "Physical activities - vigorous intensity - 7 d - total - hours"
    PAY_75B        "Physical activities - vigorous intensity - 7 d - total - minutes"
    DOSBE          "Sedentary behaviours - Inclusion Flag - (F)"
    SBE_005        "Free time sitting/lying watching screen - school/work day - 7d"
    SBE_010        "Free time sitting/lying watching screen - not school/work day - 7d"
    DOSLP          "Sleep - Inclusion Flag - (F)"
    SLP_005        "Number of hours usually spent sleeping per night"
    SLP_010        "Trouble going to sleep or staying asleep - frequency"
    SLP_015        "Refreshing sleep - frequency"
    SLP_020        "Difficulty staying awake - frequency"
    DOCSS          "Current smoking status - Inclusion Flag - (F)"
    CSS_05         "Smoked a whole cigarette - lifetime"
    CSS_10         "Smoked first whole cigarette - Age"
    CSS_15         "Smoked more than 100 cigarettes - lifetime"
    CSS_20         "Smoked - frequency - 30 d"
    CSS_25         "Num of cigarettes smoked daily (daily smoker)"
    CSS_35         "Smoked 1 cigarette or more (occasional smoker) - Num of days - 30 d"
    CSS_30         "Num of cigarettes smoked daily (occasional smoker)"
    CSS_40         "Made serious attempt to stop smoking - 12 mo"
    DOSPU          "Smoking - past use - Inclusion Flag - (F)"
    SPU_05         "Smoked daily - lifetime (occasional / former smoker)"
    SPU_10A        "Stopped smoking - month (former occasional smoker)"
    SPU_10B        "Stopped smoking - year (former occasional smoker)"
    SPU_15         "Began smoking daily - age (daily / former daily smoker)"
    SPU_20         "Num of cigarettes smoked daily (former daily smoker)"
    SPU_25A        "Stopped smoking daily - month (former daily smoker)"
    SPU_25B        "Stopped smoking daily - year (former daily smoker)"
    SPU_30         "Quit smoking completely (former daily smoker)"
    SPU_35A        "Quit smoking completely - month (former daily smoker)"
    SPU_35B        "Quit smoking completely - year (former daily smoker)"
    SMKDVSTY       "Smoking status (type 2) - traditional definition - (D)"
    SMKDVYCS       "Num of years respondent has smoked daily - (D)"
    SMKDVSTP       "Num of years since respondent stopped smoking completely - (D)"
    DOECV          "Electronic cigarettes and vaping - Inclusion Flag - (F)"
    ECV_05         "Tried e-cigarette / vaping device - life"
    ECV_10         "Tried e-cigarette / vaping device - age"
    ECV_15         "Used e-cigarette / vaping device - freq - 30 d"
    ECV_20         "Used e-cigarette - llast time - nicotine"
    ECVDVSMK       "E-Cigarette / vaping device and cigarette use - (D)"
    DOECV2         "Electronic cigarette and vaping 2 - Inlcusion Flag - (F)"
    ECV2_05A       "Vape - e-liquid with nicotine - num of days - 30 d"
    ECV2_05B       "Vape - e-liquid without nicotine - num of days - 30 d"
    ECV2_05C       "Vape - e-liquid unkown content- num of days - 30 d"
    ECV2_10        "Tried to quit smoking with e-cigarette / vaping device - 12 mo"
    ECV2_15        "Tried first - e-cigarette / vaping device or cigarette"
    DOALC          "Alcohol use - Inclusion Flag - (F)"
    ALC_05         "Had a drink - lifetime"
    ALC_10         "Drank alcohol - 12 mo"
    ALC_15         "Drank alcohol - frequency - 12 mo"
    ALC_20         "Drank 5+ / 4+ drinks one occasion - frequency - 12 mo"
    ALCDVTTM       "Type of drinker - 12 months - (D)"
    DOPRM          "Medication use - pain relievers - Inclusion Flag - (F)"
    PRM_10         "Taken pain relievers - codeine products - 12 mo"
    PRM_15         "Taken pain relievers - oxycodone products - 12 mo"
    PRM_20         "Taken pain relievers - fentanyl products - 12 mo"
    PRM_25         "Taken pain relievers - other opioid products - 12 mo"
    PRM_30         "Taken pain relievers - frequency - 12 mo"
    PRM_35         "Taken pain relievers - prescribed - 12 mo"
    PRM_40A        "Taken pain relievers - higher dose - 12 mo"
    PRM_40B        "Taken pain relievers - more often - 12 mo"
    PRM_50         "Taken pain relievers - reasons other than pain relief - 12 mo"
    PRM_55         "Taken pain relievers - tampered - 12 mo"
    PRMDV12M       "Pain relief medication use - 12 mo - (D)"
    DOCAN          "Cannabis use - Inclusion Flag - (F)"
    CAN_05         "Used cannabis - lifetime"
    CAN_05A        "Used cannabis - once or more - lifetime"
    CAN_05B        "Used cannabis - first time - age"
    CAN_05C        "Used cannabis - 12 mo"
    CAN_10         "Used cannabis - frequency - 12 mo"
    CAN_15A        "Used cannabis - method - smoked - 12 mo"
    CAN_15B        "Used cannabis - method - vaporized - 12 mo"
    CAN_15C        "Used cannabis - method - swallowed - 12 mo"
    CAN_15D        "Used cannabis - method - absorbed - 12 mo"
    CAN_15E        "Used cannabis - method - other - 12 mo"
    CAN_15BA       "Used cannabis - vaporized - dried flower, leaf"
    CAN_15BB       "Used cannabis - vaporized - cannabis liquid"
    CAN_15BC       "Used cannabis -  vaporized - cannabis solid"
    CAN_20         "Used cannabis - method used most often - 12 mo"
    CAN_25A        "Used cannabis - product - Dried flower or leaf - 12 mo"
    CAN_25B        "Used cannabis - product - hashish - 12 mo"
    CAN_25C        "Used cannabis - product - cannabis oil - 12 mo"
    CAN_25D        "Used cannabis - product - cannabis vape pens / cartridges - 12 mo"
    CAN_25E        "Used cannabis - product - cannabis concentrates - 12 mo"
    CAN_25F        "Used cannabis - product - àcannabis edible food products - 12 mo"
    CAN_25G        "Used cannabis - product - cannabis beverages - 12 mo"
    CAN_25H        "Used cannabis - product - topicals - 12 mo"
    CAN_25I        "Used cannabis - product - other - 12 mo"
    CAN_30         "Used cannabis - purpose - 12 mo"
    CAN_35A        "Used cannabis - medical purpose - pain - 12 mo"
    CAN_35B        "Used cannabis - medical purpose - nausea vomiting - 12 mo"
    CAN_35C        "Used cannabis - medical purpose- lack of appetite - 12 mo"
    CAN_35D        "Used cannabis - medical purpose- headaches / migraines - 12 mo"
    CAN_35E        "Used cannabis - medical purpose - muscle spasms / seizures - 12 mo"
    CAN_35F        "Used cannabis - medical purpose- anxiety / depression - 12 mo"
    CAN_35G        "Used cannabis - medical purpose- symptoms of PTSD - 12 mo"
    CAN_35H        "Used cannabis - medical purpose- problems sleeping - 12 mo"
    CAN_35I        "Used cannabis - purpose- opioid withdrawal symptoms - 12 mo"
    CAN_35J        "Used cannabis - medical purpose- other - 12 mo"
    CAN_40         "Used cannabis - has a medical document for medical purposes use"
    CAN_45         "Used cannabis - num of days - 30 d"
    CAN_50         "Used cannabis - daily - age"
    CANDVF12       "Cannabis - frequency of use - 12 mo - (D)"
    CANDVLEO       "Cannabis use - lifetime (excluding ""just once"") - (D)"
    CANDVLIO       "Cannabis use - lifetime (including ""just once"") - (D)"
    CANDVLS3       "Cannabis user status - lifetime - 3 categories - (D)"
    CANDVLS5       "Cannabis user status - lifetime - 5 categories - (D)"
    CANDVYEO       "Cannabis use - 12 mo (excluding ""just once"") - (D)"
    CANDVYIO       "Cannabis use - 12 mo (including ""just once"") - (D)"
    DOMEX          "Maternal experiences - Inclusion Flag - (F)"
    MEX_05         "Takes vitamin supplement with folic acid"
    MEX_10         "Gave birth - last 5 years"
    MEX_12         "Single or multiple birth - last pregnancy"
    MEX_20         "Baby's date of birth - day"
    MEX_25         "Baby's date of birth - month"
    MEX_30         "Baby's date of birth - year"
    MEX_40         "Took folic acid supplement - 3 mo before pregnancy"
    MEX_50         "Took folic acid supplement - first 3 mo of pregnancy"
    MEX_65         "Took iron supplement - during pregnancy"
    MEX_70         "Weight - before pregnancy"
    MEX_75         "Weight - before pregnancy - pounds / kilograms"
    MEX_80         "Weight - gained during pregnancy"
    MEX_85         "Weight - gained during pregnancy - pounds / kilograms"
    MEX_90         "Co-sleeping with baby less than 12 mo - frequency"
    MEX_100        "Breastfed last baby"
    MEX_105        "Did not breastfeed last baby - reason"
    MEX_110        "Still breastfeeding last baby"
    MEX_115A       "Stopped breastfeeding - baby's age"
    MEX_115B       "Stopped breastfeeding - baby's age - time period"
    MEX_120        "Stopped breastfeeding - reason"
    MEX_125        "Gave baby vitamin D supplement - less than 1 yr old"
    MEX_150        "Introduced liquids to baby - during breastfeeding"
    MEX_155        "Introduced liquids to baby - baby's age"
    MEX_160        "Introduced liquids to baby - baby's age - time period"
    MEX_170        "Introduced solids to baby"
    MEX_175        "Introduced solids to baby - baby's age"
    MEX_180        "Introduced solids to baby - baby's age - time period"
    MEX_190        "Introduced solids to baby - first solid food"
    MEXDVBM6       "Exclusively breastfed for 6 months (or more) - (D)"
    MEXDVLBM       "Length of exclusive breastfeeding - (D)"
    MEXDVWBK       "Weight before pregnancy - kilograms - (D)"
    MEXDVWGK       "Weight gained during pregnancy - kilograms - (D)"
    DOMXS          "Maternal experiences - Smoking - Inclusion Flag - (F)"
    MXS_05         "Smoked cigarettes - 3 months before last pregnancy"
    MXS_10         "Smoked cigarettes - 3 months before last pregnancy - frequency"
    MXS_15         "Smoked cigarettes - after finding out about pregnancy"
    MXS_20         "Smoked cigarettes - after finding out about pregnancy - frequency"
    MXS_35         "Exposure to second-hand smoke during pregnancy"
    DOMXA          "Maternal experiences - Alcohol use - Inclusion Flag - (F)"
    MXA_05         "Drank alcohol - 3 months before last pregnancy"
    MXA_10         "Drank alcohol - 3 months before last pregnancy - frequency"
    MXA_12         "Drank alcohol - 3 months before last pregnancy - num of drinks"
    MXA_15         "Drank alcohol - after finding out about pregnancy - frequency"
    MXA_20         "Drank alcohol - after finding out about pregnancy - frequency"
    MXA_22         "Drank alcohol - after finding out about pregnancy - num of drinks"
    MXA_35         "Drank alcohol - while breastfeeding / since giving birth"
    MXA_40         "Drank alcohol - while breastfeeding / since giving birth - frequency"
    MXA_42         "Drank alcohol - while breastfeeding / since giving birth - num drinks"
    DORHC          "Regular health care provider - Inclusion Flag - (F)"
    RHC_05         "Regular health care provider"
    DOLMAM         "Labour market activities - Inclusion Flag - (F)"
    LMAM_01        "Worked at job / business - past week"
    LMAM_02        "Absent from job / business - past week"
    LMAM_03        "Absent from job / business - reason - past week"
    DOLMA3         "Labour market activities (LMA3) - Inclusion Flag - (F)"
    LMA3_01        "Employee or self-employed"
    DOLMA4         "Labour market activities (LMA4) - Inclusion Flag - (F)"
    LMA4FQ01       "Response entered - name of business (self-employed) - (F)"
    LMA4FQ02       "Response entered - name of company / business / person - (F)"
    LMA4FQ03       "Response entered - type of business / industry / service - (F)"
    LBFCSIC        "North American Industry Classification System (NAICS) 2017"
    DOLMA5         "Labour market activities (LMA5) - Inclusion Flag - (F)"
    LMA5FQ01       "Response entered - type of work - (F)"
    LMA5FQ02       "Response entered - main activities / duties - (F)"
    LBFCSOC        "National Occupation Classification (NOC) 2016"
    DOLMA6         "Labour market activities (LMA6) - Inclusion Flag - (F)"
    LMA6_01        "Usual num of hours worked / week - current main job"
    DOLBF          "Labour market activities (LBF) - Inclusion Flag - (F)"
    LBF_11         "Had more than one job / business - past week"
    LBF_12         "Usual num of hours worked / week - current other job"
    LBFDVHPW       "Total usual number of hours worked / week - (D)"
    LBFDVING       "Industry group - (D)"
    LBFDVOCG       "Occupation group - (D)"
    LBFDVPFT       "Full-time / part-time working status (for total usual hours) - (D)"
    LBFDVWSS       "Working status last week - (D)"
    DOLM           "Telework - Inclusion Flag - (F)"
    LM_025         "Location worked most hours - 30 d"
    DOIM           "Place of birth, immigration and citizenship - Inclusion Flag - (F)"
    IM_01A         "Country of birth - Canada / Outside"
    IM_01A1        "Province / territory of birth"
    SDCCCOB        "Country of birth - coded"
    IM_02          "Year first came to live in Canada"
    IM_03          "Landed immigrant - life"
    IM_04          "Year first became a landed immigrant"
    IM_05A         "Canadian citizen"
    IM_05B         "Citizen of country other than Canada"
    IM_05A1        "Canadian citizen by birth / natualization"
    SDCCCOC        "Country of citizenship - coded - excludes Canada"
    SDCDVCB        "Country of birth - grouped - (D)"
    SDCDVIMM       "Immigrant flag - (D)"
    SDCDVRES       "Number of years in Canada since immigration - (D)"
    SDCDVALI       "Age - respondent first became a landed immigrant in Canada - (D)"
    SDCDVABT       "Aboriginal Identity - (D)"
    SDCDVVM        "Visible minority group of respondent - (D)"
    SDCDVFLA       "Visible minority flag - (D)"
    SDCDVLHM       "Language(s) spoken most often at home - (D)"
    SDCDVFL1       "Language 1st learned at home in childhood - mother tongue - (D)"
    SDCDVFLS       "First official language spoken - (D)"
    DOABM          "Indigenous identity - Inclusion Flag - (F)"
    ABM_01A        "No indigenous identity"
    ABM_01B        "Indigenous identity - First Nations"
    ABM_01C        "Indigenous identity - Métis"
    ABM_01D        "Indigenous identity- Inuk (Inuit)"
    DOPG           "Population group - Inclusion Flag - (F)"
    PG_05A         "Belonging racial / cultural groups - White"
    PG_05B         "Belonging racial / cultural groups - South Asian"
    PG_05C         "Belonging racial / cultural groups - Chinese"
    PG_05D         "Belonging racial / cultural groups - Black"
    PG_05E         "Belonging racial / cultural groups - Filipino"
    PG_05F         "Belonging racial / cultural groups - Arab"
    PG_05G         "Belonging racial / cultural groups - Latin American"
    PG_05H         "Belonging racial / cultural groups - Southeast Asian"
    PG_05I         "Belonging racial / cultural groups - West Asian"
    PG_05J         "Belonging racial / cultural groups - Korean"
    PG_05K         "Belonging racial / cultural groups - Japanese"
    VMRNIE         "Belonging racial / cultural groups - visible minority n.i.e."
    VMROTHER       "Belonging racial / cultural groups - not a visible minority"
    DOLAN          "Language - Inclusion Flag - (F)"
    LAN_01         "Knowledge of official languages"
    LAN_02A        "Language most often spoken at home - English"
    LAN_02B        "Language most often spoken at home - French"
    LAN_02C        "Language most often spoken at home - Other"
    LAN_04A        "Mother tongue - English"
    LAN_04B        "Mother tongue - French"
    LAN_04C        "Mother tongue - Other"
    DOSOR          "Sexual orientation - Inclusion Flag - (F)"
    SOR_01         "Sexual orientation"
    DOHMC          "Home care services - Inclusion Flag - (F)"
    HMC_005A       "Home care services received - nursing care - 12 mo"
    HMC_005B       "Home care services received - other health care - 12 mo"
    HMC_005C       "Home care services received - medical equipment - 12 mo"
    HMC_005D       "Home care services received - personal / home support - 12 mo"
    HMC_005E       "Home care services received - palliative / end-of-life care - 12 mo"
    HMC_005F       "Home care services received - other services - 12 mo"
    HMC_005G       "No one in household received any home care services - 12 mo"
    HMC_010A       "Person who received home care services - nursing care"
    HMC_010B       "Person who received home care services - other health care"
    HMC_010C       "Person who received home care services - medical equipment"
    HMC_010D       "Person who received home care services - personal / home support"
    HMC_010E       "Person who received home care services - palliative care"
    HMC_010F       "Person who received home care services - other services"
    HMC_015A       "Duration services provided - nursing care"
    HMC_015B       "Duration services provided - other health care"
    HMC_015C       "Duration services provided - medical equipment"
    HMC_015D       "Duration services provided - personal / home support"
    HMC_015E       "Duration services provided - palliative care"
    HMC_015F       "Duration services provided - other services"
    HMC_020A       "Monthly cost services provided - nursing care - 12 mo"
    HMC_020B       "Monthly cost services provided - other health care - 12 mo"
    HMC_020C       "Monthly cost services provided - medical equipment - 12 mo"
    HMC_020D       "Monthly cost services provided - personal / home support - 12 mo"
    HMC_020E       "Monthly cost services provided - palliative care - 12 mo"
    HMC_020F       "Monthly cost services provided - other services - 12 mo"
    HMC_025A       "Who paid home care services - out of own pocket"
    HMC_025B       "Who paid home care services - family / friend in same household"
    HMC_025C       "Who paid home care services - someone living outside the household"
    HMC_025D       "Who paid home care services - insurance"
    HMC_025E       "Who paid home care services - government"
    HMC_025F       "Who paid home care services - other"
    HMC_030        "Satisfaction with home care services received"
    HMC_035A       "Unsatisfactory home care services - poor quality"
    HMC_035B       "Unsatisfactory home care services - needs not addressed"
    HMC_035C       "Unsatisfactory home care services - insufficient services"
    HMC_035D       "Unsatisfactory home care services - long wait time"
    HMC_035E       "Unsatisfactory home care services  - other reason"
    HMC_037        "Home care services helped stay at home"
    HMC_038A       "Home care services didn't help stay at home - poor quality"
    HMC_038B       "Home care services didn't help stay at home - needs not addressed"
    HMC_038C       "Home care services didn't help stay at home - insufficient services"
    HMC_038D       "Home care services didn't help stay at home - long wait time"
    HMC_038E       "Home care services didn't help stay at home - cost too high"
    HMC_038F       "Home care services didn't help stay at home - other reason"
    HMC_040        "Perception home care services needed but not received - 12 mo"
    HMC_045        "Home care services needed - for who"
    HMC_050A       "Home care services needed - nursing care"
    HMC_050B       "Home care services needed - other health care"
    HMC_050C       "Home care services needed - medical equipment"
    HMC_050D       "Home care services needed - personal / home support"
    HMC_050E       "Home care services needed - palliative / end-of-life care"
    HMC_050F       "Home care services needed - other services"
    HMC_055A       "Home care services not received - not available in the area"
    HMC_055B       "Home care services not received - not available at time required"
    HMC_055C       "Home care services not received - waiting time too long"
    HMC_055D       "Home care services not received - cost"
    HMC_055E       "Home care services not received - didn't get around to it"
    HMC_055F       "Home care services not received - didn't know where to go"
    HMC_055G       "Home care services not received - language barrier"
    HMC_055H       "Home care services not received - decided not to seek services"
    HMC_055I       "Home care services not received - doctor didn't think was necessary"
    HMC_055J       "Home care services not received - not eligible for home care"
    HMC_055K       "Home care services not received - still waiting for home care"
    HMC_055L       "Home care services not received - other"
    HMC_060A       "Home care services provider - govt Home Care Program"
    HMC_060B       "Home care services provider - private agency"
    HMC_060C       "Home care services provider - family member / friend / neighbour"
    HMC_060D       "Home care services provider - volunteer organization"
    HMC_060E       "Home care services provider - nowhere / did not try"
    HMC_060F       "Home care services provider - other"
    HMCDVVRH       "Received home care services - (D)"
    HMCDVHLP       "Households where home care services helped recipients stay home - (D)"
    DOFSC          "Food security - Inclusion Flag - (F)"
    FSC_10         "Worried food would run out - 12 mo"
    FSC_15         "Food didn't last and no money to buy more - 12 mo"
    FSC_20         "Could not afford to eat balanced meals - 12 mo"
    FSC_25         "Relied on few kinds of low-cost food to feed children - 12 mo"
    FSC_30         "Could not feed children a balanced meal - 12 mo"
    FSC_35         "Children were not eating enough - 12 mo"
    FSC_40         "Adults skipped meals or cut size - 12 mo"
    FSC_45         "Adults skipped meals or cut size - frequency - 12 mo"
    FSC_50         "Ate less than felt should - 12 mo"
    FSC_55         "Was hungry but couldn't afford enough food - 12 mo"
    FSC_60         "Lost weight because not enough money for food - 12 mo"
    FSC_65         "Adults did not eat for whole day - 12 mo"
    FSC_70         "Adults did not eat whole day - frequency - 12 mo"
    FSC_75         "Cut size of children's meals - 12 mo"
    FSC_80         "Children skipped meals - 12 mo"
    FSC_85         "Children skipped meals - frequency - 12 mo"
    FSC_90         "Children were hungry but could not afford more food - 12 mo"
    FSC_95         "Children did not eat for whole day - 12 mo"
    FSCDVAF2       "Food security - adult status (including marginally) - (D)"
    FSCDVCF2       "Food security - child status (including marginally) - (D)"
    FSCDVHF2       "Household food security status (including marginally) - (D)"
    DOINC          "Total household income - Inclusion Flag - (F)"
    INC_005A       "Source household income - wages and salaries"
    INC_005B       "Source household income - self-employment"
    INC_005C       "Source household income - dividends and interest"
    INC_005D       "Source household income - employment insurance"
    INC_005E       "Source household income - workers' compensation"
    INC_005F       "Source household income - Canada / Quebec Pension Plan"
    INC_005G       "Source household income - job-related retirement pensions"
    INC_005H       "Source household income - RRSP / RRIF"
    INC_005I       "Source household income - Old Age Security / GIS"
    INC_005J       "Source household income - social assistance / welfare"
    INC_005K       "Source household income - Child Tax Benefit"
    INC_005L       "Source household income - child support"
    INC_005M       "Source household income - alimony"
    INC_005N       "Source household income - other"
    INC_005O       "Source household income - none"
    INC_010        "Source household income - supplement for people with disabilities"
    INC_015        "Household income - main source"
    INC_021        "Total household income before taxes - best estimate"
    INC_025A       "Source personal income - wages and salaries"
    INC_025B       "Source personal income - self-employment"
    INC_025C       "Source personal income - dividends and interest"
    INC_025D       "Source personal income - employment insurance"
    INC_025E       "Source personal income - workers' compensation"
    INC_025F       "Source personal income - Canada / Quebec Pension Plan"
    INC_025G       "Source personal income - job-related retirement pensions"
    INC_025H       "Source personal income - RRSP / RRIF"
    INC_025I       "Source personal income - Old Age Security / GIS"
    INC_025J       "Source personal income - social assistance / welfare"
    INC_025K       "Source personal income - Child Tax Benefit"
    INC_025L       "Source personal income - child support"
    INC_025M       "Source personal income - alimony"
    INC_025N       "Source personal income - other"
    INC_025O       "Source personal income - none"
    INC_030        "Source personal income - supplement for people with disabilities"
    INC_035        "Personal income - main source"
    INC_041        "Total personal income before taxes - best estimate"
    INCFIMPH       "Household income source flag - (F)"
    INCDVHH        "Total household income - all sources - (D)"
    INCDVPER       "Personal income - all sources - (D)"
    INCDVADR       "Adjusted household income ratio - national level - (D)"
    INCDVRCA       "Distribution of household income ratio - national level - (D)"
    INCDVRPR       "Distribution of household income - provincial level - (D)"
    INCDVRRS       "Distribution of household income - health region level - (D)"
    WTS_M          "Weights - Master"
    WTS_S          "Weights - Share"
    .
 
