INFILE &datafid LRECL = 1448;
INPUT
    @    1   SAMPLEID                             $ 20.      
    @   21   PERSONID                                2.      
    @   23   GEOC_PRV                                2.      
    @   25   GEOCDHR4                                4.      
    @   29   GEOCDSHR                                2.      
    @   31   GEOCDON                                 4.      
    @   35   GEOCDDA                                 8.      
    @   43   GEOCDFED                                5.      
    @   48   GEOCDCSD                                7.      
    @   55   GEOCDCD                                 4.      
    @   59   GEOCDSAT                                1.      
    @   60   GEOCDCMA                                3.      
    @   63   GEOCDPRG                                2.      
    @   65   GEOCDEA                                 8.      
    @   73   GEOCDPC                              $  6.      
    @   79   GEOCDUR7                                1.      
    @   80   GEOCDUR2                                1.      
    @   81   SAMC_TYP                                1.      
    @   82   SAMC_CP                              $  6.      
    @   88   SAMCDCP2                             $  6.      
    @   94   SAMCDSHR                             $  1.      
    @   95   SAMCDSJB                             $  1.      
    @   96   SAMCDLNK                             $  1.      
    @   97   ADMC_STA                                2.      
    @   99   ADMC_PRX                                1.      
    @  100   ADMC_YOI                                4.      
    @  104   ADMC_MOI                                2.      
    @  106   ADMC_DOI                                2.      
    @  108   ADMCFQCP                                1.      
    @  109   ADMC_YQI                                4.      
    @  113   ADMC_MQI                                2.      
    @  115   ADMC_DQI                                2.      
    @  117   ADMC_N09                                1.      
    @  118   ADMC_N10                                1.      
    @  119   ADMC_N11                                1.      
    @  120   ADMC_LHH                                1.      
    @  121   ADMC_N12                                2.      
    @  123   DHHC_AGE                                3.      
    @  126   DHHC_YOB                                4.      
    @  130   DHHC_MOB                                2.      
    @  132   DHHC_DOB                                2.      
    @  134   DHHC_SEX                                1.      
    @  135   DHHC_MS                                 2.      
    @  137   GENC_01                                 1.      
    @  138   GENC_02                                 1.      
    @  139   GENC_02A                                1.      
    @  140   GENC_02B                                1.      
    @  141   GENC_07                                 1.      
    @  142   GENC_08                                 1.      
    @  143   GENC_09                                 1.      
    @  144   GENC_10                                 1.      
    @  145   GENCDHDI                                1.      
    @  146   GENCDMHI                                1.      
    @  147   ORGC_1                                  1.      
    @  148   ORGC_2                                  1.      
    @  149   OH1C_20                                 1.      
    @  150   OH1C_21A                                1.      
    @  151   OH1C_21B                                1.      
    @  152   OH1C_21C                                1.      
    @  153   OH1C_22                                 1.      
    @  154   OH1CFCHW                                1.      
    @  155   HWTC_2                                  2.      
    @  157   HWTC_2A                                 2.      
    @  159   HWTC_2B                                 2.      
    @  161   HWTC_2C                                 2.      
    @  163   HWTC_2D                                 2.      
    @  165   HWTC_2E                                 2.      
    @  167   HWTC_2F                                 2.      
    @  169   HWTC_3                                  3.      
    @  172   HWTC_N4                                 1.      
    @  173   HWTC_4                                  1.      
    @  174   HWTCDHTM                                5.3     
    @  179   HWTCDHTI                                2.      
    @  181   HWTCDWTK                                6.2     
    @  187   HWTCDWTP                                3.      
    @  190   HWTCDBMI                                5.1     
    @  195   HWTCDISW                                2.      
    @  197   CCCC_011                                1.      
    @  198   CCCC_021                                1.      
    @  199   CCCC_031                                1.      
    @  200   CCCC_035                                1.      
    @  201   CCCC_036                                1.      
    @  202   CCCC_041                                1.      
    @  203   CCCC_051                                1.      
    @  204   CCCC_05A                                1.      
    @  205   CCCC_061                                1.      
    @  206   CCCC_071                                1.      
    @  207   CCCC_081                                1.      
    @  208   CCCC_91A                                1.      
    @  209   CCCC_91B                                1.      
    @  210   CCCC_101                                1.      
    @  211   CCCC_102                                3.      
    @  214   CCCC_10A                                1.      
    @  215   CCCC_10B                                1.      
    @  216   CCCC_10C                                2.      
    @  218   CCCC_105                                1.      
    @  219   CCCC_111                                1.      
    @  220   CCCC_121                                1.      
    @  221   CCCC_12A                                1.      
    @  222   CCCC_12J                                1.      
    @  223   CCCC_12K                                1.      
    @  224   CCCC_131                                1.      
    @  225   CCCC_13A                                1.      
    @  226   CCCC_13B                                1.      
    @  227   CCCC_13C                                1.      
    @  228   CCCC_13D                                1.      
    @  229   CCCC_13E                                1.      
    @  230   CCCC_13F                                1.      
    @  231   CCCC_141                                1.      
    @  232   CCCC_151                                1.      
    @  233   CCCC_161                                1.      
    @  234   CCCC_171                                1.      
    @  235   CCCC_181                                1.      
    @  236   CCCC_191                                1.      
    @  237   CCCC_201                                1.      
    @  238   CCCC_211                                1.      
    @  239   CCCC_251                                1.      
    @  240   CCCC_261                                1.      
    @  241   CCCC_271                                1.      
    @  242   CCCC_280                                1.      
    @  243   CCCC_290                                1.      
    @  244   CCCC_321                                1.      
    @  245   CCCC_331                                1.      
    @  246   CCCC_33A                                1.      
    @  247   CCCC_33B                                1.      
    @  248   CCCC_33C                                1.      
    @  249   CCCC_33D                                1.      
    @  250   CCCC_341                                1.      
    @  251   CCCC_901                                1.      
    @  252   CCCCF1                                  1.      
    @  253   HCUC_1AA                                1.      
    @  254   HCUC_1BA                                1.      
    @  255   HCUC_1BB                                1.      
    @  256   HCUC_1BC                                1.      
    @  257   HCUC_1BD                                1.      
    @  258   HCUC_1BE                                1.      
    @  259   HCUC_1C                                 2.      
    @  261   HCUC_01                                 1.      
    @  262   HCUC_01A                                3.      
    @  265   HCUC_02A                                3.      
    @  268   HCUC_02B                                2.      
    @  270   HCUC_02C                                3.      
    @  273   HCUC_02D                                3.      
    @  276   HCUC_02E                                3.      
    @  279   HCUC_02F                                3.      
    @  282   HCUC_02G                                3.      
    @  285   HCUC_02H                                3.      
    @  288   HCUC_02I                                3.      
    @  291   HCUC_02J                                3.      
    @  294   HCUC_03A                                2.      
    @  296   HCUC_03C                                2.      
    @  298   HCUC_03D                                2.      
    @  300   HCUC_04A                                1.      
    @  301   HCUC_04                                 1.      
    @  302   HCUC_05A                                1.      
    @  303   HCUC_05B                                1.      
    @  304   HCUC_05C                                1.      
    @  305   HCUC_05D                                1.      
    @  306   HCUC_05E                                1.      
    @  307   HCUC_05F                                1.      
    @  308   HCUC_05G                                1.      
    @  309   HCUC_05H                                1.      
    @  310   HCUC_05I                                1.      
    @  311   HCUC_05J                                1.      
    @  312   HCUC_05K                                1.      
    @  313   HCUC_05L                                1.      
    @  314   HCUC_06                                 1.      
    @  315   HCUC_07A                                1.      
    @  316   HCUC_07B                                1.      
    @  317   HCUC_07C                                1.      
    @  318   HCUC_07D                                1.      
    @  319   HCUC_07E                                1.      
    @  320   HCUC_07F                                1.      
    @  321   HCUC_07G                                1.      
    @  322   HCUC_07H                                1.      
    @  323   HCUC_07I                                1.      
    @  324   HCUC_07J                                1.      
    @  325   HCUC_07K                                1.      
    @  326   HCUC_07L                                1.      
    @  327   HCUC_07M                                1.      
    @  328   HCUC_07O                                1.      
    @  329   HCUC_07P                                1.      
    @  330   HCUC_07N                                1.      
    @  331   HCUC_08A                                1.      
    @  332   HCUC_08B                                1.      
    @  333   HCUC_08C                                1.      
    @  334   HCUC_08D                                1.      
    @  335   HCUC_08E                                1.      
    @  336   HCUC_09A                                1.      
    @  337   HCUC_09B                                1.      
    @  338   HCUC_09C                                1.      
    @  339   HCUC_09D                                1.      
    @  340   HCUC_09E                                1.      
    @  341   HCUC_09F                                1.      
    @  342   HCUC_09G                                1.      
    @  343   HCUC_09H                                1.      
    @  344   HCUCDMDC                                3.      
    @  347   HCUCFCOP                                1.      
    @  348   HMCC_09                                 1.      
    @  349   HMCC_10A                                1.      
    @  350   HMCC_10B                                1.      
    @  351   HMCC_10C                                1.      
    @  352   HMCC_10D                                1.      
    @  353   HMCC_10E                                1.      
    @  354   HMCC_10F                                1.      
    @  355   HMCC_10G                                1.      
    @  356   HMCC_10H                                1.      
    @  357   HMCC_11                                 1.      
    @  358   HMCC_12A                                1.      
    @  359   HMCC_12B                                1.      
    @  360   HMCC_12C                                1.      
    @  361   HMCC_12D                                1.      
    @  362   HMCC_12E                                1.      
    @  363   HMCC_12F                                1.      
    @  364   HMCC_3AA                                1.      
    @  365   HMCC_3AB                                1.      
    @  366   HMCC_3AC                                1.      
    @  367   HMCC_3AD                                1.      
    @  368   HMCC_3AE                                1.      
    @  369   HMCC_3AF                                1.      
    @  370   HMCC_3AG                                1.      
    @  371   HMCC_3AH                                1.      
    @  372   HMCC_3BA                                1.      
    @  373   HMCC_3BB                                1.      
    @  374   HMCC_3BC                                1.      
    @  375   HMCC_3BD                                1.      
    @  376   HMCC_3BE                                1.      
    @  377   HMCC_3BF                                1.      
    @  378   HMCC_3BG                                1.      
    @  379   HMCC_3BH                                1.      
    @  380   HMCC_3CA                                1.      
    @  381   HMCC_3CB                                1.      
    @  382   HMCC_3CC                                1.      
    @  383   HMCC_3CD                                1.      
    @  384   HMCC_3CE                                1.      
    @  385   HMCC_3CF                                1.      
    @  386   HMCC_3CG                                1.      
    @  387   HMCC_3CH                                1.      
    @  388   HMCC_3DA                                1.      
    @  389   HMCC_3DB                                1.      
    @  390   HMCC_3DC                                1.      
    @  391   HMCC_3DD                                1.      
    @  392   HMCC_3DE                                1.      
    @  393   HMCC_3DF                                1.      
    @  394   HMCC_3DG                                1.      
    @  395   HMCC_3DH                                1.      
    @  396   HMCC_3EA                                1.      
    @  397   HMCC_3EB                                1.      
    @  398   HMCC_3EC                                1.      
    @  399   HMCC_3ED                                1.      
    @  400   HMCC_3EE                                1.      
    @  401   HMCC_3EF                                1.      
    @  402   HMCC_3EG                                1.      
    @  403   HMCC_3EH                                1.      
    @  404   HMCC_3FA                                1.      
    @  405   HMCC_3FB                                1.      
    @  406   HMCC_3FC                                1.      
    @  407   HMCC_3FD                                1.      
    @  408   HMCC_3FE                                1.      
    @  409   HMCC_3FF                                1.      
    @  410   HMCC_3FG                                1.      
    @  411   HMCC_3FH                                1.      
    @  412   HMCC_14                                 1.      
    @  413   HMCC_15A                                1.      
    @  414   HMCC_15B                                1.      
    @  415   HMCC_15C                                1.      
    @  416   HMCC_15D                                1.      
    @  417   HMCC_15E                                1.      
    @  418   HMCC_15F                                1.      
    @  419   HMCC_15G                                1.      
    @  420   HMCC_15H                                1.      
    @  421   HMCC_15I                                1.      
    @  422   HMCC_15J                                1.      
    @  423   HMCC_15K                                1.      
    @  424   HMCC_15L                                1.      
    @  425   HMCC_15M                                1.      
    @  426   HMCC_16A                                1.      
    @  427   HMCC_16B                                1.      
    @  428   HMCC_16C                                1.      
    @  429   HMCC_16D                                1.      
    @  430   HMCC_16E                                1.      
    @  431   HMCC_16F                                1.      
    @  432   HMCC_16G                                1.      
    @  433   HMCC_16H                                1.      
    @  434   HMCCFRHC                                1.      
    @  435   RACC_1                                  2.      
    @  437   RACC_2A                                 2.      
    @  439   RACC_2B1                                2.      
    @  441   RACC_2B2                                2.      
    @  443   RACC_2C                                 2.      
    @  445   RACC_5                                  2.      
    @  447   RACC_5B1                                1.      
    @  448   RACC_5B2                                2.      
    @  450   RACC_6A                                 1.      
    @  451   RACC_6B1                                1.      
    @  452   RACC_6C                                 1.      
    @  453   RACC_6D                                 1.      
    @  454   RACC_6E                                 1.      
    @  455   RACC_6F                                 1.      
    @  456   RACC_6G                                 1.      
    @  457   RACC_7A                                 1.      
    @  458   RACC_7B                                 1.      
    @  459   RACC_7C                                 1.      
    @  460   RACC_8A                                 1.      
    @  461   RACC_8B                                 1.      
    @  462   RACC_8C                                 1.      
    @  463   RACC_8D                                 1.      
    @  464   RACCDIMP                                1.      
    @  465   RACCDPAL                                1.      
    @  466   RACCF6R                                 1.      
    @  467   RACCF7                                  1.      
    @  468   TWDC_1                                  1.      
    @  469   TWDC_2                                  2.      
    @  471   TWDC_2A                                 1.      
    @  472   TWDC_2B                                 2.      
    @  474   TWDC_3                                  1.      
    @  475   TWDC_4                                  2.      
    @  477   TWDC_4A                                 1.      
    @  478   TWDC_4B                                 2.      
    @  480   TWDC_5A                                 1.      
    @  481   TWDC_6                                  2.      
    @  483   TWDC_6A                                 1.      
    @  484   TWDC_6B                                 2.      
    @  486   TWDCDDDY                                2.      
    @  488   TWDCDDDM                                2.      
    @  490   TWDCDDDP                                2.      
    @  492   INSC_1                                  1.      
    @  493   INSC_2                                  1.      
    @  494   INSC_3                                  1.      
    @  495   INSC_4                                  1.      
    @  496   FLUC_160                                1.      
    @  497   FLUC_162                                1.      
    @  498   FLUC_66A                                1.      
    @  499   FLUC_66B                                1.      
    @  500   FLUC_66C                                1.      
    @  501   FLUC_66D                                1.      
    @  502   FLUC_66E                                1.      
    @  503   FLUC_66F                                1.      
    @  504   FLUC_66G                                1.      
    @  505   FLUC_66H                                1.      
    @  506   FLUC_66I                                1.      
    @  507   FLUC_66J                                1.      
    @  508   FLUC_66K                                1.      
    @  509   FLUC_66L                                1.      
    @  510   FLUC_66M                                1.      
    @  511   FLUC_66O                                1.      
    @  512   FLUC_66N                                1.      
    @  513   PAPC_020                                1.      
    @  514   PAPC_022                                1.      
    @  515   PAPC_26A                                1.      
    @  516   PAPC_26B                                1.      
    @  517   PAPC_26C                                1.      
    @  518   PAPC_26D                                1.      
    @  519   PAPC_26E                                1.      
    @  520   PAPC_26F                                1.      
    @  521   PAPC_26G                                1.      
    @  522   PAPC_26H                                1.      
    @  523   PAPC_26I                                1.      
    @  524   PAPC_26J                                1.      
    @  525   PAPC_26K                                1.      
    @  526   PAPC_26L                                1.      
    @  527   PAPC_26M                                1.      
    @  528   PAPC_26N                                1.      
    @  529   PAPC_26P                                1.      
    @  530   PAPC_26O                                1.      
    @  531   MAMC_030                                1.      
    @  532   MAMC_31A                                1.      
    @  533   MAMC_31B                                1.      
    @  534   MAMC_31C                                1.      
    @  535   MAMC_31D                                1.      
    @  536   MAMC_31E                                1.      
    @  537   MAMC_31F                                1.      
    @  538   MAMC_31G                                1.      
    @  539   MAMC_31H                                1.      
    @  540   MAMC_032                                1.      
    @  541   MAMC_36A                                1.      
    @  542   MAMC_36B                                1.      
    @  543   MAMC_36C                                1.      
    @  544   MAMC_36D                                1.      
    @  545   MAMC_36E                                1.      
    @  546   MAMC_36F                                1.      
    @  547   MAMC_36G                                1.      
    @  548   MAMC_36H                                1.      
    @  549   MAMC_36I                                1.      
    @  550   MAMC_36J                                1.      
    @  551   MAMC_36K                                1.      
    @  552   MAMC_36L                                1.      
    @  553   MAMC_36N                                1.      
    @  554   MAMC_36M                                1.      
    @  555   MAMC_037                                1.      
    @  556   MAMC_038                                1.      
    @  557   FVCC_1A                                 1.      
    @  558   FVCC_1B                                 2.      
    @  560   FVCC_1C                                 2.      
    @  562   FVCC_1D                                 3.      
    @  565   FVCC_1E                                 3.      
    @  568   FVCC_2A                                 1.      
    @  569   FVCC_2B                                 2.      
    @  571   FVCC_2C                                 2.      
    @  573   FVCC_2D                                 3.      
    @  576   FVCC_2E                                 3.      
    @  579   FVCC_3A                                 1.      
    @  580   FVCC_3B                                 2.      
    @  582   FVCC_3C                                 2.      
    @  584   FVCC_3D                                 3.      
    @  587   FVCC_3E                                 3.      
    @  590   FVCC_4A                                 1.      
    @  591   FVCC_4B                                 2.      
    @  593   FVCC_4C                                 2.      
    @  595   FVCC_4D                                 3.      
    @  598   FVCC_4E                                 3.      
    @  601   FVCC_5A                                 1.      
    @  602   FVCC_5B                                 2.      
    @  604   FVCC_5C                                 2.      
    @  606   FVCC_5D                                 3.      
    @  609   FVCC_5E                                 3.      
    @  612   FVCC_6A                                 1.      
    @  613   FVCC_6B                                 2.      
    @  615   FVCC_6C                                 2.      
    @  617   FVCC_6D                                 3.      
    @  620   FVCC_6E                                 3.      
    @  623   FVCCDJUI                                5.1     
    @  628   FVCCDFRU                                5.1     
    @  633   FVCCDSAL                                5.1     
    @  638   FVCCDPOT                                5.1     
    @  643   FVCCDCAR                                5.1     
    @  648   FVCCDVEG                                5.1     
    @  653   FVCCDTOT                                5.1     
    @  658   FVCCGTOT                                1.      
    @  659   PACC_1A                                 1.      
    @  660   PACC_1B                                 1.      
    @  661   PACC_1C                                 1.      
    @  662   PACC_1D                                 1.      
    @  663   PACC_1E                                 1.      
    @  664   PACC_1F                                 1.      
    @  665   PACC_1G                                 1.      
    @  666   PACC_1H                                 1.      
    @  667   PACC_1I                                 1.      
    @  668   PACC_1J                                 1.      
    @  669   PACC_1K                                 1.      
    @  670   PACC_1L                                 1.      
    @  671   PACC_1M                                 1.      
    @  672   PACC_1N                                 1.      
    @  673   PACC_1O                                 1.      
    @  674   PACC_1P                                 1.      
    @  675   PACC_1Q                                 1.      
    @  676   PACC_1R                                 1.      
    @  677   PACC_1S                                 1.      
    @  678   PACC_1T                                 1.      
    @  679   PACC_1Z                                 1.      
    @  680   PACC_1U                                 1.      
    @  681   PACC_1V                                 1.      
    @  682   PACC_1W                                 1.      
    @  683   PACC_1X                                 1.      
    @  684   PACC_2A                                 3.      
    @  687   PACC_3A                                 1.      
    @  688   PACC_2B                                 3.      
    @  691   PACC_3B                                 1.      
    @  692   PACC_2C                                 3.      
    @  695   PACC_3C                                 1.      
    @  696   PACC_2D                                 3.      
    @  699   PACC_3D                                 1.      
    @  700   PACC_2E                                 3.      
    @  703   PACC_3E                                 1.      
    @  704   PACC_2F                                 3.      
    @  707   PACC_3F                                 1.      
    @  708   PACC_2G                                 3.      
    @  711   PACC_3G                                 1.      
    @  712   PACC_2H                                 3.      
    @  715   PACC_3H                                 1.      
    @  716   PACC_2I                                 3.      
    @  719   PACC_3I                                 1.      
    @  720   PACC_2J                                 3.      
    @  723   PACC_3J                                 1.      
    @  724   PACC_2K                                 3.      
    @  727   PACC_3K                                 1.      
    @  728   PACC_2L                                 3.      
    @  731   PACC_3L                                 1.      
    @  732   PACC_2M                                 3.      
    @  735   PACC_3M                                 1.      
    @  736   PACC_2N                                 3.      
    @  739   PACC_3N                                 1.      
    @  740   PACC_2O                                 3.      
    @  743   PACC_3O                                 1.      
    @  744   PACC_2P                                 3.      
    @  747   PACC_3P                                 1.      
    @  748   PACC_2Q                                 3.      
    @  751   PACC_3Q                                 1.      
    @  752   PACC_2R                                 3.      
    @  755   PACC_3R                                 1.      
    @  756   PACC_2S                                 3.      
    @  759   PACC_3S                                 1.      
    @  760   PACC_2T                                 3.      
    @  763   PACC_3T                                 1.      
    @  764   PACC_2Z                                 3.      
    @  767   PACC_3Z                                 1.      
    @  768   PACC_2U                                 3.      
    @  771   PACC_3U                                 1.      
    @  772   PACC_2W                                 3.      
    @  775   PACC_3W                                 1.      
    @  776   PACC_2X                                 3.      
    @  779   PACC_3X                                 1.      
    @  780   PACC_4A                                 2.      
    @  782   PACC_4B                                 2.      
    @  784   PACC_6                                  1.      
    @  785   PACCDEE                                 4.1     
    @  789   PACCFLEI                                1.      
    @  790   PACCDFM                                 3.      
    @  793   PACCDFR                                 1.      
    @  794   PACCFD                                  1.      
    @  795   PACCDPAI                                1.      
    @  796   REPC_1                                  1.      
    @  797   REPC_3                                  2.      
    @  799   REPC_4A                                 1.      
    @  800   REPC_4B                                 1.      
    @  801   REPC_4C                                 1.      
    @  802   REPC_4G                                 1.      
    @  803   REPC_4D                                 1.      
    @  804   REPC_4E                                 1.      
    @  805   REPC_4F                                 1.      
    @  806   INJC_01                                 1.      
    @  807   INJC_02                                 2.      
    @  809   INJC_03                                 2.      
    @  811   INJC_04                                 1.      
    @  812   INJC_05                                 2.      
    @  814   INJC_06                                 2.      
    @  816   INJC_07                                 1.      
    @  817   INJC_08                                 2.      
    @  819   INJC_09                                 2.      
    @  821   INJC_10                                 1.      
    @  822   INJC_11                                 2.      
    @  824   INJC_12                                 2.      
    @  826   INJC_13                                 1.      
    @  827   INJC_14A                                1.      
    @  828   INJC_14B                                1.      
    @  829   INJC_14C                                1.      
    @  830   INJC_14D                                1.      
    @  831   INJC_14E                                1.      
    @  832   INJC_14F                                1.      
    @  833   INJC_14G                                1.      
    @  834   INJC_14H                                1.      
    @  835   INJC_14I                                1.      
    @  836   INJC_14J                                1.      
    @  837   INJC_14K                                1.      
    @  838   INJC_15                                 1.      
    @  839   INJC_16                                 1.      
    @  840   INJC_17                                 2.      
    @  842   INJCDTBS                                4.      
    @  846   INJCDCAU                                2.      
    @  848   INJCDCBP                                4.      
    @  852   INJCDSTT                                1.      
    @  853   SMKC_01A                                1.      
    @  854   SMKC_01B                                1.      
    @  855   SMKC_01C                                3.      
    @  858   SMKC_202                                1.      
    @  859   SMKC_203                                3.      
    @  862   SMKC_204                                3.      
    @  865   SMKC_05B                                3.      
    @  868   SMKC_05C                                2.      
    @  870   SMKC_05D                                1.      
    @  871   SMKC_06A                                1.      
    @  872   SMKC_06B                                2.      
    @  874   SMKC_06C                                3.      
    @  877   SMKC_207                                3.      
    @  880   SMKC_208                                3.      
    @  883   SMKC_09A                                1.      
    @  884   SMKC_09B                                2.      
    @  886   SMKC_09C                                3.      
    @  889   SMKC_10                                 1.      
    @  890   SMKC_10A                                1.      
    @  891   SMKC_10B                                2.      
    @  893   SMKC_10C                                3.      
    @  896   SMKCDSTY                                2.      
    @  898   SMKCDSTP                                3.      
    @  901   SMKCDYCS                                3.      
    @  904   YSMC_1                                  2.      
    @  906   YSMC_2                                  1.      
    @  907   YSMC_3                                  1.      
    @  908   YSMC_4                                  1.      
    @  909   YSMC_5                                  1.      
    @  910   ETSC_10                                 1.      
    @  911   ETSC_11                                 2.      
    @  913   ETSC_20                                 1.      
    @  914   ETSC_20B                                1.      
    @  915   ETSC_5                                  1.      
    @  916   ETSC_6A                                 1.      
    @  917   ETSC_6B                                 1.      
    @  918   ETSC_6C                                 1.      
    @  919   ETSC_6D                                 1.      
    @  920   ALCC_1                                  1.      
    @  921   ALCC_2                                  2.      
    @  923   ALCC_3                                  2.      
    @  925   ALCC_5                                  1.      
    @  926   ALCC_5A1                                3.      
    @  929   ALCC_5A2                                3.      
    @  932   ALCC_5A3                                3.      
    @  935   ALCC_5A4                                3.      
    @  938   ALCC_5A5                                3.      
    @  941   ALCC_5A6                                3.      
    @  944   ALCC_5A7                                3.      
    @  947   ALCC_5B                                 1.      
    @  948   ALCC_6                                  1.      
    @  949   ALCC_7A                                 1.      
    @  950   ALCC_7B                                 1.      
    @  951   ALCC_7C                                 1.      
    @  952   ALCC_7D                                 1.      
    @  953   ALCC_7E                                 1.      
    @  954   ALCC_7F                                 1.      
    @  955   ALCC_7G                                 1.      
    @  956   ALCC_7H                                 1.      
    @  957   ALCC_7I                                 1.      
    @  958   ALCC_7J                                 1.      
    @  959   ALCC_7K                                 1.      
    @  960   ALCC_7L                                 1.      
    @  961   ALCC_7M                                 1.      
    @  962   ALCC_8                                  3.      
    @  965   ALCCDTYP                                1.      
    @  966   ALCCDWKY                                3.      
    @  969   ALCCDDLY                                3.      
    @  972   MEXC_01                                 1.      
    @  973   MEXC_01A                                4.      
    @  977   MEXC_02                                 1.      
    @  978   MEXC_03                                 1.      
    @  979   MEXC_04                                 2.      
    @  981   MEXC_05                                 1.      
    @  982   MEXC_06                                 2.      
    @  984   MEXC_07                                 2.      
    @  986   MEXC_08                                 2.      
    @  988   MEXC_09                                 1.      
    @  989   MEXC_10                                 2.      
    @  991   MEXC_20                                 1.      
    @  992   MEXC_21                                 3.      
    @  995   MEXC_22                                 3.      
    @  998   MEXC_23                                 1.      
    @  999   MEXC_24                                 3.      
    @ 1002   MEXC_25                                 3.      
    @ 1005   MEXC_26                                 1.      
    @ 1006   MEXC_30                                 1.      
    @ 1007   MEXC_31                                 2.      
    @ 1009   MEXC_32                                 1.      
    @ 1010   MEXC_33                                 2.      
    @ 1012   MEXCDEBF                                2.      
    @ 1014   MEXCFEB4                                1.      
    @ 1015   SXBC_1                                  1.      
    @ 1016   SXBC_2                                  3.      
    @ 1019   SXBC_3                                  1.      
    @ 1020   SXBC_4                                  1.      
    @ 1021   SXBC_07                                 1.      
    @ 1022   SXBC_7A                                 1.      
    @ 1023   SXBC_09                                 1.      
    @ 1024   SXBC_10                                 2.      
    @ 1026   SXBC_11                                 1.      
    @ 1027   SXBC_12A                                1.      
    @ 1028   SXBC_12B                                1.      
    @ 1029   SXBC_12C                                1.      
    @ 1030   SXBC_12D                                1.      
    @ 1031   SXBC_12E                                1.      
    @ 1032   SXBC_12F                                1.      
    @ 1033   SXBC_13A                                1.      
    @ 1034   SXBC_13B                                1.      
    @ 1035   SXBC_13C                                1.      
    @ 1036   SXBC_13D                                1.      
    @ 1037   SXBC_13E                                1.      
    @ 1038   SXBC_13F                                1.      
    @ 1039   SDCC_1                                  2.      
    @ 1041   SDCC_2                                  1.      
    @ 1042   SDCC_3                                  4.      
    @ 1046   SDCC_4A                                 1.      
    @ 1047   SDCC_4B                                 1.      
    @ 1048   SDCC_4C                                 1.      
    @ 1049   SDCC_4D                                 1.      
    @ 1050   SDCC_4E                                 1.      
    @ 1051   SDCC_4F                                 1.      
    @ 1052   SDCC_4G                                 1.      
    @ 1053   SDCC_4H                                 1.      
    @ 1054   SDCC_4I                                 1.      
    @ 1055   SDCC_4J                                 1.      
    @ 1056   SDCC_4K                                 1.      
    @ 1057   SDCC_4L                                 1.      
    @ 1058   SDCC_4M                                 1.      
    @ 1059   SDCC_4N                                 1.      
    @ 1060   SDCC_4T                                 1.      
    @ 1061   SDCC_4U                                 1.      
    @ 1062   SDCC_4V                                 1.      
    @ 1063   SDCC_4W                                 1.      
    @ 1064   SDCC_4S                                 1.      
    @ 1065   SDCC_5A                                 1.      
    @ 1066   SDCC_5B                                 1.      
    @ 1067   SDCC_5C                                 1.      
    @ 1068   SDCC_5D                                 1.      
    @ 1069   SDCC_5E                                 1.      
    @ 1070   SDCC_5F                                 1.      
    @ 1071   SDCC_5G                                 1.      
    @ 1072   SDCC_5H                                 1.      
    @ 1073   SDCC_5I                                 1.      
    @ 1074   SDCC_5J                                 1.      
    @ 1075   SDCC_5K                                 1.      
    @ 1076   SDCC_5L                                 1.      
    @ 1077   SDCC_5M                                 1.      
    @ 1078   SDCC_5N                                 1.      
    @ 1079   SDCC_5O                                 1.      
    @ 1080   SDCC_5P                                 1.      
    @ 1081   SDCC_5Q                                 1.      
    @ 1082   SDCC_5R                                 1.      
    @ 1083   SDCC_5T                                 1.      
    @ 1084   SDCC_5U                                 1.      
    @ 1085   SDCC_5V                                 1.      
    @ 1086   SDCC_5W                                 1.      
    @ 1087   SDCC_5S                                 1.      
    @ 1088   SDCC_5AA                                2.      
    @ 1090   SDCC_6A                                 1.      
    @ 1091   SDCC_6B                                 1.      
    @ 1092   SDCC_6C                                 1.      
    @ 1093   SDCC_6D                                 1.      
    @ 1094   SDCC_6E                                 1.      
    @ 1095   SDCC_6F                                 1.      
    @ 1096   SDCC_6G                                 1.      
    @ 1097   SDCC_6H                                 1.      
    @ 1098   SDCC_6I                                 1.      
    @ 1099   SDCC_6J                                 1.      
    @ 1100   SDCC_6K                                 1.      
    @ 1101   SDCC_6L                                 1.      
    @ 1102   SDCC_6M                                 1.      
    @ 1103   SDCC_6N                                 1.      
    @ 1104   SDCC_6O                                 1.      
    @ 1105   SDCC_6P                                 1.      
    @ 1106   SDCC_6Q                                 1.      
    @ 1107   SDCC_6R                                 1.      
    @ 1108   SDCC_6T                                 1.      
    @ 1109   SDCC_6U                                 1.      
    @ 1110   SDCC_6V                                 1.      
    @ 1111   SDCC_6W                                 1.      
    @ 1112   SDCC_6S                                 1.      
    @ 1113   SDCC_7A                                 1.      
    @ 1114   SDCC_7B                                 1.      
    @ 1115   SDCC_7C                                 1.      
    @ 1116   SDCC_7D                                 1.      
    @ 1117   SDCC_7E                                 1.      
    @ 1118   SDCC_7F                                 1.      
    @ 1119   SDCC_7G                                 1.      
    @ 1120   SDCC_7H                                 1.      
    @ 1121   SDCC_7I                                 1.      
    @ 1122   SDCC_7J                                 1.      
    @ 1123   SDCC_7K                                 1.      
    @ 1124   SDCC_7L                                 1.      
    @ 1125   SDCC_7M                                 1.      
    @ 1126   SDCC_7AA                                1.      
    @ 1127   SDCC_8                                  1.      
    @ 1128   SDCC_9                                  1.      
    @ 1129   SDCC_10                                 1.      
    @ 1130   SDCC_11A                                1.      
    @ 1131   SDCC_11B                                1.      
    @ 1132   SDCC_12A                                1.      
    @ 1133   SDCC_12B                                1.      
    @ 1134   SDCC_13                                 1.      
    @ 1135   SDCC_14A                                1.      
    @ 1136   SDCC_14B                                1.      
    @ 1137   SDCC_14C                                1.      
    @ 1138   SDCCCCB                                 3.      
    @ 1141   SDCCGCB                                 2.      
    @ 1143   SDCCDAIM                                3.      
    @ 1146   SDCCFIMM                                1.      
    @ 1147   SDCCDRES                                3.      
    @ 1150   SDCCDLNG                                2.      
    @ 1152   SDCCDRAC                                2.      
    @ 1154   SDCCDFL1                                2.      
    @ 1156   EDUC_1                                  1.      
    @ 1157   EDUC_2                                  1.      
    @ 1158   EDUC_3                                  1.      
    @ 1159   EDUC_4                                  2.      
    @ 1161   EDUCDR10                                2.      
    @ 1163   EDUCDR04                                1.      
    @ 1164   EDUCDH10                                2.      
    @ 1166   EDUCDH04                                1.      
    @ 1167   DHHCDHSZ                                2.      
    @ 1169   DHHCDL12                                2.      
    @ 1171   DHHCDLE5                                2.      
    @ 1173   DHHCD611                                2.      
    @ 1175   DHHCDECF                                2.      
    @ 1177   DHHCDLVG                                2.      
    @ 1179   DHHCDDWE                                2.      
    @ 1181   DHHC_OWN                                1.      
    @ 1182   DHHC_BED                                2.      
    @ 1184   LBFC_01                                 1.      
    @ 1185   LBFC_02                                 1.      
    @ 1186   LBFC_03                                 1.      
    @ 1187   LBFC_11                                 1.      
    @ 1188   LBFC_13                                 2.      
    @ 1190   LBFC_13A                                1.      
    @ 1191   LBFC_21                                 1.      
    @ 1192   LBFC_22                                 1.      
    @ 1193   LBFC_23                                 1.      
    @ 1194   LBFC_31                                 1.      
    @ 1195   LBFCF32                                 1.      
    @ 1196   LBFCF33                                 1.      
    @ 1197   LBFCF34                                 1.      
    @ 1198   LBFCF35                                 1.      
    @ 1199   LBFCF35S                                1.      
    @ 1200   LBFCF36                                 1.      
    @ 1201   LBFCCNIC                             $  5.      
    @ 1206   LBFCCSOC                             $  4.      
    @ 1210   ETSC_7                                  1.      
    @ 1211   LBFC_41                                 2.      
    @ 1213   LBFC_41A                                1.      
    @ 1214   LBFC_42                                 3.      
    @ 1217   LBFC_44                                 2.      
    @ 1219   LBFC_45                                 2.      
    @ 1221   LBFC_46                                 1.      
    @ 1222   LBFC_51                                 2.      
    @ 1224   LBFC_52                                 2.      
    @ 1226   LBFC_53                                 3.      
    @ 1229   LBFC_54                                 1.      
    @ 1230   LBFC_61                                 2.      
    @ 1232   LBFC_71                                 2.      
    @ 1234   LBFC_72                                 1.      
    @ 1235   LBFC_73                                 2.      
    @ 1237   LBFC_73A                                1.      
    @ 1238   LBFCDWSS                                1.      
    @ 1239   LBFCDWSL                                2.      
    @ 1241   LBFCDRNW                                2.      
    @ 1243   LBFCDMJS                                1.      
    @ 1244   LBFCDHPW                                3.      
    @ 1247   LBFCDPFT                                1.      
    @ 1248   LBFCDJST                                2.      
    @ 1250   LBFCDSTU                                1.      
    @ 1251   INCC_1A                                 1.      
    @ 1252   INCC_1B                                 1.      
    @ 1253   INCC_1C                                 1.      
    @ 1254   INCC_1D                                 1.      
    @ 1255   INCC_1E                                 1.      
    @ 1256   INCC_1F                                 1.      
    @ 1257   INCC_1G                                 1.      
    @ 1258   INCC_1H                                 1.      
    @ 1259   INCC_1I                                 1.      
    @ 1260   INCC_1J                                 1.      
    @ 1261   INCC_1K                                 1.      
    @ 1262   INCC_1L                                 1.      
    @ 1263   INCC_1M                                 1.      
    @ 1264   INCC_1N                                 1.      
    @ 1265   INCC_2                                  2.      
    @ 1267   INCC_3                                  6.      
    @ 1273   INCC_3A                                 1.      
    @ 1274   INCC_3B                                 1.      
    @ 1275   INCC_3C                                 1.      
    @ 1276   INCC_3D                                 1.      
    @ 1277   INCC_3E                                 1.      
    @ 1278   INCC_3F                                 1.      
    @ 1279   INCC_3G                                 1.      
    @ 1280   INCC_4                                  6.      
    @ 1286   INCC_4A                                 1.      
    @ 1287   INCC_4B                                 1.      
    @ 1288   INCC_4C                                 1.      
    @ 1289   INCC_4D                                 1.      
    @ 1290   INCC_4E                                 1.      
    @ 1291   INCC_4F                                 1.      
    @ 1292   INCC_4G                                 1.      
    @ 1293   INCCDIA2                                1.      
    @ 1294   INCCDIA4                                1.      
    @ 1295   INCCDIA5                                1.      
    @ 1296   INCCDHH                                 2.      
    @ 1298   INCCDPER                                2.      
    @ 1300   NUSC_1                                  1.      
    @ 1301   NUSC_2                                  2.      
    @ 1303   NUSC_3                                  2.      
    @ 1305   NUSC_4                                  1.      
    @ 1306   NUSC_5                                  1.      
    @ 1307   NUSC_6                                  1.      
    @ 1308   NUSC_7                                  1.      
    @ 1309   NUSC_8A                                 1.      
    @ 1310   NUSC_8B                                 2.      
    @ 1312   NUSC_8C                                 2.      
    @ 1314   NUSC_8D                                 2.      
    @ 1316   WTSCFSS1                                1.      
    @ 1317   DENZ_130                                1.      
    @ 1318   DENZ_132                                2.      
    @ 1320   DENZ_36A                                1.      
    @ 1321   DENZ_36B                                1.      
    @ 1322   DENZ_36C                                1.      
    @ 1323   DENZ_36D                                1.      
    @ 1324   DENZ_36E                                1.      
    @ 1325   DENZ_36F                                1.      
    @ 1326   DENZ_36G                                1.      
    @ 1327   DENZ_36H                                1.      
    @ 1328   DENZ_36I                                1.      
    @ 1329   DENZ_36J                                1.      
    @ 1330   DENZ_36K                                1.      
    @ 1331   DENZ_36L                                1.      
    @ 1332   DENZ_36M                                1.      
    @ 1333   DENZ_36O                                1.      
    @ 1334   DENZ_36N                                1.      
    @ 1335   OH2Z_10                                 1.      
    @ 1336   OH2Z_11                                 1.      
    @ 1337   OH2Z_12                                 1.      
    @ 1338   OH2Z_13                                 1.      
    @ 1339   OH2Z_20                                 1.      
    @ 1340   OH2Z_21                                 1.      
    @ 1341   OH2Z_22                                 1.      
    @ 1342   OH2Z_23                                 1.      
    @ 1343   OH2Z_24                                 1.      
    @ 1344   OH2Z_25A                                1.      
    @ 1345   OH2Z_25B                                1.      
    @ 1346   OH2Z_25C                                1.      
    @ 1347   OH2Z_25D                                1.      
    @ 1348   OH2Z_25E                                1.      
    @ 1349   OH2Z_25F                                1.      
    @ 1350   OH2Z_25G                                1.      
    @ 1351   OH2Z_30                                 2.      
    @ 1353   OH2ZFLIM                                1.      
    @ 1354   OH2ZFOFP                                1.      
    @ 1355   HUIZ_01                                 1.      
    @ 1356   HUIZ_02                                 1.      
    @ 1357   HUIZ_03                                 1.      
    @ 1358   HUIZ_04                                 1.      
    @ 1359   HUIZ_05                                 1.      
    @ 1360   HUIZ_06                                 1.      
    @ 1361   HUIZ_07                                 1.      
    @ 1362   HUIZ_07A                                1.      
    @ 1363   HUIZ_08                                 1.      
    @ 1364   HUIZ_09                                 1.      
    @ 1365   HUIZ_10                                 1.      
    @ 1366   HUIZ_11                                 1.      
    @ 1367   HUIZ_12                                 1.      
    @ 1368   HUIZ_13                                 1.      
    @ 1369   HUIZ_14                                 1.      
    @ 1370   HUIZ_15                                 1.      
    @ 1371   HUIZ_16                                 1.      
    @ 1372   HUIZ_17                                 1.      
    @ 1373   HUIZ_18                                 1.      
    @ 1374   HUIZ_19                                 1.      
    @ 1375   HUIZ_20                                 1.      
    @ 1376   HUIZ_21                                 1.      
    @ 1377   HUIZ_22                                 1.      
    @ 1378   HUIZ_23                                 1.      
    @ 1379   HUIZ_24                                 1.      
    @ 1380   HUIZ_25                                 1.      
    @ 1381   HUIZ_26                                 1.      
    @ 1382   HUIZ_27                                 1.      
    @ 1383   HUIZ_28                                 1.      
    @ 1384   HUIZ_29                                 1.      
    @ 1385   HUIZ_30                                 1.      
    @ 1386   HUIZDVIS                                2.      
    @ 1388   HUIZDHER                                2.      
    @ 1390   HUIZDSPE                                1.      
    @ 1391   HUIZDMOB                                2.      
    @ 1393   HUIZDDEX                                2.      
    @ 1395   HUIZDEMO                                1.      
    @ 1396   HUIZDCOG                                2.      
    @ 1398   HUIZDPAD                                1.      
    @ 1399   HUIZDHSI                                6.3     
    @ 1405   MEDZ_1A                                 1.      
    @ 1406   MEDZ_1B                                 1.      
    @ 1407   MEDZ_1C                                 1.      
    @ 1408   MEDZ_1D                                 1.      
    @ 1409   MEDZ_1E                                 1.      
    @ 1410   MEDZ_1F                                 1.      
    @ 1411   MEDZ_1G                                 1.      
    @ 1412   MEDZ_1H                                 1.      
    @ 1413   MEDZ_1I                                 1.      
    @ 1414   MEDZ_1J                                 1.      
    @ 1415   MEDZ_1K                                 1.      
    @ 1416   MEDZ_1L                                 1.      
    @ 1417   MEDZ_1M                                 1.      
    @ 1418   MEDZ_1N                                 1.      
    @ 1419   MEDZ_1O                                 1.      
    @ 1420   MEDZ_1P                                 1.      
    @ 1421   MEDZ_1Q                                 1.      
    @ 1422   MEDZ_1R                                 1.      
    @ 1423   MEDZ_1S                                 1.      
    @ 1424   MEDZ_1T                                 1.      
    @ 1425   MEDZ_1T1                                1.      
    @ 1426   MEDZ_1T2                                4.      
    @ 1430   MEDZ_1U                                 1.      
    @ 1431   MEDZ_1V                                 1.      
    @ 1432   MEDZF1                                  1.      
    @ 1433   WTSC_S1S                                8.2     
    @ 1441   WTSC_S1M                                8.2     
         ;
